### ISSUE TITLE
Trying to import an ActiveEffect from JSON is unsupported, but does not throw an informative error

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10009]
### What happened?

In the console, attempting to run `ActiveEffect.prototype.importFromJSONDialog` will throw an error after the JSON file is selected. The reason appears to be that `CONFIG.ActiveEffect` does not have a `collection`. I have not tested beyond this point, however, so I don't know if providing a collection would suffice. There is no `ActiveEffects` class, and to my knowledge, active effects cannot be currently stored alone in a compendium, so I don't know if there is an easy work-around here.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

In the console, run:

```js
ae = new ActiveEffect({ name: "Test" });
ae.exportToJSON();  // So we have something to import.
await ae.importFromJSONDialog(); // Choose the json file in the Foundry dialog, at which point it will throw an error.
```

### What core version are you reporting this for?

v11.308

### Relevant log output

```shell
foundry.js:13952 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'instance')
    at get collection [as collection] (foundry.js:13952:56)
    at ActiveEffect.importFromJSON (foundry.js:14694:25)
    at foundry.js:14730:70
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
The `importFromJSON` workflow is only designed to be used for primary documents. `ActiveEffect` is only supported as an embedded Document and so is incompatible with this API as designed. We should make sure - at the very least - that the thrown error message is informative to that effect.
