### ISSUE TITLE
PDF Viewing via Journals

### ISSUE THREAD

**Issue by WickedZen** [foundryvtt/foundryvtt#10000]
### User Experience

I am a new Foundry user. I provide some things for my players through  Journals in the PDF format. I am having an issue in normal and popout mode. 

I can adjust the Journal window as much as I want horizontally (width) and this will adjust the PDF window and the pdf at the same time.

However, when adjusting the Journal window vertically (length), the PDF itself will expand but the PDF window does not, causing the players to have a small view of the PDF and have to do a lot of scrolling. Is there a way to adjust the PDF window or make it so that automatically sizes to fit the page?
 (Clicking the fit the page option within the journal just  makes the pdf small to view the PDF window).

Just to reiterate, It will resize the journal window, pdf window and the pdf width wise, but vertifically it will only adjust the Journal window and the PDF but not the PDF window. And I have tried it with all modules disabled. I have tried it via the program as the gamemaster and via Chrome as a player.

![Popout View](https://github.com/foundryvtt/foundryvtt/assets/39884245/a264231e-683f-436a-9094-fbff7d98e8e1)
![Expanded Popout View](https://github.com/foundryvtt/foundryvtt/assets/39884245/5e6b027e-5b1d-44bb-a232-ffb530f66508)
![Expanded View](https://github.com/foundryvtt/foundryvtt/assets/39884245/444275d9-71aa-4db3-8a4e-023a8da6f900)
![Normal View](https://github.com/foundryvtt/foundryvtt/assets/39884245/bfd00553-84c5-4827-a827-847b4ea09f2d)

**Comment by WickedZen** [comment]
Here are pics with no modules active.

![Expanded View No Mods](https://github.com/foundryvtt/foundryvtt/assets/39884245/d5a94922-5497-4e24-a1ba-c7d8d386aaf8)
![Normal View No Mods](https://github.com/foundryvtt/foundryvtt/assets/39884245/b420d24c-6370-4a1f-afe9-af9251e38dfd)

**Comment by WickedZen** [comment]
With the help from someone on Discord I discovered this is likely an issue with the game system I am using,

I installed D&D 5E and created a new world and added the same journal and it adjusted both width and length fine.

**Comment by aaclayton** [comment]
Issue 10,000!

**Comment by WickedZen** [comment]
It has been suggested that it still might be a good feature to have the option to have a page control interface in the journal itself, which I think would be good. So I guess I will leave it open and see if that is something that will be considered.

Thank you everyone.

**Comment by WickedZen** [comment]
I apologize. I have been going back and forth. The person helping in
discord suggested I close the issue, which I did, but then the person
helping me via the customer support email suggested it still might be a
good feature so I reopened it. SO if it should be closed can you go ahead
and close it. Apologies again, thank you.
