### ISSUE TITLE
Generic span.reference styling in v11 is interfering stylings

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#10015]
### What happened?

v11 at some point added super generic `span.reference` style that is adding rather comprehensive styling to very generic element.

Please make the Foundry's selector more specific so it does not so easily apply to everything that uses basic english in much more specific selector chains.

Here for example my own selector and the stylings above and Foundry's generic selector below and what they're affecting:  
![annoying-styling](https://github.com/foundryvtt/foundryvtt/assets/8120158/1b78ec8a-e4cb-4012-a58c-397aa7c3b08a)

I have no idea what this Foundry's styling is even supposed to be for based on the selector.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Use `.reference`  in `<span>` in your HTML anywhere.

### What core version are you reporting this for?

11.308

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Our core software does use some fairly generic rules for certain things where we want to standardize behavior universally. I think it's within our rights to use a `span.reference` tag and it would be the responsibility of packages to either not use the `.reference` class on a span element, or to style `span.mymodule.reference` with greater specificity that reverts any core rules. Sorry, but we have to design CSS for ourselves first and foremost.

**Comment by mkahvi** [comment]
Problem with the recommendation to revert core rules is that CSS is not part of your public API, so we have no guarantees that our reverted rules will remain effective whenever Foundry's styles randomly change.

**Comment by aaclayton** [comment]
> Problem with the recommendation to revert core rules is that CSS is not part of your public API, so we have no guarantees that our reverted rules will remain effective whenever Foundry's styles randomly change.

Yes, that is correct.

We try not to change CSS rules recklessly, but they will change from time to time. This is a cost that we knowingly - albeit reluctantly - pass on to our developer community.
