### ISSUE TITLE
Provide example documentation of how to use CompendiumCollection#getDocuments to retrieve a subset of documents using the query parameter.

### ISSUE THREAD

**Issue by BoltsJ** [foundryvtt/foundryvtt#10022]
### User Experience

In order to allow the retrieval or more than on document at a time from compendium collections, it would be nice to have a getManyDocuments method that takes an array of document ids to retrieve and returns an array of matched documents, essentially exposing the [getMany()](https://github.com/ernieayala/ernies-modern-layout/releases/download/0.5.7/module.json) method from `classic-level`

Currently the only ways to retrieve multiple documents is to either retrieve every compendium document or to retrieve them individually in a loop. While the loop retrieval can be parallelized, it would still be nice to have a batch method.

**Comment by aaclayton** [comment]
This is already supported via the query syntax used in `getDocuments`:
```js
await pack.getDocuments({_id__in: arrayOfIDs});
```

**Comment by BoltsJ** [comment]
Is there documentation for the query syntax anywhere? Last time I asked about it, which was when nedb was still the db, I was told that modules and systems shouldn't be using the query parameter.

**Comment by aaclayton** [comment]
It's mentioned in <https://github.com/foundryvtt/foundryvtt/issues/5065>, but documentation here is lacking. I'll reopen this issue as a documentation one to add some example usages to `CompendiumCollection#getDocuments`
