### ISSUE TITLE
Assistant GM lacks permission to rename players (V10)

### ISSUE THREAD

**Issue by MaxPelly** [foundryvtt/foundryvtt#10024]
### What happened?

A user with the role Assistant GM is able to create users and modify their permissions, but is not able to rename users. Users created appear with the default name "PlayerN", but attempting to rename them throws an inexplicable permissions error. The Assistant GM user (in this case, Player8) cannot even rename itself.

Probably related to #9749 but also causing issues in V10

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1.     Access User Management as an Assistant GM.
2. Create a new user.
3. Attempt to rename that user.

### What core version are you reporting this for?

10 303 and 310

### Relevant log output

```shell
{"level":"error","message":"User DM lacks permission to update User [DzHKsa6x2hT0bUiR]","stack":"Error: User DM lacks permission to update User [DzHKsa6x2hT0bUiR]\n    at ServerDatabaseBackend._updateDocuments (file:///home/ubuntu/foundry10/foundry/resources/app/dist/database/backend/server-backend.mjs:1:3830)\n    at async Semaphore._try (file:///home/ubuntu/foundry10/foundry/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2023-09-24 15:58:06"}
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hello @MaxPelly. This issue was fixed in Version 11. We are not backporting any further fixes to V10 at this time. We recommend updating to Version 11 when you are able!

https://github.com/foundryvtt/foundryvtt/issues/9749
