### ISSUE TITLE
`id` attribute for `colorPicker` and `rangePicker`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#10026]
### User Experience

We've been slowly improving system sheet accessibility in part by IDing form inputs to pair with `<label for="...">` tags--typically with `id`/`for` pairs of "field-{{appId}}-{{name}}". To do this with the color and range helpers is a little less convenient: the helpers have enumerated lists of attributes they'll accept, and `id` isn't among them. Could it be added to those lists?

**Comment by aaclayton** [comment]
The path forward on this is using new `<color-picker>` custom HTML elements and form-field generators which will make it easier to support `id`ed inputs with `for` linked labels.
