### ISSUE TITLE
'Jump to bottom' appears when clearing chat under some circumstances

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10041]
Originally reported by velgarn https://discord.com/channels/170995199584108546/1065764070680186930/1146865307621793882

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable):** Windows 10
**Short Description of bug:** "Jump to Bottom" appears when you clean the chat if it had enough "stuff" to let you scroll up and down, even if you were already at the "bottom" of the chat when deleting everything
**Screenshots and/or console errors:** No console errors

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/cfd396ec-8660-4a31-b728-54e54c63762c)

**Comment by mclemente** [comment]
This one is quite simple, `ChatLog.prototype._onScrollLog` is called twice when deleting a message that will remove the scroll (e.g. all messages or the only message that overflows the chat), so `pct` = 0/0 = NaN.

The fix:

```diff
  _onScrollLog(event) {
    if ( !this.rendered ) return;
    const log = event.target;
    const pct = log.scrollTop / (log.scrollHeight - log.clientHeight);
    if ( !this.#jumpToBottomElement ) this.#jumpToBottomElement = this.element.find(".jump-to-bottom")[0];
-   this.#isAtBottom = pct > 0.99;
+   this.#isAtBottom = isNaN(pct) || pct > 0.99;
    this.#jumpToBottomElement.classList.toggle("hidden", this.#isAtBottom);
-   if ( pct < 0.01 ) return this._renderBatch(this.element, CONFIG.ChatMessage.batchSize);
+   if ( isNaN(pct) || pct < 0.01 ) return this._renderBatch(this.element, CONFIG.ChatMessage.batchSize);
  }
```
