### ISSUE TITLE
Race condition on grandchild document updates and sheet rendering

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10053]
Originally reported by chaosos https://discord.com/channels/170995199584108546/1065764070680186930/1155632894937661460

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Shouldn't matter, but node/local/chrome
**Short Description of bug**: Race condition on grandchild document updates and sheet rendering
**Simple steps to reproduce the bug**:
1. Have a console message set to appear at the end of an actor's prepareData()
* Have a console message set to appear at the *start* of an actor sheet's getData()
* Have a console message set to appear at the *end* of an actor sheet's getData()
* Trigger an update on the actor
* The prepareData() message will appear between the two getData() messages, rather than before the first
**Screenshots and/or console errors**: Issue was discovered in SWADE system but appears to be system agnostic, confirming core foundry bug

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/2f6db019-0960-4976-9e53-b79975af5e75)

**Comment by Fyorl** [comment]
Bears some investigation as to what's going on here. Might be related to #10048 or just be #7987

**Comment by JPMeehan** [comment]
I think it's the same issue as #10048 based on my experience picking at the issue. The "old data" just depends on how your getData runs and how much stuff is being processed in getData vs. prepareData (which is why it's a race condition). No idea on how this relates to #7987 but I did see prepareData running *several* times in my testing.

**Comment by mkahvi** [comment]
It kind of felt like the grandchild update was triggering _onUpdate->render behaviour by itself, but I didn't dig too deep into it.
