### ISSUE TITLE
Compendium `JournalEntry`s migrated from v9 can't update the `JournalEntryPage` created by their migration

### ISSUE THREAD

**Issue by rsek** [foundryvtt/foundryvtt#10079]
### What happened?

Attempting to update the `JournalEntryPage` created by a v9 => v11 `JournalEntry` migration in an unlocked compendium produces an error notification:

![image](https://github.com/foundryvtt/foundryvtt/assets/5354757/27db5952-5645-404f-9168-617ad31f8ec0)

The reported `JournalEntryPage` ID is different in every FVTT session. I suspect this happens because the embedded document created by the `JournalEntry` migration isn't saved to the compendium pack DB.

Out of caution, I'm marking this for Electron and Firefox as that's what I've personally reproduced this in. But it's most likely present in other browsers, too.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Create/obtain a v9 `JournalEntry` with something in its `JournalEntry#content` string, saved in a compendium pack.
2) Open that compendium pack in v11.
3) Unlock the compendium pack.
4) Attempt to edit the single `JournalEntryPage` created by the `JournalEntry` migration.

### What core version are you reporting this for?

11.313

### Relevant log output

```shell
FoundryVTT | 2023-10-11 16:45:07 | [error] undefined id [gmSWKD9RwLI1g0XZ] does not exist in the EmbeddedCollection collection.
Error: undefined id [gmSWKD9RwLI1g0XZ] does not exist in the EmbeddedCollection collection.
    at EmbeddedCollection.get (file:///home/rsek/FoundryVTT-11.313/resources/app/common/abstract/embedded-collection.mjs:164:36)
    at JournalEntry.getEmbeddedDocument (file:///home/rsek/FoundryVTT-11.313/resources/app/common/abstract/document.mjs:631:23)
    at fromUuid (file:///home/rsek/FoundryVTT-11.313/resources/app/dist/core/utils.mjs:1:398)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #c (file:///home/rsek/FoundryVTT-11.313/resources/app/dist/components/prosemirror.mjs:1:1309)
```

### Bug Checklist

**Note:** I have not tested this without modules... because the compendium pack itself is contained in a module. The module in question contains only compendium packs, with no scripting.

EDIT: Looking at the screenshot, it looks like I forgot to turn of the dev tools module (which did make it much less tedious to track down the bug, lol). But I can still reproduce it with all but my compendium-only module disabled.

- [ ] The issue occurs while all Modules are disabled

**Comment by rsek** [comment]
Hmm, this may be a duplicate of #8448. Looks like I didn't search hard enough.

Personally I would prefer a solution that doesn't simply make the compendium document uneditable.

It would be more convenient, IMO, if optional migration would be available, perhaps presented as a dialog warning when the user attempts to edit the embedded document (and maybe only if FVTT settings are configured to retain migrated data).

Otherwise, the user is left without a lot of information on how to proceed. The workaround would be to copy it to the world, delete the original pack document, then drag the copy back into the compendium... but that only reliably maintains the original id if another copy of the document with the same id isn't present in the world. And this isn't necessarily the most obvious solution to most users.

**Comment by farling42** [comment]
Yes, it is exactly the same issue as #8448.

For a pre-V10 compendium journal, a "fake" page is created when the journal is opened.

**Comment by aaclayton** [comment]
@dev7355608 could you take a look at this issue and #8448 to ensure that our new v12 server-side migration correctly gets a pre-v10 Journal into a working v12 state?

**Comment by dev7355608** [comment]
Fixed in V12 by the server-side migration framework (https://github.com/foundryvtt/foundryvtt/issues/10257).
