### ISSUE TITLE
Create and restore Backups from web ui

### ISSUE THREAD

**Issue by david-plugge** [foundryvtt/foundryvtt#10101]
### User Experience

Currently you need access to the server to upload your backup from another server or local storage.

A way to do this directly in the web ui would be very nice! A simple button that opens a modal prompting the user to select the zip file to be uploaded should do the job.

**Comment by aaclayton** [comment]
We have just launched a built-in backups management feature in v11.311 <https://foundryvtt.com/releases/11.311>. These backups are generated using a specialized file format. I don't think we would add a UI-based utility to transfer these backups between different hosts, however. Sorry, but marking this one as wontfix.
