### ISSUE TITLE
API to predict the result of adding or removing active effects to a token/actor

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10127]
### User Experience

It would be useful for systems and modules to know how one or more active effects would affect a token/actor. I encountered this with my Terrain Mapper module, because I wanted to be able to predict token speed as the token was dragged across the canvas over terrains that would be applied as active effects. I would expect such functionality to be helpful in other cases where the GM or the user has an option to apply effects to a token or for documenting what effects do to specific tokens. 

Ideally, the API would allow the dev to do two things: 
1. See what would happen if one or more active effects were added. 
2. See what would happen if one or more active effects were removed. 

The functionality is already in code to accomplish this; it is mostly a matter of taking the part of the code that applies active effects and using it to modify the underlying actor data without actually changing it. And then, of course, returning the temporarily modified actor data in a meaningful way. This ideally would be done synchronously, without ever touching the database. 

(Terrain Mapper added some methods to accomplish this but it would be far better to handle this in base Foundry. For one, I would expect systems might seriously modify how active effects are applied, so it would be better to move such functionality to base Foundry so systems could take advantage of it.)

**Comment by aaclayton** [comment]
Suggest the following simple recipe:
```js
const clone = actor.clone();
clone.updateSource({effects: clone._source.effects.concat(additionalEffects)});
```
Then compare the prepared data of `clone` and `actor`.

**Comment by caewok** [comment]
Thanks! I think that will work. I will close this and reopen an issue if I run into any severe obstacles.

**Comment by caewok** [comment]
In case anyone uses this suggestion, I think it works fine, so long as you only use it on clones. If you update an actor's source with an effect like this, the effect will appear on the token's character sheet. Which is fine, except that if you then try to delete it, it will throw an error because the effect id is not in the database, so it tries to delete something that is not really there. Updating the source to remove the effect also doesn't really get rid of it from the character sheet; you might need to refresh the browser. Point being, stick to using clones.
