### ISSUE TITLE
Provide support for additional ambient lighting colors based on darkness levels

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt#10129]
### User Experience

This is entirely a nice to have feature related to #9683 

Having the ability to set up alternate lighting values when darkness hits certain levels would allow scenes to simulate other times of day with unique lighting conditions. The best example of this would be for simulating dawn or sunset conditions when light tends to be more orange.

If global lighting to simulate natural light/daylight gets worked on as well, this feature could be part of it, with possible tie-ins to game time. It would allow for the setting of sunset and sunrise times based on game time. The various calendar/timekeeping modules could also take advantage of this.

**Comment by Feu-Secret** [comment]
It would be a nice feature. Nevertheless, there is some requirements to make it happen:
- Is the scene in exterior?
- What is the time of the day?
- The colors needed to apply for specific parts of these lightning conditions.

I feel like it requires a lot of things that core doesn't handle : exterior/interior, time of the day/calendar.
I think it would make a nice module tough, if all these considerations are applied.
@CodeMoWerser Your thoughts about it?
