### ISSUE TITLE
Allow for roll expression modifiers to contain inner parenthetical or intermediate terms

### ISSUE THREAD

**Issue by rsek** [foundryvtt/foundryvtt#10120]
**EDIT:** I messed on some of the example expressions, they should be more coherent now :wink: 

#### Examples of expressions that **don't** work
* `{1d10,1d10}cs<(7)` 
* `{1d10,1d10}cs<min(4,10)`

#### Similar expressions that work as expected
* `{1d10,1d10}cs<7`
* `2d10cs<7`

#### Practical example
A typical action roll in Ironsworn could (theoretically) be expressed as `{1d10,1d10}cs<min( 10[action score cap], (1d6[action die] + 2[stat] + 1[adds]) )`; the value of each individual `d10` is mechanically relevant. Sometimes one of the `d10`s is replaced by a static value, e.g. `{5[preset value],1d10}`, so replacing the `PoolTerm` with a single `RollTerm` won't work.

### What ways of accessing Foundry can you encounter this issue in?

- [x] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

Here are some simple expressions that throw when passed to `await new Roll()`

* `{5,5}cs<(7)`
* `{5,5}cs<min(4,10)`

For comparison, here is one that works as expected:

* `{5,5}cs<7`

### What core version are you reporting this for?

11.313

### Relevant log output

```shell
# await new Roll('{5,5}cs<(7)').evaluate()

Uncaught Error: Roll.safeEval produced a non-numeric result from expression "0 7"
    at Roll.safeEval (foundry.js:10378:13)
    at Roll._evaluateTotal (foundry.js:10283:36)
    at Roll._evaluate (foundry.js:10231:24)
    at async <anonymous>:1:1
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is partially overlapping with #6048. We will not attempt to fix this outside of working on #9773, but I am associating this with that meta-issue. Hopefully this parsing issue would be incedentally fixed by using a new parsing grammar.

**Comment by aaclayton** [comment]
This might end up being handled by #9820 instead. @Fyorl to investigate and assess.

**Comment by Fyorl** [comment]
Our first pass of implementing the peggy grammar and evaluation engine have not managed to support this additional complexity, and we do not have a clear line-of-sight for how to implement it at this stage, so we are marking the issue as wontfix. This sort of game-system-specific logic can be handled outside of the roll engine, but if it is really necessary to handle purely via roll expressions then the new custom functions API (#9820) may provide a solution.
