### ISSUE TITLE
Implement PointSoundSource#getEffectiveDistance which allows subclasses to override and configure how audio distance and volume easing are computed.

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#10134]
### User Experience

Currently i need to override the whole method in order to feed a different value to the distance calculation used to determine the sound volume

It would be nice if the `const distance = Math.hypot(l.x - sound.x, l.y - sound.y);` could be factored out to a separate method.

For my specific use case, i would need to perform this operation on all sound sources, not only the ones close to the currently selected tokens as i implement a sound distance calculation based on distance from the Camera position, not the token

**Comment by dev7355608** [comment]
The Limits also patches `SoundLayer#_syncPositions`: https://github.com/dev7355608/limits/blob/main/scripts/patches/sound.mjs#L37-L43

In this case an additional multiplier is applied to the volume (if easing is enabled) that is based of the sound's origin and the listener positions. A ray is cast from the sound's origin to each listener position to measure how much energy is absorbed before it reaches the listener.
Ideally there would be a function like `_getVolumeMultiplier(sourceSource, listenerPosition)` that can be overridden to apply this additional multiplier.
