### ISSUE TITLE
"Left Click to Release Objects" setting keeps getting disabled

### ISSUE THREAD

**Issue by lphillips** [foundryvtt/foundryvtt#10133]
### What happened?

I always enable the "Left Click to Release Objects" setting whenever I join a new Foundry instance because I prefer that behavior. For a while now, I have noticed that sometimes when I log back in to an instance, that setting has been disabled. I think it happens when the instance has been updated to the latest version of Foundry. It seems like the migration process to the latest version is maybe not copying over the value for that setting.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Reproduction steps (in theory):

1. Install an earlier build of Foundry
2. Enable "Left Click to Release Objects"
3. Log out and update to the latest version of Foundry
4. Log in to updated Foundry and check value of "Left Click to Release Objects"

Expected behavior: "Left Click to Release Objects" is still enabled
Actual behavior: "Left Click to Release Objects" is disabled

### What core version are you reporting this for?

Version 11 Build 299

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
This is a browser-local setting, tied to the hostname of the host you're playing on; if your hostname (or IP address, if using that) changes, or if your browser is set to delete local storage periodically, it's expected for this setting to reset to default.

**Comment by aaclayton** [comment]
If/once we add user-level DB-stored settings (https://github.com/foundryvtt/foundryvtt/issues/4804) we could move this setting and some others that are currently stored in client storage there which would resolve this issue.

**Comment by lphillips** [comment]
That's good to know. It would be nice if the setting followed me from browser to browser, but at least I understand what's happening now. Thanks!
