### ISSUE TITLE
Changing the scene while clicking on the canvas locks the canvas from mouse input

### ISSUE THREAD

**Issue by ironmonk88** [foundryvtt/foundryvtt#10142]
### What happened?

If a player is clicking the canvas when the GM activates a different scene, when the new scene loads, right and left clicking on the canvas no longer works.  Which prevents the canvas from being moved around, or tokens from being selected.  If you're moving the mouse even a little bit while clicking it doesn't get locked out.  And if you hover over a token, or the tool bar or the scene menu, or the side bar, or move the mouse off the browser control will return, but until that happens, the player has lost control.
This wasn't an issue in v10, but has been an issue in v11.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Have both a GM and player logged in.
Get the player to click repeatedly on the scene *without* moving the mouse.
Get the GM to activate a different scene.
Once the new scene loads, the player will no longer be able to grab and move the map around or select things.

### What core version are you reporting this for?

Version 11.313

### Relevant log output

```shell
There are no errors in the console, but `canvas._onClickLeft` no longer gets called.  I couldn't trace it back further from there.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by ironmonk88** [comment]
[Locking the Canvas.webm](https://github.com/foundryvtt/foundryvtt/assets/75920956/1b6f3d23-54a3-4dff-b885-55865b71d4a2)

**Comment by aaclayton** [comment]
When calling `Canvas#tearDown` we need to be sure to cancel any ongoing mouse interaction workflow in the `Canvas#mouseInteractionManager`.

**Comment by ironmonk88** [comment]
Hate to be the bearer of bad news.... but this is still an issue in 11.314.
