### ISSUE TITLE
Selected options in multi-selects are indistinguishable from unselected options

### ISSUE THREAD

**Issue by FloRad** [foundryvtt/foundryvtt#10145]
### What happened?

When using a `select` with the `multiple` attribute it is nigh-impossible to see which options have been selected

Observed with the swade and dnd5e systems

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Make a macro with the following content (or paste it to the console)

```js
let content = `<select name="choice" multiple>
  <option value="first" selected>First Value</option>
  <option value="second">Second Value</option>
  <option value="third" selected>Third Value</option>
</select>`
Dialog.prompt({content})
```
2) Observe that _First Value_ and _Third Value_ (selected) are nigh indistinguishable from _Second Value_

### What core version are you reporting this for?

v11 Stable  (Build 313)

### Relevant log output

```shell
N/A
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Closing in favor of the recommended usage of the `<multi-select>` element which (we feel) has a superior UI/UX to the core HTML select multiple.
