### ISSUE TITLE
ProseMirror highlight content matches feature does not respect Document visibility permissions

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10159]
Originally reported by szefo09 https://discord.com/channels/170995199584108546/1065764070680186930/1164333095785353426

**ALL MODULES DISABLED?** true
**Short Description of bug**: ProseMirror editor's new feature "Toggle Content Link Matching When Highlighting" doesn't respect Ownership of displayed items. This causes the players to see actor/scene/journal entry's name they have no right to see. 
**Simple steps to reproduce the bug**: As a GM import Ancient Red Dragon actor. As a player start writing a journal entry in your PC's journal entry about Dragonchess. Highlight Dragon, see Ancient Red Dragon pop up as a Content Link. 
*Optional: Get asked by the player why is there an ancient red dragon imported to my world which ruins the surprise. And also it spoils the titles of Journal Entries.*
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/20de241d-ffb0-4afa-99ec-4665f92098d8)

**Comment by unsoluble** [comment]
This one has maybe been forgotten about, could use a milestone?

**Comment by aaclayton** [comment]
We are not assigning milestones to issues until they are picked up out of the prioritized backlog. I will boost the priority on this from low though, upon re-reviewing the issue it seems more significant than was first tagged.
