### ISSUE TITLE
Weather effects do not load for players the first time their browser joins the game

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10171]
Originally reported by flameofwar https://discord.com/channels/170995199584108546/1065764070680186930/1170008578128613446

**ALL MODULES DISABLED?** (true)
**OS, Hosting, Browser (if applicable)**: win10, firefox
**Short Description of bug**: weather effects not working for players
**Simple steps to reproduce the bug**: create map, select weather ambience, launch
**Screenshots and/or console errors**:

**Comment by thre-z** [comment]
As a note, at the steps above where a player observes no weather effect rendered, they can hit F5 to reload. After the reload, the weather effect appears normally.
