### ISSUE TITLE
Make the Macrobar movable

### ISSUE THREAD

**Issue by zarazandra** [foundryvtt/foundryvtt#10179]
### User Experience

Hi there, 

I would love to be able to position the macrobar where I want it to be. Right now, with the theme I use, the playerlist will always overlap the first macro button (I prefer the playerlist to be open). I would really appreciate the possibility to move. 

I've done it with the custom css-module, but maybe there would be an option to do this without. 

Thanks

**Comment by aaclayton** [comment]
It sounds to me like the problem is "with the theme I use" because the foundry core software does not have any overlap between the players list and the macro bar.

**Comment by zarazandra** [comment]
Yes, I know That there's No overlap. But it gives me freedom to move it anyways to My liking. 
It's a qol-feature imho.
