### ISSUE TITLE
`empty` data field option for `ArrayField`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#10186]
### User Experience

Similar to `StringField`'s `blank` option, it would be convenient to have an `empty` option for `ArrayField`, defaulting `true`, that when `false` would invalidate the field if the source array has no elements.

Alternatively, there could be a pair of options to stipulate the minimum and maximum length (defaulting to 0 and `Infinity`, respectively).

**Comment by aaclayton** [comment]
Will prioritize for V12.

**Comment by aaclayton** [comment]
@stwlam we're facing a prioritization crunch for V12 features that make the cut vs. don't. Could you provide an update on your use case here and what you need from this issue?

**Comment by stwlam** [comment]
Currently when it's crucial we can implement this by configuring the field with a validation function to check the array length. So the present issue is just a request for convenience rather than necessity.

**Comment by Fyorl** [comment]
`ArrayField` now supports `min` and `max` options that can be used to validate the number of elements.
