### ISSUE TITLE
Expand support for system-specific type data to additional document types: Active Effect, Combatant, and ChatMessage

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10185]
# Implemented Features
Support for document sub-types has been added to the `ChatMessage`, `ActiveEffect`, and `Combatant` document types.

## Non-Breaking Changes
- Added `ActiveEffect#type`, and `ActiveEffect#system` fields for document sub-types.
- Added `Combatant#type` and `Combatant#system` fields for document sub-types.
- Added `ActiveEffect#_stats` and `Combatant#_stats` fields since we require all Documents which implement support for document sub-types to track document stats.
- Generalized the `static TYPES` array from various document types (Actor, JournalEntryPage, Card, etc...) to be a shared static property defined for all `Document` types.

## Breaking Changes
- The `ChatMessage#type` field is renamed to `ChatMessage#style` in order to make way for the type field to be used for document sub-types. An automatic migration provides backwards compatibility for pre-existing messages.
- Added the `ChatMessage#type` and `ChatMessage#system` fields for document sub-types.
- `CONST.CHAT_MESSAGE_TYPES` is renamed to `CONST.CHAT_MESSAGE_STYLES`. A proxy is left in place for `CONST.CHAT_MESSAGE_TYPES` to provide backwards compatibility.
- `WHISPER` is no longer a valid value in `CONST.CHAT_MESSAGE_STYLES`. Whether a ChatMessage is a whisper or not is inferred directly from whether it has defined `ChatMessage#whisper` recipients. An automatic migration provides backwards compatibility for pre-existing messages.
- `ROLL` is no longer a valid value in `CONST.CHAT_MESSAGE_STYLES`. Whether a ChatMessage is displayed as a roll or not is inferred directly from whether it has `ChatMessage#rolls`. An automatic migration provides backwards compatibility for pre-existing messages.

# Initial User Request
As a system developer, I would like to expand upon the functionality of Active Effects and Combatants, with the specific ability to implement a system data model.

**Comment by aaclayton** [comment]
A good request. We might need to split this into two issues, but I'll scope it for V12 consideration.

**Comment by JPMeehan** [comment]
Splitting into two is probably the logical choice, I just didn't want to submit two separate tickets if there was going to be a big debate over the whole premise.

**Comment by aaclayton** [comment]
Comment from @chris-osprey:

System data model support would be really nice when using chat messages extensively in system development for things like game automation. Further, some mechanism which would allow for different types of messages with different models akin to item and actor types would also be great.
