### ISSUE TITLE
Improve the addition of header buttons and add a way for users to hide their labels

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#10182]
## Request 1
On `Application._renderOuter`, add a new hook that gets header buttons after `Application._getHeaderButtons` is called.

Alternatively, consider moving the `get${cls.name}HeaderButtons` hook out of `Application._getHeaderButtons`.

### Reasoning
There are lots of modules that add header buttons during the `render${cls.name}Application`, be it for not knowing there is a proper hook or because adding a button at that stage means the button will be added before buttons like "Sheet Config" and "Prototype Token" since the method is called at the Application class, before the subclasses can add their own.

This behavior means any dev that wants to add a button will move the core buttons to the right, which can be confusing to users since every new module might push the buttons further.

If there was another hook, developers who don't see their module's buttons as important as core buttons can push their buttons without breaking the pattern. As the alternative, the original hook could be called after all the subclasses' `_getHeaderButtons` methods were called.

## Request 2
Add a "hide labels of header buttons" to hide button labels, then turn the labels into a tooltip so the buttons keep their contextual information without taking as much space.

Alternatively or concurrently, add a  "tooltip" property for buttons so they can be set without a proper label and still have some contextual information about what the button is meant to do.

### Reasoning
It is possible to add so many buttons to the header that it pushes the X button outside of the title bar. And that doesn't require a lot of modules.

#### Example 1
Brazilian Portuguese localization, 6 modules shown, Compendium
![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/3d3dc28a-02fd-4cd0-be69-c494a53e76d3)
(Item Macro, Automated Animations, DAE twice, GM Notes, and Build-a-Bonus)

Note: DAE's button (Wrench) is longer than its English localization, but you can get a similar behavior by enabling Build-a-Bonus' label.

#### Example 2
English localization, 6 modules shown, Item Directory & Compendium.
![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/fcc7e456-43bd-46a3-862d-14b484959f36)

---

There are just 6 modules (although their dependencies bump the install number to 16). If someone opens an item like that, their only way to close it is to press ESC, which closes everything.

Also, can you spot the Sheet/Import buttons at a glance? If a user installs a module at a time, these buttons will keep moving left. Users will get used to it eventually, but still, should it be like that?

## About Cleaner Title Bar module
The general solution for this issue on the discord channels is clear: "use the Cleaner Title Bar module". While the module does its job well, it shouldn't become obligatory at such a small threshold of 6-16 modules.

I'd also raise that there is a case for users that probably use this without a cluttered header bar and just want to have the Sheet/Prototype Token/Close buttons not taking that much space, especially on systems with sheets that are smaller by default.

## Context
Original discussion: https://discord.com/channels/170995199584108546/811676497965613117/1171579058715369482

**Comment by Fyorl** [comment]
Request 1 looks similar to #9331, and request 2 is related to #3273 (and tooltips are covered by #6412), both of which are already scoped to the 'Application v2' epic #5441. In general it's easier for us if you're able to split up issues like this which are two separate feature requests into their own separate issues.

**Comment by aaclayton** [comment]
Closing as duplicate and pasting your comment into #3273 for record-keeping.
