### ISSUE TITLE
Feature Request: Alter `token.toggleCombat()` to operate only on *that* token instead of all selected

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#10197]
### User Experience

The current behaviour is clearly stated in the documentation, but that is *not* what you'd assume that method called in that way would do. A method on a single token shouldn't be operating on more than that token, at least not without some indication in the name, IMO.

**Comment by aaclayton** [comment]
Closing as duplicate of #9068 and #8797
