### ISSUE TITLE
Introduce a module permission level

### ISSUE THREAD

**Issue by rapus95** [foundryvtt/foundryvtt#10203]
### User Experience

There are modules which need GM rights (and thus a logged in GM) to perform their actions. Get rid of that requirement. I'm aware of #6503, but my proposal aims at having elevated modules instead of executing arbitrary scripts with elevated permissions. Sure, one could write a "sudo module" which could then run arbitrary macros for any user, but that also requires a gm installing that module. And if the gm is fine with any player running arbitrary scripts, well, that's already possible, can't guard against that.

Basically this allows for modules to be more than a set of scripts and data routed through the user perspective. Within these elevated modules, module authors would have to actively check for the permissions of the "requesting" players for all cases in which they actually want to care about them since the module itself is allowed to execute that task.

Example (made up from a Multilevel Tokens scenario): I have a scene which is non-euclidean, and I want to be able to freely teleport between two drawings. Now I could have a module which generally has the module permission level and thus is allowed to execute arbitrary code. That module now provides a new option of "drawings" (which can only be configured by the GM) and triggers when a player enters the space of one drawing. Now, given the module is generally allowed to execute a teleportation, the module itself has to check whether the player is allowed to teleport here according to the rules set up for that drawing, and if so, it may indeed execute the teleport. If the player is not allowed to teleport here, it can either silently fail since nothing happens, or manually place an error about lacking permissions.

Generally speaking, have the possibility that modules can run elevated when reacting to player events.

If I'm lacking any insights and that's the reason my proposal doesn't make any sense, I'd love if you explained to my why this isn't possible without the problems of #6503.

**Comment by aaclayton** [comment]
Permissions are important. We would not build an API that has user roles and permission controls, and then build a back-door for that API that lets you ignore them.

**Comment by rapus95** [comment]
Seems I somehow didn't get the point. The request was for providing a way that allows the gm to actively permit modules to behave in his name w/o him being logged in. Because with him being logged in, this already works. So this is about serving the DM and development community (which effectively also serves the DMs as it takes workload from them by providing pre-written code)
Users shouldn't get new permissions or anything like that. Everything still needs a DM to allow it. It will just replace the sync approach (DM must be logged in right at that moment) with an async approach (DM can allow ahead of time by actively providing these permissions to a module).

**Comment by aaclayton** [comment]
What you are suggesting is "there should be a way for non-GM users to act as a GM". What I am saying is that there should be no such thing.

**Comment by rapus95** [comment]
That's not what I suggested. For sure, a module could expose arbitrary execution to non-GMs if it wanted, but I'd simply not install that module in my world then.

What I was proposing is a way how modules can build world interactions without a gm required for the world to work as the gm designed it.
Say, a GM designs a lava pit which shall automatically delete anything that falls into. if a user moves into that pit, the character should be gone. But without a GM logged in and players not allowed to delete tokens, they're basically invincible until the gm reconnects again. Same for any other world interactions like linking 2 scenes together (solved via a teleport workaround), polymorphing and so on. Implementing world level actions that weren't willingly triggered by players. Thus, this isn't intended to give more rights or a "backdoor" to the players.
Only workaround is to have a gm logged in at all times, or walling interactive areas away until the GM is available, but that's still a workaround.

Not sure if I this time managed to better convey the differences between designing a way to circument permissions and this request. It's totally not about circumenting player permissions but about being able to implement world interactions which don't have to be manually triggered by the GM (or modules rerouting requests through a logged in GM).

**Comment by aaclayton** [comment]
If a module is able to circumvent GM permission using a client-side API, a user is also able to circumvent GM permission using a client-side API. Module code runs as the user, so anything the user can do the module can do, and anything the user cannot do the module cannot do.

**Comment by rapus95** [comment]
are there any chances there will be something like core modules at some point which will run on the server side and thus won't be exposed to user changes? Thus, not being a backdoor but being an open extension point to extend the functionality in the direction of world logic

**Comment by aaclayton** [comment]
> are there any chances there will be something like core modules at some point which will run on the server side and thus won't be exposed to user changes? Thus, not being a backdoor but being an open extension point to extend the functionality in the direction of world logic (open in the regard of development endpoint, not regarding user accessible). Kinda like kernel modules in OS'

No, zero chance of server-side modules ever.

**Comment by rapus95** [comment]
okay, thanks for staying with me so long and the patience to follow my words and explain to me the problems with it! Hopefully more of those ideas/concepts will over time find some way into the core as individual features developed on your side! Totally curious what the next version will bring to the table :D in particular for lighting and map regions
