### ISSUE TITLE
[Feature Request] Add "Material Design Icons  Webfont" to v12

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#10206]
### User Experience

Font awesome a always covered my needs, but there are beginning to be occasions when I can't find the icon I need. 

Another good opensource, license-compatible icon linbrary that I ask you to consider as a addition for v12 is "Material Design Icons" https://github.com/Templarian/MaterialDesign (Webfont / SCSS branch)

**Comment by aaclayton** [comment]
We would not add a second large icon font to the core software, especially not after we shifted to include FA Pro. I realize there are icons out there that FA doesn't provide. If these are essential to your use case you can include a second icon font like Material Design Icons via a module.
