### ISSUE TITLE
Request: Add option for identifiers to context menus to style or find them

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#10217]
### User Experience

For example I want my system's context menu options to stand out from core Foundry options in chat cards, but currently the only way I can do that is via the icon.

My need is simple background color shift to the system entries to make them stand out as relating to the system, which would be easy to accomplish if I could complement the built-in `context-item` class.

**Comment by Fyorl** [comment]
`ContextMenuEntry`s may now specify an optional, space-delimited `classes` property that will be appended to the generated context meny entry markup.
