### ISSUE TITLE
Simplify adding custom sound sets for Combat Themes.

### ISSUE THREAD

**Issue by Freeze023** [foundryvtt/foundryvtt#10268]
### User Experience

Currently FoundryVTT comes with two Combat Themes (Epic and Fight Commentator). 
The paths of the files are stored in `CONFIG.Combat.sounds` and I expected adding a sound set to `CONFIG.Combat.sounds` would suffice for getting it listed in the drop-down menu in the Combat Tracker Settings, because that is how it works for adding a sound set for doors.

However the drop-down menu for combat sounds gets created from the `choices` in the `"core.combatTheme"` game setting. 
This makes adding your own themes way more complicated, as you not only need to change CONFIG you also have to make a change to the game setting.

Solution: do away with the choices for the setting and let handlebars build the drop down from the data from the CONFIG instead?

**Comment by aaclayton** [comment]
This choices list is now populated dynamically so updates to `CONFIG.Combat.sounds` can be chosen in the UI and saved as a valid setting value.
