### ISSUE TITLE
A module enabled with a broken compendium causes the whole world not to load.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10275]
### What happened?

Reported here: https://discord.com/channels/170995199584108546/1065764070680186930/1176076696026349638

A module enabled with a broken compendium causes the whole world not to load. Players only see a blank screen. No issue if module is disabled but the enabled/disabled settings are not reachable as the whole screen is blank.

![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/806ad588-d388-4158-a9f5-38bb5ca8b49a)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a leveldb compendium with folders and set a folder.type=null

### What core version are you reporting this for?

Version 11

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Unable to reproduce problem. Reached out to original reporter for clarification.
