### ISSUE TITLE
Cannot whisper rolls to a specific user because the whisper targets of chat messages containing rolls are always overridden by the roll mode

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10278]
## Implemented changes

Now, if the `ChatMessage` is created with data that has nonempty `whisper` targets and `options.rollMode` is not set, `ChatMessage#_preCreate` no longer applies the current roll mode, which would override the `whisper` targets.

### What happened?

Reported here: https://discord.com/channels/170995199584108546/1065764070680186930/1177629907099062322

Roll type messages ignore and scrap already set roll mode information. 
ChatMessage.applyRollMode() scraps whisper targets if already provided for a message. Since this is called in ChatMessage._preCreate() and few other places automatically, this is unavoidable.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

```js
ChatMessage.create({
   rolls: [(await new Roll("3d6").evaluate()).toObject()],
   type: CONST.CHAT_MESSAGE_TYPES.ROLL,
   whisper: ["someOtherPlayerIdThat"],
});
```
The problem code is the following (and other similar instances of it):

```js
const rollMode = options.rollMode || data.rollMode || game.settings.get("core", "rollMode");
if ( rollMode ) this.applyRollMode(rollMode);
```

And the applyRollMode() then overwriting whisper field no matter if it's already been defined.

And another much easier repro:
1) Make sure your UI selected roll mode is public
2) Execute following

```js
const msgData = await new Roll("3d6").toMessage({}, {rollMode: CONST.DICE_ROLL_MODES.PRIVATE, create:false});
ChatMessage.create(msgData);
```

3) Note how the message is still public despite me explicitly creating it as private previously?

Only even remote workaround for this is to always provide rollMode in the creation context data. But this still prevents you from whispering a roll to specific player. It also makes calling applyRollMode() manually pointless for roll messages, unlike with other chat messages.

Edit: I suppose the real workaround is to provide invalid (but truthy) value for rollMode context option (e.g. true). Though this will still override blind even if it spares whisper targets.
```


### What core version are you reporting this for?

Version 11

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
Originally reported by zhell9201: https://discord.com/channels/170995199584108546/1184176415139184731/1259453876176814121

**Short Description of bug**: The `whisper` and `blind` properties of a chat message data object are overwritten by the roll mode setting unless `rollMode` is passed to the ChatMessage creation operation option object.
**Simple steps to reproduce the bug**:

Set default roll mode to 'Public', then run:
```js
const roll = await new Roll("1d4").evaluate();
const messageData = {rolls: [roll]};
ChatMessage.applyRollMode(messageData, CONST.DICE_ROLL_MODES.PRIVATE);
ChatMessage.create(messageData);
```
Expected: A private roll. Actual: A public roll.
