### ISSUE TITLE
Faint light leaking through walls a very small distance

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10281]
### What happened?

Faint light leaking through walls a very small distance

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Simple steps to reproduce the bug:
1. Create a scene with a background map image that has wall art of some kind
2. Wall a room in the map with normal, default walls
3. Place a few lights close by the outside of the wall
4. Create an Actor without ability to see in the dark (for example, completely default DND5E 2.4 PC token)
5. Place the token for the new Actor inside the room
6. If the faint outlines of the wall with the exterior illuminate aren't visible to you, take a screenshot and boost the brightness and contrast of it so the faint "edges" of the light become visible

Expected results: The token can see nothing
Actual Results: The token can see the edges of the lights that are "leaking through" some of the walls a very small distance. This is very faint and only visible on certain monitor settings or if the image is adjusted to make it more visible.

![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/2e5bbf81-1768-430d-8719-a83f7fb20546)
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/db7c20c0-955a-4577-875a-b69d7ef55153)
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/72ca3911-84d6-496c-bc24-b2869812a996)
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/324b0073-cfaa-46f0-b903-95958c7f884b)

### What core version are you reporting this for?

Version 11

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Feu-Secret is this still an issue? If so, I imagine that the root cause is sufficiently deeply embedded in our rendering pipeline that we should not touch it until V13. Do you agree?

**Comment by Feu-Secret** [comment]
It seems the issue is fixed. I can't reproduce the light leaks.
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/8314469c-6da8-442e-bb6d-580a4c9753fd)
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/d4e38c0a-9ef9-4776-9fe2-042557c148cc)
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/d3904778-ba2c-45a8-95b0-136124fff424)
