### ISSUE TITLE
Attempting to launch the Linux version in Windows using 18.14.2 binary results in an error

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10288]
### What happened?

Reported here: https://discord.com/channels/170995199584108546/1184176415139184731/1184272254809419869

Attempting to launch the Linux version in Windows using a Node 18.14.2 binary and seeing 
Error: Cannot find module '@node-rs/crc32-win32-x64-msvc'

The folder seems to have stuff for Linux but not Windows

Edit: Apparently it's broken on the Mac Electron build too

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

-

### What core version are you reporting this for?

Version 12 P1 316

### Relevant log output

```shell
-
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Related to this issue: 
Reported here: https://discord.com/channels/170995199584108546/1184176415139184731/1184639917226213396

Attempting to launch the Linux version in Windows using a Node 20.10.0 binary and seeing 
Error: Cannot find module '@node-rs/crc32-linux-arm64-gnu'
I checked that the referred file really does not exist in that directory.

**Comment by Spice-King** [comment]
> I haven't tried this personally, but there is a workaround that has been reported for this issue:
> 
> If you are running from within the Foundry dir, try: `npm i @node-rs/crc32-win32-x64-msvc`
> 
> otherwise, try this: `npm i @node-rs/crc32-win32-x64-msvc --prefix c:\path\to\resources\app\`

@Norc Looks like my thoughts pan out, `npm i @node-rs/crc32` works to shorten it and ignores all OS/CPU arch/Libc mismatch issues locally by just reevaluating and installing the correct one. Will solve it for things like 32-bit/ARM64 on Windows, x64/ARM64 on macOS, x64/ARM64 Linux with gnu/musl Libc, or even the unsupported options of ARM/ARM64 for Android or x64 FreeBSD.

**Comment by aaclayton** [comment]
@Fyorl to take a look into whether we can drop `yauzl-promise` in favor of an alternative unzipping library.
