### ISSUE TITLE
--world option doesn't describe the format it expects

### ISSUE THREAD

**Issue by strongpauly** [foundryvtt/foundryvtt#10297]
### Where did you find it, or where does it belong for requests?

Other foundryvtt.com site page (not package listings)

### What page or file needs a look at?

https://foundryvtt.com/article/configuration/#:~:text=Command%20Line-,Flag,-Listing

### What core version are you reporting this for?

Version 11 Build 315

### What is wrong, in your opinion?

Trying to pass the world title to this option results in: `The requested World is not available to auto-launch.`.  Either the documentation should specify it expects the data path folder (ideally with an example), or the error message should display which worlds are available, or both.

**Comment by Norc** [comment]
Made the requested changes. New text:


```html
<dt><code>--world</code></dt>
	<dd>This flag allows for a specific world to be opened immediately as Foundry launches. The expected value is the datapath of the world, not the user-facing name of the world. For example, if your campaign was named <code>My PF2E Campaign</code>, Foundry generates a datapath for that world by setting all characters to lowercase and replacing spaces with hyphens, resulting in <code>my-pf2e-campaign</code>. The datapath for a world can be viewed from the Setup screen by right-clicking it and selecting the "Edit World" option. 
		<br><br>Note that this option will not work if some setup steps are not completed, such as EULA acceptance.</dd>
```

**Comment by aaclayton** [comment]
Feels like somewhere in this documentation we should use the term "id", which is what it is.
