### ISSUE TITLE
Allow scope variables passed to a macro via chat command to contain spaces as long as they are not equals (=) separated

### ISSUE THREAD

**Issue by GraithTiger** [foundryvtt/foundryvtt#10303]
### User Experience

This is somewhat of a follow-up to #9201 

When passing arguments from chat to script macros, only the text before any whitespace is actually passed to the `scope` object.
 
For example, if we have a macro echoText:
```js
console.log(scope);
ChatMessage.create({content: scope.message});
```
and execute it using `/macro echoText message="hello world"`

The intended behavior of the script would be to print `hello world` to chat, with the console output being:
`Object { message: 'hello world' }`

However as currently implemented, it will return `"hello` with the console output being:
`Object { message: '"hello' }`

**Comment by aaclayton** [comment]
Fixed for V12P2.
