### ISSUE TITLE
Compendium UUID redirects

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#10301]
### User Experience

In the pf2e system, we're bracing for a new bestiary publication that supplants an older one. While we would like to avoid clearing out our older compendium, the additional data load of new monsters and NPCs would have an unacceptable impact on system performance (particularly when launching a world). However, because premium modules pull from that compendium, we also can't simply remove the old actors and add their rewritten versions to the to-be-created compendium.

It would be valuable in this case if we could somehow register UUID "redirects", perhaps in `CONFIG`, such that `fromUuid` and `fromUuidSync` would check first in case of compendium UUIDs and utilize a match if found. For our purposes, it could be as simple as something like the following:

```js
async function fromUuid(uuid, options={}) {
  // ...
  const realUuid = CONFIG.uuidRedirects.get(uuid) ?? uuid;
  let {collection, documentId, documentType, embedded, doc} = foundry.utils.parseUuid(realUuid, {relative});
  ```

**Comment by FloRad** [comment]
This would be a great asset in the toolkit for content providers in general.

**Comment by aaclayton** [comment]
I can see how this would be useful in allowing systems to manage compendium content migrations, will evaluate it for v12.

**Comment by aaclayton** [comment]
Marking as high priority to see if we can squeeze into V12 Dev2.
