### ISSUE TITLE
Ampersand (&) in description causes error "Metadata validation failed for module \"nordlond-bestiary\": Cannot read properties of undefined (reading '0')"

### ISSUE THREAD

**Issue by Dana-Johnson** [foundryvtt/foundryvtt#10304]
### What happened?

Module no longer worked because of ampersand (&) in description.  A better error message would have helped, ideally "ampersand (&) not satisfied while processing 'description'" but even a validation "validation failure while processing description" would be an improvement.
From the code, I thought a double ampersand (&&) could be used to replace the ampersand but that didn't work:
        else if (c === CharCodes.Amp) {
            // We have two `&` characters in a row. Stay in the current state.
from line 579-580 in Tokenizer.js (Tokenizer.prototype.stateBeforeEntity).  But I don't fully understand what is going on at this point.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Any module with an ampersand (&) in the description, several of the modules I have installed had this issue..  Error eliminated by removing/replacing ampersand (&) in description.

### What core version are you reporting this for?

Version 11 build 315

### Relevant log output

```shell
{"level":"error","message":"Metadata validation failed for module \"nordlond-bestiary\": Cannot read properties of undefined (reading '0')","stack":"TypeError: Metadata validation failed for module \"nordlond-bestiary\": Cannot read properties of undefined (reading '0')\n    at Tokenizer.stateBeforeEntity (/home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)\n    at Tokenizer.parse (/home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)\n    at Tokenizer.write (/home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)\n    at Parser.write (/home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)\n    at sanitizeHtml (/home/foundry/foundry/resources/app/node_modules/sanitize-html/index.js:588:10)\n    at cleanHTML (file:///home/foundry/foundry/resources/app/dist/database/validators.mjs:1:233)\n    at Function.cleanData (file:///home/foundry/foundry/resources/app/dist/packages/package.mjs:1:3105)\n    at Module._initializeSource (file:///home/foundry/foundry/resources/app/dist/packages/package.mjs:1:2531)\n    at new DataModel (file:///home/foundry/foundry/resources/app/common/abstract/data.mjs:50:19)\n    at new BasePackage (file:///home/foundry/foundry/resources/app/common/packages/base-package.mjs:213:5)","timestamp":"2023-12-27 18:18:55"}
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
Hi there! The console has sent you on a bit of a goose chase there — this error you're seeing isn't actually related to any of that, and is rather a symptom of having installed v11 without completely wiping out the v10 app first. If you're running the desktop app, fully uninstall it and then re-download and install. If you're running on a linux server: stop the process, wipe the app install folder, re-download and unzip, re-start the process.

**Comment by aaclayton** [comment]
Yes, @unsoluble is correct in the diagnosis here. This should resolve your issue.

**Comment by Dana-Johnson** [comment]
Thanks for your help.  I am running on Linux and I had upgraded.  I've now done a fresh install and the ampersand no longer causes an issue.  And I was feeling so good that I'd tracked down the issue for me... ;)
