### ISSUE TITLE
[BUG ?] The method `setProperty` when setting an undefined value also remove the key attached to it

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#10310]
### What happened?

During some testing we noticed that using the `setProperty` to set a value as undefined also removes the key attached to it ? is this intentional ? Below is an image to clarify the concept.

![](https://i.imgur.com/tSQk0uL.png)

As a solution (if it were an intended thing), perhaps an optional parameter to verify that you want to keep the key ? For example:

`setProperty(object, key, value, {doNotRemoveKey = false})`

Connected to this issue: 

- https://github.com/foundryvtt/foundryvtt/issues/4418

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Here the code to test:

This is the current code:

```js
  function setProperty(object, key, value) {
    let target = object;
    let changed = false;

    // Convert the key to an object reference if it contains dot notation
    if ( key.indexOf('.') !== -1 ) {
      let parts = key.split('.');
      key = parts.pop();
      target = parts.reduce((o, i) => {
        if ( !o.hasOwnProperty(i) ) o[i] = {};
        return o[i];
      }, object);
    }

    // Update the target
    if ( target[key] !== value ) {
      changed = true;
      target[key] = value;
    }

    // Return changed status
    return changed;
  }

   setProperty({
  	flags:{
  		a:{
  			b: "test"
  		}
  	}
  }, `flags.a.b`, undefined);
```

This the code with the expected behaviour ?

```js
function setProperty(obj, attribute, value) {
        const arr = attribute.split(".");
        while(arr.length){
            const prop = arr.shift();
            if(prop != undefined && prop != ""){
                if(obj[prop] == undefined){
                    obj[prop]={}
                }
                if(arr.length === 0){
                    obj[prop]=value;
                }
                obj = obj[prop];
            }
        }
    }
   setProperty({
  	flags:{
  		a:{
  			b: "test"
  		}
  	}
  }, `flags.a.b`, undefined);
```

### What core version are you reporting this for?

Version 11.315

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'll take a look and report back!

**Comment by aaclayton** [comment]
Did some investigation here but this is the expected behavior for the function:
```js
const o = {
  inner: {
    one: 1
  }
};
foundry.utils.setProperty(o, "inner.one", undefined);  // o = {inner: {one: undefined}}
```
You are explicitly setting the property `"inner.one"` to `undefined` - which is what happens. Am I misunderstanding?
