### ISSUE TITLE
Request: Throttle template rotation updates

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#10311]
### User Experience

Currently if you shift+mousewheel rotate templates, it can be somewhat unresponsive as each step seems to be pushed to the backend. It should instead only preview the change as long as the wheel keeps being turned and commit it after people stop wheeling.

This however does prevent other users from being able to witness your glorious live rotation, so it can be a problem for some odd use cases.

**Comment by aaclayton** [comment]
Mouse wheel events are currently throttled according to `MouseManager.MOUSE_WHEEL_RATE_LIMIT` which is 50 milliseconds by default. A module could set a different rate limit to be slower if it represents a performance problem for them or their players.

**Comment by mkahvi** [comment]
The throttling seems to be only for getting the wheel events, not for pushing updates. So it updates as much as it actually reacts to wheeling as far as I can read the relevant code.

**Comment by aaclayton** [comment]
We can look into it, we made some changes to the way that throttled events are handled in v12.

**Comment by aaclayton** [comment]
This is not handled any differently than token or tile rotation updates. Wheel events are throttled according to the configured `MOUSE_WHEEL_RATE_LIMIT`.
