### ISSUE TITLE
Add `module-data` subfolder to `Data` folder by default

### ISSUE THREAD

**Issue by ian612** [foundryvtt/foundryvtt#10323]
### User Experience

In the user data folder, where the `modules`, `systems`, `worlds`, etc. folders live, it would be nice if there was a folder called `module-data` by default. Within this folder, each time a module `module-example` is installed, a similarly named subfolder would be created that would provide a default location for modules to store data.

Currently, a module can't store created data files within the `modules/moduleName` folder, since each of those folders is overwritten each time the module code is updated. However, many modules introduce functionality that requires storage of data that needs to persist across updates (a token art creation module like [Tokenizer](https://foundryvtt.com/packages/vtta-tokenizer/) is one example, but [Token Action HUD](https://foundryvtt.com/packages/token-action-hud-core) also stores config data in files).

Right now, there is no preferred location for modules such as these to store created files, so many of them simply create folders in the user Data folder directly, which can lead to a cluttered Data folder. To improve this problem, I don't think modules need to be forced to use specific locations to store data or anything, just provided with a clearly "preferred" data storage location that always exists in the directory structure.

**Comment by ian612** [comment]
I also noticed this issue (https://github.com/foundryvtt/foundryvtt/issues/9872). They may be related but wasn't sure

**Comment by MaxPat931** [comment]
[v11.292](https://foundryvtt.com/releases/11.292) introduced the option for "Persistent Storage" for mod authors to enable in their manifests, I believe this does what you are looking for 
Original ticket: #8590
