### ISSUE TITLE
Updating drawing position tab:  x/y coordinate updates ignored when width or height is also adjusted.

### ISSUE THREAD

**Issue by pmoore603** [foundryvtt/foundryvtt#10325]
### What happened?

When I adjust x/y coordinates and width or height at the same time, only the width/height is updated.  The x/y coordinates remain at the original values.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Make a drawing (I used a text box), and update x/y coordinates and width/height to new values, then click update drawing.

### What core version are you reporting this for?

Version 11 (Build 315)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@dev7355608 could you take a look at this one? I have reproduced the issue in V12.
