### ISSUE TITLE
Foundry Content / News is permanently unreachable for some Foundry installations

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10326]
### What happened?

Certain installations of Foundry will always display an error message in the Setup screen where the News and Featured Content sections are located:

`No content recommendations were received from the foundryvtt.com web server.`

![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/1cf8d91f-db47-441d-9542-139b9ddf82eb)

This has been reported widely (but infrequently) in the past few weeks, and may or may not be related to cases where the same modules repeatedly fail to update due to an ECONN error or "request to setup took longer than 30s" error (will log and add links soon).

In at least one case (Community Helper KhazadJake), only one of two installations on the same network were affected by this issue. The other accesses featured content normally.

**Potentially related Featured Content / News issues:**
Featured content was sometimes not displaying in early V11:
[](https://github.com/foundryvtt/foundryvtt/issues/9367)

Local caching of featured content items:
[](https://github.com/foundryvtt/foundryvtt/issues/9281)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

This bug is impossible to reproduce on some Foundry installations, and impossible to _not_ reproduce in others. 

The best way to reproduce this is likely to remote onto an affected machine. Community Helper KhazadJake has indicated they would be willing to help troubleshoot and other voluteers can be recruited as needed. 

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
Relaying some thoughts from Discord moderator Spice King that he shared via Discord originally:

**Data Dumping**
Right I reached in and dumped some data on the package request:

```
// dumped data
{
  url: 'https://foundryvtt.com/_api/packages/get',
  data: {
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'APIKey:<YEET>'
    },
    method: 'POST',
    body: '{"type":"world","version":"11.307","license":{"host":"<yeet>>","license":"NOPEMINENOPEMINENOPEMINE","version":"11.293","time":"2023-05-02T14:22:05.001Z","signature":"<YEET>"}}',
    signal: AbortSignal {}
  },
  headers: {
    'access-control-allow-origin': '*',
    connection: 'close',
    'content-length': '9407',
    'content-type': 'application/json',
    'cross-origin-opener-policy': 'same-origin',
    date: 'Fri, 29 Dec 2023 17:35:00 GMT',
    'referrer-policy': 'same-origin',
    server: 'nginx/1.22.1',
    vary: 'Origin, Cookie',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY'
  }
}

```

```
// More dumped data
{
  url: 'https://api.foundryvtt.com/_api/license/check/',
  data: {
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'APIKey:<yeet>'
    },
    method: 'POST',
    body: '{"diagnostics":null,"updateChannel":"stable","license":{<yeet>},"versions":{"foundry":"11.307","node":"18.12.1","electron":"23.2.3"}}',
    signal: AbortSignal {}
  },
  headers: {
    connection: 'close',
    'content-length': '6658',
    'content-type': 'application/json',
    'cross-origin-opener-policy': 'same-origin',
    date: 'Fri, 29 Dec 2023 17:34:48 GMT',
    'referrer-policy': 'same-origin',
    vary: 'Origin',
    // signs of AWS magic here
    'x-amz-apigw-id': 'Qt1w3Fr4vHcEvBg=',
    'x-amzn-remapped-content-length': '6658',
    'x-amzn-requestid': 'f8b1c009-5168-4325-bb5c-919158751b06',
    'x-amzn-trace-id': 'Root=1-658f0338-2dc19b6575c264b20e466124;Sampled=0;lineage=eec561d8:0',
    'x-content-type-options': 'nosniff'
  }
}
```
The returned data has nothing interesting, I looked, it's about what you expect, with a few extra bits of junk that probably could be trimmed if one cared to.

**Additional thoughts:**

1. url and data is what Foundry is sending up stream, while headers is what the API server is throwing back once passed through what ever layers in Amazon you guys use.

2. The Vary header is suspect, as some proxies do caching (nginx is one) and might key that off of the Vary header, so something might be aching it on the API server side.

3. There is also no use of the Cache-Control header, which IMHO in this case might be wise to be no-cache.

4. Adding If-Modified-Since to the Foundry instance's request headers could be an option if you want the instance to cache results locally, which would require sending back the Last-Modified header. Would need some rework as the code path ignores any chance to look at the returned headers.

5. As an aside, weirdly, the package API end points are still on foundryvtt.com and not api.foundryvtt.com. News/featured content is bundled into the version check, but that uses the license/check endpoint.

**Comment by Norc** [comment]
Some additional findings from Discord moderator Spice King:

> It's a flaw in the update check.
> Did not dig deep enough, but if on a 100% clean (no Logs folder, no saved options.json as minimum) there will be no cached Logs/news.json saved. Yet to probe all the update logic, but something else is sort of prechecking if there is an update on the current channel. For 11.315, it's the latest version on stable, it does not then seek to see what all is in the current version's changes, which also has the news data. Kick the instance to the prototype channel, 12.316 exists, Foundry then asks for update notes and what not to flag the user about it and then gets the news data.
> 

[**NORC NOTE**: This matches what I heard from a user, who said they were able to bypass this issue by downgrading to 11.314 temporarily.]

 **Suggested solutions:**

- move news to a dedicated API end point, add an expiry date to it (API side, allows you to just control and tweak it as you wish with no update to Foundry installs), add logic to fetch news if expired or missing at select points (say start up and every time a world is closed).
- don't change [anything] server side, but force a full fat update check to get the news if missing locally.

**Comment by Spice-King** [comment]
Oh, worth double checking for `--noupdate`'s interactions with news. Should not impact it, but better to put it under inspection.

**Comment by Norc** [comment]
There is now a workaround for this issue:

**Workaround**

1. From Setup, click the 'Update' button, select the Prototype channel, and then click the 'Check for Update' button. A window containing information about the available update displays.

2. Close the window now by clicking the 'X' button in the upper-right corner. Please Note: We are not actually updating Foundry here, just using this update check to also force a check for the News content.

3. Return to Setup, click the 'Update' button again, select the Stable channel, and click the 'Check for Update' button.

4. Restart Foundry

**Comment by Norc** [comment]
Atropos determined that this is likely a website-side issue and deployed a fix that is promising in limited testing. Keeping open for a bit here, but there is likely nothing to do Foundry-side for this issue, despite initial appearances.

**Comment by aaclayton** [comment]
Believed to be resolved. Will reopen if evidence to the contrary emerges.
