### ISSUE TITLE
Removed the SHIFT behavior from the `Ruler`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10328]
## Implemented changes

We removed the SHIFT behavior of the `Ruler` entirely: holding SHIFT no longer has an effect on the ruler. Previously it switched to Euclidean distance when SHIFT was down.

### User Experience: When holding shift key, the Ruler should not snap waypoints/token to grid

Briefly discussed on [Discord](https://ptb.discord.com/channels/170995199584108546/811676497965613117/1193255670129107066). 

I would expect that holding "shift" would force the Ruler not to snap-to-grid. But instead it only seems to override the grid measurement setting so that if (for example, in dnd5e) you have 5-5-5 for the measurement, it will change to Euclidean. If you already are using Euclidean, it does nothing.

It seems like if you have a `moveToken`, then holding shift and moving the token with the ruler should correspond to holding shift and dragging the token. This would correspond to the expected behavior for holding "shift" when dragging tokens, templates, etc.

Thus, I recommend changing the default Foundry Ruler behavior to not snap waypoints or destination when holding shift.

**Comment by mkahvi** [comment]
Implementing this would make my [Unsnap Ruler](https://foundryvtt.com/packages/unsnap-ruler) module unnecessary, which would be nice.

**Comment by aaclayton** [comment]
With our grid and snapping changes in V12 we should probably revisit the behavior of the Ruler and make changes to (a) bring the UX into consistency with our other API changes and (b) improve upon any UX flaws that exist.

@dev7355608 this is not as high priority as other V12P2 work, but if you're looking for a small issue to pick up this could be a good one to evaluate.

**Comment by dev7355608** [comment]
We decided to remove the SHIFT behavior entirely (for now). If we allow measurements from any point to any point while holding shift (no snapping to grid space centers), we'd probably should use a distance function that matches grid measurements, i.e. grid space center to grid space center measurements with SHIFT down matching measurements with SHIFT up as the path that is measured is exactly the same. These distance functions aren't the Euclidean distance though: not in hex grids and not in square grids regardless of the diagonal rule used. Certainly having access to Euclidean measurement can be useful, but it should probably not be SHIFT behavior.

Let me know if you have thoughts on this.
