### ISSUE TITLE
Updating fill color doesn’t apply until drawing is moved

### ISSUE THREAD

**Issue by mrkwnzl** [foundryvtt/foundryvtt#10329]
### What happened?

When I update the fill color of a text drawing (both using the GUI or a macro using `document.update()`), the new color isn’t applied until the drawing is re-rendered (for example by moving it).

It seems to work when I do it the first time after it was moved, but not after that.

This might be related to #10325 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create text drawing.
2. Double click, go to Fill. Give it a fill color. Click save. It will probably work.
3. Double click again, got to Fill. Change the fill color. Click save.
4. It doesn’t update the color.
5. Move the text drawing. It now has a changed color.

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mrkwnzl** [comment]
In the meantime, because I actually want to use a macro to update the fill color, is there a way to re-render a drawing in a macro?

**Comment by Freeze023** [comment]
`canvas.drawings.draw()` redraws the drawing layer and should rerender the drawings.

**Comment by aaclayton** [comment]
This issue has been resolved already for V12. Closing as duplicate.
