### ISSUE TITLE
@Embed not working in chat messages due to replaceParent being true (v12 prototype 1)

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10338]
### What happened?

In `editor.js` `_enrichEmbeds` the `replaceParent` option is set to true.

Snippet:
```js
/**
   * Handle embedding Document content with @Embed[uuid]{label} text.
   * @param {Text[]} text                  The existing text content.
   * @param {EnrichmentOptions} [options]  Options provided to customize text enrichment.
   * @returns {Promise<boolean>}           Whether any embeds were replaced and the text nodes need to be updated.
   * @protected
   */
  static async _enrichEmbeds(text, options={}) {
    const rgx = /@Embed\[(?<config>[^\]]+)](?:{(?<label>[^}]+)})?/gi;
    return this._replaceTextContent(text, rgx, match => this._embedContent(match, options), { replaceParent: true }); // <-- this part
  }
```

Because of this the chat input `@Embed[JournalEntry.DSQM9mLokwFDNUeH.JournalEntryPage.46riMQ1pGoYmrwmA]` doesn't get embedded, however the input `<span>@Embed[JournalEntry.DSQM9mLokwFDNUeH.JournalEntryPage.46riMQ1pGoYmrwmA]</span>` or any similar HTML element for that matter; will work as it needs a parent to replace.

I noticed this difference while comparing it to `_enrichContentLinks`, locally removed the `{ replaceParent: true }` making it work as expected, and from my brief testing doesn't appear to impact Journal Pages.

I'd personally imagine this is unintended behavior and `@Embed` should work similarly to `@UUID`.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a Journal Entry + Page and copy the Page's UUID.
2. Paste this into an empty chat box: `@Embed[uuid-of-journal-entry-page]`
3. The message will not embed
4. Repeat step 2 but now with the following format: `<span>@Embed[uuid-of-journal-entry-page]</span>`
5. The message will embed
6. Remove `{replaceParent: true}` from `TextEditor._enrichEmbeds`
7. Repeat step 2, unlike before it will now embed.

### What core version are you reporting this for?

Version 12 (build 316)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl this should be a hopefully simple fix, but one you can look at related to the new `@Embed` functionality.

**Comment by dylanpiera** [comment]
@aaclayton @Fyorl Is this proofing more difficult than expected or is it flying under the radar?

It's a tedious issue for manually creating Embeds in chat during play.

**Comment by aaclayton** [comment]
This issue is on our V12 project board - so we certainly hope to accomplish it - but it is assigned priority `MEDIUM` which means its waiting in line behind a bunch of `HIGH` priority stuff which our team feels is more essential to address.

I hope we'll get to it!

**Comment by aaclayton** [comment]
@Fyorl let's take a look at this in the next milestone, since `@Embed` is a new feature it woul be good to clean this up before we call it stable.

**Comment by Fyorl** [comment]
Should be a relatively straightforward fix
