### ISSUE TITLE
Snap the Ruler origin to the hovered Token to improve measurements for Tokens that are unsnapped

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10331]
### User Experience

Ruler behavior when starting with an unsnapped token is confusing and inconsistent. 

Current behavior:
1.  Move a token so it is unsnapped (drag token with shift).
2. Go to the ruler tool, and start a measurement from the center of that unsnapped token.
3. The ruler will snap the origin to some grid center instead of the token center. 
4. As a result of (3), you may or may not be able to use spacebar to move the token with the ruler, depending on whether the ruler origin is within the token shape.

It would be preferable to have the ruler detect the token and start the origin point at the token center. I think this would probably be preferable even when the token is snapped, so that the ruler is always moving even larger tokens from the token center. 

To accomplish this, `Ruler.prototype._addWaypoint` needs to detect that it is adding the first waypoint and that a `moveToken` is present, and then use the token center instead of the snapped origin.

Related: Issue #10328.

**Comment by caewok** [comment]
Fair enough; I do think we both see the 4th item as a bug. The bug is a result of locating the movement token based on the (snapped) first waypoint instead of the originating mouse click. You could change the methodology for locating the move token without changing the initial waypoint snapping.

While I agree that the Ruler is used to measure grid spaces, it is an open question what should happen when a token is not snapped to a grid space. Perhaps measuring from the center of the clicked grid space is correct. Maybe if the Ruler UX was changed so that holding shift could unsnap the measurements (see #10328) then that would be the better overall approach: if not holding shift, then originate at the grid center; if holding shift, originate at the actual point clicked.

**Comment by dev7355608** [comment]
The behavior has changed. (4) does no longer occur. The token that was clicked when the measurement was started is moved even if the snapped origin isn't inside the shape of the token. The token is moved relative to the first waypoint to the destination of the ruler.

![ruler-unsnapped-token](https://github.com/foundryvtt/foundryvtt/assets/31905376/e2d09e55-3ef2-4aa3-9eac-2ff0d36ab461)

I'll keep this open for now. I haven't been able experimented yet how it would be if we used the center of the token as the origin for (unsnapped) tokens. It should be possible now that #10475 is completed. But it might be a bit more tricky to make this work with tokens larger than 1x1, in which case the center point of the token wouldn't be the right choice, I imagine.
