### ISSUE TITLE
In `PIXI.Rectangle.prototype.segmentIntersections`, return t0 for the {a, b} segment being tested

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10336]
### User Experience

The function `foundry.utils.lineLineIntersection` returns the `t0` percent along the segment a|b that the intersection occcurs. `PIXI.Rectangle.prototype.segmentIntersections`, however, returns the `t0` percent along the segment of the rectangle that the intersection occurs, not the `t0` for the  tested segment a|b. I recommend changing this, so that `PIXI.Rectangle.prototype.segmentIntersections` returns t0 for the tested segment a|b. 

When testing whether a segment intersects a rectangle, knowing at what point along the segment the intersection occurs is generally more useful than knowing at what point along one of the rectangle edges the intersection occurs. Particularly because you do not know—without further testing—which rectangle edge was intersected, so knowing the percentage along the rectangle edge is not useful in itself. On the other hand, knowing the percentage intersection along the tested segment can be useful. For example, you can use the `t` value to quickly construct some multiple of the a --> intersection distance. Or you can use the `t` values to determine the percentage of the segment that lies within the rectangle.

To accomplish this change, each of these lines would need to flip the order of the `lli` parameters. So from this:
```js
    if ( (z & CSZ.LEFT)
      && lsi(leftEdge.A, leftEdge.B, a, b)) ix = lli(leftEdge.A, leftEdge.B, a, b);
```

to this:
```js
    if ( (z & CSZ.LEFT)
      && lsi(leftEdge.A, leftEdge.B, a, b)) ix = lli(a, b, leftEdge.A, leftEdge.B);
   // For consistency, you could switch the order of the lsi parameters, but it is not really necessary.
```

For consistency, you may also want to define and return t0 values for the intersections when the segment is collinear with the horizontal or vertical edge. That would, however, require further calculations because those `t0` values are not calculated with this algorithm. An alternative would be to simply not define them and allow the user of the method to catch and define them as needed.

This would be a breaking change, but likely one with little impact. I did not see anywhere in the Foundry code that used `t0` values. As mentioned above, it is unlikely for someone to use the existing `t0` values because `t0` of the rectangular edge is not useful on its own.

**Comment by aaclayton** [comment]
Thanks for the detailed report. I think we can make this change for V12P2
