### ISSUE TITLE
Removed the drag distance threshold from `Ruler#_onMouseMove`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10337]
## Implemented changes

Removed the drag distance threshold from `Ruler#_onMouseMove`. The Ruler is still inherently limited by the `canvas.mouseInteractionManager.options.dragResistance` (default `canvas.dimensions.size / 4`), but this threshold is configurable.

### User Experience

In `Ruler.prototype._onMouseMove`, this line prevents the ruler from measuring before moving at least 1/4 of a grid space:

```js
if ( !this.waypoints.length && (distance < (canvas.dimensions.size / 4))) return;
```

I know this is opinionated, but it feels too long when first starting to measure with the ruler. Particularly if you are on gridless (and of course, depending on the underlying "grid size" used there). If you are measuring a small distance, it gets a bit tricky.

Please consider making the divisor configurable, at least so modules can change it. This also comes up if the module is using the Ruler for something else, like token dragging, for which that specific limitation makes less sense and can interfere with the intended action.

**Comment by aaclayton** [comment]
@dev7355608 a small and low-priority issue, but related to some other changes you've been making with ruler measurement if you care to take this on. I'm okay with us making the `4` configurable in some way (perhaps a static on the `Ruler` class like `Ruler.MEASURE_START_THRESHOLD` or something)
