### ISSUE TITLE
Update documentation of the `validationError` option of the `DataField` to clarify when it is used.

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10335]
### Where did you find it, or where does it belong for requests?

Code documentation comments (foundry.js)

### What page or file needs a look at?

https://foundryvtt.com/api/classes/foundry.data.fields.DataField.html

### What core version are you reporting this for?

Version 11 (build 315)

### What is wrong, in your opinion?

Currently in `DataField` subclasses such as StringField it seems that instead of returning 'false' when the validation fails an error is thrown with the message as to why it failed.

e.g.
```js
_validateType(value) {
  if ( typeof value !== "string" ) throw new Error("must be a string"); // <-- line in question
  else if ( this.choices ) {
    if ( this._isValidChoice(value) ) return true;
    else throw new Error(`${value} is not a valid choice`); // <-- line in question
  }
}
```

Based on the documentation this seems to be intended however; due to this `validationError` is unused, meaning you are unable to set custom error messages for a StringField with f.e. choices set. The documentation doesn't hint at the fact that `validationError` wouldn't work on built-in validators such as StringField's `choices` parameter. 

Suggestion: Either if `validationError` is set when throwing the error in a `_validateSpecial` or `_validateType` function append `validationError` or alternatively; replace the entire message with the `validationError` instance. 

If this is not something that will be pursued I'd instead suggest updating [the API Docs](https://foundryvtt.com/api/classes/foundry.data.fields.DataField.html) to state that `validationError` is only for a custom validator set using `validate`. 

Cheers!

**Comment by aaclayton** [comment]
You are correct that the `validationError` string is only used in conjunction with a boolean return type from the `validate` method.

**Comment by aaclayton** [comment]
I have updated the documentation for V12 to improve how this information is presented.
