### ISSUE TITLE
When a player views a journal of which they only have Observer permission, if they right-click a page (with inherited) permission, the TOC disappears

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#10358]
### What happened?

See title

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Be player
- Have observer permission of journal with Inherited Permission of page
- Right-click page in ToC
- watch it go bye bye.

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
We weren't able to reproduce this in v12, so it has potentially already been fixed.
