### ISSUE TITLE
HTML Sanitizations in certain descriptions

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/foundryvtt#10366]
### User Experience

Posted a while ago about an issue in the D&D5e system which ended up being blocked by a Foundry Issue; specifically this issue:

https://github.com/foundryvtt/dnd5e/issues/2394

Not sure if this was something that was covered already in an issue posted here, but I'm posting to maybe bring it to light. Issue itself was about HTML sanitization in Core and not being able to support complex formatting in some description fields.

**Comment by aaclayton** [comment]
Can you please share a minimal example of what you mean by "complex formatting" which the current sanitization does not support?

**Comment by Zanderaf** [comment]
It was more Arbron and Fyorl having a discusison about it, but at least in the example I gave when I made the initial issue for the D&D5e system, certain advancements in the system have "hint" boxes that allow text to be written, but not formatted at all. In the picture I posted in the original issue and below, theres no real way of adding in a line break, space, bold text, or similar text formatting.

![257077323-bdb54330-6c7d-4e2e-9cf2-a303bc8acd4b](https://github.com/foundryvtt/foundryvtt/assets/65571170/6b616e92-c9e4-42d3-bb12-70ecad2f7f21)

I'm not exactly sure about how prevalent this is in other systems, but I was directed here by Arbron and I don't exactly understand this much other than that its a core issue,

**Comment by aaclayton** [comment]
Sounds to me like that text is being rendered as plaintext rather than rendered as HTML. Without a working example of the sanitization issue there isn't anything for us to investigate here. Our core sanitization supports `<hr>` elements.

**Comment by krbz999** [comment]
The comment by Kim here (https://github.com/foundryvtt/dnd5e/issues/2394#issuecomment-1658814991) is the issue.
