### ISSUE TITLE
Relative document links render as broken when the html is rendered with enrich html

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#10371]
### What happened?

Relative document links render as broken when the html is rendered with enrich html

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create a journal with at least 2 pages
- Create a link on page 2 that references page 1
- Use some code to TextEditor.enrichHtml() on the page 2 contents
- The content link will be broken

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Are you passing the `relativeTo` option to `enrichHTML` so that it knows which `Document` to resolve relative UUIDs against?

**Comment by theripper93** [comment]
I'm doing

`const content = await TextEditor.enrichHTML(page.text.content, { secrets: game.user.isGM, relativeTo: page.parent });`

but at this point i suspect i'm doing something wrong

**Comment by theripper93** [comment]
Disregard, i realized i need to pass the actual document and not the parent
