### ISSUE TITLE
Use monaco-editor for editing script macros

### ISSUE THREAD

**Issue by ThiefMaster** [foundryvtt/foundryvtt#10384]
### User Experience

[monaco-editor](https://github.com/microsoft/monaco-editor/) is a standalone version of the nice editor that's used by Visual Studio Code.

Editing script macros would be much more pleasant with a sourcecode-focused editor compared to the standard one we have right now. It'd avoid the hassle of pasting between vscode (or any other editor) and foundry all the time.

**Comment by aaclayton** [comment]
If we add an integrated editor for JS code in the future it will almost certainly be CodeMirror <https://codemirror.net/> given the investments we have already made in use of ProseMirror for text editing.
