### ISSUE TITLE
Combat Turn/Round events are triggered whenever the Combat or any Combatant is updated

### ISSUE THREAD

**Issue by WBHarry** [foundryvtt/foundryvtt#10387]
### What happened?

Noticed this bug since it's become breaking for the system I'm currently working on.
I went ahead and made a completly empty system for testing purposes, and did nothing but extend the Combat class with a console.log in the `OnRoundStart` method.

https://github.com/foundryvtt/foundryvtt/assets/89362246/9cb44050-9073-4720-8bb9-efdebc12a222

I would expect `OnRoundStart` to only be called when the the turn or round is progressed to enable solid OnRoundStart logic.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Add a console.log or something to `onRoundStart` for detection purposes.
2) Start a combat in any system and have the combatant first in initiative order active. Click the 'Mark Defeated' button or do any other update to the combat or combatants.
3) Notice that onRoundStart is being called constantly. 😢 

It seems to stem from a check present in the Combat class methods: 
`_onUpdate`
`onCreateDescendantDocuments`
`onUpdateDescendantDocuments`
`onDeleteDescendantDocuments`

They all check for:
```
// Dispatch Turn Events
if ( options.turnEvents !== false ) this._manageTurnEvents();
```
In the video above, `onUpdateDescendantDocuments` is being called with options.turnEvents = undefined. Therefore it enters `_manageTurnEvents` since it strictly checks for anything but false.
Since the first combatant is active, it will then see that `current.round` != `previous.round` and therefore trigger `onRoundStart`.

Unsure if it can be fixed by just changing the check to look for a falsy value instead, but hoping this can be resolved as it breaks systems using onRoundStart logic 😄 

### What core version are you reporting this for?

Version 11 Stable (build 315)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This issue has been resolved in a V12 prototype release.

**Comment by dev7355608** [comment]
I'm still able to reproduce it in the current V12 branch. Run the following and begin a combat. It will result in unending start turn events.
```js
CONFIG.Combat.documentClass = class TestCombat extends Combat {
  /** @override */
  async _onStartTurn(combatant) {
    await super._onStartTurn(combatant);
    await combatant.unsetFlag("world", "test");
  }
};
CONFIG.debug.combat = true;
```
Or simply updating a flag of the combat or combatant triggers start/end turn events that already occurred.
```js
combatant.setFlag("world", "test", Math.random())
combat.setFlag("world", "test", Math.random())
```

**Comment by aaclayton** [comment]
Thanks @dev7355608, that helped me reproduce the issue. I worked on this for a while this afternoon and have implemented a solution which I think will work well for V12.
