### ISSUE TITLE
Remove support for `TokenDocument#effects` and `TokenDocument#overlayEffect`. Status effects on a Token are now handled entirely by Active Effects on the Token's associated Actor.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#10396]
This change meaningfully simplifies our code and removes some ugly edge cases for duplicate status icons. The major downside of this change is that Tokens which do not reference any actor are no longer permitted to use status effect icons. 

This does not seem like a meaningful drawback to us, but we will be monitoring community feedback and explore an alternative mechanism for having token markers in the future if something lightweight is absolutely required.

**Comment by coffiarts** [comment]
Is there (or will there be) any alternative way of adding overlayIcons to owned tokens? Because one of my mods depends on that functionality: https://github.com/coffiarts/FoundryVTT-lock-the-sheets

**Comment by aaclayton** [comment]
You can request that any active effect be rendered in an "overlay" style by setting the `core.overlay` flag to `true` on that ActiveEffect.

**Comment by coffiarts** [comment]
That sounds exactly like what I need, thank you very much! Will give this a try.
