### ISSUE TITLE
Document.updateSource with dry run option does not properly restore embedded data model sources.

### ISSUE THREAD

**Issue by DJ4ddi** [foundryvtt/foundryvtt#10395]
### What happened?

When FoundryVTT validates updates, it runs `doc.updateSource` with `dryRun: true`. My understanding is that the affected models should be unchanged after the operation is completed. However, this assumption is only true for `doc._source`. For embedded models, e.g. when using system data models, the `updateSource` method applies the change recursively using `DataModel.#updateData`, but does not restore it with `mergeObject(this._source, _backup, { recursive: false })`.

The expected behavior is that `this._source.system` is equal to `this.system._source` after a dry run update, which is not the case.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Use a system with custom actor data models.
2. Set a breakpoint at the start and end of `DataModel.updateSource`.
3. Update the actor's system data.
4. Observe how at the start of the method, `this._source` and `this.system._source` have matching data, but at the end of the method, `this.system._source` was not restored to its original state and still contains the change.

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks, will investigate!
