### ISSUE TITLE
CompendiumFolderCollection#updateAll errors unless you pass an explicit pack as its third argument

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10406]
### What happened?

Due to a lack of overrides, you end up with the error that `Folder id [16charString] does not exist in the Folders collection` because despite there's no override for `updateAll` like there is in `CompendiumCollection`

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

After making some folders in a compendium

```js
const collection = game.packs.get("world.my-compendium")

collection.folders.updateAll({color: "#ffffff"})
```

### What core version are you reporting this for?

Version 11.315

### Relevant log output

```shell
Uncaught (in promise) Error: Folder id [DW1t4vwdcIc2CRzn] does not exist in the Folders collection.
    at Folders.get (foundry.js:15329:36)
    at #preUpdateDocumentArray (foundry.js:13645:30)
    at ClientDatabaseBackend._updateDocuments (foundry.js:13449:73)
    at ClientDatabaseBackend.update (commons.js:8677:19)
    at async Folder.updateDocuments (commons.js:8001:23)
    at async Macro.eval (eval at #executeScript (foundry.js:22924:16), <anonymous>:13:1)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks, will get this fixed!
