### ISSUE TITLE
Request: Include token reference in updates coming from actor sheets for tokens

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#10407]
### User Experience

The built-in update calls to actors coming from actor sheets should include token UUID or similar reference in the update context when the sheet is for specific token (opened from a token, thus has `this.token` as non-null).

This would allow preUpdateActor/_preUpdate and such still maintain reference to the token in case I want to display the user visible name or similar info for linked actors.

All this would need is have the _updateObject() or whatever do something like the following:
```js
this.actor.update(formData, { token: this.token?.uuid });
```

**Comment by mkahvi** [comment]
It's for linked actors, too. Since some of their info may be different on a scene (mainly the token name).

For example, I have a module that reacts to character health and prints a chat message about it. Someone using that has decided to keep their identity secret by renaming the token. But when my code receives info about the damage being dealt, there's no longer any link to the token via which the damage was applied, so the printed message can not display the token's name since all reference to that has been lost by the time we reach preUpdateActor hook.

This also affects updates sent via the token resource inputs, too.

So, to summarize:
- Linked actor on scene, token name has been changed.
- Sheet opened via the token and modifications made via that, or via the token resource inputs.
- preUpdateActor and updateActor do not have any reference to this token.

I can usually handle this with actor.getActiveTokens() of course, and probably is sufficient for my use case, but if I were to have it handled by all users in different way, it quickly becomes more of a problem if they aren't on same scene. Also misbehaves if I have the same linked actor multiple times on the same scene for some reason.

The sheet retains the token reference for linked actors, so the update workflow retaining it as well seems useful for odd uses like these where the token identity retention is important.

**Comment by aaclayton** [comment]
The intended solution here would be to use `actor.getActiveTokens()` - as you mention different users may be on different scenes so it's important to verify whether a token for that Actor is present on their viewed scene or not before additional handling. For a linked `Token`, that token *is* the Actor, and for unlinked tokens, `actor.getActiveTokens()` will identify the specific unlinked Token.

I don't agree with the premise that "token identity retention is important". Our API provides sufficient methods and properties to know exactly which token or tokens represent an `Actor` and to recover that without the information needing to be passed through an update.
