### ISSUE TITLE
Use `prefers-reduced-transparency` media query to remove UI transparency

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#10405]
### User Experience

There are a number of places in the Foundry UI that have semi-transparent backgrounds. While these look nice, that can present issues for users with certain types of low vision or trouble parsing words on a busy background. Chrome recently added support for the `prefers-reduced-transparency` media query and it is in development on Firefox, so now would be a good time to start using that to optionally remove the transparency on those elements. Since unrecognized media queries are simply ignored by browsers, it would be an enhancement for Chrome users and not have any negative effect on users of browsers who don't yet support the option.

**Comment by aaclayton** [comment]
Related to https://github.com/foundryvtt/foundryvtt/issues/10400 which was also filed recently.

**Comment by aaclayton** [comment]
We'll be working on UI stuff later in the V12 cycle. Going to tag this for V12 API/testing phase investigation.

**Comment by aaclayton** [comment]
Comment from @kristianserrano

### What happened?

I noticed if an app window with the `.app.sidebar-popout` selector is displayed, my GPU takes a bit of a hit as indicated by the FPS meter. Disabling the style for `backdrop-filter: blur(5px);` improves the performance.

I think replacing the blur with a background color of black and an opacity of about 70% (`rgba(0,0,0,70%)`) creates a similar enough effect without the performance hit.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Depending on the GPU you might not see this result on your machine, but the steps mentioned above might reproduce it.

### What core version are you reporting this for?

Version 11 Stable 315

### Relevant log output

_No response_

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Added support for ApplicationV2 usage of `prefers-reduced-transparency` to change rendering of application instances.
