### ISSUE TITLE
Upgrade Font Awesome to 6.5.2

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#10409]
### What happened?

I get multiple warnings like this on Firefox:
![image](https://github.com/foundryvtt/foundryvtt/assets/3605541/78b67e8f-d3fd-40f8-a967-3911356e9206)

Probably this can be fixed by updating FA:
https://github.com/FortAwesome/Font-Awesome/issues/19925

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Log in
2. Open actor sheet

### What core version are you reporting this for?

v11.315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Version 12 is using Font Awesome 6.x which should resolve your issue. We do not plan any backports of Font Awesome upgrades to V11 or earlier.

**Comment by grz0** [comment]
The warning is still being reported on v12.318. The issue was [fixed in FA 6.5 ](https://github.com/FortAwesome/Font-Awesome/issues/19925#issuecomment-1882517540)but it looks that v12.318 uses FA 6.4,
