### ISSUE TITLE
Players can only see folders that they have permissions to in the Actors directory if there is an actor present

### ISSUE THREAD

**Issue by webmaster94** [foundryvtt/foundryvtt#10408]
### What happened?

The issue with this is that a when a GM creates a folder, they have to place something in there for the player to be able to see it to add their own creatures. This is a problem for GMs that want their players to be able to create their own actors and have given them that permission. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1. Create a folder
2. Change Ownership so that a player is an Owner or Observer
3. They will be unable to see or interact with the folder until an Actor is placed or created in it, even though they have permissions to it. 

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
In your step 2 there, you're not actually changing the ownership of the folder — when you right-click > Configure Ownership on a folder, you're doing a one-time bulk change on the permissions of the _documents within the folder_ (this is mentioned in the label text in that window).

**Comment by aaclayton** [comment]
Our folders don't have permissions themselves, just the contents within them, so this is a misunderstanding or otherwise a feature request extension of https://github.com/foundryvtt/foundryvtt/issues/4318

**Comment by webmaster94** [comment]
Okay. I think I understand now. I don't think I ever read the text because I assumed it just talked about what I thought the future already did. That is incredibly counterintuitive and definitely is an issue with UX. 

Basically, every other program handles folders as having permissions to inherit permissions to objects within them. I would definitely second that feature request.
