### ISSUE TITLE
ArrayField#_cast should support Set as an input value type which is converted to an array

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10418]
If a user passes a `Set` as their `initial` value for a `SetField`, it returns an error because `SetField#_cast` simply inherits from Array, so in the `_cast` process you end up with `[Set()]`. A simple fix would be something like:

```js
_cast(value) {
  if (getType(value) === "Set") {
     return Array.from(value);
  }
  return super._cast(value);
}
```

**Comment by aaclayton** [comment]
Agreed.

**Comment by JPMeehan** [comment]
Honestly if `ArrayField#_cast` is willing to parse an object with numerical keys as an array, there's an argument this parsing should just be in `ArrayField#_cast`.
