### ISSUE TITLE
`template.json` has been restricted to `Actor`, `Card`, `Cards`, `Item`, and `JournalEntryPage`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10424]
Sub-types of Documents that added sub-type support in V12 will need to be defined in the system's manifest instead of `template.json`. Sub-types of Documents that supported sub-types pre V12 (`Actor`, `Card`, `Cards`, `Item`, `JournalEntryPage`) may still be defined in `template.json` as before without deprecation warnings at this time.

**Comment by JPMeehan** [comment]
Is the long term plan here to move *all* document type definitions to the `system.json`?
