### ISSUE TITLE
Added support for status effects with static `_id` and implicit `statuses`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10431]
Status effects in `CONFIG.statusEffects` may now define a static `_id`, which is used to create the `ActiveEffect`. Status effects with a static `_id` can define implicit `statuses`, e.g:
```
{
    id: "paralyzed",
    _id: "paralyzed0000000",
    name: "Paralyzed",
    img: "paralyzed.svg",
    statuses: ["incapacitated"]
}
```
Status effects without static `_id` cannot define implicit statuses.

**Comment by FloRad** [comment]
Am I understanding correctly that implicit statuses means that other statuses with the IDs in the list are created as well?
Based off your example, the `paralyzed` effect would also create a second effect with the `incapacitated` id, resulting in a total of two `ActiveEffect` documents to be created?

**Comment by dev7355608** [comment]
> Am I understanding correctly that implicit statuses means that other statuses with the IDs in the list are created as well? Based off your example, the `paralyzed` effect would also create a second effect with the `incapacitated` id, resulting in a total of two `ActiveEffect` documents to be created?

It creates just the one ActiveEffect as usual but with the additional statuses.
