### ISSUE TITLE
Added `FogManager#isPointExplored`, which tests whether a canvas point has been explored by the current User

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#10433]
## Implemented changes

- Added `FogManager#isPointExplored`, which tests whether a canvas point has been explored by the current User.
- The exploration data used to test whether a point is explored is updated every 500 ms.
- When the explored area changes the `FogManager` (which is now an `EventEmitter`) emits the `"explored"` event. 

### User Experience

It would be nice if Foundry provided a method to test if a given canvas location was explored/unexplored. I think it would be fine if it used the current user for this test, although a more thorough approach would probably use the FogExploration collection and allow the query on a per-user basis.  Obviously, if fog of war was not active or the GM was the specified user it could simply return true to indicate the point is explored. 

Currently, my [Elevation Ruler module](https://github.com/caewok/fvtt-elevation-ruler/blob/9a896d8e0dabd80a4a119f21d84dcd4f1632f048/scripts/pathfinding/pathfinding.js#L638) is checking the user's fog texture in order to prevent pathfinding in unexplored areas:
```js
export function fogIsExploredFn() {
  // log("Checking for new fog texture");
  const tex = canvas.fog.exploration?.getTexture();
  if ( !tex || !tex.valid ) return undefined;

  const { width, height } = canvas.effects.visibility.textureConfiguration;
  const cache = CONFIG.GeometryLib.PixelCache.fromTexture(tex, { width, height });
  return (x, y) => cache.pixelAtCanvas(x, y) > 128;
}
```

(`CONFIG.GeometryLib.PixelCache.fromTexture` is something I use elsewhere to cache tile textures to test for transparency and to map paths accordingly. It is probably overkill here, but it was the simple answer for now. You can basically assume that it uses the canvas renderer to pull the fog of war texture pixels into an array.)

It would be preferable if Foundry provided this method, however, because Foundry knows when the fog is getting updated. I suspect it is necessary to cache the pixel array representing the fog of war to query it, like what is done for testing tile transparency in Foundry. Because Foundry knows when the fog of war is updated, Foundry could flag the cache as dirty and lazily update the cache the next time the `fogIsExplored` method is called. Also, correlating a given canvas point with a given texture pixel is not exactly straightforward, so this test may be out of reach of basic modules or even some systems.

An alternative might be to add some sort of notification whenever the user's fog texture is updated. This would be fine, except that if I am correct that you essentially need to cache the entire fog pixel array in order to test against given canvas points, then it could be a serious resource drag if several modules implemented such a cache. Plus, you still leave it to developers to implement the test correctly.

**Comment by aaclayton** [comment]
Useful suggestion, but below the line and out of scope for V12.
