### ISSUE TITLE
Make the template.json file optional, allowing systems to declare document types directly in their system.json manifest

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10444]
A number of important changes:

1. The "data model" that is being used is now stored at the overall `Game` level instead of at the `System` level. This data model includes all 3 of (a) core types, (b) system-defined types, (c) types defined by active modules. This is still referenced in the codebase as  `game.model`, just no longer as `game.system.model`.
2. The system `template.json` file is now optional, systems can define sub-types directly in their `system.json` manifest if they wish.
3. If the system does provide a `template.json` file, its declared types and type metadata are merged into `system.documentTypes` as part of system data preparation, this allows `System#documentTypes` field to be authoritative about "which types are defined by the system" for the purposes of things like obtaining a model provider. 
4. Sanitization info from the `template.json` file like `htmlFields` or `gmOnlyFields` are also merged into `System#documentTypes`, simplifying the identification of sanitization fields.
5. The `System#template` property is deprecated. There is not a need for it to exist since all the relevant information is now contained in `System#documentTypes` and `Game#model`.
6. When updating active modules, module-defined sub-types are now registered into `Game#model` as part of that workflow. Previously they were only added into `Game#documentTypes`.
7. Added a server-side global `getDocumentClass` method for symmetry with the client environment.

This gives us a much more robust and symmetric system for talking about package-provided document types and also makes `Game#model` a much more powerful and useful data structure.

**Comment by aaclayton** [comment]
> Will systems be able to define a data model for the "base" document type? What's the expectation for existing Active Effects, Combats, etc.?

No, the properties of the `base` data model cannot be configured. A system-specific sub-type must be registered and used.

**Comment by JPMeehan** [comment]
So what will the `type` field of existing AEs become?

**Comment by aaclayton** [comment]
> So what will the `type` field of existing AEs become?

Existing active effects remain as the `base` type unless migrated to some other type.

**Comment by aaclayton** [comment]
Updated the original issue with details of the change!
