### ISSUE TITLE
Server folder permission

### ISSUE THREAD

**Issue by seb9393** [foundryvtt/foundryvtt#10451]
### User Experience

If the permission to upload file is given to an user, the whole folder structure and files of the world will be visible. It would be great to have the possibility of selecting "user folders", thus player could upload their images, music and anything without seeing (and eventually modifying) the folders containing all the stuff related to the campain.

**Comment by aaclayton** [comment]
It is already possible for the GM or server admin to mark certain folders as hidden from players.
