### ISSUE TITLE
Update pdfjs to version 4.x

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#10459]
### User Experience

In order to provide better support for PDFs, could Foundry V12 have the pdfjs library updated to the latest stable 4.x version?

I've been doing some checking with my own PDF Pager module on V12 prototype 2, and pdfjs library 4.0.379 (the latest available on github) works better for at least one PDF whose first page was just a big solid black on Foundry's current version of pdfjs.

**Comment by aaclayton** [comment]
@Fyorl I know we have to handle this in a special way. Could you evaluate the feasibility of upgrading our PDFJS fork to 4.x?
