### ISSUE TITLE
Delete files from world

### ISSUE THREAD

**Issue by seb9393** [foundryvtt/foundryvtt#10452]
### User Experience

It would be great to have the possibility to delete folders and files inside the world. This is particularly useful when the world is self hosted, for example, in a raspberry Pi. At the state of the art, in this configuration, to delete a file uploaded by mistake, it is necessary to access the server by ssh, sftp or similar and the procedure is quite annoying.

**Comment by JPMeehan** [comment]
If this is added, definitely need an additional set of permissions separate from upload.

**Comment by seb9393** [comment]
> If this is added, definitely need an additional set of permissions separate from upload.

Definitely it would be needed. This is indeed linked to the issue #10451
