### ISSUE TITLE
Disable Electron app built-in spellchecking

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#10454]
### What happened?

Electron's spellchecker is toggled on by default and uses the OS's native language.
That's probably fine 99% of the time on English OSes, but it's an awful experience on non-English OSes, especially for things like Macro editing and anything that requires writing in a language that isn't native to the OS.

Solution: toggle it off by default. Add a setting to toggle it on for whoever needs it.

Example:
![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/38cce582-a974-4886-9cf8-e85f15a2fb59)
Absolutely unreadable.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Load FoundryVTT's Electron app on a non-English speaking system.
2. Write or edit a macro, edit a roll table or journal (on ProseMirror) written in English.

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Is this a new feature in a more recent Electron version? Have I just never noticed it? I'm questioning why this hasn't come up before.

**Comment by mclemente** [comment]
> Is this a new feature in a more recent Electron version? Have I just never noticed it? I'm questioning why this hasn't come up before.

According to the [documentation](https://www.electronjs.org/docs/latest/tutorial/spellchecker#how-to-enable-the-spellchecker), it has been that way since version 9 (May 2020), so it should have been around since Foundry V7 (Electron 9.1).

I think it has gone unnoticed because TinyMCE has the spellcheck attribute off (ProseMirror doesn't), so it could only be spotted while writing macros in a non-English system until V10.
Even without the spellcheck attribute, I doubt there are that many users that write journals in English if it isn't their native tongue.

**Comment by Norc** [comment]
I have seen this issue exactly once before, in the customer support emails a few months ago. It doesn't seem to happen very commonly, and it's even rarer for someone affected to be motivated enough to reach out to us I think (and we are glad that you did, thanks!)

**Comment by tslays** [comment]
I am on macOS and Foundry Electron (newest) version and I have this problem in my Journals with custom character names.
It is really distracting to write down your newly invented character and location names (which are of course fantastic and in no dictionary) and get them underlined in red. This is not just a problem for developers but also players like myself. 
Please make sure to turn this off for good. An option to turn back on could be helpful but the default should be off.

**Comment by aaclayton** [comment]
Not to myself for later - looks like in Electron > 8 this needs to be done by manipulating the session attached to the electron window: https://www.electronjs.org/docs/latest/api/session
