### ISSUE TITLE
Add button to Compendium app header to copy ID

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10466]
### User Experience

As a power user, grabbing the full ID of a Compendium can be obtuse. It would be easier if there were a header button similar to the one for Documents that grabbed the compendium's ID.

Possible extension: This *could* use the alternate left/right click controls that documents get, although I'm unsure what use *just* the `name` field would be useful for.

**Comment by krbz999** [comment]
(Related: https://github.com/foundryvtt/foundryvtt/issues/9848)

**Comment by aaclayton** [comment]
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/9848
