### ISSUE TITLE
The {#select} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or one of the new helper functions in the foundry.applications.elements module

### ISSUE THREAD

**Issue by Alkali-Metal** [foundryvtt/foundryvtt#10471]
### User Experience

Currently the `select` Handlebars helper requires that a space character comes before `value=`, this works fine in the following cases:

1. The value is inline
2. The value is on a newline, using spaces for indentation

However if the `value=` is on a newline, using tabs for indentation, the helper fails to find the value completely and has no indication for what could be going wrong. This would be useful to have because for those developers in the community that use this helper and also use tabs to indent code this can lead to spending a while trying to figure out why the helper is not correctly selecting the `option`.

---

I would like to request updating the Regular Expression used in the `select` helper in one of the following ways:

1. Remove the space requirement
2. Allow any whitespace character (`\s`) instead of just a space
3. Allow a space or a tab (`[ \t]`)

Alternatively, an update to the documentation stating the assumption that `value` is preceeded by a space would help, but I'd like to see the RegEx updated instead.

**Comment by aaclayton** [comment]
Could you post an example (or examples) of your HBS syntax and the generated HTML that results?

**Comment by aaclayton** [comment]
Thanks for the clarification. I'm internally trying to retire the `{{select}}` helper (we don't use it at all) so it *might* end up being a case where you take this over as a module-specific helper if you need it. Given your existing HTML markup, this helper isn't really doing much for you that you couldn't accomplish in other ways which don't produce any error. For example, if you already have properties on each `die` like `die.disabled`, you would be better served with simply passing in `die.selected` as another property of each option.
