### ISSUE TITLE
Convert TokenConfig to ApplicationV2

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#10482]
### User Experience

Token rotation is for some reason found in the **identity** tab. It would make much more sense on the _appearance_ tab. Please move?

**Comment by aaclayton** [comment]
This would be nice to do, but we don't have time in V12. This will be picked up in V13 as high priority when we move it to AppV2.

**Comment by anathemamask** [comment]
Related: #11342 

Complex but notable related to canvas previews: #7163

Related issues that may be worth consideration:
#11261 
#11222 
#10625 
#10453
#10344
#10317
#7417
#7294
#5698
#5024
#2439
