### ISSUE TITLE
Set and get static FilePicker property `LAST_TILE_SIZE` consistently

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#10485]
### What happened?

Originally reported here: https://github.com/foundryvtt/foundryvtt/issues/9908, I've made a new issue since substantial time has passed since the original ticket was closed.

When using the Tile Browser on The Forge updating the Asset Grid Size doesn't work properly.

This happens on The Forge because Forge extends FilePicker, and the FilePicker static property `LAST_TILE_SIZE` is handled inconsistently in the base class.

Setting the Tile Browser Asset Grid Size sets `this.constructor.LAST_TILE_SIZE` (set on extended class constructor), but that property is then later referenced through `FilePicker.LAST_TILE_SIZE` (references base class constructor property).

In contrast, `LAST_BROWSED_DIRECTORY` always uses `this.constructor` and works correctly.

Please see reproduction steps for screenshots.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a class that extends `FilePicker`.
2. In the base class `FilePicker`, `LAST_TILE_SIZE` is updated via `this.constructor.LAST_TILE_SIZE`, which correctly sets the property on the constructor of the extended class, as expected.
![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/8116be95-703a-4ad8-be35-8bf9e854bffe)

3. However, when trying to reference `LAST_TILE_SIZE` later, the reference is made directly to `FilePicker.LAST_TILE_SIZE` instead of using `this.constructor.LAST_TILE_SIZE`, leading to the extended class not accessing the updated value.
![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/ca13adca-6f69-4d67-b106-85df3df79ae3)
![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/35eafd3a-3d44-425d-a22a-e369043a805c)

4. In contrast, another static property `LAST_BROWSED_DIRECTORY` always uses `this.constructor` for both setting and getting, ensuring the property is correctly scoped to the instance's constructor (the extended class in this case), demonstrating the expected and consistent behavior.
![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/91114ce3-fb7a-4539-9eea-a6f2e7f852ab)

### What core version are you reporting this for?

v11.315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hi @rikmarais thanks for explaining the prior issue more succinctly. That's an easy change that we'll add to our next v12 update.
