### ISSUE TITLE
`@Embed` could just check for `this.system.toEmbed`

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#10490]
### User Experience

In `ClientDocumentMixin#_buildEmbedHTML` there is a test for `this.system instanceof foundry.abstract.TypeDataModel`, but it would be more useful to allow expansion in systems if this test simply checked for the presence of `this.system.toEmbed` (since that is the only function call which is protected by this test.

This would allow system/module developers simply to provide a `toEmbed` method to get `@Embed` to work correctly for their data types.

**Comment by JPMeehan** [comment]
The general goal seems to be that everyone should be using TypeDataModel — it doesn't carry any downsides since it's not overriding functionality. You can also see this in the change to prepareDerivedData.

**Comment by farling42** [comment]
Some game systems will take a long time to switch from template.json to using the new data models.

But your explanation still didn't change the fact that that particular code line could more directly check for the presence of the function it is about to call, rather than relying on the object being of a particular class.
