### ISSUE TITLE
Allow players to update the Combat combatants array for combatants which they have permission to modify.

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10501]
### What happened?

My system has quite the involved alterations to the Combat Tracker, in our case the turn never advances, instead the initiative of combatants update to show the progress of initiative.

To save on trips to the database we calculate the update to all the combatants and if required update the round:
```js
nextTurn() {
    const updateData = this._prepareTurnUpdateData();
    return this.update(updateData)
}
```
updateData is either `{combatants: [/*Array of Combatant updates*/]}` or `{round: Number, combatants: [/*Array of Combatant updates*/]}`

This works fine when the GM calls `nextTurn()` however when a non-GM account tries to call `Combat.update` with the `combatants` property it fails.

If we take a look at `BaseCombatant#canUpdate` we can see that `initiative` is an allowed key, hence when we call either `Combatant.update({initiative: 5})` or `Combat.updateEmbeddedDocuments('Combatant', [{_id: 'combatant-id', initiative: 5}])` it works fine, however if we try to call `Combat.update({combatants: [{_id: 'combatant-id', initiative: 5}]})` it fails.

![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/6eebb4a4-9e72-4cfe-b17b-ee4ff069de81)

I tried putting breakpoints in both `Combat#canUpdate` as well as `Combatant#canUpdate` but it seems neither are hit in this case? 

Is this something that can be resolved with a Foundry update or is this a limitation with the DB engine that can't / is too much of a pain to fix?

In the meanwhile I'll just have to warp it in a `if(game.user.isGM)` call the single update, else run `Combat.updateEmbeddedDocuments` + `Combat.update` separately, so I can work around this, but it seems like behavior that *should* work.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a Combat with at least one combatant, make sure the Combatant's actor is not owned by anyone (or at the very least the test player account you will be using)
2. Grab the Combatant ID
3. As a non-GM account run:
  - `game.combat.combatants.get("the-id-from-step2").update({initiative: 5})` -> Success
  - `game.combat.updateEmbeddedDocuments('Combatant', [{_id: "the-id-from-step-2", initiative: 10}])` -> Success
  - `game.combat.update({combatants: [{_id: "the-id-from-step-2", initiative: 15}]})` -> **Fail**
4. Do the same on a GM account and all will Succeed.

### What core version are you reporting this for?

Version 12 Prototype 2 (12.317)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dylanpiera** [comment]
@aaclayton To confirm, was the resolution this the inverse of what I hoped for? 

The code suggested that players are allowed to update the `initiative` `flags` `defeated` and `system` properties for any Combatant, even those they do not own, the server however rejected this.

I can see in the latest v13 the `#canUpdate` call has been updated to first perform a `testUserPermission` call.

So was it always intended to NOT allow players to update initiative of other combatants and the `#canUpdate` call was wrong, or has since me bringing this to light it been decided that players shouldn't be allowed to do it, or was this fixed wrong?

I was personally hoping for players to be allowed to edit these fields (specificially `initiative`) so I can allow players to end their turn in my system without having to route the call through a socket to the GM.

**Comment by aaclayton** [comment]
It's not permitted for a player to update the initiative for a combatant they don't own - this is an intentional limitation so you'll need to work around it in some other way - depending on your exact needs.

It sounds like your system requires a combatant to get a new initiative value at the start of their turn? Is that correct? If you provide a little bit more information about what is supposed to happen for your gameplay needs I can perhaps provide a more useful direction or advice.
