### ISSUE TITLE
Errors thrown by DOM functions can cause Hooks.onError to obscure the original error with its own

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10534]
Originally reported by manaflower https://discord.com/channels/170995199584108546/1065764070680186930/1206859849262960660

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: Errors thrown by DOM functions can cause Hooks.onError() to scrap the error and error itself.
**Simple steps to reproduce the bug**:
```js
static get defaultOptions() {
  return {
    ...super.defaultOptions,
    tabs: [
      {
        contentSelector: "section.tabs",
        navSelector: "nav.tabs[data-group'bad']",
      },
    ],
  }
}
```
**Screenshots and/or console errors**:
Instead of the error produced by the bad selector, you instead produces this:
```
foundry.js:752 Uncaught (in promise) TypeError: Cannot set property message of  which has only a getter
    at Hooks.onError (foundry.js:752:30)
    at foundry.js:5771:13
```
Which is from onError line:
```js
if ( msg ) error.message = `${msg}. ${error.message}`;
```
Actual error it should've shown is something more like:
```
Application#render DOMException: Failed to execute 'querySelector' on 'Element': 'nav.tabs[data-group'bad']' is not a valid selector.
```

**Comment by mkahvi** [comment]
Easy solution should be something like
```js
const err = new Error("Bad Stuff Happend", { cause: originalError })
```
Instead of modifying the original error.
