### ISSUE TITLE
Suppress the "Delete All" context option for Folders of the Compendium type since contained compendium packs cannot be deleted in this way.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10533]
Originally reported by muhammad2126 https://discord.com/channels/170995199584108546/1065764070680186930/1201894551149871114

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows 10, Foundry client.
**Short Description of bug**: Using the Delete All button in a compendium folder deletes only the folder while keeping the compendiums there (basically doing the same thing as the Remove Folder button.
**Simple steps to reproduce the bug**: make a folder in the compendiums tab, add a compendium to it, right click the folder and click Delete All.
**Screenshots and/or console errors**: -

This was tested in a fresh world in the Foundry client, Foundry version 11.315.

**Comment by aaclayton** [comment]
I don't think we want this to be an option at all for compendium packs. We should suppress the "Delete All" option from folder context in cases where the folder is a Compendium type.
