### ISSUE TITLE
Two users moving the same token simultaneously can cause one user to become out-of-sync and see double tokens

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10538]
Originally reported by manaflower https://discord.com/channels/170995199584108546/1065764070680186930/1210609346740756490

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: Two users moving same token simultaneously causes one user to get out of sync and get doubled tokens.
**Simple steps to reproduce the bug**:
Move same token at the same time by two different users to different locations. May require notable latency (e.g. 200ms or worse on at least one user involved).

Can easily happen when player moves their token and GM moves them also to correct their position.

**Comment by Fyorl** [comment]
I would expect some 'rubber-banding' perhaps in a high latency environment, but not a case where an entirely new token appears.

**Comment by Nordiii** [comment]
Had a similar issue last week, dragged a token while the player also moved. Now there was a none selectable duplicate on my end and I needed to reload the page.

Hosted on an raspberry pi at home, so latency could also be a problem.

**Comment by Norc** [comment]
I have also seen this happen in the wild... I believe it occurred in v12 Prototype 2 with DND5E 3.1.

Just like Nordiii, my player went to move the token (by the arrow keys, I believe) at the same time I (the GM) clicked the player and dragged it to a new location (across a wall, I believe). This is a screenshot I took of the result of this issue and forgot to share earlier, sorry:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/125eb018-5550-460e-8573-96f7fa4fc5d3)

A page refresh deleted the "extra" token. I don't believe a hard-refresh was required. Checking to see if anyone else could see the extra copy or if it was just me, I'll update.

**Comment by krbz999** [comment]
We have a very easy time reproducing this by just having user A dragging the token (preview active), user B dragging and dropping the same token, and then user A finally dropping theirs.

**Comment by aaclayton** [comment]
We will prioritize an investigation of this issue during the user testing phase before v12 goes stable.
