### ISSUE TITLE
Old-style document links don't open

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#10535]
### What happened?

Old style links, such as `@Item` and `@Compendium` do not open the referenced document when clicked.

The HTML is different between old-style and new style links.
![image](https://github.com/foundryvtt/foundryvtt/assets/17485384/4222bd4a-6ded-454e-9122-312b4a07dbed)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create a link using the old style syntax, such as `@Item` or `@Compendium`
- The presentation appears correct in the journal page.
- Clicking on the displayed button does nothing; no error is reported in the browser console.

### What core version are you reporting this for?

12.318

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by farling42** [comment]
A quick patch in the browser console shows that adding `data-link` as an attribute to the `a` element gets the link to work.

**Comment by aaclayton** [comment]
Escalating at high priority for testing 3
