### ISSUE TITLE
Cannot change TableResult images by clicking on them in the RollTableConfig

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10536]
Originally reported by gwengreenears https://discord.com/channels/170995199584108546/1065764070680186930/1208961301888499712

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows, Forge
**Short Description of bug**: Cannot change rollable table image of compendium entries by clicking on image.
**Simple steps to reproduce the bug**: Create new rollable table, place new entry from compendium, click on image, where nothing happens.

**Comment by stwlam** [comment]
The change made here was to remove the image edit listener for document and pack results (thus not giving the impression they can have their images changed) but also to keep the images of such results in sync with their referenced documents.
