### ISSUE TITLE
UserConfig's size does not account for the player character image as it has not loaded at render time

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10549]
Originally reported by chaosos https://discord.com/channels/170995199584108546/1184176415139184731/1218010013931536535

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Node Windows, Localhost, Chrome
**Short Description of bug**: Opening the UserConfig after an actor has been selected cuts off the bottom
**Simple steps to reproduce the bug**:
1. Assign an actor and then Save Configuation
2. Re-open it
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/7492d96c-3d81-4405-84c5-a562ebcb17e6)

**Comment by aaclayton** [comment]
Resolved by changes to AppV2 auto resizing.
