### ISSUE TITLE
ArrayField inner schema is not validated correctly under some circumstances

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10541]
Originally reported by amediocredad https://discord.com/channels/170995199584108546/1065764070680186930/1210766379486289920

Validation logic in the `ArrayField` is flawed in that an update to a document triggered by a `submit`-event will lead to a `partial`-flag set during validation. Thus even if validation fails in the `ArrayField` this is considered `unresolved: true` when the error bubbles high enough, leading to an invalid `ArrayField` being created. This can be confirmed by creating a datamodel like this:
```js
export class DataData extends foundry.abstract.DataModel {
  static defineSchema() {
    const fields = foundry.data.fields;
    return {
      myArray: new fields.ArrayField(new fields.SchemaField({
        one: new fields.StringField(),
        two: new fields.StringField({ required: true, nullable: false }),
      }))
    }
  }
}
```
Then a form like this to update:
```
<form>
  <input type="text" name="system.myarray.0.one" placeholder="Name" />
  <input type="text" name="system.myarray.1.one" placeholder="Name 2" />
</form>
```
The expected outcome is that foundry should fail to update the underlying document. Instead the document ends up like this:
```js
system: {
  myArray: [
    { one: "<>", two: undefined },
    { one: "<>", two: undefined },
  ]
}
```

**Comment by Fyorl** [comment]
I modified the above to prepare a slightly more succinct script that will demonstrate this:

```js
(function() {
  class DataData extends foundry.abstract.DataModel {
    static defineSchema() {
      const fields = foundry.data.fields;
      return {
        myArray: new fields.ArrayField(new fields.SchemaField({
          one: new fields.StringField(),
          two: new fields.StringField({ required: true, nullable: false }),
        }))
      };
    }
  }
  const d = new DataData();
  d.updateSource({ myArray: { 0: { one: "foo" }, 1: { one: "foo" } } });
  console.log(d);
})();
```

Because the update is processed with `partial: true`, the array elements are validated as though they were updates to existing elements, but they are, in fact, *new* elements being added to the array.

**Comment by aaclayton** [comment]
Fixed by https://github.com/foundryvtt/foundryvtt/issues/10401
