### ISSUE TITLE
Allow the DoorControl class to be configurable via `CONFIG.Canvas.doorControlClass`

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#10559]
### User Experience

I thought it's just me, but in truth there are many people doing a "WRAPPER" of the DoorControl methods like "DoorControl.prototype._onMouseDown", since I'm not good enough to sync with all the other modules  can we add some methods to be called ? also hooks "preMouseDown" and "postMouseDown" would be appreciated.

For clarity here is a list of the api methods I need on the DoorControll:

- `DoorControl.prototype.open(options)`, try to 'open' the door with the current user
- `DoorControl.prototype.close(options)`, try to 'close' the door with the current user
- `DoorControl.prototype.lock(options)`, try to 'lock' the door with the current user
- `DoorControl.prototype.unlock(options)`, try to 'unlock' the door with the current user
- `DoorControl.prototype.modify(options)`, try to 'modify' the door with the current user, for example make the door controll a secret door or a window

The `options` is a set of settings such as emulates left-click opening (MouseDown) or right-click opening (RightDown), for example:

```
options = {
   isMOuseDown: true,
  isRightDown: false
}
```

or as a alternative for help the developers maybe a more generic and simple solution is to add some hook in general for any placeable object:

- `Hooks.call("placeableObject.preMouseDown", this, config) `
- `Hooks.call("placeableObject.mouseDown", this, config) `
- `Hooks.call("placeableObject.postMouseDown", this, config) `
- `Hooks.call("placeableObject.preRightDown", this, config) `
- `Hooks.call("placeableObject.rightDown", this, config) `
- `Hooks.call("placeableObject.postRightDown", this, config) `

that's what I thought, but there are probably better solutions

**Comment by aaclayton** [comment]
I think the solution here is to allow the entire `DoorControl` class to be swapped to a different class. We currently do:
```js
this.doorControl = canvas.controls.doors.addChild(new DoorControl(this));
```
We should instead do something like:
```js
this.doorControl = canvas.controls.doors.addChild(new CONFIG.Canvas.doorControlClass(this));
```
Obviously only one module can ultimately have control over who is responsible for DoorControl logic, but this is my preferred pathway to adding a large number of hooks.
