### ISSUE TITLE
`Token._refreshVisibility` sometimes throws an error, preventing newly-dropped Tokens from being drawn on the canvas

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10550]
Originally reported by alexdiste https://discord.com/channels/170995199584108546/1184176415139184731/1218098999253270620

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Self- Host
**Short Description of bug**: Sometimes I cannot drop token on canvas
**Simple steps to reproduce the bug**: I am not sure how to reproduce because is happened randomly seems. First time I was in adventure Phandelver and below and dropping PC from SRD (pregenerated) to scene (old well) and after deopping first 2 I was not able to drop any more. I mean I rop them but Canvas is not refreshed and I saw an error message in console. Second time was a new create world with new version of foundry without any modules, I was in the "nue" map, dropping pc from SRD and after a while I receive error in console
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/fe8e8ad3-96cb-4683-a285-88da71e5f981)

**Comment by Fyorl** [comment]
Unable to reproduce this but logging it in case the stack trace gives some hints as to how this error state can be reached

**Comment by alexdiste** [comment]
I also am unable to reproduce costantly but it happens in 2 different worlds (one migrate and one completely new) in fisrt 5 minutes of testing. So seems to be a race condition that happens only in same cases
