### ISSUE TITLE
`game.system.documentTypes` type has changed

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10553]
Originally reported by awake42 https://discord.com/channels/170995199584108546/1184176415139184731/1218212199512674414

**ALL MODULES DISABLED?** true
**Short Description of bug:** Changed dataformat for game.system.documentTypes (breaking change)
**Simple steps to reproduce the bug:** game.system.documentTypes.Item returned an `string[]` in v11, but in v12proto2 it returns an object:
```js
{
    "armor": {},
    "cult": {},
    "gear": {},
}
```

**Comment by Fyorl** [comment]
I was able to verify that in v11 we had a `BaseSystem#documentTypes` getter that just returned `game.documentTypes`.

**Comment by aaclayton** [comment]
I think this change is unavoidable now that `documentTypes` is an `AdditionalTypesField` in the system data model. We simply need to flag it as `breaking` on the prior issue https://github.com/foundryvtt/foundryvtt/issues/10444
