### ISSUE TITLE
Module-defined sub-types remain in `game.documentTypes` after the module has been disabled until the world is restarted

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10567]

**Comment by aaclayton** [comment]
I assume this actually causes some problem? I was aware that this would be the behavior but I assumed that having a super-set of information about types would not cause an issue. I probably overlooked something. What is the problem that arises?

**Comment by dev7355608** [comment]
If the type remains in `game.documentTypes`, documents with this sub-type won't fail validation. This what it looks like after disabling the module that defined the sub-type in the case of Region Behaviors:

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/c1414fe8-8dde-4518-a4a4-19032531f8c8)
