### ISSUE TITLE
Replace custom transforms to canvas coordinates with canvas.stage.toLocal for completeness.

### ISSUE THREAD

**Issue by digitalpacman** [foundryvtt/foundryvtt#10561]
### What happened?

When a module applies transforms on the canvas, mostly rotation and skew, the drag and drop math for interaction between cursor and canvas calculates incorrect coordinates.  The math is hard coded for scale and transform only, lacking other transforms.  This should be able to be solved by using PIXI as such:  this.stage.toLocal(new PIXI.Point(x, y))

This was discovered using grape juice isometric module.  In v11, the drag and drop features stop working after grape juice isometric applies transforms to the canvas.

The likely culprit is the following code:

` _onDrop(event) {
    event.preventDefault();
    const data = TextEditor.getDragEventData(event);
    if ( !data.type ) return;

    // Acquire the cursor position transformed to Canvas coordinates
    const [x, y] = [event.clientX, event.clientY];
    const t = this.stage.worldTransform;
    data.x = (x - t.tx) / canvas.stage.scale.x;
    data.y = (y - t.ty) / canvas.stage.scale.y;`

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1.  Install the module grape juice isometric.  
2. Change scene to be isometric by going to properties, isometric tab, enable isometric.
3. Create a PC, put the token onto the map.
4. Execute the intimidation macro.
5. Drag and drop the frightened condition onto the PC token

### What core version are you reporting this for?

Version 11 Build 315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@dev7355608 I'll let you take this one - should be a small and simple change!

**Comment by digitalpacman** [comment]
Any chance for a v11 fix?
