### ISSUE TITLE
Consider providing a way to cache a set of compendium documents prior to world document construction in `Game#setupGame`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#10560]
### User Experience

Some systems currently employ a custom asynchronous data migration strategy that allows fetching compendium `Document`s, primarily items, for the purpose of data updates or replacement. In the synchronous `DataModel.migrateData` method, achieving that is not possible.
By introducing a preloading step before constructing the world documents, these compendium documents can be fetched from the server and cached locally. This would enable the use of `fromUuidSync` during the `migrateData` process.
This could be done by providing a new `CONFIG` property that allows specifying an array of compendium UUIDs that should be preloaded from the server.

**Comment by aaclayton** [comment]
Rather than approaching this directly as requested, I'm going to merge this in with #8476 as a feature request for what a centralized client-side migration framework might need to support.
