### ISSUE TITLE
Switch PM2 for Systemd

### ISSUE THREAD

**Issue by ChaoticEvilDM** [foundryvtt/foundryvtt#10576]
### Where did you find it, or where does it belong for requests?

Knowledge Base (https://foundryvtt.com/kb/)

### What page or file needs a look at?

https://foundryvtt.com/article/installation/

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### What is wrong, in your opinion?

Issue: It's not advisable to install a secondary process manager in order to run a single process. This might cause additional security issues and/or concerns, especially when a default linux system is already outfitted with the necessary tooling to daemonize a process. Recommendation is to remove the mentioning to PM2 and use a systemd service **for single instance** applications. In case a cluster of installations is run, pm2 is preferred.

Solution:
Warning! This currently depended on pathing based on a user specific installation. See [here](https://github.com/foundryvtt/foundryvtt/issues/10575).
For debian based systems, create the following file
/etc/systemd/system

[Unit]
```
Description=foundryvtt
Documentation=https://foundryvtt.com/kb/
After=network.target

[Service]
Type=simple
User=foundryvtt
ExecStart=/usr/bin/node /home/foundryvtt/foundryvtt/resources/app/main.js --dataPath=/home/foundryvtt/foundrydata
WorkingDirectory=/home/foundryvtt/foundryvtt
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Then issue:
```
systemctl daemon-reload
systemctl start foundryvtt
```

If you wish for foundry to be started by default:
`systemctl enable foundryvtt`

**Comment by anathemamask** [comment]
Not all linux distros use systemd. PM2 can be installed on any OS.

**Comment by ChaoticEvilDM** [comment]
Installing a secondary low level process manager for a single application is bad practice from an integration point of view. I respect the different opinion, but complete denial to further better the integration into possible existing infrastructure by amending the documentation to offer systemd as an option for process management is bad integration practice. This was already foretold [here](https://twitter.com/grauhut/status/1769074185828024724).

As this is possibly a security risk, especially for low level linux users, I will create an addendum to the pentest report for foundry that is currently being created.

**Comment by aaclayton** [comment]
To be honest, I'm not sure that we should be recommending either. I think Linux users should be able to choose if and whether they want to govern Foundry VTT's execution using a process manager or service configuration. This is definitely not required and I'm not sure that we should endorse any particular approach beyond providing instructions on what is required to launch the server in the first place.

**Comment by ChaoticEvilDM** [comment]
Very simple:

Large cluster with lots of nodejs related applications (e.g. a few foundryvtt instances) -> PM2
Standalone on linux system -> systemd

Reasoning is that running a cluster is always easier when using proper cluster management tool and pm2 provides sufficient tooling in an around it (Logging, Monitoring, hookup into various third party systems, aso.).

This overhead and possible path for program execution, following the reasoning "If you don't need it, don't install it because it can be a security factor" is not required for a single instance. Systemtools need to fit the required job, not vice versa. You should always aim at minimizing the attack surface of any system, especially when you open a fixed port on all interfaces per default.

Just probing with shodan shows a multitude of instances...

**Comment by aaclayton** [comment]
Made some updates to the https://foundryvtt.com/article/installation/ article to recommend either systemd or pm2 depending on your use case. Fixed a number of other small improvements along the way.
