### ISSUE TITLE
Make `ChatLog._renderBatch` use `this.collection.contents` instead of `game.messages.contents`

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/foundryvtt#10588]
### User Experience

The issue pertains to extending the `ChatLog` class. In order to change the messages that are being rendered you have to override the `_renderBatch` function from using `const messages = game.messages.contents` to the given messages you want to render.

This would be much safer done if the original function instead used `this.collection.contents` as it is already set to `game.messages`. This would help avoid developers having to copy paste Foundry code in order to change where the data comes in.

**Comment by aaclayton** [comment]
I'm not sure why you would be using the `ChatLog` class to render some collection other than `game.messages`, but this is not an objectionable change to make.

**Comment by MrVauxs** [comment]
It pertains to creating a popout chat log with specific array of messages, not those contained in `game.messages`.
