### ISSUE TITLE
Foundry server crashes if any protected package has an empty `signature.json` file

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#10590]
### What happened?

Encountered a case where the Foundry server was crashing on startup. Investigation eventually found an empty `signature.json` file inside a protected package. I think that a module's json failing to parse will handle the error and not load the individual module, but an invalid/empty `signature.json` file could cause the server to crash

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Have any premium package installed
- Delete the contents from signature.json
- Start Foundry server via node and access via the browser

Checking the logs, I see:
![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/8292a48b-6d67-4a04-889e-8c77d1393fac)

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Resolved for next release!
