### ISSUE TITLE
Uncaught TypeError: Cannot set properties of null (setting 'textContent')

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#10591]
### What happened?

Every 15 seconds the following error is logged in the web browser console:
![image](https://github.com/foundryvtt/foundryvtt/assets/3605541/254301d9-a0c4-493f-a786-ce8e95f07e7b)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Log in as GM
2. Start a new combat and add an actor to it
3. Set roll mode to 'Blind GM Roll'
4. Roll for initiative
5. Log in as a player
6. Check console, the error message is logged with 15 second intervals until Chat log is cleared 

### What core version are you reporting this for?

v11.315

### Relevant log output

```shell
foundry.js:85831 Uncaught TypeError: Cannot set properties of null (setting 'textContent')
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by grz0** [comment]
@aaclayton please try to reproduce on wfrp4e system, on dnd this issue does not exist.

**Comment by mkahvi** [comment]
Shouldn't this only happen if module or system removes the timestamps from the chat messages? Foundry is very insistent on updating those even when they don't exist.
