### ISSUE TITLE
Lower default values for volumes (Playlist/Ambient/Interface)

### ISSUE THREAD

**Issue by JensChup** [foundryvtt/foundryvtt#10593]
### User Experience

Currently, for a new player joining a world, the default volumes are set to high values (100% for Playlists/Ambient).
Nearly all sounds/music added and played at the default volume will be too loud.

So either the GM has to turn down each individual sound, or users will be blasted with too loud music and have to adjust downwards.
Default values should be around 50% to start out at a comfortable level (to then be easily adjusted up/down by the individual user like it works now). Eventually instead add an option to set the default values.

**Comment by mkahvi** [comment]
I'd suggest lowering default even closer to 25%

Relatedly I believe the volume sliders are logarithmic, which makes them do very little in the upper half, which makes this default volume issue even worse.

**Comment by aaclayton** [comment]
Default user-level volume controls are changed to `0.5` in v12.
