### ISSUE TITLE
Configure Default Sheets form save logic sometimes reverts default sheets

### ISSUE THREAD

**Issue by kgar** [foundryvtt/foundryvtt#10609]
### What happened?

The Configure Default Sheet application will save the changed options but not the existing options for default sheets. As a result, any previous default sheet choices are reverted back to whatever is the original default for the document type.

If I have multiple alternative sheets for Actors, Items, etc., and I only change one at a time and click save, only the changed option will be included in the save operation, and it will completely overwrite `core.sheetClasses`.

For users of my sheets module, if they visit the Configure Default Sheet form multiple times, their previous preferences seem to revert back to whatever is the original default.

What I'd expect to happen: All default sheet preferences, whether saved this time around or previously, should remain intact.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Using the dnd5e system and a sheets module (e.g., Tidy 5e Sheets),
1. Go to Configure Default Sheets and specify an alternate sheet for "Character"
2. Click Save Changes
3. Refresh the web page
4. Go to Configure Default Sheets and specify an alternate sheet for "NPC"
5. Click Save Changes
6. Refresh the web page
7. Go to Configure Default Sheets and note that "Character" is not using the alternate sheet, and "NPC" is using the alternate sheet option.
8. Repeat this back and forth to see how both settings still not stick between visits to the form.

Alternatively, this can be observed without any modules:
1. Go to Configure Default Sheets and specify the "Legacy 5e Character Sheet" for "Character"
2. Click Save Changes
3. Refresh the web page
4. Go to Configure Default Sheets and do nothing
5. Click Save Changes
6. Refresh the web page
7. Go to Configure Default Sheets and note that "Character" has reverted back to "Default 5e Character Sheet", even though it was set to "Legacy 5e Character Sheet".

### What core version are you reporting this for?

11.315

### Relevant log output

```shell
// Before saving a new default Character sheet
> game.settings.get("core", "sheetClasses")
{}

// Saving a new default Character sheet (note: I only changed the Character sheet option)
Foundry VTT | Retrieved and compiled template templates/sidebar/apps/settings-config-category.html
foundry.js:5802 Foundry VTT | Rendering SettingsConfig
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/package-configuration.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/default-sheets-config.html
foundry.js:5802 Foundry VTT | Rendering DefaultSheetsConfig
game.settings.get("core", "sheetClasses")
{
    "Actor": {
        "character": "dnd5e.Tidy5eCharacterSheet"
    },
    "JournalEntryPage": {
        "class": "dnd5e.JournalClassPageSheet",
        "map": "dnd5e.JournalMapLocationPageSheet",
        "rule": "dnd5e.JournalRulePageSheet"
    }
}

// Saving a new default NPC sheet (note: I only changed the NPC sheet option)
Foundry VTT | Rendering DefaultSheetsConfig
> game.settings.get("core", "sheetClasses")
{
    "Actor": {
        "npc": "dnd5e.Tidy5eNpcSheet"
    }
}

// Note how the entire world setting got overwritten.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Confirmed as an active issue by @mattexdee
