### ISSUE TITLE
When importing a scene from a compendium 'navigation:true' is not being cleared properly

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10610]
### What happened?

When importing a large number of scenes with navigation enabled, the scene navigation component of the UI can become unwieldy or even render the user interface unusable. For example, an import of all CzePeku scenes (which have `navigation:true`) can be problematic:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/4c993e98-58fe-4aea-9d7c-0ca355a74e93)
Per Kim, we currently do try to force `navigation:false` in `Scenes#fromCompendium`, so this is not expected behavior.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Import a large number of scenes from a compendium that have `navigation:true`, for example, all CzePeku maps

**Expected**: These scenes are not automatically added to the Scene Navigation UI
**Current**: They are added to the Scene Navigation UI.

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl take this one please if you can. You are familiar with these `fromCompendium` import flags.
