### ISSUE TITLE
add a way to export folders with their data inside them as zip or exposed.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/foundryvtt#10629]
### User Experience

the issue im having is that i want to export a compendium of macros but i have no way of exporting a batch amount of macros within those folders without having to make json files for each individual macro via export. 

ideally id like to be about to right click an imported/compendium folder and export as folder with all their respected json files. then have the ability to mass import json files into a folder similar to the batch import with sound files.

**Comment by JPMeehan** [comment]
What's the context here? The supported way to export a compendium is to do so as part of a module.

**Comment by aaclayton** [comment]
Agree that we need some more context about what is the use case here to evaluate this request.

**Comment by GuitarGuyNick** [comment]
> Agree that we need some more context about what is the use case here to evaluate this request.

maybe im misunderstanding the intention of exporting things. because what i wanted to do was easily export data and easily import data from one instance of foundry to another. i have a raspi situation with two isntances that dont talk to each other. and id like a way to easily export and import those folders with their respective macros from one instance to another. 

i found that what tends to happen is that you want to export a bunch of macros. but the only option available is to export as compendium. 

but you cant export a compendium into a raw folder. afaik. 

so i have to import the macros. export them one by one then create items in the new world and import them one by one.

**Comment by aaclayton** [comment]
The general guidance would be to create a module, and add a Macro compendium pack to that module. You can install your own shared module on both installs and share the compendium of macros that way.

**Comment by JPMeehan** [comment]
The supported way to do that is to make a module - which you can do from the Setup page - make a compendium in *that* (also doable from that setup page make-a-module form) and then .zip up the compendium and unzip it in your other instance's `foundrydata/Data/modules` folder.

**Comment by GuitarGuyNick** [comment]
the issue i had was that i couldnt export it as a module in this case. as it was on forge and it wouldnt allow me to export as module some weird connection issue.
