### ISSUE TITLE
Toolclips show incorrect modifier key under macOS

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#10633]
### What happened?

The modifier keys listed in toolclips aren't OS-aware like they are in the Configure Controls app. (The Chain tip here, for example, should be "Hold `Command` then `Click`" — or better, "Hold `⌘` then `Click`")

<img width="331" alt="Screenshot 2024-04-09 at 2 25 14 PM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/6228480c-65f0-425f-9577-efd3134ae9f3">
<img width="284" alt="Screenshot 2024-04-09 at 2 26 13 PM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/48488eb7-da22-47fb-b617-0ed86f92d582">

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

(Consistent across all tool layer toolclips in v12 currently)

### What core version are you reporting this for?

12.318

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Norc please tackle this one for our next release!
