### ISSUE TITLE
UserConfig Window does not appear in window.ui.windows

### ISSUE THREAD

**Issue by mouse0270** [foundryvtt/foundryvtt#10635]
### What happened?

After opening the User Config for foundry v12, it does not show up as a window under the `window.ui.windows` object. I am not sure if this effects all v2 windows or just the user Config

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Open User Config Window.
Open Browser Console
Type `window.ui.windows`

### What core version are you reporting this for?

Version 12 Build 318

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
`ui.windows` is specifically and only `Application` (v1) instances. ApplicationV2 instances appear in `foundry.applications.instances`.

**Comment by mouse0270** [comment]
Darn, so there is not going to be an easy way to get a list of windows, but instead they will be application specific? thats going to have to force some design logic for my module WindowTabs... I will have to figure if there is a better way to do that.

**Comment by aaclayton** [comment]
You can iterate over both `ui.windows` AND `foundry.applications.instances`. It's a little bit of an extra step but I'm not sure I agree that "there is not going to be an easy way to get a list of windows".
