### ISSUE TITLE
Explicitly name ItemSheetV2 using a "V2" suffix in the class name.

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10658]
### User Experience

As brought up in [Discord](https://ptb.discord.com/channels/170995199584108546/1209623497664364614/1230643898926370898).

---

ItemSheetV2 as located in `client-esm/applications/sheets` is called `ItemSheet` instead of `ItemSheetV2` this causes confusion between the AppV1 and AppV2 version as both will be existing side by side. 
Thus my request is to rename it to `ItemSheetV2` as to be in-line with `ApplicationV2` and `DocumentSheetV2` class naming schemes.

## Edit:
> Also add a getter for item and title to maintain feature parity with the original ItemSheet

It is indeed also missing the `get item()` the original ItemSheetV1 has, and similarly would also need to have the item property added in `_prepareContext`.

**Comment by JPMeehan** [comment]
Also add a getter for `item`

**Comment by dylanpiera** [comment]
> Also add a getter for `item` and `title` to maintain feature parity with the original ItemSheet
Title would be taken care of by DocumentSheetV2.

The old implementation of ItemSheet was 
```js
get title() {
    return this.item.name;
}
```

DocumentSheetV2 has:
```js
get title() {
    const {constructor: cls, id, name, type} = this.document;
    const prefix = cls.hasTypeData ? CONFIG[cls.documentName].typeLabels[type] : cls.metadata.label
    return `${game.i18n.localize(prefix)}: ${name ?? id}`;
}
```

So while there is a difference here, I personally prefer DocumentSheetV2's style of `[item-type]: [item-name]`.
