### ISSUE TITLE
Add a basic ActorSheetV2 implementation which provides a starting place for modules that wish to use the ApplicationV2 framework for Actor sheet UI.

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10657]
### User Experience

As brought up in [Discord](https://ptb.discord.com/channels/170995199584108546/1209623497664364614/1230643898926370898).

---

Create the base implementation for ActorSheetV2, for package developers to base their new AppV2 Actor sheets from.

To get feature parity with ApplicationV1 the following should be included:
- [ ] Drag & Drop support for ActiveEffect, Actor, Item & Folder.
  - [ ] ActiveEffect Creation.
  - [ ] Actor exists but doesn't execute any logic.
  - [ ] Item Creation & Sorting.
  - [ ] Folders with type Item create all items inside of it as owned items.
- [ ] Add `items` and `effects` properties to `_prepareContext` for access in templates.
- [ ] Add 'Configure Token' button to header bar.
- [ ] Remove `actor.overrides` during `_prepareSubmitData`

**Comment by JPMeehan** [comment]
getter for `token` too

**Comment by JPMeehan** [comment]
Thought: I think this is a good opportunity to introduce what D&D has been doing, which is `disable` fields affected by `override` since otherwise the input could be misleading.

**Comment by JPMeehan** [comment]
Also, a ticket that's related to possible Drag & Drop handling: https://github.com/foundryvtt/foundryvtt/issues/10372

**Comment by aaclayton** [comment]
I've implemented something basic for now (all there was time for). Several of the requests in this issue were below the line but can be added later. At least `foundry.applications.sheets.ActorSheetV2` is now available to be used in a standardized way.
