### ISSUE TITLE
Dynamic Token Ring next steps

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#10655]
- Token anchor adjustment should shift the subject within the ring rather than shifting the composited result
- Do we need to expose subject scale correction to the UI?
- Image fit mode should apply to the subject texture but not the ring itself
- How to expose optional ring effects to the UI?
- Fix some fit modes which are not compatible (`Fill`)

**Comment by Fyorl** [comment]
Related: #10787

**Comment by Feu-Secret** [comment]
This issue has been splitted into several issues:
- https://github.com/foundryvtt/foundryvtt/issues/11138
- https://github.com/foundryvtt/foundryvtt/issues/11139
- https://github.com/foundryvtt/foundryvtt/issues/11141
