### ISSUE TITLE
Feature Request: Adding Fake Roof Tiles.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#10661]
### User Experience

so because most of us probably dont have the art to make a roof tile. id like to propose we have a way to designate areas of the canvas as roof tiles for the sole purpose of excluding weather effects. currently it isnt possible to designate an area that is transparent as a roof.  as it always requires an image.

**Comment by aaclayton** [comment]
Good idea! this is implemented in V12 Scene Regions via https://github.com/foundryvtt/foundryvtt/issues/10389
