### ISSUE TITLE
Creating temporary actors does not apply default token settings

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10665]
Originally reported by mrprimate https://discord.com/channels/170995199584108546/1065764070680186930/1221947472377544857

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable)**: 5e 3.1, Foundry v11
**Short Description of bug**: Actor.implementation does not use default token properties for temporary actors
**Simple steps to reproduce the bug**:
Set the Default Token Settings display bars to "Hovered by Owner"
```javascript
let options = {
    temporary: true,
    displaySheet: false,
  };
// creates a temp actor with the default token properties set correctly
let temp1 = await  Actor.create({ name: "Test", type: "npc" }, options);

// creates a temporary actor, but the prototype token Hovered by Owner property is not set correctly
temp2 = new Actor.implementation({ name: "Test", type: "npc" });
temp3 = new Actor.implementation({ name: "Test", type: "npc" }, options);

```
**Screenshots and/or console errors**:

Not sure if I'm just holding it wrong though.

**Comment by Fyorl** [comment]
This is working as designed as default token settings are only applied in `Actor#_preCreate`, so it's unclear if there's anything to be done about this. We might be able to move it to `_initializeSource`.

**Comment by MrPrimate** [comment]
For context, I was looking at moving to implementation due to a deprecation warning that popped up when tryiong out v12. If there is a workaround or an extra step I should do then please let me know.

**Comment by aaclayton** [comment]
> For context, I was looking at moving to implementation due to a deprecation warning that popped up when tryiong out v12. If there is a workaround or an extra step I should do then please let me know.

Workaround for the time being while we decide what should be done here is:

```js
const a = new Actor(data);
a._applyDefaultTokenSettings(data);
```
