### ISSUE TITLE
Feature Request: Roll term to limit how many times a roll expression can explode.

### ISSUE THREAD

**Issue by SagaTympana** [foundryvtt/foundryvtt#10677]
### User Experience

We already have the "xo" term for exploding dice that makes it so that only the initially rolled dice can explode. A similar feature that establishes an overall limit on how many additional dice can be added to the roll as a result of explosions would also be useful. For a concrete example of how this could work or be used, a great example is the D&D 5e spell Sorcerous Burst, found on page 44 of this playtest document: https://media.dndbeyond.com/compendium-images/ua/ph-playtest7/tsgOb3llF22AL0nU/UA2023-PH-Playtest7.pdf?icid_source=house-ads&icid_medium=crosspromo&icid_campaign=playtest7

**Comment by aaclayton** [comment]
Hello @SagaTympana, this is already supported, but the syntax required is a little bit intricate. An example expression is:
```
/r 10d10x3<5
```
This interprets as "roll ten d10 and explode up to a maximum of 3 times any result that is less than 5. So for example, you could configure sorcerous burst as something like:
```
1d6x@abilities.cha.mod=6
```
