### ISSUE TITLE
Allow ApplicationV2 Theme to be set via Client setting.

### ISSUE THREAD

**Issue by mouse0270** [foundryvtt/foundryvtt#10678]
### User Experience

The new ApplicationV2 Theme using system prefers to apply a dark or light mode is a great feature. However a client setting to override system with a specific theme should be included. Right now, my system is set to dark mode, and I really don't prefer the dark mode of ApplicationV2 and the only way to resolve this is to set my entire PC or Browser to Light mode.

A Client setting should be included that will allow users to select either `System`, `Light` or `Dark` Theme. If system, it will use the prefers method, otherwise it will use the theme for the selected theme.

**Comment by aaclayton** [comment]
Added a setting which allows overriding the browser default preferred color scheme:

![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/46bc564c-16b9-4ca1-b86e-9061de9ef418)

![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/950bacdc-505d-48b5-9c65-22915b9b3404)
