### ISSUE TITLE
formField Handlebars Helper does not enrich HTML content/show raw content in the Prosemirror Editor

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10685]
### What happened?

Original Post: https://ptb.discord.com/channels/170995199584108546/1209623497664364614/1231523287704801431

---

When using the `formField` handlebars helper to render a HTML Data Field it either displays unenriched data or has the data enriched even while in the editor.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Given the following HBS:
```hbs
{{formField fields.description value=descriptionHTML target=data.description localize=true toggled=true}}
```
Where `fields.description` is an HTMLField, `data.description` is the raw html, and `descriptionHTML` is the enriched version of `data.description`. (This is following the implementation used for AppV1 in `base-sheet.js`)

While the editor is closed everything looks fine:
![editor-closed](https://cdn.discordapp.com/attachments/1209623497664364614/1231523287251681331/image.png?ex=66374470&is=6624cf70&hm=1fa7e0829cb8b2a36091eef1c4210ca2341dfe8df0e5d16bc7823b00a87d5473&)

However when you open the editor, the enriched content link is still present instead of `@UUID[uuid]`
![editor-open](https://cdn.discordapp.com/attachments/1209623497664364614/1231523287532703846/image.png?ex=66374470&is=6624cf70&hm=99644622c886a340dc7db15ad6099ee835f361fe2069eb423d94d31df5c259c1&)

### What core version are you reporting this for?

12.319

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This works a little differently now for the new `<prose-mirror>` custom element. The example syntax to use here would be:

```hbs
{{formField editorField value=textRaw toggled=true enriched=textRich}}
```

The value passed to the field should be the raw (un-enriched) text which is the source for editing. If using a `toggled` editor instance you may also pass an `enriched` property which provides the enriched HTML that is displayed when when the editor is not active.
