### ISSUE TITLE
Allow index as values for arrays passed to selectOptions handlebars helper

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#10691]
### User Experience

In a mass conversion of select -> selectOptions, I noticed that some of our select entries were for an array of strings, with the option value being the index and the option label being the value itself. ~~It would be helpful if there's some way to tell selectOptions arrays to use the index as the option's value (valueAttr="index"?).~~

Currently selectOptions, when given an array of strings, sets the array elements as both the array element and the array value.

The array I'm trying to convert right now is an array of proficiency rank localization keys. If this is not desired functionality, I can choose to call Object.entries() on the array before feeding it to the templates instead.

EDIT: Some discussion below, but I think a prop is no longer a good idea. I think preventing an array of strings or changing the default behavior is the correct idea now.

**Comment by aaclayton** [comment]
@CarlosFdez if it's not too much trouble, I think you should call `Object.entries()` on the array before passing it in. I want to avoid having there be *too many* possible ways to use this in favor of a more structured API and I think this feels a little bit like a niche case thatr can be solved by pre-processing the array.

**Comment by CarlosFdez** [comment]
Understood. I found it odd that arrays don't use the index as the key to mimic the behavior objects have when you loop over them, but it can't be helped and its probably too far in to change that behavior to align more closely.

Basically this:
```hbs
  {{#select data.traits.type}}
      {{#each armyTypes as |label type|}}
          <option value="{{type}}">{{localize label}}</option>
      {{/each}}
  {{/select}}
```
 now becomes `{{selectOptions armyTypes selected=data.traits.type localize=true}}`

but this 
```hbs
  {{#select data.savingThrows.fortitude}}
      {{#each proficiencyChoices as |label key|}}
          <option value="{{key}}">{{localize label}}</option>
      {{/each}}
  {{/select}}
  ```
explodes if we try to do the same thing. It was a landmine I ran into during conversion.

**Comment by aaclayton** [comment]
The reason I implemented the fallback to use the array values as both the value and the label was that I encountered a couple core software use cases that were doing this, but I could consider removing that also and instead only support arrays of objects. I'll think about it.

**Comment by aaclayton** [comment]
I have revisited this behavior. Passing an array of strings like `["foo", "bar"]` to the `{{selectOptions}}` helper will produce options like:
```html
<option value="0">foo</option>
<option value="1">bar</option>
```

**Comment by BernhardPosselt** [comment]
Can we get an option on the selectOptions instead to define which behavior we need? I've got values that operate on indices like the new default, but also values that use the array element for both the value and label.
