### ISSUE TITLE
Changing the value of a <color-picker> custom element does not trigger `Application#_onChangeInput`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#10693]
### What happened?

`HTMLColorPicker##onChangeInput`:
```js
    /**
     * Handle changes to one of the inputs of the color picker element.
     * @param {InputEvent} event     The originating input change event
     */
    #onChangeInput(event) {
      event.stopPropagation();
      this.value = event.currentTarget.value;
    }
```
Removing the call to `event.stopPropagation()` allows the event to bubble to `Application#_onChangeInput`.

`Application#_onChangeInput`:
```js
  /**
   * Handle changes to an input element, submitting the form if options.submitOnChange is true.
   * Do not preventDefault in this handler as other interactions on the form may also be occurring.
   * @param {Event} event  The initial change event
   * @protected
   */
  async _onChangeInput(event) {
    // Saving a <prose-mirror> element
    if (event.currentTarget.matches("prose-mirror")) return this._onSubmit(event);

    // Ignore inputs inside an editor environment
    if (event.currentTarget.closest(".editor")) return;

    // Handle changes to specific input types
    const el = event.target;
    if ((el.type === "color") && el.dataset.edit) this._onChangeColorPicker(event);
    else if (el.type === "range") this._onChangeRange(event);

    // Maybe submit the form
    if (this.options.submitOnChange) {
      return this._onSubmit(event);
    }
  }
```
It's looking for an `edit` dataset attribute for color picker inputs that isn't set for the new custom element.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Use a `<color-picker>` element in an `Application` with `submitOnChange` enabled.

### What core version are you reporting this for?

Version 12 Build 319

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This has been partially "fixed".
- Input change events for custom input elements like `<color-picker>`, etc... are dispatched to the `Application#_onChangeInput` method.
- Input change events for `<color-picker>` ARE NOT dispatched to `Application#_onChangeColorPicker`, however - because this method is only intended for legacy color picker markup which does not internally handle necessary logic.
