### ISSUE TITLE
Deleting a Folder (Delete All or Remove Folder) throws an error

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10699]
Originally reported by hervedarritchon: https://discord.com/channels/170995199584108546/1184176415139184731/1231124628999766057

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable):** MacOs/Native App
**Short Description of bug: ** Deleting Folder (Delete All or Remove Folder) throw an error in the console. The Folder is not deleted until you refresh the page.
**Simple steps to reproduce the bug**: Create a folder any where and delete it.
**Screenshots and/or console errors:**

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/cd204c68-8fcb-473a-b357-fb283010c301)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/6dcf60a4-dcac-4148-a043-b4e1a824acb9)

**Comment by aaclayton** [comment]
I believe I fixed this bug in dev2, so if it's not reproduced I think it's because it has already been fixed.
