### ISSUE TITLE
Support passing the `groups` parameter to the `selectOptions` Handlebars helper which is forwarded on to `foundry.applications.fields.createSelectInput`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#10715]
### What happened?

Having a fixed order of option groups would also be useful for the Handlebars helper.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
static selectOptions(choices, options) {
    let { localize = false, selected, blank, sort, nameAttr, valueAttr, labelAttr, inverted } = options.hash;
    ...
}
```

### What core version are you reporting this for?

Version 12 Build 319

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Not a bug, but a potential improvement. The vision moving forward though is that handlebars helpers would not be used for this in favor of form fields or element generation API methods.
