### ISSUE TITLE
Dynamic Token Ring subject mapping does not work after client reload

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#10713]
### What happened?

when using the subjectPaths flag to automatically use the subject images for dynamic tokens, the mapping works only during the session where the token is originally created.

after reloading via f5, the token uses the full token art instead of the subject art again. When that token is copied and pasted, the new token uses the subject image again.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

-

### What core version are you reporting this for?

12.319

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Resolved in Testing 2
