### ISSUE TITLE
Allow modules to register an additional dynamic token ring

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#10714]
### User Experience

Currently the dynamic token ring is loaded from a path in `CONFIG.Token.ring.spritesheet`. This path can be updated by a system or a module to use a different dynamic token ring.

But currently this means that all dynamic tokens use the new ring instead of the default dynamic token ring. There is no way to have both the original version of the dynamic token ring and a custom one active at the same time.

My use case is that I want to have multiple modules that define different token rings and have creatures or compendium mappings in them that use their own dynamic ring. These rings are expected to have a different profile on the inner line to each other, so the same subjects can't be used with interchangeable rings.

**Comment by aaclayton** [comment]
There are some significant performance implications of comingling token rings because it breaks batching. @Feu-Secret can comment on this some. We may not want to allow this. We can consider it, but if we allow it users will probably lean into customizing a different ring for each token which can be a silent killer for performance.

**Comment by Drental** [comment]
> but if we allow it users will probably lean into customizing a different ring for each token which can be a silent killer for performance.

I understand this perspective, but I could use the same argument to add stronger guard rails against importing a whole compendium at once or other similar foolhardy ideas.

I also don't think that adding a token ring should be possible through the UI for any user, having it as a code only thing or maybe limited to one ring per module via needing a property in the manifest could help reduce the amount of rings that people use

**Comment by aaclayton** [comment]
We aren't able to prioritize this in V12, but we can explore it as an enhancement for future versions.

**Comment by Drental** [comment]
How do the settings for this look now?

**Comment by Feu-Secret** [comment]
> How do the settings for this look now?

Numerous examples will be present into the API Doc. Now, configuring a new Dynamic Token Ring sheet will look like this:
```js
// Create a hook to add a custom token ring configuration. This ring configuration will appear in the settings.
Hooks.on("initializeDynamicTokenRingConfig", ringConfig => {
  const mySuperPowerRings = new foundry.canvas.tokens.DynamicRingData({
    label: "My Super Power Rings",
    effects: {
      RING_PULSE: "TOKEN.RING.EFFECTS.RING_PULSE",
      RING_GRADIENT: "TOKEN.RING.EFFECTS.RING_GRADIENT",
      BACKGROUND_WAVE: "TOKEN.RING.EFFECTS.BACKGROUND_WAVE"
    },
    spritesheet: "canvas/tokens/mySuperPowerRings.json"
  });
  ringConfig.addConfig("mySuperPowerRings", mySuperPowerRings);
});
```

**Comment by shemetz** [comment]
I think this issue wasn't exactly "done" -- The above API now allows modules to register additional dynamic token rings, but there is still a strict limit of only one ring being active at any given time, making it impossible to do what @Drental requested:

> There is no way to have both the original version of the dynamic token ring and a custom one active at the same time.

I've seen many people express desire for this -- at least a dozen users in the pf2e server said they would like to have multiple rings simultaneously, and several of them specifically wanted different rings for different groups (e.g. ring 1 for PCs and ring 2 for NPCs).

If this ticket isn't describing that "multiple rings" feature after all, should we open a new ticket?
