### ISSUE TITLE
Use ALT (instead of CTRL) to lock aspect ration when placing a Scene Region for consistent UX with similar canvas objects

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#10718]

**Comment by unsoluble** [comment]
(Is this an opportunity to swap to Shift for constraints to match the rest of the design industry? :)

**Comment by aaclayton** [comment]
> (Is this an opportunity to swap to Shift for constraints to match the rest of the design industry? :)

It is not.
