### ISSUE TITLE
Use the name of the sub-type as the default Document name instead of "New Document Name"

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10737]
### User Experience

Currently when you create a new Region Behaviour without entering a `Name`, the behaviour always gets the name of "New Region Behaviour". Suggest instead defaulting to the name of the behaviour that was added — so a new `Pause Game` behaviour would get the name "Pause Game" by default, if none was entered, etc.

![CleanShot 2024-04-26 at 19 10 32](https://github.com/foundryvtt/foundryvtt/assets/801582/5c3f34e8-cc84-4e75-aec0-01e200ff99b8)

**Comment by aaclayton** [comment]
Assigning to @dev7355608
