### ISSUE TITLE
`Esc` Menu is using `GAME.ReturnSetup` label instead of `MENU.NavLabel`

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#10740]
### What happened?

All `Esc` menu labels (Reload Application, Log Out, User Management) are under `MENU` namespace but the last one is using `GAME.ReturnSetup` (Return to Setup) label instead of the correct one `MENU.NavLabel` (Main Menu) which does exist but not used.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Press `Esc` in the game world.

The last item should be "Main Menu" not "Return to Setup".

### What core version are you reporting this for?

Version 11 Build 315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
The use of the `GAME.ReturnSetup` label in that menu is intended: the button to which it's applied does the same thing as the identically-labeled button in the settings sidebar. `MENU.NavLabel` is in fact used in the ESC menu but to label the entire list for screen readers.
