### ISSUE TITLE
Allow token-emitted light sources to be new V12 darkness sources

### ISSUE THREAD

**Issue by Rabulias** [foundryvtt/foundryvtt#10741]
### User Experience

I saw the FVTT 12 dev2 stream and saw the new darkness sources and how they work. Looks really good for duplicating D&D magical darkness. See Discord question and discussion here: https://discord.com/channels/170995199584108546/1184176344276406292/1232812789257605151

Use case: D&D 5e warlock with _devil's sight_ casting _darkness_ on himself and moving about.

"Is Darkness Source" is not currently in the token config UI, but it can be done programmatically. It currently blocks the source token's vision when the token is set as a source of darkness. My use case would need some way for any tokens with _devil's sight_ to see through the darkness effect.

Thanks!

**Comment by aaclayton** [comment]
@Feu-Secret did we have another issue for this (is this a duplicate)?
