### ISSUE TITLE
Consider having the context menu render with a fixed position relative to the viewport rather than injected alongside the target

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10747]
This would unblock a few issues:

- #8358 
- #10502 
- #10263 

Alternatively, we could consider an opt-in `ContextMenu2` class that behaves this way, and retain the original behaviour of `ContextMenu` for backwards-compatibility.

**Comment by Norc** [comment]
I believe this may be a consequence of this issue (or one of the related ones): 

Right-clicking a Macro that in the second row or of the Macro Directory or lower causes the bottom-most  options (Duplicate, in this case) to be cut off and a scrollbar to appear:
<img width="231" alt="image" src="https://github.com/foundryvtt/foundryvtt/assets/64667579/54caa7ff-142c-4d84-b06c-6ffce52111d9">

**Comment by aaclayton** [comment]
Shifting to V13
