### ISSUE TITLE
V12: `TextEditor._primeCompendiums` Regex doesn't match UUID links featuring non-word characters

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt/foundryvtt#10750]
### What happened?

I noticed a sheet with lots of `@UUID` links was taking a long time to open. Running a `pack.getDocuments()` manually before eliminated the delay. I noticed `_primeCompendiums` was running suspiciously quickly, and upon investigation I discovered the following:

Given the regex: `/Compendium\.\w+\.\w+\.[a-zA-Z\d.]+/g` on line 68583, the `\w`s will not match package names or compendium names with non-word characters in, in my case a compendium name `class-features`.

The regex should be changed to account for non-word characters in package and compendium names.

Discussed on discord: https://discord.com/channels/170995199584108546/1184176344276406292/1233025240578134036

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

In an enriched text field, create content links to a compendium with non-word characters in its name (or from a package with the same requirement).

Observe `_primeCompendiums` not matching the UUIDs.

### What core version are you reporting this for?

12.319

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Spice-King** [comment]
The correct regex would be `/Compendium\.[A-Za-z0-9-_]+\.[^\.]+\.[a-zA-Z\d.]+/g`  based on the exact rules for package and pack ID checks in V11 at least. `A-Za-z0-9_` could be simplified to just `\w` for the package ID, so just `[\w-]+` for package ID. Pack ID is just "does not contain a period" and nothing else.
