### ISSUE TITLE
Consider inverting the Behaviour Status control inside the Region Behaviour config sheet

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#10771]
### User Experience

The "Behavior Status" section of a Region's config is needlessly inverted — it would be a more straightforward UX to have the control be labelled `Enable`, with the checkbox on by default (and the supporting hint tweaked to match).

![CleanShot 2024-04-26 at 19 17 37](https://github.com/foundryvtt/foundryvtt/assets/801582/3b2e0c92-64f8-455c-881d-bfeb28008f9e)

**Comment by aaclayton** [comment]
We could consider flipping the UI but from a data models perspective this was done for consistency with other placeable types like Token, Tile, AmbientLight, AmbientSound, MeasuredTemplate, etc... where we track whether the placeable is `hidden`. In the case of those other placeables, the UX around interacting with the `hidden` field is different (either via a HUD or via a right-click on a control icon).
