### ISSUE TITLE
Journal Notes with Toggle Notes Display do not display on other layers after World load until the Notes layer is activated at least once

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10783]
Originally reported by farling https://discord.com/channels/170995199584108546/1184176415139184731/1233551031993106453

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows 11, Chrome 124.0.6367.91 
**Short Description of bug**: Hovering over Note doesn't show label until Journal Notes layer selected
**Simple steps to reproduce the bug**: On first starting a world (or pressing F5), hovering over a note icon doesn't show the note's label. If the GM switches to the Journal Notes layer then note's label are shown. Switching back to Token Controls layer then still allows hover to show the note's labels.

**Comment by aaclayton** [comment]
Assigning to @dev7355608 - this issue is related to a change we made to initialization of layer activation state.
