### ISSUE TITLE
Checking for package updates throws an error in cases of REQUIRES_CORE_UPGRADE_UNSTABLE

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10781]
Originally reported by agaringer https://discord.com/channels/170995199584108546/1065764070680186930/1231615309509689444

**ALL MODULES DISABLED?** N/A, on setup screen
**OS, Hosting, Browser (if applicable)**:  remote Node hosting
**Short Description of bug**:  V11 Core throws translation string error when a V12-only system update is available
**Simple steps to reproduce the bug**:  Try to update Scum and Villainy from V11.315
Appears to be an issue in setup.js `#updateCheck()`
`Setup.checkPackage()` returns an `availability` of 9, but,
```js
const message = { 6: "Insufficient", 7: "UpdateNeeded", 8: "Unstable" }[availability];
```
so `message` returns undefined
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/c49adbcc-68d0-4631-a6a2-f171af2bb38d)

**Comment by drewg13** [comment]
This is definitely a V11 issue.  When I had a V12-only release on my Github, I was getting user reports from V11 users about this error.  I have since deleted that release, but this seems like it will be an issue for any V12-only release until V12 releases as stable.
