### ISSUE TITLE
HTMLStringTagsElement does not escape HTML when rendering entered tags

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10785]
Originally reported by asheeon https://discord.com/channels/170995199584108546/1184176415139184731/1233702770293477387

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows 11 / Node / Chrome
**Short Description of bug**: HTMLStringTagsElement directly renders content into the DOM without sanitization
**Simple steps to reproduce the bug**: Create a HTMLStringTagsElement and add value `<test value>` you will find that instead of the string "<test value>" being rendered within the Tag's span, it will interpret it as an HTML element of `<test value>`.
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/d6117378-29d7-40ce-8a74-d4311378ae42)

**Comment by aaclayton** [comment]
Leverage `HTMLElement#textContent` to do sanitization for us:

![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/e0164b1d-4147-4701-adc0-acd4a53d8001)
