### ISSUE TITLE
Remove Macro validation on save (or at least make it helpful)

### ISSUE THREAD

**Issue by Freeze023** [foundryvtt/foundryvtt#10809]
### User Experience

As is when you execute or save a macro that has an error in it the macro doesn't save and gives a fairly generic error giving no indication of what you have done wrong. And if you executed it will run whatever last version it had leading to more confusion. 

Without that validation step you could at least go into the console and figure out what you did wrong or go to Macro Polo on Discord and ask if it didn't work (lets say you forgot a `)`). 

Either the validation will have to report back what line has the error, and perhaps the type of error. Or it just shouldn't be there as it makes life harder and not easier, because a debugging step has been removed.

**Comment by JPMeehan** [comment]
Having some sort of built-in syntax highlighting would make a HUGE difference. Right now I feel like best practice is to just have notepad++ or something open.

**Comment by aaclayton** [comment]
It's possible to improve things here *very slightly*. The validation in place catches syntax errors only, it does not capture runtime errors or logical errors which would only be revealed upon macro execution. We can forward more of the error message that captures the syntax error though to give the resulting error message a little bit more context.

The amount of information we can return is the same as what you would get when declaring a function with a syntatic error via the console:

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/87845b45-ce5d-4073-81b6-af5c42b28188)

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/d34723be-6d39-421a-a5d3-8f8a07dd93fa)
