### ISSUE TITLE
TinyMCE editor has incorrect font sizes

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#10801]
### What happened?

Font sizes looked a little off when editing, and I realized its because the default body text's font is too big.

(We can't swap to prosemirror while there's still outstanding bugs with it, the menu overflow clipping being the biggest one)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [x] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

* Create a journal page, then start editing it
* Set sheet to TinyMCE

I also verified in simple worldbuilding system.

![image](https://github.com/foundryvtt/foundryvtt/assets/1286721/487e35d2-986f-49c7-af4d-d3858d5ae736)

### What core version are you reporting this for?

12.320

### Relevant log output

None really, but --font-size-X properties existed in V11 but not in V12 for the mce.css.

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hey @Fyorl a small one I hope you can look at. Sounds like there might be a related issue with ProseMirror that would be blocking PF2E adoption of the "go-forward" editor also.

**Comment by Fyorl** [comment]
> Sounds like there might be a related issue with ProseMirror that would be blocking PF2E adoption of the "go-forward" editor also.

> (We can't swap to prosemirror while there's still outstanding bugs with it, the menu overflow clipping being the biggest one)

If #8212 is the menu clipping issue then I don't see how it could be related to this one.
