### ISSUE TITLE
Allow for free-form entries for `statuses` in the base `ActiveEffectConfig`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#10803]
### User Experience

(v12.320)

Since the `<multi-select>` element in `ActiveEffectConfig` limits the options to those in `CONFIG.statusEffects`, it is not possible to add any custom string to `ActiveEffect#statuses` (via script) and retain it if one should want to make changes to the ActiveEffect at any point through the UI.

Additionally it is not possible to add such a string by any means other than by script.

It would be perfect if this field was instead a "tags" input ([example of what is meant by that](https://codepen.io/iamqamarali/pen/qyawoR)).

**Comment by aaclayton** [comment]
This is not a good candidate for free-form user input. These statuses have mechanical significance and need specific string IDs to function properly. Those string IDs (and their corresponding labels) need to be pre-registered in `CONFIG` so they can be honored by the system. I'm sure there are use cases for free-form input, but I would encourage you to think about alternative ways to pursue your desired design.
