### ISSUE TITLE
Clearing the Name input of the RegionConfig and then saving results in a validation error

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10813]
The placeholder of the Name input shows the current name of the Region. Clearing the input and saving should result in no change instead of this validation error:
```
foundry.js:631 Error: RegionDocument [p4mlKUyhH4aAri4B] validation errors:
  name: may not be undefined
```

**Comment by aaclayton** [comment]
Not sure I agree with framing this as a bug ... trying to save the form with a blank name field means you are trying to save a blank name...

We could add extra UX to protect users from themselves here, but this isn't a bug.

**Comment by stwlam** [comment]
After discussion, keeping this in place since no change is made to the region data and the error is useful feedback.
