### ISSUE TITLE
Bug with version checking of systems in admin page

### ISSUE THREAD

**Issue by Stexinator** [foundryvtt/foundryvtt#10835]
### What happened?

Foundry does not realise that version 1.020 of a system is greater then version 1.019

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Make a release with these numbers

### What core version are you reporting this for?

Version 11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Version checks in Foundry VTT are performed via the `foundry.utils.isNewerVersion(v1, v0)` helper method. This method does correctly return that `"1.020"` is greater than `"1.019"` when both version numbers are compared as strings. It also correctly returns that `1.020` is greater than `1.019` when both versions are compared as numbers.

If the two version numbers are not consistently typed - however - for example one is a string and one is a number, this may yield incorrect results as shown below:
![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/190790aa-3252-4d29-9a0e-2001a2a56ce8)

Please verify that the version comparison you are performing uses consistent types (strings or numbers) for your version field.

**Comment by Stexinator** [comment]
Sorry for the incomplete information.

This problem does not occur in the code. It happens why I try to update in the real foundry server. I updated the version and still after 15 min the server claimed that there are no updates available.

![grafik](https://github.com/foundryvtt/foundryvtt/assets/69796777/f04a2bfb-9d18-41e2-90b9-aa4b1fbb0851)
![grafik](https://github.com/foundryvtt/foundryvtt/assets/69796777/ef458f8e-ca76-4e01-99d4-b9aa96e99bab)

After I upped the version to 1.021 it immediatly recognised an update is available.

**Comment by aaclayton** [comment]
To understand what is happening here we need to compare the `system.json` manifests for the various versions. I looked on our website and found https://foundryvtt.com/packages/thewitchertrpg, but this is badly out of date and the versions listed here are incorrect.

1. They do not reflect the more recent versions you are describing in this issue (1.020, etc...)
2. The version numbers on the website do not match the version numbers in the manifest files (website says `0.0.40`, manifest says `0.97`.

**Comment by Stexinator** [comment]
I use my fork since the original seems to be abandoned.

The system.json can be found at https://github.com/Stexinator/TheWitcherTRPG/blob/main/system.json

**Comment by aaclayton** [comment]
Version numbers in Foundry VTT are `.` separated strings. When two version numbers are compared, each part of the string is compared against the corresponding part. If both parts are numeric, they are converted to numbers before comparison. Otherwise they are compared as strings.

In your case you have two versions `"1.029"` and `"1.03"`. This compares as `["1", "029"]` vs `["1", "03"]`. The `1`s are both compared as numbers and are equal so it moves onto the second part. `29` is compared with `3` and `29` is larger. The problem is that your new version is declared as `1.03` not `1.030` which is a meaningful difference.
