### ISSUE TITLE
Render context menus for the Macro Hotbar above the Game Paused graphic

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#10832]
### What happened?

Context menus for the Macro Hotbar app are currently rendered under the Game Paused graphic, which is less than ideal. I know the CSS stacking is a complex beast, but figured it's worth a look if feasible.

<img width="282" alt="Screenshot 2024-05-03 at 2 32 14 PM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/d53def71-c3e5-483a-a202-93feb344e921">

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Right-click a Macro Hotbar slot that coincides with the Game Paused graphic's location.

### What core version are you reporting this for?

12.321

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Sorry, I think this is a regression based on some recent rationalization of z-index rules. Will fix.
