### ISSUE TITLE
Add support for `TypedSchemaField` outside of `ArrayField`

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt#10833]
### What happened?

There are technically 2 issues here.

1. TypedSchemaField does not support Partial Updates.
2. TypedSchemaField fails its local update cycle when not contained in ArrayField because it does not support Partial Updates

In this case what I mean with a Partial Update is given the model:
```json
"model": {
    "type": "type1",
    "value1": "value 1"
    "value2": "value 2"
}
```
Calling document.update with the value: `{"model.value1": "new value 1"}` fails with Validation Error "field does not have a valid type".

This *feels* like it is unintended behavior as we are able to call `item.update({"system.property": "value"})` just fine without letting foundry know the item type so it can resolve the TypeDataModel of `system`, and I personally can't find a reason why you'd explicitly make this distinction in functionality.

*Regardless*, due to this behavior, ***all*** updates fail client-side if the TypedDataField is not contained within an ArrayField (Point 2).

As upon the DB return-trip, the DB only returns changed values and therefore the local `updateSource` fails as if the type is unchanged it is not returned by the DB.

The reason why this *does* work for ArrayField is because you cannot partially update an ArrayField and thus always have to update the full array, and thus the DB always returns the full array with all data in it. (This also imo is unintended behavior and is related to #10541)  

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Given the following schemas:
```js
class ItemSystem extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    const fields = foundry.data.fields;
    return {
      typedField: new fields.TypedSchemaField({
        test1: TestModel1,
        test2: TestModel2
      })
    }
  }
}

class TestModel1 extends foundry.abstract.DataModel {
  static defineSchema() {
    const fields = foundry.data.fields;
    return {
      type: new fields.StringField({required: true, initial: 'test1', choices: ["test1","test2"]}),
      value: new fields.StringField()
    }
  }
}

class TestModel2 extends foundry.abstract.DataModel {
  static defineSchema() {
    const fields = foundry.data.fields;
    return {
      type: new fields.StringField({required: true, initial: 'test2', choices: ["test1","test2"]}),
      otherValue: new fields.StringField()
    }
  }
}
```
You can create the item just fine
```
Item.create({"name": 'test', "type": 'custom', "system": {"typedField": {type: "test1", value: "value"}}})
```
However when I attempt to update the value of the `typedField.value` property to `new value` an error is thrown:
![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/79d1ac65-9518-4a9c-b36e-daaf4d9653ff)
If I refresh right after this error occurs however, we can see that the update *did* work:
![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/10809930-7e49-4fd7-8a06-685e4d9efaaf)

The problem seems to be coming from `ClientDatabaseBackend#handleUpdateDocuments`, the results property only contains the changed values in the DB, so in this case, the returned property would be: 
```json
{
    "system": {
        "typedField": {
            "value": "new value"
        }
    },
    "_stats": {
        "modifiedTime": 1714819613546
    },
    "_id": "DIhegTZJrWXRLq6K"
}
```
which is then in turn fed to `doc.updateSource` which fails because the typedField is lacking a type.

### What core version are you reporting this for?

V 12.321

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dylanpiera** [comment]
One addendum: Please note that if the DB were to always return the type of a typedatafield that this would not resolve the issue, as if we added an additional field like:
```js
class TestModel1 extends foundry.abstract.DataModel {
  static defineSchema() {
    const fields = foundry.data.fields;
    return {
      type: new fields.StringField({required: true, initial: 'test1', choices: ["test1","test2"]}),
      value: new fields.StringField(),
      otherValue: new fields.StringField({initial: "oops!"})
    }
  }
}
```
Initialize a new item with: 
```js
Item.create({"name": 'test', "type": 'custom', "system": {"typedField": {type: "test1", value: "value", otherValue: "some other value"}}})
```
and call 
```js
item.updateSource({"system.typedField": {"type": "test1", "value": "new value"})
```
`item.typedField.otherValue` will be reset to the initial value of "oops!"

As long as TypedDataField does not support a partial update the whole object would need to be returned.

**Comment by Fyorl** [comment]
We have special handling in `ClientDatabaseBackend` to add the `type` information so that this can work for `system`. I don't think we support arbitrary use of the `TypeDataField`.

**Comment by dylanpiera** [comment]
> We have special handling in `ClientDatabaseBackend` to add the `type` information so that this can work for `system`. I don't think we support arbitrary use of the `TypeDataField`.

Totally my mistake there in the title, it ain't `TypeDataField` it is `TypedSchemaField`, the issue body itself mentions it correctly.

**Comment by Ethaks** [comment]
@dev7355608 I just tried this in 13.333, and the issue in https://github.com/foundryvtt/foundryvtt/issues/10833#issuecomment-2127154209 still occurs, and still triggers the validation error.

**Comment by dev7355608** [comment]
> @dev7355608 I just tried this in 13.333, and the issue in [#10833 (comment)](https://github.com/foundryvtt/foundryvtt/issues/10833#issuecomment-2127154209) still occurs, and still triggers the validation error.

I opened a new issue: https://github.com/foundryvtt/foundryvtt/issues/11986
