### ISSUE TITLE
Un-diffed changes are passed to `preUpdate` handlers

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10841]
Originally reported by asheeon: https://discord.com/channels/170995199584108546/1184176415139184731/1236359773784375346

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Desktop App, Windows 10
Short Description of bug:  _preUpdate contains the entire actor/item object in the "changed/updateData" parameter when a change is made.
Simple steps to reproduce the bug: Make any change to an actor or item and log the preUpdate data.
Screenshots and/or console errors: None

**Comment by aaclayton** [comment]
This is an intentional change we made in V12. `_preUpdate` workflow are called before `diff` so that additional modifications applied during preUpdate workflows are also diffed with shims applied. Closing as wontfix.
