### ISSUE TITLE
Immediately evaluated inline rolls should always force use of non-interactive roll resolution. Deferred inline rolls should use the default roll resolution method which may be interactive.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10854]
Originally reported by max.pat https://discord.com/channels/170995199584108546/1184176415139184731/1237152150820225035

**Short Description of bug**: Immediately Evaluated Inline Rolls should always use Foundry/digital roll methods to prevent the roll dialog from displaying frequently and disrupting the user
**Simple steps to reproduce the bug**: Change the Dice settings to Manual Input, put an IEIR in an item description
**Screenshots and/or console errors**:

[IEIR.webm](https://github.com/foundryvtt/foundryvtt/assets/207433/1e0e5f08-4148-4d3f-941f-c12bd9a93f8a)

**Comment by Fyorl** [comment]
I've raised it for discussion but this is working as designed. It would be useful to understand a bit more the use cases for these non-deterministic immediately evaluated inline rolls (is it really useful if the number changes every render?), but presumably, if you're including them, you want them to be rolled. And if that's the case, then you presumably might also want to use manual or bluetooth dice to resolve those rolls too, like any other.

**Comment by MaxPat931** [comment]
> if you're including them, you want them to be rolled. And if that's the case, then you presumably might also want to use manual or bluetooth dice to resolve those rolls too, like any other.

I dont think this is necessarily true, if you're using an Immediately Evaluated roll, you likely just want that roll to be executed in the background and displayed as they are done in v11, if you want to participate in the roll then you should use a Deferred Inline roll instead.

**Comment by Fyorl** [comment]
> I dont think this is necessarily true, if you're using an Immediately Evaluated roll, you likely just want that roll to be executed in the background and displayed as they are done in v11

It's not necessarily untrue either, which is the problem. I don't think we can make any assumptions about what is and isn't likely until we understand the use cases better.

**Comment by aaclayton** [comment]
Reframed the title of this issue with a decision about how I want us to proceed

> Immediately evaluated inline rolls should always force use of non-interactive roll resolution. Deferred inline rolls should use the default roll resolution method which may be interactive.
