### ISSUE TITLE
Remove trailing question marks from certain data model field labels, for example `Is Darkness Source?` or `Restricts Light?` no longer present the field label with a question mark.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#10866]
### User Experience

This element should be just `Darkness Source`.

<img width="479" alt="Screenshot 2024-05-08 at 11 19 10 AM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/248f3896-fee9-44d1-b1d5-fee45c12b07b">

(See #7914 for previous question-mark removals for precedent.)

Tack-on tweak: Should probably also be "...light and vision, and suppresses lights _and_ vision sources..."

Oh, also, these in the `Tile > Overhead` app:
<img width="420" alt="Screenshot 2024-05-08 at 11 25 59 AM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/0add97b5-79af-402d-ba6c-4dc0d702a162">

and these in the `Configure Default Token Settings` app:
<img width="311" alt="Screenshot 2024-05-08 at 11 33 18 AM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/af3de4ad-2bb3-4b36-9a2f-0feb346ec278">

and this in the `Combat Tracker Settings` app:
<img width="417" alt="Screenshot 2024-05-08 at 11 33 35 AM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/91764da7-8cbb-4452-8ebe-efb5191aab05">

**Comment by unsoluble** [comment]
Missed the ones in the hint text here (which will also need to be rephrased a bit):
<img width="419" alt="Screenshot 2024-05-10 at 2 06 55 PM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/e915afbe-2647-47d4-8c47-8981475ba3a7">

**Comment by aaclayton** [comment]
The policy I want to apply here is that field labels are not phrased as questions, but I think that question marks in hint text is not inappropriate. I'll keep this in mind if we want to rework it as we gradually redesign these apps for v2.

**Comment by unsoluble** [comment]
Totally fine if that's the style you want to go for, of course, but I was ticketing as a matter of global consistency — the question-phrasing was removed from hint text too in 7914, and doesn't appear in any other places in the UI.
