### ISSUE TITLE
`SoundsLayer#_syncPositions` can pick wrong `AmbientSound` to process among multiple with common path

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#10863]
This seems to be an intermittent issue, but can be reproduced somewhat reliably by: 
- loading the Demon Queen Awakens, 
- moving a token to room 1b next to the secret door on "The Vault of Aten" scene to trigger the audio, 
- attempting to leave the hearing range of the placed audio source

**Comment by Norc** [comment]
I can reliably reproduce this every time with the Akra starter hero standing next to the 1B secret door.

When Volume Easing is enabled, playback stops when moving away, but when disabled it does not stop until a refresh.

Foundry 12.325, DND5E 3.2, and DQA 4.0.0.

**Comment by Norc** [comment]
[#11067](https://github.com/foundryvtt/foundryvtt/issues/11067) is the same issue as this one, I believe. Once I get the ambient sound playback into the bugged state, deselecting the token does not stop audio playback either. 

Once you can reproduce with a particular sound source, I've been able to reliably reproduce with that source even after refreshing, changing activated scenes, etc. This is a fragile state, though, and it seems deleting other sound sources or switching to the sound layer might break it? A sound source seems to stay consistently "broken" in this way between refreshes.

I've been able to reproduce in 11.325 on a clean scene and drawing a clean 10ft radius ambient sound in the center of a square that plays the core `drum.wav` sound. Constrained by walls was on and Easing was off, so it's not a complicated interaction with walls or anything. 

The best way to reproduce this is by trying the DQA scound  location mentioned by Anathema and hope that this bugged state occurs for you. Other than that, manually drawing 10' radius sounds in a clean scene, refreshing, and moving tokens in and out like a maniac should eventually get you a "lucky" sound source that is broken and stays broken for a while.

**Comment by anathemamask** [comment]
This has re-emerged as a difficult to reproduce bug during work on A House Divided. Current repro path is somewhat shaky but has been confirmed to affect multiple users.

- Install and import latest A House Divided
- Activate First Floor of Feyward Manor
- Select token in southmost part of F13B Dance Hall
- Wait for ambient audio sourceto start playing
- Attempt to deselect token and note that audio continues even when deselected, (regardless of the state of "Preview Ambient Sounds" )

Discovered details which might lead to identifying the cause:
- This _**seems**_ to occur predominantly on scenes that have pre-v12 canvas audio sources; newly created audio sources do not appear to have this problem.
- It is possible to stop the audio from playing by 
  - reselecting the token, dragging it outside the audio area (sometimes), and then deselecting
  - enabling "preview ambient sounds" and carefully dragging the mouse through the ambient audio region, carefully avoiding crossing walls (other than doors) before mouse leaves
  - refreshing (cached or cacheless)

## [Video of the behaviour in action](https://cdn.discordapp.com/attachments/1098958758501154927/1260738115698688091/token-audio-issue.webm?ex=6696581e&is=6695069e&hm=f9ed55d2a65c913578a491b6e4fe5031f6712a6a7cf6a75acb2247b515952860&)
