### ISSUE TITLE
Fog of war is cleared when the GM drags a token across a one-sided wall with a darkness source on the other side

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10874]
Originally reported by patrikp https://discord.com/channels/170995199584108546/1184176415139184731/1237657252257730610

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows, NodeJS(v20), Chrome
**Short Description of bug**: Fog of war clears when GM drags player across on-sided wall in room with dark source
**Simple steps to reproduce the bug**:
Create an empty scene with fog of war and token vision active
Create 2 rooms sharing a wall with Wall Direction=left
Place a light source with Is Darkness Source = checked in the right room
Place a token in the left room
Give the token a light radius
Move the token from the left room to the right room using keys
As GM, drag the token from the right room to the left room using the mouse
Result: The fog of war has cleared in the right room in a half circle where the token crossed the wall
Expected result: The fog of war remains in the right room
Note: It works as expected if it is a normal 2-sided wall and the GM drags across in both directions, or if it's a 2-sided wall without movement restriction.

**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/ba0579c4-1f08-4f03-b33c-43c59bbd5a41)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/5e27a55a-163f-4cb2-b681-70f43fc117b9)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/650b6acd-251e-4b34-8707-60a7267dda47)

**Comment by dev7355608** [comment]
I suspect the underlying issue here is the same as #10839.
