### ISSUE TITLE
Allow overriding the valid `types` in a document class's `createDialog` method

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#10870]
### User Experience

Currently the `createDialog` method determines the valid types itself. Depending on the context of where and when a document is created, it would be good to be able to supply only a subset of the regular options.

E.g., simply being able to call `#createDialog(data, {types: someSubset})`.

(Related to #5349, but not in my opinion the same use case.)

**Comment by aaclayton** [comment]
Nice suggestion

**Comment by aaclayton** [comment]
@dev7355608 can you take a look at this? I know you were working recently on the document creation dialog with improving the default naming conventions.
