### ISSUE TITLE
Freehand drawings are not automatically controlled after creation

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10885]
### What happened?

All other types of drawings become controlled afer you finish placing them. The same behavior should be added for freehand drawings also for consistency.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create Freehand Drawing

### What core version are you reporting this for?

12.322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
This is intentional behavior, to allow successive freehand drawings.
