### ISSUE TITLE
Don't display notification unless multiple Placeable Objects are deleted by the Delete key or recreated/deleted by CTRL+Z

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10890]
### User Experience

The notification raised when hitting CTRL+Z can become a bit "spammy" if you're trying to cycle back through multiple history items rapidly. As an example, place a half dozen walls or so and then hit CTRL-Z til they're gone. 

@dev7355608 suggested cancelling the last notification before displaying the next one for CTRL-Z, CTRL+C, and CTRL-V notifications.

**Comment by unsoluble** [comment]
(and Delete)
