### ISSUE TITLE
Omit 'dialog-content' of `DialogV2` instances if `content` is undefined

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#10894]
### User Experience

When making a simple confirmation dialog or prompt, it is often enough to have the "question" in the header and omitting the `content` property.

Currently this causes the DialogV2 instance to render with `<div class="dialog-content">undefined</div>`.

If using `content: ""`, the `.dialog-content` div tag is still added, but with 0 height. However, the default styling adds a big margin.

It would be nice if this content tag was entirely optional.

**Comment by aaclayton** [comment]
Good suggestion and a simple fix. Tossing to @Fyorl
