### ISSUE TITLE
Minor CSS issues in Filepicker application

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10891]
### What happened?

There are a few minor CSS issues that could be tweaked in the Filepicker application:

**Unexpected font color:**
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/6172149b-a0ed-4a7b-bedd-ed9c7e3a76a9)

**The well is missing around the favorited paths:**
_Previously (preferred):_
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/fbe46995-f1b3-4a8b-994a-b5d55b515418)

_Current:_
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/7eefc3c7-093b-4593-a918-9a917bd59bf8)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. In Foundry, open the Filepicker dialog

### What core version are you reporting this for?

12.322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I fixed the color of the hint text but left the favorites tags as is to be more compatible with other design elements.
