### ISSUE TITLE
`ProseMirror` editor loses focus when a dropdown menu item is clicked

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#10899]
### What happened?

This might be a side effect of #8212, I'm not sure if it was the same before that.
Adding `this.view.focus()`  at the end of `ProseMirrorMenu#_onAction` fixed it for me.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Click any dropdown item and observe the editor losing focus.

### What core version are you reporting this for?

Version 12 Build 322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Probably related to the dropdown change. Tagging @Fyorl to take a look.
