### ISSUE TITLE
Monochromatic and Light Amplification vision modes do not render correctly in areas illuminated by light sources

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10911]
Monochromatic: Illuminated areas should be grayscale.
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/f7981ed1-8647-4667-938c-657ab078a52d)

Light Amplification: Illuminated areas should be only shades of green.
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/3f71079c-7152-49ec-a27f-b83c00435d23)

**Comment by aaclayton** [comment]
@dev7355608 @Feu-Secret what should the priority be here?
