### ISSUE TITLE
Ambience filter effects are not applied to the background color of the Scene

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#10927]
### What happened?

The purple token tinting is incredibly powerful to the point where we had to reduce dark scene luminosity in preCreate (to 0, but now I'm considering -0.25) because people thought it was a bug. Reset to defaults unfortunately foils that plan though, because the defaults are hardcoded.

![image](https://github.com/foundryvtt/foundryvtt/assets/1286721/6cf4ab3d-d01f-44e3-8c83-fe627d0d2659)

A closer look
![image](https://github.com/foundryvtt/foundryvtt/assets/1286721/215226a5-e1a3-461e-9646-299046318539)

Something to consider though is how it looks on a real map. For example alaustin in in the discord posted this example. Undoing the tint on just the tokens will look like weird behavior. The actual solution is beyond me, but perhaps altering the default works well as a short term bandaid?
<img width="418" alt="Foundry_Virtual_Tabletop_RkxbWwYEC3-1" src="https://github.com/foundryvtt/foundryvtt/assets/1286721/51b41d69-e2f9-4740-90bc-2e15749200f1">

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Make a new scene, then transition it to darkness. Create a new actor and place on the scene. Create a new light source and place on the scene.

### What core version are you reporting this for?

12.322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
> we had to reduce dark scene luminosity in preCreate (to 0, but now I'm considering -0.25)

I think the visual phenomenon you are commenting on here is more related to hue intensity rather than luminosity.

**Comment by CarlosFdez** [comment]
The luminosity slider in the environmental dark settings seems to be what triggers this behavior. Reducing it to -0.25 from -0.5 renders mystery man in light visible again. It could be that hue intensity uses luminosity to compute the result though?

**Comment by dev7355608** [comment]
The issue is that the ambience filter effects are not applied to the background color of the scene. This is what it's supposed to look like:
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/b032c640-76cb-44db-ab31-45446855c1fd)

**Comment by Norc** [comment]
To clarify, this issue was only occurring when no background image was set.

**Comment by CarlosFdez** [comment]
Ah, so there was a bug, I just didn't ID it. Awesome!
