### ISSUE TITLE
`EmbeddedCollectionField` has a static `hierarchical` field. Did you mean `recursive`?

### ISSUE THREAD

**Issue by kmoschcau** [foundryvtt/foundryvtt#10926]
### What happened?

As it says in the title. The field is doc-comment tagged with `@override`, but there is no such field in the class hierarchy. This seems like you meant `recursive`.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

Look at the code.

### What core version are you reporting this for?

Version 11.315

### Relevant log output

```shell
None
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
[DataField.hierarchical](https://foundryvtt.com/api/v12/classes/foundry.data.fields.DataField.html#hierarchical)

**Comment by kmoschcau** [comment]
> [DataField.hierarchical](https://foundryvtt.com/api/v12/classes/foundry.data.fields.DataField.html#hierarchical)

Yep makes sense. Was just surprised by it being there in v11, but this field not existing on supertypes yet.
