### ISSUE TITLE
ObjectField({ required: false, nullable: true }) doesn't actually allow null/undefined values unless cast is overridden

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10928]
`ObjectField#_cast` will transform any `null` or `undefined` values into `{}` even if `required: false` is set. One example of this is the `AdditionalTypesField` that's used in `BaseModule` and as of v12, `BaseSystem`.

I'm good with the defaults, but maybe `_cast` should be updated to account for this options or a note should be made that downstream developers should also implement their own `_cast` method.

**Comment by aaclayton** [comment]
Pushed a fix to `ObjectField` which allows it to be initialized as `undefined` in cases where `{required: false}` or initialized as `null` in cases where `{required: true, nullable: true}`, otherwise initialized as an empty object `{}`.
