### ISSUE TITLE
Consider adding an option to `RegionBehavior`s that execute code or a macro to only be run by the active GM

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#10947]
## Implemented changes

- Added the `everyone` boolean field to `ExecuteMacroRegionBehaviorType`. The initial value is false.
- Existing (pre Stable 3) Execute Macro behaviors are migrated such that `everyone` is true.
- Added `Macro#canUserExecute(user: User)`, which tests whether a given User can execute the Macro. `Macro#canExcute` now calls `Macro#canUserExecute` with the current User.

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/3f401d82-ceff-4bfa-889b-ef8e6dcc3298)

### User Experience

This can be solved now by adding `if (game.user !== game.users.activeGM) return` to the executed code but could be simplified by providing such an option.

Discord discussion: https://discord.com/channels/170995199584108546/1184176344276406292/1241371772830617600

**Comment by krbz999** [comment]
Will this be an option for the Execute Script behavior too, or only macro execution?

**Comment by dev7355608** [comment]
> Will this be an option for the Execute Script behavior too, or only macro execution?

Specific for Execute Macro. The logic that selects the user that should handle the macro execution is based the macro permission.

No change for Execute Script behaviors. Not sure if we really a similar option for it considering one can easily add `if ( game.users.activeGM?.isSelf ) return;` at the top of the script.
