### ISSUE TITLE
Document._preCreate is missing some options

### ISSUE THREAD

**Issue by NekroDarkmoon** [foundryvtt/foundryvtt#10944]
### What happened?

The options property in `Document._preCreate(data, options, user)` no longer propagates the `noHook`, and `pack` options.  

```js
static async #preCreateDocumentArray(documentClass, operation, user) {
  const {data, noHook, pack, parent, ...options} = operation;
  ...
  // Call per-document workflows
  let documentAllowed = await doc._preCreate(d, options, user) ?? true;
  documentAllowed &&= (noHook || Hooks.call(`preCreate${type}`, doc, d, options, user.id));
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

**Step 1:** Create an embedded document in an actor
```js
const ids = (await this.actor.createEmbeddedDocuments('Item', items, { noHook: true, keepId: true }));
```
**Step 2:** In `Item._preCreate` observe the options property.

### What core version are you reporting this for?

Version 12 Testing 4 Build 323

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
It is intentional that these options (nohook, pack, and parent) are extracted from the `options` object so that they cannot be modified elsewhere in the operation. If you were relying on this option to be passed, please explain your use case so we can consider other ways to accommodate it.

**Comment by NekroDarkmoon** [comment]
In the A5E system, we have a workflow for adding documents related to a class when it's first created. This is done in `Item,_preCreate`. These items themselves can also grant other items. We've been preventing the workflow from firing multiple times using the `noHook` option like so,
```js
const ids = (await this.actor.createEmbeddedDocuments('Item', docs, { noHook: true }));
```
```js
// Apply grants if any
    if (this.parent && this.parent.documentName === 'Actor') {
      const actor = this.parent;
      // Keep id of the original document
      options.keepId = true;
      if (!options.noHook) actor.grants.createInitialGrants(this, true);
    }
```

As a system, it was easier to do this in `Item._preCreate` instead of the item pre-create hook, because we have additional logic separated out into multiple classes for different item types.

**Comment by krbz999** [comment]
Nothing stops you from just slapping in your own option, e.g., `noGrant: true`.

**Comment by NekroDarkmoon** [comment]
> Nothing stops you from just slapping in your own option, e.g., `noGrant: true`.

I uh... did not realize that. I thought it would get cleaned out.

**Comment by NekroDarkmoon** [comment]
Sweet that works too. Thanks <3
