### ISSUE TITLE
In systems without localization, `ClientDocument.defaultName()` returns a localization key rather than a Document type

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10959]
Initial report: https://discord.com/channels/170995199584108546/1184176415139184731/1241757939300044940
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/6053829a-ee44-40c6-b395-fd799123ae57)

**Comment by drewg13** [comment]
I appreciate the quick fix and that did solve the issue as stated, but now the issue has been shifted to the Types field, which is probably worse than just a confusing default name.

![image](https://github.com/foundryvtt/foundryvtt/assets/1455026/6a1135e7-bdaf-4e27-9080-7656a0e190a2)

**Comment by aaclayton** [comment]
You have to laugh.

**Comment by drewg13** [comment]
I did!  That was my first reaction.  😆
