### ISSUE TITLE
Selecting text in a journal page no longer works in TinyMCE editor

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10957]
Initial report: https://discord.com/channels/170995199584108546/1184176415139184731/1241678301790076989
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/b02c996c-c2a6-453a-b659-961bfe9af80b)

**Comment by farling42** [comment]
I should clarify that it is the display of the selected text which is not working - I assume a CSS change has caused this.
