### ISSUE TITLE
Loading a large number of chat messages at once causes duplicate rendering

### ISSUE THREAD

**Issue by Ghostdesu** [foundryvtt/foundryvtt#10951]
### What happened?

For context, my group uses Foundry to play in text, so the chat log tends to be quite large (a few thousand messages per session). We regularly export and purge it to keep the size down, but that's besides the point. 
Scrolling back up in a long chat log appears to render entire chunks of the chat multiple time back to back (usually only twice, though it can get higher sometimes). 

As the result, the issue ends up looking something like this:

> [chat log going as usual]
> A: hi
> B: we are going to go kill trolls now
> C: i love monster hunting
> [rest of the repeated batch of ~50-100 messages]
> A: hi
> B: we are going to go kill trolls now
> C: i love monster hunting
> [rest of the repeated batch of ~50-100 messages]
> [chat log continues as usual]

Sometimes the messages repeat more than twice if I load even more at once (for example, if I'm scrolling back multiple sessions worth in one go).

I was only able to test the issue with the Pathfinder 2e system since I don't currently have another world with a large number of messages. 
Tested this with Chrome and Firefox on Windows 10, the server is running on a remote Ubuntu server.

Example: [Video on GDrive](https://drive.google.com/file/d/1A7H8Ma-RuU-gHL09i4qbk6kMJVJk5aw-/view) (make sure to set higher quality to see text)

Foundry settings: 
![settings 1](https://github.com/foundryvtt/foundryvtt/assets/31375910/34b268f4-d6c6-4e01-8266-c4e1eb0034f8)
![settings 2](https://github.com/foundryvtt/foundryvtt/assets/31375910/54b89790-81b5-4f74-b3d1-192fc1f1e394)

The actual internal chat log is unaffected, during my testing I have seen the same chunk of chat in the example video not duplicate at times, further evidenced by the txt export only containing the two instances of the phrase I searched (as opposed to 3 instances in the rendered chat, one extra being a duplicate): 
![actual log unaffected](https://github.com/foundryvtt/foundryvtt/assets/31375910/aeaa29fb-9a9f-4891-bab4-a3d2752d431a)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open a Foundry world with a large number of chat messages (at least 1000+). 
2. Scroll up until Foundry loads at least ~5 batches of messages.
3. Copy and Ctrl+F messages to check if it is duplicated until you find one, older messages are more likely to be affected.

### What core version are you reporting this for?

Version 11 Stable (build 315)

### Relevant log output

```shell
No errors in logs
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Not able to reproduce this. I used the Simple Worldbuilding System to eliminate any potential system interference. I generated 10,000 messages with the following:

```js
await (async function() {
  const now = Date.now();
  const iterations = 10_000;
  const hour = 60 * 60 * 1000;
  const start = now - hour * iterations;
  const messages = [];
  for ( let i = 0; i < iterations; i++ ) {
    const timestamp = start + hour * i;
    const content = `Message #${i}:<br>Lorem ipsum dolor sit amet. Eos quae dignissimos non internos quis sed inventore autem ad asperiores ullam.`;
    messages.push(new ChatMessage.implementation({ timestamp, content }));
  }
  await ChatMessage.implementation.createDocuments(messages);
})();
```

I refreshed the page to reset the chat log, then rapidly scrolled through several thousand messages with middle-click scroll. I then detected any duplicates in the generated HTML with the following, but there were no hits.

```js
(function() {
  const log = document.getElementById('chat-log');
  const messages = Array.from(log.querySelectorAll(':scope > li'));
  // Sort to place duplicates next to each other.
  messages.sort((a, b) => a.dataset.messageId.localeCompare(b.dataset.messageId));
  // Detect duplicates.
  for ( let i = 0; i < messages.length; i++ ) {
    const message = messages[i];
    const nextMessage = messages[i + 1];
    if ( message.dataset.messageId === nextMessage?.dataset.messageId ) {
      console.log('Duplicate detected', message, nextMessage);
    }
  }
})();
```

It's possible that this requires more latency to the server in order to manifest, I'm not sure.

**Comment by Ghostdesu** [comment]
For context, I generally have about ~50ms latency to my server (at least according to the user latency module) with a connection speed of about 300 Mbps (server has gigabit upload). 

I will try copying my world locally to see if I can still reproduce it.

**Comment by Ghostdesu** [comment]
I can confirm that I can still reproduce the issue on the same world hosted locally (Node JS version). 
However, I was not able to reproduce this when generating the text messages using the script above, neither by putting them into a new world, nor by putting them into the same world I originally noticed the issue in (modified to be spaced out by a second rather than an hour to put them at the bottom of the chat log). 

I suspect this might have something to do with the fact that many system-specific messages are much larger than plain text ones generated with the script (chat cards, rolls, messages with inline macro/item/damage roll/check links that have to be resolved, messages with images built in, etc), and so take longer to load.

**Comment by Fyorl** [comment]
> I suspect this might have something to do with the fact that many system-specific messages are much larger than plain text ones generated with the script (chat cards, rolls, messages with inline macro/item/damage roll/check links that have to be resolved, messages with images built in, etc), and so take longer to load.

Could be something like that. I wonder also if any of your messages contain embedded images? There is some special handling around waiting for images to load that might cause this.

**Comment by Ghostdesu** [comment]
A lot of the chat cards have at least one image, yeah. Action number cost icon, feat icon, spell icon, item icon, etc. A lot of them are repeats, and they are mostly under 100x100 resolution, but there are probably at least a hundred unique ones that I scrolled past in the example video. And there are a couple actual full scale images that players sent during the session using the Chat Images module (the module was disabled for testing, but the images naturally stick around).

**Comment by aaclayton** [comment]
Leaving this as HIGH priority for now so we can investigate whether this duplicate rendering has anything to do with lazy loading of chat message images.

**Comment by K4rakara** [comment]
Here's a snippet that can be run on archives that are affected by this issue, in the event that anybody else is running into this:
```js
(async () => {
  function nextFrame() {
    return new Promise((resolve) => requestAnimationFrame(resolve));
  }

  window.scrollTo(0, document.body.scrollHeight);

  let chatLog = document.querySelector("#chat-log");
  let messages = Array.from(chatLog.children);
  let processedThisFrame = 0;
  let totalProcessed = 0;
  let totalPruned = 0;
  let visited = new Set();
  
  for (let message of messages) {
    let messageId = message.getAttribute("data-message-id");
    
    if (!visited.has(messageId)) {
      let duplicates = Array.from(document.querySelectorAll(`.chat-message[data-message-id="${messageId}"]`));
      duplicates.shift();
      for (let duplicate of duplicates) {
        duplicate.remove();
        totalPruned++;
      }
    }
    
    totalProcessed++;
    if (++processedThisFrame >= 100) {
      console.log(`Processed ${totalProcessed} messages...`);
      await nextFrame();
      processedThisFrame = 0;
    }
  }

  console.log(`Processed ${totalProcessed} messages, pruning ${totalPruned}! Complete!`);
})()
```
On the logs here, it takes about a minute to a minute and a half to run, because it needs to pause execution each frame in order to avoid making the page (and the entire browser, in this case) unresponsive.

**Comment by dev7355608** [comment]
I am able to reproduce this issue reliably after I adding an artificial delay in `ChatMessage#getHTML`.
