### ISSUE TITLE
Missing labels and hints on prototype token config.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10953]
Initial report: https://discord.com/channels/170995199584108546/1184176415139184731/1241315914062757940
![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/9fb5ac67-ea93-4e01-bac0-fd85635a8036)

**Comment by aaclayton** [comment]
Resolved by https://github.com/foundryvtt/foundryvtt/issues/10962
