### ISSUE TITLE
On macOS, the installation window is a non-standard width

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10968]
### What happened?

As of 12.323, the window of the installer on macOS systems has a non-standard width:

![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/4030bc82-e8ad-42ea-8a76-96bf27ccac0a)

Matt confirms that this does not occur with older installers, so this is likely due to the Electron version upgrade.

**Note:** I could not reproduce this with the Windows installer. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Download the macOS installer for Foundry 12.323 or later on a compatible machine
2. Start the Foundry installation

### What core version are you reporting this for?

12.323

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This seems to have resolved itself. Closing and deleting.
