### ISSUE TITLE
Chat messages with multiple rolls require two clicks to expand a roll beyond the first

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#10970]
### What happened?

Using a chat macro such as this:
```
/r 1d6
/r 1d6
```
creates a message in  the chat with two rolls. Clicking one roll once expands it. This sets a flag on the message itself resulting in expanding the second roll requiring two clicks (first click removes the expanded flag and then goes no further).

Same issue naturally occurs when collapsing rolls.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Run above macro.
- Click first roll once.
- Click second roll once. (Nothing happens.)
- Click second roll again. (The second roll expands.)

(Best tested in a system such as SWB since it does not handle multi-rolls in different ways.)

### What core version are you reporting this for?

12.323

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think this issue no longer occurs. Closing as nonrepro.

**Comment by krbz999** [comment]
Definitely still happening on 12.331.
