### ISSUE TITLE
Left-clicking the "Copy ID" button in the header of a Document's configuration window should copy the UUID to the clipboard instead of the ID

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10975]
### User Experience

When clicking this button on any document, it would be more beneficial to copy the UUID rather than the ID:

![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/3f666c20-b6a5-4f18-a5a2-cf0fd01bd09c)

This provides a number of benefits:
1. Directly usable in the Scene Regions' Behavior dialogs
2. The "extra" bits can be deleted out to get the regular ID if needed.
3. More touch-friendly

**Optional**: Move the existing left-click behavior ("Copy ID") to occur on a right-click of the button instead.

**Comment by krbz999** [comment]
Doesn't that just mean users will get confused on how to copy the id instead of confused about how to get the uuid (which you can get currently via right-click).

**Comment by Norc** [comment]
Potentially. @krbz999 is there a use case where you feel this would be a particular problem in the UI for the average (non-macro-wielding) user?

The main motivation of this happening now is that if you copy the ID of a Macro or a Scene Region into a Scene Region Behavior, it throws an error currently because it needs the UUID, and even many experienced users don't know that you can get this by right-clicking this button.

**Comment by krbz999** [comment]
> Potentially. @krbz999 is there a use case where you feel this would be a particular problem in the UI for the average (non-macro-wielding) user?

I find users need the id equally as often as the uuid. The actual root of the problem is that nothing indicates this single button has two functions.

**Comment by Norc** [comment]
Understood. In this case, the UUID includes the ID as a subset of itself. I think this is good feedback for keeping the ID as a right-click behavior, though. 

Perhaps some further consideration can be given this in the future for improvements here, but for V12 Stable at least I feel this change will be massively a net positive.

**Comment by unsoluble** [comment]
Why not mention both in the same tooltip?
