### ISSUE TITLE
Edges of inactive but not disabled or suppressed darkness sources are not created

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10973]
This bug allows Tokens with a Vision Mode that disables the visibility (rendering) of the darkness layer to see into darkness sources.

```js
CONFIG.Canvas.visionModes.test = new VisionMode({
    id: "test",
    label: "Test",
    lighting: {
      darkness: { visibility: VisionMode.LIGHTING_VISIBILITY.DISABLED }
    }
});
```

![10973](https://github.com/foundryvtt/foundryvtt/assets/31905376/7524e2dc-87e0-4258-952e-dc5d7ae9ce80)

**Comment by aaclayton** [comment]
Moving to V13 for more careful thought.
