### ISSUE TITLE
MergeObject culling static properties can cause error in Localization.#localizeSchema

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10979]
Using `foundry.utils.mergeObject` to assign data models will cull any empty static properties from the model, such as `DataModel.LOCALIZATION_PREFIXES` which starts as an empty array. This can cause an error in `Localization.#localizeSchema`, which assumes the `prefixes` passed in are at least an array. If the property is instead `undefined`, such as post-`mergeObject`, then the function will error.

The fix is easy: Change `if ( !prefixes.length ) return;` to `if ( !prefixes?.length ) return;` so if `prefixes` is somehow `undefined` then it won't error.

**Comment by JPMeehan** [comment]
The error-causing code was the following.
```js

Hooks.on("init", () => {
    foundry.utils.mergeObject(CONFIG.Actor.dataModels, {
        "test-companion-actor.minion": MinionModel,
    });

    foundry.utils.mergeObject(CONFIG.Item.dataModels, {
        "test-companion-actor.treat": TreatModel,
    });
})
```

**Comment by anathemamask** [comment]
@aaclayton I have tagged this to V12 stable 1 as an urgent priority **for your assessment** as it reportedly results in worlds failing to load; 

While the consensus between ChaosOS and Supe is that this probably won't be a show stopper, it does look to be a very simple fix to implement and I wanted to be sure that it gets a look from someone with the knowledge to know what they're looking at.

**Comment by aaclayton** [comment]
This code already changed due to a separate bugfix staged for V12 stable. `prefixes` passed into `static #localizeSchma` defaults to an empty array if it was undefined.
```js
static #localizeSchema(schema, prefixes=[], {prefixPath=""}={}) {
```
This should be sufficient to avoid the issue if I understand correctly.

**Comment by JPMeehan** [comment]
Yeah that would also do it!

**Comment by JPMeehan** [comment]
For what it's worth it wasn't my code that did it, the issue was discovered by a pf2 dev who was trying to see if they should support module subtypes and how much work that would be.
