### ISSUE TITLE
Cross-generation update message contains malformed URL

### ISSUE THREAD

**Issue by kylania** [foundryvtt/foundryvtt#10991]
### What happened?

The link for "foundryvtt.com" on the Update Notes - Version 12 1 has a / instead of . leading users to https://foundryvtt/com/me/licenses instead of https://foundryvtt.com/me/licenses when told to download the software to re-install.  See attached image.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Click the "foundryvtt.com" link in the "re-installing the software from the foundryftt.com website." line.
![Screenshot 2024-05-22 215904](https://github.com/foundryvtt/foundryvtt/assets/119372/6fd46dc4-a31a-403c-8097-3c70dda66c8f)

### What core version are you reporting this for?

Version 12.324 Release Notes

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
@anathemamask and I took a look at this, and the text that contains the incorrect text isn't in the actual release notes, so this does look like a core bug.
