### ISSUE TITLE
Tokens do not immediately emit light on page load

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10997]
Originally reported by rabidowlbear https://discord.com/channels/170995199584108546/1184176415139184731/1243008302074433586

**ALL MODULES DISABLED?**true
**win10, self host, firefox/chrome**:
**Short Description of bug**: Token light sources cease to display light after page refresh/world load. The light display resumes when the token is controlled. This occurs on gm and player tokens. When logged in as a player on a refresh an owned token will retain its light display, but no other tokens that have light enabled display. Token Lighting works as expected in version 12.323
**Simple steps to reproduce the bug**: Create token, enable light radius, reload the page. Tested in the 5e and old school essentials systems.
**Screenshots and/or console errors**: No console errors

**Comment by RabidOwlbear** [comment]
I have found in my personal testing that this bug appears to be introduced in the 12.324 update, as this behavior is not occurring in version 12.323. Additionally I encounter this behavior in 12.324 when changing between maps in addition to page refresh and world load.
