### ISSUE TITLE
Consider adding `submitOnChange: true` to ActorSheetV2 and ItemSheetV2

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10993]
Actor and Item sheets are generally used in live play, which means while DocumentSheetV2 may default to needing a submit button, the default for Actors and Items should be to use `change` events.

**Comment by aaclayton** [comment]
These sheets are only a base class, they serve no function on their own, so there must inherently be a subclass of them which provides an actual implementation. That subclass should define `submitOnChange: true` if that is the behavior that is desired.
