### ISSUE TITLE
Missing model localization keys show up as blank rather than showing their keys

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11005]
Originally reported by yerrash https://discord.com/channels/170995199584108546/1184176415139184731/1243022532441800775

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: win10 self host
**Short Description of bug**: light sources window not having any text in some elements. This became a thing only in version 12.324, no problems in version 12.322.
**Simple steps to reproduce the bug**: create a light source, not changing any configs. Homebrew system with no CSS related to foundry windows, or changes to HTML in that regard.
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/77ee3ab8-b37b-41c1-84bc-aa66e3969f96)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/fcc14183-2790-4af9-a237-39951448ddc2)

**Comment by aaclayton** [comment]
Merging this with #11003
