### ISSUE TITLE
Sound#loaded should be false after its HTMLAudioElement has been unloaded. This fixes a bug which caused long-duration sound files to fail to play after they had completed playing once.

### ISSUE THREAD

**Issue by FramezyGD** [foundryvtt/foundryvtt#11004]
### What happened?

Trying to play 2 sounds at the same time in either separate or one playlist results in one track showing infinite duration and progress and doesn't play. Stopping and starting does not resolve the issue. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open foundry, go to audio, add playlist, add 2 sounds. Both looped. Output doesn't seem to matter. Set to simultaneous playback and press play on both sounds or by hitting play on the playlist.
![foundry audio playback error](https://github.com/foundryvtt/foundryvtt/assets/16341463/f03eba3a-8430-4a36-9f5a-d110b27fa896)

### What core version are you reporting this for?

Version 12 Stable - Build 324

### Relevant log output

```shell
Uncaught (in promise) DOMException: Failed to construct 'MediaElementAudioSourceNode': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at Sound._createNodes (http://localhost:30000/scripts/foundry-esm.js:51500:50)
    at #queuePlay (http://localhost:30000/scripts/foundry-esm.js:51127:12)
    at Sound.play (http://localhost:30000/scripts/foundry-esm.js:51106:42)
    at Sound.load (http://localhost:30000/scripts/foundry-esm.js:51039:14)
    at PlaylistSound.sync (http://localhost:30000/scripts/foundry.js:20065:11)
    at http://localhost:30000/scripts/foundry.js:20479:59
    at EmbeddedCollection.forEach (http://localhost:30000/scripts/foundry-esm.js:5020:9)
    at Playlist._onUpdate (http://localhost:30000/scripts/foundry.js:20479:44)
    at http://localhost:30000/scripts/foundry-esm.js:55782:15
    at http://localhost:30000/scripts/foundry-esm.js:55788:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (http://localhost:30000/scripts/foundry-esm.js:55788:33)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
I managed to reproduce this issue:

1. Play sound with a duration longer than 10 mins (or set `foundry.audio.Sound.MAX_BUFFER_DURATION = 0` for testing and play any sound).
2. Stop this sound.
3. Play this sound again.

Playback fails with the error mentioned above.

**Comment by dev7355608** [comment]
Originally reported by suzuxiii: https://discord.com/channels/170995199584108546/1184176415139184731/1243990915526430760

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable)**: Windows 10, hosted locally on the Foundry Desktop app and Firefox
**Short Description of bug**: Individual ambient sounds stop working after moving out of the range of the sound for the first time, both with tokens and with the preview ambient sound feature. File used is a 13.7 MB mp3 file. Foundry Version 12 Stable Build 324.
**Simple steps to reproduce the bug**: Draw an ambient sound, move token in and then out of range of the sound, or use preview ambient sound and move mouse in and then out of range of the sound.
**Screenshots and/or console errors**: Attached below.

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/b07dcd88-32bd-4546-9071-d9bb95a268a3)

**Comment by aaclayton** [comment]
Comment from @Fyorl 

Note, I was not able to reproduce this issue as described. This only occurred when using a >10 min track, and I received a different error instead:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/96df1cb8-d21b-49f8-88db-69bb288d83ee)
