### ISSUE TITLE
DiceTerms with negative numbers evaluate as 0

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt/foundryvtt#11010]
### What happened?

/r -3d6 in v12 resolves to 3d6 * -1
The following, which should be equivalent, don't result in the same outcome:
/r (-3)d6 in v12 results to 0
/r min(0,-3)d6 in v12 throws a SyntaxError
/r (min(0,-3))d6 in v12 results to 0

See discord https://discord.com/channels/170995199584108546/1184176344276406292/1243118292504285226

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Roll `-3d6` and observe the result.
Then roll any of the following formula and observe that they don't result in the same as the first formula.

### What core version are you reporting this for?

12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mkahvi** [comment]
The first one shouldn't be adding `* -1` even.

**Comment by Fyorl** [comment]
> The first one shouldn't be adding `* -1` even.

This is generally needed to resolve issues with leading operators in the grammar. Is `-3d6` not equivalent to `3d6 * -1`? It's important to know because it will inform how we resolve the issue with `DiceTerm#number` being negative in general.
