### ISSUE TITLE
For tabbed App v2 Configs, move tabs to a static object

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#11023]
### User Experience

For App v2 configurations like `AmbientLightConfig`, the `getTabs` method is currently private. This poses some difficulty for anyone (modules or systems) that want to either add a tab or extend the class because the tabs are defined and the active tab set within this private method. If instead tabs were defined as a static object, this would become much easier.

Using `AmbientLightConfig` as an example, currently `AmbientLightConfig.prototype#getTabs` looks like:
```js
    #getTabs() {
      const tabs = {
        basic: {id: "basic", group: "sheet", icon: "fa-solid fa-lightbulb", label: "AMBIENT_LIGHT.SECTIONS.BASIC"},
        animation: {id: "animation", group: "sheet", icon: "fa-solid fa-play", label: "AMBIENT_LIGHT.SECTIONS.ANIMATION"},
        advanced: {id: "advanced", group: "sheet", icon: "fa-solid fa-cogs", label: "AMBIENT_LIGHT.SECTIONS.ADVANCED"}
      };
      for ( const v of Object.values(tabs) ) {
        v.active = this.tabGroups[v.group] === v.id;
        v.cssClass = v.active ? "active" : "";
      }
      return tabs;
    }
```

My proposal would be to first define a static tabs object, similar to how `PARTS` is defined.
```js
AmbientLightConfig.TABS = {
        basic: {id: "basic", group: "sheet", icon: "fa-solid fa-lightbulb", label: "AMBIENT_LIGHT.SECTIONS.BASIC"},
        animation: {id: "animation", group: "sheet", icon: "fa-solid fa-play", label: "AMBIENT_LIGHT.SECTIONS.ANIMATION"},
        advanced: {id: "advanced", group: "sheet", icon: "fa-solid fa-cogs", label: "AMBIENT_LIGHT.SECTIONS.ADVANCED"}
      };
```

Then the `#getTabs` method can be simplified:
```js
    #getTabs() {
     const tabs = this.constructor.TABS; // Consider using `duplicate` here to avoid modifying the TABS object.
      for ( const v of Object.values(tabs) ) {
        v.active = this.tabGroups[v.group] === v.id;
        v.cssClass = v.active ? "active" : "";
      }
      return tabs;
    }
}
```

**Comment by stwlam** [comment]
> @stwlam we have done this a couple of times now while doing AppV2 refactors. Do we know enough about the problem now to commit to a standard spec that we could implement as a framework for all apps?

Mixed opinions: the core applications converted thus far are _simple_ insofar as they only have a single column of tabs along the top of the window. Thus they have fairly uniform tab preparation--including a `static TABS` property--and are useful as a reference when developing new apps. But that pattern could easily fall short in an application with virtually unlimited potential for complexity, such as an actor sheet. 

Currently there is a core application under development for V13 with tabbing and subtabbing intricate enough that the "standard" pattern isn't of great use. If/when one or two more of that variety are built out, a more widely applicable standard may emerge.

**Comment by stwlam** [comment]
There is now a static `ApplicationV2.TABS` property:
```js
  /**
   * Configuration of application tabs, with an entry per tab group.
   * @type {Record<string, ApplicationTabsConfiguration>}
   */
  static TABS = {};
```

With the configuration data defined as:
```js
/**
 * @typedef ApplicationTabsConfiguration
 * @property {{id: string; icon?: string; label?: string; tooltip?: string}[]} tabs An array of tab configuration data
 * @property {string} [initial]     The tab in this group that will be active on first render
 * @property {string} [labelPrefix] A localization path prefix for all tabs in the group: if set, a label is generated
 *                                  for each tab using a full path of `${labelPrefix}.${tabId}`.
 */
```

Example utilization in `DrawingConfig`:
```js
  /** @override */
  static TABS = {
    sheet: {
      tabs: [
        {id: "position", icon: "fa-solid fa-map-marker-alt"},
        {id: "lines", icon: "fa-solid fa-paint-brush"},
        {id: "fill", icon: "fa-regular fa-fill-drip"},
        {id: "text", icon: "fa-solid fa-font"}
      ],
      initial: "position",
      labelPrefix: "DRAWING.TABS"
    }
  };
  ```
