### ISSUE TITLE
Evaluate drag distance based on screen coordinates instead of canvas coordinates.

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/foundryvtt#11028]
### What happened?

Currently, it's possible to pan the canvas by right-clicking and dragging the cursor across the screen.  Left-dragging will let you use rectangular selection, or drag tokens around.  Long-pressing left click in the same spot will create a ping.

The code for `#handlePointerMove` has these lines:

```js
      data.destination = event.getLocalPosition(this.layer, data.destination);
      // (...)
      const dx = data.destination.x - data.origin.x;
      const dy = data.destination.y - data.origin.y;
      const dz = Math.hypot(dx, dy);
      const r = this.options.dragResistance || (canvas.dimensions.size / 4);
      if ( dz >= r ) this.#handleDragStart(event);
```

Because most classes don't have a defined `dragResistance`, this calculation ends up comparing the **local (canvas-coordinates) distance** of the mouse drag gesture to a **static number (25% of canvas size)**, making a "drag" event require moving the mouse a certain **canvas distance** rather than a certain screen distance.

As a result, users need to move their cursor a longer screen distance when they're zoomed in and trying to pan, to select placeables, or to drag a token, which makes controls feel somewhat laggy.  Another result is that long-pressing to ping becomes harder when the canvas is significantly zoomed out (mostly affects users who can't keep their mouse perfectly stable).  Drawing is also harder, though I think it's been locally solved for the drawing tool already.

The behavior of differentiating between drag and long-press gestures based on canvas distance seems odd;  it makes a bit of sense for grid-snapped things like walls, but overall I think it's usually not desirable.

I implemented a fix for this in my module [Zoom/Pan Options](https://github.com/shemetz/ZoomPanOptions/) - see the "Drag resistance mode" setting for Scaling, you can compare how it feels vs the foundry default.

Please consider changing this drag resistance code to depend on screen distance and not canvas distance!

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See description - for example, try to pan the canvas in short bursts while zoomed in as much as you can.

### What core version are you reporting this for?

Version 12 Stable

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Not a bug since this design was intentional, but flagging it as a UX issue we could discuss whether we want to change to evaluate the drag resistance in screen pixels rather than canvas pixels.
