### ISSUE TITLE
Remove Folder moves items to root not parent folder

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/foundryvtt#11025]
### What happened?

When you remove a folder in a compendium thats already within a folder, the items are moved to the root of the compendium not to the parent folder

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) have a compendium with a target folder in a folder and put items in the deeper folder
root
    ->folder
          -->target folder
2) right click to remove the target folder with the items
3) items are in root not parent folder

### What core version are you reporting this for?

version 11 build 315

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by esheyw** [comment]
Can confirm this behaviour is unchanged in 12.324
