### ISSUE TITLE
Scene light/dark transition "jumps" when the Global Illumination Threshold is less than 1

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#11038]
## Implemented changes

The initial value of `Scene#environment.globalLight.luminosity` was unintentionally and incorrectly set to 0.5 (which the default value for normal light sources). We added a migration that reset the global illumination luminosity to 0 for all scenes to correct this issue. Global illumination will provide the same brightness level as in V11 by default after the migration, which is no visible brightness change when it is toggled on.

### What happened?

The transition looks like this for me when the threshold is less than 1:
![Recording 2024-05-26 at 23 28 31](https://github.com/foundryvtt/foundryvtt/assets/41452412/f8eda73b-efbf-4aef-8c4a-cf8f693f52e1)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create a new scene or reset scene settings to default
- Set `Global Illumination Threshold` to less than 1
- Transition scene to darkness

### What core version are you reporting this for?

Version 12 Build 324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Related to a global light luminosity issue we are discussing internally for a proposed fix.
