### ISSUE TITLE
Consider adding a Scene Region event that fires for all tokens inside a region when it is created

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#11043]
### User Experience

Currently the only way to have a Region affect a token on load or when the scene changes is to iterate through `canvas.tokens.documentCollection` and then checking each `TokenDocument#regions` for a specific behavior in the `canvasReady` hook.

**Comment by dev7355608** [comment]
We have the `BEHAVIOR_STATUS` event:
   - A Region Behavior is `active` after it is created while it isn't disabled until it's deleted.
   - A Region Behavior is `viewed` while it is `active` and the Scene of its Region is viewed.
```ts
// === Region event data of BEHAVIOR_STATUS ===
{
  // `true` if the behavior is created while enabled or the behavior is enabled
  // `false` if the behavior is deleted while enabled or the behavior is disabled
  // `undefined` if the `active` state didn't change
  active: boolean | undefined;

  // `true` if active and the Scene of its Region is viewed
  // `true` if the Scene of its Region is viewed and the behavior becomes active
  // `false` if `active` and the Scene of its Region is unviewed
  // `false` if it was viewed and the behavior becomes inactive
  // `undefined` if the `viewed` state didn't change
  viewed: boolean | undefined;
}
```

For example, the *Adjust Darkness Level* and *Suppress Weather* behaviors use it.
