### ISSUE TITLE
`NumberField#_toInput`'s range-picker bugs

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#11040]
### What happened?

If no `config.value` is set on a range, the range-picker's inputs won't have a value, even though it could pick up on `this.initial`.

If `NumberField.required` is true, the range-picker's inputs won't have a `required` value, even though it could pick up on `this.required`.

Overall, `NumberField#_toInput` feels really stingy on its requirements.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
getData() {
  const input = new NumberField({ initial: 10, min: 1, max: 10, required: true });
  return { input };
}
```

```html
{{formGroup input name="whatever"}}
```

Resulting HTML
```html
<range-picker name="whatever" min="2" max="20" step="1">
  <input type="range" min="2" max="20" step="1">
  <input type="number" min="2" max="20" step="any">
</range-picker>
```

### What core version are you reporting this for?

V12.324

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I have added support such that a nullish `config.value` will fall back to the initial value for the field. As for `required: true` this isn't automatically done because it's an opinionated choice for HTML markup. You can do this yourself as:
```hbs
{{formGroup input name="whatever" required=true}}
```
