### ISSUE TITLE
Implement a wide range of documentation fixes to improve generated docs quality

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11050]
Collecting type errors as I work through v12, follow up to #10227 

New in v12
- [x] `ApplicationV2#_insertElement` allegedly returns the inserted HTML element, but the function itself returns void and the only use of it in the codebase doesn't leverage the return.
- [x] HTMLDocumentTagsElement alleges the FormInputValue is `Record<string, string>`, but `_getValue` returns `string | string[]`
- [x] `HTMLProseMirrorElement#disconnectedCallback` is marked with `override`, but there doesn't appear to be any function its overriding or inheriting from.
- [x] The `Plugin` referenced as a type in `HTMLProseMirrorElement` is the deprecated browser version, rather than Prosemirror's plugins.
- [x] `ProseMirrorInputConfig` should just extend `FormInputConfig` with those extra properties, rather than the weird extension-of-the-import that's currently happening.
- [x] `HTMLRangePickerElement#valueAsNumber` should return `number` since that's the specified type for the generic.
- [ ] The linting in `resources/app/client-esm/client.mjs` is inconsistent, specifically variable use of semicolons. [RESPONSE: TOO GENERAL TO BE ACTIONABLE]

Holdovers from v11.315
- [x] Many functions return `Object<InnerType>` when more properly that should be `Record<string, InnerType>`
- [x] `RenderFlagsMixin(Base)` annotates Base as type `PIXI.DisplayObject`, but should be eligible to take any class constructor [per Atro](https://discord.com/channels/170995199584108546/811676497965613117/1177701903795245148)
- [x] References to `PIXI.filters` should just be `PIXI`, e.g. `PIXI.filters.BlurFilter` => `PIXI.BlurFilter`
- [x] `PIXI.Mesh` does not have a method `addChildren()`, and so it does not need to be overridden and throw an error in PointSourceMesh
- [x] `SpriteMesh#_transformID` is marked as `private` by PIXI.Mesh, but SpriteMesh performs an override anyways [RESPONSE: we don't have a choice, but I will mark as `@private`]
- [x] `VisibilityFilter.calculateMatrix` has the wrong parameter type; `PIXI.FilterSystem` is valid, `PIXI.FilterManager` is not.
- [x] `GlowOverlayFilter#animated` is mis-typed as `number` instead of `boolean`
- [x] `GlowOverlayFilter.createFragmentShader` and `OutlineOverlayFilter.createFragmentShader` are marked with `@inheritdoc`, but they don't inherit the method from anything.
- [ ] `CanvasLayer.instance` is typed as returning a CanvasLayer, but `WeatherEffects.instance` returns an `EffectsCanvasGroup`, which is an extension of `PIXI.Container` rather than `CanvasLayer` [RESPONSE: skipping this one, too problematic]
- [x] `CompendiumCollection#ownership` is typed as `number` but should be some proper Record of USER_ROLES and DOCUMENT_OWNERSHIP_LEVELS
- [x] `FilePickerOptions#favorites` and other related fields are typed as a `Map`, but `Record` is more accurate.
- [x] `DirectoryApplicationMixin#_sortRelative` is missing an @ on its returns notation
- [x] `Compendium#_getDocumentDragData` is marked as an override but does not in fact inherit from anything. It also doesn't appear to be called anywhere?
- [x] `ChatPopout#_renderInner` has an `options` parameter which is never used *and* is never fed in, as `_renderInner` is only called with a single argument: the return of `getData`.
- [x] Hook Events
  - [x] `canvasDraw` refers to `The Canvas instance being deactivated`
  - [x] `destroyObject` refers to `The object instance being refreshed`
  - [x] The description for `chatBubble` is `A hook event that fires when some useful data is dropped onto a RollTableConfig.`. This seems less correct than the v9 `A hook event that fires when a chat bubble is rendered.`
  - [x] `initializeRenderedPointSourceShaders` should be renamed to `initializeRenderedEffectSourceShaders` to match the defining class rename
  - [x] `chatMessage` incorrectly types `chatData.user` as `User`, when it should be `string` since it feeds the ID.

**Comment by aaclayton** [comment]
Is it necessary to have this as a separate issue from #10227 which is still open and active? Or does that serve an organizational purpose for you that is best to remain separated?

**Comment by JPMeehan** [comment]
Not really, would need to retitle and probably check in on any type errors that are now obsolete. One option would be I could transfer standing issues to this ticket and close the old one, since it doesn't look like there will be another v11 release where it would make sense to dual-track the typing fixes.

**Comment by aaclayton** [comment]
There will not be another v11 release, but we were still going to try and correct the issues you raised (if they still apply).

**Comment by JPMeehan** [comment]
> There will not be another v11 release, but we were still going to try and correct the issues you raised (if they still apply).

I think what makes the most sense is I transfer valid type issues to this ticket and close the old one, since that's about type errors in 11.315 and this is for 12.324

**Comment by JPMeehan** [comment]
OP has been updated for still-valid issues.

**Comment by esheyw** [comment]
I'm going to use this comment to compile my findings in this vein now that I'm working on the types project:
- `VisionMaskFilter#enabled` is a no-op setter

**Comment by DenWav** [comment]
The type definition for `DocumentModificationContext` was removed in v12, however it is still referenced in 4 places, so not sure if that would be considered a "deprecation" or if there's a more appropriate way of handling that.

**Comment by JPMeehan** [comment]
@aaclayton regarding the linting in `client.mjs` - the import and export statements are inconsistent if they have a semicolon at the end of the line, which won't affect the docs but struck me as something that a linter should be catching
