### ISSUE TITLE
Item#getDefaultArtwork no longer being called upon creation of an item document.

### ISSUE THREAD

**Issue by EndlesNights** [foundryvtt/foundryvtt#11074]
### What happened?

When updating Systems from from v11 to v12, subclasses that extends off of the Item class can no longer overrider the `foundry.documents.BaseItem` static function `getDefaultArtwork` .

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Using the Simple World Building system as an example, add the following function to the `SimpleItem` class from `item.js`, and create a new item.

```js
  	/** @inheritdoc */
	static getDefaultArtwork(itemData) {		
		return {img: "icons/svg/cancel.svg"};
	}
```

In v11 we will see that a new Item will be created with the `cancel.svg` icon, while in v12 the item will continue to be made with the default `item-bag.svg`

Currently in v12, I can get around this issue by using a wrapper function that targets `foundry.documents.BaseItem.getDefaultArtwork` directly with this exact same function.

### What core version are you reporting this for?

Version 12.324

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by JPMeehan** [comment]
Looks to be a side effect of `Document.schema` now making solely the base document responsible for schema creation.
