### ISSUE TITLE
TokenDocument#getTrackedAttributes is getting tracked attributes from ALL actor types, rather than only Actor type for the token

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11089]
### What happened?

In a system using TypeDataModel, when the token config window is opened, the list of resources for a bar attribute is presenting the fields across ALL Actor types, rather than only the Actor type for the token.

This means that a lot of invalid resources are being displayed, since some of the listed resources are for OTHER actor types, rather than the type of the token.

TokenDocument#getTrackedAttributes is iterating over all entries in game.model.Actor rather than getting only the entry for the Actor type for the token.

This is for a system that does not explicitly define `_getTrackedAttributesFromSchema`, so getTrackedAttributes is being passed data = "pc", which could be used instead of iterating across all entries in `game.model.Actor`

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open the Token Config window.
Go to the Resources tab.
Click on the drop-down list for Bar 1 Attribute.
See that the list contains resources from ALL actor types rather than only the type of the token's Actor.

### What core version are you reporting this for?

12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by farling42** [comment]
If data is a string, then it should attempt the code inside the loop only for the type whose name is in the string.

**Comment by JPMeehan** [comment]
The way TokenConfig and bars is setup in general is a total mess that feels like a holdover from the v9 DocumentData days.

**Comment by aaclayton** [comment]
I think "total mess" is an uncharitable categorization. We specifically implemented `_getTrackedAttributesFromSchema` as a specialized layer to do a good job with this task in cases where the Actor's system data is backed by a data model.
