### ISSUE TITLE
Big frame drops after opening any settings menu. Fixed when leaving a settings menu open and interacting with the canvas.

### ISSUE THREAD

**Issue by MightyMushka** [foundryvtt/foundryvtt#11082]
### What happened?

I'm experiencing big FPS drops after opening then closing any Foundry settings menu. This, however is fixed by opening a settings menu again and leaving it either open or minimized which seems to eliminate all stutter/FPS drops when doing things like move the canvas. As soon as the settings are closed, issues occur again.

This occurs with all modules disabled. It also occurs if the world is started in safe mode.

Video recording of the issue is here: https://youtu.be/SByjuOM2rOM

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Video of steps here: https://youtu.be/SByjuOM2rOM

Essentially: Open any foundry settings menu, then close for FPS drops to begin

### What core version are you reporting this for?

Version 11 Stable 315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by MightyMushka** [comment]
Interestingly, this does not appear to happen on a newly created world so seems to be something to do with my particular worlds data.

**Comment by MightyMushka** [comment]
So I've narrowed it down to my Playlist folder in the World folder. It was a mix of tracks imported from the Kingmaker module and from the Tabletop RPG (Streaming) module.

With nothing in the playlist folder, there's no FPS drops anymore. However, re-importing the Kingmaker playlist from the module (~350 tracks) results  a couple of FPS drop in the scenario above... as in, there isn't any drop until opening a settings menu, then when closed, very minor FPS drops with the current playlist.

Not sure if there is something funky happening regarding the playlist and the canvas after opening the menu?

**Comment by aaclayton** [comment]
Closing as nonrepro.
