### ISSUE TITLE
Unnecessary whitespace in dice formula causes problems for Peggy grammar parsing.

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#11099]
### What happened?

I'm starting to build a replacement Peggy grammar for a new system as the standard one is a bit limited.

My testing is starting to throw up some pretty basic flaws in the grammar as provided in V12.

For example, this is an easy one to demonstrate the problem.

```js
foundry.dice.RollGrammar.parse(' (2 / 3) / (4 * 5) ')
```
It works when you eliminate the excess spaces.

```js
foundry.dice.RollGrammar.parse('(2/3)/(4*5)')
```
A handy tip for writing parsers. Most grammar parsing has two phases - a lexical scan and then a parser scan. Peggy doesn't require a separate lexical scan, but that doesn't mean it's not a good thing to do. Get rid of the cruft before you start parsing and it's makes the grammar easier to write!

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Execute the commands from the console.

### What core version are you reporting this for?

Version 12 Build 325

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by esb** [comment]
Sorry, forgot to include actual error message -

```
Uncaught SyntaxError: Expected [+\-], [0-9], or whitespace but "(" found.
```

**Comment by aaclayton** [comment]
Thanks for the report. Please try to use clear issue titles which pertain to the problem being reported. In this case "needs some work" comes across as unnecessarily condescending. I'm sure that's not what you intended, just something to be mindful of.

**Comment by esb** [comment]
Point taken about the title.

A simple way to deal with this is to write a simple Finite State Machine to remove all whitespace, except for flavour tokens. It's about 40-50 lines and just stick it in parse just before the call to replaceFormulaData. Then remove all whitespace tokens from the grammar. You end up with a smaller generated peggy file.
