### ISSUE TITLE
Autofocus the first input field in the roll resolver application

### ISSUE THREAD

**Issue by tslays** [foundryvtt/foundryvtt#11092]
### User Experience

I really like the new manual roll function. But right now, everytime the dialogue pops up to enter the number I have to manually focus the field. Can we please auto-focus the field? So I click on roll, type my dice result, hit enter and get the dice roll resolved.

**Comment by aaclayton** [comment]
Yeah, autofocus on the first resolver input field would be a nice QOL touch.

**Comment by tslays** [comment]
Awesome, thanks! Could you also implement a function that we can switch all (!) dice to one mode with just one drop-down? We can use the other drop-downs for fine-tuning, but only if we select a custom mode. I would rarely roll my D6 manually while having my D20 on Foundry roll.
