### ISSUE TITLE
Switching to the Scene Controls of a non-PlaceablesLayer causes an error

### ISSUE THREAD

**Issue by jacobwojoski** [foundryvtt/foundryvtt#11107]
### What happened?

Creating a custom tool and having it get added to the scene controls (through getSceneControlButtons hook) doesn't properly work on initial load. 

Clicking the custom SceneControl button causes none of the SceneControlTools to get displayed and produces the following error:
![image](https://github.com/foundryvtt/foundryvtt/assets/124112219/054d57f9-e6d0-4cf0-b8db-ee8e1c434f27)

Changing scenes or selecting another SceneControl button fixes the issue. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Have a module that adds a custom scene control item. (Found when validating Dice Stats in v12)
Load any system and try selecting the new button.  

It looks to be trying to iterate a "placeables" array that may not always be populated depending on if the buttons get added to its own layer? 

### What core version are you reporting this for?

12

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
https://discord.com/channels/170995199584108546/1184176415139184731/1245985424338587658

**ALL MODULES DISABLED ?**: true
**Short Description of bug**: Menu added by the system in the sidebar doesn't work at first click (It was working in 12.324, but no more in 12.325)
**Simple steps to reproduce the bug**: Install Cthulhu Hack system and click on the Cthulhu Hack menu 
After the first click (not working), if I click on a Foundry menu then click on CH menu it's working

**Screenshots and/or console errors**:
