### ISSUE TITLE
Improve compendium API/ui for finding compendia

### ISSUE THREAD

**Issue by MaterialFoundry** [foundryvtt/foundryvtt#11103]
### User Experience

Right now, searching for a compendium by name is handled different from other documents. `game.packs.getName(name)` does not seem to work, instead I have to use `game.packs.find(p=>p.metadata.label == name)`.

Additionally, I'd like to see a 'Copy Document UUID' button at the top of each compendium.

**Comment by aaclayton** [comment]
Compendium packs are not documents.
