### ISSUE TITLE
`updateDocument` hook should mention that the token location may not yet be changed

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#11106]
### Where did you find it, or where does it belong for requests?

Code documentation comments (foundry.js)

### What core version are you reporting this for?

v12.325

### What is wrong, in your opinion?

In "hooks.msj", the documentation claims that the `document` parameter is, "The existing Document which was updated." Note past tense, as in, "this document has already been updated." The `changed` parameter similarly states, "Differential data that was used to update the document".

For `TokenDocument` in v12, this appears to no longer necessarily be the case. The documentation should note that token documents may not be fully updated at the time the hook is called, and identify which parameters may not be updated. (I believe it is at least `x` and `y`, but may also be `elevation` and other parameters (`rotation`, `width`, `height`?) related to token animation. From what I understand, the token may not yet have finished animation and so in v12, the `updateToken` hook is called before that process is finished. 

Presuming I am not misunderstanding or missing something, this is a pretty big change that may lead to a few bugs, as to date modules and systems would have expected that the `document` in the `updateDocument` always already reflects the changes identified in the `change` parameter.

**Comment by aaclayton** [comment]
I think this is probably a misunderstanding. The `TokenDocument` is fully updated before the `updateToken` hook is called. What *may not be fully updated* however is the rendered position of the `Token` placeable or the rendered attributes of the `PrimarySpriteMesh` that represents the token on the canvas. Those updates occur asynchronously on the next render call after the Token render flags have been set.

If you have reproducible steps that generate a non-updated `TokenDocument` at the time that the update hook is called please feel free to post them and we'll investigate as a bug. You can verify the intended design in `ClientDatabaseBackend##handleUpdateDocuments` and see that `doc.updateSource` occurs before `Hooks.callAll(...)`

**Comment by caewok** [comment]
See #11122
