### ISSUE TITLE
Add `HTMLDocumentTagsElement#_validateDocument` which allow s subclasses to impose custom validation logic

### ISSUE THREAD

**Issue by DJ4ddi** [foundryvtt/foundryvtt#11101]
### User Experience

The `HTMLDocumentTagsElement` introduced in v12 are a good way to streamline references that virtually every game system uses. There are a few minor things that I'd like to see for this element.

### Extended validation
The `HTMLStringTagsElement` exposes a `_validateTag` method that can be used to extend the validation. It would be great to have the same option for document tags as part of the `#add` workflow. The method could receive the `record` object as a parameter to perform custom validations.

**Use case**: In my system, we usually don't want to allow *any* item to be referenced by a field. Instead, we check the item's `type` and `system.group` in order to determine whether it can be used for this picker.

### Link items
It would be convenient if the tag elements would simultanously function as links to the referenced document. This could be done by simply replacing the `tag > span` elements with `tag > a.content-link` elements (the required information to construct the link is already there).

This can currently be achieved by overriding the `renderTag` method.

### Placeholder text
The current placeholder "uuid" seems a bit unclear. I think a more appropriate text would be a localization of "Enter UUID or drop {type}".

### Document replacement
Currently, an error message is emitted when adding a second document to an element with `single="true"`, I think the behavior that most users expect is that the existing item is replaced instead.

### Documentation
The documentation for the new elements is quite sparse at the moment (not limited to document tags). It would be helpful to have examples for:
- How to create the element from code.
- How to create the element with Handlebars.
- How to extend and register custom elements.

None of these are difficult, but I still had to read a significant amount of source code to understand the processes.

**Comment by aaclayton** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11286

**Comment by aaclayton** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11287

**Comment by aaclayton** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11288

**Comment by aaclayton** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11289
