### ISSUE TITLE
Allow active `HTMLProseMirrorEditor` instances to contribut e their current unsaved content to form submission events

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11110]
Originally reported by zhell9201 https://discord.com/channels/170995199584108546/1184176415139184731/1246087954426757201

**Short Description of bug**: Updated contents of a `<prose-mirror>` element is not included in form data.
**Simple steps to reproduce the bug**:

1) Create AppV2 form with a `<prose-mirror>` element (`[name="description"]`).
2) Update the contents of the element to be `<p>Steve.</p>` and save the editor via its own button.
3) This snippet has the updated contents: `new FormDataExtended(ui.activeWindow.element).object.description`.
4) Change the contents of the editor to be anything else (without using the editor save button).
5) Run the same code as in step (3).

**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/3e9103c3-2ca8-47b6-865f-cde7606e6a7f)

**Comment by aaclayton** [comment]
Note that this isn't really a bug but rather a feature request that `FormDataExtended` should retrieve the un-saved HTML from active `<prose-mirror>` elements as part of processing a form that contains them. It's an opinionated decision which merits some internal discussion before we act.
