### ISSUE TITLE
Implement an API for packages to provide Actor art mappings

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11125]
### Must Haves
1. A manifest field specification for packages to declare that they provide art for Actors in certain compendium packs.
2. Implement logic when loading the World to apply the art to the Actors in the specified compendium packs.
3. Implement a UI to allow users to configure the priority of their loaded art packs.
4. Implement a UI to allow users to configure whether to use mapped portrait artwork or token artwork.
5. Implement a UI to allow users to configure whether to apply dynamic token rings to mapped token artwork.

**Comment by JPMeehan** [comment]
Seems like it would make sense to build on the section of CONFIG carved out for UUID redirects.

**Comment by stwlam** [comment]
Should the "compendiumArtMappings" and "system-id" keys in the example be swapped, or does it being a manifest flag make for a different convention?

**Comment by Fyorl** [comment]
The `system-id` is the system that the art module is providing mappings for, so it could conceivably have several under the `compendiumArtMappings` field if it provides mappings for several systems.
