### ISSUE TITLE
`updateToken` hook provides a `document` that has not been fully updated

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#11122]
### What happened?

When moving a token, the `updateToken` hook will show `changes` to `x` or `y` that are not reflected in the `document` parameter. This is contrary to the documentation for that hook. This appears to be related to token animation. I have not attempted to confirm whether it is limited to the `x` and `y` properties.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

From the console, I add this hook:
```js
Hooks.once("updateToken", function(document, changed, options, userId) {
  if ( !(Object.hasOwn(changed, "x") || Object.hasOwn(changed, "y")) ) return;
  
  console.log(`Updated token ${document.name} ${document.id}`);
  console.log(`\tChanged: x: ${changed.x}, y: ${changed.y}`);
  console.log(`\tDocument: x: ${document.x}, y: ${document.y}`);
  console.log(`\tToken: x: ${document.object.x}, y: ${document.object.y}`);
})
```
Then I move the token one space, from x = 2000 to x = 2100. I get this back in the console:
```
Updated token Randal C5AAIP0zQrw2R6LA
VM1426:5     Changed: x: 2100, y: undefined
VM1426:6     Document: x: 2000, y: 1000
VM1426:7     Token: x: 2000, y: 1000 
```

### What core version are you reporting this for?

v12.325

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Very odd. Thanks for raising this. I'll investigate.

**Comment by dev7355608** [comment]
Pre V12 the token document was in its final state in `Token#_onUpdate`/`updateToken` until the first tick of the animation. With the animation framework changes in V12 that is no longer the case. Now the token document is put in the state that it would have at time 0 of the animation.

**Comment by aaclayton** [comment]
Closing as `wontfix` since this is an intentional change. `TokenDocument#_source` is updated but the derived (current visual position) of `TokenDocument#x` or `TokenDocument#y` may not be updated if the movement is being animated.
