### ISSUE TITLE
Consider firing region token events at the end of the token move animation

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#11123]
### User Experience

As far as I can tell the events are currently fired from `TokenDocument#preUpdateOperation` which means that they always fire before the animation is initiated.
For the e.g. teleport behavior that means dropping a token on a teleport region from farther away will instantly teleport the token to the target region instead of waiting for the move animation to finish.

**Comment by Norc** [comment]
There was some discussion that perhaps this could be limited to the Teleport Token behavior only in some way.

**Comment by stwlam** [comment]
Could it be available from the base class but disabled by default?

**Comment by dev7355608** [comment]
The behavior needs to await the movement animation if it needs to take some action after it completed. See `TeleportTokenRegionBehaviorType` or `DisplayScrollingTextRegionBehaviorType` for example.
