### ISSUE TITLE
Display user latency in the UI to help identify players who have a slow or unreliable connection

### ISSUE THREAD

**Issue by mawburn** [foundryvtt/foundryvtt#11132]
### User Experience

I took up the maintenance of the [user latency plugin](https://github.com/mawburn/foundry-user-latency) when it went unmaintained a couple of years ago and improved upon it by converting it to use WebSockets instead of fetch. Since then, I have not used Foundry as much, and most of my games are run IRL rather than online.

This feature **should** be built natively into Foundry and should be a low-effort addition. It can be a massive help when diagnosing player issues or letting others know that someone might be timing out. Foundry is much more like a video game than a web application, so a user's ping is a fairly important metric to have.

Right now, it is simply relying on the WebSocket endpoint for the system time, since this is a connection that is already established and will give a more accurate representation of a user's latency rather than a fetch call or Axios request. It's not actually using the time from the endpoint; it's simply measuring how long it takes to call the server and back. It was just a WebSocket endpoint that I found that I could use, and it is a rather hacky solution, in my opinion.

This is a pretty widely used feature, with the latest release being [installed about 6,000 times](https://tooomm.github.io/github-release-stats/?username=mawburn&repository=foundry-user-latency) times as of this ticket. But I'm sure more people would use as a native solution. Past versions had more downloads for some reason, I'm not really sure why but everyone who uses it finds it to be immensely useful. 

I will be archiving this repo and redirecting users here. It's a pretty low effort plugin, but I am just trying to reduce the amount of things on my plate in general.

**Comment by unsoluble** [comment]
Complete aside, but note that the download metrics there are for the _manifest_, which is grabbed every time someone checks for updates. The stats on the zip file are more indicative of actual installs. :)

**Comment by mawburn** [comment]
Fair enough. There is also caching like The Forge does as well. But I updated the ticket.

**Comment by DenizKose** [comment]
It'll be awesame to have this util in core foundry. This helpfull module help to understand who has problem with connection. So, I was dissapointed when understood that this module will not support v12 :...(

**Comment by Arthil11** [comment]
Mark me as another voice speaking up that this is added to Foundry itself, hopefully not having to wait until v13... or later.

**Comment by elemorelli** [comment]
I'd love to see this as a Foundry native feature.

Having players from other continent, it helped us too many times to diagnose conection issues during our games.

**Comment by SwedishRabbit** [comment]
It would be really good if this was native Foundry.

**Comment by aaclayton** [comment]
Issue is closed because it's coming in V13!

**Comment by DariusWolfe** [comment]
Unless I'm missing something, this does not completely replicate the functionality of the mod previously maintained by mawburn, as it does not seem to allow me, as the GM/Host to see the latency of connected players; it only allows the connected player to see their own latency.
