### ISSUE TITLE
TOC processed in wrong order with headings containing numbers

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11134]
### What happened?

If a journal page contains some subheadings which are numbers, and those same numbers appear as subheadings under more than one heading, then the TOC wrongly places some of the headings before the actual page's heading

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a journal page containing the following test, where the numbers have a style of "Heading 2"
```
one

2

two

3

three

4

four

2

five

3

six

4

seven
```

Observe that the TOC appears as follows:
![image](https://github.com/foundryvtt/foundryvtt/assets/17485384/1a526f02-3241-4ec8-ae88-ed237f13de4a)

---
It looks like _flattenTOC is upsetting the order of the fields when modifying the node.slug in addNode (where eventually it does Object.values, and **hopes** that the fields are in sort order).

### What core version are you reporting this for?

11.315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This has been improved in V12 via https://github.com/foundryvtt/foundryvtt/issues/10473
