### ISSUE TITLE
Curing data for an invalid embedded document is unexpectedly difficult

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#11133]
Suppose I have an invalid journal entry page. Here is what I expect I should be able to do:
```js
const j = game.journal.get(journalEntryId);
const p = j.pages.getInvalid(invalidPageId);
await p.update({"system.field.that.was.invalid": "corrected!"});
```
This does not work however, even if I pass `{diff: false}`. Somehow the update is being ignored.

What does work is to brute-force update the entire parent document's embedded array:
```js
const j = game.journal.get(journalEntryId);
const pages = foundry.utils.deepClone(j._source.pages);
const p = pages.find(p => p._id === invalidPageId);
p.system.field.that.was.invalid = "corrected!";
await j.update({pages}, {recursive: false});
```
I'm not sure why this brute-force solution is required but we should certainly try and ensure that a simple embedded document update is able to cure the invalid data.

**Comment by Fyorl** [comment]
Closing as nonrepro
