### ISSUE TITLE
Text drawings do not update text during preview or after clicking "Update Drawing." Refresh is required.

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#11146]
### What happened?

Text drawings do not update text during preview or even after clicking "Updrawing Drawing." A refresh is required to see the new text value.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a new drawing
2. Double-click it to edit it
3. Change the text value to "test"
- Expected: As you enter new text, the new text appears as a preview in the Drawing in the canvas
- Current: The new text value is not previewed in the canvas

4. Click Update drawing
- Expected: The new text appears as in the Drawing in the canvas
- Current: The new text value is not previewed in the map

5. Refresh the canvas

The new text value finally appears in the Text Drawing

### What core version are you reporting this for?

12.325, DND5E 3.2.0

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
https://github.com/foundryvtt/foundryvtt/assets/64667579/c4bafa4c-636c-407e-95ca-35f7cac3ccd9

Second half of this video demonstrates the delayed text update. Sorry that the actual entering of "test" and clicking "update drawing" took place outside capture area.

**Comment by dev7355608** [comment]
Originally reported by lyss_plyss: https://discord.com/channels/170995199584108546/1184176415139184731/1249633590950629397

**ALL MODULES DISABLED** True
**OS, HOSTING, BROWSER (IF APPLICABBLE)** Windows 10
**SHORT DESCRIPTION OF BUG** Drawing text tool does not work. I can write text in Square and Circle and update those, until I create a Text Box that I can't update those.
__EDIT: If you refresh the form reappears and so does the text.__
**SIMPLE STPS TO REPRODUCE THE BUG** Create a square/circle form, you can type and update text on those. Create a text box, you can't type text on it and you can't update text in your previous forms.
**SCREENSHOTS AND/OR CONSOLE ERRORS**

**Comment by dev7355608** [comment]
Originally reported by nonchalantwombat: https://discord.com/channels/170995199584108546/1184176415139184731/1249328262761545769

ALL MODULES DISABLED? TRUE
OS, Hosting, Browser (if applicable): Win 11, Self-hosted, Foundry Application
Short Description of bug: Creating a text drawing, it just disappears. Text does not update. After changing the label or selecting other tools, the drawing disappears.
Simple steps to reproduce the bug: Create a drawing object, edit it to add text, and it self-deletes or disappears.
Screenshots and/or console errors: No errors I can see, it just disappears?
