### ISSUE TITLE
Add support for configurable Token Ring color band positioning

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#11143]
### Implement support for configurable color band positioning according to predefined configurations. 

The default color band configuration should be used unless specific configurations are provided for certain ring types. Additionally, implement a static method to retrieve the appropriate color band configuration based on the ring name.

- Define a default color band configuration.
- Allow specific configurations for different types of rings.
- Implement a static method (getRingColorBand) that:
  - Checks if the provided ring name includes a specific key from the color band configurations.
  -  Returns the corresponding color band configuration if a match is found.
  - Falls back to the default configuration if no match is found.

**Comment by Drental** [comment]
This is very nice to see, but is there a way to tie the `startRadius` and `endRadius` to the spritesheet, just in case there are two modules defining the ring and one of them is *not* defining the bands (on account of the default working for them)

Or some other solution so that the band definition is tightly bound to the dynamic ring that won the config wars?

**Comment by Drental** [comment]
That sounds like it would solve the issue, yes.

**Comment by Drental** [comment]
Oh, a third thought enters my head today.

what is the maximum value for the band? Can I define 0 and 1.5 to make the complete square area be inside the band, or am I constrained to some upper or lower values?

**Comment by Feu-Secret** [comment]
> Oh, a third thought enters my head today.
> 
> what is the maximum value for the band? Can I define 0 and 1.5 to make the complete square area be inside the band, or am I constrained to some upper or lower values?

You can. But remember that the red channel of the ring is used for color replacement. So, if you put the whole ring viewport as the *radius*, you would replace the red channel of the whole ring with the ring color.
