### ISSUE TITLE
Consider improving the handling of incompatible packages

### ISSUE THREAD

**Issue by mooped** [foundryvtt/foundryvtt#11169]
### User Experience

Currently packages incompatible with the current Foundry version are simply hidden.

While I'm sure this was straightforward to implement it creates a lot of problems and confusion for users and by extension the system/module developers who have to field this confusion.

Hiding a package leads users to speculate about why the cannot see the result they expect and inevitably ask questions based on this speculation.

As an alternative, consider showing the package, but greying out the button to install it. Additionally, provide information to explain why it cannot be installed (incompatible, other relevant reasons). This saves the user wasting time trying to adjust their search terms and provides immediate clarity about why they are not seeing the result they expect.

In the long run this will save a lot of unnecessary questions and improve everyone's experience, especially during new version releases which have traditionally been very chaotic.

**Comment by aaclayton** [comment]
Are you talking specifically about the "Install Module" interface? Because modules that are already installed which are incompatible are not hidden.

**Comment by mooped** [comment]
> Are you talking specifically about the "Install Module" interface? Because modules that are already installed which are incompatible are not hidden.

Yes, this is about the Install Module interface. Sorry, I think that info got lost while rewording.

As per the above comment we've had a lot of new users come in due to the sale, buy premium content, and then wonder why they can't install it or the system to use it with.

One user explicitly asked if the system was paid too, which implies that they were somehow able to see the paid content, but not the system. Unfortunately I don't have further information to reproduce that case.

Fortunately because they're mostly new users there wasn't much of a penalty to them downgrading for a while, but it's still not a great introduction for them.
