### ISSUE TITLE
Include the module which produced the error when a module.json parsing error occurs.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#11164]
I have the `manifest`, `download`, and `url` fields of the manifests of my modules as `updatedByRelease`, specifically so an Update All doesn't actually grab a release version and overwrite my local dev version. That this produces errors is fine and expected.

But for cases where the error is not on purpose, the error message produced does not contain the module that caused it: ![](https://i.imgur.com/7EsOcCz.png)
ETA: (Chrome 125.0.6422.142/Windows 10)

Adding that would improve the debugging experience for legitimate problems.

**Comment by aaclayton** [comment]
The intended workflow here would be for you to mark your local dev module as locked so no updates are attempted for it.

**Comment by esheyw** [comment]
To summarize our conversation in discord:
- yes I am spacebar-heating here
- the issue is not about the spacebar-heating generating errors, that was just context for how and why I noticed that
- the error does not specify either the module or specific field that caused the error, which is bad for people who aren't spacebar-heating and don't necessarily know what module is throwing their errors

Atro, you seem to have re-tagged but not actually re-opened this.
