### ISSUE TITLE
Check for compatibility before doing manifest validation, on update checks in Setup

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#11188]
### What happened?

When you check for package updates in Setup, it seems as if a validation pass is done on the manifest for the newly available release before a check is made on its `compatibility` properties.

This will result in an error being thrown if the new manifest isn't v11-valid, instead of the expected messaging around the available release not being compatible:

![CleanShot 2024-06-12 at 09 12 17](https://github.com/foundryvtt/foundryvtt/assets/801582/f94b7352-b17e-4869-9dc9-4096109097ec)

Dunno how technically feasible it would be to check the compatibility state _before_ doing the validation, but something along those lines would be best here, or else we'll always be throwing errors instead of helpful messages when folks use newly-available manifest properties that are valid in the _next_ major relesae, but not this one.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Be in a v11 instance.
2. Have a module installed that has a v12-only release, and which also uses v12-valid-only manifest properties, like `documentTypes.RegionBehavior`.
3. Check for updates.
4. Expect to see a warning that this package has an update that is unavailable because it has a `compatibility.minimum` of `12`.
5. Instead see a validation error (attached above).

### What core version are you reporting this for?

11.315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Yeah, we need to load this remote manifest non-strictly so we tolerate errors until a point when we no longer can. We probably won't backport this change to v11 at this point, but we should push to get it into v12 so that we benefit from it during the v13 cycle.
