### ISSUE TITLE
Consider possibility of adding a check for available system drive storage space and notifying user if it is insufficient 

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#11187]
### User Experience

Many of the most common reports in Foundry troubleshooting recently are cases where there are intermittent canvas rendering issues due to Chromium not having sufficient cache space available (4GB). "Do you have at least 4GB storage space available on your system drive?" is almost as common a question as "Does it happen with all modules disabled?" With insufficient space, users encounter odd, intermittent canvas failures that have no obvious cause.

It occurred to me that we check for available storage space as part of our integrated backup functionality. If it was practical to do so, adding a check for available storage space when a client launches Foundry could be hugely beneficial. Perhaps throw an error if less than 4GB is available?

Something like:

> Foundry requires at least 4 GB of hard drive space to use for caching and only X GB is currently available. To prevent canvas rendering issues, please free up additional hard drive space.

**Comment by aaclayton** [comment]
We can only learn whether the *server host* has available storage space on their disk, we cannot learn how much space a client has available. The issue with chromium cache is a client side problem so this approach isn't really feasible.
