### ISSUE TITLE
Token Drag Measurement as a new approach to movement and measurement UX

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#11185]
## Poll Description
The Ruler in Foundry VTT today works by prompting you to measure first and then move along that measured path. This workflow has its advantages, but an alternative workflow that many users enjoy is one where distance is automatically measured as you drag your token. This feature would add an alternative measurement mode which works in this way. Both the current and this new measurement mode would be usable side-by-side according to your individual preference or method of interaction.

#### This feature will:
- Provide an alternative token movement mode where ruler measurement is performed automatically whenever you drag your token
- Add tools for GM users to perform secret measurements.

#### This feature might:
- Provide a more beautiful visualization of the ruler, using more advanced rendering options to make the measured distance easy to read but also more aesthetically pleasing.
- Be extendable, allowing modules and systems to provide custom data to the ruler to provide a visual distinction for different types of - movement at different distances, or based on limitations provided by the game rules.

-------------------------

## Requirements
- Implement a new UX for measuring while dragging a token
- Add tools for GM users to perform secret measurements that other clients do not see (#8675)
- Support a choice between measurement workflows and UX
- Support multiple simultaneous Ruler instances per client
- Allow rendering of measured segments to be more customizable, different colored segments, edges, etc...
- Improve larger tokens with a better visual presentation and more nuanced cost measurement
  - Related issue: #10147
- Enable a single Token update to provide a path of waypoints to animate
- Ensure that measurement history is aware of aborted or truncated movements (#10830)
- Improve the framework for locking a token so that only one measurement is occurring per token at a time
- Define a UX which prevents users from measuring outside of their explored area or receiving metadata that reveals information they should not have. How does it interact with Token Drag Vision?
  - Related issue: #10433
- Enforce (optionally) to measure from the center of a token instead of from another point.

## Stretch Goals
- Support a visualization of measurement history
- Pathfinding framework (#10148)
- Provide improved API methods for hit testing or range testing
- Add hover distance information as a convenient alternative to ruler measurement
- Enable using a ruler to measure movement for other types of placeables (like a measured template)

**Comment by JPMeehan** [comment]
This old issue seems related: https://github.com/foundryvtt/foundryvtt/issues/3315

**Comment by Rabulias** [comment]
I hope that the devs are able to look at incorporating waypoints with this. The current Ctrl-Left Click for the Ruler tool is clunky, but it works. Dragging a token while holding the left button would preclude this from working.

Personally, I find Drag Ruler's option setting a waypoint by Right-Clicking during dragging to work well, and I hope that finds it way into Core. Thanks for considering this.

**Comment by ThiefMaster** [comment]
> Add tools for GM users to perform secret measurements that other clients do not see

I hope this is a new permission? Restricting this to GMs does not make sense IMHO. Because as a player I may want to measure to plan for my next round of combat, but even if the GM does not intend to metagame, they will see my doing that measurement and subconsciously react to it when doing something with that token...

**Comment by aaclayton** [comment]
> I hope this is a new permission? Restricting this to GMs does not make sense IMHO. Because as a player I may want to measure to plan for my next round of combat, but even if the GM does not intend to metagame, they will see my doing that measurement and subconsciously react to it when doing something with that token...

We are currently leaning towards a keyboard modifier when starting your measurement rather than a permission, but the UX may evolve in response to feedback during the V13 testing cycle.

**Comment by Rabulias** [comment]
I also hope that the text displaying distance (either with the ruler or token movement) can be made to scale in relation to the zoom level. Trying to measure long distances across a large map when zoomed out is difficult to read, especially for those of us with older eyes!
