### ISSUE TITLE
Fix regression which prevented vertical scrolling for Scene Region shapes or behaviors tabs of the config sheet.

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/foundryvtt#11186]
### What happened?

I'm developing a module and wanted to use AppV2. I used the `RegionConfig` as an example and noticed a problem with scrollbars not showing up in mine but realized it also didn't work in `RegionConfig` either.

Create a new region and add a lot of Shapes and/or Behaviors to it. Instead of the Update Region button staying at the bottom and the list of shapes/behaviors being scrollable, the list just ends at the bottom of the window. Scrolling in that list isn't working. I'm not running on the latest v12 build, but I checked the release notes and didn't see any fixes related to this.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a new region. Then on the Behaviors tab, keep adding new behaviors (doesn't matter which ones) until the Update Region button at the bottom disappears since the behavior list doesn't scroll.

### What core version are you reporting this for?

12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This looks like an unfortunate regression - we did work during the Testing phase to ensure these tabs were scrollable.
