### ISSUE TITLE
Use an intermediate select element to validate and standardize multi-select innerHTML

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/foundryvtt#11193]
### What happened?

I'm using the new `<multi-select>` element to make something in AppV2 and running into an issue with `<optgroup>` elements in it. I'm using it to build a multi-selector of documents but wanted to include the folder structure in it to make it easier to use. So I looked into adding an `<optgroup>` to represent the folders. Everything is fine if they're just one level deep, but once there's a nested folder, that `<optgroup>` does not show up.

For comparison, I tried creating this as a normal, bog-standard `<select>` element and it worked. I could see the nested `<optgroup>` elements. I'd probably have to do some formatting to make them look like subfolders, but at least they showed up.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

To make it easier to see, I turned what I was doing into a macro. The top one is the `multi-select` and the bottom one is the normal `select`. Put the following into a script macro and run it. When you bring up the Multi Select, you'll only see the On Top, Between, and On Bottom options. I added those just so it wouldn't be nearly empty. But with the single select, you can see all the options.

```js
const content = `
<fieldset>
  <legend>Multi Select</legend>
  <div class="form-group">
    <div class="form-fields">
      <multi-select name="multi-select-test">
        <optgroup label="A House Divided">
          <option value="0a">On Top</option>
          <optgroup label="Characters of the Ruined Manor">
            <option value="1">Perrius Annmatar</option>
            <option value="2">Usk</option>
          </optgroup>
          <option value="0b">Between</option>
          <optgroup label="Creatures of the Ruined Manor">
            <option value="3">Arcane Wraith</option>
            <option value="4">Coat of Constricting</option>
          </optgroup>
          <option value="0c">On Bottom</option>
        </optgroup>
      </multi-select>
    </div>
  </div>
</fieldset>
<fieldset>
  <legend>Single Select</legend>
  <div class="form-group">
    <div class="form-fields">
      <select name="single-select-test">
        <optgroup label="A House Divided">
          <option value="0a">On Top</option>
          <optgroup label="Characters of the Ruined Manor">
            <option value="1">Perrius Annmatar</option>
            <option value="2">Usk</option>
          </optgroup>
          <option value="0b">Between</option>
          <optgroup label="Creatures of the Ruined Manor">
            <option value="3">Arcane Wraith</option>
            <option value="4">Coat of Constricting</option>
          </optgroup>
          <option value="0c">On Bottom</option>
        </optgroup>
      </select>
    </div>
  </div>
</fieldset>`;

foundry.applications.api.DialogV2.confirm({ content });
```

### What core version are you reporting this for?

12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by kaelad02** [comment]
Even though there's a macro, just realized some screenshots might help too:

![image](https://github.com/foundryvtt/foundryvtt/assets/19502084/599b4469-cc65-47b4-8293-c1d7cca40784)
![image](https://github.com/foundryvtt/foundryvtt/assets/19502084/76f13f4a-256c-4700-a3bc-117e0fd6779a)

**Comment by aaclayton** [comment]
Nested `<optgroups>` are not supported in the HTML spec. It looks like the `<select>` element is doing something internally to protect you from yourself by flattening all `<optgroup>` descendents into the top level of the HTML, but you will notice in your first example that when added to the DOM, your input HTML with nested optgroups becomes the following output HTML:
```html
<select name="single-select-test">
  <optgroup label="A House Divided">
    <option value="0a">On Top</option>
    </optgroup><optgroup label="Characters of the Ruined Manor">
      <option value="1">Perrius Annmatar</option>
      <option value="2">Usk</option>
    </optgroup>
    <option value="0b">Between</option>
    <optgroup label="Creatures of the Ruined Manor">
      <option value="3">Arcane Wraith</option>
      <option value="4">Coat of Constricting</option>
    </optgroup>
    <option value="0c">On Bottom</option>
</select>
```
The optgroup elements have been flattened.

I have made a change here to use an intermediate `<select>` element as a way to validate and standardize the `innerHTML` of the `<multi-select>` element. So any behavior or functionality that is supported by `<select>` should now also be supported by `<multi-select>`. But please note and be aware that your attempted use case of nested optgroups isn't supported the way you expected.

**Comment by Fyorl** [comment]
Marking this as wontfix as nested `<optgroup>`s are not valid HTML.
