### ISSUE TITLE
Add a button to roll on an embedded RollTable

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/foundryvtt#11201]
### User Experience

Foundry v12 added the new `@Embed` enricher that lets you embed a RollTable into something like a journal or other places (e.g. an item's description). It is a little inconvenient to roll on the table. You first have to click on the button at the bottom of the table to open the RollTable document, then roll from there. It would be nice if there was a roll button on the embed itself to make that quicker.

I'd propose adding a button with the same d20 icon that the deferred inline roll uses (e.g. `[/r 2d6]`). I did a quick mockup. Not sure if it's better to have the button/icon before or after the word Roll. Also, we can probably style it better to make it more obvious that it's actually a button you can click on as opposed to just some text.

![image](https://github.com/foundryvtt/foundryvtt/assets/19502084/18a636e5-50dc-4e5b-b494-6df38629e9d4)

**Comment by aaclayton** [comment]
Bonus points if we improve the embedded table display to visualize which options are currently locked and cannot be drawn.
