### ISSUE TITLE
Blind rolls are no longer evaluated interactively

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11208]
### User Experience

The basic idea would be an option that when set causes player-made blind rolls to revert back to normal digital roll fulfillment. It was briefly discussed during the development of the unfulfilled rolls feature and has also more recently been requested directly for the pf2e system.

https://github.com/foundryvtt/foundryvtt/issues/9775#issuecomment-1938810213
https://github.com/foundryvtt/pf2e/issues/15063

**Comment by aaclayton** [comment]
I understand the argument for why blind rolls might not support interactive fullfillment and instead require the default non-interactive method. I'll discuss with Kim and figure out where this belongs in prioritization order.
