### ISSUE TITLE
For `DialogV2` the inner `dialog-content` element should also have the `standard-form` class

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11213]
### User Experience

I expected to be able to assign the `standard-form` class somewhere in `DialogV2` to get some of the default styling, but it was not the case, since the wrapping `div.dialog-content` element works against that. Perhaps this element could simply inherit from `options.window.contentClasses`?

This is of course extremely minor but if `DialogV2` had an option to add a css class to that element (or if the element did not exist and its children were just in the parent `<form>` element), it would have been the difference between these two dialogs.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/1d6577df-ca96-4ba8-8b99-8b650b0c1f45)
![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/3abdbfb7-56fa-4b67-bfbb-5aefb16fc488)

The workaround is to add yet another wrapping element with the `.standard-form` class.

**Comment by aaclayton** [comment]
I agree that `.dialog-content` should also have the `.standard-form` class
