### ISSUE TITLE
Module Primitives documentation is missing in V12

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#11216]
### Where did you find it, or where does it belong for requests?

Other foundryvtt.com site page (not package listings)

### What core version are you reporting this for?

Version 12 Build 325

### What is wrong, in your opinion?

The documentation exists for V11 at

```
https://foundryvtt.com/api/v11/modules/primitives.html
```

This does not seem to exist for V12.

**Comment by JPMeehan** [comment]
I've also got a post on Website Feedback for this issue: https://discord.com/channels/170995199584108546/1247940352040632451
