### ISSUE TITLE
Lighting Controls: Luminosity should be able to have negative values to achieve creative animation and blending effects

### ISSUE THREAD

**Issue by OrangejuiceNinja** [foundryvtt/foundryvtt#11215]
### Feature Request:
1. **Enable Luminosity values between -1 and 1 when "Is Darkness Source" is deactivated**

In previous Foundry versions it was possible to set Lights > Advanced Options > Luminosity values between -1 and 1 for light sources. In v.12  values may only be set between 0 and 1. This removes extremely versatile functionality in Foundry and the "Is Darkness Source" option is of very limited use in comparison.

The light effects previously made available through mixing Coloration Techniques and Light Animation Types together with the parameters found under Advanced Options could easily be made to resemble dark clouds, rivers of ink, fire, smoke, fog and other interesting effects. Especially when used creatively with **negative luminosity values.** 

_See video example below:_

https://github.com/foundryvtt/foundryvtt/assets/93767107/f0ae9dde-10a8-4607-b47f-538deda969db

**Comment by aaclayton** [comment]
The expected workflow here is to use darkness level to darken the scene and then to brighten in areas where illumination is desired. Purely aesthetic darkness can be accomplished with scene regions but that’s the only tool we have (or will have) in v12.

I’m confident that increasing darkness level and then adding in some lights will produce an almost identical effect to what you had before.
