### ISSUE TITLE
ApplicationV2 header controls dropdown styling issues

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11229]
# Implemented Change

### Light Mode
![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/99372611-fe5d-4ac7-9952-0c5f4e3e9c6d)

### Dark Mode
![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/1712dd14-716b-4677-951c-1c021249822a)

# Original Issue
https://discord.com/channels/170995199584108546/1184176415139184731/1251267228083687576

**ALL MODULES DISABLED? **true
**OS, Hosting, Browser (if applicable): **Electron
**Short Description of bug: **Toggle Controls dropdown is transparent, and css animation looks quirky 
**Simple steps to reproduce the bug: ** 
Use basic (boilerplate) unmodified system with ApplicationV2. No system css is used in the menu.controls-dropdown or li.header-control. Also validated the issue with an empty system css to be sure.
See screencapture:

[applicationV2-controls-dropdown.webm](https://github.com/foundryvtt/foundryvtt/assets/31905376/15511d1d-cb66-4afd-a97b-ec7455322b9f)

**Comment by yjeroen** [comment]
Retested with build 328, still an issue.

![image](https://github.com/foundryvtt/foundryvtt/assets/1303988/1cdb04fc-ed8c-4e63-9833-4870221a00f1)
