### ISSUE TITLE
Implement dynamic ring clipping based on rectangular distance instead of euclidean distance

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#11237]
### What happened?

using this expertly made dynamic test Token Ring, I noticed that the blue parts in the corners are getting cut off entirely, leaving only the blue ring as the area to draw the token ring in, since everything in the green area is reserved for the subject and background, while everything outside the blue ring just disappears. This hits both the Background and the Ring texture

Can you allow the Dynamic Token Ring to use the area in the corners as well, or is this intentionally forbidden? I can see that it makes turning the token smoother, but most pog style tokens aren't made for turning in the first place.

![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/a6ebe2fc-18e3-4992-ad63-c7dae3be8ad8)

![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/37f2dfe9-fc9a-44aa-8d95-17bedbd1dbbd)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I can pass a minimal module with the reproduction to you if you need me to, but it should be easy to reproduce with a quick and dirty edit fo the default dynamic ring too.

System used: PF2e (to make sure that the ddn5e special handling does not interfere)

### What core version are you reporting this for?

12.327

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Drental** [comment]
ONe more thing, when using a larger ring and adjusting the subject scale to 0.8 (or anything below 1) this happens:

![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/5ec75cc0-7366-4752-953f-dcd34c5bd7a7)

parts of the background and ring that go beyond the square of the token get cut off agressively

**Comment by Feu-Secret** [comment]
> Hey @Drental - the first issue you raise is probably a bug. I would expect the ring to render anywhere within the quad geometry. @Feu-Secret is that correct?
> 
> The second issue about rescaling the ring to a point where it clips is an expected limitation.

This is not a bug, but a limitation. We need to clip a texture coming from a sprite sheet. Clipping by using distance from center of the ring is the cheapest way to achieve it. If we want to clip using the frame, we need extra information into the shader. The batched shader is already full of information, adding frames for both the ring and the background is not feasible.

**Comment by Drental** [comment]
stupid worry, but just to be sure - this doesn't change how the dynamic band is used, right?

**Comment by Feu-Secret** [comment]
> stupid worry, but just to be sure - this doesn't change how the dynamic band is used, right?

Absolutely not. The operation of the dynamic bands remains unchanged. The modifications are only made to the clipping region of the ring, which is now a rectangle instead of a circle. It will therefore be possible to use assets for the dynamic ring that are not just rings, allowing for greater artistic flexibility.

**Comment by Drental** [comment]
Perfect, just needed to be sure 👍 <3
