### ISSUE TITLE
`Combat#_onEndRound` and `Combat#_onEndTurn` are called at the beginning of combat

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11238]
## Implemented changes

- `Combat#_onEndRound` is no longer called for round 0.
- Fixed `Combat#turn` is being set to 0 instead of null if the `round` becomes 0. This fixes the case where `Combat#_onEndTurn` was called in round 0.
- Fixed `Combat#resetAll` setting the `turn` to 0 instead of null if the combat wasn't started yet. This fixes another case where `Combat#_onEndTurn` was called in round 0.

## Original issue

Originally reported by zhell9201: https://discord.com/channels/170995199584108546/1184176415139184731/1252376209757573160

**Short Description of bug**: The `tokenRoundEnd` region event is triggered when combat starts.
**Simple steps to reproduce the bug**: Place token in region. Give region `tokenRoundEnd` event. Create combat with token in it. Click 'Being combat'.

**Short Description of bug**: The `tokenTurnEnd` region event is triggered when combat starts.
**Simple steps to reproduce the bug**: Place token in region. Give region just all of the events. Create combat with token in it. Click 'Being combat'. Then click 'Previous Round' such that combat is no longer started. Then click 'Begin Combat'.

**Comment by krbz999** [comment]
I think most would not consider the "round" before combat even begins to be an actual round, and as such would not consider any turn or round to be ending when starting combat.

I mean, if combat has not started, then no turns or rounds have ended yet, isn't that logical? It seemed like a glaring bug to me, and I had a few agreeing before posting.

Note this is only about these two specific events, not any turn-start or round-start events.

**Comment by krbz999** [comment]
Is "end of round" meant to be used as an "at the top of the round" event when "start of round" also exists?

**Comment by aaclayton** [comment]
There should be both an `_onEndRound` and an `onStartRound` event that occurs when combat is begun. This is what happens when a combat is started:

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/991307e4-3f1a-4772-9148-4d1136f7a8f1)

The following events occur in order:

1. `_onEndRound` for round `0`
2. `_onStartRound` for round `1`
3. _onStartTurn` for the first combatant in turn order

**Comment by stwlam** [comment]
If for any `_onStartRound` there is also an `_onEndRound` called immediately prior, what is the point of having them as separate events rather than a single hypothetical `_onChangeRound` one? Is the value of them being separate not precisely that one might be interested in an `_onStartRound` that doesn't follow an `_onEndRound`?

**Comment by JPMeehan** [comment]
I agree this seems like a bug to me. While it may be the end of the 0th round from a programming perspective, that doesn't make any game sense.

**Comment by FloRad** [comment]
> The concept of ` round: 0` is used to denote the process of setting up the combat and advancing to round 1 should trigger events like "round start". Some effects that happen "every round of combat" do happen on the first round.

By that logic, shouldn't a round start event be fired when combat is created, since it technically enters `round:0`?

**Comment by Aliharu** [comment]
If _onEndRound occurs during combat start how are you supposed to properly implement trigger events that activate at the "End of Round"?

This would mean implementing any End of Round effect requires you specifically make sure it does not trigger on "Round 0" in pretty much all cases.

The whole reason a rules system would say "End of Round" and not "Start of Round" for a mechanic is specifically so it does not trigger when combat starts.

**Comment by dev7355608** [comment]
We reevaluated this issue and came to the decision to not call `Combat#_onEndRound` for round 0.
