### ISSUE TITLE
Implementation of external API for eg. app development

### ISSUE THREAD

**Issue by ZeroXNoxus** [foundryvtt/foundryvtt#11239]
### User Experience

A friend of mine and I currently work on a mobile character sheet module that could develop into a mobile app and we were wondering if an externally called API could be implemented to get the game data without loading the foundry instance?

Would be a highly appreciated feature!

**Comment by aaclayton** [comment]
Hello @ZeroXNoxus, thanks for submitting this request. It's something that has been asked a few times but we are confident in our choice to only offer a JavaScript API internal to Foundry Virtual Tabletop rather than an external HTTP (or other protocol) API at this time.
