### ISSUE TITLE
Add an optional slug property to the `HTMLStringTagsElement` which automatically converts input strings to slugs

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11248]
### Using HTML
```html
<string-tags name="string.tags.field" value="['foo', 'bar']" slug></string-tags>
```

### Using JavaScript
```js
HTMLStringTagsElement.create({
  name: "string.tags.field"
  value: ["foo", "bar"],
  slug: true
}
```

## Original Request

Using this field for tags, there's often no meaningful difference between "Steve", "STEVE", "steve", and "sTevE. It would be nice to be able to have a property that automatically slugifies the tags in this html element when added.

**Comment by krbz999** [comment]
Can this not be used with `{{formGroup}}`?

**Comment by aaclayton** [comment]
It should, but I did not test it. Share an example of the syntax you are trying?

**Comment by krbz999** [comment]
```js
const m = new foundry.data.fields.SetField(new foundry.data.fields.StringField());
const template = "{{formGroup field slug=true}}";
Handlebars.compile(template)({field: m});
```
Not seeing the element's attribute actually being set anywhere in the code either. It does call `hasAttribute` but never `setAttribute`.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/6010358c-72cb-4894-b9b2-62163e114151)
