### ISSUE TITLE
(#10948 reopened) Full Text Search does not work: DocumentCollection.getSearchableFields returns incorrect field paths

### ISSUE THREAD

**Issue by admiralnlson** [foundryvtt/foundryvtt#11258]
### What happened?

The issue described in #10948 is still very much present.

No noticeable difference in v12.327.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See #10948

### What core version are you reporting this for?

12.327

### Relevant log output

```shell
See #10948
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
#10948 wasn't part of 12.327. It's going to be fixed with the upcoming release.

**Comment by admiralnlson** [comment]
@dev7355608 sorry about that.
I can confirm it works again in 12.328 (and better even thanks to your #11198), thanks!
