### ISSUE TITLE
In `Ruler`, separate `_addWaypoint` from doing the measurement

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#11274]
### User Experience

To facilitate modules or systems that would like to track additional information, it would be preferable if the ruler measurement was not triggered in `Ruler#_addWaypoint` and `Ruler#_removeWaypoint`. 

Currently, you cannot add properties to a waypoint prior to the call to `_addWaypoint` because the waypoint has not yet been created. But you cannot wait until after `_addWaypoint` because `measure` is called before you have a chance to do so. There is a good chance that if you are adding properties to a waypoint, it is relevant to the next measurement. 

Further, it is a bit unexpected to have `_addWaypoint` trigger a measurement. Adding/deleting waypoints and triggering the ruler measure are two distinct actions. 

This simplified `_addWaypoint` and `_removeWaypoint` into something like:
```js
  /**
   * Handle the addition of a new waypoint in the Ruler measurement path
   * @param {Point} point                    The waypoint
   * @param {object} [options]               Additional options
   * @param {boolean} [options.snap=true]    Snap the waypoint?
   * @protected
   */
  _addWaypoint(point, {snap=true}={}) {
    if ( (this.state !== Ruler.STATES.STARTING) && (this.state !== Ruler.STATES.MEASURING ) ) return;
    const waypoint = this.state === Ruler.STATES.STARTING
      ? this._getMeasurementOrigin(point, {snap})
      : this._getMeasurementDestination(point, {snap});
    this.waypoints.push(waypoint);
    // Parent caller should determine if the ruler state is now measuring 
    // and whether to measure.
  }

  /* -------------------------------------------- */

  /**
   * Handle the removal of a waypoint in the Ruler measurement path
   * @protected
   */
  _removeWaypoint() {
    // Because the waypoints should always 
    // have the origin waypoint, test for waypoint length here.
    if ( waypoints.length < 2 ) return; 
    // Not clear why ruler state matters but could be tested if you want.
    this.waypoints.pop;
    // Parent caller should determine if the measurement has ended or 
    // call measure as necessary.
  }

```

**Comment by dev7355608** [comment]
Closing. The Ruler class changed significantly in V13 Prototype 1. In particular, `Ruler#_addWaypoint` and `Ruler#_removeWaypoint` don't exist anymore.
