### ISSUE TITLE
Support malformed zips produced by Windows' built-in archiver

### ISSUE THREAD

**Issue by gotenxds** [foundryvtt/foundryvtt#11276]
### What happened?

Hi, I'm trying to make my module that works on v11 on v12, it is a very simple module that only has packs (compendiums) in it, but it fails to install on v12.
It is not a large module so unrelated to other issues here (60mb~)

From looking at the error and delving into foundries code a bit, there see to be some issue unzipping the module file, as it is unable to extract and create a folder.
When looking at the resulting folder it is malformed and not fully unzipped.

The same link works on v11
It is a clean installation of v12 - no extra modules installed
When unzipping manually the module works fine.
Here is a link to the manifest you can try yourself https://annomicon.onrender.com/free-module.json

Here is the error 
![image](https://github.com/foundryvtt/foundryvtt/assets/3519520/7865594b-2c2a-4233-afae-8e4c893c7e5f)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open up foundry on version 12 build 327 (might happen on older builds of version 12 too)
go to modules and install the module via direct manifest link

https://annomicon.onrender.com/free-module.json

Another mirror in case the link above does not work for some reason: 
https://www.dropbox.com/scl/fi/1t7rxlk8ql6fsc1a37pbx/free-module.json?rlkey=asziyia0sgajbylkmq14plc3y&dl=1

The module should download but then not install, looking at the dev tools should show the error above

### What core version are you reporting this for?

12 - 327

### Relevant log output

```shell
setup.js:2080 Error: ENOTDIR: not a directory, mkdir 'C:\Users\David\AppData\Local\FoundryVTT\Data\modules\annomicon-free\assets\images\creatures_vol_01'
    at mkdirSync (node:fs:1379:3)
    at t.mkdirSync (node:electron/js2c/node_init:2:12926)
    at Files._extractEntry (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/files/files.mjs:1:3038)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/files/files.mjs:1:2658
    at Files.processArchive (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/files/files.mjs:1:2417)
    at async PackageInstaller.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/packages/installer.mjs:1:1416)
    at async #s (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/packages/package.mjs:1:9166)
    at async Module.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/packages/package.mjs:1:7894)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletopv11/resources/app/dist/packages/views.mjs:1:3245
```
```


### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by anathemamask** [comment]
Hi there,

In doing preliminary research on this issue before reaching out to suggest you email us about it, I took a look on our community discord and found your post regarding use of a powershell command to zip your module files.

That is absolutely the problem here.

There is a longstanding powershell bug that keeps getting filed as fixed but doesn't actually get fixed related to use of Compress-Archive.

This will be resolved if you use a normal program for creating your zips instead.

Cheers,
Anathema

**Comment by gotenxds** [comment]
Hi @anathemamask as discussed in the discord, this also reproduces by just using windows archiver, that is, right clicking some files, and pressing the Compress to zip file.

On my end I changed the zipping process and it now works, if you wish to close this issue that's fine, just reported it because it is a breaking issue (worked fine in v10 and v11) and that using windows archiver is probably a pretty common practice that foundry might want to support.
