### ISSUE TITLE
Dynamic Token Ring uses incorrect asset size class in PF2e

### ISSUE THREAD

**Issue by Dorako** [foundryvtt/foundryvtt#11282]
### What happened?

I've replaced the default rings.webp with a modified version, which recolors the background for each size class.
<img width="812" alt="image" src="https://github.com/foundryvtt/foundryvtt/assets/1561190/dce935e3-4e20-479a-9b7d-ec35d744169f">
I then created PF2e NPC's using each size class.
<img width="860" alt="image" src="https://github.com/foundryvtt/foundryvtt/assets/1561190/ec0415e6-5925-455a-b64b-9622743f3fbd">
Note that Tiny, Small, and Medium all share the smallest asset background, and the largest token uses the second-largest asset background.
This also makes small and medium token rings/background very blurry, since they're using an asset designed to fit creatures 1/4th the size.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Tested using most recent FVTT and PF2e
![CleanShot 2024-06-26 at 20 01 26@2x](https://github.com/foundryvtt/foundryvtt/assets/1561190/226c68b9-bdf8-4742-a7ab-ce0855b19868)

### What core version are you reporting this for?

v12.327

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We have added some new metadata to the ring JSON which will go out in the next v12 update and will fix this problem to ensure that the ring size used is based on the creature size rather than their rendered size. @Feu-Secret confirm what I've said is correct and if so we can close this issue as a duplicate?

**Comment by Feu-Secret** [comment]
I confirm you can now target a grid size for a specific ring. Your problem is fixed in the most recent Foundry version.
```json
"token-ring-tiny":
{
	"frame": {"x":3328,"y":2048,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256},
	"anchor": {"x":0.5,"y":0.5},
	"gridTarget": 0.5
}
````
