### ISSUE TITLE
Some CONFIG[docType].typeLabels are initialized by i18n rather than as part of loading ESM

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11297]
A number of `typeLabels` in CONFIG are initialized as empty objects by `Localization#initialize` rather than being just part of CONFIG in normal ESM loading. This is inconsistent and can cause problems for packages attempting to interact with the existence of these properties in the `init` hook. It's currently only present on `Actor`, `Item`, `Cards`, and `JournalEntryPage`, but is initialized for *every* document type. Many of these are of course not very useful (e.g. ActorDelta) but the handling should be consistent across document types.

**Comment by aaclayton** [comment]
Can you please share a little bit more information like what happens as a result of this issue, or the best way to reproduce that problem? I have not looked into this personally yet but just from reading the issue I'm not clear what the problem is or where it manifests.

**Comment by JPMeehan** [comment]
It's a consistency thing. If you access `CONFIG[docType].typeLabels` prior to i18nInit, it's inconsistent whether you get `{}` or `undefined`
![image](https://github.com/foundryvtt/foundryvtt/assets/16617088/eae76bfe-3415-45ca-b09e-9881861b576e)

It's fair to mark this as low prio, but it is weird and should see adjustments in either direction.

**Comment by JPMeehan** [comment]
Addendum: I'm realizing the original post was me checking v11, I thought I had my v12 install open. So it *is* marked correctly as `{}` for anything that has a proper type field, and the `undefined` is for anything without a `type` field

**Comment by aaclayton** [comment]
`typeLabels` is undefined for a document like `Macro` because it cannot have package-defined types.
