### ISSUE TITLE
The `.application nav.tabs .item` style makes the tab labels difficult to see in "light mode"

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11290]
### User Experience

There are 5 tabs in this picture.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/3b2c2e00-3238-4305-88c1-3507272f9c87)

**Comment by stwlam** [comment]
This particular `.item` selector was incidentally imported under `.application`, but it remains as a legacy selector for V1 applications. Reference core V2 applications with tabs such as `RegionConfig` for intended tab styling (note especially the lack of any class whatsoever for the tabs).
