### ISSUE TITLE
Add setting to control where Region Legend appears when switching to Region layer

### ISSUE THREAD

**Issue by git-steve-git** [foundryvtt/foundryvtt#11307]
### User Experience

When I switch to the Region layer in normal usage, the Region Legend appears directly on top of the left-hand control buttons; in particular it covers the Actors button, which is by far the most common one I'd want to switch back to.  This makes it a pain to _leave_ the Region layer when I'm done, as I have to move the Legend first, every time.

As the Legend gets longer with actual regions created, it blocks more and more of the left-hand buttons.

**Solution:**
- Add a Core setting to choose where that Legend should appear (top left, top right, bottom left, bottom right.)  Maybe other options.
- Ideally have the Region Legend panel remember where it was the last time I was on Region layer, so it will effectively stay where I put it last.

**Comment by krbz999** [comment]
It starts here, where it doesn't cover any other control buttons. Though it *would* be nice if it remembered its previous position.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/0416fea6-81a9-4ce9-ad55-c8aadc5cc883)

**Comment by git-steve-git** [comment]
On my install it fully covers the buttons with the left edge against the
left edge of the window.  Maybe it's a plug causing trouble though,I'll
check and report back.

**Comment by stwlam** [comment]
Unable to reproduce covering of control tools without simulating an extremely large number of ones added by modules, but the legend application will now remember where it was manually repositioned.
