### ISSUE TITLE
Create Macro and Create Folder buttons are missing from the Macro Directory

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11304]
Originally reported by frosty5687: https://discord.com/channels/170995199584108546/1184176415139184731/1256264482456469515

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable)**: Windows 11, Self-hosted, Electron app & Chrome
**Short Description of bug**: Create Macro and Create Folder buttons not available in Macro Directory
**Simple steps to reproduce the bug**: Create a new world in 12.328 with any game system. Log in as GM. Open the Macro Directory. The buttons are not available
**Screenshots and/or console errors**:

---

Underlying bug: `Macro.canUserCreate` returns always false, because it calls `hasPermission` instead of `hasRole`.

**Comment by dev7355608** [comment]
Originally reported by abominablerob: https://discord.com/channels/170995199584108546/1184176415139184731/1261132933163651104

All modules disabled: all but 1 (needed for bug)
OS: Windows, self-hosting, v12 328
Description: Macro Compendiums - right clicking on macro provides no import option, only delete. Tried with only one module (+libwrapper) active, happens for all modules
Steps to recreate: activate a module, open macro compendium, right click on a macro
No console errors

**Comment by YenBenGrey** [comment]
I am experiencing this problem too. I am on  a MAC, that is the only difference. 

Cannot create new folders or sub-folders in Macros Directory.
