### ISSUE TITLE
deleteAll disapeared in hooks option

### ISSUE THREAD

**Issue by jdeon** [foundryvtt/foundryvtt#11310]
### What happened?

I have a module that protect some chat message from being deleted by flush chat button. 
Since v12, deleteAll boolean is not present anymore in the option of the hook preDeleteChatMessage and deleteChatMessage.
So there is no way to know if it is a single delete or a flush.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

It's an api bug.
You need to `Hooks.on("deleteChatMessage", (chatMessage, option) => console.log(option.deleteAll )` same for preDeleteChatMessage hook.

### What core version are you reporting this for?

V 12.328

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm sorry, but this was an intentional change to prevent hooks from being able to tamper with the value of `deleteAll`. You will have to find an alternative path forward for your module.
