### ISSUE TITLE
Convert Hotbar to ApplicationV2

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11356]
## Potential Related Issues
- #11300 
- #11114 
- #10676 
- #10642 (also #8344)
- #9674
- #9346
- #8591
- #8344

**Comment by anathemamask** [comment]
Related issues worthy of consideration:
#11300 
#11114 
#10676 
#10642 (also #8344)
#9674
#9346
#8591
#8344
#5890 (i'm not sure this is still the case)
