### ISSUE TITLE
Convert JournalTextPageSheet to ApplicationV2

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11365]
## Related Issues
- https://github.com/foundryvtt/foundryvtt/issues/11664

**Comment by anathemamask** [comment]
Related issues worthy of consideration:
#4406
#10543
#10383
#10309
#9753
#9186
#9155

**Comment by Fyorl** [comment]
Initial conversion is complete with some related issues still under consideration. The new sheets are available under:
- `foundry.applications.sheets.journal.JournalEntryPageSheet`
- `foundry.applications.sheets.journal.JournalEntryPageTextSheet`
- `foundry.applications.sheets.journal.JournalEntryPageProseMirrorSheet`
