### ISSUE TITLE
Convert Sidebar to ApplicationV2

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11391]

**Comment by anathemamask** [comment]
Overarching issues related to redesign of sidebar:
#3579 (possible heavy lift)

#7048 
#6638
#5836


Related issues worthy of consideration:
#5828
#4600

**Comment by OmegaRogue** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11541

**Comment by Fyorl** [comment]
### Notes for V13 Prototype 1
 - The new `Sidebar` application is available under `foundry.applications.sidebar.Sidebar`. Accessing the old global `Sidebar` will trigger a deprecation warning.
 - The App V2 implementation of `SidebarTab` is now called `AbstractSidebarTab`. The old `SidebarTab` remains while we continue the process of migrating sidebar tabs to App V2.
 - The public API for `Sidebar` has been retained. If some part of the previous public API surface is missing, it should be logged.
 - The `collapseSidebar` and `changeSidebarTab` hooks have been retained. The first parameter passed to `changeSidebarTab` may be either a `SidebarTab` or `AbstractSidebarTab` instance, depending on the tab in question. In the future this will only return `AbstractSidebarTab`s.
 - `Sidebar#activateTab` was part of the App V1 interface and has been deprecated in favour of `SidebarTab#changeTab`.

### Breaking Changes
 - The HTML structure of the sidebar pane has changed.
 - As `Sidebar` is now an App V2 application, its associated `renderSidebar` hook now returns an `ApplicationV2` instance and an `HTMLElement` as its first and second parameters, respectively.
