### ISSUE TITLE
Register a rendered `AppV2` instance immediately before its element is inserted on first render

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11407]
### User Experience

When using a custom element in an AppV2 application, it would be nice to easily get access to the application itself. What I would like to be able to do is the following:
```js
connectedCallback() {
  const id = this.closest(".application").id;
  const sheet = foundry.applications.instances.get(id);
  // ...
}
```
From which I can access the application's `document` and all the other good stuff. This however fails on the first render (not subsequent renders) since the application is registered immediately after its element is inserted:
```js
// Update Application frame and position
if ( options.isFirstRender ) this._insertElement(this.#element); // <-- connectedCallback is called here
if ( this.hasFrame ) this._updateFrame(options);

// Register successful render
this.#state = states.RENDERED;
foundry.applications.instances.set(this.#id, this);
```

If the last line here was moved up above the `this._insertElement` line, callbacks would have access to the application directly.

**Comment by aaclayton** [comment]
Reasonable request - I will consider whether this can be squeezed in a V12 stable patch or whether it needs to wait for v13.
