### ISSUE TITLE
Electron and Dependency updates for V13 Prototype 1

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#11403]
| Package                         | Current | Wanted  | Latest  |
|---------------------------------|---------|---------|---------|
| @aws-sdk/client-s3              | 3.577.0 | 3.670.0 | 3.670.0 |
| @aws-sdk/client-secrets-manager | 3.580.0 | 3.670.0 | 3.670.0 |
| @aws-sdk/s3-request-presigner   | 3.577.0 | 3.670.0 | 3.670.0 |
| @rollup/plugin-node-resolve     | 15.2.3  | 15.3.0  | 15.3.0  |
| abstract-level                  | 1.0.4   | 1.0.4   | 2.0.0   |
| archiver                        | 6.0.2   | 6.0.2   | 7.0.1   |
| chokidar                        | 3.6.0   | 3.6.0   | 4.0.1   |
| cookie                          | 0.6.0   | 0.6.0   | 0.7.2   |
| electron                        | 31.1.0  | 32.2.0  | 33.0.0  |
| electron-builder                | 24.13.3 | 24.13.3 | 25.1.7  |
| eslint                          | 8.57.0  | 8.57.1  | 9.12.0  |
| eslint-plugin-jsdoc             | 48.5.0  | 48.11.0 | 50.3.1  |
| express                         | 4.19.2  | 4.21.0  | 4.21.0  |
| express-fileupload              | 1.5.0   | 1.5.1   | 1.5.1   |
| express-handlebars              | 7.1.3   | 7.1.3   | 8.0.1   |
| gulp                            | 4.0.2   | 4.0.2   | 5.0.0   |
| jsdom                           | 24.1.0  | 24.1.3  | 25.0.1  |
| memfs                           | 4.9.3   | 4.13.0  | 4.13.0  |
| npm                             | 10.8.1  | 10.9.0  | 10.9.0  |
| peggy                           | 4.0.3   | 4.1.1   | 4.1.1   |
| prosemirror-commands            | 1.5.2   | 1.6.0   | 1.6.0   |
| prosemirror-history             | 1.4.0   | 1.4.1   | 1.4.1   |
| prosemirror-model               | 1.21.3  | 1.23.0  | 1.23.0  |
| prosemirror-schema-list         | 1.4.0   | 1.4.1   | 1.4.1   |
| prosemirror-tables              | 1.3.7   | 1.5.0   | 1.5.0   |
| prosemirror-transform           | 1.9.0   | 1.10.0  | 1.10.0  |
| prosemirror-view                | 1.33.6  | 1.33.8  | 1.33.8  |
| prosemirror-view                | 1.33.8  | 1.34.3  | 1.34.3  |
| rimraf                          | 5.0.7   | 5.0.10  | 6.0.1   |
| rollup                          | 4.18.0  | 4.24.0  | 4.24.0  |
| sanitize-html                   | 2.13.0  | 2.13.1  | 2.13.1  |
| socket.io                       | 4.7.5   | 4.8.0   | 4.8.0   |
| socket.io-client                | 4.7.5   | 4.8.0   | 4.8.0   |
| terser                          | 5.31.1  | 5.34.1  | 5.34.1  |
| tinymce                         | 7.2.1   | 7.3.0   | 7.3.0   |
| typedoc                         | 0.26.7  | 0.26.8  | 0.26.8  |
| typedoc-plugin-missing-exports  | 2.2.0   | 2.3.0   | 3.0.0   |
| winston                         | 3.13.0  | 3.15.0  | 3.15.0  |

**Comment by aaclayton** [comment]
Docs build currently blocked by https://github.com/electron/asar/issues/330

**Comment by aaclayton** [comment]
Some packages we are blocked on updating:

* `@types/css-font-loading-module` throws documentation build errors
* `abstract-level` we shouldn't update to `2.0.0` until `classic-level` supports it
* `gulp` version 5.0.0 does not respect wildcard file order
* `pixi.js` 8.4.1 major breaking changes

**Comment by Pjb518** [comment]
> * `abstract-level` we shouldn't update to `2.0.0` until `classic-level` supports it

Just wanted to let you know that `classic-level` now supports version `2.0.0` of `abstract-level` in case you missed it. Link: https://github.com/Level/classic-level/releases/tag/v2.0.0

**Comment by Pjb518** [comment]
> Yes. I saw that. A very recent development!

Yeah, I just happened to notice it when updating some dependencies for a system I'm working on. Anyway, I just thought I'd let you know on the off chance it went unnoticed 🙂
