### ISSUE TITLE
@Embeds can be used to create circular references

### ISSUE THREAD

**Issue by FloRad** [foundryvtt/foundryvtt#11417]
### What happened?

Using the `@Embed` content embed you can create a circular reference which causes an infinite rendering loop

### What ways of accessing Foundry can you encounter this issue in?

- [x] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

1. Define an item or actor embed that contains enriched text, such as an item description
2. Embed a journal page in the enriched text.
3. Embed the item in the journal page.
4. Observe the infinite loop as soon as you call `document.toEmbed()`

![image](https://github.com/foundryvtt/foundryvtt/assets/5250409/a90aa9a4-0937-4447-b75c-a7e11362046f)

### What core version are you reporting this for?

 Version 12 - Stable 4

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
The core API will now take care of managing embedded depth automatically but you must take care in your `toEmbed` or `_buildEmbedHTML` override to propagate the `options` argument into your call to `TextEditor.enrichHTML`. Or, if you must provide custom options, then you must make sure to at least preserve the `options._embedDepth` value passed to `TextEditor.enrichHTML`.
