### ISSUE TITLE
<prose-mirror> doesn't close toggle the editor when pressing on save button without changes

### ISSUE THREAD

**Issue by yjeroen** [foundryvtt/foundryvtt#11414]
### What happened?

I expect the editor to close when the Save button is pressed, even if no content was changed.

Relevant boilerplate systemcode:

ActorsheetV2
```js
      case 'biography':
        context.tab = context.tabs[partId];
        // Enrich biography info for display
        // Enrichment turns text like `[[/r 1d20]]` into buttons
        context.enrichedBiography = await TextEditor.enrichHTML(
          this.actor.system.biography,
          {
            // Whether to show secret blocks in the finished html
            secrets: this.document.isOwner,
            // Data to fill in for inline rolls
            rollData: this.actor.getRollData(),
            // Relative UUID resolution
            relativeTo: this.actor,
          }
        );
        break;
```

biography template
```hbs
  {{#if editable}} 
    <prose-mirror name="system.biography" data-document-u-u-i-d="{{actor.uuid}}" value="{{system.biography}}" collaborate="true" toggled="true">
      {{{enrichedBiography}}}
    </prose-mirror>
  {{else}} {{{enrichedBiography}}}
  {{/if}}
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

[prose-mirror-only-back-to-inactive-on-change.webm](https://github.com/foundryvtt/foundryvtt/assets/1303988/7feb41a6-66ca-445a-9dcd-75758b9ec3e2)

### What core version are you reporting this for?

12.328

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Noticed this as well, will get it fixed.
