### ISSUE TITLE
Deleting a property with the `-=` prefix does not work if the property is part of a `DataModel`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#11420]
### What happened?

Let's say I have a `TypeDataModel` with the optional property `foo`:
```js
{
  foo: new foundry.data.fields.ObjectField({ required: false, initial: undefined }),
}
```
When I try to delete an existing `system.foo` property with `document.update({ "system.-=foo": null })` nothing happens. No errors or warnings in the console. The update promise resolves to `undefined`.
I think what's happening is that `Document#updateSource` performs a data validation
```js
// Clean and validate the provided changes, throwing an error if any change is invalid
this.validate({ changes, clean: true, fallback: options.fallback, strict: true, fields: true, joint: false });
```
which cleans out the (not in the schema) `-=foo` key from the update so the diff ends up as empty.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Try to delete a property from a `TypeDataModel` with an update containing a deletion prefix.

### What core version are you reporting this for?

Version 12 Build 328

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
From [manaflower](https://discord.com/channels/170995199584108546/1184176415139184731/1303785091365081240):

> **ALL MODULES DISABLED?** true
> **OS, Hosting, Browser (if applicable)**: any
> **Short Description of bug**: `DataModel#updateSource()` does not accept delete syntax.
> **Simple steps to reproduce the bug**:
> ```js
> class DM extends foundry.abstract.DataModel {
>    static defineSchema() {
>        return {
>          num: new foundry.data.fields.NumberField({required:false,initial:0}),
>        }
>    }
> }
> const c = new DM({num:15})
> c.updateSource({"-=num": null})
> console.log(c.num); // prints 15 still
> ```
> I can soft delete the value of course by doing `c.updateSource({ num: undefined })` instead, but this is not how rest of the API works with updates, so it's strange.

**Comment by aaclayton** [comment]
@In3luki this should be fixed as of V13 API Development 1 if you have a chance to test and confirm that your use case is properly handled in the latest release.
