### ISSUE TITLE
Consider readmitting `FunctionTerm`s as `DiceTerm` numbers

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11457]
### User Experience

In V11, a `DiceTerm`'s `number` field could be an actual number, a `MathTerm`/`FunctionTerm`, or some arbitrary parenthesized expression. V12 dropped `FunctionTerm`s from that list. If restoring such expressions is open to consideration, it appears those terms can be readmitted in the new grammar (limited testing with `floor(2/1)d6`, `ceil(1d6/2)d6`, etc.):
```diff
-Term = FunctionTerm / DiceTerm / NumericTerm / PoolTerm / Parenthetical / StringTerm
+Term = DiceTerm / FunctionTerm / NumericTerm / PoolTerm / Parenthetical / StringTerm
 
 FunctionTerm = fn:FunctionName "(" _ head:Expression? _ tail:(_ "," _ @Expression)* _ ")" flavor:Flavor? {
   return parser._onFunctionTerm(fn, head, tail, flavor, text());
 }
 
-DiceTerm = number:(Parenthetical / Constant)? [dD] faces:([a-z]i / Parenthetical / Constant) modifiers:Modifiers? flavor:Flavor? {
+DiceNumber = Parenthetical / FunctionTerm / Constant
+DiceTerm = number:DiceNumber? [dD] faces:([a-z]i / Parenthetical / Constant) modifiers:Modifiers? flavor:Flavor? {
   return parser._onDiceTerm(number, faces, modifiers, flavor, text());
 }
 ```

**Comment by aaclayton** [comment]
@stwlam encourage you to discuss with @Fyorl

**Comment by mkahvi** [comment]
I'd very much want this to be re-implemented.

**Comment by dmrickey** [comment]
Why are formulas that have been valid for a very long time no longer supported?
