### ISSUE TITLE
`DocumentCollection.getSearchableFields` returning incorrect field paths

### ISSUE THREAD

**Issue by AndrewBurian** [foundryvtt/foundryvtt#11452]
### What happened?

When using the full text search option in the journal on a standard `JournalEntry`, the `JournalEntryPage` collection is searched, but when calling `getSearchableFields` the results are broken, and return `["name", "", "content"]`, where it should have returned `["name", "text.content"]`.

The bug seems to be in the function passed to `schema.apply`

```javascript
// DocumentCollection.getSearchableFields()

// ...
    dataModel.schema.apply(function() {
      if ( (this instanceof foundry.data.fields.StringField) && this.textSearch ) {
        const [, ...path] = this.fieldPath.split(".");
        const searchPath = (isSubtype && !isEmbedded) ? ["system", ...path].join(".") : [...path].join(".");
        textSearchFields.add(searchPath);
      }
    });
```

the assignment `[, ...path] = ` discards the leading path part and doesn't readd it when the document isn't a subtype. So in the case of `text.content`, the `text.` prefix is lost.

When attempting to search the field later, there is no `content` object at the root
```javascript
// DocumentCollection.search()

// ...
const value = foundry.utils.getProperty(doc, field);
// value == undefined
```

I don't quite understand the logic for modifying the searchPath in the case of subtype documents, I assume this code is there to handle that case, but it seems to break the main document types.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create a JournalEntry with one or more pages
- Set the search bar to full text search
- Type in some query
- See the results from getSearchableFields (before caching)
or
- After some searching, inspect the `DocumentCollection.#dataModelSearchFieldsCache` for `'JournalEntryPage'`

I tested a version of the search path function where the `fieldPath` is used directly in the case of non subtype documents as below
```javascript
// DocumentCollection.getSearchableFields()

// ...
    dataModel.schema.apply(function() {
      if ( (this instanceof foundry.data.fields.StringField) && this.textSearch ) {
        const [, ...path] = this.fieldPath.split(".");
        const searchPath = (isSubtype && !isEmbedded) ? ["system", ...path].join(".") : this.fieldPath;
        textSearchFields.add(searchPath);
      }
    });
```
And the journal search does now populate all pages that have matching content. I don't know why this code exists for subtypes though so I don't know if this breaks the search functionality in other cases.

### What core version are you reporting this for?

12 stable 327

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
This bug was already fixed in 12.328 (#10948).
