### ISSUE TITLE
Do not automatically scroll the chat log to the bottom when switching sidebar tabs.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11461]
### User Experience

If I briefly need something from the other tabs, currently the chat log gets reset to bottom when I return to it. So please, disable that or allow disabling it.

Currently the workaround to this is to not swap tabs and instead pop one out, but I don't remember to do that every time.

There's also the convenient scroll to bottom button anyway if I really want to go back to the bottom, when I _actually_ do want that.

**Comment by aaclayton** [comment]
I reviewed the current UX here and agree that we should not automatically scroll to bottom when switching tabs. Have made this change.
