### ISSUE TITLE
PackFolders not created in first load after a module is enabled

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11473]
Reproduction steps

1. Create a fresh world
2. In the world, enable a module that has pack folders configured
3. Perform the required reload and observe that the packs are unfoldered
4. Reload again and observe the folders are created

**Comment by aaclayton** [comment]
@mattexdee we are using `packFolders` in several premium content releases lately. Have you noticed this issue occuring or seen reports of it?

**Comment by mattexdee** [comment]
@aaclayton I just did a test in V13 with the PHB and PBSO modules (one at a time) in a fresh world and all of their packs and folders appeared correctly after activating them. I can't say that I've seen any other reports about it yet either.

**Comment by aaclayton** [comment]
Closing as nonrepro. Can reopen if we gain new evidence.

**Comment by somanyrobots** [comment]
FWIW, I was just able to reproduce this issue perfectly. I finished making a module and installed it in a different foundry game, on a copy of foundry that had never seen the module before (via forge-vtt). On initial load, none of the packfolders appeared. They appeared after I rebooted foundry.
