### ISSUE TITLE
Feature: Add a way to specify htmlFields and filePathFields that exist within ArrayFields

### ISSUE THREAD

**Issue by BoltsJ** [foundryvtt/foundryvtt#11471]
### User Experience

Currently if a TypeDataModel contains an HTMLField or filePathField that exists within an ArrayField, there is no way to specify that for server side sanitation. Means that filepaths and htmlfields inside array fields must either be avoided, or sanitized manually client-side.

Providing a way to specify descendants of array fields would allow more robust data models. Currently, I have three schema fields in one of my DataModels even though an array field would be more concise. [Ref](https://github.com/BoltsJ/foundryvtt-hellpiercers/blob/main/src/data/actor.mjs#L121-L147)

Related: https://github.com/foundryvtt/dnd5e/issues/2394, https://github.com/foundryvtt/foundryvtt/issues/10366

**Comment by bhudnell** [comment]
I would also love for this to be implemented!

**Comment by Fyorl** [comment]
> @Fyorl Does this also work for `filePathField`s?

It does.
