### ISSUE TITLE
Consider officially maintaining JSON SchemaStore definitions

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11478]
The [JSON SchemaStore](https://www.schemastore.org/json/) definitions for Foundry packages are quite out of date. It may be worth officially maintaining the package schema definitions for community development use.

**Comment by aaclayton** [comment]
I would prefer that we focus on our own documentation first and foremost rather than using an external schema repo that we don't officially endorse or use.
