### ISSUE TITLE
Privacy Mode of the File Picker is ignored after switching from a GM to a non-GM user

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11475]
Originally reported by noogledonk: https://discord.com/channels/170995199584108546/1184176415139184731/1255308496182968360

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable):** Foundry 12.327, Canonical Ubuntu, MS Edge
**Short Description of bug:** Privacy Mode does not properly stop player from accessing purple highlighted files when accessing file picker from Journal image uploader.
**Simple steps to reproduce the bug:** As a player, open a journal you own. Select Add Page. Select Image as the Type. Create New Page. From the page, click the Browse Files icon next to image source. From here, all image files are now accessible, even the ones that --should be private. They can be selected and displayed in the journal page upon hitting Save Entry.

*Note: noogledonk wasn't able to reproduce the issue after testing it again.* (https://discord.com/channels/170995199584108546/1184176344276406292/1260320817124868196)

---

Originally reported by lordufreeman: https://discord.com/channels/170995199584108546/1184176415139184731/1263458494884085780

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows 10, Oracle Cloud, Chrome
**Short Description of bug**: Privacy Mode of the File Picker is ignored after switching from GM to Trusted User 
**Simple steps to reproduce the bug**: Hide a few folders in the picker using Privacy Mode as GM. Create a Trusted User and log in, check File Picker. Private folders are still visible (but marked as hidden). Does not happen if in Incognito Mode (caching related?).
**Screenshots and/or console errors**:

**Comment by aaclayton** [comment]
Closing as nonrepro.
