### ISSUE TITLE
Unable to import or execute compendium macros created before 12.329

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11483]
Originally reported by 117dios:
https://discord.com/channels/170995199584108546/1184176415139184731/1263931560038764635

**All modules disabled?** Yes
**OS/Hosting**: Ubuntu 22.04.4 LTS via Oracle Cloud Service, Any Browser
**Short description of bug:** Unable to import macro from compendium, or to execute macro from compendium. Making a new macro compendium, either empty or not, either locked or unlocked, seems to fix this.
**Simple steps to reproduce the bug:** Try to import or execute a macro from an existing compendium from 12.328 or before, without a macro compendium made in 12.329 present

![compendium-macro-error](https://github.com/user-attachments/assets/2d81f376-d0ff-4e96-8ccb-a0cd4d76461d)

**Comment by dev7355608** [comment]
Likely a regression caused by #11472. I suspect this can be triggered when you disable a module with a pack first. The disconnect from the pack probably clears the sanitized fields cache for this document type and it is not re-created.
