### ISSUE TITLE
Allow NumberField#_toInput's `step` to be any integer if `config.integer` is set.

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#11484]
### What happened?

```js
// NumberField
_toInput() {
  config.step ??= this.step;
  if ( this.integer ) {
    config.step = 1;
  }
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a setting with the following type:
```js
new foundry.data.fields.NumberField({
			initial: 0,
			min: 0,
			max: 100,
			step: 10,
                        integer: true
		})
```
2. Try to change the value, be it through the slider or the field.

### What core version are you reporting this for?

12.329

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by JPMeehan** [comment]
Seems like you should just be using `step` and not `integer`

**Comment by mclemente** [comment]
Then there's no guarantee the number is an integer, e.g. someone sets the setting's value to a float.

Also, I forgot to add `integer` to the reproduction code.

**Comment by aaclayton** [comment]
Assigning a `step` to the input has some significant UX implications that may not be desired. If you wish this behavior you can set `step: 1` in your field definition. I don't think I'm in favor of this proposal.

**Comment by esheyw** [comment]
Would validating that the `step` is itself an integer not be enough? Why must it be only ever `1`?
