### ISSUE TITLE
All Dice Rolling links in API Index are broken

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#11485]
### Where did you find it, or where does it belong for requests?

Other foundryvtt.com site page (not package listings)

### What page or file needs a look at?

https://foundryvtt.com/api/#md:dice-rolling

### What core version are you reporting this for?

Version 12

### What is wrong, in your opinion?

The Dice Rolling links all report a 404.

https://foundryvtt.com/api/classes/client.Roll.html
https://foundryvtt.com/api/classes/client.RollTerm.html
https://foundryvtt.com/api/classes/client.MersenneTwister.html
https://foundryvtt.com/api/classes/client.DiceTerm.html
https://foundryvtt.com/api/classes/client.FunctionTerm.html
https://foundryvtt.com/api/classes/client.NumericTerm.html
https://foundryvtt.com/api/classes/client.OperatorTerm.html
https://foundryvtt.com/api/classes/client.ParentheticalTerm.html
https://foundryvtt.com/api/classes/client.PoolTerm.html
https://foundryvtt.com/api/classes/client.StringTerm.html
https://foundryvtt.com/api/classes/client.Die.html
https://foundryvtt.com/api/classes/client.Coin.html
https://foundryvtt.com/api/classes/client.FateDie.html

**Comment by Norc** [comment]
After the fix, docs have been redeployed. While the URLs above no longer exist, the correct links in the API are now functioning properly: https://foundryvtt.com/api/#md:dice-rolling.
