### ISSUE TITLE
preUpdate hooks containing before update values

### ISSUE THREAD

**Issue by muhahahahe** [foundryvtt/foundryvtt#11499]
### User Experience

I recently rescued a module to still work in Foundry v12. Prior to v12 the returned document object of the hook `preUpdateToken` had the before update values for x and y of the token. Now in v12 the document contains the updated x and y. My request would be to include the old values in the changed object of the hook.

Example for my use case when someone moved a token on the canvas:
```JavaScript
Hooks.on("preUpdateToken", (document, changed, options, userId) => {
    //changed object containing old values
    changed = {
        x: 1000,
        y: 900,
        oldX: 1000,
        oldY: 1000,
    };
});
```
This would help developers getting better information about the change

**Comment by aaclayton** [comment]
A misunderstanding @muhahahahe, since this hook is *pre* - as in *before* the update, the `changed` object are the new values that will be updated and the `document` instance still contains old pre-change values.

**Comment by muhahahahe** [comment]
Then I wish to transfrom this issue to a bug report, let me know if i should open a new Issue or this will be reopened!

code:
![image](https://github.com/user-attachments/assets/ab0f72e3-061b-4b1e-b57c-301d041a51a1)

Logs:
![image](https://github.com/user-attachments/assets/48026844-7f60-4ebf-8dcb-9490eb3363e5)

![image](https://github.com/user-attachments/assets/68d36ce3-b7b7-4129-86da-21ce9e347b72)

![image](https://github.com/user-attachments/assets/da58d09e-eed3-43f3-859f-bb9c6a3bae00)

as you can see the document and the changed contain the same values

**Comment by aaclayton** [comment]
You can verify the core behavior in the `ClientDatabaseBackend.#preUpdateDocumentArray`. The `preUpdate` hook is called *before* diff and before any updates are applied to the document. If you are seeing other unexpected behavior here make sure that it isn't resulting from some other module or the game system that is incorrectly mutating the document in a preUpdate hook.

**Comment by muhahahahe** [comment]
This is a fresh game world only running my module: https://github.com/muhahahahe/8bit-movement
In the game system DnD5e 
![image](https://github.com/user-attachments/assets/db5c72e8-0a5a-4952-81b3-0137daa21cd6)

if you wish me to update to 12.330 i can do that and check with latest stable

**Comment by krbz999** [comment]
Is this a case of console lazy loading objects?

Try logging `x` and `y` of the token document directly, rather than logging the token document itself.

**Comment by muhahahahe** [comment]
wow, seems like it is
![image](https://github.com/user-attachments/assets/0d0ab252-c778-489e-b603-7562875f66f5)

![image](https://github.com/user-attachments/assets/4808537f-c839-4ee3-9f4b-f32ae57252f6)

then i had some different issue before while comparing these values, ill try again, thanks for the help

**Comment by muhahahahe** [comment]
I figured what the issue was, prior to v12 if `x` was changed only `x` was in the changed object. Now always both `x` and `y` are in changed, which screwed with my condition.
