### ISSUE TITLE
Symbols is a non-serializable primitive and should not be an allowed setting type

### ISSUE THREAD

**Issue by Spice-King** [foundryvtt/foundryvtt#11507]
### What happened?

@esheyw on Discord spotted this, I did digging. Symbols exist to be not equal anything else, additional calls to `Symbol()` will always generate a new unique Symbol instance, even with the same key argument. While `Symbol.for(key)` exists, and would interact with a global Symbol registry, it's basically a wrapper around a hidden hash map that generates missing Symbols on demand and is basically a glorified string.

There is no good way to persist the Symbol primitive, if you try to find some way to map it into some other primitive you can serialize, you should just be working with that primitive value to begin with.

Symbol should be removed from `Setting.#PRIMITIVE_TYPES` in `resources/app/client/data/documents/setting.js` and anywhere else it was used. There should be limited fallout if someone did use Symbols as a setting, but the flip side was that it was a non-functional setting anyway and a hard error will tell them to fix it.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Create a setting with the type of Symbol
2. Observe that the Symbol does not persist correctly.

### What core version are you reporting this for?

v10.272-v12.330

### Relevant log output

```shell
Welcome to Node.js v20.15.0.
Type ".help" for more information.
> JSON.stringify(Symbol())
undefined
> JSON.stringify(Symbol('testing'))
undefined
> Symbol() == Symbol()
false
> Symbol('testing') == Symbol('testing')
false
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Yeah, this was likely an oversight. We should remove `Symbol` as a valid type.
