### ISSUE TITLE
Ability to hide tokens that are not on the ground from tokens with Tremorsense/Feel Tremor

### ISSUE THREAD

**Issue by Icarus-the-phoenix** [foundryvtt/foundryvtt#11508]
### User Experience

In order to prevent player confusion on what they can and can't see, I'd like to have the ability to hide tokens that are not on the ground from tokens with Tremorsense/Feel Tremor. 
Currently if a token is at a different elevation from a unit with tremorsense, the tremorsense unit can still see it as shown in the 2 pictures below in DnD5e and Pf2e systems. I think this is how it should work, because a unit at higher elevation could still be on the same ground. However, because of this, there is no way to hide a flying unit from a unit with tremorsense.
![image](https://github.com/user-attachments/assets/fb0fd9e7-8c43-457c-b285-6535d7c376c2)
![image](https://github.com/user-attachments/assets/1804a53d-76ba-46ac-907d-9cda2923e797)

I propose adding a way for players/dm to change whether or not their token is in a flying state, that prevents them from being seen by tokens with tremorsense/feel tremor. It could look something like the picture below.
![image](https://github.com/user-attachments/assets/c8b4ab3e-599a-4c2b-a9bd-719992019914)

**Comment by krbz999** [comment]
This is what the Flying condition is for.

**Comment by Icarus-the-phoenix** [comment]
That works for Dnd5e, but Pf2e does not have a flying condition or a condition similar to it. 
I mostly play pf2e, but figured I should post the issue with a screenshot from Dnd5e as well. Sorry I didn't know that system had a solution.

**Comment by krbz999** [comment]
The flying and hovering conditions are core.

**Comment by Icarus-the-phoenix** [comment]
Interesting. They seem to be removed from Pf2e. They are not included in the system.

**Comment by Icarus-the-phoenix** [comment]
This seems to be an issue needing to be fixed by the pf2e system. Closing issue
