### ISSUE TITLE
allow for customisable template measurements for each system.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#11502]
### User Experience

i would love for systems that have different template measurements to be able to customise their systems to have custom templates to make it easier for systems to have ways to do things such as the different templates in such a system like pf2e. as per the examples below. 
![image](https://github.com/user-attachments/assets/fb107f51-7f36-4947-a212-a58ee4ca630c)

**Comment by aaclayton** [comment]
We added a huge number of improvements for measured templates and grid measurement rules in V12. We won't be working further in this area anytime soon.
