### ISSUE TITLE
Macro#execute is supposed to return a ChatMessage instance if the macro was of the chat type

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11505]
Chat macros do not return a chat message, as documented. `Macro##executeChat` simply has no return at all, making the type `void`.

Related, the return type for `Macro##executeScript` should be updated to `Promise<*>` because it's *always* a promise and can be awaited.

**Comment by Norc** [comment]
@JPMeehan for clarity, the second part of your issue here was not addressed:

> the return type for Macro##executeScript should be updated to Promise<*> because it's always a promise and can be awaited.

If you believe that this is something that you believe needs to be done, please raise it as a separate issue. If so, please provide some additional clarification or examples because this does not appear correct to us at first glance.

**Comment by JPMeehan** [comment]
(not at my computer, but) Execute Script is an asynchronous function, so the return is a promise regardless of the content of the script.

**Comment by krbz999** [comment]
`#executeScript` is not async, though it does return a Promise if the call to the created `AsyncFunction` is succesful, otherwise it pops out a `ui.notification.error` and returns nothing.

**Comment by Norc** [comment]
What Zhell says matches what the devs tell me, yes.

Like I said, @JPMeehan, if you believe that this is something that needs to be adressed in some way, please raise it as a separate issue. This one is being closed as completed without addressing this component and I don't want this feedback to be lost if there's something that needs to be done here. Thanks!
