### ISSUE TITLE
Consider adding helper function to generate the `chatData` for `Roll#render`

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11532]
Currently, having a fully custom roll template requires fully overriding `Roll#render`, as the data passed to the handlebars template is fairly limited. It would be helpful if there was a `_prepareContext` equivalent that would be used to generate different `chatData` for the template without overriding the entire `Roll#render` function.

**Comment by JPMeehan** [comment]
Appears to be resolved by #11650

**Comment by aaclayton** [comment]
Sorry, missed this duplicate. Deleting this one.
