### ISSUE TITLE
Error is thrown when setting a flag that is null

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11540]
Originally reported by aedif: https://discord.com/channels/170995199584108546/1184176415139184731/1269287320649994282

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: n/a
**Short Description of bug**: Foundry began throwing errors as of release 12.299 while processing updates that overwrite null flags
**Simple steps to reproduce the bug**:
```js
_token.document.update({"flags.world.abc": null})
_token.document.update({"flags.world.abc": {test: [123]}})
```
**Screenshots and/or console errors**:
![image](https://github.com/user-attachments/assets/8762a939-646f-4464-aa66-60136ca37912)

**Comment by aaclayton** [comment]
This seems probably related to storing token history changes.
