### ISSUE TITLE
Core Actor art mappings do not overwrite non-default system compendium data

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#11563]
### What happened?

I set up a module with Actor Art Mappings for Dnd5e, including subject art, token art, and of course actor art. But most of my Art map was ignored by FoundryVTT. As an example, I set up the Unicorn. I expected to see the Unicorn's art in the compendium while flipping through the creatures, but it uses the top-down art that comes with the system. Importing the Unicorn did not change this, and the actor shows the Top-Down art too.

![image](https://github.com/user-attachments/assets/f46a80d0-ea30-4c91-bbcc-f6b58189bfa8)

When placing the unicorn on the canvas, it had the dynamic token enabled and used my custom subject art, but the scale was set to the system compendium 1.5 instead of the Actor Art Mapping 2.0 (manually adjusted to the right)

![image](https://github.com/user-attachments/assets/41528e86-0502-4606-97c7-06e670047238)

As a final test, I disabled the dynamic token and the unicorn is now using the top-down token instead of the Pog style one provided by the image mapping.

![image](https://github.com/user-attachments/assets/16b12657-b826-48a8-8e55-0abf82873a72)

I can provide the complete module for testing. This has been reproduced in other systems.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

enable a module with Foundry Core style image mapping to the DnD5e system, or the 13th Age system.

### What core version are you reporting this for?

12.330

### Relevant log output

```shell
no log output
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
The `dnd5e` system does not make use of the new API yet.

**Comment by Drental** [comment]
Yes, the system doesn't make use of the old API either, it's just data in the compendium.

Data in the compendium that is breaking any core API mapping. And the same thing happens in `archmage`

**Comment by Fyorl** [comment]
> Yes, the system doesn't make use of the old API either, it's just data in the compendium.

Can you elaborate? The existing, system-specific API still functions just fine when I tested it with the PF2e Bestiaries pack.

**Comment by Drental** [comment]
I'm not reporting on the DnD5e system, I'm reporting on FoundryVTT Core 😅 

I have one module (the one I used to produce this issue) and the system active in the world. The system does not itself use the art mapping, it only provides an API for modules to use, which is then not used by the system itself nor any installed modules.

The Module that I do have uses the Core Actor Art Mapping functionality, but it loses against the data that the compendium already has. I could Reproduce this issue in the 13th Age system too.

Are you saying, that the dnd5e system is actively preventing a Core Foundry Functionality from working, even if the system API to achieve the same functionality is not used at all?

**Comment by Drental** [comment]
Ah. Thanks for that link. I checked for a file like that but couldn't find it, looks that I didn't look hard enough.

**Comment by Fyorl** [comment]
You should be able to provide mappings in your module in both the old and new formats and then when the system eventually switches over to the new API, the mappings should continue working.
