### ISSUE TITLE
Add Mouse to keybind options clicking and mouse buttons

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#11562]
### User Experience

im trying to add my mouse and mouse buttons from my gaming mouse to keybinds but it seems to be a foundry limitation. could that be added to foundry that if you edit a keybind it can be modified by right click and any mouse buttons?

**Comment by aaclayton** [comment]
Closing for https://github.com/foundryvtt/foundryvtt/issues/7389
