### ISSUE TITLE
Taking the level into account in the graphic representation of regions

### ISSUE THREAD

**Issue by Sasmira** [foundryvtt/foundryvtt#11595]
### User Experience

Hello Hello, 

Would it be possible for the graphic representation of the region to take into account the level when the latter is entered in the region. 
As you can see from my screenshot, when the level in the region is set, the graphical representation appears on all the level layers, making the maps unreadable.

<img src="https://puu.sh/Kd3wz/b502b3af5f.jpg">

Thank you for your help and understanding.
Sincerely
Sasmira.

**Comment by aaclayton** [comment]
It sounds like you are requesting a core feature here for how scene regions should interact with the levels module. Am I misunderstanding? I hope it would be clear why these two things don't interact. Until we add core support for multi-level scenes, it would be up to a module to handle this additional UX.

Please feel free to reopen if I have misunderstood your request.
