### ISSUE TITLE
Please make `TeleportTokenRegionBehaviorType.#teleportToken` a non-private method

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/foundryvtt#11590]
### User Experience

I would love to be able to use this method to, for instance, create a macro (to perhaps be executed by a region) with a dialog that has a list of potential teleport destinations, choose one from the list, and teleport to it. I would prefer to just be able to use this method to do so, as it seems to do everything required (and I am not sure what potential harm it could cause, but it doesn't seem like much). 

This may require `#getDestination` to be made not private as well.

**Comment by aaclayton** [comment]
Combining with #10828
