### ISSUE TITLE
Token rings are not correctly sized in hexagonal grids with Grid fit mode

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11608]
Originally reported by boltsj: https://discord.com/channels/170995199584108546/1184176415139184731/1273753630922510438

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Self hosted/firefox
**Short Description of bug**: Dynamic Token Rings Fit Mode: Grid scales oddly on hexagonal rows grids.
**Simple steps to reproduce the bug**:
1. Create a scene with a hexagonal row grid and add a 1×1, 2×2 and 3×3 token using dynamic rings
2. Set the Dynamic Rings Scaling setting to grid
3. The size 1 token will have the ring exceed the grid space, the size 2 will be about right and the size 3 (and larger) will be smaller than the border
4. Change the scene to have a hexagonal column grid
5. The tokens will appropriately fill the grid spaces
**Screenshots and/or console errors**:

![image](https://github.com/user-attachments/assets/eac0fd0a-b396-4e2a-8e77-18075e511a6d)
![image](https://github.com/user-attachments/assets/d9b649a1-82bd-49b2-b9eb-215998268968)
![image](https://github.com/user-attachments/assets/f1478654-cb05-4b2f-93b8-9ded020b1229)

**Comment by BoltsJ** [comment]
So for some additional clarification, this appears to be related to having a token texture that is not square. I have created a 4:3 example texture and set it as the token image and the results are as follows:
![image](https://github.com/user-attachments/assets/130c0b6a-4308-49da-b2ba-a1d8129c7ab2)
![image](https://github.com/user-attachments/assets/aa3b5e23-b5fe-41bb-986a-79334f07cf1c)

On hexagonal columns, a texture that is wider than it is tall leads to the ring being too large for size 1, and too small for size 3 and up.

![image](https://github.com/user-attachments/assets/5fa8d477-c18e-4182-ae6e-30ad4f759d4b)
![image](https://github.com/user-attachments/assets/77344ff2-5c4b-4a84-b285-35e5bb93ad70)

And on hexagonal rows, a texture that is taller than it is wide leads to the same behavior. 

Token settings: 
![image](https://github.com/user-attachments/assets/d7c43609-3ca4-4ae3-b841-a9bb233e8764)

**Comment by Feu-Secret** [comment]
The Dynamic Rings fit modes have been rationalized. When there is no subject texture, the rings are now fitted to the Token grid bounds (inner radius of the grid polygon) instead of the token texture bounds. 
- In Grid fit mode, the ring radius is 100%. 
- In Standard fit mode, the ring radius is 66%.

With a subject texture, the ring fits to it.

![image](https://github.com/user-attachments/assets/055e644e-c82d-4bc5-a00e-f41ad839bc62)
