### ISSUE TITLE
"Jump to bottom" might not disappear when deleting a message that removes the scroll

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#11618]
### What happened?

If you have just enough messages to have the scroll displayed, scroll up to the top of the chat log, and then delete a message that would hide the scroll, the "Jump to bottom" button doesn't disappear.

This only seems to happen when the scroll is at the top of the log.

Also, clicking the button doesn't seem to remove it, since the listener that hides it isn't triggered since no scrolling is done. I'm not sure if I should open another issue for that.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Have enough messages to fill the chat (e.g. 9+ roll messages).
2. Scroll up to the top.
3. Delete any number of messages.
4. The "Jump to button" won't be hidden and won't work either.

### What core version are you reporting this for?

12.331

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@stwlam could you triage this one since it's related to something you worked on recently?
