### ISSUE TITLE
The `renderTemplate` method (line 7900 foundry.js) seem not work as before on v12

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#11623]
### What happened?

I don't know if it's an error or an advancement of v12, but the `renderTemplate` method (line 7900 foundry.js) no longer renders a template that worked for me in version 11 and I can't figure out why, however, I was able to replicate the error and list the steps needed for a test from your side.

![2024-08-25 19 20 15](https://github.com/user-attachments/assets/15565452-4613-4900-8758-5c01d3409f86)
![2024-08-25 19 22 44](https://github.com/user-attachments/assets/6766ac20-05e2-4bd7-8e75-973589a026b0)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Get this hanlderbar templates by **path**: https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/src/templates/card/better-chat-card.hbs
- Prepare this **data**: https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/wiki/backups/v12/json_data_with_bug.txt
- Apply the method: `renderTemplate(path, data)`
- For some strange reasons the `itemsData` list is not "parsed" on the handlerbar template

### What core version are you reporting this for?

Version 12 Stable 331

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by krbz999** [comment]
Your hbs template is doing a switch case on `type` and seems to be expecting numbers, and it looks like it is ... table results?

The types in `CONST.TABLE_RESULT_TYPES` are strings, not numbers.

**Comment by p4535992** [comment]
> Your hbs template is doing a switch case on `type` and seems to be expecting numbers, and it looks like it is ... table results?
> 
> The types in `CONST.TABLE_RESULT_TYPES` are strings, not numbers.

Good catch fixed with the strings "text", "document", "pack", the issue persis, but i'll try some more test.

**Comment by p4535992** [comment]
Nothing I don't understand why it doesn't work in v12.
I don't know what else could have changed the constants now look correct to me and it doesn't even give me any parsing error it simply returns an empty string as if it doesn't enter the “itemsData” loop :(. 
It is likely to be my mistake .
I could change the template to a “smarter” one probably, but I would like to understand why it is not working on v12
