### ISSUE TITLE
A position update during an ongoing movement animation can change the path of the Token such that animation to the new position reveals part of the scene that the user is not supposed to see

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11628]
Example: left GM, right player.

![movement-animation-reveals](https://github.com/user-attachments/assets/4c0b7299-5d3c-4857-bfe9-56c18384365a)

**Comment by caewok** [comment]
Possibly related: #11627. 

Right now, the animation uses the current token document. Any updates to that document can affect the animation, which is what you see when the GM changes the destination of the token in the screenshot. 

Consider a more comprehensive change that relegates some of this to a "path manager" that can pause and change token movement. This will become increasingly important as more complex regions compete for how the token should move.

**Comment by dev7355608** [comment]
Fixed by #11684: Animation of movement properties (`x`, `y`, `elevation`, `width`, and `height`) are now always chained. Other animated properties are still animated unchained.
