### ISSUE TITLE
Visibility in Encounter tracker doesn't track with actual token visibility

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11635]
### What happened?

Changing the visibility of the combatant in the encounter tracker or the token on the canvas, does not change the visibility in the other.

When combatants are added to the encounter tracker, the encounter tracker shows the correct visibility for the tokens.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Have some tokens with visibility disabled on the canvas.
- Add them to the encounter tracker - observe that those tokens are shown as not visible in the tracker.
- Change the visibility in either the tracker or on the canvas - observe that the visibility is NOT reflected in the other place.

### What core version are you reporting this for?

12.331

### Relevant log output

```shell
No output in console
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
These visibilities start out (by default) as linked because it's a sensible default value to assign - but they are _intentionally_ allowed to evolve separately after that point. A token may become hidden from view but still have a visible turn on the combat tracker, or a vice-versa.
