### ISSUE TITLE
Token Default Settings not honored when dragging compendium actor to Actors Tab

### ISSUE THREAD

**Issue by xiitone** [foundryvtt/foundryvtt#11639]
### What happened?

When I drop a token on a map directly from a compendium, the Display Name value I set up in core settings works just fine. If I instead drop an NPC from the compendium into the actor list, and then drag from there onto a map, it sets the Display Name to "Never Displayed"
Furthermore, for actor that gets auto-created when I drop an NPC on a map-any future copies of that one that I drop on the map from the actor list have the correct Display Name

Summary:
Compendium->Map = follows default Display Name from setting
Actor List entry from above->Map = follows default Display Name from setting
Compendium->Actor List->Map = sets Display Name to "Never Displayed"

I've verified this behavoir using both the pf2e system and level up

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Move creature/npc from compendia to the actor list
drag creature from actor list to canvas

### What core version are you reporting this for?

Version 12 Stable - Buld 331

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl I recall we spoke about this recently but my recollection is failing me a little. This is an *intended* limitation, correct? To avoid overwriting meaningful compendium configuration data?

**Comment by Fyorl** [comment]
> @Fyorl I recall we spoke about this recently but my recollection is failing me a little. This is an _intended_ limitation, correct? To avoid overwriting meaningful compendium configuration data?

There's an open issue #9818 that is related to the logic used for when default token settings are applied, and there are some limitations that are still unresolved.

This issue I think needs some investigation. Different behaviour based on whether you drag to the canvas vs. drag to the sidebar is strange. It may be that one of those code paths is not calling `importFromCompendium` or something.

**Comment by dagit** [comment]
This bug is really obnoxious. If you don't drag to the actor tab then you end up with lots of duplicates in your actor list. If you do drag from the actor tab, then you have to edit the settings individually for each token (no group edit).

**Comment by unsoluble** [comment]
@dagit You might be mixing up a couple of concepts here. This bug very specifically impacts the act of importing an actor from a compendium pack by dragging the actor from the pack to the Actors sidebar. If you do _that action_, then your Default Token Config will not be applied to this actor. 

If you want your defaults to apply, currently all you need to do is import the actor from the pack by either dragging it directly to a scene, or opening its sheet in the pack and clicking Import in the window header. Both of these methods result in the actor being imported to the Actors sidebar, same as with the first case.

**Comment by dagit** [comment]
> @dagit You might be mixing up a couple of concepts here. This bug very specifically impacts the act of importing an actor from a compendium pack by dragging the actor from the pack to the Actors sidebar. If you do _that action_, then your Default Token Config will not be applied to this actor.

Right. I lost a couple hours of my time today due to doing this.

> If you want your defaults to apply, currently all you need to do is import the actor from the pack by either dragging it directly to a scene,

This is the case I was talking about where it causes duplicates to appear in the actor tab. If you were to do this every time you want to add an actor of some type to one of your scenes, it would appear again in the actor tab.

> or opening its sheet in the pack and clicking Import in the window header. Both of these methods result in the actor being imported to the Actors sidebar, same as with the first case.

I have not tried this option. So then once you drag from the actor tab to the scene it will have the correct defaults?

**Comment by unsoluble** [comment]
In any of these cases you should only ever be importing an actor one time (creating it in your Actors sidebar one time). For all subsequent token creation you should be dragging from the Actors sidebar.
