### ISSUE TITLE
The global light source should not be restricted by roofs

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11644]

**Comment by Drag0nF** [comment]
Any update on this issue? It seems to not being looked at anymore. I'd argue it's a pretty large bug in the lighting engine for anyone who uses overhead tiles (which are a big part of how a lot of maps are set up, including your own adventures, like A House Divided)

**Comment by aaclayton** [comment]
> Any update on this issue? It seems to not being looked at anymore. I'd argue it's a pretty large bug in the lighting engine for anyone who uses overhead tiles (which are a big part of how a lot of maps are set up, including your own adventures, like A House Divided)

This issue is assigned to our V13 project board and assigned to a team member to work on, so I'm not sure why you would think that it's "not being looked at". Some things take time.

**Comment by dev7355608** [comment]
Originally reported by gambettv: https://discord.com/channels/170995199584108546/1184176415139184731/1354489075335303299

**ALL MODULES DISABLED?** true
**Bug:** If an overhead tile is set to "Restricts Light" on a scene set to "Global Illumination" and no other light sources, a token with Darkvision will see grayscale beneath the roof, however a token without Darkvision will see completely normally beneath it.
**Steps to reproduce:** Create a scene with Token Vision and Global Illumination Turned on, add an overhead tile a player's token can go under. Take two tokens with vision, one with Darkvision and one with Basic Vision, and move them beneath the overhead tile and alternate betwen them. The one with Darkvision will show black and white beneath that area, as if they are in darkness. The one with only basic vision will be able to see in color, completely normally.

![Image](https://github.com/user-attachments/assets/3dc082e2-9ac2-4342-a1df-e6edb39887ba)
