### ISSUE TITLE
Nested dice operations throws error

### ISSUE THREAD

**Issue by fluxxdog** [foundryvtt/foundryvtt#11647]
### What happened?

Operation inside of parentheses throws errors. These errors occur with operations as simple as subtraction. See Reproduction steps for some tested examples.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

The following rolls were tested. Ones that threw errors are marked.

/r 1d20+1+1d4+max(0,floor((10-0)/2))+@bonus #Error
/r 1d20+1+1d4+max(0,floor(10-0/2))+@bonus #Error
/r 1d20+1+1d4+max(0,(10-0)/2)+@bonus #Error
/r 1d20+1+1d4+max(0,10/2)+@bonus #Error
/r 1d20+1+1d4+max(0,5)+@bonus #Works!

### What core version are you reporting this for?

Version 12 Stable Build 331

### Relevant log output

```shell
All the rolls marked #Error throw the same error as follows:


Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at Roll._evaluateASTSync (foundry-esm.js:63693:17)
    at Roll._evaluateASTSync (foundry-esm.js:63704:29)
    at Roll._evaluateASTSync (foundry-esm.js:63704:29)
    at Roll._evaluateASTSync (foundry-esm.js:63704:29)
    at Roll._evaluateSync (foundry-esm.js:63672:26)
    at Roll.evaluateSync (foundry-esm.js:63587:19)
    at simplifyRollFormula (simplify-roll-formula.mjs:68:87)
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:339:29)
    at chat-message.mjs:317:68
    at NodeList.forEach (<anonymous>)```
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl where does this fall on the spectrum of bug vs. known/intended limitation?

**Comment by Fyorl** [comment]
I think this is actually a dnd5e bug caused by some dice simplification done in chat messages ( foundryvtt/dnd5e#3895 specifically) that has since been fixed. I was unable to reproduce this in SWS or the dnd5e `4.0.x` branch.

**Comment by aaclayton** [comment]
Thanks for the confirmation @Fyorl!

**Comment by fluxxdog** [comment]
Can confirm this now works as expected in dnd5e 4.0.0. Thank you for your time.
