### ISSUE TITLE
Expand show undentify description

### ISSUE THREAD

**Issue by gandb** [foundryvtt/foundryvtt#11655]
### What happened?

Secret Information is revewed to player
![foundry-bug](https://github.com/user-attachments/assets/17758a6c-e9cd-4007-93bb-5369e9a665f2)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

When the player click in expand, into the item menu (in bag) or in the line of the item, the undentify description is showed.  

### What core version are you reporting this for?

12.330

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
This is a bug with the dnd5e system, not a core Foundry VTT bug. It has already been fixed for the next release, see foundryvtt/dnd5e#3890
