### ISSUE TITLE
Improve documentation of server-side views `installPackage` and `checkPackage` methods to clarify which arguments are strictly required and which are optional.

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#11659]
### What happened?

Encountered while attempting to simulate the browser and install a premium package with a POST to `/setup` but only when providing `id`. Omitting `id` causes the install to proceed as normal, avoiding the error (possibly a bug or unintended).

The issue is raised mainly to point out the possible discrepancy since I'm not sure why adding the `id` property specifically does a downgrade check.

- Since the `id` is also included in the manifest contents, you might expect both with or without `id` to run into the downgrade check and error.
- Is downgrading to an older version of a premium package from manifest URL meant to be disallowed like the error implies it is, or is it meant to be allowed?
- If it is meant to be allowed, why is it being disallowed when I add `id` in the POST?

Thanks for reading and guidance appreciated!

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Assume version v1.2.2 of pf2e-tokens-bestiaries is installed.

Using Firefox POST to `/setup` with:
`{"type":"module","manifest":"https://r2.foundryvtt.com/packages-public/pf2e-tokens-bestiaries/module-1.1.1.json","action":"installPackage", "id": "pf2e-tokens-bestiaries"}`

This returns an error:
`You are currently using a more recent version of module Pathfinder Token Pack: Bestiaries and may not downgrade to an older version`

But if you omit the `id` (as is the case when installing from manifest URL on the setup screen) and POST to `/setup` with `{"type":"module","manifest":"https://r2.foundryvtt.com/packages-public/pf2e-tokens-bestiaries/module-1.1.1.json","action":"installPackage"}`, it succeeds.

### What core version are you reporting this for?

v12.329

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We can update our server-side documentation to be more precise about what arguments are required or not, but I think this is *working as designed*. 

An installation on top of a known local ID checks that local package with some extra verifications. An installation using only a manifest URL is more of a "brute force" install.

Is this causing you a problem? Or were you raising this issue as a FYI for us? I'm not sure what the intended action item is here. Could you clarify?

**Comment by rikmarais** [comment]
> We can update our server-side documentation to be more precise about what arguments are required or not, but I think this is _working as designed_.
> 
> An installation on top of a known local ID checks that local package with some extra verifications. An installation using only a manifest URL is more of a "brute force" install.
> 
> Is this causing you a problem? Or were you raising this issue as a FYI for us? I'm not sure what the intended action item is here. Could you clarify?

Hey there @aaclayton, thanks for the reply and clarification.
The issue was raised mainly as an FYI/query about why adding `id` would do a check, but omitting it would skip the check. I thought it might be a bug, but I see from your explanation that adding the `id` is expected to do the extra checks so that's my misunderstanding.
