### ISSUE TITLE
Add Non-Ellipsed Buttons to the Window Header for ApplicationV2

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/foundryvtt#11666]
### User Experience

I’d like to request a core method for ApplicationV2 to add buttons directly to the window header without placing them under the ellipsis menu; for instances where the button is intrinsic to the application design. For example, the buttons on the header of dnd5e 4's new item sheets (though I understand these are populated in a different way).

In my current use case, I’d like to add a help button to my forms so that users can quickly find it when they need assistance. Since this is just a single button on a module-specific form, putting it under the ellipsis menu makes it far less noticeable. Users might not even realize it’s there unless they’ve read about it elsewhere or they randomly decide to see what's under the menu. This is different from the scenario where modules populate the header with buttons in a core or system applications, which suffer from cluttered headers. In these instances, it feels like the menu serves the purpose of "and here's all the other options provided by your modules" rather than "here's some options specific to the form".

Here's another example, where a show/hide button is added to the window header (currently still in ApplicationV1):
![image](https://github.com/user-attachments/assets/8ea4cfde-bcd0-4e42-9fd1-b2fe5d736976)

**Comment by aaclayton** [comment]
You can accomplish this in your subclass by extending the `ApplicationV2#_renderFrame` method. We spent so much of the last several major versions with users complaining about button clutter in the application header, the decision to move to a nested submenu was an intentional one that we're not going to turn back from now.

**Comment by Larkinabout** [comment]
Thanks, I'll have a look at `ApplicationV2#_renderFrame`. Just a note that I have no issues with the solution for button clutter, rather a desire to choose to easily pop a button on the header for my own applications where button clutter is unlikely to be an issue in comparison to core and system applications. Point taken though if it's introduction would be seen as an encouragement to pop them any old application.
