### ISSUE TITLE
Improve performance of `deepClone` and `diffObject` workhorse methods by avoiding unnecessary object creation.

### ISSUE THREAD

**Issue by Codas** [foundryvtt/foundryvtt#11665]
### User Experience

The `deepClone` function is heavily used in foundry core itself and even more so probably in the Pathfinder2e system, either directly or indirectly. In fact, when changing turns in the encounter tracker, adding effects or modifying the inventory, 5-10% of the time for these operations is regularily spent within the `deepClone` function.

The function body is already well optimized and possible micro optimizations in my testing only resulted in barely measurable improvements but made the code too verbose. The current implementation is really clean, neat and fast!

However, the function definition itself can be improved:
```js
function deepClone(original, { strict = false, _d = 0 } = {}) { /* ... */ }
```

About 10% of the execution time of `deepClone` in my testing is spent with creating the options object. Luckily, a simple fix for this would be to move the actual implementation to another function with explicit arguments:

```js
function deepClone(original, { strict = false, _d = 0 } = {}) {
  return _deepClone(original, strict, _d);
}
function _deepClone(original, strict, _d) { /* calls _deepClone recursively */ }
```

In my testing this improves the performance by about 10%. I have also prepared a jsperf for this: https://jsperf.app/fatado.

**Comment by aaclayton** [comment]
Good suggestion, thanks for the benchmark.

**Comment by aaclayton** [comment]
Thanks @Codas!
