### ISSUE TITLE
Support header control customization via ApplicationV2 hook with the hook signature `getHeaderControls{ApplicationClassName}(app, controls)`

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11668]
### What happened?

There appears to be no mechanism for adding header buttons when you aren't the owner of the app.

With AppV1 I could use `getItemSheetHeaderButtons`, `getActorSheetHeaderButtons`, `getApplicationHeaderButtons`  and the like to add header buttons.

With AppV2 there is no similar hook in place, only render hooks.

@Fyorl mentioned that there was supposed to be a pre-render hook, but no such thing exists.

So either this is a bug and something broke, or the feature was lost and modules or other things can no longer add buttons to sheets, which seems to downplay the need for  the menu that AppV2 introduced.

Please fix/re-implement some header button mechanism that allows modules to insert header buttons, otherwise this is forcing people to monkeypatch it in.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
Hooks.on('getActorSheetHeaderButtons', (app, buttons) => {
  buttons.unshift({
    class: 'my-button',
    icon: 'fas fa-atom',
    label: "MY BUTTON",
    onclick: _ => ui.notifications.info("It works!"),
  });
});
```
That's the old method. Which doesn't work with AppV2.

### What core version are you reporting this for?

12.331

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by ddbrown30** [comment]
What was the fix for this?

**Comment by aaclayton** [comment]
> What was the fix for this?

ApplicationV2 instances emit a `getHeaderControls{ApplicationClassName}` hook event, for example `getHeaderControlsActorSheetV2`.

**Comment by riccisi** [comment]
Sorry, but what did the "onclick" callback function be replaced with?
