### ISSUE TITLE
Recursively prepare ApplicationV2 options allowing for hierarchically nested arrays to be concatenated instead of replaced.

### ISSUE THREAD

**Issue by moo-man** [foundryvtt/foundryvtt#11675]
### What happened?

When defining a subclass of ActorSheetV2, I added a button to `windows.controls` within `DEFAULT_OPTIONS`, but this overwrites the default buttons for Actor Sheets
```js
class MyActorSheet extends HandlebarsApplicationMixin(ActorSheetV2) {
  static DEFAULT_OPTIONS = {
    window : {
      controls : [
        {
          icon : 'fa-solid fa-gear',
          label : "Actor Settings",
          action : "configureActor"
        }
      ]
    },
}
```
![image](https://github.com/user-attachments/assets/3ba06d11-001d-428d-bb8e-15ddcdbe1e7d)

The root cause is within `_initializeApplicationOptions` - 
```js
if ( Array.isArray(v0) ) applicationOptions[k].push(...v);                // Concatenate arrays
else if ( foundry.utils.getType(v0) === "Object") Object.assign(v0, v);   // Merge objects
```

`window` is not an array, so it merges the objects.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See Above - create a subclass of ActorSheetV2 and add one or more window header controls

### What core version are you reporting this for?

V12 Build 331

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hopefully we can find a way to make this a bit smoother.
