### ISSUE TITLE
Add `User#isActiveGM`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11678]
`user.isActiveGM === (user === game.users.activeGM)`

**Comment by esheyw** [comment]
Could we also get helpers for "Is Actual GM" and "Is Active Actual GM"? the current helpers only check for assisant, but there are things assistants can't do (set world settings, at a minimum)

**Comment by aaclayton** [comment]
> Could we also get helpers for "Is Actual GM" and "Is Active Actual GM"? the current helpers only check for assisant, but there are things assistants can't do (set world settings, at a minimum)

We actually made a chance to `Users#activeGM` to return a full Gamemaster if one is available.

**Comment by esheyw** [comment]
Just to clarify: it preferentially returns real GMs, but will still fall back to assistants if there are no full GMs and non-zero assistants? Because that is definitely improved behaviour IMO, but the fallback makes it false positive an 'can I update world settings' check if there are only Assistants logged in.

**Comment by JPMeehan** [comment]
Isn't there a permission setting to enable assGMs modifying world settings?

**Comment by dev7355608** [comment]
@esheyw 

> Just to clarify: it preferentially returns real GMs, but will still fall back to assistants if there are no full GMs and non-zero assistants?

Correct.

> Because that is definitely improved behaviour IMO, but the fallback makes it false positive an 'can I update world settings' check if there are only Assistants logged in.

You need to test for the permission in this case: `user.can("SETTINGS_MODIFY")` for example.

 Also we added `Users#getDesignatedUser` and `User#isDesignated` (https://github.com/foundryvtt/foundryvtt/issues/11698) which allow you to get the designated user for an arbitrary condition. For example we use to define `activeGM`
```js
  get activeGM() {
    return this.getDesignatedUser(user => user.active && user.isGM);
  }
```
and in the `TeleportTokenRegionBehaviorType`
```js
  static #shouldTeleport(token, destination, user) {
    const userCanTeleport = (token.parent === destination.parent) || (user.can("TOKEN_CREATE") && user.can("TOKEN_DELETE"));
    if ( userCanTeleport ) return user.isSelf;
    return user.isDesignated(u => u.active && u.can("TOKEN_CREATE") && u.can("TOKEN_DELETE"));
  }
```
