### ISSUE TITLE
Bug: `HandlebarsApplicationMixin#_preFirstRender` can miss some preloadable templates

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#11672]
If a part specifies both `template` and `templates`, the `template` will not be preloaded because of this line:
```js
const partTemplates = part.templates ?? [part.template];
```
I'm not sure if this is technically outside the design of appv2 or not, but it's in use in the "wild" in the [dnd5e compendium browser](https://github.com/foundryvtt/dnd5e/blob/d3704554f9a1a539a1a3816742f3733c460f210a/module/applications/compendium-browser.mjs#L139).

**Comment by aaclayton** [comment]
@Fyorl mind taking this quick fix as part of your ongoing appv2 work.
