### ISSUE TITLE
Cannot extend existing wall segments with ctrl+click-drag

### ISSUE THREAD

**Issue by jmurrayufo** [foundryvtt/foundryvtt#11693]
### What happened?

When holding control and click-dragging off of an existing node I just move the node rather than placing a new wall off of that node about 80% of the time. Holding control after I have started to place a wall behaves as expected (each click places a node and allows me to continue). 

Of note:

- Tested in on my macbook, and holding apple+click-dragging behaves as expected and allows me to click-drag off of an existing wall node to place a new wall. 
- This issue has happened to me in the past, but went away without a clear cause when trying to reproduce the issue. 
- This issue didn't effect me two days ago as I built a full map with various "doors" and "windows" without an issue at all. 
- 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Select wall controls.
- Place any wall into scene.
- Press and hold left-ctrl key.
- Click and hold on a node of the placed wall.
- Drag away from wall.
- If above steps are repeated without ever releasing control, it will eventually work.

### What core version are you reporting this for?

Version 12 Stable, Build 331

### Relevant log output

```shell
No relevant  console log output is seen while interacting with the walls. Clearly my console log and doing full reproduction steps results in an empty log.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by jmurrayufo** [comment]
I have no idea if this is important to the bug but I have noticed a specific behavior with the cursor. 

Uploaded a video example here: https://youtu.be/SjJVPIEYct0

- 0:08: Placed a wall.
- 0:12: Held down control key, moved to node, dragged away to extend a new wall. Notice how the cursor is an index finger. 
- 0:13 After letting go of the node, the mouse changes to an arrow cursor. Importantly I *do not* move the mouse before clicking to place a new wall. If I had just moved the mouse without clicking, the cursor changes back to a finger. 

Unsure if this behavior matters, but I cannot start a new wall segment with ctrl held while it's showing a finger and have it start the wall, it will instead just move the node.

**Comment by jmurrayufo** [comment]
Update: I would recommend flagging this as "Do Not Fix". 

I own a VIRPL brand HOTAS setup. When we unplug both the joystick and the throttle, this bug goes away. VIRPL doesn't use any driver software that I have to keep installed, they are just normal joysticks exposed to windows' default driver stack. Unplugging them, and waiting about 10 seconds makes this bug go away. Plugging it back in instantly

**Comment by aaclayton** [comment]
Strange one!
