### ISSUE TITLE
Changing a heading to paragraph in journals doesnt work.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#11692]
### What happened?

when you are using the journals and you want to change a heading back to paragraph you cant do it. and its a behaviour youd expect it to do.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

creating a heading line or subheading line. 

click the button to change said heading back to paragraph. 

and it wont change. 

the only way to do that is to delete. 

i spent a long time trying to figure this out as to why it wasnt functioning in the way youd expect.

### What core version are you reporting this for?

version 12.331

### Relevant log output

```shell
no log output because its a core behaviour and expected of core.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Doesn't it work to un-select the header style in the dropdown?

**Comment by ThingsCouldGetDicey** [comment]
> Doesn't it work to un-select the header style in the dropdown?

if you use the header style drop down and change back to paragraph it will not go back to paragraph. the only way to delete the header line is with delete rather than the workflow i wanted which is replace with paragraph.

let me know if that makes sense.

1. chooser header.
2. change header with drop down to paragraph
3. it doesnt change.

**Comment by ThingsCouldGetDicey** [comment]
> I am able to remove a header style by clicking on the header style again to turn it off. This is working just fine in my case. Are you using any modules which could be interfering with text editor behavior?

i reported it without modules on.

**Comment by aaclayton** [comment]
Not working for you?

https://github.com/user-attachments/assets/ccd3d14b-d526-4af9-911f-2768d5684905

**Comment by unsoluble** [comment]
What Nick is running into here is that you cannot _switch_ from a Heading style to the Paragraph style by simply choosing Paragraph from the dropdown; you need to disable the heading style by choosing it again. This appears to be how the editor is designed to work, but is admittedly a bit of an awkward workflow.

**Comment by ThingsCouldGetDicey** [comment]
> Not working for you?
> ProsemirrorHeaderReset.mp4

https://imgur.com/a/Zd40bS9
@aaclayton 
hope that illustrates the point

**Comment by aaclayton** [comment]
Hi @ThingsCouldGetDicey I do understand the friction you're running into, but please follow the steps of my linked GIF more closely. You need to toggle OFF the heading style, not click "paragraph". This is teh way that prosemirror currently works.
