### ISSUE TITLE
Game Settings no longer allows choices to be a function

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11707]
### What happened?

In V11, the choices field when calling `game.settings.register` was permitted to be a function which was invoked when the settings window was opened.

In V12, the same code does NOT invoke the function passed to the choices field.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Set up a module which attempts to set the choices field of a setting to a function call.
Observe that at no point is that function called (neither at game load, nor when the module settings window is opened).

### What core version are you reporting this for?

12.331

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Will look into it and see if I can add back compatibility. That being said there is a big push to move towards using a `DataField` or `DataModel` to define your setting type - and such fields *do* support choices (and choices that are functions).

**Comment by farling42** [comment]
I did follow advice from the Discord about using a DataField, but it seems a little strange to do `type: new foundry.data.fields.StringField({ choices: itemCompendiums })` within the call to game.settings.register

**Comment by aaclayton** [comment]
Why do you feel that way? You are declaring a data field that expresses the type of your setting. It seems quite natural to me?

**Comment by farling42** [comment]
I think I just needed to change my perspective of the "type" field, since it is already being assigned an actual type such as Boolean or String, so making it extensible to a complete DataField does indeed seem natural.
