### ISSUE TITLE
Chat cards in wrong order when lazy loaded

### ISSUE THREAD

**Issue by samgrieve** [foundryvtt/foundryvtt#11700]
### What happened?

If the chat log is scrolled up to find older messages some will appear in the incorrect order from when they were originally posted. Only occurs with older messages that required scrolling up to load.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open world with a long chat log. Scroll up to older messages that weren't load with the world.

### What core version are you reporting this for?

v12 build 331

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hey @Fyorl since you're working on the upgraded chat log in v13 could you take a look at this issue and see if its reproducible there?

**Comment by Fyorl** [comment]
Seems like a similar issue to #10951 but I wasn't able to reproduce this using the same test code in that issue and adding an artificial delay like Eber suggested.

**Comment by samgrieve** [comment]
I did speak with stwlam on the PF2E discord about this a week or so ago and they mentioned it was a "public secret" in terms or being a known issue heh.

I can reproduce it on my instance, but I guess there's nothing to show definitively that the chat cards were in a different order originally short of me screenshotting all cards and hoping they are the ones that change order later on.

Anything I might be able to grab that may help in terms of additional info?

**Comment by aaclayton** [comment]
@stwlam perhaps you have some missing context or level of understanding here?

**Comment by Fyorl** [comment]
The issue remains quite difficult to reproduce, but we have determined some circumstances under which it could theoretically happen, and implemented a fix for such a scenario.
