### ISSUE TITLE
Consider using CodeMirror for the editor in `MacroConfig`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11713]
### User Experience

https://codemirror.net/

It sure would be swell!

**Comment by krbz999** [comment]
> It sure would be swell!

You're not wrong!

**Comment by stwlam** [comment]
![image](https://github.com/user-attachments/assets/bfa765f3-affb-4e93-84ca-3ff596e2aed8)

- Language support includes JS, JSON, and HTML
- Also allows for plain text (line numbers but no syntax highlighting
- Syntax error checking included for JS and JSON

Example usage:
```hbs
<code-mirror name="command" language="{{editorLang}}" aria-label="{{localize fields.command.label}}">
    {{~source.command~}}
</code-mirror>
```
