### ISSUE TITLE
Consider replacing raw HTML prosemirror editor `textarea` with `code-mirror`

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11741]
When editing the raw HTML of a field, it would be helpful to have codemirror features like syntax highlighting to more clearly read my content.

**Comment by aaclayton** [comment]
Encourage @stwlam and @Fyorl to compare notes and consider how we might make this happen. I agree it's the logical next step now that we have CodeMirror included.
