### ISSUE TITLE
[v13] Consider making ChatLog##renderBatch public API

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/foundryvtt#11744]
### User Experience

My module, [Scene Specific Messages](https://foundryvtt.com/packages/scenemessage), sorts messages by scene. When you are in a scene with no messages, or not enough messages to create a scrollbar, in the last 100 which are automatically rendered, the module needs to render (at the user's request) additional messages, in order to allow for scrollback. Please make this method public or add an alternative.

While this v13 change does not technically make the module unusable, it would make scrollback for sorted scenes impossible to recover without posting new messages (which defeats the purpose of wanting to view the scrollback).

Please revert this change and provide (or instruct me how to access) this functionality as it was in v12 :pray:

**Comment by aaclayton** [comment]
Tagging to @Fyorl for consideration!

**Comment by Fyorl** [comment]
Title needs adjusting because `_renderBatch` was never in a public state to be returned back to. It was always annotated `@private`.

**Comment by etiquettestartshere** [comment]
In v13, scrolling back (if there are enough messages to create a scrollbar) when some messages are hidden seems unreliable (this was not the case in v12). This method may be the only way to make the scrollback recoverable.

> Title needs adjusting because `_renderBatch` was never in a public state to be returned back to. It was always annotated `@private`.

Yes, I should have said 'usable' state, as it was usable in v12. I am not familiar with the technical terminology around underscore methods. But I see no reason why this should not be available via API in v13 by the same token.
