### ISSUE TITLE
Redesign the functionality of default token settings to restrict to the subset of attributes which we can reliably enforce a user-defined preference. Support defining those preferences per Actor type

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11758]
## Original Submitted Request
Default visibility of name and attribute bars, disposition, actor data linking, vision enabling, and the new token shape all are things that seem to me as valid for defining by system outside of JS or attempting to setup Foundry's default token settings config without ruining user customization of it.

Either allow these in system.json or some way to provide them via some API.

Besides overriding Actor#_preCreate and TokenDocument#_preCreate and filling in undefined things, I don't think there's anything even remotely reliable way to do this right now that doesn't override user configuration.

**Comment by aaclayton** [comment]
I think we're going to do something in this arena in V13, we discussed as a team in our prioritization meeting, but it may not be exactly what you're asking for.
