### ISSUE TITLE
Scenes fail to render on firefox

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11759]
Originally reported by [boltsj](https://discord.com/channels/170995199584108546/1296292044011995136/1297969195681845330)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Fedora Atomic 40, Firefox
**Short Description of bug**: Scenes fail to render on firefox (possibly linux specific)
**Simple steps to reproduce the bug**: 
1. Create a new world
2. Create a new scene
3. Activate or view the new scene
4. See "Failed drawing visibility canvas group: Fog of War pixels extraction failed. Fog of War pixels extraction failed" error notification and the scene does not load.

**Support Details**:
```
Foundry Virtual Tabletop: Version 13 Prototype 1, 13.332
Game System: dnd5e, 4.0.4
Active Modules: 0
Performance Mode: 2

OS: Linux x86_64
Client: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
GPU: Radeon R9 200 Series, or similar
Max Texture Size: 16384

No viewed scene
Actors: 1 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 13 | Chat Messages: 2

World Scripts: None
```
This doesn't seem to affect the default scene created by the welcome tour on initial load, but switching to it causes the error and manually created scenes cause the error on initial load

**Screenshots and/or console errors**:
![image](https://github.com/user-attachments/assets/6f70f5fe-8812-412e-bda0-53b402c91422)

**Comment by aaclayton** [comment]
@dev7355608 any perspective on this one?
