### ISSUE TITLE
Various Documentation errors in 12.331

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11764]
- Now that Foundry is using templates, `Collection` should just be `Collection<T>` instead of `Collection<string, T>`
- The type `BasseEffectSourceOptions` has a typo with an extra s in `resources/app/client-esm/canvas/sources/base-effect-source.mjs`
- Static methods can't use `template` properties, e.g. `BaseEffectSource.defaultData`
- The type definition of `BaseEffectSource#initialize` references `options.behaviors` but never actually references or uses that object.
- RenderedEffectSource refers to `VisionMode.LIGHTING_LEVELS` multiple times when that should be referring to `CONST.LIGHTING_LEVELS`
- `PointEffectSourceMixin` fails to supply its internal properties to the generated docs as well as any generated types
- `PointVisionSource._brightLightingLevel` mis-types the return as `string` instead of `number`
- The second parameter of `PointVisionSource#_updateVisionModeUniforms` is typed as an array, but it should be a Record as seen by the use of `const [uniform, value] of vmUniforms`
- `CameraPopoutAppWrapper#_onResize` is a no-op.
- `EnrichmentAnchorOptions` in `TextEditor` uses `@param` instead of `@property` causing the property definitions to fail
- The `callback` parameter for SearchFilter is typed as `Function`; a more specific type should be provided to list the arguments and expected return value (void)
- `Game#toggleCharacterSheet` can also return `ActorSheetV2`
- `ActorSheetV2#actor` is typed as `ClientDocument` instead of `Actor`
- `foundry.dice.terms.DiceTerm#countEven` and `foundry.dice.terms.DiceTerm#countOdd` take in a modifier argument but goes unused in the function itself.
- `static fragmentShader` is not marked `@override` or `@inheritdoc` in the following classes:
  - `VoidFilter`
  - `BewitchingWaveIlluminationShader`
  - `BewitchingWaveColorationShader`
  - `FlameIlluminationShader`
  - `FlameColorationShader`
  - `GhostLightIlluminationShader`
  - `GhostLightColorationShader`
  - `PulseIlluminationShader`
  - `PulseColorationShader`
  - `RoilingDarknessShader`
  - `SirenColorationShader`
  - `SirenIlluminationShader`
  - `SmokePatchColorationShader`
  - `SmokePatchIlluminationShader`
  - `SunburstIlluminationShader`
  - `SunburstColorationShader`
  - `TorchIlluminationShader`
  - `TorchColorationShader`
  - `VortexIlluminationShader`
  - `WaveIlluminationShader`
  - `WaveColorationShader`
- `AdaptiveIllunimationShader.EXPOSURE` is not marked `@override`
- `VisionMaskFilter#enabled` is a getter that overrides a `PIXI.Filter` property (vscode is wrong about how far back it goes): https://i.imgur.com/HxwBxqk.png
- The type `ShaderTechnique` in `client\pixi\webgl\shaders\lighting\base-lighting.js` types several properties as `|undefined` without marking them as optional with `[]`
- `BaseSamplerShader.batchDefaultUniforms` is set to `{}` and typed as `object`. However all three subclasses that override it (with inconsistent use of `@override` *or* `@inheritDoc`) supply a method with a single `maxTex` argument.

**Comment by aaclayton** [comment]
Hi @JPMeehan - things are changing dramatically here in V13 because all these classes you mention are moving to ESM which changes the way they are documented. Please re-file any reports like this in the future with V13 as the relevant baseline.

**Comment by JPMeehan** [comment]
> Hi @JPMeehan - things are changing dramatically here in V13 because all these classes you mention are moving to ESM which changes the way they are documented. Please re-file any reports like this in the future with V13 as the relevant baseline.

Looks like there's only one of these that needs adjustment and that's just for referencing a file path; many of these classes were already migrated to ESM in v12, e.g. the Sources. Do you still want a new ticket?

**Comment by JPMeehan** [comment]
I made a fresh ticket in #11768
