### ISSUE TITLE
Trapezoid tokens on a hex grids can change to square shape

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11760]
Originally reported by [kitcat](https://discord.com/channels/170995199584108546/1296292044011995136/1298662096476835891)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: not relevant
**Short Description of bug**:Trapezoid tokens on a Hex Rows grid fall back to square shape when width is smaller than height, and circular ones fall back to it when width is less than or equal half the height. Neither one seems to have an issue rendering when the width and height are swapped however. 

Hex Rows grids have the same issue, but width/height threshholds are swapped.

**Simple steps to reproduce the bug**: Set token dimensions to one of the described/screenshotted sizes on a grid set to Hexagonal Rows - Odd

**Screenshots and/or console errors**:
![image1](https://github.com/user-attachments/assets/aa8c2f45-70b7-400e-99a3-86ad96eb5119)
![image2](https://github.com/user-attachments/assets/424594a0-911e-4b63-b1e3-3c5ef7f2b48b)
![image3](https://github.com/user-attachments/assets/08b97a17-5ca9-4173-b642-294b0d4351f5)
![image4](https://github.com/user-attachments/assets/2d419e2f-532b-4780-824e-bf07d7ec2a51)

**Comment by dev7355608** [comment]
That's normal. We have to fallback to the rectangle if it is not possible to create the hexagonal shape for the dimensions of the token.
