### ISSUE TITLE
Rationalize the way that Theme V2 color variables for text are used across themes

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11770]
Originally reported by [manaflower](https://discord.com/channels/170995199584108546/1184176415139184731/1295807800844353556)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: `<h4>` in light-theme is not very visible.
**Simple steps to reproduce the bug**: Use `<h4>` in light-theme
**Screenshots and/or console errors**:
![Screenshot 2024-10-15 205550](https://github.com/user-attachments/assets/750b495d-3e1b-4860-9b0f-e842b47b1eef)

**Comment by mkahvi** [comment]
This affects the other headers in light theme also, but h4 is the worst.

There's other contrast issues with light-theme besides those, so it might be good idea to check all that.
