### ISSUE TITLE
Consider improving the wording of the "key.split" error

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#11783]
### User Experience

Filing this request as a way to improve the user experience when the issue described in #11533 is encountered. Please see this ticket for additional details, including repro steps to generate this error message.

When Foundry fails to check for package updates, a message is displayed that could be improved.

_Current:_ "`key.split is not a function or its return value is not iterable`"
_Recommended:_ "`Failed to check for updates. Please try again later.`" (or something similar)

Some care will have to be taken to make sure that this more human-readable error message isn't returned in other cases where `key.split` might result in an error, perhaps.

**Comment by stwlam** [comment]
Handled by solution for #2977

**Comment by unsoluble** [comment]
Sure it's 2977? :)

**Comment by stwlam** [comment]
> Sure it's 2977? :)

![to-me](https://github.com/user-attachments/assets/97828262-b2ea-406e-8ae5-922356bf24d1)
