### ISSUE TITLE
Drag data containing sound data cannot be processed by playlists

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#11788]
### What happened?

Creating a drag data object as such:

```js
{
      type: "PlaylistSound",
      data: {
          path: "path/to/file.ogg",
          name: "mysound",
      },
}
```
cannot be processed when dropped into a playlist as the raw data does not have a playlist set.

In the _onDrop function

```js
  // Copying to another playlist.
    if ( otherPlaylistId !== playlist.id ) {
      const otherPlaylist = game.playlists.get(otherPlaylistId);
      return PlaylistSound.implementation.create(sound.toObject(), {parent: otherPlaylist});
    }
   ```
Simply adding a question mark `playlist?.id` will allow this kind of drop workflow to work

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See above

### What core version are you reporting this for?

V12 331

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Made a quick fix for next V13 release.
