### ISSUE TITLE
RenderFlag and PerceptionManager `alias` misalignment

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11790]
PerceptionManager defines several of its render flags with
```js
deprecated: { message, since, until, alias: true }
```

However, `RenderFlag##set` assumes that `alias` is a top level property.
```js
const cfg = this.flags[flag];
if ( !cfg ) throw new Error(`"${flag}" is not defined as a supported RenderFlag option.`);
if ( cfg.deprecated ) this.#logDreprecationWarning(flag);
if ( !cfg.alias ) this.add(flag);
 ```

Either `RenderFlag##set` needs to check for `cfg.deprecated.alias` or PerceptionManager needs to update its definitions (and the RenderFlag typedef needs to be updated)

**Comment by aaclayton** [comment]
@dev7355608 could you take a quick look at this one? Should be an easy fix one way or the other.
