### ISSUE TITLE
Add labels to `name` and `img` fields of documents

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11796]
### User Experience

While making a smaller system where a character sheet is of very little importance, I wanted to simply slap every property into `formGroup` and go on my merry way, but turns out that the `name` and `img` fields of an actor don't have a `label` property. So these were the only two I added properties for manually.

There already exists in localization the strings "Name" and "Image", which is what I used.

**Comment by aaclayton** [comment]
As we are going through and doing our AppV2 migrations for different documents we are adding localization to their full data models along the way. @stwlam has been leading this effort and can verify if we might have missed for some documents that are already migrated. In particular we probably need to go back and add this for the `Actor`.
