### ISSUE TITLE
Player accounts are not restricted from using pause through the socket

### ISSUE THREAD

**Issue by MiniGrief** [foundryvtt/foundryvtt#11806]
### What happened?

If you send the "pause" command via a socket, you will pause/unpause the game on other connected clients. The problem is that there is no verification if this is originating from an account with the correct permissions (such as a gamemaster).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open up a world on any game system (I tested D&D5e and Crucible).
2. Connect to this world with 2 clients. Permissions of the accounts used are irreverent.
3. On one of the clients, run this code: `game.socket.emit("pause", false)`
4. The game should now be unpaused on the client that did not run the code, while being paused on the client that did.
5. You can refresh on the client that ran the code to sync the pause state and the game will be unpaused for them too.

The same steps can be performed with changed false to true and the game will pause.

### What core version are you reporting this for?

Version 12 (build 331)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This was fixed in V13 as part of the work in https://github.com/foundryvtt/foundryvtt/issues/11142
