### ISSUE TITLE
User Permission Configuration editing pass

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#11859]
### User Experience

The User Permission Configuration app could use a few consistency and wording tweaks:

1. Remove "New" from a few labels where it's redundant:
   - `Create New Actors` —> `Create Actors`
   - `Create New Items` —> `Create Items`
   - `Create New Tokens` —> `Create Tokens`
   - `Upload New Files` —> `Upload Files`
2. Remove redundant "Allow":
   - `Allow Broadcasting Audio` —> `Broadcast Audio`
   - `Allow Broadcasting Video` —> `Broadcast Video`
3. Verb consistency with Pings:
   - `Canvas Pings` —> `Ping the Canvas`
4. Playlist clarification:
   - `Create Playlists` —> `Create and Control Playlists`
   - Allow users with this role to create new Playlists in the world. —> Allow users with this role to create new Playlists in the world, and to control Playlists that they own.
4. Minor typos and fixes:
   - `Create Measured Template` —> `Create Measured Templates`
   - Allow users with this role to create Note objects from Journal Entries which they own. —> Allow users with this role to create Note objects from Journal Entries that they own.
   - Display the position of the player's mouse cursor which illustrates where the user is looking on the canvas. —> Display the position of the user's mouse cursor to all other connected users.
   - Display measurement using the ruler tool to other connected players. —> Display measurements made with the Measure Distance tool to all other connected users.
   - Allow users with this role to use JavaScript macros that access the Foundry API, and to execute Script Behaviors in Scene Regions.
   - Allow users with this role whisper private messages that the Game Master cannot see. —> Allow users with this role to use the `/whisper` chat command to send private messages.

**Comment by aaclayton** [comment]
Good suggestions @unsoluble.

@stwlam could you take this set of suggestions and apply these improvements where possible?
