### ISSUE TITLE
have a way to handle images as documents and compendiums of images and shareable images on canvas.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#11857]
### User Experience

so the biggest issue i have with images is that i have to make them into journals for them to be shareable for the pcs to view. 

if you are running alot of pen and paper style games. 

there are a few ways of sharing images. 

make them journals
make them as scenes. 
make them as tokens. 

all of these seem tedious compared to being able to drag them and share them onto the canvas. 

so i propose a new document item of having images to be shareable. 

so we can have compendiums of purely just images. 

this way i could mass import images into a compendium. 

share the images directly to pcs. 

also if i want to drop images onto the canvas for the pcs to organise. the only way is to make them into tokens individually. rather than a systemic way of dragging any image to the canvas with default permissions being set for images being dragged onto a canvas. 

if you are using systems that are mostly pen and paper and you have hundreds of images to share to players and if you want your players to use those images to organise them on a scene. you have to spend hours with making every one of them as tokens. 

or make a journal which is tedious to make them into handouts. 

i propose that we have image compendiums, canvas shareable images and an image section on the right hand side amoungts the other document types. 

i know this wont be a priority but it would make games like call of cthulu/delta green/ style games easier to run. and would be less strain on game systems.

**Comment by aaclayton** [comment]
Thanks for taking the time to write this up, but this is not something we will be doing.
