### ISSUE TITLE
V13 - provide world-level setting for whether tokens rotate based on mvement

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11870]
### User Experience

It would be good to have a world-level setting to determine whether tokens are rotated when dragged across the canvas.

It is still required that players might want to manually rotate their token (ctrl + middle mouse button) separately from the V13 behaviour of rotating tokens to face the direction of movement.

**Comment by aaclayton** [comment]
This is already done as part of the Lock Rotation option of Prototype Token overrides.

**Comment by farling42** [comment]
It is sometimes useful to be able to rotate a token to indicate to the players a certain situation (e.g. prone - separately from the condition status icon).

A world-wide rotation switch would also make it easier for GMs to configure this without having to know anything about the rotation lock available on each individual token.

**Comment by aaclayton** [comment]
> It is sometimes useful to be able to rotate a token to indicate to the players a certain situation (e.g. prone - separately from the condition status icon).

I don't agree with the premise of this use case. This is exactly what active effects and statuses are for.

> A world-wide rotation switch would also make it easier for GMs to configure this without having to know anything about the rotation lock available on each individual token.

changing the world-level prototype token overrides does apply to all tokens. You do not have to apply it to each individual token. 

I don't think there is sufficient rationale to this request for us to prioritize it at this time.

**Comment by farling42** [comment]
All PF2 tokens are POG-style, so all PF2 games will require all scene tokens and prototype tokens to have their rotation disabled.

**Comment by aaclayton** [comment]
Cool. Here you go:

![image](https://github.com/user-attachments/assets/a5791ea6-e76a-4cac-aac8-5d4d1ca51ffd)

**Comment by farling42** [comment]
I'll leave it to others to add their own arguments. It does seem like a general-purpose capability has been repurposed into one specific use-case.

**Comment by alaustin0** [comment]
I spoke about this a little bit in the [discord](https://discord.com/channels/170995199584108546/1243227783082283140/1311032527263105074), but I would like to echo the sentiment here that I too would like to maintain the ability to manually rotate tokens.

The auto-rotate is admittedly super cool, and it looks great with top-down tokens, I actually really like it. AND I really like that there is a super convenient menu for overriding prototype token settings, including locking tokens which is fantastic for pog-style.

However, it still feels a bit bad to lose a feature that I had before. I go into the reasoning a bit more in the discord messages, but tl;dr is that rotating tokens was sometimes quite useful, and many times just FUN. I will miss it if it's gone, even if it's far from a "deal breaker" feature. And it's something that is going to affect a really large subset of users, so I don't think I will be the only one.

**Comment by krbz999** [comment]
> Quick edit: Would this not also have a pretty big impact on premium content?

Yes, but an incredibly minor one.

**Comment by Larkinabout** [comment]
I love to rotate my tokens to indicate dead and prone as well as apply the status effects. To me, it feels immersive, like they fell over. I'd like this functionality to remain available even though it's possibly not seen as the intended purpose of the token rotation.

**Comment by aaclayton** [comment]
We are not removing the standard ability to rotate tokens.

**Comment by Larkinabout** [comment]
> We are not removing the standard ability to rotate tokens.

For clarity, I meant while not also auto-rotating on movement, which I understand this issue is regarding.
