### ISSUE TITLE
Allow additional effect data to be specified when calling Actor.togggleStatusEffect

### ISSUE THREAD

**Issue by tposney** [foundryvtt/foundryvtt#11879]
### User Experience

I have occasion to want to create status effects on actors, but would like to be able to add additional data to the effect being created (in particular flags).

This would be an expansion of the existing behaviour which adds overlay as a flag, but would allow arbitrary date to be added to the created effect.
A new method signature might be
```js
async toggleStatusEffect(statusId, {active, overlay=false, flags}={})
```

**Comment by aaclayton** [comment]
For more advanced use cases, it is intended that you would simply create a fully custom `ActiveEffect`, for example:
```js
await ActiveEffect.create({
  name: "My Effect",
  statuses: [statusId],
  flags: {
    core: {
      overlay: true
    },
    myModule: {
      otherFlag: 1
    }
  }
}, {parent: actor});
```

**Comment by tposney** [comment]
Noted, but you lose the advantage of being able to check for existing status effects that toggleStatusEffect provides.

**Comment by aaclayton** [comment]
> Noted, but you lose the advantage of being able to check for existing status effects that toggleStatusEffect provides.

Sure, but you can do that easily in a single line of code.

In general, it's always going to be the case that you sacrifice some capabilities when using a convenience function. We have to draw boundaries around the scope of convenience somehow though. This is one of those boundaries.
