### ISSUE TITLE
Programmatically toggling uiConfig.colorScheme to light does not adjust style without reload

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11937]
Originally reported by [chaosos](https://discord.com/channels/170995199584108546/1296292044011995136/1311118626841165885)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows/Node/Chrome
**Short Description of bug**: Toggling uiConfig.colorScheme back to light does not appear to adjust styles until reload if changed programatically
**Simple steps to reproduce the bug**:
In v12 I wrote a macro to toggle the UI color scheme between light and dark for CSS testing purposes. I've updated it to the new setting structure, but it's only toggling one way - light to dark. Once the UI goes dark it won't switch back. It appears as though the entire live setting behavior is controlled solely by a listener on the select field.

```js
const uiConfig = game.settings.get('core', 'uiConfig');

uiConfig.colorScheme = uiConfig.colorScheme === 'light' ? 'dark' : 'light';
await game.settings.set('core', 'uiConfig', uiConfig)
this.update({ img: uiConfig.colorScheme === 'light' ? 'icons/sundries/lights/lantern-iron-yellow.webp' : 'icons/sundries/lights/lantern-steel.webp'});
```

**Screenshots and/or console errors**:
![ui-config](https://github.com/user-attachments/assets/d980b427-fe7f-488e-ad77-87c6db2a70fc)

**Comment by aaclayton** [comment]
Caused by #11924 which is caused by a flaw in the `dnd5e` system. Forwarding along.

**Comment by aaclayton** [comment]
Will mark as resolved once the upstream system bug is fixed.
