### ISSUE TITLE
`ChatLog` does not call a hook for its context options

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11943]
Originally reported by [ethaks](https://discord.com/channels/170995199584108546/1296292044011995136/1314981790426988574)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: — 
**Short Description of bug**: `ChatLog` does not call a hook for its context options (like e.g. `Players` does with `getUserContextOptions`).

**Comment by aaclayton** [comment]
@Fyorl related to new chat log behavior.
