### ISSUE TITLE
`ActiveEffectConfig` has typo in "scrollable" CSS class name

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11946]
Originally reported by [zhell9201](https://discord.com/channels/170995199584108546/1296292044011995136/1317997050029146173)

**Short Description of bug**: Wrong css class on AE config main tab (scollable instead of scrollable).
**Simple steps to reproduce the bug**: Gaze at AE config with eyeballs.
**Screenshots and/or console errors**:

**Comment by aaclayton** [comment]
@stwlam thought on this ... I'm not sure that the main tab of this form even needs or should have the scrollable class? Certainly we want the list of changes to be scrollable because it could be arbitrarily long, but the main tab is pretty finite in size.
