### ISSUE TITLE
Multiple `ApplicationV2` title bars difficult to mutually distinguish while in dark mode

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11961]
Originally reported by [manaflower](https://discord.com/channels/170995199584108546/1184176415139184731/1302940929757282354)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: AppV2 header is very indistinguishable in dark mode if you have multiple apps open, making it difficult or even impossible to see where the headers are compared to content of several apps.
**Screenshots and/or console errors**:
Here's also a screenshot with the window controls removed to make the problem more obvious since the controls are a crutch for finding the headers. You should NOT need to find the controls first to be able to tell that's a header.

There's 4 apps open in the screenshot btw, in case you can't see them either.

**Comment by aaclayton** [comment]
Don't see this as something we're going to change. It's really not that different than AppV1
