### ISSUE TITLE
Add strictness to `mergeObject` and `DataModel#updateSource` deletion keys which MUST pass `null` as their value in order to be honored.

### ISSUE THREAD

**Issue by LukeAbby** [foundryvtt/foundryvtt#11977]
In `mergeObject` the semantics of `"-=foo.bar"` means delete the entire key `foo`. i.e.
```js
foundry.utils.mergeObject({ foo: { bar: "xyz" } }, { "-=foo.bar": null }, { performDeletions: true })
```

Results in `{}`.

The appropriate way to delete the key `foo.bar` is either to nest the objects:
```js
foundry.utils.mergeObject({ foo: { bar: "xyz" } }, { "foo": { "-=bar": null } }, { performDeletions: true })
```

Or to write this:
```js
foundry.utils.mergeObject({ foo: { bar: "xyz" } }, { "foo.-=bar": null }, { performDeletions: true })
```

This is a probably accidental consequence of calling `expandObject` at depth 0 in `mergeObject`. This transforms `{ "-=foo.bar": null }` into `{ "-=foo": { bar: null } }`. Given that the value in a deletion key is ignored this results in `foo` being deleted.

I see three solutions:
1. Make `expandObject` itself aware of the semantics of `-=foo.bar`.
2. Make `mergeObject` specially handle the `-=` prefix.
3. Do nothing. Embrace the current semantics.

To change this would technically be breaking but given that `foo.-=bar` would presumably keep working this would likely be very minor. I imagine the number of authors who write `-=foo.bar` meaning "delete `foo`"` are very small.

Note: I do not have access to the implementation of #11273 but it may have a same issue such that `{ "==foo.bar": null }` means "override `foo` with `{ bar: null }`" instead of "override `foo.bar` with `null`".

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards

**Comment by aaclayton** [comment]
I don't view `{"-=foo.bar": null}` as a valid operation and it should probably throw an exception if that syntax is used.

**Comment by aaclayton** [comment]
Reframed the issue. The value of a deletion key must be `null` to be honored. Any other value (including an object) will throw an error.

**Comment by LukeAbby** [comment]
@aaclayton While I'm happy to see `"-=foo": { abc: 123 }` turn into an error I will admit I still find the syntax `-=foo.bar` to be much more intuitive than `foo.-=bar`. I'd be happy to open a new issue about this part of the issue specifically.

If you're strongly in favor of the current syntax would you at least consider emitting an error specific to the `-=foo.bar` case if you aren't already?

I think it should be as simple as:
```js
for (const key of Object.keys(data)) {
    if (key.startsWith("-=") && key.includes(".")) {
        let keyParts = key.split(".");
        keyParts[0] = keyParts[0].slice(2);
        keyParts[keyParts.length-1] += "-=";
        const correctKey = keyParts.join(".");
        throw new Error(`The key ${JSON.stringify(key)} is invalid. You likely meant ${JSON.stringify(correctKey}}`);
    }
}
```

**Comment by aaclayton** [comment]
@LukeAbby I do feel strongly about the syntax. Intuition here is subjective, for example what you feel is more intuitive, I feel is less intuitive. 

The error message that gets produced is fairly explicit that you must pass the value of `null` when applying a deletion key.

**Comment by LukeAbby** [comment]
@aaclayton  Glad to know it's explicit that you must pass null. I think that could still be confusing if you write `{ "-=foo.bar": null }` as that doesn't "feel" but I'm glad you made sure the error is clear. Thanks!
