### ISSUE TITLE
Develop Triggers System for Event Automation

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#151]
The event trigger system will allow you to define trigger areas in your world which activate upon certain firing conditions and have customizable events which occur when triggered. An example of using the event trigger system would be drawing a rectangle around a doorway which, when a player token passes through the trigger zone causes the game to pause and four hidden enemies to appear on the map, beginning a combat encounter. This framework will eventually support a wide range of both trigger types and triggered events as part of the core platform, but also ensure the system is extensible by mods who can use event triggers to define their own custom scripted interactions.

## Related Issues
- This work depends on #9772 which must be developed first.
- Token movement animations
- Scene transition animations

## Requirements
```fix
This issue is still being scoped and is not final.
```

## Data Model
- Implement an "Event Trigger" sub-type of Scene Region which contains specialized data to support event triggers specifically.
- TODO: identify data model requirements.

## UI/UX
- Implement a canvas layer for visualizing and interacting with active trigger regions.
- Implement a configuration sheet for an Event Trigger region which allows its data to be viewed and modified.

## API
- Provide a robust set of API methods for interacting with Event Triggers.
- Dispatch events (hooks?) which are generated at various points of the Event Trigger lifecycle.

**Comment by anathemamask** [comment]
User suggestion that may be related to triggers: 
ability to trigger macros from the canvas, similar to how map notes are placed.
