### ISSUE TITLE
Add distance modifier to ruler

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3191]
Originally in GitLab by @fohswe

Consider adding a way to increase and decrease the distance/movement cost for a given section of the ruler, to allow taking (for instance) difficult terrain into account. The proposed solution is generic to work for different systems, which might have several different distance modifiers.

Could work like this:
- The user invokes the ruler
- The user measures up to an area with difficult terrain (1x normal distance)
- When holding Ctrl+Shift and using mousewheel, the zoom is temporarily disabled and instead the ruler modifier is changed. The distance modifier increases to 2x (maybe by 0.25x increments)
- Releasing Shift but still holding Ctrl allows the user to measure 2x distance (ie movement cost) over the difficult terrain
- Still holding Ctrl, and pressing Shift again allows to decrease back to 1x distance for regular terrain

Pros of this movement modifier is that the user doesn't have to define different areas on a map as a certain terrain. It also allows for situations where a terrain + conditions work together to maybe impose 4x movement cost. Or the opposite.

**Comment by dev7355608** [comment]
I think we can close this. The Grid and Ruler API supports cost measurements now (#10474, #10525), which the system (or a module) can use to implement difficult terrain (as a Scene Region behavior).
