### ISSUE TITLE
Inconsistent support for drag modifiers

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3216]
Originally in GitLab by @Forien

## Case:

Dragging Scene (and probably any draggable) using different keys as modifiers (`Control`, `Alt`, `Shift`, `Command`).  
On various browsers and systems this results in different behaviour. 

## Keys by browsers:

|         	| Chrome 	| Firefox 	| Electron 	| macOS Electron 	|
|---------	|--------	|---------	|----------	|----------------	|
| Shift   	| ✗      	| ✓       	| ✗        	| ✗              	|
| Control 	| ✓      	| ✓       	| ✓        	| ✗***              	|
| Alt     	| ✓      	| ✓       	| ✓        	| ✓              	|
| Meta    	| ✓*     	| ✓*      	| ✓*       	| ✓**            	|

* \* on Windows it fires up start menu, but otherwise works
* \*\* on macOS Command works with draggables, if it's released before "dragend"/"drop" event
  * at least that's how it works with https://github.com/Forien/foundryvtt-forien-scene-navigator
* \*\*\* on macOS Control+Click defaults to right click, thus blocking other events

## The "Shift key paradox":

With `Shift` especially it's weird, because it seems to be issue related to Foundry VTT, but present only on Chromium browsers.
How `Shift+Drag` looks like in Foundry (first normal drag, then shift+drag, same behaviour in Electron and in Chrome):  
![](https://i.gyazo.com/fb788bf8de27e9879e962dfa5741c8b3.gif)

Same flow, FireFox:  
![](https://i.gyazo.com/3eb0d5cd71a0e3cd223bfe490785ff49.gif)

But why I think it's related more to FVTT? Because when I try it here, it works: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop

Below `shift+drag` using Chrome:  
![](https://i.gyazo.com/77c504f1b6b18f7f7d2a1711f6a8bcd6.gif)

**Comment by anathemamask** [comment]
I just spent 20m trying to identify what causes this behaviour and i've come to no conclusions other than variance in browser and OS hotkey usurpation. I don't _think_ there's anything we can do about this. I'm going to suggest that this is likely a #wontfix and move on.

**Comment by aaclayton** [comment]
I think there is a bug here worth fixing as it specifically relates to the Electron application where we have a greater level of control over OS-level events than we do in a browser environment. In theory, we should be able to guarantee that our keyboard modifiers could work properly in all Electron environments specifically.
