### ISSUE TITLE
Redesign the ApplicationV2 header buttons to collapse to a submenu in cases where the window is too narrow to display all of the buttons.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3273]
Originally in GitLab by @putt1

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/b6b8c67651a07fe891844f7302183789/hidden-close.png)

Notice how the close button is not visible anymore.

**Comment by aaclayton** [comment]
Originally in GitLab by @Forien

### From Discord's discussion:

I render different header buttons on Item's Sheet depending if it is unidentified or not, and when item is turned into identified, I would like the buttons to change as well. I know I can use jQuery for that.  
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/6c767e9c810eba736259ea67a3607c06/image.png)

I think that while it's good assumption to not re-render header on every `render()` call, it would be nice to be able to call `render(true, {renderButtons:true})` or maybe `render(true, {renderHeader:true})`. 

### Reasoning

Similar to Context Menus, where we can have `condition` callback that checks if context menu should contain given entry depending on circumstances, maybe systems and modules would like to show only certain header buttons depending on cirtumstances as well. And while it's possible to hack around to achieve this thing, I believe that with fast incrasing number of modules, properly exposed API calls are essential to keep application stable in the long run and to introduce standard for Modules to follow, hopefully increasing their stability in the process. 


Loosely linked to other suggestion: [Inject Header Buttons programmatically into Application class](https://gitlab.com/foundrynet/foundryvtt/-/issues/3144)

**Comment by aaclayton** [comment]
Request from @mclemente:

### User Experience

## Request 1
On `Application._renderOuter`, add a new hook that gets header buttons after `Application._getHeaderButtons` is called.

Alternatively, consider moving the `get${cls.name}HeaderButtons` hook out of `Application._getHeaderButtons`.

### Reasoning
There are lots of modules that add header buttons during the `render${cls.name}Application`, be it for not knowing there is a proper hook or because adding a button at that stage means the button will be added before buttons like "Sheet Config" and "Prototype Token" since the method is called at the Application class, before the subclasses can add their own.

This behavior means any dev that wants to add a button will move the core buttons to the right, which can be confusing to users since every new module might push the buttons further.

If there was another hook, developers who don't see their module's buttons as important as core buttons can push their buttons without breaking the pattern. As the alternative, the original hook could be called after all the subclasses' `_getHeaderButtons` methods were called.

## Request 2
Add a "hide labels of header buttons" to hide button labels, then turn the labels into a tooltip so the buttons keep their contextual information without taking as much space.

Alternatively or concurrently, add a  "tooltip" property for buttons so they can be set without a proper label and still have some contextual information about what the button is meant to do.

### Reasoning
It is possible to add so many buttons to the header that it pushes the X button outside of the title bar. And that doesn't require a lot of modules.

#### Example 1
Brazilian Portuguese localization, 6 modules shown, Compendium
![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/3d3dc28a-02fd-4cd0-be69-c494a53e76d3)
(Item Macro, Automated Animations, DAE twice, GM Notes, and Build-a-Bonus)

Note: DAE's button (Wrench) is longer than its English localization, but you can get a similar behavior by enabling Build-a-Bonus' label.

#### Example 2
English localization, 6 modules shown, Item Directory & Compendium.
![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/fcc7e456-43bd-46a3-862d-14b484959f36)

---

There are just 6 modules (although their dependencies bump the install number to 16). If someone opens an item like that, their only way to close it is to press ESC, which closes everything.

Also, can you spot the Sheet/Import buttons at a glance? If a user installs a module at a time, these buttons will keep moving left. Users will get used to it eventually, but still, should it be like that?

## About Cleaner Title Bar module
The general solution for this issue on the discord channels is clear: "use the Cleaner Title Bar module". While the module does its job well, it shouldn't become obligatory at such a small threshold of 6-16 modules.

I'd also raise that there is a case for users that probably use this without a cluttered header bar and just want to have the Sheet/Prototype Token/Close buttons not taking that much space, especially on systems with sheets that are smaller by default.

## Context
Original discussion: https://discord.com/channels/170995199584108546/811676497965613117/1171579058715369482

**Comment by Rabulias** [comment]
I would really like it if the core buttons (especially the Close button) would have priority to stay visible no matter how narrow the window or how many other buttons are in the header. A separate module subheader/submenu would be very nice.

**Comment by aaclayton** [comment]
Comment from @kristianserrano:

### User Experience

The header of an app window has limited space, and a lot of modules and systems compete for that real estate, often overcrowding it and causing core features to fall off or become concealed.

An easy solution for this would be to give application windows a menu bar among which would be a Tools into which modules can add menu items. This suggestion would be primarily for Documents and not every app window. It might look something like this.

- File (for Documents only)
  - Open (A list of World Documents of the same type)
  - Recent  (A list of recently opened World Documents of the same type)
  - Duplicate
  - Save as... (Duplicate with edited name and select which Folder)
- Edit
  - Sheet
  - Related registered settings from the system or modules
  - [Additional functional menu items from the system such as toggling Edit mode for 5e, Tweaks for SWADE, Prototype Tokens for Actors, etc.]
- Tools (Documents only)
  - Copy ID
  - Copy UUID
  - Send to console (for developers and users troubleshooting)
  - [Additional functional menu items from the system or modules such as Popout!]
- Window
  - Minimize/Collapse
  - Maximize
  - Keep on top
  - Close
- Help
  - About (if a Document, opens dialog with ID, UUID, and maybe Folder "location")
  - [Additional menu items from the system or modules that link to external URLs or Journal Entries for documentation/instructions or that open Tours]

I know a lot of these suggested menu items are technically new features. I don't mean for this issue to serve as a feature request for those; they're just added to illustrate what might be possible with a set of menus versus buttons.
