### ISSUE TITLE
Add missing localization support to Token Management and Prototyping interface

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3340]
Originally in GitLab by @michal.golaszewski

### Summary

Certain UI elements for managing tokens and prototyping tokens for an actor remain untranslatable.

This includes:
 - "Prototype Token" button at the top right of Actor window
 - Section names in the "token configuration" menu (Image/Position/Vision/Resources)
 - Contents of the drop down list allowing to choose whether and where to show token name, in the character section of token configuration window.
 - Placeholder text in the elevation text-field in the position panel. (Says "units")
 - Values of dropdown bars in the "Resources" section. Bar position (similarly to token name position), and the "None" option on the resource seletion dropdowns

#### Demonstration

Prototype Token in Actor window header

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/7cc20a5a6463474e61f47ce45fd24813/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/3ea7b3916e514151415db1a50c8c3c73/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/af5fcd2914937445dcdb2a1b91b00784/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/a0434d7e4c4531dde970c65df55ff9ab/image.png)

\[Examples come from my work-in-progress Polish localization. Texts subject to change.\]

**Comment by cswendrowski** [comment]
An audit of where we are 2 years later shows these are all now localized 👍
