### ISSUE TITLE
Add missing localization support for the Measurement Template Interfaces

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3341]
Originally in GitLab by @michal.golaszewski

### Summary

Virtually no contents of the following two template management windows has localization support.

This includes:
 - Template configuration window
 - Template deletion confirmation window

#### Demonstration

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/03ee87fa59ff493af152f20752e72a0e/image.png)

\[Example comes from my work-in-progress Polish localization. Texts subject to change.\]

**Comment by cswendrowski** [comment]
An audit of where we are 2 years later shows these are all now localized 👍
