### ISSUE TITLE
Add missing localization support for Drawing Tools UI

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3343]
Originally in GitLab by @michal.golaszewski

### Summary

Drawing tools contain UI sections that don't support localization

This includes:
 - Clear drawings popup window
 - Whole contents of the Drawing Confituration and Default Drawing Configuration windows

#### Demonstration

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/efe9a6b23072e3ec8425706368cbbd61/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/4e7491668b62da07da615a44aba52f2d/image.png)![image](https://gitlab.com/foundrynet/foundryvtt/uploads/f2a9148d50fbf8e3f46698285a0670f4/image.png)

\[Examples come from my work-in-progress Polish localization. Texts subject to change.\]

**Comment by cswendrowski** [comment]
An audit of where we are 2 years later shows these are all now localized 👍
