### ISSUE TITLE
Add missing localization support to Permission Management window

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3348]
Originally in GitLab by @michal.golaszewski

### Summary

Dropdown menu options in the players' entity permissions configuration option lack the option to be localized.

#### Demonstration

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/0241260692c841d6d2ca03fcb966ad73/image.png)

\[Example comes from my work-in-progress Polish localization. Texts subject to change.\]

**Comment by cswendrowski** [comment]
An audit of where we are 2 years later shows these are all now localized 👍
