### ISSUE TITLE
Detect the latest compatible version of a module/system instead of downloading the latest version released

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3382]
Originally in GitLab by @JiDW

### Feature Summary

Currently, as stated by Atropos on Discord, the installer will list and download the latest version of all modules and systems, even if they are not compatible with the Foundry Core version installed.  

I'd like to suggest a change to this behavior, and have the list filtered to show the latest compatible version with the currently installed Core version if it exist.

For this, we can use "minimumCoreVersion". The website already have all the informations available as it keeps in its database all the releases and manifest links.

### User Experience

The most basic version of this would be invisible for the user. It would show a compatible version and it would install it.  
A more advanced version could show that the currently listed version has a newer version for a newer Core version. It could be a "outdated" tag for example.

### Priority/Importance

I would say medium. Because of the growth of the module/system community, and the extended delay between alpha->beta->stable because of the end of the early access period, modders need to be able to test their modules/systems before a FVTT version is released to stable. For this, we currently have to make call for help in Discord for users to install a manifest link.

I think it would be important in order to increase the quality of modules and therefore decrease the risk of failed FVTT release because of a popular module not being properly tested in alpha/beta, like it happened before with the infamous setting-extender module.

**Comment by MrVauxs** [comment]
With each new major version coming out, this becomes an ever annoying gap in functionality for both developers and end-users when a dev supports both the new and previous Foundry version (ex. 11 and 12). Is this going to be worked on anytime soon?

**Comment by aaclayton** [comment]
> With each new major version coming out, this becomes an ever annoying gap in functionality for both developers and end-users when a dev supports both the new and previous Foundry version (ex. 11 and 12). Is this going to be worked on anytime soon?

We probably need to start by re-clarifying what this issue is actually about. The packages browser in the setup screen will filter for packages with a version that is compatible with the core version that is running. Installing a package from that list will install a compatible version. 

This issue (as originally framed in August 2020) is actually complete. So it should either be closed or re-framed to reflect a current friction point.

**Comment by MrVauxs** [comment]
I would say this issue has been only resolved halfway, or simply, in a way that solves the bare minimum problem. 

The issue was, and still is, about the problem of Foundry only using the _latest_ version of the package, instead of taking into account all versions of a package, opting to only look at the latest version, whether it is compatible or not. 

The **only** thing that has been solved is _stopping_ you from installing a version that is incompatible with your Foundry install. The underlying issue of it taking _the wrong package_ to begin with has not been.

**Comment by aaclayton** [comment]
Can you please share a specific narrative example that guides me through understanding the problem more clearly? I'm not getting it.

**Comment by MrVauxs** [comment]
> Can you please share a specific narrative example that guides me through understanding the problem more clearly? I'm not getting it.

The comment was prompted by a fellow module developer creating a V12-testing version of their module. It has been published on FoundryVTT's module listing as a V12-only version. [Module in question.](https://foundryvtt.com/packages/pf2e-toolbelt)

They are also providing updates to the V11 version of the module, updating both simultaneously, both versions having the same features, just different Foundry compatibilities.

**V11 users can no longer update the module.** The module manager simply checks the _latest_ (V12), notices its V12, and refuses to download. Even when there are available V11 versions. Updating from 2.4.4 to 2.4.5 is no longer possible. Foundry _wants_ you to update to 2.5.0 and seeing it cannot, does not update at all.

The warning missing a localization string does not help either.
![image](https://github.com/foundryvtt/foundryvtt/assets/32039708/e58c4132-f58c-4052-981a-d03bce45756a)

**Comment by aaclayton** [comment]
In a v11 environment:

## Initial Installation
For initial package install, the module browser detects that version `2.4.5` of this package is the compatible version with V11 and offers to install it:

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/dfdae30c-0752-4719-9e34-d1d39a27f1cc)

It installs successfully and correctly installs `2.4.5` because this installation is brokered through our website which knows the different available versions.

## Incremental Updates
Once the module is installed in a V11 environment - you are correct that attempting to update the module fails as you describe because the available update is incompatible with V11.

Why does this happen? Because the locally installed module declares its upstream manifest to be `"https://raw.githubusercontent.com/reonZ/pf2e-toolbelt/master/module.json"` which is version `2.5.0` which requires V12.

What could theoretically be done about this?

1. Either the module author could maintain two separate development tracks, where `master` remains V11 compatible until V12 is stable and v12 manifests are on a separate track.
2. We could force module update requests to route through our website instead of interfacing directly with the declared upstream manifest. 

Option 1 is immediately available as a possible solution. Option 2 would require a huge amount of dev work and fundamentally change the paradigm for how Foundry VTT modules are updated. That doesn't make it a bad thing, but it is difficult to prioritize. Option 2 is tracked here: https://github.com/foundryvtt/foundryvtt/issues/7547

**Comment by MrVauxs** [comment]
I was under the belief Option 2 has already been done given you could modify the manifest thru the website without changing the module data (in fact once suggested to me by a Foundry staff member back in V10-V11 debacle). 

I suppose this does not apply to incremental updates then?

**Comment by esheyw** [comment]
A final fallback of 'if the retrieved module is incompatible, see if there is a foundry-registered release newer than current local that is' would be a meaningful improvement to dev life around major version transitions, yea.
