### ISSUE TITLE
Provide a button in the header of an entity or embedded entity configuration sheet to copy the _id of the object being configured to the clipboard.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3917]
Imported from Gitlab

**Comment by Kariaudhanaur** [comment]
It seems it has been done in V10, but can this button be on the top left instead of top right ? to always be at the same position ?

**Comment by aaclayton** [comment]
Closing this issue as a duplicate. We are happy with the location of the button on the left side adjacent to the sheet title.
