### ISSUE TITLE
Certrain types of .webm animations fail to display

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#4034]
Originally in GitLab by @LorduFreeman

- An issue with webm encoding, it seems only webms encoded with either VP8 or VP9 4:2:0 display correctly in Foundry, while VP 4:2:2 and 4:4:4  encoding types do not display at all. (display mystery man as token and do not create a tile if dragged in)
- Both VP8 and VP9 4:2:0 loop, but VP8 encoded webm pixelerates for a short time when relooping (very obvious when viewed as placed tiles) - only VP9 4:2:0 displays without any issues.

Animated test tokens attached for all mentioned formats. All encoded using Adobe Media Encoder with a webm plugin, 2.5k VBR and Alpha Channel, all but one with 2 passes.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/668dd914238505b1a1f7d22500def2c6/test_token_images.zip)

**Comment by anathemamask** [comment]
Can confirm this is still occurring in v10. lich_VP9vbr422 does error in the same fashion. Reattached the original supplied zip below for testing purposes. I think this is rare enough that it doesn't need an immediate fix, but achieving some clarity as to the cause my be beneficial.
[test_token_images.zip](https://github.com/foundryvtt/foundryvtt/files/8997281/test_token_images.zip)

**Comment by Feu-Secret** [comment]
The issue could be one of the two:
1. The testing images are encoded with an outdated/bugged codec.
2. The browser is using an outdated/bugged codec.
FYI: my windows media 10 decoder, chrome, and edge can't read some of the files.

**Comment by dev7355608** [comment]
lich_VP9vbr422, lich_VP9vbr422no2pass, and lich_VP9vbr444 won't render (correctly) in Chrome/Firefox/... as @Feu-Secret said. 
 Also I'm unable to create vp9 yuva422p/yuva444p with ffmpeg:
> Encoder libvpx-vp9 [libvpx VP9]:
>    Supported pixel formats: yuv420p yuva420p yuv422p yuv440p yuv444p yuv420p10le yuv422p10le yuv440p10le yuv444p10le yuv420p12le yuv422p12le yuv440p12le yuv444p12le gbrp gbrp10le gbrp12le

> Incompatible pixel format 'yuva422p' for codec 'libvpx-vp9', auto-selecting format 'yuva420p'

The pixelation of the vp8 file on loop can be observed if viewed with Chrome/Firefox (right-click -> loop). It's also unrelated to PIXI and Foundry.

**Comment by aaclayton** [comment]
I'm going to close this as wontfix. We can use as a heuristic: if you can open a video file and it works properly in Chrome/Firefox it should work properly in Foundry VTT - otherwise we will treat it as an upstream issue.
