### ISSUE TITLE
Add localization support to Clear All Objects window

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#4482]
Originally in GitLab by @DemianWright

### Summary

None of the **Clear All Objects** windows use the translated entity type name.

### Location

- Sidebar > Measurement Controls > Clear Templates (button)
- Sidebar > Drawing Controls > Clear Drawings (button)
- Sidebar > Wall Controls > Clear Walls (button)
- Sidebar > Lighting Controls > Clear Lights (button)
- Sidebar > Ambient Sound Controls > Clear Sounds (button)
- Sidebar > Journal Notes > Clear Notes (button)

### Screenshot

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/7473aea6e630ef05347b35a47147d7d2/clear_templates.png)

**Comment by dev7355608** [comment]
This was fixed by #11427. Closing as duplicate.
