### ISSUE TITLE
Drawing text has insufficient padding to fully render certain fonts.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#4490]
Originally in GitLab by @atnoslen

Using module [Forien's Custom Fonts](https://github.com/Forien/foundryvtt-forien-custom-fonts), loaded a few script type fonts.  On some, the right edge is cut regardless the size of the bounding box.  This is using font `Dancing Script` from Google Fonts.

Dancing Script, Forien's Custom Fonts
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/61102bd892f10654c278ba60e72f9c2e/image.png)

When additionally using module [Better Text Drawing](https://github.com/ruipin/fvtt-better-text-drawings) this becomes more pronounced.

Dancing Script, Forien's Custom Fonts, Better Text Drawing
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/102654bf7524613113e2e41f83f8ab90/image.png)

Additional fonts show similar issues.

Marck Script, Forien's Custom Fonts, Better Text Drawing
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/4498e8ac7359bcfa9480bfbc822fa009/image.png)

Clicker Script, Forien's Custom Fonts, Better Text Drawing
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/6cce8201444f2aae3f5f627c19710dad/image.png)

As this occurs without `Better Text Drawing`, I assume this is more Foundry than a module issue.

**Comment by anathemamask** [comment]
@Fyorl --- Do current plans for font integrations in v10 account for or correct this?

**Comment by Fyorl** [comment]
> @Fyorl --- Do current plans for font integrations in v10 account for or correct this?

Is this a duplicate of #7150 (or vice-versa since that was created later)?

**Comment by aaclayton** [comment]
I'm a bit unsure of how to proceed here. We would need some way to programmatically determine how much padding a particular font requires. This might be something worth folding as optional metadata into the `fontDefinitions` object which @Fyorl has developed that could allow custom font registrations to define some non-standard amount of padding that should be used when they are rendered using `PIXI.Text`. Thoughts?

**Comment by Feu-Secret** [comment]
> From @Fyorl:
> 
> What happens if we universally set the padding to a larger amount? Does it make the gap between lines of text really large?

Gap between lines will be larger. But in this case we could reduce the `leading` to compensate (I *think* it will works).
