### ISSUE TITLE
Improve the experience of re-establishing a web socket connection in the event that the user has become disconnected from the game server.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#4770]
Originally in GitLab by @jdgcoop

In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 0.7.9
* Operating System: Windows 10 (But foundry is running on an Ubuntu Droplet running Portainer and Docker)
* How Are You Using Foundry: Hosted, MS Edge, updated to latest
* Which Game System: Observed in DnD 5e, FateX and Modular Fate
* Modules Enabled?: Yes; none seem relevant to this.

### Issue Description

If I leave foundry open and running for a while (an hour at least), I've noticed that I can return, and everything looks like it should work, but, none of the file upload functions work, and there's no error message.  If I refresh instead of reloading the game it takes me to the login screen, but the gamemaster account is greyed out, if I refresh again I can log in.

I wasn't able to get a console output, but this has happened enough will try.  I checked the list here and didn't see a matching entry so figured best to speak up.  Thank you for a great VTT.

**Comment by cs96and** [comment]
Are the any plans to improve the disconnection/reconnection experience in v10?

**Comment by aaclayton** [comment]
I'll add this to our milestone for scoping, thanks for the nudge.
