### ISSUE TITLE
Grid square highlighting for the measuring tool exhibits odd selection choices of squares

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt#4892]
(Issue originated from Cora)

The measurement tool often highlights squares in an unexpected manner.
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/1e43d6faa20174774cc2bc2a49fcc7a3/grid-highlighting-1.png)
Here the blue squares should be highlighted, not the pink ones, since while the line does touch one, it actually passes through another. The line is symmetrical but the highlighting isn't. If touching a corner is enough to highlight bottom right, then top left should highlight too.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/1d8e0121b0fe090138431bdf2065331f/grid-highlighting-2.png)
This is another example of square highlighting that is seemingly not correct.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/2abe9fae04c9ce5a9377be0a9161e9be/grid-highlighting-3.png)
For longer distance measurements this tends to be less of an issue.

**Comment by dev7355608** [comment]
This was fixed in V12.
