### ISSUE TITLE
Swap functions of "Save" and "Save Entry" buttons in journal editor.

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt#4894]
Saving Journal Entries using lower “Save Entry” saves but doesn’t close editor. When editing a journal entry, if you use the Save Entry button with the quill, it will save the journal but will not close out the editor and remove the text formatting bar. If you use the formatting bar save icon, however, it saves and closes the editor ui.

Per Atropos: Swapping this function is planned. The “Save” button in the editor should save without closing TinyMCE while the “Save” at the bottom should save and close TinyMCE.

**Comment by aaclayton** [comment]
Related to finalization of ProseMirror interface. Feel free to close this if we aren't making any changes here.

**Comment by Fyorl** [comment]
The journal page editor now always opens in the 'active' state and the editor is no longer destroyed when the save button is clicked (either in TinyMCE or ProseMirror), so there's no different between the functioning of the 'Save Entry' vs. editor's save button anymore.
