### ISSUE TITLE
Migrate the technology used for data persistence from NEDB to ClassicLevel.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5065]
# Context
Since early development Foundry VTT has used the `nedb` package (https://github.com/louischatriot/nedb) to provide an engine for file-system persistence of document data structures.

Unfortunately nedb is no longer maintained and now has some active security issues (https://github.com/louischatriot/nedb/issues/675) which do not currently impact the Foundry VTT use case, but highlight the risks of relying upon an essential package that is no longer maintained.

As part of ongoing investment to improve our infrastructure we are, in Version 11, migrating away from NEDB and adopting 
ClassicLevel (<https://github.com/Level/classic-level>) as the new backend technology that Foundry Virtual Tabletop uses for data persistence. ClassicLevel is a highly optimized key/value store which provides local filesystem persistance using high-performance C++ bindings. You can read more about the Level ecosystem of persistence technologies here: <https://github.com/Level/community#faq>

Some of the key features of ClassicLevel include:

* Key/value storage. Records are highly optimized for retrieval by ID, but querying records by their contained values requires iteration.
* Data is compressed and stored in binary format. This means that database files are no longer human readable.
* The database can be partitioned using Sublevels. This allows for flexibility and performance gains in managing hierarchical data structures.
* Data is still stored locally in an operating system agnostic and transportable format.

---------------------------------

# Benchmarking and Comparison
This section outlines some benchmarking results which explain the performance differences of ClassicLevel vs. NEDB.

## File Size
The database files used by ClassicLevel will generally be larger than their NEDB counterparts when those NEDB datastores are fully compacted. The difference in disk utilization can be reversed, however, during active server use where NEDB writes incremental updates using append-only mode which causes database files to grow in size during use until they are periodically compacted to collapse the transaction history.

An example file size comparison for a fairly large world containing numerous documents:

* **NEDB (Fully Compacted)**: `35.2MB` across all datastores
* **NEDB (Active Use)**: `46.2MB` across all datastores
* **ClassicLevel**: `38.5MB` across all datastores (9.4% larger vs. "NEDB fully compacted", 20% smaller vs. "NEDB active use")

**Important Note**: During the testing phases before V11 stable, when a NEDB file is automatically migrated to a ClassicLevel database we do not delete the prior NEDB datastore. This allows for easier testing and recovery of data if something goes wrong with the migration. As a result, during these testing phases, the overall filesize for Worlds and other Packages will be larger than before. Once we feel this technology is stable and we can confidently delete the prior NEDB datastores after migration, the total file size for packages will decrease.

## Document Write Performance
Updating documents can be faster in ClassicLevel, although performance is comparable in this case. One advantage of ClassicLevel for Document writes is that the amount of data written to disk is reduced due to our use of sublevels. For example, making an update to an Actor document only writes the record of the actor itself excluding its embedded Item and ActiveEffect documents. Consider this example of changing the "Strength" score of an actor many times:

```js
const a = game.actors.get("Ep8XOVwvhXlDd0Yu")
const fn = async i => {
  const d = i % 2 === 0 ? 1 : -1;
  const v = a.system.abilities.str.value + d;
  await a.update({"system.abilities.str.value": v});
}
await foundry.utils.benchmark(fn, 1000);
```

* **NEDB**: 1000 iterations | 45335.2ms | 45.3352ms per
* **ClassicLevel**: 1000 iterations | 38978.7ms | 38.98ms per (14.0% faster)

## Embedded Document Write Performance
Similarly, updating embedded documents can be faster in ClassicLevel. In NEDB an update to an embeded document required the entire document to be re-written to disk. This was most costly in the case of Scenes where, for example, updating a Token position would require the entire Scene to be re-written (including all other embedded documents like Walls, Lights, etc...). Using the sublevel approach of ClassicLevel, modifications to an embedded document can be made directly without impacting any other Document in the same embedded collection. Consider this example of moving a Token position back and forth within a Scene:

```js
const scene = game.scenes.get("4V93BfPX6MzFkfsZ");
const token = scene.tokens.get("y26N5jU91k5Ut68B");
const size = canvas.dimensions.size;
const fn = async i => {
  const d = i % 2 === 0 ? size : -size;
  await token.update({x: token.x + d});
}
await foundry.utils.benchmark(fn, 1000);
```

* **NEDB**: 1000 iterations | 30795.6ms | 30.7956ms per
* **ClassicLevel**: 1000 iterations | 27135.6ms | 27.1356ms per (11.9% faster)

---------------------------------

# Frequently Asked Questions

> Q: What happens to my Worlds? 

When a World is loaded for the first time in V11, its existing NEDB files (document collections and world-level compendium packs) are automatically migrated to store their data in ClassicLevel database format. These migrated databases are then used for all further operations. This does not require any action from the user. 

> Q: What happens for Modules and Systems and the Compendium packs they provide?

Similarly to the behavior of Worlds, when a compendium pack is first loaded that is provided in pre-existing NEDB format that compendium pack is migrated as a one-time operation to a ClassicLevel database with a file path that places it as a sibling to the prior NEDB file. Existing Modules and Systems that provide compendium packs do not need to make any change in order for those compendium packs to continue working.

* Package developers who wish to release updates which jointly support both V11 and older Foundry VTT versions should continue to provide NEDB files.
* Package developers who wish to release updates that only support V11 and onwards may provide compendium packs directly in ClassicLevel format.

We plan to provide some build tools and documentation to assist developers with migrating existing packs from NEDB format into ClassicLevel or vice-versa.

> Q: What about build tools which manipulated the NEDB files?

Some packages, for example the `dnd5e` system use build tools to automate certain compendium management tasks. Once those packages are released for V11+ using only ClassicLevel databases these build tools will need to be redesigned to instead utilize the ClassicLevel API. We are evaluating the possibility of providing some core build tools for packing and unpacking compendium databases to and from a directory of human-readable JSON format.

> Q: Why not stay with a maintained branch of NEDB

As part of this migration we also considered other limitations that could be resolved by a shift in technology. Moving to ClassicLevel allows us to more easily solve related problems including:

1. Provide databases containing mixed document types like Adventures that contain Actors, Items, etc...
2. Allow Compendium packs which can define their own internal Folder hierarchy
3. Resolve lingering technical debt related to unlinked Tokens and their storage of differential Actor data

> Q: Is this a breaking change?

Generally speaking, no, however there are two specific use cases for which this change may be breaking.

We provide a `Compendium#getDocuments` API which uses the underlying `Document.database.get` method to query and retrieve documents from a source database like a compendium pack. Some modules and game systems use this API to perform queries to retrieve specific documents from a compendium pack. Since we are moving away from NEDB, the query language used by this operation also changes slightly. ClassicLevel itself is only a key/value store which does not have native support for querying records by their contained values, however we have implemend a query layer on top of ClassicLevel which preserves this functionality. The syntax is, however, slightly different. For example an operation which previously searched for all documents in an array of types using the NEDB query language now needs to update:
```diff
- await pack.getDocuments({type: {$in: ["weapon", "armor"]}});
+ await pack.getDocuments({type__in: ["weapon", "armor"]});
```
This use case is relatively niche and should only impact a minority of modules and game systems.

Secondly, some packages were previously using build tools to interact with NEDB files directly. This is addressed in a prior FAQ.

**Comment by kakaroto** [comment]
Seeing as this was scoped for v11 and is potentially being researched. I'd like to remind you of something I mentioned years ago about a limitation of nedb, the inability to open databases in read-only mode. 
Whatever replacement you create/find, it would be great if it could open db files that are read-only. I think packs from modules/systems should be opened read-only unless the user "unlocks" the pack, in which case, it would attempt to re-open it as read-write. 
Thanks for considering that possibility in your research.

**Comment by p4535992** [comment]
Just as knowledge only, this branch of the nedb project is still followed and updated https://github.com/seald/nedb for anyone interested.

**Comment by EternalDeiwos** [comment]
@aaclayton Congratulations on your move away from NeDB; this was long overdue.

Regarding the choice of LevelDB in particular, I see your reasons for choosing it, however there are many other embedded databases that provide similar features in addition to durability guarantees which LevelDB can only do with sequential writes, reducing it to a choice between performance and durability.

Which other embedded DBs did you consider?

**Comment by p4535992** [comment]
There is a discord channel for dicussion on the v11 prototype is better if you use that, But I can tell you that in addition to leveldb they tried several 4 or 5 if I'm not mistaken .
