### ISSUE TITLE
Immediately evaluated inline rolls in chat messages do not store the roll result in the persisted document, resulting in different results for each player.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#5292]
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/1f392fb782f4dfba13038ffd998a5552/image.png)

Heyo. Macro rolls in brackets do not work on the server we play on anymore. They appear as different numbers for every user. We tested it without any modules and the issue is still there. And the messages with bracketed rolls get deleted after reloading as well. https://cdn.discordapp.com/attachments/834020419459481610/849741133633552414/unknown.png
https://cdn.discordapp.com/attachments/834020419459481610/849742467871014942/unknown.png
https://cdn.discordapp.com/attachments/834020419459481610/849741035261394994/unknown.png

https://discord.com/channels/170995199584108546/848968607526551592/849765258297737217

**Comment by unsoluble** [comment]
Hey guess what, this one's back in v10.
