### ISSUE TITLE
Allow the use of path-style for S3 objects

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5296]
Originally in GitLab by @ElvisPereira

I tried setting up the S3 integration in Foundry in both a MinIO server and the Oracle Object storage, both seem to have a S3 compatible API, however Foundry are using the wrong URL when trying to load the objects, MinIO and Oracle use path-style by default, which means the URL should be `https://endpointURL/bucketName/object`, but Foundry are trying to load `https://bucketName.endpointURL/object` that will in turn fail.

Here is the S3 config files I tried (in Foundry v0.7.9 and v0.8.5)

oracle-s3.json

```json
{
    "region": "sa-saopaulo-1",
    "endpoint": "https://[oracleNamespace].compat.objectstorage.sa-saopaulo-1.oraclecloud.com",
    "accessKeyId": "myAccessKeyID",
    "secretAccessKey": "mySecretAccessKeyID",
    "s3ForcePathStyle": true,
    "signatureVersion": "v4"
}
```

minio-s3.json

```json
{
    "endpoint": "https://example.com",
    "accessKeyId": "minioUsername",
    "secretAccessKey": "minioPassword",
    "s3ForcePathStyle": true,
    "signatureVersion": "v4"
}
```

I found this old issue foundrynet/foundryvtt#3741, the first URL that you mention in your last response should work with MinIO and Oracle, but doesn't seem to be working in more recent versions of Foundry.

**Comment by Fyorl** [comment]
An update on the resolution to this: The `s3ForcePathStyle` option has been renamed to `forcePathStyle` in (I assume) v3 of the AWS SDK.
