### ISSUE TITLE
Allow token#actor#uuid for un-linked Tokens to return a string which can recover the synthetic Actor itself rather than simply providing the TokenDocument which governs it.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5381]
Originally in GitLab by @dumbmuscle

### Environment Details

* Foundry VTT Version: 0.8.6
* Operating System: Windows
* How Are You Using Foundry: Chrome
* Which Game System: Dnd5e
* Modules Enabled?: no

### Issue Description

As stated in the title.  For token.actor of an unlinked token, it's UUID is the same as that of the token.  This means that in this case (and as far as I can tell, only this case) fromUuid(document.uuid) does not return the original document.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/60ea76b317ad5ed4ee01d0683469143f/image.png)

My use case for this is in Bad Ideas Toolkit, where I need to be able to pass any Document (or EmbeddedDocument) over a socket and reconstruct that exact Document.  I can work around it for now, but it seems like the last remaining trap for working with unlinked tokens after the significant improvements in the refactor.  

The 0.7 behaviour was to return the UUID of the base actor, and this is still a significant improvement over that!

(My workaround is to detect this case and add a ".Actor" to the UUID before sending it over, and then to pick that up on the other end when reconstructing the Document.  Some warning of the eventual implementation of this would be appreciated, so I can get my code fixing in early.)

**Comment by BadIdeasBureau** [comment]
Just a brief note that #7709 is somewhat related here, and (while I'm not expecting the current issue to happen in v10) if we do get a way to reference token.actor via a UUID(-ish thing), then at that point whatever fix is put in place for #7709 may want to be adjusted to take that into account (e.g. migrating old links to the new UUID format, and allowing any new links to token UUIDs to open the token's config sheet).

**Comment by aaclayton** [comment]
This may change depending on our solutions for #6892

**Comment by Fyorl** [comment]
The UUID returned by a synthetic Actor will now be of the form: `Scene.<scene-id>.Token.<token-id>.Actor.<actor-id>`

**Comment by tposney** [comment]
I've just tested in 11.293 with no modules enabled.
I created a new npc, dragged the actor to the canvas (confirmed it is unlinked) and the (with the token selected) did
_token.actor.uuid and get back ```Scene.<scene-id>.Token.<token-id>``` rather than the suggested ```Scene.<scene-id>.Token.<token-id>.Actor.<actor-id>```

For unlinked tokens for characters on the canvas, _token.actor.uuid always returns ```Actor.<actor-id>``` where the actor-id is the world actor's id. This also does not seem correct.

**Comment by aaclayton** [comment]
Hey @tposney - got an email notification about potentially some functionality here that isn't working properly, but it looks like your comment is no longer in this issue? Did you delete it as a misunderstanding, or is there an issue here for us to follow-up on?

**Comment by tposney** [comment]
I installed prototype v2 instead of development v2. It all works fine in dev v2 - apologies for the bone headed report.

**Comment by aaclayton** [comment]
No worries! Glad it's not an issue
