### ISSUE TITLE
Replace current mouse-focused event handlers in favour of Pointer Events

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#5511]
Replacing current mouse-based interaction handlers in favour of more usage of Pointer Events would have the following benefits:

- Improved interaction support for non-mouse based devices (trackpads, mobile, touchscreens)
- Provide an accessibility gain for users reliant on alternate control devices
- Provide increased support for mobile devices

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

# Workflows to support
* Placeable hovering (pens)
* Move tokens and application windows via dragging
* Double tap to open sheets
* Foundry UI reacts to taps and touches

# Work not being done in this issue
* Enabling gesture support, such as pinch to zoom and two-finger pan
* Enabling right-click workflows without mouse
* Making the UI nicer for touch / pen only

# Related issues
* https://github.com/foundryvtt/foundryvtt/issues/8633
* https://github.com/foundryvtt/foundryvtt/issues/8634
* https://github.com/foundryvtt/foundryvtt/issues/8635
* https://github.com/foundryvtt/foundryvtt/issues/8636

**Comment by cswendrowski** [comment]
For phase 1 of approaching this issue, we would like to create a translation layer that converts Pointer Events into Mouse Events. This approach is similar to what the TouchVTT module does today.

# High level design

## A new `PointerInteractionManager` extends `MouseInteractionManager` 

Short term, PointerInteractionManager would handle pointer events and fire them to the parent, emulating the less-dense MouseEvents of MouseInteractionManager.

Long term, the codebase would align on PointerEvents, emulation could be removed, and `MouseInteractionManager` could be removed.

## A new `TouchManager` exists

Like `MouseManager`, this class would be responsible for touch-specific logic, such as keeping track of current fingers for pinch-and-zoom workflows.

Short term, these workflows would be emulated as MouseEvents.

# Workflows to support

* Move tokens and application windows via dragging
* Long press for right click
* Pan and zoom canvas via ping-and-zoom workflow

# Tangent Enhancements

* Enlarge Canvas Tools buttons to make them easier to tap
* When a token you don't own is left-clicked, add it to list of targets
