### ISSUE TITLE
Bounding box of tokens on hex grid is square

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5622]
Originally in GitLab by @fyorl

Originally reported by Nick Coffin, PI#8616 https://discord.com/channels/170995199584108546/848968607526551592/863074355185319945
**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Mac OS 11.4, Self-Hosting, Chrome & node.js

**Short Description of bug:** Foundry 0.8.8 appears to use only the bounding rectangle to select tokens on a hex grid, leading to the wrong token being selected. This behavior led to a problematic combat with my group where the wrong tokens were targeted, moved, or removed from the combat. 

**Simple steps to reproduce the bug: **
Foundry 0.8.8: create a scene with a hex grid. Place two tokens in hexes directly next to one another so that their bounding rectangles overlap. Move your cursor from one token to the other. One of the tokens will be highlighted (and selected, if you click) while the cursor is actually over the other hex. See this movie of the behavior: 

https://youtu.be/lpNbscQoHvg

**Comment by Fyorl** [comment]
Closing in favour of #8243
