### ISSUE TITLE
Moving token on hex-grid sometimes results in token moving two hexes up, and not able to move down.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5631]
Originally in GitLab by @aMediocreDad

In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 0.8.8
* Operating System: Windows
* How Are You Using Foundry: Native and Node
* Which Game System: FBL, WFRP
* Modules Enabled?: No

### Issue Description

A user reported that when moving tokens using the arrow keys on a hex map (column even) they would occasionally see the token move two hexes up instead of one. 

Attempting to reproduce this in the same system (FBL) I found that moving a token around randomly for some time would eventually lead to certain areas on the scene where the token would not move down when the "down-arrow"-key was pressed, and would move two hexes up instead of one, when the "up-arrow"-key was pressed. This is localized to only certain (seemingly random places on the grid). See example video below (using wfrp with the same grid settings in order to verify it was not system specific):

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/fe51ccdc3fab51b9c7342c01f7e415bd/grid-issue.webm)

Note that in the video when the token is moving down it stops and hops up two hexes again. When it stops I am actually repeatedly pressing arrow-down, then pressing arrow-up once before repeating the process.

**Comment by anathemamask** [comment]
I believe this issue to be resolved based on work @Fyorl performed during latter part of V9 and into V10. If so, please close. If not, given recent developments regarding hex map movement @aaclayton was working on, should probably be scoped for resolution in V10.

**Comment by Fyorl** [comment]
Could definitely be related to the hex sizing issue that we addressed early in v10. Assigning to dev 2 so we can verify if it's fixed.

**Comment by aaclayton** [comment]
Not able to reproduce in current dev2 build. Closing as presumed fixed.
