### ISSUE TITLE
Standardize the convention used by all DocumentSheet#id attributes to use a combination of the class name and the Document UUID being displayed.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5652]
Originally in GitLab by @moo-man

As the WFRP4e system/modules utilizes the `keepId` creation option, I'm noticing issues when I'm trying to open both a world document and a pack document, I *presume* this is because both elements have the `#actor-{id}` id.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/b2694654508edfd7959d45f920bd02b3/image.png)

### Reproduction Steps
(New DnD5e world, no modules)
- Create an actor from the compendium with the `keepId` option set as true
- Open the actor sheet from the pack
- Attempt to open the world actor sheet (the opened sheet should change slightly, the inputs become active, but there's still an import button on the header)
- Close the sheet
- Further attempts to open the world actor sheet fail until refresh, throwing the above error.

Ideally I'd like to be able to open both sheets, but I'm not sure if there's issues with having a sheet id be `#actor-{id}-pack` or something similar.

**Comment by anathemamask** [comment]
@moo-man

Was this resolved to your satisfaction or should some API work be slated to address this?

**Comment by moo-man** [comment]
A system can work around it easily, but they shouldn't need to. Especially now that in V10 the Adventure document will likely increase the use of the `keepId` option, these conflicting sheet id errors may come up more often (Note I haven't actually tested this in V10 but I assume it has the same issue).

Regardless, core Foundry throws an error and needs a refresh when following the repro steps, not something a system should need to be modified to handle.

**Comment by aaclayton** [comment]
I agree that we need to expand the document ID paradigm to incorporate extra info in the case that we are rendering a document from a compendium pack.
