### ISSUE TITLE
Allow players to execute macros which are inside a compendium.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5702]
Originally in GitLab by @SalieriC

Not sure if it's a bug or a feature.

### Feature Summary

When players have a link to a macro which is inside a compendium, allow them to execute it by clicking the link.

### User Experience

Macros in compendiums can be placed as links in all sorts of text fields (journal entries, descriptions, etc.) using @Compendium[ID]{Title}. This creates a clickable link that executes the macro. This however is not true for all permission levels as some cannot execute macros which are in a compendium. This is somewhat confusing as one would assume that anyone with access to an ID (can view the compendium) can execute a macro using a link.

### Priority/Importance

Low.

**Comment by SalieriC** [comment]
This could be merged into #6823 as it's basically the same question and my stuff above is just giving some more context to it.
