### ISSUE TITLE
Deleting a game system causes worlds that use that system to claim the game system needs to be updated

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5726]
Originally in GitLab by @fyorl

Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/848968607526551592/876427322511720468

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Any p.sure  
**Short Description of bug:** Deleting a game system causes worlds that use that system to claim the game system needs to be updated.  
**Simple steps to reproduce the bug:** Install game system, create world for it, uninstall game system, check your worlds.  

It should say the game system is missing or needs to be installed, not that it's out of date.

**Comment by anathemamask** [comment]
A minor UI change that could be resolved as part of #5832

**Comment by mkahvi** [comment]
This seems to have been fixed in v10

![Screenshot 2022-09-08 093926](https://user-images.githubusercontent.com/8120158/189052274-45c4581f-9768-4781-9460-f80d33e40326.png)
