### ISSUE TITLE
Active Effect icons being displayed even when the effect is unavailable

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5945]
Originally in GitLab by @paulohsc

### Environment Details
* Foundry VTT: v0.8.9
* Game System: DnD5e v1.4.3

### Issue Description
Active Effect icons are being displayed even when the effect is unavailable, as exemplified in the image below.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/d639d4e8e50b92a9287a4b14ba5e601e/chrome_qWrIQJIsSs.jpg)

**Comment by anathemamask** [comment]
Does not appear to be the case in V9 with latest DND5e. Closing as non-repro.
