### ISSUE TITLE
Compendium documents can be cleared from cache even if their sheets are still open

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5968]
Originally in GitLab by @muBkH

### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: DnD5e
* Modules Enabled?: No

### Issue Description

1. Create compendium item, for this case Feature.
2. Open it.
3. Wait for approximately 5 minutes.
4. Try to change description and save.
5. Save will silently fail, look at console.

```
Error: The key ... does not exist in the CompendiumCollection Collection
```

**Comment by anathemamask** [comment]
This one has actually been around a while but I'm not sure if it's fair to classify it as a bug- it's more the case that this is how the compendium caching system currently functions. The cache is likely expiring before the edits are completed. 

It might make sense to add a refresh of the compendium cache to workflows that occur when editing inside compendium packs. 

 I'll @aaclayton to weigh in on this one in particular.

**Comment by aaclayton** [comment]
We could easily avoid expiring an entry from the cache if it has an actively rendered application.
