### ISSUE TITLE
Add a hook for Document#prepareData

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5973]
Originally in GitLab by @errational

Currently when a system or module performs activity within the `prepareData` method, there is no way for other modules to react to changes or read derived properties until a subsequent `update` or `render` hook is called.

It would be nice if there was a `prepareData` hook that could be listened to so modules can perform actions.

Preferably the hook would have the state of the `Document` before and after preparation for referencing changed/derived properties.

cc @florad

**Comment by FloRad** [comment]
As a note, what `swade` has done we've added the `swadeActorPrepareDerivedData` which is called at the end of the data preparation and passes the prepared actor as it's only parameter. We've had some great success with that.

**Comment by aaclayton** [comment]
I think that if a system wants to add such a hook to allow that it should be their choice, but I think interfering with document data preparation is outside of the scope of what a module should be doing.
