### ISSUE TITLE
Limitations of parenthetical dice terms, contained data, and flavor text

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6048]
Originally in GitLab by @CarlosFdez

In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

* Foundry VTT Version: V9 and V8
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: Any
* Modules Enabled?: Irrelevant

### Issue Description

In the comments of https://gitlab.com/foundrynet/foundryvtt/-/issues/5327, it was revealed that using dice pools for described dice (ex `{1d6+5}[fire,splash]`) is not the recommended way to use them, with parentheticals (ex `(1d6+5)[fire,splash]`) being recommended instead. However it turns out that any formula / dice data in any parenthetical data is lost when the roll is evaluated, making it not very useful as a replacement.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/7ddd5d8887a502d1bbb91638fe686b32/image.png)

Given the way it came up in the issue, I'm suspecting its a bug. Correct me if I'm wrong, but I think that if it weren't a bug, then {1d6+5}[fire,splash] would be the recommended way to do it instead.

**Comment by aaclayton** [comment]
Related issue: 

OS, Hosting, Browser (if applicable): Windows 10, self hosted, tested on the electron app and chrome.

Short Description of bug: Parenthesis inside of a roll formula errors out 

Simple steps to reproduce the bug: Simply roll the following formula: `/r {(1d10+3)*2,3*2}kh` and you will get the exact error. Removing the parens fixes the bug, but obviously the dice math won't be correct.

**Comment by ghost91-** [comment]
Regarding the most recent comment: Reproducing it is even simpler, even the following errors:
```
/r {(1)}
```

**Comment by Fyorl** [comment]
These issues (parentheticals inside pools, pools with flavour), have been resolved to the best of my knowledge and testing with the peggy parser in v12.
