### ISSUE TITLE
Ability to hook into Tinymce editor creation (to add customer event listeners)

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6190]
Originally in GitLab by @crnormand

### Feature Summary

The GURPS Game Aid for Foundry (https://foundryvtt.com/packages/gurps) allows the user to create buttons by just entering specifically formatted text, known as On-the-Fly formulas (for example `[Dodge]` or `[S:First Aid]` or `[R:Longbow]`).   When displaying the character sheets, chat log or journal entries, we hook into the display, searching for text of this format, and replacing it with an html element (that has appropriate CSS to make it look/work like a button).   

We are just now implementing drag and drop features for these On-the-Fly buttons, and I cannot hook into the Tinymce editor because the drop handler is hardcoded to a static method:

foundry.js (0.8.9) line 21268:

     window.addEventListener("drop", ev => this._onDropEditorData(ev, editor))

Where _onDropEditorData() is a static method that only recognizes compendium drops.

### User Experience

It would be nice if the user could drag and drop an On-the-Fly button into an open editor, and it reverts back to its original text (which is already part of the payload).

### Priority/Importance

Low priority.   It would be nice to be able to hook into the Tinymce editor creation so we could attach our own event listeners to the editor window object.

**Comment by Fyorl** [comment]
This is now possible with the custom enrichers implemented in #3146. Hooking into the ProseMirror editor's drop handler directly can also be accomplished by registering a plugin.
