### ISSUE TITLE
Modules that are activated as dependency are not checked for dependencies.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6274]
Originally in GitLab by @SalieriC

### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Windows (client); Linux (Pi OS; server)
* How Are You Using Foundry: Chromium
* Which Game System: SWADE
* Modules Enabled?: no

### Issue Description

When activating modules with dependencies, a dialogue is rendered asking to activate dependencies. However, if those modules have dependencies on their own, the user is not informed about them, neither are they activated automatically. In order to avoid problems, modules that are activated from the dependency dialogue should be checked for dependencies as well and prompt the same dialogue.

**Comment by mkahvi** [comment]
The slight inverse of this is also true, where if you disable a module, all dependencies get disabled even if other modules still depend on them. It should check that they aren't before disabling.
