### ISSUE TITLE
Consider an expanded Support report which lists all active modules and their versions

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6359]
Originally in GitLab by @iaguastalli

### Feature Summary

Related to https://gitlab.com/foundrynet/foundryvtt/-/issues/5434

The Support Details report has a lot of meaty technical information but most of it is probably more suited for Core bugfixing (client, gpu, texture sizes for example) rather than to help module developers find problems with their modules or broken interactions between other modules and theirs. It would be helpful to not only count the number of active modules, but also list them by name & version (and maybe manifest url just in case?).

When users click the Support button, the text on the window clearly conveys this report is a valuable tool for anyone giving support on any area, be it core issues, system issues or module issues. Many times modules crash with one another, so it would be valuable to have an exhaustive list of the acive modules to check against known cultrips or try to infer issues from multiple reports.

### User Experience

When users click the Support button, active modules are listed by name and version. Maybe include manifest URL in case there's some module release issue and a module has two versions with the same version string but coming from different locations? This whole option could also be toggleable with a checkbox to either show just active module count or full detail.

### Priority/Importance

> Probably low, but given we are on the very dawn of v9 as a stable version, it's always good to maximize bugfixing features in these needy times of modules breaking and/or modules that work individually without an update somehow cause issues to other modules.

**Comment by unsoluble** [comment]
Maybe too late for v11, but I'd love to bolster the support report with more details still, even if we don't go with a full-on "Full" version.

(db file sizes, active scene asset sizes, world scripts present, resolution scaling status, compendium document count, in particular)

**Comment by Norc** [comment]
Specifically, I would love to second adding the largest actual pixel size of an image in the scene (without scaling involved), specifically to easily compare easily against the Max Texture Size, since this is an issue that crops up frequently.

**Comment by Norc** [comment]
I would also like to break out the module aspect of this into a self-contained button in a separate repot in the Support and Issues tab. Combining it with the main Support Details report would make it unwieldy, and it really serves a separate purpose anyway (core troubleshooting versus module troubleshooting).
