### ISSUE TITLE
Consider adding `flatMap` and `some` to `Collection`

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6411]
Originally in GitLab by @stwlam

### Feature Summary

It would be marginally more convenient if a couple more `Array`-like methods were added to the `Collection` class. `every` being present but not its existential quantifier twin is a tad awkward for muscle memory, for example.

### User Experience

One can write `somecollection.flatMap` instead of `somecollection.contents.flatMap`, etc.

### Priority/Importance

Low enough that `somecollection.contents.flatMap` is the most that has to be done as a workaround.

**Comment by stwlam** [comment]
Aaayy, `some` is in!

**Comment by aaclayton** [comment]
I don't think we will add flatMap because it's a bit niche, but we did add some as you mention. Closing this one out.
