### ISSUE TITLE
The `ApplicationHeaderButton` interface should include an `aria-label` alongside any `tooltip` property

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6412]
Originally in GitLab by @stwlam

### Feature Summary

The `ApplicationHeaderButton` interface would benefit from having an optional `title` property, which would be used to set the title text in the resulting anchor element.

### User Experience
E.g.,
```js
{
  label: "Close", // Aside: this and a few others need localization
  class: "close",
  icon: "fas fa-times",
  title: "Save and close sheet", // New!
  onclick: () => this.close()
}
```

### Priority/Importance

Low but simple and beneficial enhancement

**Comment by Fyorl** [comment]
Amended the title to reflect our move to tooltips rather than `title` attributes in most cases. The `title` attribute can still be set with the same value.

**Comment by Fyorl** [comment]
From @mkhavi
> ### User Experience

Ability to define tooltips for header buttons would allow better explaining what the button is for in context, demystifying UI elements for players.

This currently requires additional hook on the app render to inject such.

**Comment by Fyorl** [comment]
From @geekswordsman
### Feature Summary

Currently header buttons added to an Application's headerButtons property do not support titles, which is necessary for proper a11y support.

### User Experience

For header buttons, this allows for icons only to be displayed and have the label, or longer text, shifted to the title on hover while also further enhancing Foundry's a11y support.

The default title can be set to the label, if no title is specified.

### Priority/Importance

Medium importance, for the a11y compliance.

**Comment by Fyorl** [comment]
Not sure when it was added but it seems that `ApplicationHeaderButton` already supports a `tooltip` property in v11 at least. I am re-framing this issue to also supply an `aria-label` alongside the `tooltip` in cases where the header button may want to omit a visible `label`.

**Comment by aaclayton** [comment]
This is no longer applicable in ApplicationV2 which uses a different approach for header controls. These App v2 controls always have a displayed `label` and does not use an anchor element.
