### ISSUE TITLE
[FEATURE REQUEST] Provide a configurable permission setting that could allow Users to delete Tokens for Actors which they own.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6488]
Originally in GitLab by @p4535992

### Feature Summary

There is a limitation that I believe is requested by several people, (at least I have found it essential on more than one occasion), the option of letting players cancel their tokens, (the ones they own ).

My request is to add this option in the user permissions settings (https://foundryvtt.com/article/users/), it would solve many use cases that require the presence of the GM for deletion.

### User Experience

Add a new option 'Delete Token' in the user permissions settings form (https://foundryvtt.com/article/users/)

### Priority/Importance

For my personal use case is 'high', but if no one else finds it useful, the priority can go down to 'very low'

**Comment by p4535992** [comment]
This ticket is been transfered here https://github.com/foundryvtt/foundryvtt/issues/7765 ? Can we close it ?
