### ISSUE TITLE
Add a 'How to Reset Your Admin Password' link to the admin password prompt

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#6505]
Originally in GitLab by @mattexdee

**Feature:** Add a link that sums up how to reset your admin password on the initial prompt when launching Foundry VTT.
**Priority:** Low

**Comment by cswendrowski** [comment]
![image](https://user-images.githubusercontent.com/15639841/179298193-eadc817c-a1c5-48a4-8432-c58de27beed1.png)
