### ISSUE TITLE
Allow players to execute macros using the GMs permissions.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6579]
Originally in GitLab by @SalieriC

### Feature Summary

Allow players of permission level assistant and lower to execute macros at their end using permissions as if they were at GM permission level. For safety reasons this should be a switch on the macro itself which is of permission level observer or lower and created by the GM to prevent players to mess up the world.

### User Experience

Right now some scripts are not viable as macros the GM may wish to allow players to execute. This includes such scripts that create actors or tokens (i.e. when summoning an ally) if the GM doesn't wish to grant players of their level permission to create actors or tokens, updating actors they do not own (i.e. casting enhancing spells on such actors) and many more. A switch to make a macro use the GM permission level to execute that could greatly improve the viability of such script macros. Of course there is a risk of players purposefully or accidentally setting up macros with malicious scripts. For that reason the switch should only be available for GMs and only for macros they created with owner permission or lower for all other players.

### Priority/Importance

This feature could greatly enhance the user experience for many players and GMs while others who don't use script macros with said functionality wouldn't benefit from it at all. For This reason I would gauge the priority as medium-low.

**Comment by p4535992** [comment]
[Advanced Macro](https://github.com/mclemente/fvtt-advanced-macros) can do that for now.
It would be perfect for the future to try to integrate the features of that module into the core.

**Comment by aaclayton** [comment]
Allowing players to execute macros with GM permission is the same thing as giving players GM permission. Thisis not something we would do.
