### ISSUE TITLE
Provide a performDeletions option to mergeObject to control whether it implements special '-=' prefixed delete instructions or ignores them

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#6582]
Originally in GitLab by @Fyorl

If you only want to use `mergeObject` to combine or override some data, you can't do so if the second object contains deletion instructions, as those deletion instructions get implemented rather than preserved.

For example:

```js
const myUpdate = {foo: 'bar'};
const additionalUpdates = getAdditionalUpdates(); // Returns an object {'-=bar': 'baz'}
const allUpdates = mergeObject(myUpdate, additionalUpdates, {inplace: false});
// We expect to send a combined object of {'foo': 'bar', '-=bar': 'baz'} to update() but instead
// we only send {'foo': 'bar'} as the additional update was consumed as part of the mergeObject call.
actor.update(allUpdates);
```

**Comment by aaclayton** [comment]
Originally in GitLab by @dev7355608

```js
foundry.utils.mergeObject({}, {"foo.-=bar": null})
// => { foo: {} }
```

**Comment by dev7355608** [comment]
This wasn't fixed:
```js
foundry.utils.mergeObject({}, {"foo.-=bar": null}, {performDeletions: true})
// => { foo: {} }
```

**Comment by aaclayton** [comment]
We did not implement behavior which eliminates the `foo` object. We implemented behavior which eliminates the `-=bar` key from the inner object. The difference is:
```js
foundry.utils.mergeObject({}, {"foo.-=bar": null}, {performDeletions: true}); // {foo: {}}
foundry.utils.mergeObject({}, {"foo.-=bar": null}, {performDeletions: false}); // {foo: {-=bar: null}}
```

**Comment by dev7355608** [comment]
> We did not implement behavior which eliminates the `foo` object.

Why not? It seems undesirable to me that `mergeObject` adds something to the object even though it was only instructed to delete a particular key.

**Comment by Fyorl** [comment]
You haven't instructed it to delete the `foo` key, only the `bar` key. The `foo` property is still merged. If you do not want that behaviour, there are options available:

```
mergeObject({}, {'-=foo.bar': null}, {performDeletions: true}); // {}
mergeObject({}, {'foo.-=bar': null}, {performDeletions: true, insertKeys: false}); // {}
```

**Comment by aaclayton** [comment]
It was instructed to delete the `bar` key from inside the `foo` object, not to delete the `foo` object. If you don't want `foo` to exist at all you should check whether it exists beforehand.

**Comment by dev7355608** [comment]
But with `insertKeys: false` I can't mix inserts and deletes:
```js
mergeObject({}, {"foo.-=bar": null, "a": 1}, {insertKeys: false, performDeletions: true}) // {}
```
Why would I need to instruct to delete something that doesn't exist? Even if I instruct to delete the `foo` key too, `mergeObject` produces different results depending on the order:
```js
mergeObject({}, {"-=foo": null, "foo.-=bar": null}, {performDeletions: true}) // { foo: {} }
mergeObject({}, {"foo.-=bar": null, "-=foo": null}, {performDeletions: true}) // {}
```

**Comment by Fyorl** [comment]
There is no way to express 'delete this key of this object but don't create the parent object if it doesn't exist, but also do insert objects that don't exist for keys that don't contain a key deletion expression'. And including support for such an expression was not the goal of this issue.

**Comment by dev7355608** [comment]
My original issue on this case was deleted and merged with this one. So I had to assume that this was a goal of this issue.
