### ISSUE TITLE
Importing scenes includes their navigation toggle state

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#6597]
Originally in GitLab by @mattexdee

* Foundry VTT Version: V9
* Operating System: Windows
* How Are You Using Foundry: Any
* Which Game System: DnD5E
* Modules Enabled?: No

### Issue Description
If scenes were exported to a compendium while available in the navigation bar they will appear in the navigation bar when they're imported. This did not occur in 0.8.9 and packs that were made in 0.8.9 do not exhibit this behavior in V9 so I _think_ this is a result of changes to exports in V9. I've noticed this issue when testing a number of creators new content packs. Here's a webm of it occurring:

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/c216137c014499013d996c193744c51a/navigation_toggled_on.webm)

**Comment by anathemamask** [comment]
I believe this was solved by #10610
