### ISSUE TITLE
Add on dropdown/select the associating images to each element for better user experience

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6653]
Originally in GitLab by @p4535992

### Feature Summary

Enrich the game in general by adding the possibility of associating images to each element to the classic dropdown / select html of the game.

![img](https://i.imgur.com/mWc03AY.png)

This library with MIT license is simple enough that it can be integrated without much effort if you are interested
[ms-Dropdown](https://github.com/marghoobsuleman/ms-Dropdown)

### User Experience

I find it particularly useful in the dropdown / select for the choice of actors and items, from token configuration ecc. but it can also be easily used in many other contexts.

### Priority/Importance

Very low

**Comment by anathemamask** [comment]
Due to the nature of conditions, variation in these dropdowns and what they might include, this sort of feature is something best implemented at the Game System or Module level and not something the core API should introduce.
