### ISSUE TITLE
Improve the error message when the check for external IP fails

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6654]
Originally in GitLab by @fohswe

Under some circumstances when the software fails to acquire an invitation link/external IP the field just shows "Unknown" and the refresh button is not visible.

For a particular user (https://discord.com/channels/170995199584108546/486930822465716249/938751426685976576) this was confusing. A restart of the app fixed the issue, presumably because the connectivity check didn't fail.

Perhaps the error message could specifically say the check failed, and suggest a course of action to the user. If possible, the refresh button should still be visible.

**Comment by anathemamask** [comment]
Suggested path for clarity is to raise a ui.notifications.error containing something like `Our IP detection service failed to identify your correct IP address or you are not currently connected to the internet.`
