### ISSUE TITLE
Wrong absPath in world.json may have caused issues.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6671]
Originally in GitLab by @watermelonwolverine

Hello,

I'm running FoundryVTT in two places:
- locally on a Windows machine to work on it
- remotely on a Linux server (Ubuntu 18.04) while playing

I sync those two using a plain bare git repo on said linux server.

The problem is very ddb-importer specific but the author of ddb-importer MrPrimate told me it's an issue with the foundry system. When ddb-importer creates its compendiums "absPath" instead of "path" is used in "world.json". When this is done on Windows the Windows path syntax is used.
This sometimes lead to issues after I synced all repos and then tried to work with the world on the other machine. I haven't recorded them but I will if I encounter them again. It was something in the line of: "[...].spells not connected" while trying to import a character with ddb-importer. Sometimes I wasn't even able to start the world at all (foundry told me it couldn't rename a file, starting as admin didn't solve it. This could have been a different issue though)

Is it possible to change it to use relative Unix paths only? I manually replaced "absPath" with "path" and the absolute (Windows) paths with relative Unix paths and it seemed to work after a restart of FoundryVTTsubmit an effective bug report, please include the following information along with your issue description.

**Comment by anathemamask** [comment]
Not a core issue, but an issue with API usage from DDB importer. Closed as #wontfix.
