### ISSUE TITLE
Toggling PAUSE affects performance significantly on complex maps and/or low-end computers.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#6675]
Originally in GitLab by @Feu-Secret

Maybe migrate **Pause** mechanisms to PIXI instead of using CSS animations.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/40aaf2dde347fea995d076a34556cea2/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/8782f06b7ffdffb51f4d6302d9adc9a5/image.png)

**Comment by Fyorl** [comment]
Closing this as nonrepro for now in v10. Might have been fixed by a PIXI update or lighting improvements.

**Comment by Fyorl** [comment]
Additional report from the_shade_505#9580:

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10  
**Short Description of bug:** My game seems to have an drastic increase in either lag or lack of frames whenever I pause my game, resuming normal speeds when unpaused. the problem persists anytime I re pause it again. Edit: Narrowed it down to only be affecting the Electron client but works as expected in a browser  
**Simple steps to reproduce the bug:**  
Repausing the game again (only affects Electron client)
