### ISSUE TITLE
Ensure that the ProseMirror activateEditor entry point has a hook where modules can add functionality to the created editor instance.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6723]
Originally in GitLab by @arcanistzed

### Feature Summary

For better package compatibility, it would help to transition to a more robust storage method for the TinyMCE configuration properties. Using arrays for certain fields such as `plugins` and `toolbar` (which are frequently edited by modules) would be a solution which is already supported by TinyMCE.

### User Experience

For example, to add a new plugin, you would simply push to the arrays:
```js
CONFIG.TinyMCE.plugins.push("searchreplace");
CONFIG.TinyMCE.toolbar.push("searchreplace");
```

### Priority/Importance

> Low

**Comment by Fyorl** [comment]
I've reframed this for our ProseMirror editor. It's possible for downstream code to append to the `ProseMirror.defaultPlugins` array easily. The menu is not quite as easy to modify as that plugin is instantiated as part of an `activateEditor` call. Modules are not always able to override this method so we should provide a way for them to customise the menu that is created.
