### ISSUE TITLE
Multiple circumstance bonuses should stack

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6735]
Originally in GitLab by @Wraith_Magus

### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Windows 10
* How Are You Using Foundry: Native Application
* Which Game System: Pathfinder 1e
* Modules Enabled?: Several, but I do not believe any are relevant

### Issue Description

To help keep track of every effect currently affecting a given character, I set up buffs for some things that are circumstantial bonuses, such as Flanking, Aid Another, attacking from high ground, or other effects.  Circumstantial bonuses are just general bonuses that arise from circumstances the characters find themselves in, and the GM can award them via fiat, so they are meant to stack.

"**Bonus Types**: Usually, a bonus has a type that indicates how the spell grants the bonus. The important aspect of bonus types is that two bonuses of the same type don’t generally stack. With the exception of dodge bonuses, **most circumstance bonuses**, and racial bonuses, only the better bonus of a given type works (see Combining Magical Effects). The same principle applies to penalties—a character taking two or more penalties of the same type applies only the worst one, although most penalties have no type and thus always stack. Bonuses without a type always stack, unless they are from the same source." - Core Rulebook p208 
https://aonprd.com/Rules.aspx?Name=Special%20Spell%20Effects&Category=Casting%20Spells

There is more specifics under the original 3.5 rules:
"A circumstance bonus (or penalty) arises from specific conditional factors impacting the success of the task at hand. Circumstance bonuses stack with all other bonuses, including other circumstance bonuses, unless they arise from essentially the same source." - d20 SRD (Paizo apparently never republished this specific part, but it apparently still applies from context in the above rule.)

https://www.d20srd.org/srd/theBasics.htm

Like dodge bonuses, circumstance bonuses should stack (that is, Aid Another should stack with masterwork equipment if, say, there's a duet going on in a Perform check).  

Having the ability to list bonuses as circumstance bonuses also is useful as a GM, because it helps me track where every bonus is coming from looking at the roll.  If everything is just "untyped" (which just adding the enhancement bonus of a +1 sword to the attack bonus line is just read out as "untyped"), you wind up with 3-4 different bonuses that are simply called "untyped" with no idea whether they're valid or not without stopping the game to root through the whole character sheet.  Having "Flanking - circumstance" bonuses makes things much faster to see.

~Bug ~"Active Effects"

**Comment by anathemamask** [comment]
This is an issue best handled by the PF1e system and is not, itself, indicative of a bug in active effects.
