### ISSUE TITLE
Locked Journal CSS formatting issue

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6790]
Originally in GitLab by @EndlesNights

### Environment Details

* Foundry VTT Version: Version 9.249
* Operating System: Windows
* How Are You Using Foundry: Electron Application
* Which Game System: issue appears regardless of system
* Modules Enabled?: NO

### Issue Description

Upon viewing locked Journal entries, I noticed that there appears to be a visual void where text is not displayed, because the CSS has been set up the DIV with the expectation that the "SAVE ENTRY" button should be their. Attached image below can illustrate.
![image](https://gitlab.com/foundrynet/foundryvtt/uploads/c327dc7fa67c3cbf7f094899c72895f3/image.png)

Luckily the solution is quite simple to fix the issue. The current CSS at line 4161 is as follows

```
.journal-sheet form .editor {
  height: calc(100% - 115px);
}
```
And you just need to add in the more specific style right underneath. Which is one way that could fix the visual issue.
```
.journal-sheet form.locked .editor {
  height: calc(100% - 81px);
}
```

**Comment by anathemamask** [comment]
Appears to have been resolved somewhere during the Journals v2 fixes in V10.
