### ISSUE TITLE
Meta Issue: Overview of breaking changes in Document and data models from V9 to V10

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6849]
## Data -> System
- `ActorData#data` migrated to `Actor#system`
- `CardData#data` migrated to `Card#system`
- `CardsData#data` migrated to `Cards#system`
- `ItemData#data` migrated to `Item#system`

## Permission -> Ownership
- `ActorData#permission` migtrated to `Actor#ownership`
- `CardsData#permission` migrated to `Cards#ownership`
- `JournalEntryData#permission` migrated to `JournalEntry#ownership`
- `MacroData#permission` migrated to `Macro#ownership`
- `PlaylistData#permission` migrated to `Playlist#ownership`
- `RollTableData#permission` migrated to `RollTable#ownership`
- `ItemData#permission` migrated to `Item#ownership`

For more info see <https://gitlab.com/foundrynet/foundryvtt/-/issues/6867>

## Other Data Schema Changes
- `ActorData#token` migrated to `Actor#prototypeToken`
- `TableResultData#collection` migrated to `TableResult#documentCollection`
- `TableResultData#resultId` migrated to `TableResult#documentId`

## Package Metadata Changes
- The metadata for each Compendium Pack is now tagged with more specific `packageType` and `packageName` metadata instead of the previous `package` (string).

## Other Functional Changes
- `DocumentData` renamed to `DataModel`
- `DocumentData#update` renamed to `DataModel#updateSource`
- `ActiveEffect#duration` changed from a getter to derived data attributes
- `Card#back` getter replaced with derived data attribute
- `Card#face` getter renamed to `Card#currentFace`
- `Card#name` getter replaced with derived data attribute
- `Card#reset` method renamed to `Card#recall` to avoid conflict with `DataModel#reset`
- `Cards#reset` method renamed to `Cards#recall` to avoid conflict with `DataModel#reset`
- `Combatant#img` getter changed to a derived data attribute
- `Combatant#name` getter changed to a derived data attribute
- `Playlist#playing` getter changed to derived data attribute
- `PlaylistSound#volume` getter functionality renamed to `PlaylistSound#effectiveVolume`
- `Scene#playlistSound` changed from getter to derived data attribute
- `TableResult#reset` renamed to `TableResult#resetResults` to remove conflict with `DataModel#reset`
- `User#avatar` changed from a getter to a derived data attribute
- `PrototypeTokenData` renamed to `PrototypeToken`, still available under the `foundry.data` namespace.

**Comment by JysonKhan** [comment]
Something else that seems to have been broken

foundry.js:9438 Uncaught (in promise) TypeError: simplified.at is not a function
    at Function.simplifyTerms (foundry.js:9438)

**Comment by aaclayton** [comment]
> Something else that seems to have been broken
> 
> foundry.js:9438 Uncaught (in promise) TypeError: simplified.at is not a function at Function.simplifyTerms (foundry.js:9438)

If you don't have the `Array.prototype.at` function available it's because you are either using too old an Electron version of the software OR you are using a non-modern web browser. Solutions for this are to reinstall the software from our website (if self-hosting) or switch to a more updated browser if using a web browser.
