### ISSUE TITLE
Tokens can not move into a square bisected by a wall using drag movement

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#6856]
Originally in GitLab by @mattexdee

Originally posted by SoundAI: https://discord.com/channels/170995199584108546/872553750877835264/949638409524240394

**ALL MODULES DISABLED?** true

**Short Description of bug:** drag-distance based movement not possible into half-grid squares

**Simple steps to reproduce the bug:** draw a wall line diagonally through a square to cut it exactly in half. normal token movement into that square is possible, but drag-distance based movement is not. this affects both ctrl+drag + spacebar and the module drag-ruler.

**Screenshots and/or console errors:**

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/8676d169e012854acd4d7521e1c1253f/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/dc45e1ffa691d41a793d030c731a2af1/image.png)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/cfc32d3ccf27483f55ba8e69da4332a8/image.png)

### Issue Description
When using drag movement to set waypoints for a token they can not move into a square that is bisected by a wall. I have reproduced this issue as well.

**Comment by aaclayton** [comment]
This issue has been resolved by the changes introduced in #7218
