### ISSUE TITLE
Improve hit area detection for hexagons

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#6878]
Originally in GitLab by @Fyorl

The existing method to convert a canvas pixel to the grid space that contains it on a hex grid is imprecise due to rounding errors.

**Comment by aaclayton** [comment]
This *may* no longer be an issue, @Fyorl and @Feu-Secret to confirm.

**Comment by Fyorl** [comment]
Closing as duplicate of #8243
