### ISSUE TITLE
Add .csv text/csv to TEXT_FILE_EXTENSIONS for FilePicker()

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6881]
Originally in GitLab by @zgsuppo

### Feature Summary

I would like to see the .csv file extension included in the FilterPicker file options. Currently the options are

TEXT_FILE_EXTENSIONS = { json: "application/json", md: "text/markdown", pdf: "application/pdf", txt: "text/plain", xml: "application/xml" };

I would like to see `csv: "text/csv"` added.

### User Experience

The csv file is used by a module called Data Toolbox for Foundry, that is currently unable to show the csv file in the FilePicker:
https://github.com/SvenWerlen/fvtt-data-toolbox/issues/26

### Priority/Importance

I would say low priority because we can rename the file into csv or xml as workaround, but would be useful to have it soon or later.

**Comment by bzvestey** [comment]
Another nice file type would be `yaml`/`yml`. Let me know if I should create a new issue for this.

**Comment by Fyorl** [comment]
Added `csv`, `tsv`, `yaml`, and `yml` extensions.
