### ISSUE TITLE
Add a Tour Manager that allows Users to view and consume Tours registered in `game.tours`

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6883]
Create a UI for starting, resetting, and viewing Tours

### Access
- [x] A new Game Settings button launches a new Manage Tours application

### Manage Tours Application
- [x] The Manage Tours application works like the Keybindings Application, with a sidebar that groups Tours by their Namespace
- [x] Tours are searchable
- [x] Status is shown - completed, in-progress, unstarted
- [x] Completed Tours are grayed out to minimize attention, but are still actionable
- [x] Buttons are provided - Start / Resume, Reset

## Mockups

![image](https://user-images.githubusercontent.com/15639841/178018708-2f9dc9ea-61b4-4b7c-a817-090834473b79.png)

![image](https://user-images.githubusercontent.com/15639841/178020664-dbac27d4-42e5-4f4e-882e-089980cdcb9c.png)

## Bonus Scope
- [ ] A handlebars helper allows a Dev to easily wrap an element with a link to launch a Tour by clicking it
- [ ] Applications can register a single Tour associated with them, which automatically adds a header button to launch it

**Comment by aaclayton** [comment]
A few questions for you to think about:

1. How do we want the user to manage tours on the /setup page?
2. We will need some special handling to save/load tracked tour completion setting outside of the context of a world.
3. If we are using the same basic UI/UX for settings, keybindings, and tours should we have those 3 concepts all inherit from a shared base class?
4. I am concerned that the "starting conditions" may not be right for many tours. Is our assumption that the user can start a tour from any world state at all - and the tour should be responsible for setting up any example data that is needed to illustrate the tour? For example - a tour that needs to demonstrate a specific canvas workflow. What if the user has no Scene, or even has the canvas fully disabled? How much work should the individual `Tour` be expected to do? Should each Tour expose an `isAvailable` getter which can rule out tours for which the current world state is insufficient to give the tour? I worry about this UX compared to the case of programmatic tour initiation.

**Comment by cswendrowski** [comment]
> How do we want the user to manage tours on the /setup page?

Current intention is that Setup page Tours cannot be managed, and are instead launched either automatically or via user action like the "Installing a System" tour, since they are only created by us

> We will need some special handling to save/load tracked tour completion setting outside of the context of a world.

Given the above, I don't think we need this

> If we are using the same basic UI/UX for settings, keybindings, and tours should we have those 3 concepts all inherit from a shared base class?

This is probably a wise idea

> I am concerned that the "starting conditions" may not be right for many tours. 

This is a fair concern. I think at the end of the day we need to trust Tours to manage their own state. Outside of canvas based tours, I'm not coming up with thoughts on why a Tour couldn't start, but that's a good enough reason to add that functionality.
