### ISSUE TITLE
Sound tracks sporadically not starting until moving the volume slider

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6899]
From https://discord.com/channels/170995199584108546/872553750877835264/954684619800846446

---

https://media.discordapp.net/attachments/872553681449537666/954449594031427614/unknown.png

Sound tracks sporadically not starting until moving the volume slider. Cannot reproduce it consistently.

Although I believe this bug happens out of the blue as well, the following repro-steps get to the same problem outcome:
1. Get into a playlist with Shuffle Tracks mode one
2. Play a song
3. Press next song, wait at least 10 seconds of it playing
4. Press Previous song and then next song again, quickly enough to not give time to fade out
5. Current track will restart to 0:00 and will never start playing

Tested with module: Tabletop RPG Audio tracks 
![](https://images-ext-1.discordapp.net/external/1e8j06_E50tnYOpynvNw0E8ZgkP1szpYTfHRkpHRgYM/https/media.discordapp.net/attachments/872553681449537666/954449594031427614/unknown.png)

**Comment by aaclayton** [comment]
Fixed by audio improvements in v12.
