### ISSUE TITLE
Rightmost vertical grid line is not being rendered

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6903]
From https://discord.com/channels/170995199584108546/872553750877835264/956784088398823445

---

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): chrome or firefox on mac or windows
Short Description of bug: rightmost vertical grid line is not being rendered
Simple steps to reproduce the bug: set up a map with a visible grid.  The effect is easier to see with 0 padding so that the rightmost vertical grid line should fall on top of the map, and have the map width not close to a multiple of the grid size

**Comment by aaclayton** [comment]
Wont change.
