### ISSUE TITLE
Fog of war exploration positions can be incorrect if a door has been opened within the visible radius of a prior visited position.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6921]
Originally in GitLab by @dev7355608

Unless the token moves through the open door and into the unexplored room, the exploration is not recorded except the snapshot of the moment the doors is opened:

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/a3baea7d1a64c1d104130b4531063829/doors_and_fog.webm)

Opening a door needs to delete explored positions from the exploration data: all positions from which the door is visible. The simple solution would be to delete all explored positions. Testing whether each explored position sees the door is probably more expensive (assuming there are a lot of points in the exploration data) than checking whether the explored positions are visible from the door. I tested the latter, and it works well:

```js
  // Wall#_onModifyWall
  _onModifyWall(doorChange=false) {

    const perceptionUpdate = foundry.utils.mergeObject(PerceptionManager.DEFAULTS, {
      lighting: {initialize: true, refresh: true},
      sight: {initialize: true, refresh: true},
      sounds: {initialize: true, refresh: true},
      foreground: {refresh: true}
    }, {inplace: false});

    // Re-draw door icons
    if ( doorChange ) {
      const dt = this.data.door;
      const hasCtrl = (dt === CONST.WALL_DOOR_TYPES.DOOR) || ((dt === CONST.WALL_DOOR_TYPES.SECRET) && game.user.isGM);
      if ( hasCtrl ) {
        if ( this.doorControl ) this.doorControl.draw(); // Asynchronous
        else this.createDoorControl();
      }
      else if ( this.doorControl ) {
        this.doorControl.parent.removeChild(this.doorControl);
        this.doorControl = null;
      }

      if (this.isOpen) { // Only if the door is opened, we need to update the fog exploration
        perceptionUpdate.sight.forceUpdateFog = true; // Not really necessary anymore
        const updateData = {};
        const { a, b } = this.vertices;
        // Test points along the wall segment in at most grid size intervals such that the center of the segment is tested as well
        const n = Math.ceil(((Math.hypot(a.x - b.x, a.y - b.y)) / 2) / canvas.dimensions.size) * 2;
        for (let i = 0; i <= n; i++) {
          const t = i / n;
          const los = CONFIG.Canvas.losBackend.create({ x: a.x * (1 - t) + b.x * t, y: a.y * (1 - t) + b.y * t }, { type: "sight" });
          for (const position in canvas.sight.exploration.data.positions) {
            const [x, y] = position.split("_");
            if (los.contains(Number(x), Number(y))) { // The door is visible from the explored position
              updateData[`positions.-=${position}`] = null; // Delete the explored position
            }
          }
        }
        if (!foundry.utils.isObjectEmpty(updateData)) {
          canvas.sight.exploration.data.update(updateData);
          if (!canvas.sight.exploration.id) {
            canvas.sight.exploration.constructor.create(canvas.sight.exploration.toJSON()).then(e => canvas.sight.exploration = e); // Asynchronous
          } else {
            canvas.sight.exploration.update(updateData); // Asynchronous
          }
        }
      }
    }

    // Re-initialize perception
    canvas.perception.schedule(perceptionUpdate);
  }
```

**Comment by dev7355608** [comment]
Is the fog commit fast enough now so that the explored positions test could be removed and every refresh commits the fog?

**Comment by Feu-Secret** [comment]
> Is the fog commit fast enough now so that the explored positions test could be removed and every refresh commits the fog?

Indeed, I think it deserves consideration. The annoying side effect is that the fog will be commited and saved when it is not necessary.

**Comment by aaclayton** [comment]
It feels to me that there should be some low-cost mechanism for avoiding unnecessary fog operations when a token is moving back and forth over the same spaces that they have previously visited. I do acknowledge that as we add more features to the lighting system, there are more things about the environment that can change which require fog to be re-explored for a previously visited position, though.

**Comment by aaclayton** [comment]
I wonder if we could efficiently hash the vision polygon somehow and store that as exploration progress as a way to test whether we are seeing the same thing that we saw before at a certain grid coordinate.

**Comment by Feu-Secret** [comment]
We could generate a hash from the fog texture content (a 128 bits hash) and compare it with the previous texture hash. If the hash is identical, we could skip compression and db operations. It could be done inside a worker.

**Comment by dev7355608** [comment]
This issue is seems to be partially fixed. The fog is already committed each time a token with vision is moved regardless of whether the position was already explored: once the token reaches it destination of the movement animation, vision is refreshed with `forceUpdateFog: true`. V10 already forces this fog update. So if Token Vision Animation is disabled, the explored position test has basically no effect.
```js
    // Render the completed animation
    config.animatePerception = config.forceUpdateFog = true;
    this.#animateFrame(animation, config);
```

Also if a token that emits light and that isn't controlled is moved, `forceUpdateFog` is true and each frame the fog is committed. There is actually a bug here: even if the token is controlled, `forceUpdateFog` must be true, because, if token revisits an explored position with a light source, not commit is done.
```diff
    const config = game.settings.get("core", "visionAnimation") && isPerceptionChange ? {
      animatePerception: this._isVisionSource() || emits,
      sound: this.observer,
-     forceUpdateFog: emits && !this.controlled && (canvas.effects.visionSources.size > 0)
+     forceUpdateFog: emits && (canvas.effects.visionSources.size > 0)
    } : {animatePerception: false};
```

So if a token that emits light is moved, each frame of the movement animation (should) trigger a commit. So in this case the explored position test has no effect too.
