### ISSUE TITLE
World creation allows creating folders forbidden by Windows

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6948]
From: https://discord.com/channels/170995199584108546/872553750877835264/959424466537041930

---

It seems that during world creation, FoundryVTT has the ability to create folders which include Windows forbidden names such as CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

Normally, if you try to create such things, the system will add extra data at the end of the name to distinguish them.

**Comment by aaclayton** [comment]
Added a specific Package ID validation rule:
```js
  static #validateId(id) {
    const allowed = /^[A-Za-z0-9-_]+$/;
    if ( !allowed.test(id) ) throw new Error("Package IDs may only be alphanumeric with hyphens or underscores.");
    const prohibited = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])(\..*)?$/i;
    if ( prohibited.test(id) ) throw new Error(`The Package ID "${id}" uses an operating system prohibited value.`);
  }
```

Some example failures:

![Image](https://user-images.githubusercontent.com/2468703/175838166-5b1b413d-91d5-4ae8-8d58-8871af9283bc.png)
