### ISSUE TITLE
Fog exploration appears to reveal slightly less than assigned value, shifting the explored amount just slightly.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6955]
From https://discord.com/channels/170995199584108546/872553750877835264/962144204744687626

---

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Chrome/Chromium(electron)
Short Description of bug: Submitted by @Saltanis , --- Fog exploration appears to reveal slightly less than assigned value, shifting the explored amount just slightly.
Simple steps to reproduce the bug: Create any blank scene with a grid of any size. Place a token, move the token two spaces right, then two spaces left. observe as the amount of explored does not line up with what the token was able to see when standing two spaces to the right.
Screenshots and/or console errors:
![](https://media.discordapp.net/attachments/872553750877835264/962144203352182914/unknown.png)
![](https://media.discordapp.net/attachments/872553750877835264/962144203616432228/unknown.png)

**Comment by anathemamask** [comment]
Considered resolved by #7231
