### ISSUE TITLE
Allow /join and /auth credentials to be saved by a browser's password manager.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6961]
Originally in GitLab by @lugray

### Environment Details

* Foundry VTT Version: 9.266
* Operating System: MacOS
* How Are You Using Foundry: Chrome
* Which Game System: dnd5e
* Modules Enabled?: yes, none relevant

### Issue Description

The join game screen has `autocomplete="off"` for the password field. Combined with a user drop-down instead of a text input field, password managers fail to pick this up as a field they should offer to fill. Changing this instead to use `autocomplete="current-password"` causes password managers to offer to fill it.

**Comment by mhornbacher** [comment]
Can I re-open this? It seems to have come back in version 12
