### ISSUE TITLE
Resetting card deck removes custom sort order

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6976]
Originally in GitLab by @DrMcCoy

In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

* Foundry VTT Version: 9.268, but also happened in 9.266
* Operating System: Debian GNU/Linux bullseye
* How Are You Using Foundry: nodejs on the Debian system, connecting from Firefox 99.0 running on a Gentoo Linux system
* Which Game System: pf1
* Modules Enabled?: yes, a whole bunch, but none should be relevant

### Issue Description

Clicking "Reset" on a card deck, no matter if cards were drawn or not, also reset the custom sort order. This happens both if the sort order was created by dragging around, or by importing a JSON with embedded sort values.

It could be that this is a feature, not a bug. If so, I'd like to petition for a change, or at least a checkbox to keep the sort order on "Reset".

My use-case is this: I'm currently prepping a resurrection of a real-life Pathfinder campaign we put on hold due to both the pandemic and then people moving away, Foundry VTT allowing us to finally continue this campaign. The campaign uses the Pathfinder "Harrow Deck", a kind of tarot style deck of 54 cards in 6 suits.

I don't really want to manually create 54 cards, so I instead bought the PDF version of the deck, extracted the individual cards as images and did some shell hackery to create a JSON file describing the cards that I can use to import into Foundry VTT. Now, the cards have a canonical order: the suits themselves have a (non-alphabetical) order and the cards within the suits have one as well (each cards has a D&D-style alignment and there is a canonical ordering of those). So I gave each card a "sort" value with the correct ordering.

I import the JSON, and the ordering is there, perfect. With the "sort mode" button, I can switch between canonical and alphabetical ordering of the suits, fine.

But then I click "Reset", and the canonical ordering of the suits is gone. Clicking the "sort mode" button does nothing, the suits are all sorted alphabetical now, always. The cards within the suit do keep their correct order, though. When I export deck as JSON and compare it with what I imported, the sort values have been rewritten.

**Comment by aaclayton** [comment]
Hi @DrMcCoy. The resetting of the sort order *was* originally an intentioanl feature, but I think your report explains why this is a bad idea and why that original sorting should be maintained. I'll make this change.

**Comment by DrMcCoy** [comment]
Ah, nice, thanks! :)
