### ISSUE TITLE
onUp events for keybindings are not being fired after clicking certain UI elements

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6978]
Originally in GitLab by @manuelVo

### Environment Details

* Foundry VTT Version: 9.268
* Operating System: Linux (Arch Linux)
* How Are You Using Foundry: Electron
* Which Game System: dnd5e (happens in other game systems as well)
* Modules Enabled?: no

### Issue Description
Keybindings that activate a certain effect when pressing a key and deactivate that effect once the key is being released can get stuck in the down state if certain UI elements are being clicked. One example of a keybinding that suffers from this is the "Highlight Objects"-Key.

### Steps to reproduce
1. Open a character sheet
2. Press and hold the Alt Key, to highlight objects
3. Click into the character name field to edit the character name
4. Release the Alt Key
5. Observe, that the "Highlight Objects" effects remain active indefinitely (to get rid of them, one needs to un-focus the character name box and tap the alt key)

**Comment by shemetz** [comment]
This bug may be responsible for an occasional bug where dragged tokens do not align with the grid.  The game treats the drag motion as if shift is being held down when it isn't, and so avoids snapping them into the grid.  It happened to me multiple times in both v9 and v10, and apparently to many others as well.  (unclear if it happens only when Drag Ruler is enabled, but even if that's true it's apparently a core bug at the root)

**Comment by aaclayton** [comment]
@cswendrowski looks like this issue escaped our attention for a while, it may or may not remain an issue in V10 - but perhaps you could take a look and see if you can identify a reproduction path as described in the original issue.

**Comment by cswendrowski** [comment]
@aaclayton  We explicitly don't react to keyevents while an input field is focused so we don't consume the typing events (and therefore lose characters).

This is a tricky one - if someone is holding "T" for instance and then focuses an input, what is the expected outcome? Should "T" be typed in that input? We ideally should fire the onUp for "T" as well to clear any previous events, but that event might then be consumed.

The answer is possibly to, on input focus, emulate an onUp for any down keys similar to what we do in `game._onWindowBlur`
