### ISSUE TITLE
Add 3D Filetypes to the Filepicker Allowed Extensions

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6995]
Originally in GitLab by @theripper93

### Feature Summary

> Add 3D Filetypes to the Filepicker Allowed Extensions. Since this would be an easy change to implement and i don't see any security risks involved. While a bit of a selfish request, not only my premium modules can benefit from it but possibly modules like Dice so Nice could allow for custom 3D dice model uploads.

Extensions would include: glb, gltf, obj, stl, fbx

### User Experience

At the moment getting 3d files into the data folder is very finniky unless you host locally.

### Priority/Importance

While not high priority, it would be very nice to have

**Comment by theripper93** [comment]
Any news on if this will be in v10?

**Comment by aaclayton** [comment]
I'll add it to our candidates milestone for further consideration. Hopefully we can get to it.

**Comment by theripper93** [comment]
Perfect, thanks, hopefully it’s not too much work

**Comment by Fyorl** [comment]
Added `fbx`, `glb`, `gltf`, `mtl`, `obj`, `stl`, and `usdz`.

**Comment by theripper93** [comment]
i'll add that .bin should aslo be added, otherwise separate gltf files would not work.
