### ISSUE TITLE
Allow a game Setting to be defined using a type that refers to a DataModel class definition.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7041]
Originally in GitLab by @arcanistzed

```js
game.settings.register("myModule", "mySetting", {
  name: "Register a Module Setting with validation",
  hint: "A description of the registered setting and its behavior.",
  scope: "client",
  config: true,
  type: MyDataModel
});
```

In this example, `MyDataModel` would be used to validate the setting whenever it is updated and would also provide a structure for the setting.

**Comment by arcanistzed** [comment]
Could we see this for Document flags as well?

**Comment by aaclayton** [comment]
> Could we see this for Document flags as well?

Probably not automatically, but you can certainly use this approach for your own flags.
