### ISSUE TITLE
Add more built-in easing functions to CanvasAnimation

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7076]
Originally in GitLab by @ghost91-

### Feature Summary

`CanvasAnimation` now provides support for easing and already comes with a couple of built-in easing functions. However, there are many uses cases for more easing functions, so it would be great if a more were provided. A comprehensive list of easing functions (including their mathematical implementations) can be found at https://easings.net/.

Some modules already provide their own easing functions, and could probably switch to the ones provided by foundry core, if the ones they use are added. Here is an overview of some modules and the easing functions they use:

| Easing Function    | FXMaster | Sequencer | Token Ease |   Provided by Core    |
| ------------------ | :------: | :-------: | :--------: | :-------------------: |
| `easeLinear`       |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInSine`       |    ✓     |     ✓     |     ✓      |           ×           |
| `easeOutSine`      |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInOutSine`    |    ✓     |     ✓     |     ✓      | ✓ (`easeInOutCosine`) |
| `easeInQuad`       |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutQuad`      |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutQuad`    |    ×     |     ✓     |     ✓      |           ×           |
| `easeInCubic`      |    ✓     |     ✓     |     ✓      |           ×           |
| `easeOutCubic`     |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInOutCubic`   |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInQuart`      |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutQuart`     |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutQuart`   |    ×     |     ✓     |     ✓      |           ×           |
| `easeInQuint`      |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutQuint`     |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutQuint`   |    ×     |     ✓     |     ✓      |           ×           |
| `easeInExpo`       |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutExpo`      |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutExpo`    |    ×     |     ✓     |     ✓      |           ×           |
| `easeInCirc`       |    ✓     |     ✓     |     ✓      |  ✓ (`easeInCircle`)   |
| `easeOutCirc`      |    ✓     |     ✓     |     ✓      |  ✓ (`easeOutCircle`)  |
| `easeInOutCirc`    |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInBack`       |    ✓     |     ✓     |     ✓      |           ×           |
| `easeOutBack`      |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInOutBack`    |    ✓     |     ✓     |     ✓      |           ×           |
| `easeInElastic`    |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutElastic`   |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutElastic` |    ×     |     ✓     |     ✓      |           ×           |
| `easeInBounce`     |    ×     |     ✓     |     ✓      |           ×           |
| `easeOutBounce`    |    ×     |     ✓     |     ✓      |           ×           |
| `easeInOutBounce`  |    ×     |     ✓     |     ✓      |           ×           |

Potentially there are more modules, but these are the ones I am aware of.

Foundry core could also benefit from more built-in easing functions, as it allows more flexibility regarding how animations look and feel.

### User Experience

End users won't interact with this directly. It's meant as a convenience feature for package authors who want to provide custom animations. For these module authors, it should be easy to access the easing functions, either directly on `CanvasAnimation`, or if there are too many, it might make sense to extract them to some other place.

### Priority/Importance

It's not very important, since people could just provide the needed easing functions themselves. But it seems like a pretty straight forward improvement and is not a lot of work. It also just feels a bit inconsistent, that only three (seemingly randomly chosen) easing functions are provided, and not a set of commonly used ones.

**Comment by itamarcu** [comment]
Small note: `CanvasAnimation.animate` currently uses Linear easing by default:

```js
    const pa = complete ? 1 : (animation.easing ? animation.easing(pt) : pt);
```

However, the function documentation says nothing about this, making it a bit ambiguous (especially for developers migrating away from `CanvasAnimation.animateLinear`).  It would be nice if, as part of this change, linear easing was explicitly stated to be used by default (perhaps simply by having a default value in the function signature).

**Comment by aaclayton** [comment]
This is a good idea for a future release, but not something we will be doing in V10 in order to limit scope and reach our target deadlines.

**Comment by aaclayton** [comment]
Closing as wontfix.
