### ISSUE TITLE
Improve the performance of Document get/set/unset flag op erations by caching the set of available flag scopes and restricting module scopes to active modules instead of all modules.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7111]
Originally in GitLab by @dev7355608

`getFlag` can be quite the performance killer if called frequently. `getFlagScopes` creates an array of all installed modules in an very inefficient way, and the following linear search in this array is slow; especially if you have hundreds of modules installed. I suggest to add `isFlagScope`, which can be efficiently implemented. Also the concatenation of `scope` and `key` is unnecessary; instead return `getProperty(this.data.flags?.[scope], key)`.

I think the flag scope check unnecessary and even restrictive: `getFlagScopes` only knows about installed modules, so a valid scope could be rejected. I'd say either `getFlag` only allows scopes of active modules or it trusts any scope.

**Comment by TheGiddyLimit** [comment]
What's the reasoning behind limiting scopes to only active modules (or really, limiting scope at all)? As a module developer, being able to set flags for inactive modules allows me to provide a better user experience should the user later enable those modules.

At present, it seems like `doc.update({flags: { ... })` still "works" for my use-case, as there are no scope checks there. Is this functionality going to maintained, or will strict scope checks be added there too?

**Comment by aaclayton** [comment]
The rationale is to limit the scope of the data which is stored to the database and to protect developers or users writing macros from accidentally injecting flag data into an invalid scope which will just bloat the data and never be used by any module. We might add more strict checks to Document.update in the future, I'm not sure. 

In general you should not be writing flags for some other package besides your own.

**Comment by TheGiddyLimit** [comment]
I see. Thanks for the explanation.
