### ISSUE TITLE
Provide filtering entry points with dedicated containers. These containers could be used by modules/systems to add their own post processing effects.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7186]
Originally in GitLab by @dev7355608

It's not possible to add filters after lighting is applied to the scene unless the filter is applied to the stage directly, but then the filter would affect the interface as well. Filters that need to be applied after effects are displacement (underwater), old film/CRT, glitch, bloom or any kind of color adjustment filters.

The primary canvas group and the effects group need to be placed in a separate container, where the filters can be attached.

I also noticed that `VisualEffectsMaskingFilter` and `VisibilityFilter` are not correctly sampling from `uVisionSampler` and `uRoofSampler` (if you add any filter to the stage and pan to the edges of the canvas while having a token selected, you see why): they must not use `vTextureCoord`, but `vMaskTextureCoord` as in `AbstractBaseMaskFilter`.

**Comment by Feu-Secret** [comment]
A new organization has been introduced with groups and layers, with the new `rendered` and `environment` groups (`canvas.rendered` and `canvas.environment`).

These groups could be filtered according to the needs of the system and module developers. All alias have been preserved. It is only breaking if your module or system is dependant of the canvas tree hierarchy.

Here it is:
```js
groups: {
  hidden: {
    groupClass: HiddenCanvasGroup,
    parent: "stage"
  },
  rendered: {
    groupClass: RenderedCanvasGroup,
    parent: "stage"
  },
  environment: {
    groupClass: EnvironmentCanvasGroup,
    parent: "rendered"
  },
  primary: {
    groupClass: PrimaryCanvasGroup,
    parent: "environment"
  },
  effects: {
    groupClass: EffectsCanvasGroup,
    parent: "environment"
  },
  interface: {
    groupClass: InterfaceCanvasGroup,
    parent: "rendered"
  }
},
layers: {
  weather: {
    layerClass: WeatherEffects,
    group: "primary"
  },
  grid: {
    layerClass: GridLayer,
    group: "interface"
  },
  drawings: {
    layerClass: DrawingsLayer,
    group: "interface"
  },
  templates: {
    layerClass: TemplateLayer,
    group: "interface"
  },
  tiles: {
    layerClass: TilesLayer,
    group: "interface"
  },
  walls: {
    layerClass: WallsLayer,
    group: "interface"
  },
  tokens: {
    layerClass: TokenLayer,
    group: "interface"
  },
  sounds: {
    layerClass: SoundsLayer,
    group: "interface"
  },
  lighting: {
    layerClass: LightingLayer,
    group: "interface"
  },
  notes: {
    layerClass: NotesLayer,
    group: "interface"
  },
  controls: {
    layerClass: ControlsLayer,
    group: "interface"
  }
},
```
