### ISSUE TITLE
Significant performance improvements to the Fog of War framework using high-performance methods for texture extraction and persistence.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7231]
We feel strongly about making this change and have discussed prioritizing it for V11.
We are going to evaluate two approaches: 
- Optimized Texture based 
- Geometry based

---

# Optimized Texture Based

## Objectives :
- Improvement of the texture extraction
- Remove freezes (or at least reduce them drastically)
- Improve quality of the saved texture (jpeg artifacts, etc.)
- Use worker thread

## Linked issues :
- https://github.com/foundryvtt/foundryvtt/issues/8580
- https://github.com/foundryvtt/foundryvtt/issues/8658

# Geometry Based

## Objectives :
- Get rid of the FOW render texture and image compression.
- Compute intersections of polygons in a debounced way.
- Save the resulting polygon points.

## Linked issues :
- https://github.com/foundryvtt/foundryvtt/issues/8583
- https://github.com/foundryvtt/foundryvtt/issues/8584

---

# Common to both approaches

## Objectives :
- Improve the rendering of the pending elements
- Stabilize FPS
- (nice to have) Simple Fog
- Choose the best approach after some profiling and user testing

## Linked issues :
- https://github.com/foundryvtt/foundryvtt/issues/8581
- https://github.com/foundryvtt/foundryvtt/issues/8582
- https://github.com/foundryvtt/foundryvtt/issues/8585

---

## Related issues
Closely related to https://github.com/foundryvtt/foundryvtt/issues/1080 because simple/manual fog of war would use geometries to define explored and unexplored regions. This should probably be combined as part of the existing https://github.com/foundryvtt/foundryvtt/issues/1080 epic.

## Resolves
- https://github.com/foundryvtt/foundryvtt/issues/7020
- https://github.com/foundryvtt/foundryvtt/issues/6859
- https://github.com/foundryvtt/foundryvtt/issues/6983
- https://github.com/foundryvtt/foundryvtt/issues/6444

**Comment by Weissrolf** [comment]
Great stuff then! <thumbs_up>

**Comment by JacketsMask** [comment]
Looking forward to this! My friend's game has been experiencing a lot of fog drift similarly described in #6983. It's especially bad when repeatedly opening and closing doors that obstruct vision.
