### ISSUE TITLE
Add configurable Sound cues that can play when Combat begins, when your turn is next, and when it is your turn

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7242]
Should be configurable at minimum in `CONFIG`, and ideally in UI.

Should default to nothing

```js
  Combat: {
    documentClass: Combat,
    collection: CombatEncounters,
    defeatedStatusId: "dead",
    sidebarIcon: "fas fa-swords",
    initiative: {
      formula: null,
      decimals: 2
    },
    sounds: {
      "8bit": {
        label: "COMBAT.Sounds.8Bit",
        startEncounter: ["sounds/combat/8bit-start-guitar.ogg"],
        nextUp: ["sounds/combat/8bit-next-badoop.ogg"],
        yourTurn: ["sounds/combat/8bit-turn-shing.ogg"]
      },
    }
  },
```

**Comment by eclarke12** [comment]
RIP [insert modules here]
As a stretch goal, consider adopting Maestro Combat Tracks? 
I have it setup to play a sound/playlist at the start of Combat. There is a default playlist option and a per-encounter option. I also have a shuffle/random (so you can set a default playlist and then have it select a random track at the start of combat).
