### ISSUE TITLE
Clockwise Sweep: Improve ability to drop edges which are fully outside of a boundary shape.

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7257]
### Environment Details

* Foundry VTT Version: 10.270

### Issue Description

Currently, 10.270 eliminates walls using quadtree (`ClockwiseSweep.prototype._getWalls`). But walls could be further culled where they do not intersect the bounding box of the boundaryShapes. 

Example:
![Screen Shot 2022-06-11 at 9 45 10 AM copy](https://user-images.githubusercontent.com/1267134/173197404-6982545f-53fd-4c5e-84ed-50a402d06f28.jpg)

In the above, wall 3|4 should probably be kept if 4 is within the bounding box of the circle radius, but 1|3 is well outside the bounding box and thus should be dropped. (Moving further south will eventually drop 1|3 and 3|4 thanks to quadtree.) 

### Proposed solution
I recommend adding to `_getWalls` with something like:
```js
  _getWalls() {
    if ( !this.config.boundaryShapes.length ) return canvas.walls.placeables;
    const bounds = this.#defineBoundingBox();
    const walls = Array.from(canvas.walls.quadtree.getObjects(bounds).values());
    return walls.filter(w => bounds.lineSegmentIntersects(w.A, w.B, { inside: true });
  }
```
Where `bounds.lineSegmentIntersects` is a new PIXI.Rectangle method [defined here](https://github.com/caewok/fvtt-walled-templates/blob/17bc3ec196733a625f31359d8e0ee05a1f12e5c1/scripts/ClockwiseSweep/PIXIRectangle.js#L217). Basically, that method determines where each wall endpoint is in relation to the rectangle, categorizing each endpoint using the [Cohen-Sutherland bit codes](https://en.wikipedia.org/wiki/Cohen%E2%80%93Sutherland_algorithm). Once the location of the endpoints are known, we know what edges of the rectangle, if any, we need to test for potential intersections. The `inside` flag is an easy way to return true if we also want to keep walls that are fully inside the rectangle (which technically do not intersect the rectangle). 

I suspect that other Foundry code could take advantage of an efficient test for whether a line segment intersects a bounding box, thus I recommend adding `lineSegmentIntersects` to PIXI.Rectangle for general use. Note that you could write a similar algorithm to return the actual intersection point(s), but that is outside the scope of this issue.

**Comment by aaclayton** [comment]
Implemented by @caewok!
