### ISSUE TITLE
Improve elimination of walls which are very close to collinear with the origin in the ClockwiseSweepPolygon.

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7273]
### Environment Details

* Foundry VTT Version: 10.270
* Operating System: macOS 12.4
* How Are You Using Foundry: Chrome  103.0.5060.33
* Which Game System: dnd5e 1.6.2
* Modules Enabled?: no

### Issue Description

I am seeing what is not an error per se, but some visual artifacts and unexpected results when a token's vision origination point lines up with a wall.

There appear to be two related issues:

1. Walls that are precisely in line with the vision origin (e.g., wall 11|12 in the polygon debugging screenshot) may or may not appear depending on how the token was moving when entering its current square. I could make 11|12 disappear by moving the token to a different grid square and then back, but it depended on direction the token moved. Ideally, the final view when the token stops moving would remove that wall completely and be consistent regardless of prior token movement. 
2. Walls nearly in line with the vision origin (e.g., wall 3|2 in the polygon debugging screenshot) can cause "choppiness" in the view of the shadow. This may not be entirely fixable, but perhaps a more permissive colinearity test could eliminate walls that are nearly collinear with the origin? 

The relevant test is `testWallInclusion` where it test the orientation of the wall with respect to the origin. This may be an instance where rounding the origin is having negative effects.

Here are screenshots all of the same scene with the token in the same place:
<img width="1037" alt="Screen Shot 2022-06-12" src="https://user-images.githubusercontent.com/1267134/173229664-d672c2ba-a2ed-4b6a-af20-f1e38075af61.png">

Zoomed in:
<img width="1037" alt="Screen Shot 2022-06-12 close up" src="https://user-images.githubusercontent.com/1267134/173229670-8cdb98f2-d813-43f0-8c80-74a54a778157.png">

Wall set up:
<img width="1037" alt="Screen Shot 2022-06-12 walls" src="https://user-images.githubusercontent.com/1267134/173229696-7847f954-5cf0-4299-b4af-490b67ac7fb9.png">

With polygon debugging on:
<img width="1037" alt="Screen Shot 2022-06-12 polygons" src="https://user-images.githubusercontent.com/1267134/173229558-4b8a3054-a3ce-4a32-b5af-5079803c6978.png">

Another version with a light in the scene:
<img width="1069" alt="Screen Shot 2022-06-12 with light" src="https://user-images.githubusercontent.com/1267134/173229630-b454ece9-5656-4e9a-89a1-c762116bd99c.png">

**Comment by aaclayton** [comment]
Need to confirm whether this is still an issue after some of the other improvements we have made here.

**Comment by caewok** [comment]
Here is an example with a single-wall setup (the wall follows the shadow almost exactly):
![Screen Shot 2022-06-28 at 2 58 16 AM copy](https://user-images.githubusercontent.com/1267134/176222375-4bfd1a04-3f81-4d8a-8b30-01e3a5195d2e.jpg)

It happens with my setup when a diagonal wall is nearly collinear with the token. (Not exactly collinear, because then of course the wall is ignored.) Here is what the wall setup looks like:
![Screen Shot 2022-06-28 at 8 44 30 AM copy](https://user-images.githubusercontent.com/1267134/176223035-8b3e04e1-e9f0-4213-ae1d-baf8b60812e2.jpg)

Notice how the closer wall endpoint is collinear with the token but the further one is not. Here is the LOS display:
![Screen Shot 2022-06-28 at 8 48 42 AM copy](https://user-images.githubusercontent.com/1267134/176223911-94fb99bc-333b-4929-a678-b610d53a7b51.jpg)

And this is the LOS points, wall location, and token location:

> _token.vision.los.points
> (16) [1000, 800, 5000, 800, 5000, 3800, 3940, 3800,  3200, 2612, 3612, 3275, 3939, 3800, 1000, 3800]
>
> _token.center
> {x: 2850, y: 2050}
>
> w.A
> PolygonVertex {x: 3200, y: 2612, key: 209717812, _distance: undefined, _d2: undefined, …}
> w.B
> PolygonVertex {x: 3612, y: 3275, key: 236719307, _distance: undefined, _d2: undefined, …}

I think this part causes the problem: 
{3940, 3800} --> {3200, 2612} --> {3612, 3275} --> {3939, 3800}

To me, these polygon coordinates appear correct, but the shadow line width is less than a single pixel, which is probably causing the visual artifact. See how it starts at the canvas edge at {3940, 3800} and returns to a point 1 pixel away, {3939, 3800}.

**Comment by aaclayton** [comment]
This is probably an issue with the geometry of the shader rather than a problem with the polygon itself. @Feu-Secret might have an opinion. It's such an edge case (literally) that I also think we can close this as wontfix if there isn't an obvious path forward.
