### ISSUE TITLE
Allow the search filter in Sidebar Directory instances to find folders in addition to documents

### ISSUE THREAD

**Issue by rsek** [foundryvtt/foundryvtt#7282]
consider the following document directory structure in v10:

<img width="317" alt="Screen Shot 2022-06-12 at 7 43 22 PM" src="https://user-images.githubusercontent.com/5354757/173270204-44455de7-ef22-455b-afc7-b49160ca2490.png">

the behaviour i'd expect is that searching "A1a" or "subsubdirectory" would include the corresponding subdirectory in its results. but, currently, this returns nothing. manually picking over a directory tree to find a specifc subdirectory is no fun!

### Priority/Importance
while it'd make the subdirectories much more usable for larger groups of items, it's not especially urgent. it's just more obvious that it's missing now that directories can be nested a few levels deep.

**Comment by Fyorl** [comment]
Bumping this to the next release at least as it's not immediately clear to me what the desired behaviour should be.

Presumably, if we match a folder, we want to see every item in that folder. Otherwise I would think just showing an empty folder is not useful.

But if we match lots of folders with our search term, then we diminish the usefulness of the search feature for finding documents themselves since we'll see many open folders with lots of documents rather than only the handful of documents that match our query.

**Comment by rsek** [comment]
> Presumably, if we match a folder, we want to see every item in that folder. Otherwise I would think just showing an empty folder is not useful.

maybe there's a way to make that useful? for example: on selecting a directory from the list of search results, the sidebar scrolls to, selects/highlights, and expands the folder if it isn't already open.

additionally/alternatively, the search results might display returned folders as collapsed by default, instead of open. then the additional clutter is 'opt-in' but search still provides some utility on that front

a more complex implementation might use different approaches depending on the number of returned results: if there's only a handful of results, show results as expanded. if there's lots, the directory results default to collapsed. that makes it lesss predictable to users, though, unless some explanatory label is provided (e.g. "Show 31 more results...").

perhaps the functionality of common desktop OS file/directory searches would be a useful avenue to investigate; i reckon that's the metaphor that any folder system on a web app is invoking, so there's a logic to being consistent with that, if only to take advantage of the familiar idiom. the context isn't totally the same, ofc, but maybe there's something useful to be gleaned?

**Comment by aaclayton** [comment]
I think what I would suggest that if the search string matches a folder, it displays all of the content inside that folder IF (and only if) it is currently expanded. So you would search for a Folder name which might be initially collapsed, but you could expand that folder and view its content directly from the filter result.
