### ISSUE TITLE
Support VisionMode ability to configure a custom visibility testing, activation, and deactivation methods

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7287]

**Comment by Feu-Secret** [comment]
Vision modes are now supporting: 
- An `activate` method, which is called when its linked vision source becomes active.
- A `deactivate` method, which is called when its linked vision source becomes inactive.
- A `testVisibility` method, which is called when testing this vision source for a subject object.
- A custom `testVisibility` method for our core tremorsense vision mode, which takes into account token elevation.
