### ISSUE TITLE
Add a clear (X) button in search/filter fields

### ISSUE THREAD

**Issue by YugoNumachi** [foundryvtt/foundryvtt#7313]
> Please describe with as much detail as you feel is necessary the feature which you are requesting.

It would be nice to have a clear button (such as an X at the right of the field) in search/filter fields that allows to clear/empty the field and reset the search/filter.

### User Experience

> Please describe what you feel the ideal user experience would be for interacting with this new feature.

Adding such a button allows to quickly clear a field, which is useful when searching for specific entries then getting back to the full list, or to quickly clear the field to allow a subsequent search.

### Priority/Importance

> Please describe your assessment of feature priority. If you feel it is highly important, describe why you believe it to be more important than other enhancements.

Not really a priority, it's more of a nice-to-have feature.

**Comment by paulohdsc** [comment]
Related issue: https://github.com/foundryvtt/foundryvtt/issues/5874

**Comment by aaclayton** [comment]
Closing this one as duplicate.
