### ISSUE TITLE
Improve the foundry.utils.randomID method to generate strings with mixed case instead of only lowercase IDs

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7317]

**Comment by itamarcu** [comment]
@aaclayton would it be too much to ask that this function is changed to never generate IDs that use I or l (i.e. uppercase i or lowercase L)?

It would greatly help to ensure that token IDs visually copied from sheet headers (e.g. in Wall config sheets) are always correct and have no ambiguity.  Usually it's not possible to easily copy the ID of things, especially if you want to do it mid-session.

**Comment by aaclayton** [comment]
> @aaclayton would it be too much to ask that this function is changed to never generate IDs that use I or l (i.e. uppercase i or lowercase L)?
> 
> It would greatly help to ensure that token IDs visually copied from sheet headers (e.g. in Wall config sheets) are always correct and have no ambiguity. Usually it's not possible to easily copy the ID of things, especially if you want to do it mid-session.

These identifiers are not really for human use, there are other ways to solve the problem of ensuring that you can reference an ID - and I'd like us to make UX improvements to make those IDs clickable that would copy them to clipboard also. These changes would help avoid the need for you to transcribe the ID manually.
