### ISSUE TITLE
Bright light and vision must be always as bright as the background color

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7323]
### Environment Details

* Foundry VTT Version: 10.270

### Issue Description

`colorBright` of normal light sources and vision must be always at least as bright than the background color; otherwise `colorDim` could be brighter than `colorBright`.

Bright light source with luminosity 0 on top (higher z-index) of a dark light source with luminosity -1:
![image](https://user-images.githubusercontent.com/31905376/174313751-2bcae662-f001-42e0-8894-1ac71d9712d2.png)

Dim light source with luminosity 0 on top (higher z-index) of a dark light source with luminosity -1:
![image](https://user-images.githubusercontent.com/31905376/174313827-6485cf58-aaae-4715-999b-465414a0258d.png)

```diff
- u.colorBright = [1, 1, 1].map(x => ll.bright * x * (1-penalty) * lumPenalty);
+ u.colorBright = [1, 1, 1].map((x, i) => Math.max(ll.bright * x * (1-penalty) * lumPenalty, c.background.rgb[i]));
```

```diff
- const colorBright = [1, 1, 1].map(x => ll.bright * x * (1-penalty));
+ const colorBright = [1, 1, 1].map((x, i) => Math.max(ll.bright * x * (1-penalty), c.background.rgb[i]));
```

**Comment by aaclayton** [comment]
Related to @Feu-Secret ongoing work on canvas color space management.

**Comment by dev7355608** [comment]
This hasn't been fixed.

Light source with luminosity 0 on top (higher z-index) of a dark light source with luminosity -1:
![image](https://user-images.githubusercontent.com/31905376/176999470-00256dfc-6871-4821-becf-043f8f532501.png)

**Comment by aaclayton** [comment]
I don't understand what I'm looking at here - but I suspect that Secret Fire probably does. We'll ask for clarification if needed.

**Comment by dev7355608** [comment]
It's easy to fix:
```js
// compute colorBright...
// colorBright = max(colorBright, colorBackground):
colorBright = Color.fromRGB(colorBright.rgb.map((c, i) => Math.max(c, canvas.colors.background.rgb[i])));
// compute colorDim...
```
