### ISSUE TITLE
Support "Windows" with a proximity threshold configuration for Walls which can allow those walls to become active or inactive based on the observer's proximity to the wall. Allow for attenuation where the visible distance changes with respect to proximity within that threshold.

### ISSUE THREAD

**Issue by apoapostolov** [foundryvtt/foundryvtt#7324]
The feature adds a new field to Walls, that limits transparency only to actors who are within a distance range from one of its endpoints.

> Please describe with as much detail as you feel is necessary the feature which you are requesting.

This would allow replicating realistic behavior of windows, semi-transparent surfaces that need to be checked from close, and more. 

> Please describe what you feel the ideal user experience would be for interacting with this new feature.

The GM sets a wall to not block sight and then sets a distance (30 feet) in a new field. The wall will be treated as transparent if the actor is within 30 feet of it. 

> Please describe your assessment of feature priority. If you feel it is highly important, describe why you believe it to be more important than other enhancements.

Low, but a great expansion to the Wall especially if combined with #5025 support for Window icons on walls that are configured as such.

**Comment by caewok** [comment]
Consider testing distance by measuring the [closest point on the wall](https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line) to the token, instead of the endpoints. I would probably use this test in `ClockwiseSweep` when testing for wall inclusion. If the wall is a "window" and the source origin is within X feet of it, then the wall can be culled from the set of edges for the sweep.

**Comment by aaclayton** [comment]
Follow-up work includes: 
- https://github.com/foundryvtt/foundryvtt/issues/8753 (for P1)
- https://github.com/foundryvtt/foundryvtt/issues/5025 (for P2)

**Comment by kanongil** [comment]
Can this also support "ledges", where it only applies to one side of the wall?

**Comment by caewok** [comment]
The windows implementation allows them to be used as one-way walls, which I think covers the "ledges" use case.
