### ISSUE TITLE
Improve the presentation of private dice rolls by retaining custom flavor text and displaying whisper recipients.

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/foundryvtt#7326]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: v9b269
* Operating System: All
* How Are You Using Foundry: All
* Which Game System: Starfinder, Simple World-building
* Modules Enabled?: no

### Issue Description

> Please provide a description of your issue below. Including console error messages, screenshots or videos can be particularly helpful.

If a single Gamemaster account is created in the world, any Private or Blind GM Rolls made do not show the flavor text as it does for a player.
If multiple Gamemaster accounts are created in the world, the Private or Blind GM Rolls show flavor text for the Private GM Roll.

For greater accessibility, the Gamemaster accounts should see the same flavor text for these roll types as the player does.

Recording of the behavior in the Simple World-building world is available at [https://www.icloud.com/iclouddrive/004Yd9rZq7b4znht7OwyNgFwg#Screen_Recording_2022-06-18_at_2.35.22_AM](https://www.icloud.com/iclouddrive/004Yd9rZq7b4znht7OwyNgFwg#Screen_Recording_2022-06-18_at_2.35.22_AM); the file was too large to upload to GitHub.

**Comment by avagdumortesin** [comment]
You can see in https://github.com/wildj79/foundryvtt-starfinder/issues/457 that there was text that appeared in v0.8.9, but after v9 the text no longer appears.

I have worked around this for the Starfinder RPG system by changing the CSS on the chat cards for the different roll types, but it is much more difficult to see the colors, and having a text will ensure that everyone is able to tell what type of roll it is; for a color-blind or hard of sight person, textual announcements are better.

**Comment by aaclayton** [comment]
I am not able to produce this problem either using chat or using the API.

###Chat usage:
```
/blindroll 1d6 # Some flavor text
```
![Image](https://user-images.githubusercontent.com/2468703/174702076-b1213062-dc29-4756-8562-8dcb4537c6d0.png)

### API Usage
```
const r = new Roll("1d6");
await r.toMessage({flavor: "Some flavor text"}, {rollMode: "blindroll"});
```
![Image](https://user-images.githubusercontent.com/2468703/174702207-04ba1565-4604-49c2-a69a-131b907849b2.png)

Please provide a clear and simple reproduction case for this issue.

**Comment by mattexdee** [comment]
@aaclayton, I am able to reproduce the issue I think @avagdumortesin is referencing, but it's related to the `XXXX privately rolled some dice` text which uses the same flavor text span element but is not what would *typically* be considered flavor text. I can see that when doing a `Private GM Roll` no text appears for the player or GM and when using the `Blind GM Roll` text appears for the player but not the GM:

![image](https://user-images.githubusercontent.com/5018947/174851080-0325f930-7cf2-408b-98b2-0cdf4de99ad6.png)

**Comment by avagdumortesin** [comment]
Also, if you look at the issue on the Starfinder system that I posted above, you'll see the first screenshot shows the text of what was in the dropdown when the roll is made. As long as that information is exposed in a way that can be called by the system, that would be sufficient for what I'm interested in.
