### ISSUE TITLE
Generalize the Drawing#objectId and Tile#objectId concept to apply to all PlaceableObject types.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7339]
### Environment Details

* Foundry VTT Version: 10.270

### Issue Description

All other `sourceId`/`objectId` getters use `this.document.documentName`, but `Drawing` doesn't.
```js
  get objectId() {
    let id = `Drawing.${this.document.id}`;
    if ( this._original ) id += ".preview";
    return id;
  }
```

**Comment by aaclayton** [comment]
`this.document.documentName` cannot be anything other than "Drawing", so I don't think this is a problem. I can change the code for consistency, but there should be no practical implication of this. If there is, it may indicate some other problem.

**Comment by dev7355608** [comment]
> `this.document.documentName` cannot be anything other than "Drawing", so I don't think this is a problem. I can change the code for consistency, but there should be no practical implication of this. If there is, it may indicate some other problem.

It's just an inconsistency I noticed when I was looking at all the `objectId`/`sourceId` getters. I wasn't sure if this is in fact a bug or if it doesn't really matter.
