### ISSUE TITLE
`Tile#refreshOcclusion` should call `refreshTile` hooks

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7341]
### Environment Details

* Foundry VTT Version: 10.270

### Issue Description

Any partial refresh should call the refresh hooks.

**Comment by aaclayton** [comment]
`Tile#refreshOcclusion` is called as part of `Tile#_refresh` which means the refresh hook will be called as part of that workflow. Are you observing that not to be the case? Can you provide more detail? Tentatively labeling this as `wontfix`.

**Comment by dev7355608** [comment]
`#refreshOcclusion` is called by `debounceSetOcclusion`. So `refreshTile` is never called when the occlusion state changes.

**Comment by aaclayton** [comment]
I need to think about this a bit. I assume the idea is that you want to do something to draw the tile differently based on whether it is occluded or not and so you want occlusion state changes to end up flowing through `Tile#refresh` so there is a hook event that occurs?

**Comment by dev7355608** [comment]
That's correct.

**Comment by dev7355608** [comment]
No milestone. Is this really a wontfix? I'd suggest to simply add the hook call at the end of `debounceSetOcclusion`. Probably not the prettiest solution though, but it is good enough.

```js
debounceSetOcclusion = foundry.utils.debounce(occluded => {
    this.occluded = occluded;
    this.#refreshOcclusion();
    Hooks.callAll(`refresh${this.document.documentName}`, this);
  }, 50);
```

**Comment by aaclayton** [comment]
Sorry, lost track of this - will look into it quickly.
