### ISSUE TITLE
Table results with compendium results not using configured compendium

### ISSUE THREAD

**Issue by CelestianGC** [foundryvtt/foundryvtt#7345]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: (Example 0.5.4)
9.269
 
* Operating System: [Windows, MacOS, Linux (which distro)]
Windows 10
 
* How Are You Using Foundry: [Native Application (Electron), Chrome, Firefox, Safari, Brave, etc...]
Native application

* Which Game System: (Example dnd5e)
OSRIC Advanced Roleplaying System 1.1.22 (also tested in dnd5e)

* Modules Enabled?: [yes, no] If yes, please list any which might be relevant
Yes, Compendium Folder and libwrapper

### Issue Description

> Please provide a description of your issue below. Including console error messages, screenshots or videos can be particularly helpful.

There a strange issue issue when I have multiple compendiums loaded, the tables' Compendium links get ... strange? 
I've got a Table in a compendium that has it's compendium result details to set to "adnd2e-mm.actors" and the text is the name of the Critter. 
If I load the module in a campaign with no other modules, it's showing the correct compendium. If I load up another that is higher up the alphabet the compendium location is changed to that one. in the current case my adnd2e-dmg.items so of course the tables break.
Here is a peek at the table data.

https://i.imgur.com/CfQ1uLg.png 

But the table in the campaign...
https://cdn.discordapp.com/attachments/722559135371231352/987618319521681408/unknown.png

Here is test in DND5e ruleset:
https://cdn.discordapp.com/attachments/872553681449537666/987846278597722152/unknown.png

**Comment by aaclayton** [comment]
Can you please provide us with a sequence of steps we can follow to reproduce this issue?

**Comment by CelestianGC** [comment]
> 

I must apologize for this erroneous report. As I was walking through a sample build to make sure I had the correct steps I noticed something in game.packs. The entries were "adnd2e-mm.actors" and the "collection" entries on the table results were "adnd2e-mm.actor" (note the missing s).

When the collection is not found it will pick the next available compendium in the list it CAN find and list that one instead so I was confused ;(

**Comment by aaclayton** [comment]
Okay, good to know thanks for confirming!
