### ISSUE TITLE
Consider using name field for ActiveEffects, instead of (or mirroring) label

### ISSUE THREAD

**Issue by BadIdeasBureau** [foundryvtt/foundryvtt#7349]
> Please describe with as much detail as you feel is necessary the feature which you are requesting.

### User Experience

ActiveEffects currently use a label field instead of a name field.  This means that getName does not function on the ActiveEffect collection, and generally means a weird mismatch between ActiveEffects and other document types (all other documents either have a name, or are types for which a name does not make sense, e.g. TileDocuments).

This is a small developer/macro writer QoL change, but a nice one for consistency - being able to use getName to reference an Active Effect by a friendly name would match the behaviour of other embedded documents on actors (this can, of course, be done with .find and a condition based on the label - but this is the only document type requiring that workaround).

### Priority/Importance

> Please describe your assessment of feature priority. If you feel it is highly important, describe why you believe it to be more important than other enhancements.

Constant minor irritation, easily worked around - low priority

**Comment by aaclayton** [comment]
Definitely a good thing to do as part of Active Effects Phase 2: https://github.com/foundryvtt/foundryvtt/issues/5842
