### ISSUE TITLE
Improve the UX on the Token Configuration dialog for tokens which does not represent an Actor

### ISSUE THREAD

**Issue by plutoneld** [foundryvtt/foundryvtt#7350]
It seems to me that when setting a Token to not represent an Actor ("Represented Actor" set to None), it would make sense to disable configuration options that no longer makes sense for that token.

The most obvious is to disable "Link Actor Data" on the Identity tab. To me, it also seems the whole Resources tab could be disabled.

**Comment by aaclayton** [comment]
Merging this issue with #7335 which probably prompted this discussion.
