### ISSUE TITLE
Implement a generalized PointSourcePolygon.testCollision method which replaces ClockwiseSweepPolygon.getRayCollisions.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7351]
## Implemented Changes

The way that collision testing is handled using the `PointSourcePolygon` has been generalized and refactored to reuse more code from the polygon class and to give subclass instances more control over custom collision tests.

**Example Usage**
```js
const p0 = token.center;
const p1 = {x: p0.x - 3000, y: p0.y - 3000};
const collisions = ClockwiseSweepPolygon.testCollision(p0, p1, {type: "move", mode: "all", debug: true});
```
![image](https://user-images.githubusercontent.com/2468703/174853667-9ff59b7e-6a4f-4c1b-80c8-7fd5afceffa8.png)

## Original Proposal Below

I'm proposing to add the point source as an optional parameter to `WallsLayer#checkCollision`, `ClockwiseSweepPolygon#getRayCollisions`, and `ClockwiseSweepPolygon#testWallInclusion`.

`ClockwiseSweepPolygon#create` gets to have the `source` parameter, so I think the ray casting methods should have also access to it too. In `ClockwiseSweepPolygon#initialize` we can add a boundary shape based on the `source` to limit the polygon in some way unrelated to walls, but `getRayCollisions` doesn't allow us to limit the rays in the same way.

Adding the source parameter to `testWallInclusion` would allow modules/system to override the wall inclusion test and decide based on, for example, the vision mode or elevation of the source whether a wall should be included. 

```diff
  // WallsLayer
- checkCollision(ray, {type="move", mode="any"}={}) {
+ checkCollision(ray, {type="move", mode="any", source=null}={}) {
```
```diff
  // ClockwiseSweepPolygon
- static getRayCollisions(ray, {type="move", mode="all", debug=false}={}) {
+ static getRayCollisions(ray, {type="move", mode="all", source=null, debug=false}={}) {
```
```diff
  // ClockwiseSweepPolygon
- static testWallInclusion(wall, origin, type) {
+ static testWallInclusion(wall, origin, type, source) {
```

**Comment by aaclayton** [comment]
I'll think about this, but I would prefer to go a different route I think. The polygon should be agnostic to its use case and everything should be passed in as parameters. 

I would like to think about whether there are alternative ways that we can support your use case on this. Could you describe what you're wanting to do and how having `source` as an optional argument to these methods would allow you to accomplish that (I assume you are overriding them)?

**Comment by dev7355608** [comment]
Perfect Vision's sight limited regions require to cast an additional ray that test whether the ray reaches its destination or if it stops earlier. Each token has a minimum sight distance though (half the token width). That's why I need access to the `source` in `getRayCollisions` in case the sight ray originates from a token source. `getRayCollisions` may not match the computed polygon for this reason.

Wall Height currently writes the elevation of the source into `origin` to be able to access the elevation of the token inside the `testWallInclusion` override. The module also overrides `Token#checkCollision` and `Ruler#_getRaysFromWaypoints` to add the elevation properties to the ray's origin. Drag Ruler was also forced to add the elevation to ray origins for compatibility with Wall Height. If the source was passed to `getRayCollisions` and then to `testWallInclusion`, these overrides would not be required and there wouldn't be a need to hack the elevation into the origin of the ray/polygon.
