### ISSUE TITLE
Consider adding `clearLayer` hooks

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7358]
`EffectsCanvasGroup#tearDown` calls `clear` instead of `tearDown` on the layers that define `clear`. There's no hook for `clear`. I'm not sure if `clearLayer` hooks are really necessary at the moment, because you could just hook `tearDownEffectsCanvasGroup`.

**Comment by aaclayton** [comment]
I think I would prefer to ensure that every layer correctly fires a tear-down hook, whether the process of "deconstructing" that layer involves clearing objects or deleting them is more of an internal implementation detail.
