### ISSUE TITLE
Tags/categories as a manifest field

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7360]
The tags feature of the package admin panel is great, but it's inconsistent with the rest of the package development experience since they can't be specified in the manifest. This also means that unlisted modules can't take advantage of them.
It also seems like the curated list of tags should perhaps be revised to include some more categories as the software progresses and this would help with that.

These are the tags that I'm referring to:
![admin panel](https://user-images.githubusercontent.com/82790112/174678301-44b9d969-31e2-4c90-93af-a2ac497802bf.png)
![module listing](https://user-images.githubusercontent.com/82790112/174678386-05f4fe9e-3b54-4427-91b6-72c2928ed67a.png)
![module installer](https://user-images.githubusercontent.com/82790112/174678499-220021e9-a865-481b-a4ed-91b7f928588d.png)

**Comment by aaclayton** [comment]
These tags are curated, in the sense that we only support them for packages which are approved and listed in our website repo and they are only displayed in conjunction with that data. Outside of this context it would not be clear to the developer what values to use for tags that would be compliant with the existing categorization scheme that the website offers. I don't think this suggestion is the right approach for us to take.

**Comment by arcanistzed** [comment]
To clarify, this suggestion has two parts:
 - Update the list of curated tags to include upcoming package categories
 - Allow those tags to be defined in enum field in the manifest that is validated to make sure that the tags are valid
 
 I didn't mean to imply that they shouldn't be curated.
