### ISSUE TITLE
Increasing chat log size increases CPU load for chat input

### ISSUE THREAD

**Issue by Weissrolf** [foundryvtt/foundryvtt#7373]
### Environment Details

* Foundry VTT Version: 0.9 - 269
* Operating System: Client Windows 11, Server: Synology DSM 7.1 + NodeJS v16.13.1-1006
* How Are You Using Foundry: Firefox, Chrome
* Which Game System: PF2, Simple World-Building
* Modules Enabled?: no

### Issue Description

This is mostly FYI: For testing the RNG I bombarded the chat input with hundreds and thousands of "/r d256-1" + {Enter} via Autohotkey script. To make sure that the roll string stays completely intact Autohotkey sent CTRL-V to paste the "/r d256-1" string from the clipboard, else single characters of this string would get swallowed at some point (see below).
![](https://i.imgur.com/1AXXa68.png)

The more the chat output is filled with roll results the higher CPU load increases (and memory usage) and the more Foundry's chat input is unable to keep up with the input, swallowing/ignoring input characters as a consequence. Increasing the pause between CTRT-V and {Enter} mitigates the problem, but the pauses also have to increase more and more to make up for Foundry being overload. This seems like a chat input issue more than a chat output issue as one can see the input slowing down displaying input characters even before a new line of chat output is printed (Enter).

- Clearing the chat log fixes it. The larger the log the longer it takes at full CPU utilization, though (browser tab freezes so hard that Chrome asks to close it) and memory consumption even increases by this. All while the messages.db file is only 2500 kb small.
![](https://i.imgur.com/7PVJKak.png)

- Reload fixes it, likely because this only loads a small part of the chat log (unless you awkwardly fiddle with the scroll-bar).
![](https://i.imgur.com/JxnEoIN.png)

- A long pause (stopping the input) to give Foundry a chance to catch-up does *not* fix the CPU load issue. Instead the long waterfall of error-messages from a swallowed {Enter} inputs causes memory consumption to keep increasing until all messages are finally displayed. Waiting several minutes after all error messages are finished sees memory consumption drop slightly.
![](https://i.imgur.com/STOQvTr.png)
![](https://i.imgur.com/tY0Xvrh.png)

- Pressing modifier keys makes it worse, especially the combination of multiple keys (CTRL+ SHIFT) or pressing the ALT key, at one point the whole Foundry output freezes (no Chrome popup, though) for while the key is held down and then takes several seconds to unfreeze after the key is released.

**Comment by kandashi** [comment]
So the outcome of this is: 
Massivly overloading the expected capacity of the software causes issues. 

Im not sure what the takeway is.

**Comment by Weissrolf** [comment]
It is information. Make of it what you will and be aware that very long sessions with large chat logs may suffer CPU load and garbage collection issues with the chat log. I know you people despise "inapplicable" feedback, but that's your own business.

For players (especially on weak computers) this can be worked around by doing a reload or clearing that chat log from time to time.

**Comment by aaclayton** [comment]
It is a know limitation that Foundry VTT does not handle "infinite chat" well currently. At some point the expectation is that you will flush your log, either export it to disk or just delete it. 2500kb is probably around 2500 messages, as I've commonly observed in the past that the average chat message is usually around 1kb. 

The issue is not the size though, the issue is that 2500 messages means hundreds of thousands of DOM elements (especially if you start scrolling back) and at some point the browser is just going to freeze up. 

Anyways, thanks for your report and sharing this information - but there isn't anything we plan to do differently here at this time.

**Comment by Weissrolf** [comment]
The chat seems to be the weak spot of Foundry, it uses relatively large resources, both in memory and CPU. In the long run Foundry should try to better keep it in check without the need to reload the browser tab first. Clearing the chat log alone only works if the log is small enough, else Foundry/browser gets stuck at max CPU load trying to clear the log window even when the messages.db file is already emptied to zero.

Here is a demonstration of Foundry doing nothing at 100% CPU load, no rolling, no anything, but *after* having rolled a D256-1 a few thousand times. No chance to clear that chat log without doing a reload first, the file is emptied but the browser tab gets stuck endlessly.
![](https://i.imgur.com/CqLoMrS.png)

Reload causes Foundry to limit the chat to a maximum number of messages (DOM elements) unless you repeatedly (and awkwardly) scroll up/down/up via the scroll-bar. Maybe Foundry could implement this old messages to vanish similarly while a game is running, without the need to reload first?

For my personal dice rolling (RNG) tests I will use click-rolling now, because that circumvents the problematic chat input lag/swallowing of input keys.

**Comment by aaclayton** [comment]
If you're trying to test dice rolling, I'd recommend using `Roll.simulate(formula, number)` instead of using chat.

**Comment by Weissrolf** [comment]
Thanks for the hint. I did not find any documentation on that via web search, though, and creating a quick macro with just that line does nothing.

Using chat and real buttons is closer to how rolling works in practice. Since this is kind of a QA thing, using the same buttons that players use makes sense. This also includes running into the same problems, like the chat log performance limits.
