### ISSUE TITLE
Remove space in entity links inserted after the icon and before the text

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#7376]
It seems entity links (or content links) insert a space at the beginning of any text immediately after the icon. This is difficult to style, especially for custom journal entry styles.

### User Experience

When styling content links in journal entries (or anywhere), an extra space inserted at the beginning of the text node makes styling difficult. That space should not be there. If spacing is needed after the icon, then please consider applying styles to the icon itself.

### Priority/Importance
 This can cause links in journal entries to look weird, especially in cases where there might be two links in a row such as `link 1/link 2` which ends up looking like `link 1/ link 2`.

**Comment by Fyorl** [comment]
Thanks, I'll take a look.
