### ISSUE TITLE
Add more CONFIG.Canvas constants that replace constants used in zooming/panning

### ISSUE THREAD

**Issue by itamarcu** [foundryvtt/foundryvtt#7382]
Currently, `CONFIG.Canvas` has several nice constants that may be changed by settings/modules.  For example, `maxZoom: 9`, `objectBorderThickness: 4`, `blurStrength: 8`.

However, there are more places in the code where hardcoded values are still used.  I'd like you to add the following (final naming is up to you):

Canvas#_onDragCanvasPan - replace with: `CONFIG.Canvas.edgePanningPadPixels: 50`, `CONFIG.Canvas.edgePanningShiftMultiplier: 3`
```js
    // Shift by 3 grid spaces at a time
    const {x, y} = event;
    const pad = 50;
    const shift = (this.dimensions.size * 3) / this.stage.scale.x;
```

Canvas#_panCanvasEdge - this uses the same constants too but is actually never used.  consider removing this function

Token#setPosition - same pad constant
```js
    // If the movement took a controlled token off-screen, re-center the view
    if ( this.controlled && isVisible && recenter ) {
      const pad = 50;
```

Canvas##constrainView - add `CONFIG.Canvas.zoomRounding: 100`  (this will also fix #7189)
```js
      scale = Math.round(Math.clamped(scale, 1 / ratio, max) * 100) / 100;
```

### Priority/Importance

Medium/low - some of those changes are required to avoid breaking my [Zoom/Pan Options](https://github.com/itamarcu/ZoomPanOptions) module (and in fact, would make the code there **much** simpler).  However, I expect the changes to be very quick to implement.  Trying to verify that all instances of the hardcoded values were found and replaced is the only step that might take a little while.

**Comment by aaclayton** [comment]
@itamarcu can you elaborate on the use case for configuring the `pad` and `multiplier`? I'm not sure I see why these need to be configurable.

**Comment by itamarcu** [comment]
They're not necessary but:
1. I personally wanted to override them as I felt that the pad and multiplier were too large - I prefer having the screen pan in smaller increments when something is dragged to the edge.
2. These are the only other arbitrary hardcoded constants I've seen in the canvas code I interacted with

**Comment by aaclayton** [comment]
Unfortunately there are many such arbitrary constants, becuase our codebase is quite large. I don't think it's realistic for us to offer CONFIG variables for every such example. I think adding CONFIG for this tier of thing is beyond the scope of how I envision us expanding the API at this time.
