### ISSUE TITLE
Allow configurable headers for Journal Entry Pages

### ISSUE THREAD

**Issue by moo-man** [foundryvtt/foundryvtt#7395]
Allow users to define what type of header a JournalEntryPage title uses.

### User Experience

When creating a Journal Entry, each page I create is forced to use `h2` when displaying its title in the Journal Entry. I may want a certain page to be `h3`, `h4`, or even have no title, see the example.

![image](https://user-images.githubusercontent.com/28637157/176041456-3949528e-3953-40ec-97e3-7866194010c4.png)

### Priority/Importance

I think this is a pretty important content creation feature that helps with the overall design, organization, and flexibility of using Journal Entries.

**Comment by Fyorl** [comment]
This has actually been changed to an `<h1>` tag now, as part of the work for #7285. Given that we're generating a table of contents based on the heading hierarchy, and you can now link between headings, it's a bit more complicated (not impossible) to have an arbitrary start level, so I'd like to understand the use-case a bit more. For example, why can the 'Note' here not be rolled up into the 'Content' page above it? If it's a small note, presumably it's related to the above content in some way and not a total non-sequitur?

**Comment by moo-man** [comment]
Yeah, I haven't really begun the conversion process for these adventures so I haven't really found my optimal organization preferences.

To be clear about the header stylings, `h1` isn't shown in the images, which is actually rarely used. I set them up to where `h1` is the "chapter heading" but is generally not used as chapters are the journal entries themselves (or even folders).

![image](https://user-images.githubusercontent.com/28637157/176236654-87b87c81-eb46-44a3-9590-16afbc104a77.png)

![image](https://user-images.githubusercontent.com/28637157/176236999-c64620cb-87c9-4289-b8b1-8bc530bbee4f.png)

In my modules I *generally* separate journals based on `h2`, and planned in V10 to have chapters be journals and `h2` be pages, I may need to shift the styling of them all upwards to reflect `h1` being used instead. 

I don't mean to get into the weeds of my methods though, regardless, my main concern is probably the 2nd point, where I can decide "what is its own page" based on "if I want to link to it" instead of "how the headers will look." 

Anyway, I am excited to try out Dev 2!
