### ISSUE TITLE
Allow sheet registration to provide a canBeDefault parameter that controls whether it can be set as a default sheet for a given Document sub-type

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#7401]
Some sheets are meant for very specific purposes, so setting them as default sheet is always an error. It'd be as such handy if sheet registration could optionally define the sheet is not allowed to be default.

For example sheets that are for an item or actor type Foundry can't identify as they're sub-identified by additional info in the system data.

### User Experience

Sheet is not available in default sheet options.

### Priority/Importance

Low.

**Comment by zeel01** [comment]
This would also be useful for certain module sheets intended to be used only with the documents that module provided. As an example, the dScryb module Journal sheets should not be used with standard JournalEntry documents, so it has no place ever being set as the default sheet.

**Comment by kvndrsslr** [comment]
This is also a relevant capability for premium content providers.
Our custom styles are only applicable to our custom Journal sheets, so we hide the button in the header to change sheets. That means if users ever select our sheets as default, they might not be able to figure out how to reset it.

**Comment by zeel01** [comment]
There's also the issue that sometimes a custom sheet has an expectation that certain additional data exists on the document in `flags`. It's not desirable to always instantiate this data on any document opened by the sheet, nor is it always practical to check every piece of data that the sheet anticipates. But if this leads to an error while rendering, you can end up in a situation where no documents will actually open at all, making it impossible to open the sheet config.

In the case of premium content, it may also be against brand guidelines to allow users to create custom content using the trade dress of the premium content. So a mechanism to disable this would be useful in that context as well.

**Comment by Fyorl** [comment]
We can potentially do this as part of #7521
