### ISSUE TITLE
Attempting to update to a V10-ready package throws an uninformative error in V9.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7404]
Originally reported by Skimble#8601 https://discord.com/channels/170995199584108546/956306859491471420/990433480745816104

> A user attempted to install an update to fate-core-official while on version 10.260 and got a strange error rather than a message that the update wasn't compatible with the version of Foundry they were running. This was on self-hosted Electron on Windows. The error was 'k is note defined' - see screenshot of report to me below.

> Once they updated Foundry to v10.270, they were able to install the system update as you would expect.

![image](https://user-images.githubusercontent.com/207433/176910375-0f48de13-4491-4dca-b24e-afc33e42d56c.png)

**Comment by aaclayton** [comment]
I'm not sure if this is an active bug or not. @mattexdee could you reach out to Skimble and see whether there is a current module or system that generates this error? I do not produce an error with `fate-core-official` using <https://raw.githubusercontent.com/Sk1mble/fate-core-official/v4.4.07/system.json>

**Comment by aaclayton** [comment]
@mattexdee could you clarify - when attempting to install this particular manifest in V9, which is the field that is not defined?

**Comment by mattexdee** [comment]
@aaclayton I don't think any of the fields aren't defined (I see a name, title, and version in the manifest). Based on Arcanist's description it sounds like there's a variable `k` in `getManifest` (`package.mjs` line 614 in V9) that is used in the error message but is not defined. This is the error message I'm getting in V9:

![image](https://user-images.githubusercontent.com/5018947/177640764-8b1a4271-75f5-41b3-be57-c0f659aa8008.png)

and the console log:

```js
setup.js:265 ReferenceError: k is not defined
    at Function.getManifest (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7288)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async checkPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1295)
    at async Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3053)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1757)
```

Looking at that method though it looks like `k` is defined as far as I can tell but the error message definitely indicates that it's not. If one of the fields were missing it should return an error like `Required field ${fieldName} not present in ${manifestPath}` not a `ReferenceError`.

**Comment by aaclayton** [comment]
Created a V9 milestone for us to consider whether there is anything we should do here.
