### ISSUE TITLE
Changing performance modes makes all placeables on the canvas invisible

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7411]
Originally reported by LebombJames#1611 https://discord.com/channels/170995199584108546/956306859491471420/992406352485949481

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** NodeJS self-hosted, Windows 10  
**Short Description of bug:** Changing performance modes makes all placeables on the canvas invisible  
**Simple steps to reproduce the bug:** 
1. Have any number of placeables on the canvas (tokens, lights, drawings etc)
2. Change performance mode (I changed between High and Maximum)
3. All placeables will disappear. In this state, all placeables can be placed, but will remain invisible. The exception being drawings, which fail and throw the 1st below error.
4. Changing performance mode further throws another error (2nd error), this state is only fixed on reload.

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/176913465-37b0df1f-8ad9-4ed7-b9f3-ad34fc241d02.png)

![image](https://user-images.githubusercontent.com/207433/176913480-bb5de5da-a5ca-4d2a-a9f9-4a5940a4de3b.png)

**Comment by aaclayton** [comment]
I'm not able to reproduce this issue, @mattexdee could you perhaps work up some reproduction steps for me?

**Comment by mattexdee** [comment]
Confirmed as non-repro. The user had accidentally done their testing in V10D1 and not V10D2 where they say the issue is not occurring: <https://discord.com/channels/170995199584108546/956307084931112960/994403137584648232>
