### ISSUE TITLE
Translation of New User Experience chat messages is not working

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#7414]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: V10 D2
* Operating System: Windows
* How Are You Using Foundry: Electron
* Which Game System: Any
* Modules Enabled?: Yes - Russian Translation (ru-ru)

### Issue Description

In V10 the following NUE messages show up in English in the chat when you create a new world:

- NUE.FirstLaunchBody
- NUE.FirstLaunchHeader
- NUE.FirstLaunchHint
- NUE.FirstLaunchInvite
- NUE.FirstLaunchInviteBody
- NUE.FirstLaunchKB
- NUE.FirstLaunchTroubleshooting

It works correctly in V9, so that's a regression.

**Comment by aaclayton** [comment]
@phenomen did you intend to close this?

**Comment by phenomen** [comment]
@aaclayton Yes, it was my mistake. I opened the world before changing the language, and after I changed it, the messages were still in English. But that's how it is since messages are saved in the world db already and won't be re-translated on language change.

It works fine if you change the language _before_ creating the new world.
