### ISSUE TITLE
Decrease `circleVertexEpsilon` in order to increase the fidelity of circle approximation.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7418]
### Environment Details

* Foundry VTT Version: 10.272

### Issue Description

The polygonal shape is clearly noticeable in the case of small light sources or with low attenuation light sources or at intersections of dark and normal light sources. Even at maximum performance mode. 0.3 would be a good value for `circleVertexEpsilon`.

Also I don't think it's a good idea to set `circleVertexEpsilon` based on the performance mode, because it affects the visibility state of tokens etc. A player with low performance mode won't see some tokens that players with higher settings do in certain situations. I can see this causing a lot of confusion. Imagine the GM (low performance mode) wondering why their player (high performance mode) are able to see and target a token that is not visible if they select the player's token.

**Comment by caewok** [comment]
I agree that at the moment, the density can affect visibility in rare cases. If #7259 is resolved, this may cease to be an issue because the polygon approximation would use the exact circle-poly intersections.

**Comment by dev7355608** [comment]
To add to this: lowering the `circleVertexEpsilon` doesn't really do much, because of the rounding in `toClipperPoints` (because of the lack of upscaling/downscaling). Both of these circle are generated with `circleVertexEpsilon = 0.3`. The first circle is not rounded, the second is. The rounded circle is clearly not particularly smooth in comparison.

![image](https://user-images.githubusercontent.com/31905376/179575919-4aa48e1d-df5c-42bb-a748-798df1f60714.png)
![image](https://user-images.githubusercontent.com/31905376/179575985-8f7cc517-ceac-48ca-83c9-6d3e83348bbb.png)
