### ISSUE TITLE
Enable a way for wall restriction vision to be applicable for some pcs and not others.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#7445]
> what id like is an option within a scenes settings that would show the pcs in a list and allow for vision restrictions to be on or off per selection of the players. with the default being as it is. 

I have a situation where i would like to limit vision on two players but for the other players to see the whole map.

the situation is an arena style map but i cannot do what i intended above. it would be nice to have these options per scene for these occasions. 

### User Experience

> have a menu in the scene settings that shows all the players or PC actors owned by users and a way of selecting them for vision not being restricted.

### Priority/Importance

> low

**Comment by aaclayton** [comment]
This can be accomplished by new V10 vision modes.
