### ISSUE TITLE
Vision source saturation did not behave like light source saturation.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7446]
### Environment Details

* Foundry VTT Version: 10.272

### Issue Description

Desaturated vision (darkvision) gets a blue tint from the darkness color. But it should be grayscale just like desaturated light sources.

![image](https://user-images.githubusercontent.com/31905376/177667372-8b323f6b-58ce-44df-bba1-8f39ee5efda3.png)

**Comment by aaclayton** [comment]
I was reviewing this issue today and I do not really understand what is being described in the initial issue. You provide a screenshot without any explanation of what is shown in the screenshot. I don't know how to interpret this to understand what you believe the issue to be.

**Comment by dev7355608** [comment]
Top-left: standard light source.
Top-right: standard light source except that Saturation is -1.
Token: vision with Saturation -1.

Expected Behavior: If Saturation is -1, vision is grayscale.
Current Behavior: Desaturated vision is not grayscale but has the tint of the darkness color.

**Comment by Dumbhuman** [comment]
I'm not sure if this will help clarify things any, but I also wanted to voice support for having darkvision free from any color tinting.  I decided to make my underdark assets have a very slight blue tint that wouldn't show while using darkvision (to make it just a little more obvious when/where actual light is being used in a scene).

I expected this would look something like this mockup in Clip Studio Paint.  Kobold with Darkvision on the right overlapping with an area of light to the left. 
![image](https://user-images.githubusercontent.com/63615591/186502985-6f073a69-4a9f-45b8-b3fd-6c33882359fe.png)

Here's a screenshot from the latest Foundry v10 build running DND 5E with scene darkness set to 1 and standard darkvision.
![image](https://user-images.githubusercontent.com/63615591/186503493-3124ca6a-d8ee-4423-b665-06386d5995e6.png)

In-game, the area of darkvision seems to add quite a bit of blue saturation.

**Comment by Feu-Secret** [comment]
Fixed!
