### ISSUE TITLE
Add the ability to create map notes which link to specific headings elements within a JournalEntryPage.

### ISSUE THREAD

**Issue by zeel01** [foundryvtt/foundryvtt#7448]
### User Experience

In addition to the new map pins that can link to specific Journal pages, and the new document links which can link to specific headings within a Journal, it would be great if map notes could also link directly to headings. 

I've shown v10 Journals to a number of people, and one of the first questions I get is whether or not this is possible. Generally, map notes are seen as roughly equivalent to document links in journals or chat messages, so there is an intuitive assumption that  they would have the same capabilities.

This is especially true when you consider the drag/drop workflow, where you *can* drag a heading link to another journal or a chat message, but if you drop a heading onto the canvas, you only end up with a link to the page that contains the heading. 

As a specific use case, in many books it is common for a scene to be represented by an `h1` level heading "The Inn" while locations on the map are represented as `h2` headings "The Bar", "The Stairs", "The Back Room", "The Kitchen." Since map locations are one of the primary uses for notes, it would be ideal if they could link directly to these places without the need to "promote" these headings to be full top-level pages. 

### Priority/Importance

It would be really nice if this could be added in v10. I wouldn't be surprised if some users think there is a bug when it doesn't work. It would also make things easier for content creators and publishers that want to bring content to v10 and take full advantage of the new features. That being said, there are ways to work around not having it, such as promoting the headings or creating a module that adds this functionality. 

As an alternative to this suggestion, I have created this issue: #7447 regarding potential API improvements that would allow adding this functionality and others within a module or system much easier.

**Comment by roguedevjake** [comment]
Seconding this.

**Comment by SethGallucci** [comment]
This feature is sorely needed by me in order to be able to use the new journal system to organize an upcoming campaign that I plan to run. As such, I've cobbled together a crappy, little module that adds this functionality with lib-wrapper. In case anyone, like myself, isn't able to wait for the feature to be implemented, here's the module: https://github.com/SethGallucci/Notes-with-Anchors

**Comment by roguedevjake** [comment]
> This feature is sorely needed by me in order to be able to use the new journal system to organize an upcoming campaign that I plan to run. As such, I've cobbled together a crappy, little module that adds this functionality with lib-wrapper. In case anyone, like myself, isn't able to wait for the feature to be implemented, here's the module: https://github.com/SethGallucci/Notes-with-Anchors

The journal anchor links module does this as well, as does the D&D Beyond importer module (the latter will sadly mean that many people won't even notice what a deficiency the program has, hopefully this gets signal boosted enough)

https://github.com/aMediocreDad/jal/

**Comment by MrPrimate** [comment]
> > This feature is sorely needed by me in order to be able to use the new journal system to organize an upcoming campaign that I plan to run. As such, I've cobbled together a crappy, little module that adds this functionality with lib-wrapper. In case anyone, like myself, isn't able to wait for the feature to be implemented, here's the module: https://github.com/SethGallucci/Notes-with-Anchors
> 
> The journal anchor links module does this as well, as does the D&D Beyond importer module (the latter will sadly mean that many people won't even notice what a deficiency the program has, hopefully this gets signal boosted enough)
> 
> https://github.com/aMediocreDad/jal/ 

The DDB Importer module will also use/create the same flags as JAL

**Comment by aaclayton** [comment]
We have strong reasons to associate map notes with pages. This allows a direct document relationship where the linked document has its own granular permission control which associates directly to whether an observe has permission to see the pinned map notes. 

I understand that people can use the new journal system however they want to use them - but it is our design intention that different locations within a scene be different pages of a journal entry, not different headed sections of a page. 

I understand that many of you will disagree, but that is the way we have designed the system. Intentionally.
