### ISSUE TITLE
ClockwiseSweepPolygon bug

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7449]
### Environment Details

* Foundry VTT Version: 10.272

### Issue Description

![image](https://user-images.githubusercontent.com/31905376/177778112-c7eb7ae1-e073-4d74-9bd8-b4743a3cdd17.png)
![image](https://user-images.githubusercontent.com/31905376/177778810-90a8a37e-45bd-4ed9-8e5c-6150a9ed375a.png)
[fvtt-Scene-polybug.zip](https://github.com/foundryvtt/foundryvtt/files/9063746/fvtt-Scene-polybug.zip)

**Comment by caewok** [comment]
Pretty sure this is a problem with ray endpoints getting added erroneously. Try changing the radius in `ClockwiseSweepPolygon.prototype.initialize` to:
```js
cfg.radius2 = Math.pow(canvas.dimensions.maxR, 2);
```
(`radius2` controls the LOS ray lengths, so you don't really need to change the other radius configurations.)

**Comment by aaclayton** [comment]
I can confirm that firing rays with the maxium distance does solve the problem. Might take a little performance hit because of it, but accuracy is worth the tradeoff I think.

**Comment by caewok** [comment]
I doubt it will be much of a performance hit because sweep is already removing edges outside the radius. But if it is, we can revisit providing a better distance to use. The distance to the corner of the bounding box + 1 might work.
