### ISSUE TITLE
Select Toolbar Favourites 

### ISSUE THREAD

**Issue by bland-html** [foundryvtt/foundryvtt#7453]
> I think this would be a big QoL feature for a lot of GMs. Being able to select favourite tools and having them list out on a _favourites menu_ on the sidebar, would be extremely helpful.

### User Experience

> I imagine just above the Token Controls, there is a Star. In that menu, the tools populated are ones selected as favourites. I'm not sure if the selection can be done through a setting or through right clicking the different tools to mark them as favourites. Note, this would not remove them from their original menus obviously. Just re-populate them in the starred menu.

### Priority/Importance

> Since it's just a QoL, probably not a huge thing. It would take some work too. But could be a very useful QoL for a lot of people.

**Comment by aaclayton** [comment]
I'm afraid that having "favorite" scene controls is more than just an organizational concept because the different control palettes correspond to different canvas layers being the active target for user interaction. Having favorite tools per canvas layer would not be all that valuable really.

**Comment by bland-html** [comment]
Ahh, I didn't think about that "different layers" aspect. I guess that does make it way more complicated. Thanks for taking the time to address the suggestion.
