### ISSUE TITLE
Use `input[type="search"]` for core search input fields

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7455]
### User Experience

The search bar in the module management app, the search bars at the top of the sidebar tabs, and the ones on the setup screen should use the semantically correct `input[type="search"]` element. Not only is this better for accessibility, but it also allows the user to easily clear their current query if they want to restart their search.

Related to #7454

### Priority/Importance

> Medium

Accessibility improvements are always important

**Comment by paulohdsc** [comment]
Related: https://github.com/foundryvtt/foundryvtt/issues/5874
