### ISSUE TITLE
AV Refresh Feedback

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7457]
Originally reported by bekit#4213 https://discord.com/channels/170995199584108546/956307084931112960/986107597750935583

My quick feedback of v10 AV based on a bit of time playing around with it:

\+ It does look a lot cleaner. I'm not sure what all was done here, but the whole look is just a bit sharper and I like that
\+ I like the breaking out of AV controls from the GM window. That was getting too cluttered, and it's nice to have these separate. I do slightly worry about things still getting cramped here if any additional buttons are added (for instance, I add a "connect/disconnect" button for livekit). However, where it is now I could have it extend to a second line if needed.
\+ Overall, I'm glad this is getting attention because I haven't had time to work on the UI of the AV very much, and I think it does need improving. Thank you to @Kim for taking this on!

\- I don't like that there's a scrollbar when you get too many video windows. The benefit of in-game AV is being able to see everyone you are playing with at once. I can say from my server metrics that there are several folks playing with 7+ users and this isn't going to work for them at all.
\- The new version takes up a lot of screen real estate. The benefit of the old layout is that it scaled to the number of users quite well. Having a constant dark grey bar on the side of the screen isn't great, especially for those with smaller screens.
\- The new layout is probably going to make it harder for something like WebRTC Tweaks to work for moving the video windows to any side of the window. Each of my players has their own preference on where they like their video, so a UI revamp that didn't include the ability to choose the attach point for the video is going to be a problem for my players. Yes, you can pop the windows out - but then you have to place each window. I just want to move the attach point and have the layout work from there. Also, see my comment on the grey bar that doesn't go away even with everything popped out. I personally like a horizontal top layout 🙂
\- The new layout doesn't handle some of the requests I've seen here, and directed at me, several times - namely the ability to not send/receive video on a case-by-case basis (as @Atropos mentioned above), the ability to hide the video windows of individual users completely (think about OBS recording windows signed in as a "player" type user), or better UI for Audio-Only setups or Audio-Only users.

+/- I'm not sure why user border colors is an option, especially a per-user option. My suggestion would be to just enable this by default.

I think change is good and I'm glad this is getting some attention. I do worry that it's going to end up being a controversial change, and ultimately that affects my modules as well. I get not wanting to maintain multiple versions of the UI, but that's also the position I'm being put in if I want my module to work with v9 and V10 (I already had to drop support for v8 and below because of recent changes that I needed to make to the Config page that don't work on the older versions).

Since I'll have to maintain two versions of the UI anyway, I'll probably do as @Lektu suggested and add an option to flip between them. The alternative for me will be to take one UI and make it flexible enough for everyone (including myself and my players) to get the layout that they need.

In the meantime, I've made v10 support work with LiveKit again by disabling a couple of my features on that version until I get a chance to figure out how to handle the rest.

**Comment by Fyorl** [comment]
Most of these have been considered and either rejected or already included in the latest Testing release. The one outstanding feature that we haven't started work on yet is the ability for users to choose which edge of the application window to pin the AV dock to.

**Comment by aaclayton** [comment]
@Fyorl let's try and include the option to swap the dock between left/bottom in time for the V10 release if possible.
