### ISSUE TITLE
Call Document CRUD hooks with an inheritance chain (similar to Application render hooks)

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7459]
### User Experience

For example, instead of only a `createActor` hook, there would be a chain of hooks called (i.e. `createDocument` > `createActor` > `createActor5e`). This is useful if you want to hook into all Document updates or only updates from your own custom subclass of Actor. Of course, this would also apply to all of the other CRUD hooks and other Document types.

### Priority/Importance

> Low

While this is not very important, it would help some module/system developers and adding new hooks is completely non-breaking

**Comment by aaclayton** [comment]
Can you share some perspective on your use case for why you want this?

**Comment by arcanistzed** [comment]
The use case someone had in The League was to hook into Document creation for all Document types. I suggested creating this issue because I think that these hooks would be potentially generally useful.

**Comment by aaclayton** [comment]
> The use case someone had in The League was to hook into Document creation for all Document types. I suggested creating this issue because I think that these hooks would be potentially generally useful.

I realize that it's a number of hooks to register rather than one that catches everything, but I would prefer that user to register hooks for every primary Document type ( for example iterating over `CONST.DOCUMENT_TYPES`) explicitly rather than register one catch-all.

**Comment by ghost91-** [comment]
It’s not just the primary document types though, it also applies to documents that only exist in embedded form. And at the moment, there isn’t even a constant that lists all of them. Maybe that should be added at least, then…?

**Comment by aaclayton** [comment]
> It’s not just the primary document types though, it also applies to documents that only exist in embedded form. And at the moment, there isn’t even a constant that lists all of them. Maybe that should be added at least, then…?

Which embedded documents are available for each primary document is available as `Document.metadata.embedded`, e.g. `Actor.metadata.embedded`

**Comment by ghost91-** [comment]
True, but that means, if want to register hooks for all of them, you need to iterate over all of the primary documents, and then over the embedded types. And then Filter for duplicates. I guess it’s not a big deal, but I would find it more consistent if there was something similar to `CONST.DOCUMENT_TYPES` also for the embedded documents. But it’s not terribly important.

**Comment by arcanistzed** [comment]
> I realize that it's a number of hooks to register rather than one that catches everything, but I would prefer that user to register hooks for every primary Document type ( for example iterating over `CONST.DOCUMENT_TYPES`) explicitly rather than register one catch-all.

What if a user wants to only register a hook for `createMyCustomCombatant`? There are several modules which add their own Document subclasses or mixins. You might say that they should just add an `instanceof` conditional and use the generic `createCombatant` hook, but this solution and the one you presented above are both obviously less ergonomic and unnecessarily complex.
Essentially, this feature suggestion is for QoL and, since adding new hooks is completely non-breaking, it should be worth it for that reason alone.

**Comment by aaclayton** [comment]
```js
Hooks.on("createCombatant", (doc, data, options, userId) => {
  if ( !(doc instanceof MyCustomCombatant ) return;
  // ...
});

**Comment by arcanistzed** [comment]
Yeah. That's exactly what I said you might say to use...

I don't think that either of these solutions are ergonomic. There is already precedence in the API for the hooks to be called up the inheritance change and I actually thought that they did until yesterday. It just seems obvious to me that this change could be added to improve DX & QoL, without any negative side effects.

**Comment by aaclayton** [comment]
> without any negative side effects.

Traversing up the inheritance chain and calling hooks for every parent class isn't free, especially when it would happen for every document operation. For me, the benefit does not outweigh the cost which is why I've closed this as wontfix.
