### ISSUE TITLE
[V10 - TinyMCE] Injecting HTML into the DOM breaks TinyMCE behavior

### ISSUE THREAD

**Issue by DarKDinDoN** [foundryvtt/foundryvtt#7460]
### Environment Details
* Foundry VTT Version: V10 prototype 2
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: dnd5e
* Modules Enabled?: yes: https://github.com/DarKDinDoN/share-media/

### Issue Description

Updating https://github.com/DarKDinDoN/share-media/ to V10.

This module Hooks into `renderActorSheet`, find any textarea field, then find any img or video tags within, then wraps them inside a div.
Hover over this newly created DIV displays some buttons, as shown on the following screenshot (note that the field is not being edited):
![image](https://user-images.githubusercontent.com/1687854/178076046-8f691ee1-06b0-4e74-9e11-1971c20eba11.png)

Now, when I edit this field for real (TinyMCE), the editor displays not only the field content but also the injected HTML. The red part **was not persisted**, it's just the HTML I injected in the DOM when the field was not edited but simply displayed:
![image](https://user-images.githubusercontent.com/1687854/178076242-1bb95f37-6325-4c9d-9519-851486469eb5.png)

Here is how I do it: https://github.com/DarKDinDoN/share-media/blob/main/modules/media-wrapper.js#L11

**Comment by aaclayton** [comment]
Interesting. I would expect that an editor instance should be constructed using the true source data for the document rather than the HTML which happens to be present in the non-editable page.

**Comment by DarKDinDoN** [comment]
@Fyorl Sorry!
Only in the journal, tho. I still experience this issue with other RTE.
Like in 5e, when editing the biography section of a PC sheet.

**Comment by Fyorl** [comment]
I'm not able to reproduce this in the current build. I've attached a video of my reproduction steps, am I doing something wrong?

https://user-images.githubusercontent.com/207433/179078689-9252dffe-2da0-4601-b2ec-87959262ac63.mp4

**Comment by Fyorl** [comment]
I was using the v10 branch of dnd5e which is why I couldn't reproduce it. I confirmed this is still happening in legacy environments.

**Comment by DarKDinDoN** [comment]
Noted. Thx for the quick reply!
