### ISSUE TITLE
Handle ApplicationV2 positioning after post-render hooks so that additional HTML injected via hook is accounted for in the positioning logic.

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7461]
### Environment Details

* Foundry VTT Version: v9.269
* Operating System: macOS 12.4
* How Are You Using Foundry: Chrome 104.0.5112.20 (arm64) from nodeJS Foundry
* Which Game System: dnd5e 1.6.3
* Modules Enabled?: no, except my LightMask module to demonstrate the html injection

### Issue Description

A module or system, in this case my LightMask module, will sometimes modify the html being rendered for an `Application.` From what I can tell, the preferred method to accomplish this is to use the hook provided in `Application.prototype._render`. The issue is that if you add to the configuration such that you change the height of the rendered html, you can confuse the "auto" setting for that configuration.

This short video shows the problem when I add some configuration details to the `AmbientLightConfig` html. When the user selects a shape, I want to add configuration details for that shape. But adding to the render html causes a scroll bar to appear and it jumps to the top.

https://user-images.githubusercontent.com/1267134/178117172-4d16a142-e346-4efa-afea-8ab509616897.mov

### Proposed Solution
The problem seems to be that in `Application.prototype._render`, `setPosition` is called before the hook. `setPosition`, in turn, controls how "auto" or other height configuration works:
```js
// Set the application position (if it's not currently minimized)
    if ( !this._minimized ) {
      foundry.utils.mergeObject(this.position, options, {insertKeys: false});
      this.setPosition(this.position); // <-- setPosition defines the window height here
    }

    // Apply focus to the application, maximizing it and bringing it to the top
    if ( options.focus === true ) {
      this.maximize().then(() => this.bringToTop());
    }

    // Dispatch Hooks for rendering the base and subclass applications
    for ( let cls of this.constructor._getInheritanceChain() ) {

      /**
       * A hook event that fires whenever this Application is rendered.
       * The hook provides the pending application HTML which will be added to the DOM.
       * Hooked functions may modify that HTML or attach interactive listeners to it.
       *
       * @function renderApplication
       * @memberof hookEvents
       * @param {Application} app     The Application instance being rendered
       * @param {jQuery} html         The inner HTML of the document that will be displayed and may be modified
       * @param {object} data         The object of data used when rendering the application
       */
      Hooks.call(`render${cls.name}`, this, html, data);  // <-- hooks potentially change the html here, essentially invalidating setPosition's assumptions
    }

   // <-- Move setPosition to here?

    // Restore prior scroll positions
    if ( this.options.scrollY ) this._restoreScrollPositions(html);
    this._state = states.RENDERED;
```
Instead, would it be possible to move `setPosition` to after the hooks, so that `setPosition` is working with the html that will actually be displayed? I am not sure about setting the focus; I don't see an immediate need to move that.

Note that in this case, restoring scroll positions will not work because the application window had 0 as the scroll position to begin with.

I can confirm that this change would fix the issue, because I can manually call `app.setPosition(app.position);` in my module's code for this hook. This is maybe not a great long-term solution, however, because I have no control over what other modules might be doing after the hook for my module executes. See this video in which the module hook calls `setPosition`:

https://user-images.githubusercontent.com/1267134/178117458-0107eeda-514e-457c-ba8e-e76b144976d3.mov

### Priority

Low, because of the workaround I identify above.

**Comment by aaclayton** [comment]
A good issue for us to solve as part of https://github.com/foundryvtt/foundryvtt/issues/5441

**Comment by aaclayton** [comment]
This is a good idea for a future release, but not something we will be doing in V10 in order to limit scope and reach our target deadlines.
