### ISSUE TITLE
Ability to open multiple instances of the same Journal

### ISSUE THREAD

**Issue by InkyThumb** [foundryvtt/foundryvtt#7480]
> Please describe with as much detail as you feel is necessary the feature which you are requesting.
I'd like the ability to open multiple instances of the same Journal to allow for side by side viewing of different Pages in the same Journal. Right now we are able to open multiple Journals side by side, I'd like that extended to multiple windows of the same Journal.

### User Experience

> Please describe what you feel the ideal user experience would be for interacting with this new feature.
I'm not great at UX, but my instinct was to double click on the page I wanted to open in a new window, or to double click the Journal name (so that for an open journal, single clicking brings it to the front, and double clicking opens a second copy). A right click menu option on individual Pages to "open in new Journal window" might also work?

### Priority/Importance

> Please describe your assessment of feature priority. If you feel it is highly important, describe why you believe it to be more important than other enhancements.
Having no idea what other features are under consideration, or any idea of effort, this feels like a potential easy win with significant (but possibly not substantial) quality of life benefits, and so I'd like to see it sooner rather than later, but it also doesn't impact my ability to use Foundry in any way. Lacking this feature is just annoying. Considering that, if it is a difficult change, it would make sense to me to deprioritize it.

**Comment by aaclayton** [comment]
With V10 we can support the feature to pop out a single page to its own window, so you can organize multiple pages side-by-side using that technique. Hopefully this will satisfy your use case.

**Comment by InkyThumb** [comment]
If the single page pop out is still planned work, can you link me to the ticket number? I'd like to follow the work so that I know when it's released. If it's already released, I can take this to the Discord and ask for support on how to use it there.
