### ISSUE TITLE
Various (Mostly) Schema Related Documentation Mistakes

### ISSUE THREAD

**Issue by LukeAbby** [foundryvtt/foundryvtt#7481]
### Environment Details

* Foundry VTT Version: 10.265
* Operating System: Not Applicable
* How Are You Using Foundry: Not Applicable
* Which Game System: Not Applicable
* Modules Enabled?: no

### Issue Description

The ones I noticed were because of a desync between what's in `defineSchema` and what's in the corresponding Data typedef. The simplest way to make this less likely to happen in the future might be to just document inside `defineSchema` though maybe the typedefs are necessary somewhere else.

common/documents/active-effect.mjs:

- Missing `{`:

  ```js
  * @property EffectDurationData} [duration]  An EffectDurationData object which describes the duration of the ActiveEffect
  ```

- Should be `{string}`:

  ```js
  @property {*} value                    The value of the change effect
  ```
  
common/documents/adventure.mjs:

- Should be `tables`, `macros`, `cards`, `playlists`, and `folders`.
  
  ```js
  * @property {documents.BaseRollTable[]} combats    An array of RollTable documents which are included in the adventure
  * @property {documents.BaseMacro[]} combats        An array of Macro documents which are included in the adventure
  * @property {documents.BaseCards[]} combats        An array of Cards documents which are included in the adventure
  * @property {documents.BasePlaylist[]} combats     An array of Playlist documents which are included in the adventure
  * @property {documents.BaseFolder[]} combats       An array of Folder documents which are included in the adventure
  ```

- `caption` should be documented. (On `AdventureData`)

common/documents/journal-entry.mjs:

- `pages` should be documented. (on `JournalEntryData`)

common/documents/measured-template.mjs:

- `user` should be documented. (on `MeasuredTemplateData`)

common/documents/note.mjs:

- `pageId` should be documented. (on `NoteData`)

common/documents/playlist-sound.mjs:

- `sort` should be documented. (on `PlaylistSoundData`)

common/documents/scene.mjs:

- `foregroundElevation` should be documented. (on `SceneData`)

common/data/data.mjs:

- `invertColor` doesn't need to be documented anymore since it no longer exists.

**Comment by aaclayton** [comment]
Thanks for pointing out these documentation issues.
