### ISSUE TITLE
`rgbToHex` and `colorStringToHex` should return numbers, not `Color`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7487]
### Environment Details

* Foundry VTT Version: 10.272

### Issue Description

`Color` (`Number`) behaves differently compared to a number. Something like this would break with v10 if those deprecated function don't return numbers.
```js
if (colorStringToHex(string) === 0xFF0000) { console.log("Red!"); }
```

**Comment by dev7355608** [comment]
But doesn't make it an flawed deprecation if it's returning `Color` instead of a number for the reason I mentioned?

**Comment by aaclayton** [comment]
> But doesn't make it an flawed deprecation if it's returning `Color` instead of a number for the reason I mentioned?

Yes
