### ISSUE TITLE
Don't allow closing a polygon path if it has fewer than 6 points.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7494]
It's entirely unnecessary to duplicate the first point and create a zero-length edge in the process. Also nothing in the code seems to actually require that the polygon's first and last point are equal.

**Comment by caewok** [comment]
Clipper requires it because there is a parameter for clipping that is set to true signifying a closed polygon.

**Comment by dev7355608** [comment]
From the Clipper doc:
>  Note: With etClosedPolygon and etClosedLine types, the path closure will be the same regardless of whether or not the first and last vertices in the path match.
> http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Types/EndType.htm

**Comment by dev7355608** [comment]
Are those functions going to be removed? I just discovered a bug in `isClosed`/`close`:

```js
new PIXI.Polygon().isClosed // false
new PIXI.Polygon().close().points // [undefined, undefined]
```

Any empty intersections produces this corrupted polygon at the moment.

**Comment by aaclayton** [comment]
I'm happy to fix the bug, but I don't think I understand yet or agree with the reasoning as to why the `.close()` function should be removed. It does have valid use cases.

**Comment by dev7355608** [comment]
Could you explain the use case? PIXI.Polygon is already closed (well there is `closeStroke` for path drawing); if the first and last point equal, there's technically an zero-length edge. PIXI handles this case though and dedupes the last point when drawing the outlines for example. Earcut doesn't require it either, dedupes, but the duplicate point ends up in the vertices of the geometry needlessly. Clipper also dedupes the last point if it equals the first. And nowhere in Foundry's code this kind of closed polygon is required. `close` and `isClosed` just pollute the Polygon class. `close`-ing the polygon makes essentially no difference, besides the fact that it makes the polygon technically degenerate.

**Comment by dev7355608** [comment]
I'd still be interested to know why these methods aren't removed. All calls to `close` aren't necessary and `toClipperPoints` should just be this:
```js
PIXI.Polygon.prototype.toClipperPoints = function({scalingFactor=1}={}) {
  const points = [];
  for ( let i = 1; i < this.points.length; i += 2 ) {
    points.push({
      X: Math.roundFast(this.points[i-1] * scalingFactor),
      Y: Math.roundFast(this.points[i] * scalingFactor)
    });
  }
  return points;
};
```
If you don't need it, why add it?
