### ISSUE TITLE
Redrawing Token creates a ghost border

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7495]
### Environment Details

* Foundry VTT Version: 10.273

### Issue Description

Change the token's icon or run:
```js
_token.draw().then(() => _token.visible = true)
```

**Comment by Feu-Secret** [comment]
To reproduce this case (with dnd5 system):
- Bring a new starter hero on the canvas from the compendium.
- An entry is created in actor.
- Select the starter hero on the canvas.
- Delete the starter hero from the actor.
- Go to token config. Select a new vision mode or activate a light source.
- Move the token.
![image](https://user-images.githubusercontent.com/66535080/181590274-c135ea56-dad3-48ca-8420-b7c18e738772.png)
