### ISSUE TITLE
Add migration path for existing text drawings that had no width or height in v9

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7500]
Originally reported by marvin9257#8916 https://discord.com/channels/170995199584108546/956306859491471420/994239076028923984

**ALL MODULES DISABLED?** (true)  
**OS, Hosting, Browser (if applicable):** Node/JS MacOS  
**Short Description of bug:**

I'm helping on the conversion of the Twodsix system to v10. I'm running into an issue converting scenes that are generated by macro. The scenes have a number of text drawings that don't have the height and width specified for them.  This works fine in v9 and auto sizes the box.  When it they are imported into v10 - I get several errors of the kind shown in the image.  The scenes don't load into memory and can't be manipulated.  If I run the macro in v10, the scenes will load and generate with some minor formatting issues.  But the bounding box when selecting the text drawing no longer contains the text.

I'd rather not have to ask the users to regenerate all their scenes nor have to edit the json files.  Is there a way to fix this issue so that the scenes will load?  For example, do I need to make a macro/migration in v9 before users convert?   Also attached is an example json file of a scene that is causing issues. Thanks

**Simple steps to reproduce the bug:**  

[fvtt-Scene-temp-scene.zip](https://github.com/foundryvtt/foundryvtt/files/9120531/fvtt-Scene-temp-scene.zip)

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/179217547-0dab7857-f1a5-4c36-ac8d-48d3a9f3a117.png)

**Comment by aaclayton** [comment]
I'll take this as I plan to allow width/height of zero at least in the near term.
