### ISSUE TITLE
FilePicker does not open if starting directory contains files with percentage characters in their names

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7501]
Originally reported by EBER#7243 https://discord.com/channels/170995199584108546/956306859491471420/995880423903199263

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):**  Win 10, Electron  
**Short Description of bug:** Filepicker doesn't open. https://discord.com/channels/170995199584108546/956307084931112960/995878372968255638  
**Simple steps to reproduce the bug:** Click any filepicker; or execute `FilePicker.browse("data", "")`.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/179218056-3288655c-a956-4f8c-b5a2-2070308fdc07.png)

![image](https://user-images.githubusercontent.com/207433/179218083-7e910d96-0f12-42aa-8112-4a241a0a8ab1.png)

**Comment by cswendrowski** [comment]
Could not repro

**Comment by dev7355608** [comment]
Still happening to me in 10.273. Did anything change in the backend from 10.270 to 10.272 that would explain this? Something must have, 10.270 works without issue.

**Comment by dev7355608** [comment]
The source of the error has been uncovered: I had a file with a percent symbol in its name in my directory (`50%gray.png`).

**Comment by Fyorl** [comment]
Thanks for following up, I've amended the issue description.
