### ISSUE TITLE
Horizontally mirroring a token too fast breaks its scale

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7502]
Originally reported by mclemente#5524 https://discord.com/channels/170995199584108546/956306859491471420/996566146205634701

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, Electron  
**Short Description of bug:** Horizontally mirroring a token too fast breaks its scale.  
**Simple steps to reproduce the bug:**  
Run the following script macro on a token twice before the animation concludes:

```js
token.document.update({"texture.scaleX": token.document.texture.scaleX * -1});
```

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/179218444-b1c69ea8-8253-4190-89b5-6ab1df0d0913.png)

**Comment by aaclayton** [comment]
to an extent - this is working as intented. `token.document.texture.scaleX` is the currently depicted scale of the token, this changes during the course of animation. If you request a new animation target during that process which is relative to the current value, you will collapse the scale towards zero.

What you should be doing is:

```js
const tokenData = token.toObject();
token.document.update({"texture.scaleX": tokenData.texture.scaleX * -1});
```
