### ISSUE TITLE
ObjectField will no longer incorrectly allow Arrays to be set as a value

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7503]
Originally reported by LukeAbby#0001 https://discord.com/channels/170995199584108546/956306859491471420/996700223403458561

**ALL MODULES DISABLED?** true  
**Short Description of bug:** Very minor, `ObjectField._cast` accepts arrays.  
**Simple steps to reproduce the bug:** Try to cast an array into an `ObjectField`.  
**Longer explanation:**

Minor bug (or so I believe it to be) in `ObjectField` that I'm not sure has been noticed yet:

```js
  _cast(value) {
    return typeof value === "object" ? value : {};
  }
```

This condition will be true for arrays (and null though that's covered by `_validateSpecial`). It should be `return getType(value) === "Object" ? value : {};`. Though mayyybe ObjectField is _supposed_ to allow this?

If I'm correct that this is unintentional, `_validateType` should have `return getType(value) === "Object";` as well.

**Comment by cswendrowski** [comment]
Checking against `Object` isn't correct, because the output of `typeof {}` is `object`
Will add explicit checks against Arrays, which are also `object`

**Comment by aaclayton** [comment]
Use our `getType` helper.
