### ISSUE TITLE
`MonochromaticSamplerShader` improvements

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7506]
The don't need the `color` uniform, we have `SpriteMesh#tint` (`tintAlpha` and `SpriteMesh#_tintRGB`). There's no need to override `_packInterleavedGeomerty` for this reason. A lot easier and natural to set `sprite.tint` (which doesn't have an affect in the current implementation) instead of `sprite.shader.color`. Also the shader in its current implementation doesn't work with `alpha` at all.

`Tile#renderOcclusion` needs a slight adjustment (You might want to force the `worldAlpha` to 1 as well).

```js
  /**
   * Render the mesh for tile occlusion
   * @param {PIXI.Renderer} renderer
   */
  renderOcclusion(renderer) {
    if ( !this.object.isRoof ) return;
    this.pluginName = MonochromaticSamplerShader.classPluginName;
    const tint = this.tint;
    this.tint  = this.object.occluded ? 0x0000FF : 0xFF0000;
    const blendMode = this.blendMode;
    this.blendMode = PIXI.BLEND_MODES.MAX_COLOR;
    this.render(renderer);
    this.tint = tint;
    this.blendMode = blendMode;
    this.pluginName = this.shader.pluginName;
  }
```

The `perceivedBrightness` seems unnecessary, only the alpha channel is of interest if I understand correctly. The shader maps black to black instead of the color in the current implementation: that doesn't seem right. (Also the current implementation does not umpremultiply before calculating the brightness).

This is all we need:
```js
/**
 * A monochromatic shader.
 */
class MonochromaticSamplerShader extends BaseSamplerShader {

  /** @override */
  static classPluginName = "monochromatic";

  /** @override */
  static batchFragmentShader = `
    precision ${PIXI.settings.PRECISION_FRAGMENT} float;
    varying vec2 vTextureCoord;
    varying vec4 vColor;
    varying float vTextureId;
    uniform sampler2D uSamplers[%count%];

    void main(void) {
       vec4 color;
       %forloop%
       gl_FragColor = vColor * color.a;
    }
  `;

  /** @override */
  static fragmentShader = `
    precision ${PIXI.settings.PRECISION_FRAGMENT} float;
    uniform sampler2D sampler;
    uniform vec4 tintAlpha;
    varying vec2 vUvs;

    void main() {
      gl_FragColor = tintAlpha * texture2D(sampler, vUvs).a;
    }
  `;
}
```

**Comment by Feu-Secret** [comment]
It makes sense for tint.
And the fragment logic is better. Thanks.
