### ISSUE TITLE
Blur the vision occlusion with roofs, and antialias radial occlusion.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#7514]

**Comment by Feu-Secret** [comment]
Note: could be interesting to wait for PIXI 6.5.0 and the new `colorMask` feature that would allow us to blur specific channels.

**Comment by aaclayton** [comment]
This is a good idea for a future release, but not something we will be doing in V10 in order to limit scope and reach our target deadlines.
