### ISSUE TITLE
Vision radius of blindness and external radius were not consistent with each other.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7520]
### Environment Details

* Foundry VTT Version: 10.273

### Issue Description

Shouldn't the radius if blinded be `this.data.externalRadius`?

```js
    // Determine the active VisionMode
    if ( this.data.blinded ) {
      this.visionMode = CONFIG.Canvas.visionModes.blindness;
      this.data.radius = Math.max(this.object.mesh.width, this.object.mesh.height) / 2;
    } else {
```

**Comment by aaclayton** [comment]
Not necessarily - `externalRadius` could be a larger value than we intend to provide for blinded tokens. We can look into whether there is a way to standardize that though.

**Comment by dev7355608** [comment]
The token icon scale never affected the vision source and LOS polygons. But now it does in the case of blindness and only in the case of blindness. But it doesn't really matter that much though, because there's a special case for the blinded status in `testVisibility`: so even if the token with icon scale > 1 gets a visually larger FOV if blinded vs nonblinded, it doesn't matter for the visibility checks.
