### ISSUE TITLE
The order of objects in `PlaceablesLayer` should match the order of the `PrimaryCanvasObject`s

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7522]
If they don't, it can impossible, for example, to select a tile that is above another in the primary canvas group (based on elevation and sort), because the `Tile`s are not sorted in anyway, and thus the `Tile` of the `TileMesh` that is above the other one is actually behind the other `Tile`.

This affects all placeable objects as far as I can tell, except drawings, which still write their z-index to `zIndex`, but that is still not going to work if the elevation of the drawings are different. The `PlaceableObject`s in a layer should have the same order as their `PrimaryCanvasObject`s in the primary canvas group.

![sortbug1](https://user-images.githubusercontent.com/31905376/179369430-28945abd-5240-49de-bd6f-bb0da9efb66d.gif)
![sortbug2](https://user-images.githubusercontent.com/31905376/179369432-4cbf4594-6730-4f14-a504-3eca66f2633b.gif)

**Comment by theripper93** [comment]
this is the same issue i was having here (https://github.com/foundryvtt/foundryvtt/issues/7518) - i'll follow this issue instead, we can ignore the one i opened.
