### ISSUE TITLE
occlusionRadius core flag should use grid units instead of pixels

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7527]
The core `occlusionRadius` flag on Tokens currently uses Pixels instead of grid units (like Vision for example) this would cause user confusion when dropping the token on scenes with different DPI.

Also, the minimum radius should be restricted to the radius of the token (`Math.max(token.mesh.width, token.mesh.height) / 2`) since it would be undesirable to have an occlusion radius, even by accident, set at a lower value than that.

**Comment by dev7355608** [comment]
To add some more details to the second paragraph: the radius should be minimum radius of the token (`token.w / 2` as in `Token#getLightRadius`) plus the occlusion radius set by the flag. This way it gives the exact same range as one expects from setting the vision range of a token.
```js
const o = Number(token.document.getFlag("core", "occlusionRadius"));
const r = Number.isFinite(o)
    ? (token.w / 2 + Math.max(o, 0)) * (canvas.dimensions.size / canvas.dimensions.distance)
    : Math.max(token.mesh.width, token.mesh.height);
```

**Comment by Feu-Secret** [comment]
The `occlusionRadius` is now in grid units. The occlusion radius can't be inferior to the base occlusion radius.
