### ISSUE TITLE
`MeasuredTemplate` sometimes "ghosts" when releasing from drag-move

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7530]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: v.10.273
* Operating System: macOS 12.4
* How Are You Using Foundry: Chrome 104.0.5112.39 (arm64)
* Which Game System: dnd5e 1.6.3
* Modules Enabled?: no

### Issue Description

When dragging an already-created `MeasuredTemplate`, it will sometimes "ghost" when you release the drag at the new location. Not every time, but fairly often. I uploaded a recording, below, that has several examples with the circle template. To my knowledge it is not limited to the circle template. It looks like after the drag is released, Foundry is briefly drawing the template at an old location.

(Anecdotally, I can make this happen more slowly in a version of my Walled Templates module as well, and it looks like, when the drag ends, it is briefly re-drawing the template at the position where it was before the drag started. FYI, the effect in the movie below is without any modules enabled.)

https://user-images.githubusercontent.com/1267134/179424153-7600e9bf-c7a4-4962-9dbf-d74f5d30b2e9.mov

**Comment by aaclayton** [comment]
De-prioritizing this from V10 as a known limitation.
