### ISSUE TITLE
Creating a scene in a world that has none does not appropriately load the scene

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7540]
Originally reported by ghost#2000 https://discord.com/channels/170995199584108546/956306859491471420/997836843104096299

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** not applicable  
**Short Description of bug:** When creating a scene in a world that doesn't have any scenes, a warning is displayed, and the scene is not loaded. Manually navigating to the scene also is not possible. Reloading (F5) then solves the issue.  
**Simple steps to reproduce the bug:** Load a world without any scenes, then create a scene, then try to view the scene manually.   
**Screenshots and/or console errors:**

```
You cannot switch Scenes until resources finish loading for your current view. foundry.js:54978:78
```

![image](https://user-images.githubusercontent.com/207433/179505850-f9e54a58-80e5-4e48-938c-49a52f132bbe.png)

**Comment by aaclayton** [comment]
Resolved by #7539
