### ISSUE TITLE
Journal Pages over a certain length fail to render their Table of Contents.

### ISSUE THREAD

**Issue by trioderegion** [foundryvtt/foundryvtt#7543]
### Environment Details

* Foundry VTT Version: 10.273 (initially found in v10-dev2)
* Operating System: Windows 11
* How Are You Using Foundry: NodeJS + Microsoft Edge
* Which Game System: demonstrated in dnd5e
* Modules Enabled?: no

### Issue Description

Journal Pages over a certain length do not complete their rendering of the table of contents in time, preventing its display.

It appears that the observe call to IntersectionObserver is responsible for creating the apparent race condition where the ToC doesnt render.  From this function, at foundry.js:58678 (v10dev2), if I breakpoint on this._contextMenu, which would ensure any operations performed by the forEach-observe have completed, the TOC renders as expected every time.

```javascript
  /** @inheritdoc */
  activateListeners(html) {
    super.activateListeners(html);
    html.find(".create-page").click(this._onAddPage.bind(this));
    html.find(".action-buttons [data-action]").click(this._onAction.bind(this));
    html.find(".header-control").click(this._onChangeMode.bind(this));
    html.find(".journal-entry-page").hover(
      event => this._onPageHover(event, true),
      event => this._onPageHover(event, false)
    );
    this.#pageInView = null;
    const observer = new IntersectionObserver(entries => {
      this._onPageScroll(entries);
      this._activatePageInView();
      this._updateButtonState();
    }, {
      root: html.find(".journal-entry-pages .scrollable")[0],
      threshold: [0, .25, .5, .75, 1]
    });
    html.find(".journal-entry-page").each((i, el) => observer.observe(el)); //this loop does not finish in time
    this._contextMenu(html); //if I pause here for a moment (before this line is executed), all is well.
    this._updateButtonState();
  }
```

My guess is that one of the callback steps in the IntersectionObserver is the actual culprit, but I get a bit lost as soon as I poke into that class.

![image](https://user-images.githubusercontent.com/14878515/179522211-d19e7138-7375-4862-a78a-8b416c037dec.png)
![image](https://user-images.githubusercontent.com/14878515/179522316-d49bf9de-c230-4c36-bb37-984e91c65acb.png)

### Supporting Files
[fvtt-JournalEntry-toc-length-test.json.txt](https://github.com/foundryvtt/foundryvtt/files/9132222/fvtt-JournalEntry-toc-length-test.json.txt)
* Note: GitHub required this file be uploaded with `txt` extension, but it is a valid Foundry json export.
* contains a 3 pages with varying lengths of text. Only the shortest Page should correctly render its table of contents based on the h2 and h3 tags present.

**Comment by aaclayton** [comment]
Duplicates of #7463 and #7406
