### ISSUE TITLE
`PIXI.Polygon.prototype.toClipperPoints` needs to round to integers to conform to the Clipper library expectations. Provide an optional scaling factor for preserving numerical precision.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7546]
### Environment Details

* Foundry VTT Version: 10.273

### Issue Description

Passing noninteger coordinates to Clipper is undefined behavior.

**Comment by dev7355608** [comment]
It's the integer version. The float version would have `FPoint` in the ClipperLib namespace.

Clipper2 just includes a wrapper for float. It still uses integers for clipping. It's just convenience, and it's still more efficient to handle the up/down-scaling yourself in cases where you need to compute something with multiple clipping operations (the intermediate results would be up/down-scaled needlessly).

**Comment by caewok** [comment]
Thanks for the info on FPoint and the wrapper in Clipper2, @dev7355608!
