### ISSUE TITLE
Refactor duplicate function implementation to use structuredClone

### ISSUE THREAD

**Issue by itamarcu** [foundryvtt/foundryvtt#7552]
I'm copying [this feature suggestion](https://discord.com/channels/170995199584108546/517504137403826177/942480590517727313) from the discord:

The current `duplicate` function uses this code:

```js
return JSON.parse(JSON.stringify(original));
```

But there is a modern replacement that is [compatible with all major browsers](https://caniuse.com/?search=structuredClone) (and the old method can easily be used as a fallback if not):  The `structuredClone` global function!

This function serves the same purpose - deep cloning an object - except it is faster, and supports cyclical objects, 

New implementation can be:

```js
return structuredClone(original);
```

Some extra details about the function and its performance/behavior/limitations - https://web.dev/structured-clone/

### Priority/Importance

Low priority.

**Comment by aaclayton** [comment]
Good suggestion. We can't use it server-side yet until we require Node 17 which won't be for a while.  We don't recommend using `duplicate` anymore - and you will notice that we don't use it in our own code anymore. I'll look into some performance comparisons between `foundry.utils.deepClone` which we do use and `structuredClone` which could be a better built-in alternative.

**Comment by aaclayton** [comment]
Update: our `foundry.utils.deepClone` function is over 5x faster than `structuredClone`. I imagine that `structuredClone` incorporates a lot of special logic and safety checks, but I must say the performance is really disappointing:

## Benchmark Comparison
```js
// A relatively complex scene
const sd = canvas.scene.toObject(); 

// Test 1 - Old duplicate using JSON.parse/JSON.stringify
foundry.utils.benchmark(() => foundry.utils.duplicate(sd), 10000);
// duplicate | 10000 iterations | 3876.4ms | 0.38764ms per

// Test 2 - New deepClone
foundry.utils.benchmark(() => foundry.utils.deepClone(sd), 10000);
// deepClone | 10000 iterations | 1455.8ms | 0.14558ms per

// Test 3 - Built-in structuredClone
foundry.utils.benchmark(() => structuredClone(sd), 10000);
// structuredClone  | 10000 iterations | 7441.4ms | 0.7441399999999999ms per
```

The `foundry.utils.deepClone` outperforms both other alternatives, and the performance degradation of moving to `structuredClone` is quite bad. Maybe this will improve in the future, but for now this looks like its not worth changing.
