### ISSUE TITLE
Walls overlapping the inner boundary can mess up `ClockwiseSweepPolygon`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7556]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: v10.273
* Operating System: macOS 12.4
* How Are You Using Foundry: Chrome 104.0.5112.39 (arm64)
* Which Game System: dnd5e 1.6.3
* Modules Enabled?: no

### Issue Description

Walls overlapping the inner border can mess up `ClockwiseSweepPolygon`. An example:
<img width="1044" alt="Screen Shot 2022-07-20 at 7 41 35 AM" src="https://user-images.githubusercontent.com/1267134/180011207-f1059d60-0792-4087-95fe-8b7709770ef7.png">
<img width="1044" alt="Screen Shot 2022-07-20 at 7 41 14 AM" src="https://user-images.githubusercontent.com/1267134/180011217-30c7fdcd-8858-43cd-9273-9ded0552fbfa.png">

**Comment by aaclayton** [comment]
Oops! Good catch and an easy fix.

**Comment by caewok** [comment]
Looks like that would fix the issue.
