### ISSUE TITLE
Once a player has rolled initiative they should not be able to re-roll it

### ISSUE THREAD

**Issue by haqa** [foundryvtt/foundryvtt#7559]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 9.269
* Operating System: Linux (Alpine 3.14)
* How Are You Using Foundry: Chome
* Which Game System: dnd5e
* Modules Enabled?: yes, loads, I don't think any are relevant.

### Issue Description
Users are able to re-roll their initiative after it has already been set which provides a meta-gaming opportunity. Once a player has entered the combat tracker and rolled (or been rolled for) they shouldn't be able to change their position (though the GM/AGM should).

**Comment by unsoluble** [comment]
Try with no modules enabled; this is not possible in core Foundry/dnd5e.

**Comment by haqa** [comment]
Looks like this a conflict with Argon HUD, sorry, I'll close this.
