### ISSUE TITLE
When a new document is being created, append a number to better support bulk creation

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7562]
The current state of creating a new Document puts the focus on the Create button which isn't currently valid to be submitted, as name is empty

This updated workflow pre-populates the field with a semi-unique name rather than the placeholder, which makes the form valid to be submitted right away, easing bulk creation.

**Comment by farling42** [comment]
This is horrible, since everybody now has to manually delete the auto-generated name in the name box before they can add a new name.
Is bulk creation of randomly named documents really used by a lot of users?

**Comment by farling42** [comment]
An alternative UI method would be to put the auto-numbered item in the placeholder field, then when the create button is pressed if the name field is empty then it's placeholder value could be used as the name of the document.

This gives the advantage of not having to manually delete existing text in the name box when a specific name is required for the thing being created.

**Comment by aaclayton** [comment]
We agree that the implementation of this issue fell short of a great UX. We are going to make some changes next release.
