### ISSUE TITLE
Setup screen "Install Package" app will no longer make multiple POST requests to `getPackages`

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7563]
### What happened?

`getOwned` makes a second call to `getPackages`, which likely isn't necessary

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open up any Install Package app and observe the Network tab

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by kakaroto** [comment]
I still see this behavior happening with Testing 2 (`10.276`), it does not seem to be fixed yet.
