### ISSUE TITLE
V10 preUpdate behaviour different for linked vs unlinked tokens

### ISSUE THREAD

**Issue by tposney** [foundryvtt/foundryvtt#7565]
### What happened?

With the following hook I would expect any updated active effect to have it's startTime set to 1000.
For linked actors that is what happens. For unlinked actors the duration.startTime is not updated.
```js
Hooks.on("preUpdateActiveEffect", (effect, updates) => {
   setProperty(updates, "duration.startTime", 1000);
});
```

I have tried other updates and with the same outcome

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Execute
```js
Hooks.on("preUpdateActiveEffect", (effect, updates) => {
   setProperty(updates, "duration.startTime", 1000);
});
```

Edit an active effect on a linked actor and observe that the start time is updated to 1000.
Edit an active effect on an unlinked actor and observe that the start time is unchanged.

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I have added a workaround to support this type of preUpdate hook for unlinked tokens.
