### ISSUE TITLE
Type-based DataModel subclasses are not assigned a parent

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7568]
Originally reported by wyrmisis#8136 https://discord.com/channels/170995199584108546/956306859491471420/998793465502650470

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Manjaro Linux (Sway DE), Node (local), Brave  
**Short Description of bug:** When setting `CONFIG.Actor.systemDataModels[type]` to a class extended from `DataModel`, the extended data model doesn't have a `parent`.  
**Simple steps to reproduce the bug:**

1. For Actor of type 'a', set `CONFIG.Actor.systemDataModels[a]` to a class extended from `DataModel`, with an empty object schema.
2. Create an Actor of type 'a'
3. Through the browser console, examine the Actor's `system` prop
4. Observe that the Actor's `system.parent` prop is set to `null

**Note:** I was able to work around this by adding my own constructor to the extended `DataModel` class, like in the docs:

```js

class ActorAData extends DataModel {
  constructor(data, parent) {
    super(data, { parent });
  }
}
```

**Comment by aaclayton** [comment]
This was a misunderstanding - and a case of not using the correct constructor signature.
