### ISSUE TITLE
Module installation always warns about compatibility even if correct metadata is specified in the manifest

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7573]
Originally reported by ghost#2000 https://discord.com/channels/170995199584108546/956306859491471420/999798562332360875

**ALL MODULES DISABLED?** N/A
**OS, Hosting, Browser (if applicable):** irrelevant  
**Short Description of bug:** When installing a module, it first always displays a compatibility warning, even when the module explicitly declares compatibility with v10 (by setting `compatibility.verified` to `"10"`, and the same in the package admin). Reloading then makes the warning vanish.  
**Simple steps to reproduce the bug:** Install any module that declares compatibility with v10, e.g. `Per Actor Roll Mode`.  
**Screenshots and/or console errors:**  
This seems to be similar to what I described in the comments in https://github.com/foundryvtt/foundryvtt/issues/7061 (and potentially, it also applies to worlds and systems), but since this issue is already closed and doesn't seem to get any attention, I figured I'd create a new report.

![image](https://user-images.githubusercontent.com/207433/180434991-b9c027c5-c205-4e08-ad08-a88cac2b39d2.png)

**Comment by Zamrod** [comment]
The alert seems to go away after you load a world and then go back to setup.
Also, the first time you open a world after you install a new module, the module does not appear in the list of modules in Manage Modules for that world until you return to setup and then open the world again.
