### ISSUE TITLE
Create Central Notification Queue for Modules

### ISSUE THREAD

**Issue by Geekswordsman** [foundryvtt/foundryvtt#7584]
### User Experience

Problem:
Currently module developers will create dialogs, chat messages, toast notifications, or even tours as they want to fire as the module loads.  This can cause a flood of information to overload the initial screen for users when they first log in.

Proposition:
Create an API that module and system developers can call that will queue their notifications, to only move on to the next one once the prior one has been confirmed/closed.

An even better enhancement to this would be to create a UI that alerts the user to these notifications.  A possibility would be to turn the anvil icon for Foundry in the top left of the canvas to a notifications area, and clicking on it will trigger the notification queue.

Benefit:
Reduction of information overdose as system and module devs present notifications on log in.

**Comment by paulohdsc** [comment]
Related issue: https://github.com/foundryvtt/foundryvtt/issues/7564

**Comment by aaclayton** [comment]
Closing as duplicate, merged with #7564
