### ISSUE TITLE
Set the clear color of the primary canvas group to the scene's background color

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7585]
Setting the primary canvas group's clear color to the scene's background color fixes the 4 issues, that were mentioned in #6884:
1. The scene's background color is affected by illumination twice, because the renderer's background color is computed with illumination and then actual illumination is blended on top of it.
2. The background color is unaffected by lighting shaders: for example, the light's saturation has no effect.
3. Post-effects filters (filters attached to a container containing both the primary and effects group) break the color blending with the background color, because the lighting is blended on the filter texture first, which is then blended with the background. This darkens the background color extremely.
4. This would fix any issues related to (un)premulitplying alpha in shaders. Any unpremultiplying of the `baseColor` could be removed, because the the primary group texture would be opaque.

```js
// === PrimaryCanvasGroup ===

async draw() {
    this.clearColor = [...canvas.colorManager.colors.sceneBackground.rgb, 1];

    /* ... */
}
```

```js
// === CanvasColorManager ===

initialize(/* ... */) {
    /* ... */
 
    // Update scene background color

    //// `sceneBackground` is now just the scene's background color, because lighting is already applied to the clear color of the primary canvas group.
    this.colors.sceneBackground = Color.from(backgroundColor ?? scene?.backgroundColor ?? fbc.backgroundColor);
    canvas.primary.clearColor = [...this.colors.sceneBackground.rgb, 1];

    //// Set the background color of renderer to exactly the color as if the illumination was applied to the background color. The previous calculation was not quite correct.
    canvas.app.renderer.backgroundColor = this.colors.sceneBackground.multiply(this.colors.background).valueOf();

   /* ... */
}
```
  
The `tokensRenderTexture`'s clear color needs to be set to `[0, 0, 0, 0]`:
```diff
  class PrimaryCanvasGroup extends CachedContainer {
  constructor(sprite) {
    sprite ||= new SpriteMesh(undefined, BaseSamplerShader);
    super(sprite);
    this.interactive = this.interactiveChildren = false;
    this.sortableChildren = true;
    this.layers = this.#createLayers();
-    this.tokensRenderTexture = this.createRenderTexture({renderFunction: this._renderTokens.bind(this)});
+    this.tokensRenderTexture = this.createRenderTexture({renderFunction: this._renderTokens.bind(this), clearColor: [0, 0, 0, 0]});
  }
```

### Reproduction Steps

Issue 1: Create a new scene with Darkness Level 1.  Execute the snippet below and observe the difference.

Issue 2: Create a new scene with a red background color. Place a light source with Saturation -1. Execute the snippet below and observe the difference.

Issue 3: Create a new scene. Execute `canvas.stage.filters = [new PIXI.filters.AlphaFilter()]`. Execute the snippet below and observe the difference.

Issue 4:  Create a new scene and place a token with a transparent elements and vision range > 0. Reload the scene (for some reason required). Select the token. Execute the snippet below and observe the difference.

```js
g = canvas.primary.addChildAt(new PIXI.LegacyGraphics(), 0);
g.beginFill(0xFFFFFF).drawShape(canvas.dimensions.rect).endFill();
g.tint = Number(Color.from(canvas.scene.backgroundColor));
g.elevation = -Infinity;
g.sort = -Infinity;
```

**Comment by aaclayton** [comment]
Thanks for outlining this proposal so clearly. I'll discuss with @Feu-Secret
