### ISSUE TITLE
Improve the diffObject helper to use prototype.equals (if available) and prototype.valueOf for testing primitive types

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7587]
### What happened?

The `Color` object will always end up in `changes`.
```js
foundry.utils.diffObject({ color: 0 }, { color: Color.from(0) }) // { color: Color }
```

Maybe `diffObject` should compare objects of the primitives by value? 
```js
diffObject({ string: "" }, { string: new String("") }) // { string: String }
diffObject({ boolean: false }, { boolean: new Boolean(false) }) // { boolean: Boolean }
diffObject({ number: 0 }, { boolean: new Number(0) }) // { boolean: Number }
```
So maybe this is a bug in `diffObject`: I see `getType` returns `"number"` for `Color`, but `diffObject` tests with strict equality, which always returns false unless it's the same object. The comparison in `diffObject` should probably be `v0.valueOf() !== v1.valueOf()` instead of `v0 !== v1`.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```
source = new VisionSource()
source.initialize({ color: Color.from(0xFF0000) }) // changes = { x: 0, y: 0, ... }
source.initialize({ color: Color.from(0xFF0000) }) // changes = { color: Color }
source.initialize({ color: Color.from(0xFF0000) }) // changes = { color: Color }
```

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Good suggestion, I agree this could be improved in `diffObject` instead of adjusting every downstream usage.
