### ISSUE TITLE
[Bug]: `fogColor` in `VisibilityFilter` needs to be unpremultiplied

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7589]
### What happened?

![image](https://user-images.githubusercontent.com/31905376/180626290-da569e1d-88ec-4bd1-ace4-38e6e712a540.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create new scene.
2. Set the Fog of War Unexplored Color to red (#ff0000)
3. Set the Fog of War Image to the provided image.

A gradient from #ff0000 to transparent.
![fogofwar](https://user-images.githubusercontent.com/31905376/180626303-2e0e22b8-822b-4f58-926d-f7bfcd48e843.png)

### What core version are you reporting this for?

Version 10 Testing 1 (build 275)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Resolved by :
- https://github.com/foundryvtt/foundryvtt/issues/7585

**Comment by Feu-Secret** [comment]
+ unpremultiplying of the fog texture colors into the `visibility` filter.
