### ISSUE TITLE
Handlebars helpers and `Color`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7603]
### User Experience

I think the `colorPicker` helper should be able to work with any value that can be turned into a `Color`.
```js
name = name || color; // <= BTW, the `color` variable is never defined. Should this be `"color"`?
value = value != null && value != "" ? Color.from(value).toString() : "";
const safeValue = Color.from(value || options.hash["default"] || "#000000").toString();
```

And I was thinking a `colorFormat` helper would be handy too:
```js
static colorFormat(value) {
  return Color.from(value).toString();
}
```

**Comment by aaclayton** [comment]
I fixed the bug with the first part of the issue, for displaying a formatted color in your handlebars template, you can just use `color.css` which will provide a formatted string!

**Comment by dev7355608** [comment]
The default value can be a number now, but `value` still needs to be put though `Color.from(...).css` otherwise `colorPicker` cannot be used with numbers. 
```js
value = value != null && value !== "" ? Color.from(value).css : "";
```

The `colorFormat` helper would allow numbers to converted to color strings, which isn't possible without a helper if I'm not mistaken.
