### ISSUE TITLE
A ping is fired if a player tries to move a token while the game is paused.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7615]
Originally reported by ironmonk88#4075 https://discord.com/channels/170995199584108546/956306859491471420/1000824259393888388

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Chrome  
**Short Description of bug:** Ping fires when dragging across the screen.  If the game is paused and a player tries to move a token, it ends up pinging the token even when the mouse is no where near the ping location any more.  The ping probably shouldn't fire if the mouse is moving.  
**Simple steps to reproduce the bug:** Make sure the game is paused.  As a player try and drag a token, the ping will happen where you clicked on the token.

**Comment by Fyorl** [comment]
I think I know why this is happening but I'm not sure if it's worth addressing. The player did not intend to ping, of course, they intended to move their token. But since the game was paused, that intention can never be met. So I don't know how much value there is in removing one unintended effect to reveal the other one underneath.

**Comment by aaclayton** [comment]
I agree this can be a wontfix.
