### ISSUE TITLE
Add fallback Filepicker preview Icon for non-media Files rather than display broken images

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7620]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/956306859491471420/1001023813166841907

**Short Description of bug:** Non-image files shouldn't have thumbnails or should have icons  
**Simple steps to reproduce the bug:** View non-media files in file picker  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/180771032-fa0a1759-8c20-4bbb-85a7-30a0cb87827f.png)

**Comment by cswendrowski** [comment]
![](https://media.discordapp.net/attachments/830182194533892116/1007387063794016376/unknown.png)
