### ISSUE TITLE
Add hooks for "next/previousTurn" and "next/previousRound" in Combats

### ISSUE THREAD

**Issue by BadIdeasBureau** [foundryvtt/foundryvtt#7623]
### User Experience

Currently, triggering things based on the next round or turn in a combat involves either:
 - Wrapping the nextRound and/or nextTurn functions
 - Attempting to parse the updateCombat hook with suitable filters to trigger only on a new round/turn.
The former isn't ideal practice - as with all wrapping/monkeypatching, it has various potential to go wrong in circumstances when too many people are trying to do it, or be unstable through API changes.

The latter is... possible, but fiddly.  False positives are hard to avoid, e.g. when a combatant is deleted or added (potentially resulting in a change in turn number and/or current combatant where the "turn" hasn't changed in real terms).

Instead, having the nextTurn, nextRound, previousTurn, and previousRound functions each throw a hook would allow for this to be reacted to more easily.  There may be false negatives here with systems/modules that manipulate the turn order more thoroughly - e.g. changing turns by directly updating, such as popcorn initiative - but these would have the option of throwing the hook(s) for compatibility where the update represents an actual mechanical change of turn.

I suggest that the hook data includes the Combat instance, the previous Combatant and the next Combatant.

Including an object with the next round number, turn number, and time advancement could allow these to be mutated by consumers of the hook, as a potentially useful additional feature (since the final result of all these functions is a `Combat.update({round, turn}, {advanceTime})`)

```
/**
 * A hook event that fires when a Combat encounter is started.
 * @event combatStart
 * @category Combat
 * @param {Combat} combat         The Combat encounter which is starting
 * @param {number} startRound     The round at which the Combat encounter should start
 * @param {number} startTurn      The turn at which the Combat encounter should start
 */
function combatStart(combat, startRound, startTurn) {}

/* -------------------------------------------- */

/**
 * A hook event that fires when a Combat encounter is ended.
 * @event combatEnd
 * @category Combat
 * @param {Combat} combat      The Combat encounter which is ending
 */
function combatEnd(combat) {}

/* -------------------------------------------- */

/**
 * A hook event that fires when a Combat encounter is advanced to a new turn.
 * @event combatTurn
 * @category Combat
 * @param {Combat} combat           The Combat encounter which is advancing
 * @param {number} currentTurn      The turn number which is currently active
 * @param {number} newTurn          The turn number that is being advanced to
 * @param {number} advanceTime      The amount of time in seconds that time is being advanced
 * @param {boolean} forward         Is the turn advancing forward (true) or backward (false)
 */
function combatTurn(combat, currentTurn, newTurn, advanceTime, forward) {}

/* -------------------------------------------- */

/**
 * A hook event that fires when a Combat encounter is advanced to a new round.
 * @event combatRound
 * @category Combat
 * @param {Combat} combat           The Combat encounter which is advancing
 * @param {number} currentRound     The round number which is currently active
 * @param {number} newRound         The round number that is being advanced to
 * @param {number} advanceTime      The amount of time in seconds that time is being advanced
 * @param {boolean} forward         Is the turn advancing forward (true) or backward (false)
 */
function combatRound(combat, currentRound, newRound, advanceTime, forward) {}

```

**Comment by aaclayton** [comment]
@BadIdeasBureau the `Combat#previous` and `Combat#current` objects exist specifically to make it easy to detect changes in the state of a combat encounter, this should make the process of correctly identifying changes in rounds and turns within the scope of an `updateCombat` hook very reliable. 

Are there specific pain points there you can highlight? Or were you unaware of the existednce of the `current` and `previous` objects and how they can help here?

**Comment by BadIdeasBureau** [comment]
There's a few specific behaviours on adding/removing combatants which mean that basing the filtering on those can result in false positives.  Also it would seem to require keeping some secondary reference for what the code thinks the current combatant should be, to compare against `current`.

- Create a combat with two combatants
- Advance to the second combatants turn (current: `round 1, turn 1, combatant2`, previous: `round 1, turn 0, combatant1`)
- Delete the first combatant
- Both `current` and `previous` have now changed (both are now `round 1, turn 0, combatant2`, which would cause a false positive on many implementations of a "next turn" detection (can be distinguished by combatant ID, but feels like a trap).
- Add some new combatants, and roll initiative
- Both `current` and `previous` have now changed - current reflects the current position of combatant2, whose turn it still is - previous now points to the round/turn of the combatant immediately above combatant2, even though they have never had a turn - meaning that any "end of turn" detection is likely to misfire for the new combatant.

In each of those cases above, there is update data containing `turn: x`, so I'm not sure what additional comparison would be required to distinguish those cases.

It also feels like a sufficiently common use case to be worth considering a more "naturalistic" hook, rather than requiring anyone who needs it to filter the update hook appropriately.

I'm currently working on a system and seeing this as a thing I'll need to deal with in future (after a few more basic bits of setup), so I haven't poked into implementing this in detail yet - but it feels like something with a lot of possible pitfalls and requiring some trial and error, and while there's probably a reliable solution, I'm not sure it should be left to each dev to discover. (and wrapping the nextRound/nextTurn functions to add my own hooks in seems like an easier path at the moment)

**Comment by aaclayton** [comment]
If you're working on a System you should probably be extending the `Combat` document with your own system-specific subclass rather than relying on hooks IMO.

**Comment by BadIdeasBureau** [comment]
Now I'm further into this, I'm subclassing Combat and strongly considering just ignoring the underlying "turn" structure imposed by Combat altogether (it doesn't quite make sense in this system, where combatants can act in one of 5 blocks according to their initiative/whether they are monsters, but order within each block is decided entirely by players/the GM).

Which means that while this isn't required for my system directly, these hooks existing would allow systems like mine to be better supported by system-generic modules, since I could make sure to throw out the nextTurn hook at the appropriate time.  Those modules would likely be useful here (and for other similar systems, without a well-defined predetermined "turn order", but with clear "start and end of turn").

As a specific example, I'm unlikely to be able to make the system compatible with Next Up, without specifically massaging my combat updates to trigger its "updateCombat" detection for a new turn (i.e. including a vestigial "turn number" which isn't actually used in the system's combat handling - since that only cares about "block number" and whether a combatant has acted). https://github.com/kandashi/Next-Up/blob/main/src/nextUp.js#L325 , whereas a core "nextTurn" hook which systems could implement in a way that makes sense for their combat tracking (rather than the fairly opinionated approach of `Combat`) would make this kind of cross-compatibility easier.

**Comment by aaclayton** [comment]
That's a useful perspective, thanks. I'll see if we can get this investigated, although no promises it will make V10.
