### ISSUE TITLE
Allow vision modes to be excluded from the token config UI.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#7631]
### User Experience

Vision modes have a new boolean property: `tokenConfig`, which is `true` by default. If a vision mode should be excluded from the token configuration UI, `tokenConfig` should be explicitly set to `false`. Example with blindness vision mode:
```js
// Blindness
blindness: new VisionMode({
  id: "blindness",
  label: "VISION.ModeBlindness",
  tokenConfig: false,
  canvas: {
    shader: ColorAdjustmentsSamplerShader,
    uniforms: { enable: true, contrast: -0.75, saturation: -1, exposure: -0.3 }
  },
  lighting: {
    background: { visibility: VisionMode.LIGHTING_VISIBILITY.DISABLED },
    illumination: { visibility: VisionMode.LIGHTING_VISIBILITY.DISABLED },
    coloration: { visibility: VisionMode.LIGHTING_VISIBILITY.DISABLED }
  },
  vision: {
    defaults: { attenuation: 0, contrast: -0.5, saturation: -1, brightness: -1 }
  }
}),
```

Edit: replaced `listed` with `tokenConfig`

**Comment by aaclayton** [comment]
I might suggest instead of `listed` we can be a bit more specific and put `tokenConfig: false` for whether or not the vision mode should appear as an option in Token Configuration.

**Comment by Feu-Secret** [comment]
> I might suggest instead of `listed` we can be a bit more specific and put `tokenConfig: false` for whether or not the vision mode should appear as an option in Token Configuration

Main description edited with the new keyword: `tokenConfig`.
