### ISSUE TITLE
Allow custom coloration shaders to be visible even if the light source doesn't have a color

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7643]
### User Experience

I have a special coloration shader that needs to be rendered even if the light source doesn't have a color. The `hasColor` condition in `LightSource#updateVisibility` would need to be moved to `AdaptiveColorationShader`:
```js
    const hasColor = (this._flags.hasColor || this.isDarkness);
    v.coloration = hasColor && (this.coloration.shader?.isRequired !== false);
```
The `hasColor` uniform probably needs to be added (unless it's already part of the new uniforms) to make this happen.

**Comment by Feu-Secret** [comment]
The `hasColor` universal uniform has been added. Visibility logic has been moved to `AdaptiveColorationShader#isRequired`.
