### ISSUE TITLE
Deprecation warning not showing for modules that use deprecated `system` field

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#7651]
### What happened?

A deprecation warning for modules that use the old `system` field suggesting they switch to the new `relationships.systems` field. Instead nothing is show. A deprecation warning is shown for the older `systems` field.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create module with manifest:
```json
{
  "id": "my-module",
  "system": ["dnd5e"]
}
```

Launch in V10.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by ghost91-** [comment]
Actually, it seems the `system` property isn't migrated at all. It's not being handled by `BasePackage.#migrateToRelationships`.
