### ISSUE TITLE
Improve readability for transparent headers and sidebars

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#7653]
### User Experience

The large, transparent sidebars in the new journals can lead to situations where the text is hard to read due to underlying details:

<img width="328" alt="Screen Shot 2022-07-28 at 18 27 24" src="https://user-images.githubusercontent.com/19979839/181664078-62f153c1-14b4-4c8c-9db5-99cfd01969cc.png">

One possible solution is the use of `backdrop-filter` (and `-webkit-backdrop-filter`) with a blur to obscure the background somewhat:

<img width="327" alt="Screen Shot 2022-07-28 at 18 27 13" src="https://user-images.githubusercontent.com/19979839/181664208-882a6cef-0380-4efd-a458-3abdb8077a96.png">

**Comment by unsoluble** [comment]
This doesn't appear to be happening in 10.284
<img width="407" alt="CleanShot 2022-09-01 at 20 42 36@2x" src="https://user-images.githubusercontent.com/801582/188054820-6e05856f-fa05-4ec2-844f-47b36e1f2e62.png">

**Comment by aaclayton** [comment]
Looks like it was implemented for popped-out sidebar tabs but not for the journal sidebar. I'll discuss with @cswendrowski.

**Comment by paulohdsc** [comment]
For reference: https://github.com/foundryvtt/foundryvtt/issues/7767
