### ISSUE TITLE
Render an input type="number" for game settings which declare a Number type but do not specify a range.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7656]
Originally reported by HarryFurAlle#5062 https://discord.com/channels/170995199584108546/872553750877835264/984830572952158291

**ALL MODULES DISABLED?** true  
**Short Description of bug:** A registered game setting with `.. type: Number .. config: true` will render an Input element with `type=text`.  
**Simple steps to reproduce the bug:** Register a game setting with the above settings.

**Comment by aaclayton** [comment]
I don't believe this has ever been otherwise - although it would be good to switch it to a number input.
