### ISSUE TITLE
Tiles are not centred correctly on hex grids

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7659]
Originally reported by Hexling#2928 https://discord.com/channels/170995199584108546/872553750877835264/993957866694258698

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win 10, foundry app  
**Short Description of bug:** Tiles dont line up to a hex grid properly.  
**Simple steps to reproduce the bug:** Make hex grid with size 100px. Place a 100px by 100px tile. Place an actor with the same image. The actor'token will line up perfectly(as shown below) but the tile will not. Rows/columns and odd/even does not matter.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/181748099-f927a9a4-d6d3-4020-8fe7-cb163130b71d.png)

**Comment by Fyorl** [comment]
Not sure this is a bug actually. We should check again in v10 with the new hex grid calculations but regular hexagons do not have square bounding boxes, they have rectangular ones, which means that a square tile will not be able to line up with a single hex, unless we apply some similar centring logic that we use for tokens.

**Comment by aaclayton** [comment]
The correct way to construct the hex tile graphic for perfect snapping in Foundry VTT is to align the top and left edges of the hex with the top and left edges of the image canvas.
