### ISSUE TITLE
Configuring multiple packs without await causes some of the updates to be dropped

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7660]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/872553750877835264/1002409984576999538

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, Node/Electron  
**Short Description of bug:** Configuring multiple packs without await causes not all of the updates to go through.  
**Simple steps to reproduce the bug:** 

```js
game.packs.forEach(p => p.configure({locked: false}));
```

The compendiums interface briefly flickers as if this worked but immediately after shows only like one pack having been toggled.

**Comment by aaclayton** [comment]
I'm not able to reproduce this issue.
