### ISSUE TITLE
If the light color is black and the color intensity nonzero, `hasColor` is true

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7663]
### What happened?

`data.color` was a number as pre v10, so the color black had the same effect as `null` in the `hasColor` check . Now in v10, `data.color` is (or may be) a `Color` object and therefore makes `hasColor` true assuming `alpha` is nonzero.
```js
this._flags.hasColor = !!(this.data.color && this.data.alpha);
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create light source with color `#000000` and inspect `canvas.lighting.placeables.at(-1).source._flags.hasColor`.

### What core version are you reporting this for?

Version 10 Testing 1 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
I failed to mentioned: this problem isn't limited to `LightSource#_initializeFlags` and `GlobalLightSource#_initializeFlags`, but also affected are
- `LightSource#_updateColorationUniforms`
- `LightSource#_updateIlluminationUniforms`
- `LightSource#_updateBackgroundUniforms`
- `VisionSource#_updateColorationUniforms`
- `VisionSource#_updateCommonUniforms`
```js
this.data.color ? /* ... */  : d.color;
```

**Comment by Feu-Secret** [comment]
The `PointSourceMesh` uniforms updates are now done correctly as well as `hasColor`.

**Comment by dev7355608** [comment]
Nothing was really changed by the `!== null`. Black did not count as a color in v9. To recreate v9 behavior the check would need to be something like this:
```js
this._flags.hasColor = !!(this.data.color?.valueOf() && this.data.alpha);
```

**Comment by Feu-Secret** [comment]
> Nothing was really changed by the `!== null`. Black did not count as a color in v9. To recreate v9 behavior the check would need to be something like this:
> 
> ```js
> this._flags.hasColor = !!(this.data.color?.valueOf() && this.data.alpha);
> ```

You can see that as a change in favor of consistency. A color, even full black, is a color. It forces us to explicitly set `data.color` to null if we want `hasColor` to be false.

**Comment by dev7355608** [comment]
Makes sense. `VisionSource` still needs an adjustment though, because it performs `this.data.color ? /* ... */ : /* ... */` checks in two cases, but depending on whether you passed `color` as a number or a `Color` to `initialize` you get different results for black. Core always passes `Color`, so it's consistent with `LightSource`, but I assume you should be still allowed to pass a number.
![image](https://user-images.githubusercontent.com/31905376/183116629-97b35f0a-440b-40ec-9f30-efdb133f4e22.png)

**Comment by dev7355608** [comment]
Another thing: `hasColor` is now `0` if `alpha` is zero instead of `false`:
![image](https://user-images.githubusercontent.com/31905376/183166580-0154720c-3549-4475-b56a-0a722654d8ab.png)
