### ISSUE TITLE
Changing core language is not persisted

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7665]
Originally reported by Viriato139ac#0342 https://discord.com/channels/170995199584108546/956306859491471420/1001219359773040782

**ALL MODULES DISABLED?** n/a  
**OS, Hosting, Browser (if applicable):** node + edge  
**Short Description of bug:** Changing language does not save on restart  
**Simple steps to reproduce the bug:** Configuration, change language to spanish, save changes, nothing happens, next start the server is again in english. Im testing 10.275  
**Screenshots and/or console errors:** none

**Comment by aaclayton** [comment]
Not reproduced. Was able to correctly change the core language to German or Spanish using their respective core translation modules.
