### ISSUE TITLE
Stopping a playlist throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7666]
Originally reported by ironmonk88#4075 https://discord.com/channels/170995199584108546/956306859491471420/1001369032991195256

**ALL MODULES DISABLED?** n/a  
**OS, Hosting, Browser (if applicable):** n/a  
**Short Description of bug:** Stopping a playlist from playing is throwing an error.  In the _unloadMediaNode function the `sourceNode` is set to undefined.  Then further down the element is referenced, but `element` returns the sourceNode, which has already been set to undefined.  
**Simple steps to reproduce the bug:** Start a playlist playing, then stop the playlist playing.

![image](https://user-images.githubusercontent.com/207433/181750392-d164c271-7469-4ea4-b835-e781c3fc2c01.png)

**Comment by aaclayton** [comment]
This was fixed in the prior release, the bug report was using an older version.
