### ISSUE TITLE
Add a feature to allow giving an explicit button title to deferred inline dice rolls which is used instead of flavor text

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7667]
Currently a deferred inline dice roll like `[[/r 3d8 # Some Flavor Text]]` will be rendered with "Some Flavor Text" as the button title - but it might be preferable to customize the button title using the same convention used for document links, i.e. `[[/r 3d8 # Some Flavor Text]]{Some Button Title}}` which could allow the title of the button to be different than the flavor of the resulting roll.

**Comment by mrkwnzl** [comment]
Thank you for considering it and creating this issue!

**Comment by Fyorl** [comment]
It seems we had a slight misunderstanding with the original issue, and intend to roll back that behaviour to how it was in v9, while adding the explicit label option.
