### ISSUE TITLE
Ensure that a custom Roll subclass is preserved when re-constituting roll data during ChatMessage data preparation.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7668]
Originally reported by EndlesNights#9000 https://discord.com/channels/170995199584108546/956306859491471420/1001574223598329976

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** n/a  
**Short Description of bug:** Issue with the ChatMessage Class, when called from Roll.toMessage sending messageData.

In `Roll.toMessage` the prepare chat data works fine, but the issue arise when  the `messageData` is sent to the `ChatMessage` class constructor. During this proses Roll.toJSON is called turning all your rolls data into a basic JSON object, and that's where I presume an issue is occurring with how `ChatMessage.prepareDerivedData()` is structured

One of the checks in `ChatMessage.prepareDerivedData()`  is `if(!(roll instanceof Roll))` but because the object being passed in as a JSON Object it will always resolve true. Then you call Roll.defaultImplementation to turn the  JSON Object back into a Roll Object. This is fine if you wanted to use the Roll Object. But it you had a class that extends off the Roll class, your object has suddenly changed into the parent class. So if you had overridden the `Roll.render`, or had custom html file on `static CHAT_TEMPLATE`, those will now be ignored when `ChatMessage._renderRollContent` renders the object because it is now using the values from the base Roll Class.

```js
  /** @inheritdoc */
  prepareDerivedData() {
    super.prepareDerivedData();

    // Create Roll instances for contained dice rolls
    this.rolls = this.rolls.reduce((rolls, roll) => {
      if ( !(roll instanceof Roll ) ) { //This will always resolve true, because it is testing against JSON objects, not Roll Objects, or objects that are made with from Classes that extend off of Roll
        try {
          rolls.push(Roll.defaultImplementation.fromData(roll)); //And then this turns the JSON into Roll Object regardless of what class the JSON had attached to it
        } catch(err) {
          Hooks.onError("ChatMessage#roll", err, {roll, log: "error"});
        }
      }
      else rolls.push(roll);
      return rolls;
    }, []);
  }
```

**Comment by gizmo2342** [comment]
With the latest changes subclasses of Roll no longer have a chance to take own actions in their static `fromData` method. Until now it was at least possible for the default implementation.

Could you please split up `fromData` into `fromData`and `_fromData` to (re-)enable subclasses to take own actions when reconstructing a roll from JSON data. This would be identical behaviour as done for RollTerm subclasses.

```
  static fromData(data) {
    let cls = this;
    if ( data.class && (data.class !== this.name) ) {
      cls = CONFIG.Dice.rolls.find(cls => cls.name === data.class);
      if ( !cls ) throw new Error(`Unable to recreate ${data.class} instance from provided data`);
    }
    return cls._fromData(data);
  }

  static _fromData(data) {
    // Create the Roll instance
    const roll = new this(data.formula, data.data, data.options);

    // Expand terms
    roll.terms = data.terms.map(t => {
      if ( t.class ) {
        if ( t.class === "DicePool" ) t.class = "PoolTerm"; // backwards compatibility
        return RollTerm.fromData(t);
      }
      return t;
    });

    // Repopulate evaluated state
    if ( data.evaluated ?? true ) {
      roll._total = data.total;
      roll._dice = (data.dice || []).map(t => DiceTerm.fromData(t));
      roll._evaluated = true;
    }
    return roll;
  }
```

**Comment by aaclayton** [comment]
I'll add a redirect to be sure that `Roll.fromData` redirects to the correct class `fromData` method.

**Comment by gizmo2342** [comment]
Just to mention it: First thing I do in my `fromData` method is to call `super.fromData()`. That's why I suggested `_fromData` to avoid an infinite loop. It would also be the same approach as done for `RollTerm`.
