### ISSUE TITLE
Creating a world compendium does not add an entry under 'packs' to the world.json

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7670]
Originally reported by shteff#8724 https://discord.com/channels/170995199584108546/956306859491471420/1001651466483802204

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux/NodeJS on Win 10, Self-hosting V10 Testing 1 (Build 275), Chrome.  
**Short Description of bug:** Creating a world compendium doesn't add compendium to the "world.json". The db file is created under "Data/worlds/your-world/packs" but the pack is not added to the "packs" parameter of the world.json  
**Simple steps to reproduce the bug:** Create a new compendium in your world. Stop the server and run it again. The Compendium is not shown in the compendium sidebar. The db file is created but the world.json is missing the pack definition.  
**Screenshots and/or console errors:** No errors or warnings.

**Comment by aaclayton** [comment]
I am not able to reproduce this issue.
