### ISSUE TITLE
FPS meter does not show

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7675]
Originally reported by orwen89#0293

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Electron  
**Short Description of bug:** The FPS meter doesn't show up  
**Simple steps to reproduce the bug:** 

- Check in the Show FPS meter checkbox in Configure Settings / Core Settings
- Save the changes.
- Look for the FPS meter on the canvas.

**Screenshots and/or console errors:** -

**Comment by aaclayton** [comment]
Not reproduced, presume related to some other bug.
