### ISSUE TITLE
Systems containing Actor or Item packs without a system field fail to load

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7678]
Originally reported by BadIdeasBureau#7024 https://discord.com/channels/170995199584108546/956306859491471420/1002355101559693393

**ALL MODULES DISABLED?** N/A (setup screen)  
**OS, Hosting, Browser (if applicable):** Windows app  
**Short Description of bug:**  Systems containing an Actor or Item pack which does not specify `system` in the pack's properties fail to load.  They should be treated as requiring the system they are part of.  
**Simple steps to reproduce the bug:** Install e.g. the `torgeternity` system. Observe the error messages on validation  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/181755128-091adf60-bdcf-4681-a488-e9d11934b1dc.png)

**Comment by aaclayton** [comment]
Comment from @theripper93:

### User Experience

At the moment packs require a system or they will fail to validate. I'm assuming a bugfix is coming to ignore this field if the module\system also declares a system dependency?

Even with such fix, my fear is that many users made their own "Shared Compendium" module, that i'm sure will not have any kind of system tags whatsoever. When regular users update to V10 there will be an unending stream of "Why my shared compendium isn't working" posts, from users that probably just copy pasted a template and are not tech savy enought to fix them.

**Comment by theripper93** [comment]
Not really a duplicate, I’m not referring to the bug itself (aka system modules requiring syatem tag in its compendiums ) , im referring to modules missing system tags in compendiums when a system dependency for the module is not indicated. I wander, how will those be handled?

**Comment by aaclayton** [comment]
> Not really a duplicate, I’m not referring to the bug itself (aka system modules requiring syatem tag in its compendiums ) , im referring to modules missing system tags in compendiums when a system dependency for the module is not indicated. I wander, how will those be handled?

That will not be handled. The module will have to be updated to correctly designate the required system.

**Comment by theripper93** [comment]
Ok, good to know!
