### ISSUE TITLE
`Dialog.confirm` will now always bring the Dialog window into Focus

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7681]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/956306859491471420/1002450390920466432

**ALL MODULES DISABLED?** N/A  
**OS, Hosting, Browser (if applicable):** Chrome  
**Short Description of bug:** Clicking on the "Save" button in the Module Management screen should either always create a new reload dialog or bring the existing one into focus  
**Simple steps to reproduce the bug:** Open Module Management; disable a module; click save but don't accept dialog; disable a second module; click save and nothing happens because the existing dialog is now hidden behind the Module Management window  
**Screenshots and/or console errors:**

**Comment by paulohdsc** [comment]
Possibly related:
https://github.com/foundryvtt/foundryvtt/issues/6143
https://github.com/foundryvtt/foundryvtt/issues/6383
