### ISSUE TITLE
Clicking Manage Modules throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7683]
Originally reported by Farling#9579 https://discord.com/channels/170995199584108546/956306859491471420/1002516945033252875

**ALL MODULES DISABLED?** false?  
**OS, Hosting, Browser (if applicable):** Node on Windows 11  
**Short Description of bug:** Within a world, clicking on Manage Modules generates an error and the window does not open  
**Simple steps to reproduce the bug:** Enter a world and click on Manage Modules button.  
**Screenshots and/or console errors:** 

![image](https://user-images.githubusercontent.com/207433/181756592-40f877f6-906a-44b3-8e94-ba85cd59e37b.png)

**Comment by farling42** [comment]
The module.json had a relationships.requires with a type of "system".

**Comment by aaclayton** [comment]
Probably an opportunity for us to harden our `_evaluateCompatibility` method to ensure it doesn't throw an error.
