### ISSUE TITLE
The global light source is recreated but never destroyed in `initializeLightSources`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7684]
### What happened?

The global light source is recreated in `initializeLightSources` but never destroyed, which creates a slight leak, because the geometry is never disposed. But instead of recreating and destroying, creating it once and only updating it in `initializeLightSources` would more appropriate.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
s = canvas.effects.lightSources.get("globalLight")
canvas.effects.initializeLightSources();
canvas.effects.refreshLighting();
console.log(s === canvas.effects.lightSources.get("globalLight")) // false
console.log(s.illumination.parent) // null
console.log(s.illumination.destroyed) // false
```

### What core version are you reporting this for?

Version 10 Testing 1 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
The global light source is now exposed as a public property : `canvas.effects.globalLight`, and destroyed properly.

**Comment by dev7355608** [comment]
The global light source is now destroyed in `tearDown`, but is still recreated in `_createGlobalLightSource` without being destroyed.

But there's no need to recreate the global light source in `initializeLightSources`. It only needs to be updated.

```js
initializeLightSources() {
    // ...
    this.lightSources.set("globalLight", this._updateGlobalLightSource());
    // ...
}

async draw() {
    // ...
    this.globalLightSource = this._createGlobalLightSource();
}

_createGlobalLightSource() {
     return new GlobalLightSource(canvas.scene);
}

_updateGlobalLightSource() {
    const {sceneX, sceneY, maxR} = canvas.dimensions;
    this.globalLightSource.initialize(foundry.utils.mergeObject({
      x: sceneX,
      y: sceneY,
      dim: maxR,
      walls: false,
      vision: false,
      luminosity: 0
    }, CONFIG.Canvas.globalLightConfig));
    return this.globalLightSource;
}
