### ISSUE TITLE
Optimize the `FramebufferSnapshot` class for light sources and darkness to avoid extra-blitting.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7685]
## 1. `PointSourceMesh.#priorBlendMode` is not reset

After all illumination components have been rendered, `priorBlendMode` needs to be reset to `undefined`. If not, we blit one more time that would be necessary: assuming one normal light source and one dark light source there would be a blit when the normal light source is rendered and when the dark light source is rendered.

## 2. Before the first blit the framebuffer texture must be cleared with the background color

This early exit is not correct in the context of what is actually passed as `requireUpdate`. The first call to `getFramebufferTexture` would need clear the framebuffer texture in the current implementation. Otherwise it returns the framebuffer texture in the state from the previous frame.
```js
if ( !(this.#hasResized || requireUpdate) && !this.#hasBackgroundColorChanged ) return this.framebufferTexture;
```

## 3. Keep a separate texture for the background color instead of clearing the framebuffer texture

Assuming (2) is fixed, then it would alternate between clearing and blitting. This is unnecessary. Until we would need to blit for the first time, we can use another texture that contains the background color (1x1 pixels) instead of the framebuffer texture. This way we don't need to clear the framebuffer texture each frame. This also makes `FramebufferSnapshot` simpler because it wouldn't need to manage the background color at all there.

---
---

## Suggestions

- Remove the background color parts of `FramebufferSnapshot`, and instead manage a simple 1x1 pixels texture elsewhere.
- Remove the `requireUpdate` parameter. (Not removing `requireUpdate` is also an option, but then `_currentFramebufferTexture` needs to be part of `FramebufferSnapshot`, otherwise `requireUpdate` wouldn't serve a purpose. I'd probably remove `requireUpdate` though because it makes `FramebufferSnapshot` simpler and easier to use.)

And the following changes (untested):
```js
// CanvasIlluminationEffects

// 1x1 pixels texture with the background color
// please do not make this #-private: I need to replace the texture in PV by my own
_backgroundColorTexture = PIXI.Texture.fromBuffer(new Float32Array(3), 1, 1, {
    type: PIXI.TYPES.FLOAT,
    format: PIXI.FORMATS.RGB,
    wrapMode: PIXI.WRAP_MODES.CLAMP,
    scaleMode: PIXI.SCALE_MODES.NEAREST
});

set backgroundColor(color) {
    this.background.tint = color;
    if ( this.filter ) this.filter.uniforms.replacementColor = Color.from(color).rgb;

// update the background color of the texture
   this._backgroundColorTexture.baseTexture.resource.data.set(Color.from(color).rgb);
   this._backgroundColorTexture.baseTexture.resource.update();
  }

render(renderer) {
// reset the blend mode and current framebuffer texture
    PointSourceMesh._priorBlendMode = undefined;
// until the first blit we use _backgroundColorTexture
    PointSourceMesh._currentFramebufferTexture = this._backgroundColorTexture;

    super.render(renderer);
}

// -----------------------------

class PointSourceMesh extends PIXI.Mesh {
  static _priorBlendMode;
  static _currentFramebufferTexture;

  render(renderer) {
    if ( this.uniforms.framebufferTexture !== undefined ) {
// only update if the blend mode changes for the first time
      const requireUpdate = (this.state.blendMode !== PointSourceMesh._priorBlendMode)
        && (PointSourceMesh._priorBlendMode !== undefined);

      if (requireUpdate) {
          PointSourceMesh._currentFramebufferTexture = canvas.effects.illumination.framebufferSnapshot.getFramebufferTexture(renderer);
      }

      this.uniforms.framebufferTexture = PointSourceMesh._currentFramebufferTexture;
      PointSourceMesh._priorBlendMode = this.state.blendMode;
    }
    super.render(renderer);
  }
}
```

Other suggestions:
- `framebufferSnapshot` doesn't need to be a part of `CanvasIlluminationEffects` anymore if it no longer manages the background color. In theory it could be used in other places as well: `canvas.framebufferSnapshot`?

**Comment by dev7355608** [comment]
I also request that `priorBlendMode` is replaced by `priorDarkness` (and `this.state.blendMode` by `this.uniforms.darkness`) or possibly something else. My new custom global light sources need to be blended with NORMAL(_NPM), both dark and normal light sources. But it still needs to blit on a switch between dark and normal. Of course if it's both NORMAL, no blit is performed. And if the first nonglobal light source is rendered, there might be an unnecessary blit.

Illumination shaders cannot be successfully NORMAL blended at the moment, but it would be possible with a minor change that doesn't affect core at all:
```js
// AdaptiveIlluminationShader

  static FRAGMENT_END = `
  if ( !darkness ) framebufferColor = min(framebufferColor, colorBackground);
  else framebufferColor = max(framebufferColor, colorBackground);
  gl_FragColor = vec4(mix(framebufferColor, finalColor, depth), depth);
  `;

  static FALLOFF = `
  depth *= (1.0 - smoothstep(0.98 - attenuation * 0.98, 1.0, dist));
  `;
```
This way the alpha (`depth`) is written in the alpha channel (instead of 1), which doesn't affect core, but allows the NORMAL_NPM blend mode to be used. This suggestion also fixes another issue: if for some reason a custom illumination shader didn't include `FALLOFF`, the framebuffer blending would be wrong, because the min/max operations with `colorBackground` are in `FALLOFF`.

**Comment by Feu-Secret** [comment]
@dev7355608 Thank you for the review and advices!
An interesting place where the color background texture could be managed is the `ColorManager` class.

**Comment by dev7355608** [comment]
- `_backgroundColorTexture` needs to be created with `mipmap: PIXI.MIPMAP_MODES.OFF`, otherwise webgl complains.

- `IlluminationVisionShader` needs some corrections:
```js
  /**
   * Constrain light to LOS
   * @type {string}
   */
  static FRAGMENT_END = `
  framebufferColor = min(framebufferColor, colorBackground);
  gl_FragColor = vec4(mix(framebufferColor, finalColor, depth), depth);
  `;

  /**
   * Incorporate falloff if a attenuation uniform is requested
   * @type {string}
   */
  static FALLOFF = `
  depth *= (1.0 - smoothstep(0.9985 - attenuation * 0.9985, 1.0, dist));
  `;
```

- `PointSourceMesh` should override `_render` not `render`. Otherwise it blits needlessly even if the mesh is invisible or culled.
