### ISSUE TITLE
Execute Macro in a Compendium API Call

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#7686]
### User Experience

Hi,

Can you create an API call to run a macro inside a compendium? Something like this:
`game.packs.get('My Compendium').runMacro('My Macro')`

This is useful to run macros without have to import them to the world. There are a lot of modules of compendiums of macros. After they update any of them, you need to import them again. This would let you just run the macro from the compedium, always running the last version.

**Comment by aaclayton** [comment]
This is possible as long as the calling player has permission to see the compendium pack (i.e. the pack is not private).
