### ISSUE TITLE
Eliminate the need for the special `NormalizedRectangle` class by incorporating its functionality entirely into the base `PIXI.Rectangle`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7687]
### What happened?

`NormalizedRectangle#clone` should return a `NormalizedRectangle`.

`NormalizedRectangle.EMPTY` should return a `NormalizedRectangle`.

`new NormalizedRectangle()` should return a valid rectangle: the parameters of the constructor should be optional and default to 0.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
new NormalizedRectangle(0, 0, 1, 1).clone() instanceof NormalizedRectangle // false
```

```js
NormalizedRectangle.EMPTY instanceof NormalizedRectangle // false
```

![image](https://user-images.githubusercontent.com/31905376/181815637-9431ddc6-e35e-4dc7-a2f9-e18c3b385a00.png)

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Ideally I would like to get rid of `NormalizedRectangle` alltogether and fold its functionality into the regular `PIXI.Rectangle`, but I'm not sure whether I can manage that without any sort of breaking change so it may have to wait for V10. In the near term I can make some of these changes to standardize things.
