### ISSUE TITLE
Alpha map generation was not tied to texture resolution.

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7689]
### What happened?

When the alpha map for a tile is generated, the time required to compute it seems to be only connected to the size of the tile, not of the texture itself. If this is the case and the texture is sampled one time for each "pixel" the tiles occupies this can probably be considerably optimized:

If the tile is larger than the texture size, sample all pixels from the texture, generate a UV mapping, and sample from those using UV coordinates of the tile.

If the tile is smaller than the texture, do the opposite (which is think is the method currently used)

This way we are not sampling the same pixels multiple times. It's possible that by doing it this way, nearest filtering is lost, but i don't think that's particularly relevant.

As a bonus, cache globally the pixel mapping of a specific texture by filepath so that it can be reused.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a tile using a 1x1 px image, make it scene size, observe the time needed to build the alpha map.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by theripper93** [comment]
I belive this issue to be tied to this, so i'll add it here

Grab any texture (any 1x1 texture is fine)
Make it a tile
Set as overhead
Make the tile larger than the max texture resolution of your gpu (17k x 17k)
Canvas will crash and not load again.

**Comment by Feu-Secret** [comment]
> I belive this issue to be tied to this, so i'll add it here
> 
> Grab any texture (any 1x1 texture is fine) Make it a tile Set as overhead Make the tile larger than the max texture resolution of your gpu (17k x 17k) Canvas will crash and not load again.

Resolving this issue will also resolve this problem.
