### ISSUE TITLE
Better handling of invalid module manifests in v10

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7690]
### User Experience

At the moment, if a module were to have a script in it's manifest that is not present in the module files, the module will fail to load and not show in the installed modules. This was (of curse) ignored in V9.

If a module has an update for V10 that fixes this in it's manifest, but this fix is not back ported to the v9 version, the module will fail to appear in the module list in v10.

While errors will be displayed, this results in a bad user experience since the user has to hunt down those modules and re-install them.

I'm not sure on what solution would be best, but i think this issue should be handled in some way by core.

**Comment by aaclayton** [comment]
If the installed version of the module is critically invalid (i.e. missing scripts) it will not be recognized by the server and it can be cleanly re-installed with a fresh (correct) version which will replace the existing bad data. I realize this isn't great for UX, but nothing *is* going to be great for UX if the user has managed to install an invalid module to begin with.

**Comment by theripper93** [comment]
Understandable, just sharing some thoughts , not gonna be a problem for me personally,  but I guess no longer supported modules that might otherwise work will get axed, but that is fine, it’s an edge case anyways.
