### ISSUE TITLE
`ClockwiseSweepPolygon#_compute` can no longer be overridden

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7691]
### What happened?

`ClockwiseSweepPolygon#_compute` can no longer be overridden because of the addition of the `#`-private `lastAddedPoint`.

Should `#addPoint` be `#`-private? Any subclass won't be able to add points to the polygon without recreating `addPoint`. Also `#lastAddedPoint` seems entirely unnecessary, because the last two elements of `points` could be inspected instead (`#addPoint` even unnecessarily creates a new `#lastAddedPoint` object each time it's called).

I'd remove `#lastAddedPoint`, make the method protected and add it to `PointSourcePolygon` (or possibly even `PIXI.Polygon`) so it could used by another implementation.

Let me know if you want `addPoint` to be able to remove almost colinear points as well, I've adapted Clipper's `CleanPolygon` into an `addPoint` method for my own use. I can share the code.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

---

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
> Let me know if you want addPoint to be able to remove almost colinear points as well, I've adapted Clipper's CleanPolygon into an addPoint method for my own use. I can share the code.

I would be curious to take a look, if you're okay to share. I'm not sure we would incorporate it at this point but I would be interested to learn the approach.

**Comment by dev7355608** [comment]
`closePoints` removes almost-colinearities between the first and last points (technically `closePoints` would need to add points to the end until no more colinear points are detected to really satisfy `distanceSquared`, but adding the first two points is good enough in most cases to dedupe and remove colinearities).

```js
addPoint(x, y, distanceSquared) {
    const points = this.points;
    const m = points.length;

    if (m >= 4) {
        let x3 = points[m - 4];
        let y3 = points[m - 3];
        let x2 = points[m - 2];
        let y2 = points[m - 1];
        let x1 = x;
        let y1 = y;

        if (Math.abs(x1 - x2) > Math.abs(y1 - y2)) {
            if ((x1 > x2) !== (x1 < x3)) {
                if ((x2 > x1) === (x2 < x3)) {
                    [x1, y1, x2, y2] = [x2, y2, x1, y1];
                } else {
                    [x1, y1, x2, y2, x3, y3] = [x3, y3, x1, y1, x2, y2];
                }
            }
        } else {
            if ((y1 > y2) !== (y1 < y3)) {
                if ((y2 > y1) === (y2 < y3)) {
                    [x1, y1, x2, y2] = [x2, y2, x1, y1];
                } else {
                    [x1, y1, x2, y2, x3, y3] = [x3, y3, x1, y1, x2, y2];
                }
            }
        }

        const a = y2 - y3;
        const b = x3 - x2;
        const c = a * (x1 - x2) + b * (y1 - y2);

        if ((c * c) / (a * a + b * b) > distanceSquared) {
            points.push(x, y);
        } else {
            const dx = points[m - 4] - x;
            const dy = points[m - 3] - y;

            points.length -= 2;

            if (dx * dx + dy * dy > distanceSquared) {
                points.push(x, y);
            }
        }
    } else if (m === 2) {
        const dx = points[m - 2] - x;
        const dy = points[m - 1] - y;

        if (dx * dx + dy * dy > distanceSquared) {
            points.push(x, y);
        }
    } else {
        points.push(x, y);
    }
}

closePoints(distanceSquared) {
    const points = this.points;

    if (points.length < 6) {
        points.length = 0;

        return;
    }

    const [x1, y1, x2, y2] = points;

    this.addPoint(x1, y1, distanceSquared);
    this.addPoint(x2, y2, distanceSquared);

    const m = points.length;

    [points[0], points[1], points[2], points[3]] = [points[m - 4], points[m - 3], points[m - 2], points[m - 1]];
    points.length -= 4;
}
```

**Comment by aaclayton** [comment]
Good suggestion to make the `addPoint` method a general extension of `PIXI.Polygon`. I agree that adds the most utility.
