### ISSUE TITLE
The scene background color is too dark in parts of the scene not covered with a background image.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7695]
### What happened?

The clear color of the primary group (`sceneBackground`) must not not be darkened because it is already affected by lighting.

Also `sceneBG.multiply(darkenBG)` does not match illumination exactly. It should be `sceneBG.multiply(this.colors.background)`.

```diff
    // Compute scene background color
    const sceneBG = Color.from(backgroundColor ?? scene?.backgroundColor ?? fbc.backgroundColor);
-   const darkenBG = Color.from(0xFFFFFF).mix(this.colors.darkness, this.darknessLevel);
-   this.colors.sceneBackground = sceneBG.multiply(darkenBG);
+   this.colors.sceneBackground = sceneBG;
+   this.colors.rendererBackground = sceneBG.multiply(this.colors.background);
```

```diff
    // Update primary cached container and renderer clear color with scene background color
-   canvas.app.renderer.backgroundColor = this.colors.sceneBackground;
+   canvas.app.renderer.backgroundColor = this.colors.rendererBackground;
    canvas.primary.clearColor = [...this.colors.sceneBackground.rgb, 1];
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Feu-Secret and I have gone back and forth multiple times on this. My requirement is that the visible canvas background color should grow darker as the darkness level increases. I'm not sure your proposed change accomplishes that since it ignores `this.colors.darkness` and `this.darknessLevel`

**Comment by dev7355608** [comment]
With my proposed changes the background color is illuminated just like a background image of the same color would be. In the current state the scene's background color is multiplied by `darkenBG` (which is almost the same as `colors.background`) and set as the clear color of the primary group. Then the illumination is multiplied on top of it. So the scene's background color is effectively multiplied by `colors.background` twice. In a scene with background color white and darkness level 1, the background ends up as `#050514` on the screen when it should be `#242448`.

**Comment by Feu-Secret** [comment]
This behavior is on purpose. We want the background color from the outer parts of the scene to change according to the darkness level, and we would prefer to avoir adding an extra graphics rendering just to preserve the background illumination which is not covered by a background image.

**Comment by dev7355608** [comment]
> We want the background color from the outer parts of the scene to change according to the darkness level [...]

With my suggestion that would still be the case. It's just that those parts are only affected once by Darkness Level, not twice.

**Comment by Feu-Secret** [comment]
@dev7355608 Example with images :
![image](https://user-images.githubusercontent.com/66535080/182190800-42179b08-2f98-40ab-9f56-85c57319db23.png)
![image](https://user-images.githubusercontent.com/66535080/182190846-26354903-e896-4479-a4bd-16b0abf20c42.png)
![image](https://user-images.githubusercontent.com/66535080/182190889-398612fc-1f79-47c6-ab4e-893ddfbbcaa4.png)

**Comment by dev7355608** [comment]
The padding area here is twice as dark as it should be.

But I see the issue know: the clear color of the primary canvas group affects the outer parts of the canvas as well but isn't affected by the illumination of it somehow. Setting `canvas.app.renderer.backgroundColor` has absolutely no effect now. I didn't test this code after the clear color changes. I wasn't suggesting to remove the darkness level effect on the outer parts of the canvas. I'll investigate this issue further.

**Comment by Feu-Secret** [comment]
@dev7355608 @aaclayton There is a solution for that : altering the scene clear color with the darkness level. Save a non altered background color, and create a graphics on the scene with the unaltered scene clear color. But, is it worth it? It is another scene sized graphics object to just preserve areas of the scene which are not covered by a background image.

**Comment by dev7355608** [comment]
I found the problem. The primary sprite is not affected by the mask on the primary group. Previously it didn't matter when the clear color was transparent. But now it does: the sprite renders the on the entire screen overriding the `renderer.backgroundColor`. So the mask of the primary must be applied to the sprite as well (or only to the sprite should work too).

Needs to be `render` instead of `_render`, otherwise the mask wouldn't be applied.
```diff
-  this.#sprite?._render(renderer);                          // Render the bound sprite
+  this.#sprite?.render(renderer);                          // Render the bound sprite
 ```

Give the sprite the same mask as the primary group:
```js
canvas.primary.sprite.mask = canvas.primary.mask
```

After these changes `renderer.backgroundColor` should have an effect again.

And then if the suggestion of this issue is applied, the padding and the outer regions should have the exact same color and are only affected once by Darkness Level.

**Comment by Feu-Secret** [comment]
> I found the problem. The primary sprite is not affected by the mask on the primary group. Previously it didn't matter when the clear color was transparent. But now it does: the sprite renders the on the entire screen overriding the `renderer.backgroundColor`. So the mask of the primary must be applied to the sprite as well (or only to the sprite should work too).
> 
> Needs to be `render` instead of `_render`, otherwise the mask wouldn't be applied.
> 
> ```diff
> -  this.#sprite?._render(renderer);                          // Render the bound sprite
> +  this.#sprite?.render(renderer);                          // Render the bound sprite
> ```
> 
> Give the sprite the same mask as the primary group:
> 
> ```js
> canvas.primary.sprite.mask = canvas.primary.mask
> ```
> 
> After these changes `renderer.backgroundColor` should have an effect again.
> 
> And then if the suggestion of this issue is applied, the padding and the outer regions should have the exact same color and are only affected once by Darkness Level.

Oh oh! Good catch!
