### ISSUE TITLE
Relax the requirement that drawing polygon points be integers in order to preserve detail when polygons are rescaled.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7704]
### What happened?

Scaling down destroys the polygon's shape, because the points are rounded. This is a polygon, not a circle.

![rounding](https://user-images.githubusercontent.com/31905376/182044075-024b1cc7-6065-4c2a-9048-582120bbad5a.gif)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See above.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
No milestone. The rounding of polygon points needs to be reverted.

**Comment by aaclayton** [comment]
Thanks for the bump. Was busy with GenCon
