### ISSUE TITLE
Clicking a content link to a TokenDocument opens its configuration page instead of the token actor

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7709]
Originally reported by Vlyan#6771 https://discord.com/channels/170995199584108546/956306859491471420/1002561028288159774

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser:** Windows/Electron, FVTT v276  
**Short Description of bug:** When using a token's uuid, the @UUID tag open the token configuration sheet instead of the token actor sheet.  
**Simple steps to reproduce the bug:** Paste an UUID of a token, for example, in chat. format is like :  `@UUID[Scene.Yrj5HuCOvHVQyky3.Token.JKvA4OEkrGf5BPWv]` and click on it to see the sheet opened.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/182135559-16f156f1-52c1-48cf-b5ae-ed8440a7d319.png)

**Comment by Fyorl** [comment]
I don't think this is a bug, unless it's a regression from how legacy content links worked (which is possible). I think it's more a case of the default behaviour of opening the Document's sheet not being particularly useful or what the user expects. An easy UX improvement to make regardless.

**Comment by aaclayton** [comment]
I recommend that we not make any change here at present. The status quo for all document types is that links to that specific document open their sheet. This seems like a case where the user is using an un-linked actor to represent a specific character which should certainly instead be a linked actor.
