### ISSUE TITLE
Disable Package Dependencies Auto Install button when none can be installed

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7710]
Originally reported by KaKaRoTo#1337 https://discord.com/channels/170995199584108546/956306859491471420/1002562414191071283

**ALL MODULES DISABLED?** N/A  
**OS, Hosting, Browser (if applicable):** Electron/The Forge  
**Short Description of bug:** Installing a package with dependencies results in some display issues (`install 0` on left button and `required range of .` on right description). Despite showing that 0 packages can be automatically installed, the button is functional and installs them.  
**Steps to reproduce:** Make sure `_mathjs` is uninstalled, install the `monsterblocks` module.  
**Screenshots:** (not sure which module was being installed in the first screenshot, but for the second one was monsterblocks)

![image](https://user-images.githubusercontent.com/207433/182136272-31b3a8dd-5f58-4ead-bde5-d4b168ae8325.png)

![image](https://user-images.githubusercontent.com/207433/182136292-c585b113-8ec9-4739-81a8-f0c87d5073e5.png)

**Comment by cswendrowski** [comment]
The other noted issue of "range of . " has been resolved in another issue
