### ISSUE TITLE
Correct an issue with server-side assignment of immutable fields which prevented changing a user role once it was previously set to "None"

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7711]
Originally reported by KaKaRoTo#1337 https://discord.com/channels/170995199584108546/956306859491471420/1002568370417324053

**ALL MODULES DISABLED?** N/A  
**OS, Hosting, Browser (if applicable):** Electron/The Forge  
**Short Description of bug:** Found this while doing QA for The Forge's User Manager. It's impossible to change a user's role in v10.  
**Steps to reproduce:** Go to User Configuration, change a player's role. Get error...   
**Note:** After creating a new user, I could change that specific user's role as much as I wanted, but not any of the other users that were already there. Even returning to setup made no different, but after restarting the Electron app entirely, I'd get the error on all users.  
**Screenshots:**

![image](https://user-images.githubusercontent.com/207433/182136515-e1b6607d-d0bb-4d03-998a-652ffc4f487f.png)

![image](https://user-images.githubusercontent.com/207433/182136538-8c0ee379-d276-4ff3-a2c1-616392b52239.png)

**Comment by aaclayton** [comment]
I am not able to reproduce this error. @KaKaRoTo is it possible that this is in some way specific to The Forge?

**Comment by kakaroto** [comment]
> I am not able to reproduce this error. @kakaroto is it possible that this is in some way specific to The Forge environment?

Nope, we tested this on local Electron and both I and @rikmarais reproduced the problem with Electron.
(that's where the screenshots were taken from)

**Comment by kakaroto** [comment]
![image](https://user-images.githubusercontent.com/27990/182191421-aa2da1dd-5b24-4724-af2c-a9cd5d13d777.png)
Just tried again (10.276), and it happens right after when changing the role. The users need to already exist when you start the app. (I changed player 3 from "None" to "Player" in this case)

**Comment by aaclayton** [comment]
Still not reproducible for me (using pre-existing users). Will ask for second opinions from the team.

**Comment by aaclayton** [comment]
We discovered that this issue has to do specifically with assignment of the "None" role, so that should lead towards a fix.

**Comment by kakaroto** [comment]
Ah cool! I'm glad then that I re-tested and gave that extra bit of info. I didn't think it was specific to the role used 👍 
Thanks!

**Comment by aaclayton** [comment]
Found the issue and solved.
