### ISSUE TITLE
Ensure that the ChatMessage#user field may not be null, correcting an error in rendering a ChatMessage causes the entire ChatLog to fail to render.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7712]
Originally reported by KaKaRoTo#1337 https://discord.com/channels/170995199584108546/956306859491471420/1002590834786586725

**ALL MODULES DISABLED?** Yes
**OS, Hosting, Browser (if applicable):** The Forge  
**Short Description of bug:** Chat log sidebar doesn't appear  
**Steps to reproduce:** I don't know, I assume a chat message's author doesn't exist. `ChatMessage.user` is `null` so `ChatMessage.isAuthor` crashes during the render of the `ChatLog` which causes the entire chat log to stop rendering.  
**Screenshots:**

![image](https://user-images.githubusercontent.com/207433/182137069-35dfa736-462e-4778-8bd8-0a194f962428.png)

![image](https://user-images.githubusercontent.com/207433/182137084-c19471bc-f2e4-4c5f-b51e-21236df8f5b5.png)

**Comment by aaclayton** [comment]
I'll look into the possible circumstances under which ChatMessage#author could end up being null.
