### ISSUE TITLE
Installing Foundry VTT on a fresh machine fails to create the user directory

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7713]
Originally reported by Phoenix#0009 https://discord.com/channels/170995199584108546/956306859491471420/1002679559340167280

> Installing V10.276 on a fresh machine that has never run foundry produces 

```
Error: No valid user data path was available. Check your application config.
    at configurePaths (file:///home/foundryuser/foundryvtt/resources/app/dist/paths.mjs:1:765)
    at Module.initialize (file:///home/foundryuser/foundryvtt/resources/app/dist/init.mjs:1:1222)
    at file:///home/foundryuser/foundryvtt/resources/app/main.mjs:30:15j
```

> It only happens if you have never had foundry installed prior to v10.276, so I suspect it isn't creating the user data folder for some reason.  If you go back and run v9 and then launch the v10.276 it loads fine.

**Comment by lykaios** [comment]
Hi, 

This is happening on 10.291 (again) - what was the fix? 

@aaclayton
