### ISSUE TITLE
Deactivating a module with a dependency that is also a system required dependency will no longer prompt to deactivate the dependency

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7714]
Originally reported by ghost#2000 https://discord.com/channels/170995199584108546/956306859491471420/1002710351382589480

**ALL MODULES DISABLED?** false, as this is related to deactivating modules required by the system  
**OS, Hosting, Browser (if applicable):** irrelevant  
**Short Description of bug:** When deactivating a module ("A") that has the same dependency on another module ("B") as the system, foundry prompts the user to deactivate module ("B"). If the user clicks "Yes", the (disabled) checkbox for module "B" is unchecked. However, saving doesn't actually deactivate module "B", so it's just a visual bug. Probably the user should simply not be prompted to uninstall module "B", as it is a system dependency.  
**Simple steps to reproduce the bug:**

1. Install a system that has a dependency on a module (I just added a dependency to `lib-wrapper` to dnd5e, for testing purposes)
2. Install another module that also depends on the same module
3. Load a world with that system
4. Activate the the second module (and reload)
5. Deactivate the second module
6. Observe the prompt to disable the module depended upon by the system

**Screenshots and/or console errors:**

https://user-images.githubusercontent.com/207433/182137884-f24b7442-126b-4355-98c2-082ad067c53e.mp4

**Comment by aaclayton** [comment]
Related issue <https://github.com/foundryvtt/foundryvtt/issues/7708>
