### ISSUE TITLE
Activating a layer and a tool at the same time does not work

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7720]
### What happened?

Activating a layer and a tool at the same time does not work.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Make sure the target tool is not active. Switch to another layers. Then execute:
```js
canvas.tokens.activate();
ui.controls.initialize({ tool: "target" });
```
Result: target tool is not active.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is a difficult bug to solve because there is a race condition between two separate render calls. I'd like to improve this with some architectural changes, but those need to wait for Application V2.

Instead I have added an option to `InteractionLayer#activate` which allows you to request a specific tool as part of the activation flow, i.e.:

```js
canvas.tokens.activate({tool: "target"});
```

Hopefully this resolves your use-case without necessarily resolving the underlying bug.

**Comment by dev7355608** [comment]
If the layer is already active, the requested tool isn't activated. Is this intended?

**Comment by aaclayton** [comment]
Yes, if the layer is already active you would need to activate the tool using the direct API provided by the SceneControls. I know this is not ideal, but there is not a direct way to make this better at the moment. Further improvement here likely depends on the long-awaited "Application V2" framework which will change a great many aspects of our UI rendering pipeline.

**Comment by dev7355608** [comment]
I see. This has definitely made activating layers and tools prettier, so I appreciate the change.

```js
function activateLayer(layer, tool) {
    if (tool) ui.controls.controls.find(c => c.layer === layer).activeTool = tool;
    if (canvas[layer].active) ui.controls.render(true);
    else canvas[layer].activate();
}
```

```js
function activateLayer(layer, tool) {
    if (canvas[layer].active) ui.controls.initialize({ tool });
    else canvas[layer].activate({ tool });
}
```
