### ISSUE TITLE
Invisible drawings are not migrated

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7721]
### What happened?

Invisible drawings (drawings with invisible line and fill style) are not migrated. They're just throwing data validation errors.

The line width and opacity, if zero, should be set to a nonzero value by the migration. Otherwise some users are going to lose their drawings, which they may have set to invisible on purpose. As you know some modules repurpose drawings: some GMs have developed the practice to make those drawings invisible to hide them completely.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create an invisible drawing in v9 and migrate to v10.

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Added a migration that forces previously invisible drawings to have a solid white stroke.
