### ISSUE TITLE
Persist the single/multi-page view state as an optional Journal Entry flag which provides persistence in view mode preference and a path for content creators to designate how they want their content to be viewed.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7724]

**Comment by Fyorl** [comment]
Comment from @arcanistzed

> This would be useful primarily for content creators wanting to distribute their content so that it appears in multi-page view mode by default. Essentially, this would be equivalent to configuring the render mode option. This could alternatively be saved directly in the journal data model instead of a flag.

**Comment by zeel01** [comment]
I would love this, as well as perhaps a global option to set the default preferred state. I don't really see myself using single page view very often, but it seems to always default back to it. Being able to also include this setting in premium content is nice bonus as well if the content is intended to be read in a particular way.
