### ISSUE TITLE
Player token does not does not persist FoW exploration

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7733]
Originally reported by Dick K#6417 https://discord.com/channels/170995199584108546/956306859491471420/1003760151901257758

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Chrome  
**Short Description of bug:** Player Token does not leave a persistent view of explored fog-of-war.  
**Simple steps to reproduce the bug:** Create new player actor, leave image as Mystery Man. Set Player's Light and Map's Light parameters as shown in screen captures below. Place on walled map with no lights and as a player, move token around. Fog-of-war clearance does not persist.  
**Screenshots and/or console errors:** No errors or messages in console while moving player. See screen capture for Actor and Scene Lighting parameters.

> I noticed that I had left the Unexplored and Explored colours as the default. I set them to Red and Yellow respectively but observed no change in behaviour. Apart from the light from the Token illuminating the immediately surrounding map, all I could see was the rest of the map in red. No yellow mask was left for explored areas.

![image](https://user-images.githubusercontent.com/207433/182591538-3eb25975-c304-440e-9b33-c339b24a0d92.png)

**Comment by Feu-Secret** [comment]
This is not a bug. The fog of war is not explored because the token has no vision enabled or a vision range of 0.

**Comment by Feu-Secret** [comment]
Edit: But, a token with a vision range of 0 should be able to explore fow with light sources. It is fixed.
