### ISSUE TITLE
Changing lighting parameters of an already-placed linked token has no effect

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7734]
Originally reported by Dick K#6417 https://discord.com/channels/170995199584108546/956306859491471420/1003774730362429501

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Chrome  
**Short Description of bug:** Changes made to Lighting parameters of placed, linked player token have no effect.  
**Simple steps to reproduce the bug:** Drag linked player token from sidebar onto map. Change the Lighting parameters of the placed token. No change in the token's Lighting is observed. Make same change to Prototype token, delete placed token and drag Prototype to map, change is observed.

**Comment by Feu-Secret** [comment]
This is not the case in V10. If there was a bug, it has been fixed.
