### ISSUE TITLE
Embedded Documents created by `Document#clone` with the  `keepId = true` option skip data preparation

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#7741]
### What happened?

Cloning a Document that has a parent while keeping its original ID will skip `Document#prepareData` because it already exists in the embedded `Collection`.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
  _initialize() {
    super._initialize();
    if ( !game._documentsReady ) return;
    if ( this.isEmbedded && this.collection?.has(this.id) ) return; // Embedded documents are prepared by their parent
    try {
      this.prepareData();
    } catch(err) {
      Hooks.onError("ClientDocumentMixin#_initialize", err, {
        msg: `Failed initial data preparation for ${this.documentName} [${this.id}]`,
        log: "error",
        id: this.id
      });
    }
  }
```

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
thanks for the report, I got this fixed and it will be included in the next release.
