### ISSUE TITLE
Restore JSON dtype handling to `FormDataExtended`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#7742]
### User Experience

Prior to Foundry V10, `FormDataExtended` handled a "JSON" dtype by running the input value through `JSON.parse`:

```js
 /**
   * Export the FormData as an object
   * @return {object}
   */
  toObject() {
    const data = {};
    for ( let [k, v] of this.entries() ) {
      const dtype = this.dtypes[k];
      if ( dtype === "Boolean" ) v = v === "true";
      else if ( dtype === "JSON" ) v = JSON.parse(v);
```
It turns out this was intended for internal use only, but its availability was such that some systems (:eyes:) and modules were making liberal use of it. While stock DOM input elements don't individually provide good UI for editing complex data structures, some popular JS libraries can facilitate it some extent (the following is stored as an array):

![Screenshot from 2022-08-03 12-57-32](https://user-images.githubusercontent.com/106829671/182691376-08303c43-c46f-41e3-9039-3ebe22b60466.png)

 Can support for this dtype be restored?

**Comment by aaclayton** [comment]
Restored support for the "JSON" dtype, but only if explicitly specfied as a `data-dtype` on the HTML input.
