### ISSUE TITLE
`package.json` still references gitlab repository

### ISSUE THREAD

**Issue by Jagusti** [foundryvtt/foundryvtt#7743]
### What happened?

There's no functionality fail here, just some outdated info. As it's in package.json I've filed it as a bug rather than documentation error. 

>   "repository": "https://gitlab.com/foundrynet/foundryvtt",
>   "bugs": "https://gitlab.com/foundrynet/foundryvtt/issues",

should be

>   "repository": "https://github.com/foundryvtt/foundryvtt",
>   "bugs": "https://github.com/foundryvtt/foundryvtt/issues",

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I was looking for my installed build number and ended up opening package.json in the main application folder. That's when I saw the above. 

### What core version are you reporting this for?

Version 10 Testing 2 (build 276)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Thanks, this should be fixed in the next release.
