### ISSUE TITLE
Switch to using header request based user agent hints.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#7750]
### What happened?

The `Support` reporting tool currently fails to identify modern Mac hardware/OS combos, in both Chromium/Electron and Firefox.

On an M1 Mac running macOS 12.5, this is the Chromium report:

```
OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
GPU: ANGLE (Apple, Apple M1, OpenGL 4.1)
```
and this is the Firefox report:
```
OS: Intel Mac OS X 10.15
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0
GPU: Apple M1
```

I know we're up against whatever the browsers are providing for useragent strings, but it would be nice if we could find an alternate heuristic perhaps. This is certainly small-potatoes, but figured it was worth noting for the record.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Check the `Support Details` screen from an M1 Mac.

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by plutoneld** [comment]
It's possible this is because of an ongoing reduction of User Agent strings, which presumably Firefox would be adopting as well.

Mac OS platform has been capped at 10.15.7 since Chrome 90.

https://www.chromium.org/updates/ua-reduction/

**Comment by aaclayton** [comment]
I'm not sure what we could/should do better here - if anyone has suggestions I'm open to them otherwise I think this is probably too low priority for us to focus on.

**Comment by plutoneld** [comment]
I'm not sure what state User Agent Client Hints is in for the different browsers, but maybe migrating to that and using `Sec-CH-UA-Platform` and `Sec-CH-UA-Platform-Version` could improve the situation: https://web.dev/user-agent-client-hints/

**Comment by cswendrowski** [comment]
I don't normally like to ask others to do our homework, but for this particular issue I would ask someone with Mac hardware to do some exploration and let us know what options work best for detection. Anything I would do here would just be a shot in the dark unfortunately

**Comment by plutoneld** [comment]
I just noticed a caveat with using UA CH headers: they're only available over secure connections/HTTPS. So I guess that's a bad choice for the Support tool.

But per this site https://web.dev/migrate-to-ua-ch/ you should check `navigator.userAgentData` before falling back to `navigator.userAgent`. And you could potentially do
`navigator.userAgentData.getHighEntropyValues(
    ["platform", "platformVersion"])
  .then(ua => { console.log(ua) });`
to get the platform and version. This works in Chrome and in the Electron app consoles when connected to the FVTT server. Where the current `navigator.oscpu` in Support tool gives "Unknown" for me, the above snippet gives "Linux" and "5.15.0" (kernel version).

.userAgentData is notable not available in Safari or Firefox currently: https://caniuse.com/mdn-api_navigator_useragentdata

**Comment by aaclayton** [comment]
Originally reported by rathlord https://discord.com/channels/170995199584108546/1065764070680186930/1157682125177368586

**ALL MODULES DISABLED?** Yes/NA
**OS, Hosting, Browser (if applicable)**: Ubuntu, self hosted, Safari
**Short Description of bug**: Shows unsupported version even when version matches recommended
**Simple steps to reproduce the bug**: Connect to Foundry using Safari on the latest version
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/710bc687-702c-45fa-91bd-ea40f4a69f50)

**Comment by aaclayton** [comment]
I think this is high priority to try and address before V12 stable so we have actionable information in our support report.
