### ISSUE TITLE
[V10 - ProseMirror] Injecting HTML into the DOM breaks ProseMirror behavior

### ISSUE THREAD

**Issue by DarKDinDoN** [foundryvtt/foundryvtt#7752]
### What happened?

Exact same issue as: https://github.com/foundryvtt/foundryvtt/issues/7460
But with ProseMirror instead of TinyMCE

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See: https://github.com/foundryvtt/foundryvtt/issues/7460

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Are you able to provide some more information? Is this occurring on an `ActorSheet`, or a `JournalPageSheet`, or something else? If it's an `ActorSheet` (which doesn't use ProseMirror by default), how are you instantiating the ProseMirror editor?

**Comment by DarKDinDoN** [comment]
Hi @Fyorl 

It's occurring on a JournalPageSheet with ProseMirror as the default sheet.

**Comment by Fyorl** [comment]
I'm not able to reproduce this, could you provide some minimal reproduction steps that demonstrate this issue?

My attempt at reproduction registers the following hook to inject HTML content. You can see from the attached video that subsequently opening the page for editing does not include any of the injected HTML, as expected.

```js
Hooks.on('renderJournalPageSheet', (sheet, html) => {
	html.each((i, el) => el.querySelectorAll?.('img').forEach(img => {
		const div = document.createElement('div');
		const btn = document.createElement('button');
		btn.textContent = 'Injected Button';
		img.parentElement.appendChild(div);
		div.appendChild(img);
		div.appendChild(btn);
	}));
});
```

https://user-images.githubusercontent.com/207433/183078060-e6d823ee-c44b-42e2-9890-135ed22c751b.mp4

**Comment by DarKDinDoN** [comment]
@Fyorl 

I'm using the V10 branch of Share Media which brings v10 compatibility: https://github.com/DarKDinDoN/share-media/tree/v10
-> Zip file here: [share-media-10.zip](https://github.com/foundryvtt/foundryvtt/files/9268803/share-media-10.zip)

Here is a demo video (working great with TinyMCE):

https://user-images.githubusercontent.com/1687854/183081643-a2a03aa2-d2d7-4fdc-b6bf-e47e5b76bb39.mp4

**Comment by DarKDinDoN** [comment]
About Share Media.

Hooks is here: https://github.com/DarKDinDoN/share-media/blob/v10/modules/main.js#L37

HTML Injection happens here: https://github.com/DarKDinDoN/share-media/blob/v10/modules/media-wrapper.js#L11

**Comment by Fyorl** [comment]
I diagnosed your issue to line 24 of `media-wrapper.js`

```js
const medias = html.find(selectors.join(',')).add(selectors.join(','))
```

The `.add` is not limited to the scope of the elements in `html`. It will globally match those selectors and add the found elements to `medias`, so they are matching the `img` element inside the ProseMirror editor and adding HTML content inside the editor. This content is then saved when the editor is closed.

The reason it doesn't affect TinyMCE is because TinyMCE's editor content is inside an `<iframe>`, and the selectors will not match elements in a separate document entirely.

I would recommend changing your hook to the following (this will only work in v10):
```js
export const wrapMedias = ([,, html]) => {
  const selectors = [ /* ... */ ];
  const medias = html?.querySelectorAll(selectors.join(',')) ?? [];
  medias.forEach(media => {
    /* ... */
  });
};
```

**Comment by DarKDinDoN** [comment]
@Fyorl So sorry for wasting your time.
Obviously, I did not debug this enough 😞.

If I may, the main reason I tried `.add(selectors.join(','))` was because the HTML object does not contain any css classes that reference the type of journal sheet page (text, image, pdf or video). They all have three nodes: header, text, section/figure/div.

I could have a specific handler for every type of sheet, but then, it would add a lot of code.
Having to deal with this only with CSS selectors if more efficient (I guess?).

So in the latest update I had to `html.parent().parent()` in order use selectors like `article.journal-entry-page.text img` or `article.journal-entry-page.text video`

**Comment by Fyorl** [comment]
That's fine. You can also use:

```js
export const wrapMedias = html => {
  const page = html.closest('.journal-entry-pages');
};
```

It's less fragile than `parent().parent()` as it should keep working even if the HTML structure is changed (which is possible with a custom sheet, for example).

**Comment by DarKDinDoN** [comment]
Thx for the tip!
