### ISSUE TITLE
Content within summary tags is wrapped in paragraph tags causing display issues

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7755]
Originally reported by MaxPat#7936 https://discord.com/channels/170995199584108546/956307084931112960/1004940909420486726

> When I put `<details><summary>Title Text Here</summary><p>Feature Text Here</p></details>` into the ProseMirror's Source HTML, then save, it adds `<p>` elements to the summary, which leads to the Details expand/collapse triangle to be on a separate line than the summary, is there a way to prevent that?
Also, pasting the code from the Prose into MCE gets rid of the Summary tags, so Title Text and Feature test are in the collapsible section, so it seems HTML isnt transferable between the two?

![image](https://user-images.githubusercontent.com/207433/183067490-bf18c833-b19d-41c1-a194-e2035494c14d.png)

![image](https://user-images.githubusercontent.com/207433/183067513-cd9d45a6-1a84-42e8-8a1d-da49836f6200.png)

**Comment by Fyorl** [comment]
Because summary elements allow heading elements as children (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary), it means that they can accept both 'inline' and 'block' content in ProseMirror terms. The ProseMirror schema does not support a node with both inline and block content, it must be one or the other. Our schema currently defines summary elements as accepting block content (to allow for heading elements), so if ProseMirror encounters a summary element with inline content, it wraps it in `<p>` tags in order to convert it to block content. The same thing happens in many other places (notably list item elements).

There are ways to address this but none of them are particularly simple. The simplest way to resolve this, in the short-term at least, is to provide some styling rules that change the block display and remove margins from `summary > p` elements.

**Comment by aaclayton** [comment]
I think we can close this as a wontfix given the technical requirements for ProseMirror block elements.

**Comment by Fyorl** [comment]
Reopening this as we think we have a technique we can use with the ProseMirror schema to improve the behaviour here.
