### ISSUE TITLE
When pulling with a ping (shift+longpress), zoom players to the pinger's zoom level

### ISSUE THREAD

**Issue by itamarcu** [foundryvtt/foundryvtt#7763]
### User Experience

Current behavior zoom in for everyone, pinger included, to be zoomed in to a specific level (scale = 1).

Instead, I'd like the zoom level to mirror the original one that the ping-creator had while pinging.

This would be helpful for large maps and cases where players prefer seeing a zoomed out version of the map rather than a cropped zoomed-in version.

Example:

Before - 
![image](https://user-images.githubusercontent.com/6516621/183237968-225d2633-eb13-41f1-aeb0-a3a69ccc975c.png)

After pinging, currently - 
![image](https://user-images.githubusercontent.com/6516621/183237980-1de61bf4-b77c-4bd1-879b-e0334f506e5b.png)

My request - 
![image](https://user-images.githubusercontent.com/6516621/183237995-5fcfbf73-41df-4cce-8575-92eac734ef0e.png)

related: #6963

**Comment by aaclayton** [comment]
Sensible request. I don't recall why we had hard-coded this initially, I think matching the zoom level of the GM user makes sense.
