### ISSUE TITLE
Rename the Actor#getTokenData method with a deprecation warning to reflect clearly that the method now returns a TokenDocument and not just data.

### ISSUE THREAD

**Issue by spetzel2020** [foundryvtt/foundryvtt#7766]
### What happened?

Quick Encounters fails in the `new TokenDocument()` call (with all other modules disabled) when trying to execute this token creation:
```
                    const tempTokenData = await actor.getTokenData(tokenData);
                    tempToken = new TokenDocument(tempTokenData, {actor: actor});
```

Console error is below:

`tempTokenData._id` exists but is `null`

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open an existing Quick Encounter
2. Press the [Run Quick Encounter] button
3. Nothing happens - log shows it failing at this step

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Relevant log output

```shell
commons.js:3514 Uncaught (in promise) TypeError: Cannot assign to read only property '_id' of object '#<TokenDocument5e>'
    at SchemaField._cleanType (commons.js:3514:20)
    at SchemaField.clean (commons.js:3246:19)
    at TokenDocument.cleanData (commons.js:4836:26)
    at TokenDocument._initializeSource (commons.js:4823:31)
    at new DataModel (commons.js:4706:21)
    at new Document (commons.js:5224:3)
    at new BaseToken (commons.js:9516:3)
    at new ClientDocumentMixin (foundry.js:12672:5)
    at new <anonymous> (foundry.js:11845:5)
    at new TokenDocument (foundry.js:21165:5)
```
`tempTokenData._id` exists but is null:
```
tempTokenData;
TokenDocument5e {name: 'Death Slaad', displayName: 20, actorId: 'Q0P0IVG3Oll6rNMp', #valid: true, #sort: 0, …}
actorData: {}
actorId: "Q0P0IVG3Oll6rNMp"
actorLink: false
alpha: 0.5
bar1: {attribute: 'attributes.hp'}
bar2: {attribute: 'attributes.ac.value'}
displayBars: 40
displayName: 20
disposition: -1
effects: []
elevation: 0
flags: {}
height: 1
hidden: true
light: LightData {alpha: 1, angle: 360, bright: 0, color: null, #valid: true, …}
lockRotation: false
name: "Death Slaad"
overlayEffect: ""
rotation: 0
sight: {enabled: true, range: 60, angle: 360, color: null, attenuation: 0.1, …}
texture: {src: 'images/img/MM/Death Slaad.png', scaleX: 1, scaleY: 1, offsetX: 0, offsetY: 0, …}
width: 1
x: 5353
y: 2036
_actor: Actor5e {name: 'Death Slaad', type: 'npc', img: 'images/img/bestiary%2FMM%2FDeath%20Slaad.jpg', system: {…}, #valid: true, …}
_destroyed: false
_object: null
#sort: 0
#valid: true
apps: {}
collections: {}
pack: null
parent: null
_id: null
_sheet: null
...
```
```


### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is a bit of a niche issue arising from non-ideal naming of some API methods and a bit of misuse. 

`Actor.getTokenData` actually now returns a `TokenDocument` instance instead of just a data object. We should consider renaming this method with a deprecation path. 

You are then passing a `TokenDocument` as the constructor param to create another `TokenDocument` which is unnecessary. Your first line of code is all you need:

```js
const tempToken = await actor.getTokenData(tokenData);
```

Using a document to construct another document is something we can perhaps add a conversion shim to support as well though.

**Comment by spetzel2020** [comment]
> `Actor.getTokenData` actually now returns a `TokenDocument` instance instead of just a data object.

Ok, I missed that important point. Will put in some v10 specific branching to handle it.
