### ISSUE TITLE
Assign a more specific CSS class name to style the table of contents side panel

### ISSUE THREAD

**Issue by zeel01** [foundryvtt/foundryvtt#7767]
### User Experience

At the moment, there are a number of styles using the selector `.sheet.journal-entry .sidebar` to style the table of contents panel. Notably, these styles specify the text color and background:

```
.sheet.journal-entry .sidebar {
	background: transparent;
	color: var(--color-text-light-highlight);
}
```

The class `.sidebar` is very generic, and this selector has relatively high specificity. User content, and more likely content modules, may use this class to style sidebars within the text (there are multiple premium modules that already do this). For instance, an `<aside class="sidebar">` is a common occurrence. Unfortunately, with the above style definition in play, content modules need to add extra specificity to "beat" that style - and the background is pretty regularly going to be changed by a sidebar.

Since this "sidebar" is a top-level application component rather than a part of the content, it would be nice if it were referenced with a less generic class name. The same element also has the class `.directory` on it already, which is better but still pretty generic. Something like `.journal-sidebar` or `.journal-directory` would avoid the above issue, and would allow styles within the journal directory to be isolated completely from the journal content. At the moment, `.sidebar` is basically one half of the application, so all the styles within it can potentially effect content if it uses that class, and there's a lot of existing content that already does so.

**Comment by aaclayton** [comment]
I think I would like to see us moving towards using multiple selectors where possible, I think there is a reasonable use case for annotating all "sidebars" with the `.sidebar` class while also using a more specific class like `.journal-entry-sidebar` for specific rules.
