### ISSUE TITLE
Make more ProseMirror's functions public

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#7776]
There are functions in ProseMirror that are inaccessible and make adding menu entries that have their own `mark` or `cmd` impossible.

For example, adding something as simple as a span with a style, like the `underline` action, is pretty much impossible since I can't create a `MarkType` and don't have access to `toggleMark()`.

### User Experience
Modules that enhance the journal editor (in my case, Polyglot) will be hampered if ProseMirror gets pushed as the default journal editor and menu actions are restricted.

**Comment by Fyorl** [comment]
Most of the functions for manipulating editor state should now be available:

- `ProseMirror.commands` has all exports from `prosemirror-commands`
- `ProseMirror.transform` has all exports from `prosemirror-transform`
- `ProseMirror.list` has all exports from `prosemirror-schema-list`

The `keymap` function for generating a keymap plugin is also exposed via `ProseMirror.keymap`.
