### ISSUE TITLE
Separate out the permission for pinging the canvas from the show mouse cursor permission

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7778]

**Comment by oOve** [comment]
And please let us decide wether the players can shift ping the dm back and forth :)

**Comment by aaclayton** [comment]
I don't think we are going to add shift+ping permission for non-GMs at this time, but we can add a permission setting to control whether players can make regular pings.

**Comment by aaclayton** [comment]
Leaving this as-is for V10 Stable release. We can decide later whether to add a separate permission for it or keep it linked to cursors.

**Comment by aaclayton** [comment]
maybe reconsidering...
