### ISSUE TITLE
Pressing Ctrl+S or clicking the save icon scrolls the editor back to the top

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7781]
Originally reported by Farling#9579 https://discord.com/channels/170995199584108546/956306859491471420/1005131340418662400

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 11, Chrome 103.0.5060.134  
**Short Description of bug:** Pressing ctrl-S, or clicking the save icon, to save within the editor scrolls the journal page editor back to the top of the window - in V9 the window remained at the current editing point. (The editing position is lost when the save occurs, so the editing cursor is reset to the top? of the page)

**Comment by Fyorl** [comment]
I was not able to reproduce this with ProseMirror, only TinyMCE. It does not appear to be a regression from v9 behaviour however:

https://user-images.githubusercontent.com/207433/184133189-121e34ff-7ebb-4e1f-88ef-c548b6c439ea.mp4

**Comment by aaclayton** [comment]
I think we shouldn't invest any further effort into improving TinyMCE as long as this isn't a regression I'm comfortable with a wontfix here.
