### ISSUE TITLE
Rotation locked token does not call refreshToken hook anymore

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7783]
Originally reported by mclemente#5524 https://discord.com/channels/170995199584108546/956306859491471420/1005218457060651148

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Electron  
**Short Description of bug:** SHIFT+WASD on a Rotation Locked token isn't triggering token.refresh() anymore.  
**Simple steps to reproduce the bug:** 
Run `Hooks.on("refreshToken", () => console.log("Refreshed Token"));` on the console  
SHIFT+WASD a token, it'll trigger refreshToken (15 times btw)  
Lock a token's rotation and try to SHIFT+WASD it, it won't trigger refreshToken.  
Since the token is locked, `token#animateFrame` isn't called, so `token.refresh()` isn't either.

**Comment by Fyorl** [comment]
Raising to discuss but it seems like this might be working as intended. I'd assume we want to avoid unnecessary calls to `Token#refresh` wherever possible.

**Comment by mclemente** [comment]
Hello, I've reported this originally.
The main issue with that is that my module hooked on `preUpdateToken` and then wrapped `Token.refresh` to handle other logic, so it was unexpected for that interaction to break by the locked rotation. Any modules that assumed Token.refresh would be called by preUpdateToken will be affected by this.
I just wanted to be sure that was an intended change and not a bug. I'll try wrapping `updateToken` instead, since it isn't affected by the rotation.

**Comment by aaclayton** [comment]
@mclemente is this a V10 report? There are a few changes coming to token animation in the next update to address a couple bugs. I would expect that Token refresh is called during animation, as long as an actual animation is occurring.

**Comment by mclemente** [comment]
@aaclayton yes, it's for V10. Token refresh isn't called if you SHIFT+WASD a token anymore.

```js
//Token._onUpdate, 45313 on V10.277
// Animate changes or refresh immediately
if ( options.animate !== false ) this.animate(data, options.animation);
else this.refresh();
```
When SHIFT+WASD is used on a token (independent of rotation lock), its options.animate (and options.animation) is undefined, which always enters the `if`.
Then, on `this.animate()`, if the token's rotation is locked and there's nothing else to animate, the `attributes` object will be empty will return without calling token.refresh.

```js
//Token.animate, 44861 on V10.277
// Configure animation
if ( foundry.utils.isEmpty(attributes) ) return;
```

So, I'd suggest changing it to
```js
if ( foundry.utils.isEmpty(attributes) ) {
this.refresh();
return;
}

**Comment by mclemente** [comment]
This issue has been resolved. Thank you.
