### ISSUE TITLE
Context menu delete on header within Journal TOC is unclear that delete means entire page

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#7791]
When right clicking on a header contained within a journal table of contents, it isn't immediately clear that the 'delete' option refers to the page and not the section of the document, which could lead users to believe they are only deleting a subsection of the journal page rather than the entire page. 

In this screenshot, I've hovered over a particular subheader with the intent to delete just that subsection, unaware that it will delete the entire page when I click delete.

![image](https://user-images.githubusercontent.com/26660743/183551396-f72e6aff-9fc2-4f2d-8d90-5c3ed5603df2.png)

**Comment by aaclayton** [comment]
Downgrading this to "Medium" priority, but still something we should address. We'll need a workflow to un-mark a certain page section as active so we can reset focus back to the overall page level when the context menu becomes active.
