### ISSUE TITLE
Minor style change: add padding to bottom of the journal page sheets

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7792]
### User Experience

The viewing sheet has a padding at the bottom which looks great:
![image](https://user-images.githubusercontent.com/82790112/183567637-d072488c-eab7-4ede-abc9-ade3e481b21a.png)
The editing sheet has padding on all sides, but not the bottom, which looks a lot more crowded since the text mixes in with the background:
![image](https://user-images.githubusercontent.com/82790112/183567742-b151c60b-5c72-4c83-9d63-2505f1f9b1d9.png)

**Comment by Fyorl** [comment]
I think this is TinyMCE only. The ProseMirror editor has padding at the bottom.
