### ISSUE TITLE
Dragging and dropping a Document (other than a Macro) onto the Hotbar will create a macro which toggles display of the dropped Document's sheet.

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#7807]
### User Experience

A common thing that some modules ship (like the Battlezoo Bestiary premium module) is a macro in a macros compendium that opens/closes a journal entry. It would be nice if dragging a journal entry to the hotbar created a toggle entry for that journal without the need to ship a separate macro.

For regular users, it would also make it easier for the GM to pull up a scratch pad for any mid-session note taking.

**Comment by aaclayton** [comment]
Nice idea
