### ISSUE TITLE
Text drawings don't render cyrillic characters

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7809]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/956306859491471420/1006746173354299483

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux Mint Chrome  
**Short Description of bug:** Text drawings that have cyrillic characters don't have custom fonts (also on v9)  
**Simple steps to reproduce the bug:** Add a font with cyrillic support; Create a text drawing with russian characters and with that font; notice that the font isn't applied, but it works with latin characters. A drawing with a mix of cyrillic and latin characters doesn't work either.

**Comment by phenomen** [comment]
@Fyorl I've tested Cyrillic font as a custom Additional Font and have no issues with it.

![Foundry_Virtual_Tabletop_8mW3Feejv1](https://user-images.githubusercontent.com/138311/184519794-f25b1577-05bc-42f9-9ba5-a09a34acbd59.png)

![Foundry_Virtual_Tabletop_h9MyaP33tV](https://user-images.githubusercontent.com/138311/184519797-674cb82b-0a7a-4fa1-a991-108a19442484.png)
