### ISSUE TITLE
`foundry.utils.getProperty` throws an error if the target object is `null`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#7813]
### What happened?

See title.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open an item from a compendium that has an inline roll with a reference to an actor value e.g. `[[/r @attributes.hp.temp.value]]`,

```js
export function getProperty(object, key) {
  if ( !key ) return undefined;
  let target = object;
  for ( let p of key.split('.') ) {
    if ( typeof target !== "object" ) return undefined;
    if ( p in target ) target = target[p];
    else return undefined;
  }
  return target;
}
```
![image](https://user-images.githubusercontent.com/41452412/184216699-c879809e-bf08-4f96-aa63-6cb911ecd7e1.png)
(WTF Javascript?)

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Relevant log output

![image](https://user-images.githubusercontent.com/41452412/184215959-5b750cf8-f5f6-41fa-8e0a-24cf0726eb7c.png)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
> This also effects `hasProperty`, hopefully this has been addressed as well 🙇🏻

Thanks for the reminder, all set!
