### ISSUE TITLE
Editing element attributes via source HTML with ProseMirror doesn't save the attributes

### ISSUE THREAD

**Issue by moo-man** [foundryvtt/foundryvtt#7815]
### What happened?

Adding attributes such as custom classes to elements inside a ProseMirror editor doesn't seem to save.

https://user-images.githubusercontent.com/28637157/184446550-7d1060bc-20b1-4f6f-885c-f03fc0bf2f09.mp4

For reference, here's TinyMCE retaining the added class
https://user-images.githubusercontent.com/28637157/184446755-cdd86a0a-9be6-402a-a45c-dd221d669b75.mp4

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See Video - go into source, add whatever class you want to an element, and save. 

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Strange, that should definitely be supported. We'll look into it!
