### ISSUE TITLE
FormDataExtended consolidates groups of checkboxes with the same name into an array of booleans

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7819]
## Resolution (Andrew)

I have implemented what I believe to be a generalized solution for this problem is as follows:

If you assign a `value` attribute to an `<input type="checkbox">` the extracted value from `FormDataExtended` will be either the `value` or `null` instead of a boolean `true` or `false`.

The value will cast according to an explicitly provided dtype if present:
```
<input name="foo" type="checkbox">
<input name="foo" type="checkbox" checked>
<input name="foo" type="checkbox" value="hello" checked>
<input name="foo" type="checkbox" value="goodbye">
<input name="foo" type="checkbox" value="4" data-dtype="Number" checked>
<input name="foo" type="checkbox" value="5" data-dtype="Number">
```
When processed this would yield the following array: `[false, true, "hello", null, 4, null]`

This is a tricky one where depending on what markup you use or choices you make you could end up doing the wrong thing, but I think this is a better choice than what we are currently doing.

A key change between this behavior and what we did before in V9 is that in V9 we ONLY returned values for the checked boxes which caused you to lose track of the order of array elements. This proposal will always return a value for every input and will insert `null` into the extracted array for boxes which have a `value` but are not checked.

I call this a "generalized" solution because it also opens up an additional possibility for using singular checkboxes in this way. Suppose you want your checkbox to denote a specific value or null, a single checkbox (not in a radio array) would also produce this behavior. Something like:
```js
<input name="maximum" type="checkbox" value="100" data-dtype="Number">
```
The processed form would have `{maximum: 100}` or `{maximum: null}` depending on the checked state.

## Original Issue Below

Originally reported by Glutious#7241 https://discord.com/channels/170995199584108546/956306859491471420/1007348548184047777

**ALL MODULES DISABLED?** False (only module in development)  
**OS, Hosting, Browser (if applicable):** Chrome  
**Short Description of bug:**  
Not sure if this is a bug or intended response (if so, a pointer to documentation/example would be appreciated)

FormApplication in v9
```hbs
{{#each options}}
  <input type="checkbox" name="foo" value="{{ id }}" id="foo-{{ id }}">
{{/each}}
```

In `_updateObject`, the `foo` property of the `formData` object would be an array of the values for checked boxes.  Perfect.

Now in v10, the foo property is an array of Boolean (true/false) for each checkbox option.

**Screenshots and/or console errors:**

v9 vs v10

![image](https://user-images.githubusercontent.com/207433/184619441-a1eccc46-7a39-41e2-a85a-780da354b779.png)

![image](https://user-images.githubusercontent.com/207433/184619461-521ed6b8-6661-4e25-9a32-10ad030023d5.png)

**Comment by Fyorl** [comment]
This has come up a few times so I'm raising for discussion. I believe this changed as a result of a refactor of `FormDataExtended`. Core foundry code like the cards pass dialog accommodates this new structure so I'd assume it's working as designed.

**Comment by stwlam** [comment]
Could it honor dtypes and pull the input's value if set to String or Number?
