### ISSUE TITLE
Use the X-Forwarded-For header provided by a proxy server to learn the original client IP address when logging authentication failures

### ISSUE THREAD

**Issue by vizovitin** [foundryvtt/foundryvtt#7826]
### What happened?

Foundry logs incorrect client IPs when behind reverse proxy. This results in inability to set up certain security measures, such as Fail2ban.

Passenger incorrectly detects client IP for logging purposes. This results in 127.0.0.1 being logged as client IP for "authentication failed" messages. I expected to see external client IP instead.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Install Foundry behind a reverse proxy server, e.g. using https://foundryvtt.com/article/nginx/
2. Make sure X-Forwarded-For header is correctly set up and passed to the application
3. Install license and perform initial setup
4. Try to log in as Administrator with incorrect password
5. Create a player
6. Try to log in as the player with incorrect password
7. Check `Logs/debug.log` for "authentication failed" messages

**Actual result:**
See logs below. Client IP is logged as 127.0.0.1.

**Expected result:**
Real external client IP is logged.

**Note:** in my case Foundry is running via Passenger 6.0.13 on nginx 1.20.2, under Debian 10.5.
I checked that `X-Forwarded-For` header is correctly set up and passed to the application via a simple express app. So it looks like Foundry doesn't account for this header.

### What core version are you reporting this for?

Version 9 (build 269)

### Relevant log output

```shell
{"ip":"127.0.0.1","level":"warn","message":"User authentication failed for user Player1; invalid password","session":"1fd8eebd099e57b6af196e77","status":401,"timestamp":"2022-08-15 12:40:35"}
{"ip":"127.0.0.1","level":"warn","message":"Administrator authentication failed for session 1fd8eebd099e57b6af196e77; invalid password","status":403,"timestamp":"2022-08-15 12:40:48"}
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We support configuring a `hostname` that allows you to customize the URL used for external invitation links. This is configured at the server level, rather than at the client request level. We could, however, investigate adding support for `X-Forwarded-For` as a secondary method. The recommended approach is to configure your `hostname` in the core Foundry VTT `options.json` file alongside other things you likely need to configure for your proxy like `proxySSL` or `proxyPort`, etc...

**Comment by aaclayton** [comment]
We currently configure the Express server to trust the upstream proxy server IF either the `proxyPort` or `proxySSL` configuration fields are set. If you configure the `proxyPort` or add `proxySSL: true` then the upstream proxied IP addresses will be used and logged.

**Comment by vizovitin** [comment]
Thank you, it indeed works (I've set `proxySSL` in my configuration).
