### ISSUE TITLE
Certain Items Become Un-editable

### ISSUE THREAD

**Issue by slaterdamian** [foundryvtt/foundryvtt#7827]
### What happened?

I can not view item descriptions for certain groups of items (Weapons, Equipment, & Tools) in compendiums, in the imported list of items, and in character sheets. This applies to user-created items; items can be created but there is no way to edit the details as the window doesn't open when clicking it/the edit button on the character sheet.

This occurs with modules disabled, in a new world. 
Experienced Behavior:
![image](https://user-images.githubusercontent.com/39378669/184693118-ac7f6ebf-23a5-463d-8555-21803337c00c.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/39378669/184693164-21a587c9-fbdd-408c-b696-55dddb792abf.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I do not know how the bug manifests, but has been present since installing foundry.

### What core version are you reporting this for?

Version 9 Testing 1 (build 269)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Which version of the `dnd5e` system are you using?

**Comment by slaterdamian** [comment]
> 

1.6.3

**Comment by slaterdamian** [comment]
I don't know if it's helpful, but this is the error that appears in the console output when I attempt to click on 'edit item.'
![image](https://user-images.githubusercontent.com/39378669/184955126-7fa57995-b73a-4a82-b433-ef87f1d26f21.png)

**Comment by aaclayton** [comment]
I do not reproduce this issue on version 9.269 running dnd5e 1.6.3. Is it possible you have some modules active which are interfering with default behavior?

**Comment by slaterdamian** [comment]
I don't think so, as it occurred even when I first created the world and had no mods installed (and when I disable them/make a new world).

I just downloaded the current build directly from Github and overwrote the existing files. It appears to now be working.
