### ISSUE TITLE
`PlaceableObject` rendering should be informed by `CanvasDocument` data preparation

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#7828]
### User Experience

All `PlaceableObject`s have corresponding `CanvasDocument` classes that come with the standard data preparation cycle, but the prepared data is of little use--and inconsistently so to the extent that it is-- for the purpose of influencing rendering on the canvas. A placeable's `_onUpdate` method, for example, receives differential data directly from an update callback chain, and a data reset isn't performed by the associated canvas document until after a rerendering check is already complete. Working around this requires some subversion of core client operation. E.g., from a `TokenDocument` subclass:
```js
    _onUpdateBaseActor(updates = {}, options = {}) {
        super._onUpdateBaseActor(updates, options);

        if (this.isLinked) {
            const preUpdate = this.toObject(false);
            this.reset(); 
            const postUpdate = this.toObject(false);
            const changed = diffObject(preUpdate, postUpdate);
            this._onUpdate(changed, options, game.user.id);
        }
    }
```

Making `PlaceableObject` rendering wise to _prepared_ data would open up quite a bit for community development. This isn't something I would expect to happen in the near future, but it would be great if it could be considered for V11.

**Comment by stwlam** [comment]
I'm going to close this as being overly broad and make a few smaller issues instead.

**Comment by aaclayton** [comment]
> I'm going to close this as being overly broad and make a few smaller issues instead.

Thanks for considering that, I'll stay tuned.
