### ISSUE TITLE
World compendium packs should not require the system field

### ISSUE THREAD

**Issue by kakaroto** [foundryvtt/foundryvtt#7829]
### What happened?

Piggy backing off of issue #7678, which says that a pack from a system should not fail validation for missing the `system` field as it can be assumed to be for that system. The same can be said for world packs, which would be specific to the system the world is made for.
Testing v10 and seeing that one of my worlds wasn't appearing and found this in the log :
![image](https://user-images.githubusercontent.com/27990/184920558-7df8f636-22c5-4d1f-a499-013b88771381.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a world compendium pack, make sure it doesn't have a `system` field.
Confirm the world doesn't appear in setup page.

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Got this one handled!
