### ISSUE TITLE
Add strict validation to Roll objects added to ChatMessages which require those rolls to be evaluated.

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#7833]
### What happened?

It is permitted to create a chat message with an unevaluated roll, but that roll will be evaluated for each client upon rendering the message.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a chat message with an unevaluated roll.
2. View the same message as another user, or simply browser-refresh as the same user.

![image](https://user-images.githubusercontent.com/106829671/184973176-b31c96f7-fdb9-41df-8293-616fd0829753.png)

As player:
![Screenshot from 2022-08-16 14-52-10](https://user-images.githubusercontent.com/106829671/184973022-33654a2a-acf7-42ef-8fce-747786b0082a.png)

As GM:
![Screenshot from 2022-08-16 14-52-24](https://user-images.githubusercontent.com/106829671/184973384-7a621ed6-2cfc-48a8-885c-c3234119faf0.png)

As GM on refresh:
![Screenshot from 2022-08-16 14-52-30](https://user-images.githubusercontent.com/106829671/184973372-07047d26-66d1-429f-8435-11af73ce3612.png)

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
If the outcome of this issue were that chat messages would refuse to accept a non-evaluated roll, would you find that outcome satisfying, or would you regret saying anything?

**Comment by stwlam** [comment]
This actually turned up as a result of a discussion due to anxiety over reporting #7831. @cswendrowski suggested as a workaround that the second roll (in the example I gave, a followup damage roll) be included in the created message but initially unevaluated. If we could get #7832, I would have no opinion over how this issue is resolved.
