### ISSUE TITLE
Don't show Journal sidebar navigation buttons when there is just a single page

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7834]
### User Experience

All of these buttons (especially the two disabled ones at the bottom) don't serve any purpose if the journal entry only has a single page.
![image](https://user-images.githubusercontent.com/82790112/185021228-792745e8-d017-4967-ac7b-da6bfbded0d1.png)
I think that hiding the view mode button, the navigation buttons, and the directory when there is a single page makes it less cluttered and confusing since you don't need those.

**Comment by aaclayton** [comment]
You're not wrong that these are unnecessary when there is only 1 page, but I think this is a minority use case and I think consistency of UX is also valuable. I appreciate the suggestion, but I think keeping the behavior consistent wins the vote in my mind.
