### ISSUE TITLE
Clicking a linked compendium entry from within compendium content as a player does not work

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7838]
Originally reported by Arthega#3002 https://discord.com/channels/170995199584108546/956306859491471420/1008772374042255390

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows10 / Self hosted / Chrome (Version 104.0.5112.81)  
**Short Description of bug:** ERROR.DocumentSheetPermission - Cant link Contents anymore - as a PLAYER - the error shows - GM works.  
**Simple steps to reproduce the bug:** Install DnD5e System - Start the game - Open the Classes Compendium - Open Some random Class - click one of the linked compendium entries (Feats, Paths, ...)  
**Screenshots and/or console errors:** Screenshot attached - no console Errors.

![image](https://user-images.githubusercontent.com/207433/185130436-0e3b51b1-4671-4f46-92f4-0c897da1dee3.png)

**Comment by ArthegaAsdweri** [comment]
Come on guys... at least TRY to reproduce it... !?

This also applies to other Game Systems. (e.g. Shadow of the demon lord) - but I was using dnd5e v2.0.0-alpha2.

Seems like the default permission of compendiums changed. As I said - you can click the linked contents as a GM, you can't access them as a player.

Install a random game system where you can edit "Item Descriptions" for example. Remove the edit lock

-> Just copy one Compendium Entry into another Compendium Entries Description (TinyMCE).
-> Save
-> Login as test Player
-> You can't click the linked item: ERROR.DocumentSheetPermission

Same applies for imported items.

Seems like the user needs extended permissions for the linked compendium items to be able to open them. Although he can open them directly over the compendium - which does not make any sense.

This probably has to do something with the links being modified with an UUID. The generated links look like:

```
<a class="content-link" draggable="true"
   data-id="e66KZG4CTH55SedW"
   data-uuid="Compendium.demonlord.weapons.e66KZG4CTH55SedW"
   data-type="Item"
   data-pack="demonlord.weapons"
><i class="fas fa-suitcase"></i>Blowgun</a>
```

Links used to look like:
```
<a class="content-link spellLink"
   data-id="e66KZG4CTH55SedW"
   data-pack="demonlord.weapons"
><i class="fas fa-suitcase"></i>Blowgun</a>
```

**Comment by ArthegaAsdweri** [comment]
Also it does not matter what kind of privileges you grant a player:

![grafik](https://user-images.githubusercontent.com/68907471/185588263-1ebbe13b-9521-48e7-aadd-c03e990ca234.png)

Player and Trusted Players can't open the links - the Assistant GM and GM - with the same privileges can access the links.

**Comment by aaclayton** [comment]
@ArthegaAsdweri is the compendium pack that the linked content belongs to hidden, such that it is only visible to gamemaster users?

**Comment by ArthegaAsdweri** [comment]
No, they are visible for everyone. Like I said - the player can open the compendium and also open up the item - but as soon as the item is linked in some other compendium entry the ERROR.DocumentSheetPermission Error occurs.

**Comment by aaclayton** [comment]
I identified the bug here and have made a corrtection for our next release.

**Comment by ArthegaAsdweri** [comment]
Great, Good job! 👍 :)
