### ISSUE TITLE
JSON strings saved as settings of type String are being retrieved as [object Object] instead of the original string contents

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7839]
Originally reported by Wrycu#5714 https://discord.com/channels/170995199584108546/956306859491471420/1008781269305393242

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Ubuntu 20.04, self hosted, N/A  
**Short Description of bug:** Type casting on system-registered settings (from string to JSON)  
**Simple steps to reproduce the bug:**

```js
let test_setting = JSON.stringify([{'key': 'value'}, {'key2': 'value2'}])
console.log(test_setting)
console.log(typeof(test_setting))

game.settings.register("starwarsffg", "arraySkillList", {
  name: "Skill List",
  scope: "world",
  default: test_setting,
  config: false,
  type: String,
});

let registered = game.settings.get("starwarsffg", "arraySkillList")
console.log(registered)
console.log(typeof(registered))
```

![image](https://user-images.githubusercontent.com/207433/185132910-b4b31894-f51c-4407-adbc-b63ce24e60cf.png)

**Comment by aaclayton** [comment]
An improvement in V10 is that the serialization/unserialization of game settings is handled automatically by the data model. 

The underlying data type that the user is storing here is an `Array`, but you are encoding the setting as a `String`. This results in the raw setting (an array) getting unserialized from JSON and then being re-cast to string (incorrectly). I can implement a workaround for this case though.

The recommended configuration for this setting would be:

```js
game.settings.register("world", "skillList", {
  name: "Skill List",
  scope: "world",
  default: [{'key': 'value'}, {'key2': 'value2'}],
  config: false,
  type: Array,
});
```
