### ISSUE TITLE
WebP portrait images distort in journal when height and width are set to 100%

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7840]
Originally reported by ClaytonThomson#8031 https://discord.com/channels/170995199584108546/956306859491471420/1009214819355861082

**ALL MODULES DISABLED?** True (5e System)  
**OS, Hosting, Browser (if applicable):** MacOX self hosted  
**Short Description of bug:** WebP portrait images distort in journal when height and width are set to 100% (image size is 2000px)  
**Simple steps to reproduce the bug:**
1. Create a journal entry page in an an existing journal entry
2. Place a landscape oriented WebP image. Note that graphic is not distorted.
3. Repeat process with a portrait oriented WebP image. Note that the image is squished vertically.
4. I do not see this behavior in v9. I'm using v10 Testing 2, build 276 presently because I get errors in Testing 3 when exporting to compendiums.

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/185134520-30966139-36dc-4aee-b359-2b3ca98364f1.png)

**Comment by Fyorl** [comment]
The reporter indicates they're using an older build so maybe this is fixed already. Could also be a TinyMCE issue where it's setting an explicit width and height in some cases.

**Comment by aaclayton** [comment]
Closing as nonrepro
