### ISSUE TITLE
Create compendium dialog does not use placeholder for default name

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7841]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1009242733824712704

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** any  
**Short Description of bug:** Create compendium dialog does not use placeholder for default name  
**Simple steps to reproduce the bug:** Attempt to create compendium and change its name.  
Create actor/item/rolltable/cardstack/playlist uses placeholder to show default name, while create compendium uses actual text.

**Comment by aaclayton** [comment]
Assigning to @cswendrowski as the owner for this set of changes.
