### ISSUE TITLE
Error for missing system template.json is ambiguous

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7842]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1009248425042268221

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** any  
**Short Description of bug:** Error for missing template.json is ambiguous on the actual cause  
**Simple steps to reproduce the bug:** Launch a system with no template.json  
**Screenshots and/or console errors:**

```
foundry.js:56761 TypeError: Cannot read properties of undefined (reading 'Actor')
```

**Comment by aaclayton** [comment]
Improved the reported UX here:

![Image](https://user-images.githubusercontent.com/2468703/187500785-14950431-1a9a-4103-9329-105cad05856c.png)
