### ISSUE TITLE
Visual artefacts when moving token through a scene

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7851]
Originally reported by CW_Dutchman#6554 https://discord.com/channels/170995199584108546/956306859491471420/1009458665692074116

**ALL MODULES DISABLED?** (true)  
**OS, Hosting, Browser (if applicable):** Windows 10, Hosting  
**Short Description of bug:** Token vision changes in a weird way when moving (see images)  
**Simple steps to reproduce the bug:** Move player token on grid as shown on imagas  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/185152574-47486c21-9cab-4b7f-b66a-edd2fcc40815.png)

![image](https://user-images.githubusercontent.com/207433/185152617-32ac0248-c55c-44e4-9211-05bdbee2a0d1.png)

![image](https://user-images.githubusercontent.com/207433/185152650-633ee799-6f24-4125-ad99-43a3e574a3c3.png)

![image](https://user-images.githubusercontent.com/207433/185152698-de6dac45-a3ca-444c-99fe-cbbeea771de3.png)

[fvtt-Scene-crabbers-cove.zip](https://github.com/foundryvtt/foundryvtt/files/9363279/fvtt-Scene-crabbers-cove.zip)

**Comment by dev7355608** [comment]
I just experienced an artefact as well. I hope this helps:
![image](https://user-images.githubusercontent.com/31905376/185153146-bf0ad8e4-b6b7-4c1f-bbe3-e4aa76022a17.png)
[fvtt-Scene-polygon-bug-2.zip](https://github.com/foundryvtt/foundryvtt/files/9363298/fvtt-Scene-polygon-bug-2.zip)

**Comment by aaclayton** [comment]
I have a solution to this edge case, although its slightly clumsy. I hope that there might be a better long term solution that is more elegant.
