### ISSUE TITLE
Setup Configuration screen does not account for CLI flag overrides when rendering

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7853]
![](https://media.discordapp.net/attachments/1008807157065592922/1009111678551597166/unknown.png)

Repro steps:
* Launch server via node with `--port=3000`
* Keep config.json default
* Observe the app renders the default rather than the CLI override

**Comment by aaclayton** [comment]
Do I correctly presume that the application is running on `3000` (correctly) but that the setup configuration UI is displaying `30000` (incorrectly)? Or is the app running on the wrong port?

**Comment by aaclayton** [comment]
I was not able to reproduce this on my end. @cswendrowski could you do a bit further investigation and provide adidtional repro steps?

![Image](https://user-images.githubusercontent.com/2468703/187077587-95b598c3-e53d-4d68-a96b-6239d1c08f32.png)
