### ISSUE TITLE
If no roll formula is set in a Rollable table, either use or automatically set the formula the scales generate

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7854]
### User Experience

Currently users can manually press the button, but new users are often surprised they have to set a formula of some kind. Rather than error when none is set, we should fallback to the generated formula to fulfill the intent of rolling the table

**Comment by aaclayton** [comment]
This is a good idea for a future release, but not something we will be doing in V10 in order to limit scope and reach our target deadlines.
