### ISSUE TITLE
Consider changing the "Disable Pixel Resolution Scaling" Setting to "Pixel Resolution Scaling" and invert the checkbox behavior

### ISSUE THREAD

**Issue by eclarke12** [foundryvtt/foundryvtt#7861]
### User Experience

Having a checkbox setting with a negative predicate ("disable") could be considered confusing UI.

![image](https://user-images.githubusercontent.com/42503461/185251486-42e1c2f6-d6a8-461a-8219-e5012186bce6.png)

Instead consider changing this setting to simply "Pixel Resolution Scaling" and then make the checkbox state match whether scaling is on or off.

**Comment by aaclayton** [comment]
I have deleted this setting: <https://github.com/foundryvtt/foundryvtt/issues/7862>
