### ISSUE TITLE
Re-frame the "Pixel Ratio Resolution Scaling" to instead be true by default and optionally disabled for users with high pixel-ratio devices to reduce the performance burden.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7862]
It's not possible to do this properly, so I would rather do nothing at all. 

If a module wishes to restore this function or handle it better, they may do so by hooking into the `canvasConfig` hook and assigning a different `resolution` to the PIXI canvas configuration.

**Comment by unsoluble** [comment]
While I understand the frustration around this, I think without the setting _at all_ it could be argued that if a module is required for playability, core Foundry won't actually support macOS.

Since I don't think that's a result we want, consider leaving the setting itself (inverted, as @eclarke12 suggested in #7861, for clarity and consistency), while yanking all the auto-detect stuff that ultimately didn't work (sorry for kicking all that off!).

**Comment by alaustin0** [comment]
I would also like to add as an anecdote: any Mac laptop with a Retina display (which can date back to 2013 and still run Big Sur) pretty much can't run Foundry at all at native resolution.  A high end, recent Macbook Pro can run okay with a limited framerate, but that is a best case scenario. Removing the option entirely is going to bring a lot of heat from anyone who is using a mid to lower-end Macbook (really anything that's not a Pro) that suddenly can't run Foundry without their laptop catching fire.

**Comment by aaclayton** [comment]
This issue needs to die and never rise again from the grave to haunt my waking hours. I will add a "Pixel Resolution Scaling" setting which is absolutely certain to be inadequate for a number of users and prompt a further wave of feedback on the matter. *sigh*

**Comment by aaclayton** [comment]
@unsoluble @alaustin0 @errational do you find the following wording to be adequate. It is not very terse, I did not know how to adequately communicate this concept in a more concise way.

![Image](https://user-images.githubusercontent.com/2468703/185685648-6192d232-d622-48ab-b012-ab938762970e.png)

**Comment by unsoluble** [comment]
I'd say you could _probably_ get away with leaving the details to the related KB page if you want to keep the text trim here, but it reads well as-is if you're okay with the length.

**Comment by alaustin0** [comment]
Agreed, don't see how you could cut it down much while keeping the same amount of info.

You could potentially cut from "Resolution scaling is..." to "... zoom that is applied." if you don't find it wholly necessary, and leave that bit either in the KB or up to helpers on Discord to provide if people happen to get confused. This would leave the description more related to the exact effects of the setting.

Personal choice, I would say.
