### ISSUE TITLE
Tour UI tooltip replacing tour tooltip if timed incorrectly

### ISSUE THREAD

**Issue by snap01** [foundryvtt/foundryvtt#7865]
### What happened?

If you click on the Start Tour button just before the tooltip displays then div.tour-fadeout is added but is overlaid with the "Start Tour" / "Start Tour from Beginning" tooltip instead of the tour message.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Load a system with a tour (tested with CoC7)
2. Open Tour Management
3. Hover over the Start Tour button
4. Just before the tooltip appears click the button. Unfortunately this may take a few tries as you have the click just before the tooltip appears.

### What core version are you reporting this for?

Version 10 Testing 3 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@cswendrowski I think we really need to consider moving tours off the tooltip API and have it use its own separate HTML element. I think there's too much risk of inter-mixing tour functionality and tooltip functionality and having one sabotage the other. Thoughts?

**Comment by aaclayton** [comment]
This will be handled by #7898
