### ISSUE TITLE
`foundry.utils.getProperty` no longer traverses arrays

### ISSUE THREAD

**Issue by MikauSchekzen** [foundryvtt/foundryvtt#7867]
### What happened?

Since build 278, `foundry.utils.getProperty` no longer traverses arrays, it seems. It did work previously.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open the development console in a browser.
2. Type in `temp1 = { meow: { woof: [ "purr", "bark" ] } };`
3. Type in `foundry.utils.getProperty(temp1, "meow.woof.1");`

You then receive `undefined`. In previous versions, it would have returned `"bark"`.

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
These methods weren't ever intended to be used with Arrays, but I understand that since it worked (coincidentally) people want to keep that functionality. I'll bring it back.
