### ISSUE TITLE
Allow Module-provided translation files to take precedence over System-provided translations. This enables certain system re-skins which would otherwise require an entirely different system or more extensive JS overrides.

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#7870]
### User Experience

Right now, if a System has `[lang].json,` a module that tries to override some strings cannot do so by providing its own `[lang].json`.

For example, there are plenty of conversions/supplements for 5e (_Adventures in the Middle Earth, Redsky, Trudvang Adventures, Stargate, BEOWULF, Doctors & Daleks_) that could be played with small changes to language files without modifying templates (which is technically much harder to do and maintain).

Another issue are outdated language files in some system repos that cannot be fixed without contacting author / making pull requests. That creates unnecessary friction in maintaining up-to-date translations (especially if the system is not actively updated).

Ideally it should be like this:
`worlds/*/[lang.json]` > `modules/*/[lang.json]` > `systems/*/[lang.json]`

**Comment by aaclayton** [comment]
I think this is a reasonable argument. It might be too last-minute for us to make this change before V10 stable, we'll see. It might have to wait for v11.
