### ISSUE TITLE
Allow `GlobalLightSource#object` to be undefined instead of passing in the current `Scene` which is not a type of `PlaceableObject`.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7872]
### Where did you find it, or where does it belong for requests?

V10 API Documentation (https://foundryvtt.com/api/v10/)

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### What is wrong, in your opinion?

```js
class PointSource {
  constructor(object) {

    /**
     * The PlaceableObject which is the origin of this PointSource.
     * @type {PlaceableObject}
     */
    this.object = object;
  }
```

The type of `PointSource#object` is `PlaceableObject`, but the global light sources passes a `Scene`:

```js
    // Create the global light source
    this.globalLightSource = new GlobalLightSource(canvas.scene);
```

**Comment by aaclayton** [comment]
I agree this is a little ugly, but I don't know what is the right change to make. Perhaps in the future we might get rid of `PointSource#object` in favor of `PointSource#document` which could be a `Document` (either `Token`, `Scene`, etc...) but it's not clear that is the best approach either. We are stuck without an obvious change to make in this situation I think.

**Comment by aaclayton** [comment]
Maybe instead I'll just have `GlobalLightSource#object` be `undefined` instead of passing the `Scene` at all. This at least avoids breaking the parent class typing.
