### ISSUE TITLE
Doc - Bad opening tag.

### ISSUE THREAD

**Issue by mathieureygaerts** [foundryvtt/foundryvtt#7879]
https://github.com/foundryvtt/foundryvtt/blob/06e0dc82831e92b7cf13d15ffbe4c6dcbfb836d3/articles/intro-development.html#L153

Bad opening tag causing a visual issue. 
![image](https://user-images.githubusercontent.com/39110258/185750835-d5e6dc47-78b9-4fbe-994c-f5eae348f6b7.png)

**Comment by aaclayton** [comment]
Corrected!
