### ISSUE TITLE
Doc - Duplicated Lines

### ISSUE THREAD

**Issue by mathieureygaerts** [foundryvtt/foundryvtt#7880]
https://github.com/foundryvtt/foundryvtt/blob/06e0dc82831e92b7cf13d15ffbe4c6dcbfb836d3/articles/intro-development.html#L278-L282

Duplicated code at the end of the file.
![image](https://user-images.githubusercontent.com/39110258/185751765-62acfc2d-d9c8-4a35-add7-92957714e58c.png)

**Comment by aaclayton** [comment]
Fixed
