### ISSUE TITLE
`Tile#renderOcclusion` doesn't use the correct roof check

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7884]
### What happened?

Here the check needs to be `this.isRoof`, not `this.document.roof`:
```js
  /**
   * Render the mesh for tile occlusion
   * @param {PIXI.Renderer} renderer
   */
  renderOcclusion(renderer) {
    if ( !this.document.roof || this.document.hidden ) return;
```
Or the roof check could be removed in `renderOcclusion` and instead the loop in `CanvasDepth#createRoofsContainer` iterates only roofs. Maybe a module could make use of `renderOcclusion` for nonroof tiles. `renderOcclusion` doesn't state that it doesn't work for roofs explicitly.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Got it.
