### ISSUE TITLE
The tile texture data was not correctly unset when a tile was switched from overhead to non-overhead.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7885]
### What happened?

This affects `Tile#containsPixel` and `Tile#getPixelAlpha`. After the switch from overhead to nonoverhead, `Tile#containsPixel` still returns results based on `_textureData`, which should have been unassigned.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I realize we can free up a bit of memory by clearing `_textureData`, but am I correct that this doesn't cause any problem, it just represents some excess memory utilization that could be released?

**Comment by dev7355608** [comment]
If `_textureData` isn't unset, `Tile#containsPixel` and `Tile#getPixelAlpha` have inconsistent/undefined behavior in the case of nonoverhead tiles. Though not explicitly documented I assume nonoverhead tiles should always return false if `containsPixel` is called (and `getPixelAlpha` should be -1).
