### ISSUE TITLE
Journal Entry: Inline CSS styles for images and paragraphs being truncated on save of Source HTML

### ISSUE THREAD

**Issue by buttonpushertv** [foundryvtt/foundryvtt#7888]
### What happened?

(NOTE: Using the Fate Core Official System v4.4.09, in case that makes a difference.)

In V10.278, when saving a Journal Entry via the Source HTML page, an entry like this:

`<img style="float: left; padding: 0px 15px 0px 0px; border: 0px;" src="pathToImage">`

Will end up being saved to the Journal Entry with only the first Inline CSS style retained, like this:

`<img style="float: left;" src="pathToImage">`

This is a *new* behavior in V10.278. 

In V10.276, this truncation does not occur and the HTML code will be properly saved.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a Journal Entry
2. Edit Journal Entry
3. Click to edit Source HTML for Entry
4. Paste HTML code: `<img style="float: left; padding: 0px 15px 0px 0px; border: 0px;" src="pathToImage">` (updating _pathToImage_)
5. Save via icon on Source HTML
6. Verify that only first CSS Inline style is saved

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by buttonpushertv** [comment]
One additional piece of information, no log entries are generated indicating an error occurs during save.

**Comment by Fyorl** [comment]
I think I know what this is and I'm fairly confident it affects images (and possibly paragraphs) only.
