### ISSUE TITLE
When installing a dependency, we should not render the `(ver.)` if no version is found

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7892]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1009844138805563492

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, Node  
**Short Description of bug:** Dependency installation failures lie  
**Simple steps to reproduce the bug:** Install module with dependency to a module that doesn't have v10 compatible release.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/185906510-a1353816-a796-458b-9409-c2a55350e291.png)

**Comment by aaclayton** [comment]
I really thought this was fixed in Testing 4, but perhaps still a loose end for dependencies which cannot be installed.
