### ISSUE TITLE
Add default Scene for users who are new to Foundry

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7908]
### User Experience

This scene should serve as a friendly and appealing landing page ready to start interacting with, rather than the current scene-less default.

This scene should only be created for an empty world and for users who have not completed the Welcome to Foundry tour.

**Comment by stwlam** [comment]
Might this create some confusion for new users beginning Foundry with an adventure module (such as the Beginner Box for Pathfinder 2e)?

**Comment by aaclayton** [comment]
Yes, it might. This is one area of concern I want us to address. We are discussing internally.
