### ISSUE TITLE
Replace the two `Transition to...` tool buttons with a `Toggle Darkness` tool

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#7915]
### User Experience

It's very common for new users to be confused by the `Transition to Daylight` button, as it implies that the scene will become lit by "daylight". It could be renamed to `Transition from Darkness` or something, but that's a little confusing too.

Since all the buttons are really doing is transitioning the Darkness level of the scene between one and zero, I propose that we replace the two `Transition` buttons with a single _toggle_, labelled `Toggle Darkness` (using the crescent moon FA icon probably).

**Comment by aaclayton** [comment]
It's not uncommon - at least for my own usage - to use some intermediate level of darkness that is neither zero nor 1. A single toggle would leave ambiguity around which endpoint to animate towards. You could make an assumption like animate towards whichever endpoint is farther from the current value - but I don't agree with the existence of two buttons being harmful or confusing and I think it would be a downgrade of control to reduce them to a single toggle.

**Comment by unsoluble** [comment]
While I can appreciate the argument against the proposed _solution_, could we still entertain another possible fix for the `Daylight` confusion?
