### ISSUE TITLE
Importing a Scene from Compendium incorrectly applies overhead tiles to currently active scene

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7921]
Originally reported by alaustin#0963 https://discord.com/channels/170995199584108546/956306859491471420/1012131720742588467

**ALL MODULES DISABLED?** TRUE  
**OS, Hosting, Browser (if applicable):** Win10, Electron App  
**Short Description of bug:** Default V10 scene inherits overhead tiles as a visual bug when imported scene from a compendium.  
**Simple steps to reproduce the bug:**  
1) Create new world.
2) Activate Atropos Map Pack, import Forest scene.
3) Trees appear. Switching to a new scene and back removes trees.

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/186654571-92ed9e0f-d7c4-401a-b267-26b13548d1ce.png)

**Comment by alaustin0** [comment]
Just wanted to confirm this happens on scenes other than the NUE default.
![Foundry_Virtual_Tabletop_e3bMHGXdY9](https://user-images.githubusercontent.com/97931877/187007018-f0310613-98e2-42da-91d1-a8c250681c0f.jpg)
