### ISSUE TITLE
Dropping a content link into the TinyMCE editor no longer replaces the highlighted text

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7923]
Originally reported by alaustin#0963 https://discord.com/channels/170995199584108546/956306859491471420/1012154461235449876

**ALL MODULES DISABLED?** TRUE  
**OS, Hosting, Browser (if applicable):** Win10, Electron App  
**Short Description of bug:** Highlighting text in TinyMCE and creating a dynamic link to it no longer replaces the highlighted text, but rather inserts the link on cursor.  
**Simple steps to reproduce the bug:** Create an item or a journal with TinyMCE. Add text. Highlight text. Drag something to the text to create a dynamic link.  
**Screenshots and/or console errors:**

[Foundry_Virtual_Tabletop_YV0tbATyHB.webm](https://user-images.githubusercontent.com/207433/186655348-2bb59ac8-ca05-4bf5-a146-b5d38161a8c3.webm)

**Comment by Fyorl** [comment]
For my own benefit, so that I remember: This is confirmed as a regression from previous behaviour in v9.

**Comment by plutoneld** [comment]
> For my own benefit, so that I remember: This is confirmed as a regression from previous behaviour in v9.

Yes, it seems to be a regression. Dor's comment here illustrates the different behaviours https://discord.com/channels/170995199584108546/956307084931112960/1009538377709789225
