### ISSUE TITLE
Improve the compatibility tags that are displayed for Worlds to be more actionable and useful to the user. Improve the compatibility tags assigned to newly created worlds to use the game system's verified compatibility as the initial values.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7926]
Originally reported by stwlam#3718 https://discord.com/channels/170995199584108546/956306859491471420/1012212825483137154

**Short Description of bug:** A freshly-created world shows an odd compatibility warning:

![image](https://user-images.githubusercontent.com/207433/186656639-b4cb5c15-69dc-41e3-8dbe-bf7ecf7f553a.png)

**Comment by aaclayton** [comment]
This might be happening if the game system the world depends on has "unknown" compatibility, but this ideally should not happen since it's not good for new user experience.

**Comment by stwlam** [comment]
Looking over at the system, it simultaneously reports being verified against 10.275 and having "Compatibility Unknown":
![image](https://user-images.githubusercontent.com/106829671/186689230-6343bdec-eeb9-4f92-9190-513314e79265.png)
