### ISSUE TITLE
Stagger the playback of animated tiles and tokens to avoid multiple objects of the same texture being perfectly synchronized

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#793]
**NOTE:**
This is more difficult than it first seemed - all instances of the Token or Tile are referencing the same base texture and the playback state of that video is at the texture level. In order to desynchronize the different Tokens using the texture I would need to make multiple versions of the same base texture which could inflate memory usage, especially for videos.

**Comment by plutoneld** [comment]
This was fixed a while ago, right?
