### ISSUE TITLE
Active Effects Sheet clears currently set keys on submitting changes 

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#7935]
Steps to reproduce:
1. Open an actor or item sheet and create a new active effect which renders the core active effects config sheet
2. define a valid path (such as for DND5e `system.attributes.ac.bonus`) and a valid value (Add, 1)
3. Submit changes
4. Notice no change to value
5. Reopen effect config sheet
6. notice the effects tab is blank and lists no keys

**Comment by arbron** [comment]
This seems to be caused by the `<input name="disabled">` value being confused with the form's `disabled` property, resulting in no form data being processed.

**Comment by tposney** [comment]
Good catch. I was looking at this for a while and that never occurred to me.

**Comment by aaclayton** [comment]
Thanks for the report and for diagnosing the issue @arbron
