### ISSUE TITLE
The `FormDataExtended` class should once-again ignore `button` elements which define a `name` attribute.

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#7938]
### What happened?

Starting in 10.279, a `<button>` element in a form with a `name` parameter will now be processed as a form field within `formData`, resulting in erroneous data potentially being saved that previously wasn't (currently causes issues in dnd5e: https://github.com/foundryvtt/dnd5e/issues/1727).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create `FormApplication` with:

```html
<button type="submit" name="submit" value="1"></button>
```

Submit the form, inspect `formData`.

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by CarlosFdez** [comment]
I was considering removing name="submit" from all the buttons in PF2e (which has the same issue) but it seems even core uses it sometimes. The permission dialog has name="submit" and name="reset" in the bottom buttons.

**Comment by aaclayton** [comment]
Comment from @dev7355608

### What happened?

Buttons end up in the `FormDataExtended` object.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
let form = document.createElement("form");
form.innerHTML = `
    <button type="button" name="foo">Click me</button>
`;
new FormDataExtended(form).object // => {foo: ''}
```

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
> I was considering removing name="submit" from all the buttons in PF2e (which has the same issue) but it seems even core uses it sometimes. The permission dialog has name="submit" and name="reset" in the bottom buttons.
> 
> EDIT: Seems core is removing them, that's good.

I have removed these named buttons from core... BUT, I will also plan to make a change which suppresses buttons from `FormDataExtended` processing regardless. Up to you whether you would prefer to ditch the names or just wait for the core fix.
