### ISSUE TITLE
getDocuments() queries should use system instead of data for older compendiums

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#7944]
### User Experience

There is currently no easy way to migrate a module compendium (from what I've seen), so allowing v10 queries on v9 compendiums would help in smoothing that difference over.

After editing the manifest to allow the rage of elements playtests to run on v10 (the id property name enforcement broke a lot) this is what happens when you try to query it.

![image](https://user-images.githubusercontent.com/1286721/186830466-139f5177-6287-4aa7-942f-5f0dd1cf33fc.png)

This was run on V10 Testing 5.

**Comment by aaclayton** [comment]
@CarlosFdez to migrate a module compendium (which is the correct step to take to solve this problem) you should do:
```js
const pack = game.packs.get("pf2e-playtest-data.rage-of-elements-playtest-class-feats");
await pack.migrate();
```
This will convert the compendium content to the latest data model and your downstream queries should work as expected. Let me know if you encounter any trouble with this solution.

**Comment by CarlosFdez** [comment]
So these aren't my own compendiums, and its more that the system will encounter issues when encountering old compendiums. That said, this does mean we can at the very least give advice for third party content,
