### ISSUE TITLE
Document property deletions using (-=key) fails to properly remove the property in the case of embedded documents in an unlinked Token actor.

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#7945]
### What happened?

Some code that deletes properties is instead adding them.

I did a *tiny* amount of additional testing, and I don't *think* it happens to world actors or linked actors. Only unlinked ones.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

To test this, I opened a 5e world, dragged in a goblin to the scene, and ran this code with these results.

![image](https://user-images.githubusercontent.com/1286721/186857496-a25f6b1d-a463-4b75-a7bf-e55ce42f5d69.png)

When I linked a goblin before dragging it in, it didn't happen, so I think its just unlinked tokens doing weird things again.

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by CarlosFdez** [comment]
This bug still exists in 10.284 with the same reproduction steps. If it makes it easier, I'll copy paste what I put in the console

```js
await canvas.scene.tokens.getName("Goblin").actor.items.getName("Scimitar").update({ "system.activation.-=condition": null });
canvas.scene.tokens.getName("Goblin").actor.items.getName("Scimitar").system.activation;
```

For PF2e this causes certain item updates to brick the actor. Currently its strike edits that cause bricking as far as I know, but I suspect spell damage might be the same issue.

**Comment by aaclayton** [comment]
@CarlosFdez can you work around this issue by instead setting `system.activation.condition` to `null` instead of needing to delete the key entirely? I think that would be a better data model anyways since you would be affirmatively saying "there is no activation condition" rather than implicitly handling it based on the presence or absence of a key. That would also avoid any issues with deletion keys which have a track record of being fiddly.

We'll try and fix the bug all the same, but my strong advice for you would be to change your data model assumptions to set an explicit `null` rather than assigning/deleting.

**Comment by CarlosFdez** [comment]
This is an example in 5e since its easier for you guys most of the time to diagnose issues that occur in 5e. PF2e has more moving parts and thus its better to isolate issues as much as possible.

The actual property we are trying to edit is system.damageRolls, which is a record of id -> damage roll entry. So its actually choking on something like `"system.damageRolls.-={random16chars}: null`. It could alternatively be an array, but arrays are traditionally finicky for nested updates.

Best to wait I guess. But shark apparently has an idea.

**Comment by CarlosFdez** [comment]
I did some investigation, and the culprit seems to be TokenDocument's _preUpdateTokenActor() function. The update case is missing { performDeletions } on the mergeObject()

**Comment by aaclayton** [comment]
Fix will be included in the next core update. Thanks @CarlosFdez for investigating the problem, sorry for the inconvenience this causes you.

I would reiterate my guidance, however, to perhaps not rely so heavily on objects with flexible schema (arbitrary keys/values) and instead move to something that can be more rigorously structured. 

An array of `damageRolls` would be a superior choice, and array management is better in v10 than it was historically. That being said, we will do our best to ensure that deleting keys from objects works and continues to work.

**Comment by CarlosFdez** [comment]
I think once arrays get better we'll start moving to them directly for list structures like damage rolls specifically. Once `system.damageRolls.0.whatever` in form data doesn't lead to a numerically key'd object we can start using arrays more common place. However, we do have more complex non-sequenced data as pseudo-subcollections in places that need to be referenced by an id (spell variants are system data partials in a spell object for example that are merged into the main one to override the spell for example) and an array is a poor fitting choice for those structures.

But even with that changed, it wouldn't really help. We also use -= in preUpdate() to reduce data size, and also in migrations to change from one schema to another. We need to aggressively delete objects and defaults to keep pf2e structure down. The reason this has become a blocker was never about damageRolls, but about migrations. We were scared someone with old data updating to V10 would brick their scenes once all the migrations ran. Hopefully with schema changes we'll no longer need to explicitly delete optional properties, but schema changes will still be a problem.

Thanks for confirming. I'd personally be fine with a monkey patch in the meantime. But I think stwlam wanted confirmation from you. Which it seems this is.
