### ISSUE TITLE
background-size property significantly degrades quality of scene thumbnails 

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#7954]
### What happened?

With `background-size` property enabled - extremely pixelated and blurry

![Foundry_Virtual_Tabletop_GdxsVnHkaK](https://user-images.githubusercontent.com/138311/187008961-9277d80a-82af-4d97-a226-2bd65c5d00d1.png)

With `background-size` property removed - not ideal but much crisper and cleaner

![Foundry_Virtual_Tabletop_OoXVFG5hEV](https://user-images.githubusercontent.com/138311/187008960-ef1c87cd-f9c5-43eb-8071-86842e2046cc.png)

(source images in those examples are 4k)

Note, that even `background-size: 100% auto;` would for some reason produce worse results than no css property at all.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Good call-out, I agree the background size property is unnecessary here, especially when it noticeably degrades the visual quality of the thumbnail.
