### ISSUE TITLE
Render hidden templates with 50% transparency

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7959]
### User Experience

Unless on the template layer there's no way to tell whether a template is hidden. Hidden templates including grid highlight should be rendered with 50% transparency just like hidden tokens/tiles/drawings.

**Comment by aaclayton** [comment]
This is a good idea to consider for a future release, but not something we will be doing in V10 in order to limit scope and reach our target deadlines.

**Comment by dev7355608** [comment]
Bumping for V11 consideration. Suggested change in `MeasuredTemplate.#refreshState`:
```js
const alpha = isHidden ? 0.5 : 1;
this.template.alpha = alpha;
this.ruler.alpha = alpha;
canvas.grid.getHighlightLayer(this.highlightId).alpha = alpha;
```
