### ISSUE TITLE
With route prefix font awesome 5 backward compatibility URLS breaks. 

### ISSUE THREAD

**Issue by typhonrt** [foundryvtt/foundryvtt#7961]
### What happened?

Font awesome 5 backward compatibility links are absolute, so a route prefix will break them. 

Expected is that they load correctly. 

Picts for console: 
![image](https://user-images.githubusercontent.com/311473/187058212-3322f367-88c0-4957-a960-bc92dc272bd4.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Enable a route prefix then notice that the font awesome 5 backward compatible URLs don't resolve. 

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Relevant log output

```shell
GET http://192.168.1.114:30001/fonts/fontawesome/webfonts/fa-regular-400.woff2 net::ERR_ABORTED 404 (Not Found) style.css:1          

GET http://192.168.1.114:30001/fonts/fontawesome/webfonts/fa-regular-400.ttf net::ERR_ABORTED 404 (Not Found) style.css:1
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by typhonrt** [comment]
Related to initial support added here: #6893

The fix is simple... Just make them relative prepending the URLS with `..` in the styles.css file:

```
/* ----------------------------------------- */
/* Font Awesome Free Compatibility
/* ----------------------------------------- */
@font-face {
  font-family: "Font Awesome 5 Free";
  font-display: block;
  font-weight: 900;
  src: url(../fonts/fontawesome/webfonts/fa-solid-900.woff2) format("woff2"), url(../fonts/fontawesome/webfonts/fa-solid-900.ttf) format("truetype");
}
@font-face {
  font-family: "Font Awesome 5 Free";
  font-display: block;
  font-weight: 400;
  src: url(../fonts/fontawesome/webfonts/fa-regular-400.woff2) format("woff2"), url(../fonts/fontawesome/webfonts/fa-regular-400.ttf) format("truetype");
}
@font-face {
  font-family: "Font Awesome 5 Free";
  font-display: block;
  font-weight: 300;
  src: url(../fonts/fontawesome/webfonts/fa-light-300.woff2) format("woff2"), url(../fonts/fontawesome/webfonts/fa-light-300.ttf) format("truetype");
}

```

The reference fonts defined just above this section are relative with a leading `..`.

**Comment by aaclayton** [comment]
Thanks for identifying the solution for this.
