### ISSUE TITLE
Recently added feature: #7807 has several unintended regressions for macro hotbar drops.

### ISSUE THREAD

**Issue by typhonrt** [foundryvtt/foundryvtt#7962]
### What happened?

The recently added macro duplication of creating a secondary "display" macro for a document drop on the macro hotbar has unintended behavior and is a regression IMHO. 

The intent of #7807 is to create a "display" macro for a non-macro item drop, but there are several issues with the current implementation. 

I will add image / GIFs of behavior in v9 and latest v10 testing 5 in first comment. This testing is w/ latest DnD5e system on v9 & v10. Working with an item / weapon document from the Items SRD compendium.

First in v9 when dragging an item document from a compendium to the macro hot bar is rejected. (See image 1)

- In v10 this will create two macros when dropping documents from a compendium. One for displaying the item from the compendium and also an unused / unlinked macro to activate the item which is not even owned by the player. (See image 2)

- In v10 dropping an item from the player sheet onto the hotbar creates both a display & activation macro, but very undesirable is that the assigned hotbar macro is the display macro. It is definitely undesirable in this case to create a display macro for an item dropped from the player sheet.

-------------

While there is convenience functionality to potentially unlock for 3rd parties that ship compendiums of journal entries and what not I suggest backing out this feature until it can be better tested in a wider array of scenarios. Perhaps figuring out a way for documents in a compendium to have a flag or some other mechanism to enable this behavior otherwise the behavior should be reverted to v9 functionality.

Another big issue for GM users is that every single macro created for any user is visible in the macro directory, so this proliferation of additional macros really pollutes the the GM users ability to navigate the macro directory. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Open the macro directory and drop items in from a compendium and compare against v9 and v10

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Relevant log output

```shell
No specific relevant logging output. 

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by typhonrt** [comment]
Behavior on v9 from normal player when attempting to drop an item / weapon from the Items SRD compendium on dnd5e system:
![macro-hotbar-v9](https://user-images.githubusercontent.com/311473/187066872-f5635f3f-04c8-49ff-a128-20c13503fb76.gif)

-------

Behavior on v10 in same scenario shows the dual macro creation from dropping the same item / weapon from the Items SRD compendium on dnd5e (alpha 3):
![hotbar-v10](https://user-images.githubusercontent.com/311473/187066906-2a72a750-6f76-4a73-bfbd-f2f698dcc6a5.gif)

**Comment by typhonrt** [comment]
Undesirable side effect / behavior of this new feature when dragging a macro from the FQL macro compendium on v10 wherre a duplicate of the macro is created even though a macro already is created for the user in the `hotbarDrop` hook:

![FQL-macrodrop-v10](https://user-images.githubusercontent.com/311473/187067005-fb4e2a7c-1192-48d7-848c-c8943d01980e.gif)

**Comment by aaclayton** [comment]
This behavior is due to a 5e system bug, now fixed. https://github.com/foundryvtt/dnd5e/pull/1731
