### ISSUE TITLE
Creating a ContentLink of an owned item creates a broken link

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7972]
When dropping an OwnedItem into a TextEditor field of the same sheet a broken @UUID is created, which is missing the "owner/parent document" part. This worked in testing 4. When dropping into TextEditor fields of other sheets or the chat it works correct.

@UUID[.Item.DbqmTAu5IGC0Np5Y]{Sichere Klinge (Fechter)}

**Comment by aaclayton** [comment]
This may be working as intended, if this is in the biography tab of an Actor sheet. This is a relative link to the items collection of the actor. We should check with @Fyorl about what is intended in this case.

**Comment by ghost91-** [comment]
When this was initially reported on discord, I thought the same thing. But I asked the user to confirm that the link is actually broken (I.e., clicking it doesn’t work), and they did: https://discord.com/channels/170995199584108546/956307084931112960/1012358756731998288
