### ISSUE TITLE
ProseMirror discards links if they do not have a href

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7973]
From: https://discord.com/channels/170995199584108546/956306859491471420/1012390283536781362

Edit source in ProseMirror, add link `<a data-item-id...>` that has no href, when saving it is converted to `<p>....</p>`.

**Comment by aaclayton** [comment]
It's possible that @Fyorl already fixed this, but we do intend to make the `href` optional since we don't always include them for our own content links. Need to confirm whether this has been done yet or not.
