### ISSUE TITLE
Rolls with curly bracket roll groups and Math methods like `floor`, `ceil` or `round` fail

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7977]
From https://discord.com/channels/170995199584108546/956306859491471420/1013061417219403796

Make a roll using a Math keyword in a curly brackets roll group, the roll will fail. E.g `/r {floor(11/2)}`

![](https://cdn.discordapp.com/attachments/956306859491471420/1013061416271495308/unknown.png)

**Comment by aaclayton** [comment]
This is a duplicate of https://github.com/foundryvtt/foundryvtt/issues/5327
