### ISSUE TITLE
PDF Journal Entry won't open

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7980]
From https://discord.com/channels/170995199584108546/956306859491471420/1013401162571067423

Create a PDF Journal Entry and open it.

![](https://media.discordapp.net/attachments/956306859491471420/1013401174034087997/unknown.png)

**Comment by aaclayton** [comment]
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7927
