### ISSUE TITLE
Token Wildcards not working

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7981]
From: https://discord.com/channels/170995199584108546/956306859491471420/1013494510011035750

Telling a token prototype to randomize wildcard images breaks the token, replacing it with a default token and generating an "Error retrieving wildcard tokens" message, even if the image location isn't a wildcard path
Steps to reproduce: Tell any token prototype to randomize wildcard images

I'm not sure what this console log indicates but it applies to any token, even ones I make from scratch 

![](https://media.discordapp.net/attachments/956306859491471420/1013494509268647977/unknown.png)

**Comment by aaclayton** [comment]
Closed as nonrepro.
