### ISSUE TITLE
Occlusion of tiles with transparent texture is not working correctly

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7985]
### What happened?

Overhead roof tile with a gradient texture. The light source is at elevation 0.
![occlusionbug](https://user-images.githubusercontent.com/31905376/187270363-e34a78fb-872c-4f4f-8718-30fd11eef1ed.gif)

The reason for this is that the elevation is multiplied with the alpha values of the texture in the `OcclusionSamplerShader`. The alpha threshold (0.75) needs to be applied to the alpha first: `oAlpha` and `rAlpha` must be 0 or 1.

```diff
 // OcclusionSamplerShader#batchFragmentShader
- float rAlpha = color.a;
+ float rAlpha = 1.0 - step(color.a, 0.75); // 1.0 if >0.75 else 0.0 (`Tile#containsPixel`)
``` 
The alpha threshold should probably not be hardcoded.
```diff
 // OcclusionSamplerShader#batchFragmentShader
- gl_FragColor = vec4(tint, vColor.a * smoothstep(0.6, 1.0, rAlpha) * oAlpha);
+ gl_FragColor = vec4(tint, vColor.a * rAlpha * oAlpha);
```
```diff
 // OcclusionSamplerShader#fragmentShader
- float rAlpha = texture2D(sampler, vUvs).a;
+ float rAlpha = 1.0 - step(texture2D(sampler, vUvs).a, 0.75);
```

It doesn't look like the nonbatched version would compile:
```diff
- vec4 oTex = texture2D(occlusionTexture[0], vSamplerUvs);
+ vec4 oTex = texture2D(occlusionTexture, vSamplerUvs);
```
Also it seems a different value is written to `gl_FragColor.g` compared to the batched version.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Testing5 (build 279)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I don't know whether this can (or should) be addressed in time for V10 stable, but I'm assigning it to @Feu-Secret to take a look at and decide.

**Comment by Feu-Secret** [comment]
We should address this issue. This is a good catch.
