### ISSUE TITLE
Owned Items' `prepareData` is called twice if Actor or Item is updated

### ISSUE THREAD

**Issue by moo-man** [foundryvtt/foundryvtt#7987]
### What happened?

If an Owned Item or its owning Actor receives an update, the item's `prepareData` function runs twice before resetting its values.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I reproduced this simply by breakpointing `prepareData` for the Item and Actor. Here you can see the stack trace

I'm not sure if this is helpful but here are the stack traces

First call to Item's `prepareData`
![image](https://user-images.githubusercontent.com/28637157/187276853-ffa4d8b8-49b3-4ca8-b23d-825ddae780ff.png)

Second Call
![image](https://user-images.githubusercontent.com/28637157/187276909-84238605-9e1d-4a2f-9687-481464b2c56d.png)

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
Isn't that just an item's data preparation?

**Comment by aaclayton** [comment]
He is correct, it does happen twice currently, the parent document initialization calls initialization for all embedded documents which is called again a second time in the core `prepareEmbeddedDocuments`. I need to ensure that one of these can be safely removed without surprising side effects.

An important consideration though is to make sure that your `prepareData` operations are idempotent. Ideally for efficiency we should ensure that preparation only happens once - but its also important that there are no negative side effects if `prepareData` is called multiple times. So make sure your prepareData operations are idempotent and there shouldn't be any "bugs" related to this problem, but there is an opportunity to improve efficiency by removing a redundant preparation in some cases.

Hopefully this makes sense?

**Comment by aaclayton** [comment]
I have some ideas about ways to improve this in the future, but I don't feel confident about making a change the night before V10 stable release (probably the right call) so this will have to be a future enhancement. In the meantime I suggest making sure your data preparation workflows are idempotent.

**Comment by ghost91-** [comment]
What is the desired outcome here? Which of the calls to prepareData of embedded documents should be removed? I am asking, because I currently rely on it being called by the parent's prepareData, because it allows me to access properties the have already been prepared on the parent during the prepareData of the embedded document. If the prepareData of embedded documents were only to be called before/independently of the parent's, that would not be possible anymore.

**Comment by aaclayton** [comment]
I agree that it's necessary for child data preparation to occur after parent data preparation - as there are numerous use cases for child data depending on parent attributes.

That being said, there are also use cases for parent data depending on embedded documents, like an Actor armor class depending on the armor Item that character is wearing. Ultimately the desired workflow would be:

- Begin parent data preparation
- Embedded child data preparation
- Finalize parent data preparation

**Comment by ghost91-** [comment]
Thanks for the information, that’s very good to know.

What you described is exactly the workflow I am using:
* `prepareBaseData` in the actor prepares any data that doesn’t depend on embedded documents
* embedded items are prepared (called by `prepareEmbeddedDocuments`
* `prepareDerivedData` prepares data on the actor that can also depend on embedded documents.
