### ISSUE TITLE
FormDataExtended should process radio input fields as undefined if none of the checkboxes in the radio node list are checked.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7993]

**Comment by FloRad** [comment]
For reference, Foundry v9 delivers `NaN` for a set of radio checkboxes without a selection (and if the data type is set to `Number`)

**Comment by aaclayton** [comment]
That seems like the correct behavior to me... it's a `radio` so it can only have one value, and its a `data-dtype` of `Number`. It might, of course, be slightly better if it returned `null`, but this seems close to the correct behavior.

**Comment by aaclayton** [comment]
Okay, I can have it return `undefined` which is probably the best behavior in this case.
