### ISSUE TITLE
Add `mode`/`target` parameters to `DetectionMode#_testLOS`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7994]
### User Experience

Visibility might be limited by something other than walls, for example magical darkness or fog. Additional checks in `_testLOS` may require the range of the detection mode.

The parameter order would need to be different from `_testRange` in order to make this a nonbreaking change:
```js
_testLOS(visionSource, test, mode, target)
```

**Comment by aaclayton** [comment]
I will make the signature of all methods `(visionSource, mode, target, test)` in the same order. Please plan to adjust your `_testLOS` signature on your end to accommodate that change in parameter order.
