### ISSUE TITLE
Synthetic token flag persistence is broken for false(y?) values

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/foundryvtt#7997]
### What happened?

See the repro steps below.

In essence: I have an NPC actor (unlinked actor data), and I set a flag (e.g. Diamond Soul) to `true` on this actor. I then create a token from this actor. I then edit this token, setting the token's Diamond Soul to `false`. I expect the source actor to have Diamond Soul enabled, and my token actor to have Diamond Soul disabled. This works as expected, until I refresh, at which point the token's Diamond Soul flag "resets" to `true`.

My uneducated guess:

- Data for a token actor in the scene is stored as a diff against the source actor. As part of this process, values which are `false` in the token actor's flags but `true` in the source actor's flags are erroneously discarded
- When reconstructing the token actor data on reload, the token actor inherits the "incorrect" `true` flags from the source actor

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

```js
// Note: assumes `dnd5e` system
(async () => {
    const scene = await Scene.create({name: "Test Scene", active: true, padding: 0}, {renderSheet: false})
    await scene.activate()

    const npc = await Actor.create({type: "npc", name: "Test NPC"})
    await npc.setFlag("dnd5e", "diamondSoul", true)
    await npc.sheet.render(true)

    const tokenName = `${npc.name} (TOKEN)`
    const td = await npc.getTokenDocument({name: tokenName, x: scene.width / 2, y: scene.height / 2})
    const token = await td.constructor.create(td, {parent: canvas.scene})

    await token.actor.update({name: tokenName})
    await token.actor.unsetFlag("dnd5e", "diamondSoul")
    token.actor.sheet.render(true)
    
    // observe the "prototype" actor has all saving throws ticked (as expected)
    // observe the token actor has no saving throws ticked (as expected)
    
    // refresh

    // observe the "prototype" actor has all saving throws ticked (as expected)
    // observe the token actor has all saving throws ticked (NOT as expected)
})()
```

### What core version are you reporting this for?

Version 10 Testing 5 (build 279); Version 9 (build 269)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Possibly related to https://github.com/foundryvtt/foundryvtt/issues/7945

**Comment by aaclayton** [comment]
No remaining issues with your repro case, presumed fixed by the linked issue.

**Comment by TheGiddyLimit** [comment]
Is this part of the same family of bug @aaclayton?

[effects.webm](https://user-images.githubusercontent.com/25264887/187480616-c7e1fca7-638d-4677-be20-ce4f28a5091c.webm)

**Comment by aaclayton** [comment]
Different issue, but also fixed.

**Comment by TheGiddyLimit** [comment]
@aaclayton I'm seeing the original issue on v10.284 (same repro script as above):

[flags-reload.webm](https://user-images.githubusercontent.com/25264887/188914990-01dcc94c-3e19-4d2b-804c-38928a88c876.webm)

(Apologies for the clipped video, barely ducking under Github's 10 MB limit)
