### ISSUE TITLE
Detection Mode range input field doesn't have a step size and the schema doesn't define the minimum value 0 for the range

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7998]
### What happened?

Neither the input element or the schema defines a step size of the range of a Detection Mode. The Vision Range input field has a 0.1 step size and the Vision Range in the schema a 0.01 step size. Also the Detection Mode schema doesn't define the range `min` to be 0.

```js
// sight.range
new NumberField({required: true, min: 0, step: 0.01}),

// detectionModes[i].range
new NumberField({required: true, initial: 0})

// LightData
new NumberField({required: true, initial: 0, min: 0, step: 0.01, label: "LIGHT.Bright"}),
```

```handlebars
{{numberInput object.sight.range name="sight.range" placeholder=gridUnits min="0" step="0.1"}}

<input name="detectionModes.{{i}}.range" type="number" value="{{mode.range}}" min="0" step="any"/>

<input type="number" name="config.bright" placeholder="{{gridUnits}}" value="{{data.config.bright}}" step="any"/>
```

The Light Radius inputs accept any steps and the schema rounds to a 0.01 step size. So maybe the vision/detection range input fields shouldn't have a step size either?

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Assigning to @Feu-Secret
