### ISSUE TITLE
Allow vision into an area covered by a roof tile if that roof uses vision-based occlusion

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8003]
### What happened?

Walls inside a roof have a special treatment that collides with vision based occlusion. We need a way to make interior walls compatible with this kind of occlusion. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

-

### What core version are you reporting this for?

Version 10 Stable

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is important for us to address, but it came in at the last minute. It may not make the V10 release.

**Comment by aaclayton** [comment]
Found a simple solution that I feel confident enough to go with.
