### ISSUE TITLE
Files referenced in world.json broken in 10.282 (including compendium packs, world scripts, and world CSS styles)

### ISSUE THREAD

**Issue by mxzf** [foundryvtt/foundryvtt#8017]
### What happened?

The styles key in world.json seems to be broken in 10.282.  Rather than trying to load a CSS file from the relative location inside the world folder (as 10.279 did) it's trying to load it from the site root (and thus unable to find the file).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Configure the `styles` in a `world.json` to point at a local stylesheet file, see it attempt to load from the site root instead of the world folder.  

### What core version are you reporting this for?

Version 10 Stable (build 10.282)

### Relevant log output

```shell
Refused to apply style from 'http://localhost:30003/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mxzf** [comment]
To add to this, it's also impacting `esmodules` world scripts, and likely `scripts` too, I would expect.

**Comment by mxzf** [comment]
This seems like it might be hitting compendiums too.  Making a new compendium in a world is ending up making a `packs/` folder directly in my user data and storing the pack there instead of using the world's folder.

**Comment by arcanistzed** [comment]
Packs created on previous versions of v10 aren't visible anymore.

**Comment by aaclayton** [comment]
Fix for this is ready, will be released tomorrow.
