### ISSUE TITLE
Fix an issue which caused Token actor overrides to be discarded instead of used, particularly noticeable with regards to active effects on unlinked tokens.

### ISSUE THREAD

**Issue by tposney** [foundryvtt/foundryvtt#8020]
### What happened?

I happened to be using dnd5e, but am not sure that is relevant.

Open an unlinked token (from the canvas) add an active effect (e.g. system.abilities.str.value ADD 10), observe that the strength is updated correctly. 

Returning to setup and reentering the world I would expect the effect to still be present but it is not there.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Select an unlinked token from the canvas and edit it.
- Add an active effect (e.g system.abilities.str.value ADD 10) and observe that the strength is updated.
- Return to setup.
- Renter the world.
- Observe that the effect is no longer present on the linked token.

(I also checked the world actor and note that it is missing there as well - as would be expected).
If the effect is created via an item's passive effects the token is correct on reload.
If I then add an extra effect by hand both the item and the extra effect are missing from the token on reload.

It appears that token.document.actorData is incorrect with the priority of the change being undefined. I think that causes a problem on load. 

As an aside I discovered a similar problem in DAE when editing effects but in my case this threw a model validation error so have patched DAE to ensure priority is never undefined on saving effects and that tint is not a blank string. If I enable DAE and perform the same steps both effects and items are correctly displayed on reload, so suspect the problem is priority being undefined.

### What core version are you reporting this for?

Version 10 Stable (and possibly earlier)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by tposney** [comment]
I did some further playing.  
If I manually update token.document.actorData to set the priority to a number (instead of undefined) and change tint from "" to null, the effect is correctly displayed on reload.

**Comment by aaclayton** [comment]
I was unable to reproduce this using an unlinked token in the latest 5e version with no modules enabled: 

![Image](https://user-images.githubusercontent.com/2468703/187989126-96f855cb-62a4-406e-acf0-568be146adf1.png)

**Comment by tposney** [comment]
Sorry to keep flogging this issue.

I've had someone else test for me as well can they can repro the problem using 10.283 and dnd 2.0.1
```
Also, can you do me a favour. In a v10 world with no modules active choose an unlinked token and create an active effect on it with any valid change you like. Close the token then reload the world and see if the effect is still present on the token?
thatlonelybugbear — Today at 11:19
WOW v10.283 and dnd5e 2.0.1. The effect disappears
```
To try and be clear, the issue only occurs after the world is reloaded.

Rather than checking _token.actor.effect can you check _token.document.actorData

**Comment by krbz999** [comment]
On 10.284 and dnd5e 2.0.2, this also occurs. An effect that has never been opened or changed works fine.
As soon as you open one - it's still fine, just don't hit Save, or all effects get deleted on reload.

**Comment by ThatOneBaguette** [comment]
Are you having similar issues with vision and actor scale ? My modifications to those parameters are not saved when I reload Foundry.
