### ISSUE TITLE
`TokenConfig` updating the source of the document on close overrides changes to the token that happened after the config was opened

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8022]
### What happened?

`TokenConfig` updates the source with the original data of the token when the config was opened.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open the token config.
2. Move the token.
3. Close the config without saving.

Token resets to the position before the config was opened.

4. Reload.

Token is at the position it was moved to last. 

### What core version are you reporting this for?

Version 10 Stable 1 (build 282)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Confirmed, same issue. Will merge the comment in.

**Comment by dev7355608** [comment]
Pre v10 closing the token config without saving did not have any negative effects if I recall correctly. Only saving as described in the other issue was (and still is) a problem. `TokenConfig#_previewChanges` even resets flags that haven't been injected into the form.
