### ISSUE TITLE
Top & bottom docked AV panel does not correctly reclaim space when hidden

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8026]
Originally reported by Dick K#6417 https://discord.com/channels/170995199584108546/956306859491471420/1014618979022688336

**OS, Hosting, Browser (if applicable):** Win10, Self-Hosting, Chrome  
**Short Description of bug:** A/V Docking Positions Top & Bottom Fail to Reposition Other Controls When A/V  Window Undocked  
**Simple steps to reproduce the bug:** (V10 Stable) Open scene using Foundry A/V with doc position specified as Top or Bottom. Undock A/V window. Observe that dock background is removed but screen controls, scene buttons, macro bar, are left in position. Bug does not occur with Left & Right dock positions.

**Comment by Dick-K** [comment]
Thanks!
