### ISSUE TITLE
Clicking the 'x' button in the search filter does not reset the filter

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8028]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/956306859491471420/1014629026331111485

**Short Description of bug:** Clicking the `x` button in the search filter input doesn't reset the filter  
**Simple steps to reproduce the bug:** Go to module screen on the Setup page, enter something into the search field, click the `x` and notice that the filter isn't reset

**Comment by arcanistzed** [comment]
I am still having this issue on 10.284

**Comment by aaclayton** [comment]
> I am still having this issue on 10.284

What browser and version? Have you tried other browsers to confirm? are you sure it's not caching?

**Comment by arcanistzed** [comment]
All good now. It must have been caching
