### ISSUE TITLE
Packages which designate generational compatibility are still reported as compatibility risk

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8035]
ALL MODULES DISABLED? TRUE (N/A)
OS, Hosting, Browser (if applicable): Win10, Electron
Short Description of bug: Modules with proper compatibility still show a Compatibility Unknown warning.
Simple steps to reproduce the bug:
1) Install DDB Importer module (random one I can repro)
2) Close and relaunch the Foundry app until it shows a compat warning.
3) Uninstall/Reinstall module to make compat warning go away
4) Relaunch again (might take more than one?) to reintroduce warning
Screenshots and/or console errors: 

![image](https://user-images.githubusercontent.com/2468703/187935752-b57c5b63-089c-4fdd-aae4-7ea5cddef094.png)

**Comment by alexdiste** [comment]
Seems also that withou specifying "verified" there is always a warning and it report unknown compatibility evenif max and min are set up

**Comment by aaclayton** [comment]
Presumed fixed probably by the same issue which caused https://github.com/foundryvtt/foundryvtt/issues/8017 as I can not reproduce this on our current dev branch.
