### ISSUE TITLE
Localize the Document names in the Create Compendium dialog dropdown.

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#8036]
### What happened?

The following keys are *used* in the Create Compendium window but do not exist in `en.json`

```json
{
  "Actor": "Actor",
  "Adventure": "Adventure",
  "Cards": "Cards",
  "Item": "Item",
  "JournalEntry": "Journal Entry",
  "Macro": "Macro",
  "Playlist": "Playlist",
  "RollTable": "Rollable Table",
  "Scene": "Scene"
}
```

![Foundry_Virtual_Tabletop_85bUD7B2ws](https://user-images.githubusercontent.com/138311/187954012-e5f521fa-05d2-45c2-9f33-f8036b7751d8.png)

Also, it would be nice to add those strings to Compendium categories headers here:

![image](https://user-images.githubusercontent.com/138311/187953942-7236ceeb-635d-4eec-8665-5cea91566fa2.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

N/A

### What core version are you reporting this for?

Version 10 (Build 283)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by sladecraven** [comment]
Please re-open : this issue has a blocking side effect !
It is not possible anymore to create compendiums in localized Foundry installation !

**Comment by Feu-Secret** [comment]
Side effect confirmed for localized Foundry installations.

**Comment by rwanoux** [comment]
i think it comes from _onCreateCompendium() methods of CompendiumDirectory class.
this method takes directly the translated string of the class label as a variable.
[foundry.js  line 74447/compendiumDirectory Class ](https://cdn.discordapp.com/attachments/1014861144537702400/1015214068455456818/Screenshot_7.png)

**Comment by rwanoux** [comment]
modifications possibles : 
 ```
async _onCreateCompendium(event) {
    event.preventDefault();
    const types = CONST.COMPENDIUM_DOCUMENT_TYPES.map(documentName => {
      return { //modifying types variable
        label: game.i18n.localize(getDocumentClass(documentName).metadata.label),
        value: documentName
      }
    });
    //no changes in rest of method
    
    
```

then the template  resources\app\templates\sidebar\compendium-create.html should become :
```
<form id="compendium-create">
    <p>{{localize "COMPENDIUM.CreateHint"}}</p>

    <div class="form-group">
        <label>{{localize "Name"}}</label>
        <input type="text" name="label" placeholder="{{localize
            'COMPENDIUM.Name'}}" autofocus>
    </div>

    <div class="form-group">
        <label>{{localize "COMPENDIUM.Type"}}</label>
        <select name="type">
            {{#each types}}
<!-- ******************modified in options**************************************************** -->
            <option value="{{this.value}}">{{localize this.label}}</option>
<!-- ******************modified in options**************************************************** -->

            {{/each}}
        </select>
        <p class="notes">{{localize "COMPENDIUM.TypeHint"}}</p>
    </div>
</form>


```
