### ISSUE TITLE
Tokens with higher `sort` values are not mouse-interactable while sharing space with larger tokens 

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8042]
### What happened?

Larger tokens with dimensions that overlap smaller tokens on the canvas cut off mouse-interactability with the smaller tokens. To regain mouse control, one must move the larger token out of the way or press tab. This is the case even if a smaller token has a higher `sort` value.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create two tokens: one that is 1x1 grid spaces, and another that is 2x2.
2. Update the smaller token to have a `sort` value of 2.
3. Move the smaller token into the larger's space. Mouse-hovering it will highlight the larger token, and it is no longer mouse-selectable.

### What core version are you reporting this for?

Version 10.283

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Seems likely related to #8249 with certain tokens swallowing click events not meant for them.
