### ISSUE TITLE
Render Token border on top if hovered or highlighted

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8043]
### What happened?

Now that token borders are rendered underneath the main token image texture, giving a token even a slightly higher scale can cover the border in its entirety. At 1.5 scale ratio:

![image](https://user-images.githubusercontent.com/106829671/187990885-30543864-f11c-467f-8ec1-dec882465203.png)
![image](https://user-images.githubusercontent.com/106829671/187990918-f37731d8-7722-44bb-a6b0-ee74007db028.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Increase a token's scale by some amount.
2. Select the token.

### What core version are you reporting this for?

Version 10.283

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
While I agree that this is a factual description of what happens - I fail to see why this is a bug or anything other than the completely expected outcome, or what we would do differently?

**Comment by stwlam** [comment]
My thought was that an aesthetic feature like scale shouldn't obscure part of the user interface--the visual indication that a token is controlled or highlighted. On the other hand, I misremembered the behavior in V9, thinking the border was rendered on top of the token image. Given that, I would no longer call this a bug.

**Comment by dev7355608** [comment]
The token border could be rendered above the token mesh (without the reverse mask) on hover/highlight.

**Comment by aaclayton** [comment]
> The token border could be rendered above the token mesh (without the reverse mask) on hover/highlight.

I like that suggestion. Reframing the issue accordingly.

**Comment by Feu-Secret** [comment]
@aaclayton Instead of having a full _no draw_ mask, we could let the border appears on the token with an alpha blend (maybe 0.25 or event 0.15).

**Comment by BoltsJ** [comment]
Hex Token Size Support has (had?) the ability to render the border above or below the token, specifically for the option that would always show the token border. Currently, that feature is non-functional and hard coding an alpha blend would make the Always Show Border option worse for people who want the current behavior. It would be nice if said alpha value could be configured.
