### ISSUE TITLE
Feature Request: Upgrade channel that suppresses major version upgrades during the transition period to stability

### ISSUE THREAD

**Issue by mothringer** [foundryvtt/foundryvtt#8049]
### User Experience

Can we get an additional upgrade channel option that suppresses major version upgrades like v9 to v10 for those who need to wait for compatibility in our systems or modules. I recently accidentally upgraded to v10 with an incompatible system because I was trying to grab the 9.280 security update and had the misfortune to do so shortly after v10 came out but before I heard about the release of v10 stable.

It would give a lot of peace of mind being able to be sure the update button was always safe when new major versions were coming out soon that would break modules and systems in the short term.

**Comment by aaclayton** [comment]
I appreciate you submitting your suggestion, but this isn't the way we will go with it. When a core Foundry VTT build reaches the "stable" channel, we believe it is stable and we stand behind that. 

Foundry VTT version 10 incorporates a number of new safeguards which help to ensure that users cannot upgrade or launch worlds for systems that are not yet compatible with the new version. This will start to pay dividends when the time comes for the v10->v11 migration. 

This code doesn't exist in V9 so did not exist to help protect you in this case, but version 10 does a better job with this.
