### ISSUE TITLE
Macrobar and player list are hidden when the chat is opened, chat is not scrollable and Pings do not work.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8054]
### What happened?

Reported from https://discord.com/channels/170995199584108546/956306859491471420/1014982977626837004

![image](https://user-images.githubusercontent.com/66535080/188099804-dd1e9dfa-a7c5-4f02-aec7-c31418e1e0b6.png)
![image](https://user-images.githubusercontent.com/66535080/188099818-78ee04d3-d58d-41a0-9922-4ba08657c610.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Migrate a world to v10 and start the world

### What core version are you reporting this for?

Version 10 Stable

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Dick-K** [comment]
Not just chat, any sidebar category whose members extend further than the depth of the Foundry window.

**Comment by Fyorl** [comment]
This seems to only occur if AV is docked to the bottom.

**Comment by Dick-K** [comment]
> This seems to only occur if AV is docked to the top or bottom.

Confirmed, well noticed!

**Comment by bobby-driggs** [comment]
+1 same issue. and also confirmed about the docking top / bottom
