### ISSUE TITLE
The game system update dialog is throwing errors when performing an Update All.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8056]
### What happened?

Reported from https://discord.com/channels/170995199584108546/956306859491471420/1015020702107185223,
https://discord.com/channels/170995199584108546/956306859491471420/1015065010713669684,
https://discord.com/channels/170995199584108546/956306859491471420/1015158278185025536

I suspect https://discord.com/channels/170995199584108546/956306859491471420/1015098135103672370 to be related.

![image](https://user-images.githubusercontent.com/66535080/188102251-d30bf291-b62d-4355-9a82-3d9e419ed7c6.png)
![image](https://user-images.githubusercontent.com/66535080/188105239-66af7b03-bd15-4cfd-ae30-9abe79c713b8.png)
![image](https://user-images.githubusercontent.com/66535080/188105259-f7ccc116-ac37-4702-be4b-59272d75df8e.png)
![image](https://user-images.githubusercontent.com/66535080/188105279-8313aab0-de9b-4641-842f-a51b9f4646a4.png)
![image](https://user-images.githubusercontent.com/66535080/188105311-7da34bd4-3d23-4311-8573-69f002caf4c4.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Perform "Update All" in game systems on Foundry 10.284

### What core version are you reporting this for?

Version 10 Stable 284

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is definitely happening because I've seen multiple reports of the same thing, although I was not able to reproduce it in my environment. We might need to reverse-engineer what causes the error from the provided stack traces to try and figure out what might be happening.
