### ISSUE TITLE
Modules with correct compatibility are still flagged as compatibility unknown.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8057]
### What happened?

Reported from https://discord.com/channels/170995199584108546/956306859491471420/1015039745560150047

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Install a module with correct compatibility such as FXMaster or Tokenizer.
2) Restart FVTT
3) Click update on each modules (optional?), might drop a separate error.
4) Repeat 2-3 until the module is now flagged as unknown compatibility. This can take more than one restart.

### What core version are you reporting this for?

Version 10 Stable

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Ikabodo** [comment]
Can confirm this happens in Chrome too.

**Comment by Morters** [comment]
Can confirm Chrome also, having the same issue. 
Restarting foundry brings back the issue after re-installing.

**Comment by aaclayton** [comment]
Video examples of this happening:

<https://discord.com/channels/170995199584108546/956307084931112960/1015030381143142400>
<https://discord.com/channels/170995199584108546/956307084931112960/1015031344679620679>
