### ISSUE TITLE
Select multiple walls with square selection when holding shift

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#8059]
### User Experience

Currently, Foundry allows the GM to select multiple walls by holding shift while selecting walls. It would be nice if holding shift also allowed the GM to select multiple walls when using the "Rectangular Select Walls" tool. In other words, if some walls are already selected, and you hold "shift" while using "Rectangular Select Walls", the existing selection should remain, and new walls added by the tool should also be selected.

**Comment by aaclayton** [comment]
Yeah, I agree. I actually thought this UX existed and surprised myself the other day when it didn't work the way I expected.
