### ISSUE TITLE
Improve the rendered interaction between multiple vision sources which apply different vision modes, for example one token with basic sight and another with darkvision.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8061]
### What happened?

Darkvision has priority over basic vision when multiple tokens are selected.

![image](https://user-images.githubusercontent.com/66535080/188175853-d548e8e2-4c14-4447-a767-606d66884994.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Select multiple tokens with darkvision and basic vision.

### What core version are you reporting this for?

Version 10 Stable Build 284

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
https://discord.com/channels/170995199584108546/956307084931112960/1015275897919647814

**Comment by Feu-Secret** [comment]
This is not ideal, but it is working as intended. For a player, when multiple tokens are owned and not selected, the vision is the sum of all vision sources which are blended together (in maximum color blend mode). We need a kind of way to assign a low or high priority to vision sources and create an extra step into our framework for high priority vision sources to be blended over low priority vision sources (in a normal blend mode). It will be for a future version of Foundry.

**Comment by Feu-Secret** [comment]
Finally, we found an elegant way to prioritize the basic sight. A new property is introduced in the `VisionMode` object: `preferred`.
```js
      // Default (Basic) Vision
      basic: new VisionMode({
        id: "basic",
        label: "VISION.ModeBasicVision",
        vision: {
          defaults: { attenuation: 0, contrast: 0, saturation: 0, brightness: 0 },
          preferred: true // Takes priority over other vision modes
        }
      }),
```

**Comment by sPOiDar** [comment]
Hey @Feu-Secret hope you're well :smile: 

In a report from another user, this behaviour was discovered on 285, and not sure if it was covered by the fix here:

With a light source:
![lightsource](https://user-images.githubusercontent.com/70048780/190545685-427a4e01-5886-47e4-8da1-07c52b813aee.png)

A token with basic vision:
![basicvision](https://user-images.githubusercontent.com/70048780/190545697-b247bd7c-6cfd-402c-921f-854f27178e15.png)

A token with dark vision:
![darkvision](https://user-images.githubusercontent.com/70048780/190545712-376f1cc4-f205-4c74-9660-6ebe951ef903.png)

This is the result of the combined vision:
![combinedvision](https://user-images.githubusercontent.com/70048780/190545726-0bf2c359-d3ec-4ea1-8d0f-3e8d573bcf0a.png)

It appears that the darkvision monochrome effect ignores the light source mask when multiple tokens are selected.
