### ISSUE TITLE
Implement a Pre-Flight Compatibility Checklist which reports on the forward-looking compatibility status of installed systems and modules for a candidate core software version.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8064]
# Scoping/Requirements
- Present Preview Compatibility option (button, checkbox, etc...) on the `/update` view.
- Ensure that website update check endpoint reports back with error plus data.
- Improve the UX around generation updates that cannot be installed via the app - a window with more instructions - more user friendly.
- Create a process diagram that helps us to understand the workflow related to package updates.
- Potentially create a "dry run" API here which could be used to help ensure our test cases are working as expected.
- Complexity around dependency handling and satisfaction of dependencies.

In an ideal world, the compatibility check reports on *what the user would actually get if they were to click "Update All" in the next generation of the software". The ideal solution should simulate and reproduce those results.

## Data Sources
1. The website knows about a newer version and its compatibility
2. The upstream manifest URL knows about a newer version and its compatibility
- For packages that don't have 1, we have to use 2.
- If we have data from 1, use that.
3. Website API probably needs an option to return all packages, even if incompatible (key unknown)

# Related Issues

# Original Issue Content

I know that everyone and her dog has Thoughts about how to ease the oops-I-didn't-mean-to-update phase around major releases, and yes we absolutely have a good number of warnings in all the right places, but hear me out on maybe one more thing that could help _a lot_, I think:

When you're in Setup > Update Software and you hit the Check for Update button, run a manifest check on all installed systems and modules _as if the client were running the new/proposed core release_. This will acquire incompatibility flags for all installed packages, which would then be displayed — and required to be acknowledged — before the Begin Download button does anything.

Could be a window that pops after clicking Begin Download, could be displayed inline with the patch notes, I dunno, whatever works best in your mind.

But _currently_ there is no straightforward way for users to see exactly what is going to "break" when they update core. Presenting this up front seems technically possible, and could save a lot of grief in the long run.

**Comment by plutoneld** [comment]
Related to #6325

**Comment by aaclayton** [comment]
Comment from @larkinabout

It would be great to be able to check for compatibility with  installed systems and modules when updating core, systems or modules. Something like a pop-up warning  when a user clicks 'Update', which loops through and checks the compatibility requirements of systems/modules that have dependencies on the package being updated.

**Comment by theripper93** [comment]
This is my current implementation as a script that can be run in the setup screen

```js
!async function(){async function e(e,t){let o={};try{o=await Setup.checkPackage({type:e,id:t})}catch(e){}return o}const t=Array.from(game.systems).map((e=>e.id)),o=Array.from(game.modules).map((e=>e.id));let n=await Promise.all(t.map((async t=>{const o=await e("system",t);return{name:game.systems.get(t).title??t,version:o.remote?.compatibility?.verified??"Unknown",goodToUpdate:parseInt(game.version)<parseInt(o.remote?.compatibility?.verified)}})));n=n.sort(((e,t)=>e.name?.localeCompare(t.name))).sort(((e,t)=>e.goodToUpdate?-1:1));let a=await Promise.all(o.map((async t=>{const o=await e("module",t);return{name:game.modules.get(t).title??t,version:o.remote?.compatibility?.verified??"Unknown",goodToUpdate:parseInt(game.version)<parseInt(o.remote?.compatibility?.verified)}})));a=a.sort(((e,t)=>e.name?.localeCompare(t.name))).sort(((e,t)=>e.goodToUpdate?-1:1));const r=`\n    <table id="version-checker">\n        <thead>\n            <tr>\n                <th>System</th>\n                <th>FVTT Version</th>\n            </tr>\n        </thead>\n        <tbody>\n            ${n.map((e=>`<tr><td>${e.name}</td><td style="background-color: ${e.goodToUpdate?"lime":"red"};">${e.version}</td></tr>`)).join("")}\n        </tbody>\n    </table>\n    `,i=`\n    <table>\n        <thead>\n            <tr>\n                <th>Module</th>\n                <th>FVTT Version</th>\n            </tr>\n        </thead>\n        <tbody>\n            ${a.map((e=>`<tr><td>${e.name}</td><td style="background-color: ${e.goodToUpdate?"lime":"red"};">${e.version}</td></tr>`)).join("")}\n        </tbody>\n    </table>\n    `;Dialog.prompt({title:"Modules and Systems",content:r+i,rejectClose:!1,render:e=>{setTimeout((()=>{document.querySelector("#version-checker").scrollIntoView(!0)}),100)}})}();
```

![image](https://github.com/foundryvtt/foundryvtt/assets/1346839/dc85e710-d886-41b0-acd8-de62bc800a95)

**Comment by aaclayton** [comment]
Thank you @theripper93. Please note that we do not endorse anyone pasting JavaScript code into the Foundry VTT console on the setup screen. Pasting code to execute on the `/setup` screen can have damaging impacts on your environment and installation. It's essential that we emphasize that using such a script is risky and not recommended. 

We will certainly evaluate and prioritize these changes to improve user experience for our users. We hear and understand that this is a pain point for people.

**Comment by alexdiste** [comment]
It would be useful to have a report out that summarize the thins.

For example you Have installed xx systems, of this xx system yy are already ready for next version with a percentage of -> yy/xx=50%

Same for modules. It would be great if we can have a summary for all modules installed and a summart for world considering module enable for that word.
Suppose you have a word with only 2 modules, It can reports 2 2/2 migrated. 
Meanwhile overall you could have 100 modules and overall percentage could be 40%.

At least users will know, which systems will work, which world and the percentage of success for every combination of world/system
