### ISSUE TITLE
Implement Keyboard Commands for Tour Next, Previous, and Exit

### ISSUE THREAD

**Issue by plutoneld** [foundryvtt/foundryvtt#8065]
### User Experience

Currently with a Tour active, there is a fair bit of chasing the forward/backward buttons around the screen with the mouse.

Implementing Keyboard Commands for Tour Progress could allow the user to navigate the Tour forward/backward with the arrow keys on the keyboard instead.

**Comment by aaclayton** [comment]
Arrow keys would be a nice touch for sure.
