### ISSUE TITLE
`relationships.systems` no longer requires related systems to be installed, favoring an entry in `relationships.requires` for that need

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8066]
### User Experience

v10.284

If you are installing a module that has declared more than one system in its manifest, the updater will prompt you to install all listed systems as if they were required dependencies. You shouldn't have to install dnd5e to use roll-new-character-stats with pf1, etc, etc.

**Comment by tposney** [comment]
Of the top of my head I can't think of an obvious case for needing more than one of the systems installed, except perhaps if you are accessing some of the assets from one of the systems.

Ideally you could specify if foundry should attempt to load the system or not. Alternatively, perhaps if there is only a single system listed it should go ahead and prompt for the install.

**Comment by esheyw** [comment]
Yea, if *none* of the systems listed are installed, prompting to install at least one would be valuable. maybe you didn't notice the module you chose is only tagged for a system you don't use? that prompt would alert you.

As is, at least you don't have to actually install anything, you can just X out of the dependency window, but that's not something we should get users in the habit of doing.

**Comment by aaclayton** [comment]
@cswendrowski I think there is a good argument here that we should only prompt the user to install dependencies for `relationships.requires` and not `relationships.systems` - or at least not in cases where `relationships.systems` lists more than one option.
