### ISSUE TITLE
Certain invalid document links can prevent journal pages from rendering

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8067]
originally reported by `@DeciusAemilius#4956` 

It appears something may not be failing gracefully with malformed dynamic document links. The following html string from a journal entry in a compendium caused the journal entry not to render at all in v10.

(note, edited to purge copyright material as the original entry comes from a D&D beyond import, only leaving bare pieces to demonstrate the problem)
```
A narrow stone bridge....eight @Actor[ZMEHpUWhiuyqBU6t]{Drowned Zombie} (see Appendix B). two @Compendium[world.ddb-saltmarsh-items.OFALvGR0JZq4aqhr]{Spear, +1}, a set of @Compendium[world.ddb-saltmarsh-items.PLRTwEAp2Y0x25dx]{Mariner's Armor}, a @Compendium[world.ddb-saltmarsh-items.fal5pYEmoAC7ppqe]{Ring of Water Walking}, and a spell scroll of @Compendium[world.ddb-saltmarsh-spells.gWwInrmbJwDEQ9kN]{Speak with Dead} (see Appendix C)
```

Full original JSON file available upon request for internal testing.

**Comment by aaclayton** [comment]
Certainly the goal here should be that invalid syntax in a link should never cause an unhandled exception - so we need to either harden the logic or wrap this processing in a `try` to ensure that we don't end up in an unhandled exception case.

**Comment by Fyorl** [comment]
This was confirmed as a module issue by the reporter.
