### ISSUE TITLE
Add an option for the FilePathField to explicitly allow for wildcard paths in the data schema, fixing issues with wildcard token paths where the wildcard path did not include a valid extension.

### ISSUE THREAD

**Issue by shecrio** [foundryvtt/foundryvtt#8069]
### What happened?

With no modules loaded in dnd5e v2.0.2 wildcard images do not work.
Regardless of if Randomize Wildcard Images is ticked or not, setting the file path to end in *.png will just use whatever the token was last set to, and ending in just * will throw an error about unaccepted file extension and then default to whatever file was set at the beginning of that session.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

To induce this bug attempt to use wildcard images for a prototype token.

### What core version are you reporting this for?

Version 10 Stable (build 284)

### Relevant log output

```shell
foundry.js:711 Error: Actor5e [cfIOAX3jPU51e0vZ] Model Validation Errors
[Actor5e.prototypeToken]: Model Validation Errors
[PrototypeToken.texture]: Model Validation Errors
[PrototypeToken.texture.src]: does not have a valid file extension
    at SchemaField._validateType (commons.js:3630)
    at SchemaField.validate (commons.js:3357)
    at Actor5e.validate (commons.js:4994)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12560)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12476)
    at ClientDatabaseBackend.update (commons.js:6297)
    at async Function.updateDocuments (commons.js:5652)
    at async Actor5e.update (commons.js:5749)
onError @ foundry.js:711
_preUpdateDocumentArray @ foundry.js:12563
_updateDocuments @ foundry.js:12476
update @ commons.js:6297
async function (async)
update @ commons.js:6294
updateDocuments @ commons.js:5652
update @ commons.js:5749
update @ commons.js:10513
_updateObject @ foundry.js:70070
async function (async)
_updateObject @ foundry.js:70066
_onSubmit @ foundry.js:5778
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Wildcard paths like `/some/directory/*.webp` are wroking just fine for me, but I'll do further testing with a wildcard path that doesn't end in a file extension.

**Comment by danil0man** [comment]
Even after giving them a file extension, I am experiencing the same problem. Tested in two different systems. The only difference with using the file format is that there are no errors. Getting this errors
![image](https://user-images.githubusercontent.com/72052103/188286309-5252765c-0ff8-4142-b39e-d01a6b7e7892.png)
If I instead give it the extension the error goes away, but there is no wildcard token once is dragged to the map
