### ISSUE TITLE
Address a rounding issue in the fog exploration texture size which can produce gradual fog drift for unusually sized scenes.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8075]
Related to: https://github.com/foundryvtt/foundryvtt/issues/4324

I think the rounding has gone missing if it was ever there. This might be reason for the fog drift
```js
    let resolution = 1.0;
    if ( (width >= height) && (width > maxSize) ) {
      resolution = maxSize / width;
      height = Math.ceil(height * resolution) / resolution;
    } else if ( height > maxSize ) {
      resolution = maxSize / height;
      width = Math.ceil(width * resolution) / resolution;
    }
```

I've confirmed that this fixes the fog drifting. There was rounding put in place somewhere in v8 development. But it was removed in the v9 prototype with the rewrite of of _configureFogResolution and the fog drifting issue returned.  v8:
```
    // Determine the fog texture dimensions that is evenly divisible by the scaled resolution
    const width = d.sceneWidth.toNearest(factor, "ceil");
    const height = d.sceneHeight.toNearest(factor, "ceil");
```

**Comment by Fyorl** [comment]
Having some trouble reproducing the fog drift in the first place in order to verify that rounding the fog texture dimensions fixes it.

**Comment by dev7355608** [comment]
@Fyorl Scene dimensions: 8192x4001

**Comment by Fyorl** [comment]
Thanks, I'm able to reproduce this reliably now.
