### ISSUE TITLE
Package sidegrade strips the "compatibility.verified" field instead of updating it with remote data.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8081]
## Repro steps:

1. Install <https://raw.githubusercontent.com/Sk1mble/zsync/v0.0.6/module.json>
2. Observe that the installed manifest lists verified compatibility of "10.275"
3. Attempt to update the `zsync` module, retrieving sidegrade data from foundryvtt.com
4. Note that the website lists verified compatibility of "10.284"

## Expected result
The local manifest is sidegraded and now contains verified compatibility of `10.284`

## Actual result
The `compatibility.verified` field is deleted entirely from the local maniest.

**Comment by Sk1mble** [comment]
I tested switching the verified compatible field on the Foundry package manager back to 10.275 and this behaviour still occurred; I don't believe it should have performed a sideload under those circumstances. 

This is happening for most of the modules installed on my system. The only commonality between the ones where this is NOT happening are that their manifest files contain the CompatibleCoreVersion attribute set to 10.284.

I set this on the zsync and whisperbox manifests and sure enough the bug didn't occur when I clicked update all.
