### ISSUE TITLE
For packages which have errors that prevent them from being usable, add "Uninstall" and "Reinstall" buttons to the error report form.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8085]
Originally reported by Lott#5525 https://discord.com/channels/170995199584108546/956306859491471420/1015300678966591578

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** N/A  
**Short Description of bug:** Modules installed prior to upgrading to v10 that have "Module Model Validation Errors" are listed as uninstalled and will not check for updated versions when clicking "Update All" on the "Add-on Modules" Setup screen.  
**Simple steps to reproduce the bug:**  Have a module installed from v9 that gives a v10 Model Validation Error -> Click Update All -> Module is not updated even if an update exists and when viewing the module from the install screen lists it as "Uninstalled"  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/188437834-adc86142-ef1f-4ccf-b04c-ef03353e28d3.png)

## Dev notes

Packages should have different tiers:

1) Entirely invalid - missing `id` or other critical fields. These cannot even be displayed / operated on.
2) Invalid for use - packages that fail validation and can't be loaded in a World, but can be displayed. These should show up in /setup for update / uninstall
3) Valid - can be used in-world

**Comment by Fyorl** [comment]
Additional report that is likely related, in that modules that fail validation can also not be uninstalled.

Originally reported by SoundAI#7219 https://discord.com/channels/170995199584108546/956306859491471420/1016643761087975434

**ALL MODULES DISABLED?** not applicable  
**OS, Hosting, Browser (if applicable):** Ubuntu, Oracle, Brave  
**Short Description of bug:** Cannot uninstall module that fails installation validation.  
**Simple steps to reproduce the bug:** Install PF2 Workbench module. Foundry throws error and delists said module from its modules list without telling the user what to do or where to find the module directory for manual deletion.  
**Screenshots and/or console errors:**

```
foundry.js:58303 Errors were encountered while installing the package. Consult your console log (F12) for details.
setup.js:141 [xdy-pf2e-workbench] Metadata validation failed for module "xdy-pf2e-workbench": The file "lib/tooltipster.
```

From the module.json:

```
"scripts": [
    "./lib/tooltipster.bundle.min.js"
```

This is a PF2 system file. It does not matter whether the PF2 system is install or not, same error and same problem of not being able to uninstall via GUI.

**Comment by anathemamask** [comment]
Suggestion:

A workflow could be added to the error message that lists each invalid package, with a button for "delete" and another for "reinstall?" that when clicked would reach out to the package repo for the latest version of the package.
