### ISSUE TITLE
Cannot change the view mode of a journal entry without owner permissions

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8088]
Originally reported by Crowguard#7458 https://discord.com/channels/170995199584108546/956306859491471420/1015351972402045079

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Win11, Electron app  
**Short Description of bug:** As a player, clicking the "Change View" button a journal that a player doesn't have ownership of a player results in errors  
**Simple steps to reproduce the bug:**  Show a journal to players, then click "Change View" on the player side.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/188439685-15ef35b0-800e-4ee6-8cb2-a7cc00de0d44.png)

**Comment by Fyorl** [comment]
Likely caused by #7724

**Comment by mkahvi** [comment]
This also affects journals in locked compendiums.
