### ISSUE TITLE
Add an option for the FilePathField to explicitly allow for wildcard paths in the data schema, fixing issues with wildcard token paths where the wildcard path did not include a valid extension.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8089]
Originally reported by Renderance#4360 https://discord.com/channels/170995199584108546/956306859491471420/1015365456888090685

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Saw in electron app and Ubuntu Server  
**Short Description of bug:** Wildcard images throw error or don't appear. Tested in 2 different systems. 5e and Essence20  
**Simple steps to reproduce the bug:** Attempt to use WIlcard images  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/188441011-26d1035e-fb28-4d95-b088-dcb19495133b.png)

![image](https://user-images.githubusercontent.com/207433/188441055-5465097c-df0c-45a7-be58-20b03ff89bb7.png)

**Comment by Fyorl** [comment]
Seems like this might be only extension-less wildcard paths, the reporter did not specify.

**Comment by Fyorl** [comment]
Related report from a different user danil0#8120 https://discord.com/channels/170995199584108546/956306859491471420/1015714599716257942

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** windows, Brave  
**Short Description of bug:** Is not possible to add wildcards tokens. The functionality of wildcard tokens is not working  
**Simple steps to reproduce the bug:** I try to find a folder and give it the path images/folder/* or images/folder/*.png. then apply assign token or update token  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/188444005-dec7aec0-fc0a-4918-a10c-adaca3854e66.png)

**Comment by Fyorl** [comment]
An additional report to help narrow this down: 
https://discord.com/channels/170995199584108546/956306859491471420/1016290965373341767

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Win10, foundry app  
**Short Description of bug:** it seems that token wildcards no longer work. if I add * to the end of the image path, it tells me that the extension is invalid; the same for * . *  
if i use *.png instead, it doesn't recognise any images, so the token is the basic "mystery man".  
**Simple steps to reproduce the bug:** try to use wildcards to set the token image  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/188450790-c6f0196d-d5aa-4c9a-b483-0f309728a4cd.png)

**Comment by aaclayton** [comment]
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/8069
