### ISSUE TITLE
Allow API users to change a token vision mode with its vision mode defaults (or not).

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8098]
Originally reported by Cris#6864 https://discord.com/channels/170995199584108546/956306859491471420/1016055498996457552

**ALL MODULES DISABLED?:** true  
**OS, Hosting, Browser (if applicable):** Win10, Foundry app  
**Short Description of bug:** Can't change vision mode through api, see discussion here: https://discord.com/channels/170995199584108546/956243957816377414/1016044594854637679  
**Simple steps to reproduce the bug:** Run `token.document.update({sight:{visionMode:'monochromatic'}})`  
**Screenshots and/or console errors:**

https://user-images.githubusercontent.com/207433/188447771-3aa60c1a-129b-40c1-a565-f4958e39aedf.mp4

**Comment by Feu-Secret** [comment]
This was not *really* a bug. It is just that a vision mode comes with defaults, and that changing a vision mode with the API does not change the token advanced vision modes setting (which should be updated via the API).

To make it easier to change vision modes, we added a new method: `TokenDocument#updateVisionMode`

```js
  /**
   * Convenience method to change a token vision mode.
   * @param {string} visionMode       The vision mode to apply to this token.
   * @param {boolean} [defaults=true] If the vision mode should be updated with its defaults.
   * @returns {Promise<*>}
   */
  async updateVisionMode(visionMode, defaults=true) {
    if ( !(visionMode in CONFIG.Canvas.visionModes) ) {
      throw new Error("The provided vision mode does not exist in CONFIG.Canvas.visionModes");
    }
    let update = {sight: {visionMode: visionMode}};
    if ( defaults ) foundry.utils.mergeObject(update.sight, CONFIG.Canvas.visionModes[visionMode].vision.defaults);
    return this.update(update);
  }
```

**Comment by stwlam** [comment]
Won't this have aberrant results if a hook causes the update to abort?

**Comment by Feu-Secret** [comment]
> Won't this have aberrant results if a hook causes the update to abort?

I may have misunderstood your statement, but the behavior of this method is the same as `update`. So if it is cancelled, the `update` will be... cancelled.

**Comment by stwlam** [comment]
> > Won't this have aberrant results if a hook causes the update to abort?
> 
> I may have misunderstood your statement, but the behavior of this method is the same as `update`. So if it is cancelled, the `update` will be... cancelled.

The defaults are changed beforehand, though.
