### ISSUE TITLE
Deprecated token scale/mirror updates not working correctly

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8101]
Originally reported by Aedif#7268 https://discord.com/channels/170995199584108546/956306859491471420/1016296052556582932

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, Foundry App  
**Short Description of bug:** Token scale/mirror updates are not being correctly converted to the new format. Scale updated will revert mirroring, and mirror updated will revert scaling to 1.  
**Simple steps to reproduce the bug:**
1a. Change Token configuration to Mirror Image Vertically
2a. Select Token and run `_token.document.update({ scale: 1})`
3a. Token mirroring will revert to X/Y: false

1b. Change Token configuration to Scale: 2
2b. Select Token and run `_token.document.update({ mirrorX: false, mirrorY: false })`
3b. Token scale will be reverted to: 1

**Comment by Feu-Secret** [comment]
Unfortunately, we won't be able to provide compatibility with the deprecated token properties `scale` and `mirrorX/Y`, there are competing needs for backwards compatibility and its not possible for us to support all deprecated workflows.
You will need to use the new properties to update correctly tokens:
- texture.scaleX
- texture.scaleY
