### ISSUE TITLE
`AlphaBlurFilterPass` doesn't affect the saved fog sprite as intended

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8103]
### What happened?

The saved fog texture is opaque and so the alpha passes of the `VisibilityFilter` are no different from a normal blur. Fog sprite needs a shader that makes the red channel the alpha, for example: https://github.com/dev7355608/perfect-vision/blob/9e2263b77920bf63068f917171a1f37b78da5269/patches/fog.js#L421-L439

Before the first time the fog is saved. The fog sprite is empty.
![image](https://user-images.githubusercontent.com/31905376/188490648-989ee2e3-97f9-48e3-be25-b847376dd0f9.png)
After reloading the fog sprite is no longer empty.
![image](https://user-images.githubusercontent.com/31905376/188490700-67e02d3d-272c-4837-b3e8-b2f32a7f0259.png)
With nonempty fog sprite and fix.
![image](https://user-images.githubusercontent.com/31905376/188490771-3035e390-0e21-4ca5-b0f5-1c97d1cd0d7f.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 1 (build 284)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Good catch!
