### ISSUE TITLE
Block the Token actorData object from containing a degenerate circular reference to "token" or "prototypeToken"

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8109]
### What happened?

I'm not sure how this could have even happened, but upon testing some older worlds (created in 0.7 and kept up to date through V9) by attempting to migrate them to V10, some unlinked tokens have a prototype `token` partial in their `actorData` objects. These don't get migrated to `prototypeToken`, making for a flurry of deprecation warnings when a synthetic actor is constructed that can't be easily gotten rid of by a typical user.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Somehow have an unlinked token in a scene with an object at `#actorData#token`.
2. Launch the world with that scene in V10.

### What core version are you reporting this for?

Version 10.284

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think perhaps the best thing to do here would be to forcibly cull the `token` and `prototypeToken` keys from `actorData` since it's meaningless to store any data there. Thoughts?

**Comment by stwlam** [comment]
Sounds good to me.
