### ISSUE TITLE
The documentation of `prepareData` indicates that it resets the source data, this changed in V10 and the reset method performs this source reset and calls preparation.

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/foundryvtt#8110]
### What happened?

In v9, there was a call to `this.data.reset();` at the top of `Actor.prepareData` (and indeed, the method's comment still mentions "`Begin by resetting the prepared data back to its source state.`") which reset things back to a pre-AE/etc. state. In v10, this no longer seems to be the case. 

This is problematic for my use-case as I previously ran `prepareData`, after patching some active effect functionality, to re-generate each actor's user-facing data. Without the reset, each call to `prepareData` applies each AE an additional time!

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

```js
(async () => {
	const act = await Actor.create({
		name: "Test",
		type: "npc",
		system: {
			"abilities.str.value": 20,
		}
	})

	await act.createEmbeddedDocuments(
		"ActiveEffect",
		[
			{
				label: "test",
				changes: [
					{
						key: "system.abilities.str.value",
						mode: 2,
						value: "+1",
					}
				]
			}
		]
	)

	for (let i = 0; i < 5; ++i) {
		act.prepareData();
	}
	
	// Expected: 21
	// Actual: 26
	console.log(act.system.abilities.str.value)
})()

```

### What core version are you reporting this for?

Version 10 284

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
You'll want to call `act.reset()` now, which will in turn call `#prepareData`.

**Comment by TheGiddyLimit** [comment]
Fair enough. Just the documentation of `prepareData` which needs updated, then!
