### ISSUE TITLE
Shift-mousewheel doesn't rotate things under macOS

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8111]
### What happened?

Shift-mousewheel to rotate things in large increments hasn't worked on macOS since at least as far back as v7. Would be nice to get that going, if it's not a huge technical hurdle.

Command-mousewheel has always worked (aping Control-mousewheel), and adding Shift for things like group selection and other keybinds works as expected. Just rotations don't — for all placeables.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Control or hover a token, tile, light, sound, or template.
2. Hold Shift and scroll the mousewheel.
3. (nothing happens)

### What core version are you reporting this for?

10.284

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Strange one. Perhaps @unsoluble you might be able to lend us a bit of time to help collect some diagnostic data to understand why the shift key is not detected during a mousewheel event.

**Comment by unsoluble** [comment]
Happy to help with whatever I can.

For what it's worth, if I throw this onto a page it'll respond properly to all three modifier keys on `mousewheel` events:
```js
document.addEventListener("mousewheel", (evn) => {
  const shift = evn.getModifierState("Shift");
  const cmd = evn.getModifierState("Meta");
  const alt = evn.getModifierState("Alt");

  console.log("Mouse scrolled! Modifiers:");
  console.table({shift, cmd, alt});
});
```
Not quite sure where to look to see how the Foundry API is listening specifically on these events tho.

**Comment by aaclayton** [comment]
@unsoluble do `event.getModifierState("Shift")` and `event.shiftKey` both give you the same (correct) answer? You can take a look at the `MouseManager#_onWheel` function to see what Foundry is doing. We use `event.shiftKey` to determine whether shift is pressed.

**Comment by unsoluble** [comment]
Yep, if I use `event.shiftKey` instead, it still prints `true`, as I'm Shift-scrolling while hovering a measurement origin (for example). Same for both left and right Shift, too.
