### ISSUE TITLE
Allow higher maximum framerate then 60 fps (for monitors with a higher refresh rates)

### ISSUE THREAD

**Issue by Albinosheep** [foundryvtt/foundryvtt#8118]
### User Experience

I use a monitor with a higher refreshrate then 60 fps. Foundry only allows 60 fps as the Maximum Framerate in the Core-Settings.
<img width="264" alt="Maximum Framerate" src="https://user-images.githubusercontent.com/41292141/188757256-9405c650-f1e7-4407-a6a1-3fb4fa0793be.PNG">
It would be nice if vtt isnt capped at 60 fps.

**Comment by MaxPat931** [comment]
If your performance mode is on Maximum, and the FPS is set to 60, then it will not be capped and can exceed 60 fps

**Comment by unsoluble** [comment]
If your Performance Mode is set to Maximum and FPS Cap set to 60, it’s actually uncapped at that point.

**Comment by unsoluble** [comment]
Goddammit max

**Comment by Albinosheep** [comment]
OK that works, thank you!
It would be fine to have higher fps-caps then 60 and also an "unlimited" option then. :-D
