### ISSUE TITLE
Player view is not refreshed when a token with vision is dropped onto a scene where the player did not have vision before

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8120]
Originally reported by MLeahy#4299 https://discord.com/channels/170995199584108546/956306859491471420/1016512113256181770

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Latest Chrome / Windows 10; Latest FVTT (Node)  
**Short Description of bug:** Player client does not update scene when going from no token to a token added to the scene by the GM.  
**Simple steps to reproduce the bug:**  
 Connect a player and GM client. Put the player on a scene they don't have a token. Black screen as expected. Have the GM drop their token on the scene. Notice that the player client does not update w/ vision of the scene and it requires a refresh of the player client to properly see the scene. Refer to the clear example GIF below. 

**Screenshots and/or console errors:**

![FVTT-player-drop-bug](https://user-images.githubusercontent.com/207433/188864855-5df7e47c-ea6e-4591-b685-e4542396cbf0.gif)

**Comment by Feu-Secret** [comment]
I can't reproduce this issue. I need a second opinion to confirm.

**Comment by typhonrt** [comment]
Just a note that I confirmed the issue existed w/ `10.284`, but is working / nonrepro in `10.285`. So this issue is resolved.
