### ISSUE TITLE
FoW is revealed in a smaller radius than the token perceives

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8126]
Originally reported by Cris#6864 https://discord.com/channels/170995199584108546/956306859491471420/1016774097725816934

**ALL MODULES DISABLED?:** true  
**OS, Hosting, Browser (if applicable):** Win10, self hosted, tested on Electron, Chrome and Firefox  
**Short Description of bug:**  
Explored fog of war is smaller than vision range after moving.  
See the attached image: on the left, the vision is equal to the red circle. The token is then moved one spot to the right (right image). The red circle is the same size and on the same location, but there is a part on the left that's obscured again by the FoW, but only in the direction of movement. If the FoW is reset, the explored FoW is exactly the size of the token, even after the token moves away, so this only happens after movement.  
**Simple steps to reproduce the bug:** Place a token on the canvas, reset the FoW, move one spot in one direction, and then back.  
**Screenshots and/or console errors:** No errors

![image](https://user-images.githubusercontent.com/207433/188871287-db5ec194-3aec-4f86-ad4d-6e6e2adb4f2a.png)

**Comment by aaclayton** [comment]
probably due to debounced fog exploration during animated token movement.
