### ISSUE TITLE
Scope notification CSS styles more specifically to only apply to messages within the singular notifications element.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8133]
### User Experience

For example, `.notification` is defined simply as that, with nothing else. This makes it apply to any .notification inside of sheets any other parts of Foundry. In this case `#notifications > .notification` would be be much better and not leak out of its intended usage.

Other similar overly generic CSS selectors should be tightened also.

This helps systems/modules not need to fight the generic stylings when they happen to use similar selector names but with tighter selectors themselves (e.g. `.mysystem.sheet .notification`).

The alternatives is more explicit selector names (e.g. for us to use `.mysystem-notification` or similar), but if that's the recommended path for systems/modules, Foundry should set the example itself (e.g. `.foundry-notification` with the aforementioned case).

**Comment by aaclayton** [comment]
I'm happy to address an issue to improve scoping for `.notification` specifically - but we can't take a GitHub issue to just generally "write better code" as that isn't an actionable thing but rather an abstract goal.

Focusing on the specific example at hand. If you have other specific examples we can expand this issue or open others.

**Comment by mkahvi** [comment]
Yeah, sorry, I did not investigate too deeply on the possible cases that could be improved. That particular one is just something I've encountered repeatedly. I'll try to be vigilant for other specific instances.

**Comment by arcanistzed** [comment]
I definitely prefer the `.fvtt-notification` option over scoping this class with `#notification > . notification`. The reason for this is that I just wrote code yesterday that uses the notification styling with an Application actually, so there's definitely a use case for that.

In fact, at risk of making this suggestion too broad again, it might make sense to prefix all of the classes used in FVTT with `.fvtt-`.

**Comment by mkahvi** [comment]
It's easy to copy the styling over, or use CSS variables for unified style, which I feel is better than unscoped style rules.

**Comment by aaclayton** [comment]
I don't think we are going to start a convention of namespacing all of our own classes with `fvtt-`. I realize there are some arguable advantages of that, but I think it's too much of a headwind. We are defining the landscape of the core software upon which the module ecosystem is based. For our classes to be non-namespaced is appropriate.

**Comment by arcanistzed** [comment]
That makes a lot of sense indeed. #6482 is probably a better approach than this issue anyway.

**Comment by aaclayton** [comment]
Closing as wontfix.
