### ISSUE TITLE
After reload. Wall don't block movement.

### ISSUE THREAD

**Issue by sanguaire** [foundryvtt/foundryvtt#8139]
### What happened?

When I reload the scene the first movement with the arrow key is not blocked by a wall.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Place a token on the scene
2. Place a wall in front of the token
3. Reload foundry
4. Try to move the token in the wall direction

![image](https://user-images.githubusercontent.com/10399481/189093849-8efe5915-f89e-446e-96d4-14e0aeb227dc.png)
after arrow up
![image](https://user-images.githubusercontent.com/10399481/189094045-00e7e68e-7b87-44d8-9741-11ad6a057d3c.png)

### What core version are you reporting this for?

Version 10 (build 284)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Might be the same issue as #8123

**Comment by aaclayton** [comment]
Confident this is the same issue as #8123 closing as duplicate.
