### ISSUE TITLE
Reduce difference between 0 and lower color intensities of Natural Light coloration

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8152]
### User Experience

The difference between 0 and 0.05 color intensity when using Adaptive Luminance coloration is unsurprising and acceptable in my opinion:
![Adaptive Luminance, 0 color intensity](https://user-images.githubusercontent.com/106829671/189196358-8ce5f926-2f75-417e-9f11-53fe481a42dc.png)
![Adaptive Luminance, 0.05 color intensity](https://user-images.githubusercontent.com/106829671/189196361-7581c7d7-f42b-4135-bb1d-3f86fa5f35d9.png)

When using Natural Light, however, the difference is comparatively extreme:
![Natural Light, 0 color intensity](https://user-images.githubusercontent.com/106829671/189196352-c0fde168-2799-42c1-bb12-063c9e04c8f9.png)
![Natural Light, 0.05 color intensity](https://user-images.githubusercontent.com/106829671/189196360-f72bd40b-9a6e-43ca-9e37-d9c89a71c83f.png)

Could this degree of difference be greatly reduced so as to open up finer gradations between no and minimal color intensity when using Natural Light?

**Comment by Feu-Secret** [comment]
I'll take a look. Something could be improved, definitely.

**Comment by Feu-Secret** [comment]
I have found a way to take into account the `Color Intensity` for the `Natural Light` coloration technique. The multiplicative strength of the light is directly linked to the color intensity. It will allow to have a wider nuance of natural lighting.
