### ISSUE TITLE
Randomize Wildcard Images for Tokens Not Working in V10.284

### ISSUE THREAD

**Issue by nremmer** [foundryvtt/foundryvtt#8165]
In Prototype Token/Appearance if you select a wildcard file path for "Image Path" (e.g. "/somepath/image*") and check the Randamize Wildcard Images and press "Update Token" everything saves like it should. But when you drag the associated actor on to the canvas you will always get the first image in the list of images that matches the wildcard. There is not randomization, just the same image every time.

**Comment by aaclayton** [comment]
@nremmer the team and I were not able to reproduce this issue. If you can share an exact token configuration that produces the problem and confirm that it occurs on our latest release without any modules enabled we can re-open and investigate further.
