### ISSUE TITLE
Attempt to address a rare situation in which the server does not properly initialize a user session, causing the user to get stuck at a grey screen when loading the world.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8168]
## Anecdotal observations
- Seems to happen when the server has been running for a long time
- Seems to happen with the user has a client-side session cookie stored which may no longer exist in the server session store
- Console reports that session restoration is attempted, but nothing ever reports back
- Hard to debug, no known repro path currently available

**Comment by Tommycore** [comment]
The one time I encountered it I had previously put my PC into sleep mode while Foundry was running. That wasn't the first time I had Foundry running, activated sleep mode, woke the PC and continued using Foundry. But it was the first time I've done that and had the bug appearing.

**Comment by aaclayton** [comment]
I have implemented a candidate fix, although given the difficulty of reproducing this issue I cannot guarantee that it will work for all situations. This is one to continue to monitor.
