### ISSUE TITLE
Wide form elements inside the settings dialog can cause the entire tab to wrap onto the line below the sidebar

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8175]
From https://discord.com/channels/170995199584108546/956306859491471420/1017806904644354048

when you change font size to 6 or above in the core settings. it doesnt render properly and moves all the text to below where you expect it.  it goes below and defeats the purpose of the new menu style.

![](https://media.discordapp.net/attachments/956306859491471420/1017806903914541157/unknown.png)

**Comment by cs96and** [comment]
I also see this problem with the Chat Portrait module at font size 5.
![image](https://user-images.githubusercontent.com/898086/192519690-1b254053-77de-45ed-b43f-f3be1943845d.png)

**Comment by cs96and** [comment]
Did you try the chat portrait module?
