### ISSUE TITLE
Moving nested folders into a nested folder can cause deeper nested folders beyond the third to become inaccessible

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8178]
From https://discord.com/channels/170995199584108546/956306859491471420/1017906519171411978

1) Create 4 folders, "Test 1", "Test 2", "Test 3", and "Test 4"
2) Place "Test 2" inside "Test 1"
3) Place "Test 4" inside "Test 3"
4) Place "Test 3" inside "Test 2", which is inside of "Test 1"
5) "Test 4", which is now 4 levels deep, is inaccessible.

**Comment by aaclayton** [comment]
Somewhat related to https://github.com/foundryvtt/foundryvtt/issues/8107
