### ISSUE TITLE
Add missing V10 data model migrations for Item or Active Effect overrides within unlinked Token data.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8180]
From https://discord.com/channels/170995199584108546/956306859491471420/1018193294573981696

Foundry 9.280
- Create a new world (DnD5e 1.63 (v9))
- Create an unlinked actor and create an embedded item
- Create a token for that actor
- Alter the item to contain none-default values causing it's data to be saved into scenes.db
- Close the world

Foundry 10.285
- Start and upgrade the v9 world
- Open the token actor
- Observe default item values instead of changes made above

Note: scenes.db contains 'data' for the unlinked actors item data instead of 'system'. Changing that causes the data to show up again.
Note: I think this worked on 10.284, but I'm not certain.

![](https://media.discordapp.net/attachments/956306859491471420/1018193294112587887/v9_to_10.285_migration_-_marked.png?width=959&height=410)

**Comment by Scepfari** [comment]
additional note: 

The error does not occur when migrating from 9.280 to 10.284. 
If you do not change the corresponding token and then migrate to 10.285, it behaves like the direct migration from 9.280 to 10.285 and all items of the token actor contain only default values. 
If you change a item of the token actor in 10.284 then the migration to 10.285 works without errors.

**Comment by stwlam** [comment]
Possibly persists? https://discord.com/channels/880968862240239708/880969253765935174/1022578677751492722
