### ISSUE TITLE
FoW is sometimes not revealed according to token sight

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8181]
From https://discord.com/channels/170995199584108546/956306859491471420/1018308797669847111

Using vision animation (default) may make this happen more often, but is can also happen without vision animation. This does not mean that the "in between" steps are missing in FoW (they are), but that even the end-steps (token not moving) are missing once the token moves elsewhere. Sometimes a browser reload fixes this (for some time?) and then another reload makes it happen again. Happens in 284 and 285.
Simple steps to reproduce the bug: Create a scene with limited angle of view through windows/holes, try multiple in different places. Move token straight in front of it to get a vision polygon straight out. Move token elsewhere to see that FoW is not revealed according to the former field of view.
Screenshots and/or console errors: Image 1 shows token line of sight. Image 2 shows token being moved one step to the left and FoW not being revealed according to former token sight polygon. 

![](https://media.discordapp.net/attachments/956306859491471420/1018308797225238549/unknown.png)
![](https://media.discordapp.net/attachments/956306859491471420/1018308797460123709/unknown.png)

**Comment by aaclayton** [comment]
This is almost certainly related to debounced and throttled fog of war persistence. There are some limitations of that approach but it's important that we not try and persist fog every sight frame. This will become better in V11 once we use geometry unionization for fog polygons.
