### ISSUE TITLE
_canDragDrop is not being correctly checked before binding drop listeners in Applications

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8194]
`Application#_createDragDropHandlers` supplies the `permissions` object as:

```js
d.permissions = {
	dragstart: this._canDragStart.bind(this),
	drop: this._canDragDrop.bind(this)
};
```

But `DragDrop#bind` checks for `this.can("dragdrop", this.dropSelector)` rather than `this.can("drop", this.dropSelector)`.

**Comment by aaclayton** [comment]
Pushing to V11 due to lack of urgency and breaking nature of the fix.
