### ISSUE TITLE
Updating deprecated fields of an actor throws an error in some circumstances

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8201]
Originally reported by neck#0001 https://discord.com/channels/170995199584108546/956306859491471420/1019591494954393690

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux, Proton  
**Short Description of bug:** Updating an actor's `img` and `prototypeToken.name` values without updating the `prototypeToken.texture` value results in an error.  
**Simple steps to reproduce the bug:** `game.actors.get([ID]).update({img: "test.png", "prototypeToken.name": "test"})`  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/190625664-2ff9fddd-9d39-4500-969e-959d4ce06f9e.png)

**Comment by aaclayton** [comment]
I'm not sure we should do anything about this. It's a transitory problem that will happen during the v9->v10 transition in rare cases where an update operation is simultaneously expressing it's update using two different "languages". 

Part of the update is expressed in "v10 language" with v10-specific terms like `prototypeToken`, while the other part of the update is expressed in "v9 language" with v9-specific terms like `img`. 

Our compatibility and shims system will gracefully support update expressions in *either* "v9 language" OR "v10 language", but an update expression that mixes languages is not gracefully supported. Perhaps it would be easy for it to be by switching some areas where we do specific migrations to instead do merges instead, but I think that opens the door for other undesirable bugs.

Unless @Fyorl has a different view or an idea of a way to solve this gracefully, I vote for `wontfix`.

**Comment by Fyorl** [comment]
Duplicate of #8241
