### ISSUE TITLE
Holding alt while switching away from a layer leaves selection boxes around placeables visible

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8205]
Originally reported by Geekswordsman#3085 https://discord.com/channels/170995199584108546/956306859491471420/1019975396659314769

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Ubuntu 20.04, Node.js, Firefox/Edge  
**Short Description of bug:** Holding alt while switching layers fropm the tile layer to any other layer leaves the box highlight for the tiles visible  
**Simple steps to reproduce the bug:**  
Swap to a layer with tiles.  
Hold alt, which will highlight all tiles.  
Swap to another layer  
Release alt.  
Tiles still have their red border.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/190629982-a26740cf-2199-41ef-bcf4-9041f958b243.png)

**Comment by aaclayton** [comment]
Presumably this applies to the Token or Drawing layer as well which use the same object highlighting workflow? A fix should address all cases to ensure that highlighting is disabled when the layer is deactivated.
