### ISSUE TITLE
Map notes with no associated journal entry can be moved by players who lack 'create map note' permission

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8207]
Originally reported by damccull#7422 https://discord.com/channels/170995199584108546/956306859491471420/1019999857521479690

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Ubuntu 20.04  
**Short Description of bug:** When map notes are directly created by GM without corresponding Journal Entries, Player role users can edit them and drag them around even when Player role does not have Map Notes permission.  
**Simple steps to reproduce the bug:** As a GM, create a Map Note using the "Create Map Note" tool but do not provide a linked journal entry. Log in as a Player and drag it around and edit it.

**Comment by Fyorl** [comment]
Not sure if this is a bug or 'working as designed'. I can't recall the v9 behaviour or if journal-less notes were permitted before at all.

**Comment by aaclayton** [comment]
Is this related to the drag permissions issue in #8194?
