### ISSUE TITLE
V10 doesn't support # in filenames anymore

### ISSUE THREAD

**Issue by SvenWerlen** [foundryvtt/foundryvtt#8222]
### What happened?

Version 10+ doesn't support images which have a `#` character in their filename.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Upload an image `test#.svg`
2) Use FilePicker to browse
3) Notice that the preview/thumbnail doesn't show up for that file
4) Select the image as icon for a macro
5) The image is broken

HTTP response is 404 for that file.

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Was this formerly supported in V9?

**Comment by esheyw** [comment]
https://i.imgur.com/OyiYxLs.png works on 9.280, yes

**Comment by SvenWerlen** [comment]
_Note : it's not a blocking issue._ 
Moulinette Game Icons used to generate file name with `#`. I changed it in V10 to avoid this special case.
I reported it because existing paths with `#` are broken in V10.
