### ISSUE TITLE
Broken links which do not otherwise define a text label should say something like "Unknown" rather than "null".

### ISSUE THREAD

**Issue by djinnstar** [foundryvtt/foundryvtt#8235]
### User Experience

When a link breaks on a journal sheet, you get an inline element that says ‘null’- not very useful information when a link breaks. It would be more helpful to the user if a link stored its original name and displayed that name when the link breaks.

**Comment by aaclayton** [comment]
Can you share an example of what you mean? I agree we can do better than displaying "null", but that would only happen if the link does not include a label (which ours do by default).

For example, if you linked as `@UUID[JournalEntry.Q2Ugx1bL0kbKlRXR.JournalEntryPage.DgKfcMseZCzmxqg8]{The Page Title}` - if this link were to become broken it would still display "The Page Title" with the broken link icon. 

If the label were removed, however, and your link was `@UUID[JournalEntry.Q2Ugx1bL0kbKlRXR.JournalEntryPage.DgKfcMseZCzmxqg8]`, the label information would be absent and the framework would not know what to display. 

I agree it should not say "null" but rather something like "Unknown".

**Comment by djinnstar** [comment]
My mistake - I needed to disable a module! This works already.
