### ISSUE TITLE
Add the ability to configure the default sheet for a document type without opening a document of that type.

### ISSUE THREAD

**Issue by zeel01** [foundryvtt/foundryvtt#8238]
### User Experience

Some users struggle with the process of assigning the default document sheet, as they don't realize that this is done by opening the sheet config from an already open sheet. I've coached a number of users on doing this with Actor sheets and Card sheets. They know how to change the sheet for a given document, but often don't realize the second option exists, and if they do know that a "default" is a thing, they don't realize where they will find it.

Additionally, it is possible to get into a semi-unrecoverable state where the selected default sheet for a document is not valid - [such as a sheet intended for documents created by a particular module that shouldn't be used for normal documents](https://github.com/foundryvtt/foundryvtt/issues/7401). If this sheet can't render, it can make it difficult to fix without disabling a module, reloading Foundry, opening the sheet config and saving it, then re-enabling the module (many users probably won't figure this out on their own, and will have to ask for help).

It would therefore be useful if it were possible to access the document sheet config dialog from outside of a document sheet. A button in the directory on each tab would work well. It could open a sheet that displays a select box for every subtype of document available, with which the user can configure the default sheet for each of those document subtypes. For instance, on the Cards tab you would click a little cog icon, and a dialog with four select boxes would appear: One each for Card, Deck, Pile, and Hand. More selects would appear for system-defined subtypes. For documents with embedded documents, those would appear too - Card for the cards tab, each page type in the Journal tab.

This makes it intuitively easy to configure default sheets, and to correct invalid default sheet configurations without disabling and enabling modules.

**Comment by Fyorl** [comment]
I think we can do this as part of #7521
