### ISSUE TITLE
Bottom-align the Players window with the Macro hotbar

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8240]
### User Experience

Literally unplayable — the Players app and the Macro hotbar are two pixels out of bottom alignment.

![Screen Shot 2022-09-20 at 10 54 30 AM](https://user-images.githubusercontent.com/801582/191331163-1b0152af-8873-42ed-bae6-aebae5f7f40d.png)

**Comment by aaclayton** [comment]
This was an intentional design decision we made after careful internal consideration, we did it this way to drive you insane. You're welcome.

**Comment by AlanDNelson** [comment]
I can't unsee it now... thank you!
