### ISSUE TITLE
Provide a more graduated series of compatibility warning colours on the systems/modules pages.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8244]
### User Experience

Right now, the styling for a warning that a module/system:
- is a major version out of date
- has unknown compatibily
- is listed as verified to one patch version ago

all display the same styling, for wildly varying levels of 'this very well might not work' to be conveyed to the user. 

I know using colour alone is generally frowned upon in UI design, but being able to say 'Oh, that's a yellow warning, it was updated a day before the last patch I'm sure its fine' or 'Red means it's not even claiming compatibility with this major version' would, I think, reduce user confusion.

**Comment by esheyw** [comment]
That's fair; I have never personally encountered red because I started on v9, and didn't try to migrate to v10, fresh installs of everything. I got a little lost in the weeds in the OP; the major point I want to hit is that off-by-a-minor-version warnings should be *much* less prominent than the others, IMO. The current behaviour, again IMO, incentivizes people to set `"verified": 10` to not have to push a new manifest with every foundry patch if they don't want their module to give users warnings, and that seems anithetical to the purpose of that flag.

**Comment by farling42** [comment]
It is already impossible for the 5% of red-green colour deficiency people to tell the difference between the existing red and yellow. Adding an "orange" which is between the two existing chosen RGB values won't help us identify any differences at all.

**Comment by aaclayton** [comment]
Merging with #8576 as duplicate.
