### ISSUE TITLE
Paragraph style rules can cause them to overlap under some circumstances

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8246]
Originally reported by HYBRiS#7351 https://discord.com/channels/170995199584108546/956306859491471420/1021839362503229440

**ALL MODULES DISABLED?** false (it relies on the default style.css)  
**OS, Hosting, Browser (if applicable):** Tested both Chrome and Firefox. Same issue  
**Short Description of bug:** The default CSS for the journal editor seems to mess up layout of paragraphs, with "min-height: 1rem;" (from style.css: row 365) garbling all parapraphs together if there are more than can be viewed without scrolling. Disabling that css rule fixes the issue, and it only happens while editing. Looks fine outside the editor.  
**Simple steps to reproduce the bug:** Fill a journal with several paragraphs and more text than can fit one window.  
**Screenshots and/or console errors:**

```css
p {
  min-height: 1rem;
}
```

![image](https://user-images.githubusercontent.com/207433/191492013-ef7aaf7e-92e1-457d-b40b-1fc7ac3a87c9.png)

**Comment by Fyorl** [comment]
Additional information from Mana#4176 https://discord.com/channels/170995199584108546/956307084931112960/1021869439760728124

> The bug reported by HYBRiS is not limited to journals. It's any case of <p> element use pretty much anywhere.

**Comment by mkahvi** [comment]
Here's demonstration of it outside of journals:  
![Screenshot 2022-09-29 011331](https://user-images.githubusercontent.com/8120158/192898202-4781b2be-d41f-4885-bbe5-6675bab80305.png)

Applying `min-height:unset` style to the `<p>` element fixes it here.

Seems to happen any time the `<p>` element needs to wrap.

**Comment by Fyorl** [comment]
I'm still not able to reproduce this. Here you can see I've added a wrapping `<p>` element above a `<div>` and it does not overlap the content below it.

![Image](https://user-images.githubusercontent.com/207433/193021566-bccce81c-0133-451e-a2ab-1d431602219f.png)

And I've added the `hint` class here to match your example.

![Image](https://user-images.githubusercontent.com/207433/193021839-f177ca66-c449-4d09-997f-559ed708f253.png)

![Image](https://user-images.githubusercontent.com/207433/193022086-28bc3274-812a-49e8-9b5c-76090cae9687.png)

Are you able to rule out the possibility that this is caused by an interaction with system styles?

**Comment by mkahvi** [comment]
No system styles, only my own. And it seems to happen in my case if the container for the `<p>` is a flexbox.  That seems like it shouldn't be relevant with journals.

**Comment by Fyorl** [comment]
The broad selector is due to the fact that content created with the rich-text editor may appear in lots of different places (the chat log, actor and item sheets, etc.).

**Comment by mkahvi** [comment]
> The broad selector is due to the fact that content created with the rich-text editor may appear in lots of different places (the chat log, actor and item sheets, etc.).

Shouldn't that mean it should be limited to the editor instead of global if it's meant to fix editor styling?

**Comment by Fyorl** [comment]
No, because when that content is displayed outside of the editor, it still needs to be appropriately styled.

**Comment by mkahvi** [comment]
Wouldn't that then be up to whoever displays it? The min-height obviously is not working for everyone, and it seems to be unnecessary as removal of it doesn't seem to break anything, only fixes things (at least I'm not seeing any editor content breaking from it).

**Comment by Fyorl** [comment]
If you edit some content in ProseMirror (a journal page, actor biography, item description, etc.) and add blank lines, these will collapse to nothing without this rule.

> Wouldn't that then be up to whoever displays it?

Yes, and the core application is doing the displaying by default. We provide default stylings for all parts of rich-text editor content: headings, blockquotes, code blocks, secret blocks, tables, and these are all also top-level selectors.

**Comment by mkahvi** [comment]
> If you edit some content in ProseMirror (a journal page, actor biography, item description, etc.) and add blank lines, these will collapse to nothing without this rule.

Not seeing it. Tested with dnd5e with 0 modules:  
![Screenshot 2022-10-06 203049](https://user-images.githubusercontent.com/8120158/194380055-07b03da8-4a17-45b3-a30b-01f18f6aa9ac.png)

**Comment by Fyorl** [comment]
They need to be blank lines, all those lines have content. I've attached a video demonstrating the behaviour if this rule is disabled.

https://user-images.githubusercontent.com/207433/194382162-53f5b9a3-0a99-4631-ae0d-77eeace6249a.mp4

**Comment by mkahvi** [comment]
Oh.. Well, tested that outside of Foundry, and that collapsing behaviour with empty `<p>` happens there as well, so... why does this need to be different in Foundry?

**Comment by Fyorl** [comment]
So that blank lines added in foundry's editor can be preserved when viewing the content outside of the editor. There are other solutions to this (within ProseMirror itself) but the CSS solution was deemed the simplest at the time. As I mentioned before, we change a number of default stylings at the top-level for the sake of editor content formatting and this is no different.

**Comment by mkahvi** [comment]
Well, in that case I'll retain my hope that such stylings will be changed to be restricted to editor content if it's meant to fix editor content.

I'll just apply stylings on my end to counter it breaking everything else until then.

**Comment by Fyorl** [comment]
Closing as nonrepro.

**Comment by mkahvi** [comment]
Here's a repro:
```js
new Dialog({content:"<form class='flexcol' style='height:100%;overflow:hidden;'><p style='flex:0;'>Hee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee bee</p><ul style='overflow:scroll'><li>stuff</li><li>stuff</li><li>stuff</li><li>stuff</li><li>stuff</li></ul><div><button>Button</button></div></form>", buttons:{}}, {resizable:true}).render(true)
```
Adjust width of the dialog until the `<p>` contents start wrapping (with three lines it becomes painfully obvious).

It immediately fixes itself if you disable the min-height rule.

**Comment by Fyorl** [comment]
> I thought this was fairly obvious from the stuff provided earlier, but I guess explicit code example was needed?

You can see from [this](https://github.com/foundryvtt/foundryvtt/issues/8246#issuecomment-1262160304) comment that I am not able to reproduce this with any of the information given.

Using your code snippet, I am still unable to reproduce this:

![image](https://user-images.githubusercontent.com/207433/200933227-022007c8-ba1f-4dbf-97b6-425643f5ff8b.png)

**Comment by Fyorl** [comment]
Sorry, my mistake for not reading your comment carefully enough. I am able to reproduce this now. It looks like a flexbox-specific issue where elements inherit their `flex-basis` from the `min-height`. Explicitly setting the `flex-basis` to `auto` works to resolve it in these cases, though we can look for alternative solutions.
