### ISSUE TITLE
[Journal] Option to insert a link without the default text

### ISSUE THREAD

**Issue by DarKDinDoN** [foundryvtt/foundryvtt#8252]
### User Experience

**Context:**
Using ProseMirror, we can insert a link to a document by drag'n dropping said document directly into the editor content.

It's working great, and the default format looks like this: `@UUID[Actor.J6DsBsBEMLNGL8Hv]{Actor Name}`

By default, it also inserts the title of the document between brackets (e.g: `{Actor Name}`). This is ok, this tells the user he can actually change the name of the link without breaking the link.

**The issue is:**
By inserting a default text, it overrides the title of the document shown in the link. Meaning, if I later change the title of that document, it won't change the link title.

Instead, if I use this format `@UUID[Actor.J6DsBsBEMLNGL8Hv]` (without the default text between brackets), changing the title of that document later on will change the link title as well.
 
**Feature request:**
Having a way to not insert a default text when drag'n dropping a document. Whether by holding a key while doing so, or changing a default option.
Removing the default text after inserting a link is tedious.
Also, I bet that the most common use case is not to override the default document title, as most users probably want the link title to reflect the document title, even if the document title changes the link creation.

**Comment by DarKDinDoN** [comment]
Thx for taking the time to explain this.
I guess you are right. Although, it feels more like "the least bad" solution regarding this issue.

**Comment by aaclayton** [comment]
I can agree with that, but sometimes the "least bad" is the best you can do!
