### ISSUE TITLE
canvas.walls.checkCollision should error if no type is being passed in v10

### ISSUE THREAD

**Issue by manuelVo** [foundryvtt/foundryvtt#8257]
### User Experience

When calling `canvas.walls.checkCollision` with no explicit type set, all walls end up being ignored and an empty array is always returned. This is usually never desired by the caller of the function. Since this behavior differs from the v9 behavior, so I suggest raising an error instead to make developers aware that they now have to explicitly pass in a type.

**Comment by Feu-Secret** [comment]
@aaclayton I propose to just add documentation. I think this part of the code is critical enough to avoid adding *stuff* in it.

**Comment by dev7355608** [comment]
`type` should default to `"move"`. That's what it did in v9. Any other behavior would be an unnecessary breaking change.
