### ISSUE TITLE
`CompendiumCollection#getIndex` does not add v10 shims to the returned index when an unmigrated pack is queried

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#8258]
### What happened?

I've discovered this today after a user reported that compendium contents were missing from the PF2e Compendium Browser.
The Browser relies on a custom index that is built when a tab is activated. Naturally we've updated those index fileds for v10 to use the `system` property. 
When the Browser requests the index of an unmigrated pack however (for example from a newly installed module that wasn't yet updated to v10) the index will contain no `system` values.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Install PF2e System
- Install PF2e Playtest Data Module
```js
const pack = game.packs.get("pf2e-playtest-data.rage-of-elements-playtest-actions");
const index = await pack.getIndex({ fields: ["system.actionType.value"] });
```
The index will only contain the base fields.

### What core version are you reporting this for?

Version 10 Stable (build 289)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by In3luki** [comment]
Related #7944

We could force migrate non-system packs on load, but I don't know if that would be the best solution to this problem.

**Comment by aaclayton** [comment]
This is not an issue that can be fixed with shims. The source data in the compendium pack has the incorrect fields. We query the index by asking for specific fields which do not exist. I'm afraid this is simply an issue where modules need to migrate their packs and release v10-compatible versions.
