### ISSUE TITLE
`CanvasDocumentMixin#object` fails to return the correct object in the case of preview objects and instead creates a new one

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8259]
### What happened?

Instead of returning the preview placeable object `CanvasDocumentMixin#object` creates a new placeable and places it into the `placeables`.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
previewDocument = new TokenDocument(_token.document.toObject(false), { parent: canvas.scene });
previewObject = new Token(previewDocument);
console.log(previewDocument._object); // null
console.log(previewDocument.object === previewObject); // false
console.log(canvas.tokens.placeables.includes(previewDocument.object)); // true
```

### What core version are you reporting this for?

Version 10 Stable 3 (build 286)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I will have to check, this may be intended. For example when drag-and-drop moving a Token we leave the original mesh in place and create a new mesh to use as the preview.

**Comment by JDCalvert** [comment]
If this is the case, then I think some clean-up needs to happen when the

**Comment by dev7355608** [comment]
My initial repro steps demonstrated how the preview object is constructed and that `previewDocument.object` creates another Token instance. But the consequences of this behavior may have not been immediately obvious.

Execute:
```js
Hooks.on("refreshToken", token => token.document.object)
```
Drag a token: each drag a new Token is added to `canvas.tokens.placeables`. Switch scene: canvas breaks.
```
foundry.js:747 TypeError: Cannot read properties of null (reading 'refCount')
[No packages detected]
    at z.destroy (SmoothShader.ts:4:1)
    at Token5e._destroy (foundry.js:45506:17)
    at Token5e.destroy (foundry.js:24971:10)
    at e.destroy (display.min.mjs:8:21346)
    at foundry.js:30131:42
    at Array.forEach (<anonymous>)
    at TokenLayer._tearDown (foundry.js:30131:27)
    at TokenLayer._tearDown (foundry.js:30604:18)
    at TokenLayer._tearDown (foundry.js:36628:18)
    at TokenLayer.tearDown (foundry.js:30119:16)
    at TokenLayer.draw (foundry.js:30094:16)
    at InterfaceCanvasGroup.draw (foundry.js:25925:21)
    at async InterfaceCanvasGroup.draw (foundry.js:38800:5)
    at async Canvas.draw (foundry.js:23509:11)
    at async Scene.view (foundry.js:20754:7)
foundry.js:30626 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'visible')
[No packages detected]
    at TokenLayer._activate (foundry.js:30626:26)
    at TokenLayer._activate (foundry.js:36635:11)
    at TokenLayer.activate (foundry.js:30197:10)
    at #initializeCanvasLayer (foundry.js:23682:11)
    at #initialize (foundry.js:23632:32)
    at Canvas.draw (foundry.js:23525:29)
    at async Scene.view (foundry.js:20754:7)
```

**Comment by aaclayton** [comment]
I'll add this to our ongoing V10 maintenance milestone to evaluate, but I don't know right now what the right path forward here is. There might be something small we can do within the scope of V10 stable maintenance to improve things, although probably a full solution would require a more overarching review of how we handle placeable object previews.

**Comment by aaclayton** [comment]
I have *partially* addressed this issue by improving the behavior of the `PlaceableObject#clone` method which is the correct API that a developer should use for this type of workflow - and is the API used by the drag preview workflow.

Since `CanvasDocument#object` is singular, it is not necessarily correct to have the constructor `new Token()` or `new TokenDocument()` automatically designate the linked object.

The recommended usage (which will be supported in our next update) would be:

```js
const previewObject = _token.clone();  // Token
const previewDocument = previewObject.document; // TokenDocument
previewDocument.object === previewObject; // true
canvas.tokens.placeables.includes(previewObject); // false
```

Hopefully this resolves your concern, at least until better data structures can be developed in a future major version.
