### ISSUE TITLE
Consider removing the restriction which requries Adventure compendium packs to declare a specific system.

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#8262]
### User Experience

Hi.

The  Adventure Compendium is great tool. But, there is a big limitation. You need to set a system. I understand this is useful for Actor/Items and other system related entities. But, this prevents the user from create generic adventure compendiums (jornals, scene, playlists etc).

Can you please add the remove this restriction?

You could make this error go away if the adventure pack don't have any system entities.
![image](https://user-images.githubusercontent.com/4999783/192037915-d1235f7a-b8db-4acf-a828-9c3df62d73d6.png)

This feature is very special. Compendium Folders module is mandatory, but this feature could free lots of users from use Compendium Folders.

**Comment by aaclayton** [comment]
I agree we should think about this more.

**Comment by dinotheextinct** [comment]
I would also like to see this feature. And maybe make it possible to use those adventures compendiums in different worlds.

**Comment by alexdiste** [comment]
correct If I am wrong but part of benefits of objecting programming is that you can create a very basic object and then extend how many times you want. So why are actors strictly related to a system? There is a common definition and then each system extends the common definition using his property so if an actor create for example in Dnd5e is opened in pathfinder could have some attribute not valued, but the ones with same name instead could be found.
For example I am creating my personal system and I reuse str,dex,int,ac as attribute of my actor object. So If I get an actor form 5e and open with my sistem at least str, dex, int and ac are valued. So why keep actor and items to be strictly related to systems when also different systems could have common variables? 

Maybe an alert telling your actor could not have all data needed is okay but why an hard stop?

I am thinking that for example Dnd5e, Pf1, pf2 all share ac, initiative and other variable so there is a certain percentage of reusability. So why lock that?

For example prior to starting create my own system I used SWB as based. I create my items as ITEM of SWB, then in my template.json I definied again Item type for item and I reused all items created in SWB in my systems. Then I change type from item to right item type in my system but at least first import I can reuse all SWB items (and actors) into a different systems.

**Comment by Fyorl** [comment]
We have relaxed this constraint on Adventure compendia. They will be (as of the next release) no longer required to specify a `system` in their metadata. If they do not specify a system, Actors and Items will not be able to be stored in the Adventure document, and they similarly will not be able to be imported into worlds from the Adventure document.

Adventure compendia that do specify a system have no restriction on document types, as before.
