### ISSUE TITLE
In the Adventure Exporter UI display documents in yellow which have different data from what exists within the current world.

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#8263]
### User Experience

Drop an entity on Adventure Builder make it green to add, red to remove.

Can you make yellow to identify an update? If you drop an updated world entity in the Adventure Builder it'll not identify about an update.

**Comment by brunocalado** [comment]
https://user-images.githubusercontent.com/4999783/192039836-39defca8-203f-46a5-b61d-cc07e1665fe8.mp4

**Comment by aaclayton** [comment]
Duplicate issue, completed in V11.
