### ISSUE TITLE
Only allow players to PingCombatant on tokens visible to them on the canvas

### ISSUE THREAD

**Issue by Nazacra** [foundryvtt/foundryvtt#8265]
### User Experience

Summary: As a DM I don't want players to be able to use Ping Combatant on tokens which they shouldn't be able to see otherwise.

The current implementation of `_onPingCombatant` only checks if the selected combatant is on the same scene. This means that as long as the target is visible in the combat tracker players can get a ping of where it is on the map. This isn't ideal because it can give players exact positioning knowledge of creatures they can't see (including possibly invisible tokens, if the DM doesn't hide them from the combat tracker). In an ideal world players wouldn't use and/or abuse this, but the temptation will always be there.

My suggestion is to add some extra requirements for a player to be able to use the Ping Combatant feature. These could all be implemented as options if they are all technically feasible (and I believe should be options because I could see different tables ruling different on this):

1. Only allow PingCombatant on tokens visible on your canvas (i.e. everything visible to any token you have "Observer" on)
2. Only allow PingCombatant on tokens in your currently selected token's line of sight
3. Only allow PingCombatant on tokens which you have "Observer" permission on
4. Existing behaviour

I have implemented option 3 for myself in a monkey patch of `foundry.js`, but obviously that will disappear on any game updates as it is in the core .js files. I would much prefer to have option 1 available longer term.

For everyone's benefit, the patch I made is (in file `foundry/resources/app/public/scripts/foundry.js`):
```diff
  async _onPingCombatant(combatant) {
-    if ( !canvas.ready || (combatant.sceneId !== canvas.scene.id)) return;
+    if ( !canvas.ready || (combatant.sceneId !== canvas.scene.id) || (!combatant.actor?.testUserPermission(game.user, "OBSERVER"))) return;
    await canvas.ping(combatant.token.object.center);
  }
```

**Comment by aaclayton** [comment]
Good suggestions, I think it probably makes sense to only be able to ping combatants whose tokens which are detected (not hidden and within LOS).
