### ISSUE TITLE
Adding new users to a world appears to require a restart of server before they can log in

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8270]
Have butted up against this a few times and it seems to be somewhat tricky to diagnose. I have had this happen 2 in 5 user accounts created on a remote server I host.

**Host info:** 
ubuntu 22.04 
NodeJS with SSL
No reverse proxy or other software

Reproduction steps:

- Add one or more users through user management, save changes to return to the world
- Have someone attempt to login through newly created user account

The new users are partially able to login--the login check passes, but they end up 'grey screened' as if the websocket fails to connect, though no errors appear in console. The login simply seems to stall. 

restarting the server allows the new users to login without issue.

**Comment by aaclayton** [comment]
Interesting, sounds related to https://github.com/foundryvtt/foundryvtt/issues/8168

**Comment by Fyorl** [comment]
Not able to reproduce this currently.
