### ISSUE TITLE
Flags injected into the Ambient Light and Token config are not saved

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8271]
### What happened?

A flag injected into the Ambient Light and Token config is not saved if the flag doesn't exist on the document yet. The flag appears to have been saved successfully, but a reload reveals that it wasn't. This issue seems to be limited to the Token and Ambient Light config.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Use the snippets below to inject the flag into the config, create a new token / ambient light, set the flag value in the config and save. Reload.

```js
Hooks.on("renderAmbientLightConfig", sheet => {
    sheet.form
        .querySelector(`.tab[data-tab="advanced"]`)
        .insertAdjacentHTML("beforeend", `\
            <div class="form-group slim">
                <label>Priority</label>
                <div class="form-fields">
                    <input type="number" name="flags.core.priority" value="${sheet.object.getFlag("core", "priority") ?? ""}">
                </div>
            </div>`);
});

Hooks.on("renderTokenConfig", sheet => {
    sheet.form
        .querySelector(`input[name="alpha"]`)
        .closest(".form-group")
        .insertAdjacentHTML("afterend", `\
            <div class="form-group slim">
                <label>Occlusion Radius</label>
                <div class="form-fields">
                    <input type="number" name="flags.core.occlusionRadius" value="${sheet.object.getFlag("core", "occlusionRadius") ?? ""}">
                </div>
            </div>`);
});
```

### What core version are you reporting this for?

Version 10 Stable 3 (build 286)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
If this is specific to token and light sheets, it must have something to do with the way that we do real-time preview of the sheet configuration.
