### ISSUE TITLE
I can't roll as GM but players can

### ISSUE THREAD

**Issue by Kielhaul** [foundryvtt/foundryvtt#8272]
### What happened?

After update 10. I cannot roll any dice, but everything else works fine for me. All my players can use everything and roll just fine.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

![image](https://user-images.githubusercontent.com/114365071/192166335-07cb7dbd-dd3f-4432-a80c-8148d85f10e1.png)

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Are you using the native application or a browser?

**Comment by Kielhaul** [comment]
Yes it's saying I'm using an older electron client. When I update as
administrator why doesn't it update the client?

**Comment by aaclayton** [comment]
An unfortunate limitation of our in-app updater is that it can only update the internal code of the application, not the outer Electron application itself. This is something we would like to improve in the future. For now you'll want to uninstall/reinstall the software to get a more modern Electron version.

**Comment by Kielhaul** [comment]
Thank you for the clarification.

**Comment by Kielhaul** [comment]
I'm using the native application
