### ISSUE TITLE
Support block-level anchor tags which wrap around an image element in the ProseMirror schema.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8275]
Originally reported by MrPrimate#8701 https://discord.com/channels/170995199584108546/956306859491471420/1022431116222804009

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Linux, Firefox, local  
**Short Description of bug:** `<a>` links are removed if not text inside, this includes if there is just an `img` in that link  
**Simple steps to reproduce the bug:**
Switch to html editing mode in a new page, and enter:
```html
<p>
  <a href="assets/01-005.shield-bremen.png">
    <img src="assets/01-005.shield-bremen.png"/>
  </a>
</p>
```
When it saves it leaves only:
```html
<p>
</p>
```
If however the link and img are outside a <p> tag then it leaves the img, but strips the link:
```html
<a href="assets/01-005.shield-bremen.png">
    <img src="assets/01-005.shield-bremen.png"/>
  </a>
```
becomes:
```html
<img src="assets/01-005.shield-bremen.png" style="">
```

**Comment by Fyorl** [comment]
Block-level image links are easy enough to represent in the schema, but having them inline might be a challenge.

**Comment by MrPrimate** [comment]
This is still happening in 10.287 where links are inside another tag, such as <p> as per the first example:

```html
<p>
  <a href="assets/01-005.shield-bremen.png">
    <img src="assets/01-005.shield-bremen.png"/>
  </a>
</p>
```

becomes :

```html
<p></p>
```

**Comment by Fyorl** [comment]
@MrPrimate Please see this comment https://github.com/foundryvtt/foundryvtt/issues/8275#issuecomment-1258060694

**Comment by MrPrimate** [comment]
Ah I misunderstood that comment - is there an issue for the inline functionality, or is this a "wontfix"?

**Comment by Fyorl** [comment]
It's mostly covered by #8130. Once we support inline image nodes, the existing link marks should apply to them without any extra work. So I think we can accommodate this in the future.
