### ISSUE TITLE
Cannot drag-select tiles if they are on top of another tile

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8281]
Originally reported by Stefan#0328 https://discord.com/channels/170995199584108546/956306859491471420/1023284106148196454

**ALL MODULES DISABLED?** Only Library: Chat commands active (default on system, couldn't disable it), tried on both simple worldbuilder and custom system builder systems.  
**OS, Hosting, Browser (if applicable):** Windows 10  
**Short Description of bug:** Can't drag-select tiles if they are on top of another tile (unless you start selection on blank space, which is not always readily available)  
**Simple steps to reproduce the bug:** Use large tiles as background with smaller tiles on top, try to select multiple with selection box. This is true if the tile underneath is locked or invisible.

![DragSelect](https://user-images.githubusercontent.com/207433/192267469-50949748-920e-4977-a6fd-246a2a282f31.gif)

**Comment by aaclayton** [comment]
This is probably difficult to solve, but I do think we should be able to ignore left mouse click+drag workflows when the target interactive element is a **locked** tile specifically. As in the video here we should be able to select the inner tiles because the outer background tile is locked.
