### ISSUE TITLE
The package compendium name field should be validated more strictly with the same rules permitted for package IDs.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8282]
Originally reported by Georgee#3195 https://discord.com/channels/170995199584108546/956306859491471420/1023682273700229212

**ALL MODULES DISABLED?** (false) Bug involves how compendium packs are declared in modules.  
**OS, Hosting, Browser (if applicable):** Forge  
**Short Description of bug:** If a single quote is used in name field of module.json pack declaration, an error results when item is clicked in compendium  
**Simple steps to reproduce the bug:** Put a quote in the name field of module.json pack declaration. Open module's compendium in compendium pane. Click item and get error instead of the item details itemsheet. Spaces seem ok, but not the single quote.  
**Screenshots and/or console errors:**

```
Error: An error occurred while rendering ItemSheet5e 44. Syntax error, unrecognized expression: #ItemSheet5e-Compendium-outfitters-upgrades-Outfitter's Supplies-zp1o0yZSWo27iggp
    at se.error (jquery.min.js:2:13639)
    at se.tokenize (jquery.min.js:2:21650)
    at se.select (jquery.min.js:2:22477)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25047)
    at new S.fn.init (jquery.min.js:2:25536)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:4942:12)
    at ItemSheet5e._render (foundry.js:5776:22)
    at ItemSheet5e.render (foundry.js:5026:10)
```

```json
  "packs": [
    {
      "name": "Outfitter's Supplies",
      "label": "Outfitter's Supplies",
      "path": "packs/outfitters-supplies.db",
      "type": "Item",
      "system": "dnd5e",
      "module": "outfitters-upgrades"
    }
  ],
```

This bug did not occur in v9 which is why I'm reporting it, as it was difficult to track down.

**Comment by Fyorl** [comment]
Seems to be choking on the apostrophe when used as part of a CSS selector, so likely related to #8204

**Comment by aaclayton** [comment]
This compendium package definition is invalid, or at least it should be. The compendium `name` should not contain spaces or special characters. Perhaps our validation is more lax than it should be here. Unfortunately we cannot tighten validation at this point so we need to defer this until V11. Hopefully fixing the linked #8204 issue will at least ameliorate the problem.
