### ISSUE TITLE
Document#unsetFlag does not unset nested flags and instead deletes the root object

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8283]
Originally reported by Idle#3251 https://discord.com/channels/170995199584108546/956306859491471420/1023715451655704638

> on v10, actor.unsetFlag will not do deep delete, but instead will delete the "root" object entirely,

> here a example:

![image](https://user-images.githubusercontent.com/207433/192269010-02d8afec-14f6-4d60-af5c-34c3e12adb72.png)

**Comment by Fyorl** [comment]
This is a regression from the behaviour in #5367

**Comment by aaclayton** [comment]
I had forgotten about the linked issue, but this doesn't seem like the right API usage for us to permit anyways. We should not support unsetting `heroAction.rolled` which is not a flag, that is an inner property of a flag. For me, personally, this would be a `wontfix` but I'm open to your thoughts @Fyorl in terms of what you feel we should do here.

**Comment by Fyorl** [comment]
My opinion hasn't really changed from what I wrote in that issue. `unsetFlag`'s current behaviour in v10 is surprising and inconsistent with the rest of the flag API:

```js
doc.setFlag('scope', 'foo.bar', 'baz'); // Sets an inner property.
doc.getFlag('scope', 'foo.bar'); // Returns the value of an inner property.
doc.unsetFlag('scope', 'foo.bar'); // Should logically be the inverse of the behaviour in setFlag.
```

**Comment by aaclayton** [comment]
I suppose that is a persuasive argument.
