### ISSUE TITLE
`_preCreate` source updates are dropped for embedded documents created on synthetic actors 

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8287]
### What happened?

`TokenDocument#_preUpdateTokenActor` receives `items` and `effects` objects that have different references between `data.items`/`data.effects` and `options.embedded.hookData`:

```js
  /**
   * When the Actor data overrides change for an un-linked Token Actor, simulate the pre-update process.
   * @param {object} data
   * @param {object} options
   * @param {User} user
   * @returns {Promise<void>}
   * @private
   */
  async _preUpdateTokenActor(data, options, user) {
```
![Screenshot from 2022-09-26 18-26-57](https://user-images.githubusercontent.com/106829671/192398990-5b90a707-3950-43c9-b41b-d10c5d60706c.png)

When a document is created to call `#_preCreate`, the `hookData` is used. What is ultimately sent in the server request is `data.items`. This is fine for world actors, but the sharing of references is somehow broken beforehand for synthetic actors.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a new embedded item on any actor.
2. Change some of the new item's data via `this.updateSource({ ... })` in a `_preUpdate` method or "preUpdate" hook.
3. The changes will be reflected if the actor is a world actor but dropped if it is a synthetic actor.

### What core version are you reporting this for?

10.286

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Unlinked tokens were a mistake.
