### ISSUE TITLE
Journal Pages are not brought to foreground if links that reference them are clicked.

### ISSUE THREAD

**Issue by chrisvalentine** [foundryvtt/foundryvtt#8292]
### What happened?

Journal pages that get moved to the background, and covered by foreground entities, do not get pulled to the foreground if a link that should pull them up is visited again. Subsequent links should probably check to see if the page has been rendered and move it to the foreground, and if not rendered, render it.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open a journal page. click a link, put the page that comes up from the link behind other pages.  Click another link that would bring up that same page.  It **appears** to do nothing at this point.

### What core version are you reporting this for?

Version 10  (build 286)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by chrisvalentine** [comment]
This issue was marked closed but I still observe the same behavior  in 287 and 288. Journal entries that are moved behind other windows do not come to the foreground giving the appearance that links to them have achieved nothing.

**Comment by Fyorl** [comment]
I've attached a video following the repro steps and it seems to be functioning correctly. Do you have any additional details? Could it be a system issue?

https://user-images.githubusercontent.com/207433/196194418-2ceda61a-d4f0-488f-b3af-729febef5cb5.mp4

**Comment by Fyorl** [comment]
I've got another video here which shows the behaviour when clicking a content link to an embedded page rather than a whole journal entry too, since the repro steps were actually specific about pages:

https://user-images.githubusercontent.com/207433/196196662-d1d79bb5-047a-4333-b97d-86a2613e0ab5.mp4
