### ISSUE TITLE
Text Labels in drawings do not visibly drop in opacity when their drawing is toggled hidden

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8297]
### What happened?

When a drawing is toggled hidden, its Text Label does not drop in opacity to visibly signify the hidden state. All of the other elements of the drawing do this as expected. The text label does correctly disappear from view for players in this state.

![Screen Shot 2022-09-28 at 1 26 22 PM](https://user-images.githubusercontent.com/801582/192882485-d7868628-5e38-496a-a036-7bbf09a29b40.png)
![Screen Shot 2022-09-28 at 1 26 28 PM](https://user-images.githubusercontent.com/801582/192882496-6fa39747-fa1b-468a-ba84-5c1c5680b31c.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Make a drawing with a Text Label.
2. Toggle the drawing hidden.

### What core version are you reporting this for?

10.286

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aestrada4355** [comment]
Would it be feasible to implement an opacity slider for the Hidden state that could allow the user to configure how opaque/transparent the line/text becomes?
