### ISSUE TITLE
Tile Z-Index not changing to match z value from TileConfig window

### ISSUE THREAD

**Issue by EndlesNights** [foundryvtt/foundryvtt#8298]
### What happened?

When using a tiles configuration window to try and set the Z-Index, while the number inputted is being tracked on a tile objects `document.z`, the tiles `zIndex` value stays at a value of 0.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Make a tile, attempt to change it's z-axis, and check it visually compared to other peaceable objects, such as tokens, or drawings.

For instance in this example here I have:
Two tiles, the top one with a zIndex that is suppose to be set to -31, and the bottom one with a zIndex  that is suppose to be set to 20. You can see from the console that both are returning a value of zero.
I then have a few text drawings set with their lablded z indexs (of +10, -10, and -4)
As well as a actor token with an elevation set to -5 (which should directly translate to its z index?)

The drawings and tokens all seem to be working as expected with the token being drawing between two of the text drawings. But the tiles are not. The top tile with the lower negative index value is being drawn above both the token and drawing. While it would be expected that it should be drawn underneath both. And the bottom tile with the greater positive index is below the drawing which is suppose to have a lower zindex.

![image](https://user-images.githubusercontent.com/58280840/193111771-684b9edb-3591-4c6b-9e93-4fb61f316d64.png)

### What core version are you reporting this for?

Version 10, 10.286

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
@EndlesNights Tiles `zIndex` is not working in the same way as Tokens or Drawings `zIndex`. For Tiles, its only purpose is to break ties between Tiles setted at the same `elevation`. In V10, the later is not exposed in the UI.

**Comment by EndlesNights** [comment]
[Feu-Secret](https://github.com/Feu-Secret)

Maybe this should be a different issue, but I'm going to have to respectfully disagree with the relationship of how Z-index are being handled between a scenes background, tokens, drawing and tiles then. And note that it is highly unintuitive, and frustrating to us since there is no indication that the different z-index/elevations are referring to indexs on different layers. Perhaps rename several of the display labels? As well 

Drawings have a value currently labeled  as "Z-Index", and tokens have a value labeled as "elevation" this value determines the draw order between:
- other drawing based on their "Z-index" value
- tokens based on elevation value
- and overhead tiles based on the scenes "foreground elevation" value
Since the drawing "Z-Index" has no direct integration with the Z-index of either type of tile, and it is used to determine the drawing order based on elevation. It would be much more intuitive to have it labeled as "Elevation".

Similarly perhaps with tiles instead of just label of "Z-Index" if it was more specific to, "Underfoot Index" and  "Overhead Index"

Drawing and Tokens with with a negative elevation/z-index are suddenly drawn behind underfoot tokens. Why does a negative index suddenly effect the drawing order, when the magnitude of the tokens/drawing elevation/z-index before has no bearing on the draw order with tiles? Again this is a highly unintuitive behavior.
If this is an intended behavior, perhaps if there was a way to configure the "elevation of underfoot tiles" and Elevation of Background Image" in a similar manner to when setting the Foreground Elevation value within the Scene configuration window.
Currently having tokens and drawing with negative elevations are extremely frustrating to use since they are suddenly no longer visible on the map.

**Comment by EndlesNights** [comment]
@Feu-Secret 
Maybe this should be a different issue, but I'm going to have to respectfully disagree with the relationship of how Z-index are being handled between a scenes background, tokens, drawing and tiles then. And note that it is highly unintuitive, and frustrating to us since there is no indication that the different z-index/elevations are referring to indexs on different layers. Perhaps rename several of the display labels? As well 

Drawings have a value currently labeled  as "Z-Index", and tokens have a value labeled as "elevation" this value determines the draw order between:
- other drawing based on their "Z-index" value
- tokens based on elevation value
- and overhead tiles based on the scenes "foreground elevation" value
Since the drawing "Z-Index" has no direct integration with the Z-index of either type of tile, and it is used to determine the drawing order based on elevation. It would be much more intuitive to have it labeled as "Elevation".

Similarly perhaps with tiles instead of just label of "Z-Index" if it was more specific to, "Underfoot Index" and  "Overhead Index"

Drawing and Tokens with with a negative elevation/z-index are suddenly drawn behind underfoot tokens. Why does a negative index suddenly effect the drawing order, when the magnitude of the tokens/drawing elevation/z-index before has no bearing on the draw order with tiles? Again this is a highly unintuitive behavior.
If this is an intended behavior, perhaps if there was a way to configure the "elevation of underfoot tiles" and Elevation of Background Image" in a similar manner to when setting the Foreground Elevation value within the Scene configuration window.
Currently having tokens and drawing with negative elevations are extremely frustrating to use since they are suddenly no longer visible on the map.
