### ISSUE TITLE
Updating module menu not working as expected

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#8303]
### What happened?

when you update your modules its not coming back with the correct modules updated in the same way that v9 used to. in that the way it updates isnt showing its being updated after the updated button is hit and the report back is always showing errors and im not receiving a message to confirm all modules are currently up to date.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

just updating modules.

### What core version are you reporting this for?

Version 10 stable 286

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by cswendrowski** [comment]
Update log is working as expected in my testing
