### ISSUE TITLE
Package update button status not retained after Update All operation

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8305]
Originally reported by PH#2526 https://discord.com/channels/170995199584108546/956306859491471420/1024683886460010537

**OS, Hosting, Browser (if applicable):** Windows 10 | Node, self hosting | Chrome (latest)  
**Short Description of bug:** On version 9 Foundry showed the status of each package update attempt after performing an _Update All_ action. On v10 this is no longer the case; after completing an _Update All_ workflow there is no visual indication of the package's update status.  
**Simple steps to reproduce the bug:** Click the _Update All_ button at _Game Systems_ or _Add-on Modules_ tabs and wait for Foundry to finish fetching all packages; see the status of each package  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/193569846-a8df0852-73da-4441-9b8f-61b01f6497c2.png)

**Comment by Fyorl** [comment]
Possibly related to #8303 though the user there is reporting always seeing errors.

**Comment by cswendrowski** [comment]
Reported behavior is not a bug - we rerender the UI in more cases now to support workflows such as sidegrading and availability checks, but the downside is that we lose the button state when that rerender occurs. 

If this rerender doesn't occur, then the states are retained as before, but with the new dependency system there's a lot more cases where it may occur.
