### ISSUE TITLE
refCount error when scaling up background size

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8306]
Originally reported by epsilon#7430 https://discord.com/channels/170995199584108546/956306859491471420/1024891281970831360

**ALL MODULES DISABLED?**  true (10.286, a5e 0.8.5)  
**Steps to reproduce:**  I created a new scene with image dimension 4800x3000.  I scaled background to 2 - no apparent issues.  I scaled background to 3 and saved with a refCount error.  Refreshing FVTT resolves and scene is at scale 3.  Configuring scene scale again, e.g., setting back to 2,  reproduces error. 

```
Canvas drawing failed: Cannot read properties of null (reading 'refCount')
```

**Comment by Fyorl** [comment]
Possibly related to #8253 as the refCount error is the same.

**Comment by Feu-Secret** [comment]
@Fyorl Confirming that this issue is a duplicate of #8253. To delete.
