### ISSUE TITLE
Empty Combat Tracker may cause infinite loop in an ActiveEffect's duration evaluation

### ISSUE THREAD

**Issue by Spice-King** [foundryvtt/foundryvtt#8318]
Right, this was a "fun" one to try and sort out.

## Symptoms

Given the right set of conditions, this seems to cause freezing/lock up of the UI thread, no user input would be accepted, browser crashing and tab killing. This could be triggered whenever any AE needed to recalculated, like during a system migration, user change, or a module adding an AE. Most often seen on the DnD 5E system thus far from my perspective, but I also got a report on a Bladurs Gate world, but the user bailed on upgrading to v10 and reverted to v9 due to modules.

## Versions effected

10.282 through 10.286

## Conditions

1. A started combat tracker instance which is the current active one at `game.combat`, which has been used and tracked round, but has had all combatants removed from the tracker, even dead ones
2. An active effect on an actor which has a rounds/turns duration set, which is considered started
3. A trigger that causes the need to evaluate the AE's derived data. (a normal user could log in just fine, but a GM who does and triggered DnD5E's migrations would freeze since they see and touch all the actors)

## Cause

resources/app/client/data/documents/active-effect.js:100
```diff
       // Some number of remaining rounds and turns (possibly zero)
       const remaining = Math.max(((start + duration) - current).toNearest(0.01), 0);
       const remainingRounds = Math.floor(remaining);
-      const remainingTurns = Math.min(((remaining - remainingRounds) * 100).toNearest(0.01), c.nTurns-1);
+      let nt = c.turn - d.startTurn;
+      while ( nt < 0 ) nt += c.nTurns;
+      const remainingTurns = nt > 0 ? c.nTurns - nt : 0;
```

That `while` loop. Firefox's dev tools always dropped me in there as the code host spot. Why? Because `c.nTurns` was 0. Why is it zero? Well for reference, here is how `c` is set:
```js
      // Determine the current combat duration
      const cbt = game.combat;
      const c = {round: cbt?.round ?? 0, turn: cbt?.turn ?? 0, nTurns: cbt?.turns.length ?? 1};
```
Functionally, `c.nTurns = game.combat?.turns.length ?? 1` which would be zero if there were no combatants in the combat.

## Fix

Wrap setting `c.nTurns` in a `Math.max(..., 1)`, possibly look for a pure math solution to avoid a `while` loop all together to avoid the chance of an infinite loop due to floating point shenanigans due to someone putting in something larger than `Number.MAX_SAFE_INTEGER` (~9 quadrillion) in the duration, though I'd just say that anything past a few million is invalid data for an AE and block it in validation.

**Comment by Fyorl** [comment]
Thank you very much for the thorough investigation, this is an impressive bug.

**Comment by Spice-King** [comment]
No problem. The in-situ fix has been to delete the active combat that has no combatants, but the window between Foundry being fully functional with the world's data payload from socket.io and when DnD5e's migrations or another possible triggerer touches the actor can be very quick, even more so if it's an early actor in the collection that has the AE. Deletion via API in JS console was far faster if typed out than trying to do it via UI.
