### ISSUE TITLE
Add an option in settings on the main menu to ignore compatibility issue yellow warning

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#8320]
### User Experience

id just like a way to ignore compatibility issues other than critical ones.  mainly in the settings menu here

![image](https://user-images.githubusercontent.com/62528192/193848859-73579085-a7fe-4452-897c-3a1ca668c54c.png)

**Comment by aaclayton** [comment]
I don't think we would support this option. We instead need (and want) to continue improving the UI/UX around the warnings that we do provide so that they are desirable and informative.
