### ISSUE TITLE
Foundry browser clients are not caching many static assets on chrome.

### ISSUE THREAD

**Issue by ScottRosenberg2** [foundryvtt/foundryvtt#8324]
### What happened?

Foundry is not browser caching most static assets on chrome specifically, when hosted without a reverse proxy. This problem is not appearing to occur on firefox.

Platform tested:
Ubuntu 20.04 + nodejs(latest from 20.04 repo)
No reverse proxy, direct IP over port 30000.

This image is from firefox.
![image](https://user-images.githubusercontent.com/11279463/194175996-09d0e78c-757a-4a2b-9b03-180d1f1022dc.png)
On firefox, nearly every asset is cached. Only 2 are not.

This image is from chrome.
![image](https://user-images.githubusercontent.com/11279463/194176190-7b9f7e73-2fad-44e7-812a-53e4f5e36159.png)
On chrome, only png, and woff2 assets are cached.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Enter chrome
Press f12
Go to a foundry server, without a reverse proxy.
Refresh the page twice.
See what assets are cached.

### What core version are you reporting this for?

Version 9 - Build 269

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Are you sure they're not being retrieved from cache? The screenshot shows 304 responses which generally means they will be.

**Comment by aaclayton** [comment]
This is something to do with the way Chrome is reporting this. A size of 256B is absolutely tiny and is not the size of the actual files you are transferring here. A size that small is likely nothing more than just the request/response headers that are used to determine whether the resource can be cached. 

A 304 response code in Chrome indicates that the resource was cached. You will easily be able to see the difference between a forced refresh (`CTRL+F5`) which does not cache anything and a regular refresh (`F5`) which does.
