### ISSUE TITLE
Token rotation should also accept decimal places

### ISSUE THREAD

**Issue by kagedansa** [foundryvtt/foundryvtt#8325]
### User Experience

At the moment the field for token rotation is defined in Foundry as

`<input type="number" name="rotation" value="{{object.rotation}}">`

As it is currently, it only accepts integers. 
Some modules e.g. Auto-Rotate insert values with decimal places.
This results in that they can no longer be changed and this blocks the entire editing process of a Token, regardless which fields you try to change.

To avoid this the foundry template for the token-config can be changed to:
`<input type="number" name="rotation" value="{{object.rotation}}" step="any">`

**Comment by Fyorl** [comment]
This should use our `numberInput` helper if not already, which will handle defaulting to `step="any"` for us.
