### ISSUE TITLE
relationships.systems silently accepts an invalid object instead of an array in some cases

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8328]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1026887411814371368

**ALL MODULES DISABLED?** true (/setup scren)  
**OS, Hosting, Browser (if applicable):** Any?  
**Short Description of bug:** `relationships.systems` silently accepts system object instead of requiring an array (this systems field is scrapped and ends up empty in the module)  
**Simple steps to reproduce the bug:**  Make a module with following relationships field:
```json
"relationships": { "systems": { "id": "bloop"} },
```
And observe how it's silently accepted.

**Comment by Fyorl** [comment]
Additional discussion starting here: https://discord.com/channels/170995199584108546/956307084931112960/1026872813312802816

**Comment by aaclayton** [comment]
We should investigate whether this is a lingering bug or whether it has been fixed by other recent changes.
