### ISSUE TITLE
`ui.notifications.notify` doesn't respect the permanent option.

### ISSUE THREAD

**Issue by SalieriC** [foundryvtt/foundryvtt#8333]
### What happened?

When giving the permanent option to a `notify` notification, the notification will disappear after five seconds anyway. It works as expected with `error` and `warn` however.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Execute a simple macro:
```js
ui.notifications.notify("Notify", {permanent: true})
ui.notifications.warn("Warn", {permanent: true})
ui.notifications.error("Error", {permanent: true})
```

### What core version are you reporting this for?

Version 10.whateverislatest, also happened on v9

### Relevant log output

```shell
None.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
You are getting the method signature for `.notify` wrong. `.notify` is a general purpose message dispatcher which handles all notification types. It's signature is `notify(message, type="info", options)`, you are passing options as teh second parameter. You probably want `ui.notifications.info()` instead.
