### ISSUE TITLE
Journal Entry titles in the map note dialog do not respect player permissions

### ISSUE THREAD

**Issue by hmarthinsen** [foundryvtt/foundryvtt#8335]
### What happened?

Players could see the titles of journal entries that they don't have permission to view, spoiling the game. I expected that the journal entry titles that they didn't have the permission to view would not appear in the Journal Entry drop-down in the New map note dialog.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. As a player, create a new map note.
2. In the dialog box that appears, in the Journal Entry field, the player can see the title of journal entries that they don't have the permission to access.

The titles of journal entries are potential spoilers.

![Capture](https://user-images.githubusercontent.com/6989581/194412667-41915693-a62c-44ca-b40d-3f1be6feead5.JPG)

### What core version are you reporting this for?

Version 10 (build 286)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by hmarthinsen** [comment]
I didn't check if the problem occurs with all modules disabled.

**Comment by unsoluble** [comment]
Can confirm this is still an issue in 10.287 (without modules).
