### ISSUE TITLE
Consider not throwing the `World Data Migration Required` dialog unless a data migration will actually happen

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8336]
### User Experience

Currently, this `World Data Migration Required` dialog pops on each world's first launch after _any_ core update. I don't think it should pop unless it's determined that the delta between the world's current `coreVersion` and the newly installed core version actually contains data migrations.

(If it pops on every patch without actually doing anything irreversible, people will begin to learn to ignore it, which will bite back when it's eventually important.)

<img width="427" alt="CleanShot 2022-10-06 at 14 21 25@2x" src="https://user-images.githubusercontent.com/801582/194422830-e57915ed-dc6d-4ad4-8f69-2c304b018a18.png">

**Comment by aaclayton** [comment]
It would be nice to improve the targeted nature of this prompt, but some other changes in V12 have meant that it is possible that *some data* might be migrated on every version update. Without investing to build a "migration dry-run" to know we cannot predict easily whether irreversible migrations will or will not occur as a result of the update.
