### ISSUE TITLE
Allow script macros to shadow parameters

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8345]
### User Experience

Currently script macros have several invisible parameters that must be stepped around in order to avoid throwing a syntax error due to redeclaring them:
```js
    const fn = new AsyncFunction("speaker", "actor", "token", "character", this.command);
```

If those variables were instead bound to an outer scope, they could be shadowed:
```js
    const command = ["{", this.command, "}"].join("\n");
    const fn = new AsyncFunction("speaker", "actor", "token", "character", command);
```

**Comment by silvative** [comment]
Of note, some of these variables were used in premium content macros, which caused them to break when this change was made. We can adjust/harden our variable names in premium content to avoid similar conflicts in the future regardless of the outcome of this issue, though.

**Comment by stwlam** [comment]
This has become slightly more critical since V11 made the script-execution method #private.
