### ISSUE TITLE
HTML comment strings are treated as invalid and deleted from journal contents

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8350]
Wrapping comment elements around sections in journal entries appears to cause prosemirror to delete the entire encapsulated text from the journal page contents.

Repro steps:
1. On any journal text page, click edit
1. open the raw html editor
1. wrap any text, paste the below:
```
<!--  
NOBODY expects the Spanish Inquisition! Our chief weapon is surprise...surprise and fear...fear and surprise.... Our two weapons are fear and surprise...and ruthless efficiency.... Our *three* weapons are fear, and surprise, and ruthless efficiency...and an almost fanatical devotion to the Pope.... Our *four*...no... *Amongst* our weapons.... Amongst our weaponry...are such elements as fear, surprise.... I'll come in again.
-->
```
1. Save the journal page and notice its contents are gone, reopen the raw HTML editor and the commented string is not present.

**Comment by aaclayton** [comment]
It doesn't seem like there should be much use case for this, but we'll keep the issue open for long-term consideration.

**Comment by aaclayton** [comment]
Good point. I'm going to close this issue as "not planned" and add a comment to #9447
