### ISSUE TITLE
Passing Embedded Documents inline with other properties in `update` on synthetic actors replaces existing Embedded Documents

### ISSUE THREAD

**Issue by moo-man** [foundryvtt/foundryvtt#8351]
### What happened?

Normally, passing `items` or `effects` inline with `update` just adds/updates the documents specified

For example, `actor.update({name : "new name", items : [<itemdata>]})`

Currently, doing this to synthetic actors replaces existing embedded documents with the provided ones. (**only happens when another property is being updated at the same time**).

`actor.update({name : "new name", items : []})` for example would delete all the items on the synthetic actor

**Again this ONLY happens when another property is being updated at the same time**

`actor.update({items : []})` does nothing, this is why the previous examples also change "name" 

### What ways of accessing Foundry can you encounter this issue in?

- [x] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

Setup a DND5e world
Drag and Drop an Acolyte onto the canvas and select the token
Execute the following command (replaces all items but adds a new weapon)
`canvas.tokens.controlled[0].actor.update({items : [{type : "weapon", name : "weapon"}], name : "test"})`
or
`canvas.tokens.controlled[0].actor.update({items : [], name : "test"})` (deletes all items)

Observe that all existing items have been deleted

### What core version are you reporting this for?

Version 10 Stable (Build 287)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm not initially confident about fixing this issue without risking stability to other aspects of unlinked token updating or without incurring additional technical debt in this area. I'm happy for us to investigate whether there is an easy solution to this bug, but if not I think we need to add it to the mountain of evidence for why unlinked tokens suck and we need to do something architecturally different in V11 to eliminate this area of tech debt from our software.
