### ISSUE TITLE
Showing inline journal images to players only displays a blank box

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8359]
Originally reported by PS#9868 https://discord.com/channels/170995199584108546/956306859491471420/1028687867297398788

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Chrome, Edge, Windows  
**Short Description of bug:** When showing the players only an image that's pasted in a journal (not the whole journal page), they see only a blank window without the image.  
**Simple steps to reproduce the bug:** open any image pasted in a journal page, show it to the players and check if they see anything.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/194859505-8e39f191-a276-4cc7-889d-fe38f3431fab.png)

![image](https://user-images.githubusercontent.com/207433/194859531-e80f82d3-ddea-4726-853b-e626c1bf54ed.png)

**Comment by minnellac** [comment]
<img width="567" alt="Screen Shot 2022-10-16 at 15 55 48" src="https://user-images.githubusercontent.com/115952600/196056369-92299b8d-658e-4230-a34f-cc42b3a4d67b.png">
I'm experiencing this issue in Foundry 10.288 with dnd5e 2.0.3. I've attached a console image from a client that did not receive the images. A client connected to .localhost:30000 gets the images without issue. I was able to reproduce the behavior described above where full the journalsheet renders correctly but the imagepopout does not.

**Comment by Fyorl** [comment]
That's a big help, thanks, it's clear where the issue is now.

**Comment by minnellac** [comment]
I saw something that looked like this in the release notes for version 290 with D&D5e; however, when I went to test it I got mixed results. Again, I tested with all modules disabled. This time, I was able to show players some of my journal images, but not others. Here is a screen shot showing an image shown (successfully), and image shown (failed), and another image shown (successfully). The images are all embedded images in a journal (different journals though). Seems like something is still broken.
<img width="556" alt="Screen Shot 2022-11-13 at 21 03 50" src="https://user-images.githubusercontent.com/115952600/201561177-44d8be33-af20-4545-9afe-7ca8d901a656.png">

**Comment by minnellac** [comment]
I played around with the html and I found that the image displays properly when I use the relative link to the image. Below, the first <img> tag fails and the second one works. I'm not sure why I ended up with a mix in my journals. I was just pasting images in when I created them.

```
         <img src="http://localhost:30000/worlds/icewind-dale/assets/pages/V1AarXFSO92n2rVi-pages-Sn12kK1IqUSZEw3k-image-1cc8rdr0iTDTwsJ5.png" style="box-sizing: border-box; user-select: text; border: 1px solid var(--color-border-dark); border-radius: 2px; max-width: 100%; cursor: pointer">
         <img src="worlds/icewind-dale/assets/pages/V1AarXFSO92n2rVi-pages-Sn12kK1IqUSZEw3k-image-1cc8rdr0iTDTwsJ5.png" style="box-sizing: border-box; user-select: text; border: 1px solid var(--color-border-dark); border-radius: 2px; max-width: 100%; cursor: pointer">
```
