### ISSUE TITLE
Ruler.segments sometimes contains a segment for which ray.B is undefined

### ISSUE THREAD

**Issue by manuelVo** [foundryvtt/foundryvtt#8370]
### What happened?

When a ruler from another player is being displayed, sometimes `Ruler._calculateDistances` is being called with `Ruler.segments[0].ray.B` set to `undefined`. Unfortunately, this bug isn't very stable to reproduce, so it may take a few attempts involving restarting of the foundry app to reproduce.

Initially reproducing the bug may be simplified by enabling the Terrain Ruler module version 1.7.1 (which as of writing is the most current version), since this module will run into an infinite loop if `ray.B` is undefined, which makes it obvious that the bug has triggered. Here is a video of this bug reproducing with Terrain Ruler active, which may be helpful in reproducing this bug: https://www.youtube.com/watch?v=FI4-uiFLbaw

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

As already stated, the bug is a bit unstable to reproduce and seems to be somewhat dependent on race conditions, so unfortunately I cannot give a detailed step-by-step guide for reproduction that works every time, but rather only a general guideline of what I'm doing when reproducing this bug.

1. Create an empty Foundry VTT world that has one GM and one Player account, enable the Terrain Ruler module (this bug also occurs without Terrain Ruler, but is easier to reproduce with Terrain Ruler enabled)
2. Close the Foundry VTT application & server and browser tabs connected to that foundry instance
3. Open the Foundry VTT standalone application
4. Launch the world
5. Join the world as GM
6. Wait for Foundry VTT to be fully loaded and initialized
7. Connect to Foundry VTT via a browser
8. In the browser, join the world as player
9. In the browser, measure something
10. Stop measuring
11. Go back to the native application and measure something there

If Terrain Ruler is enabled, step 11 should cause the browser to freeze because Terrain Ruler hits an infinite loop (in case Terrain Ruler is disabled, the ruler will calculate invalid distances), which means that the bug occurred `ray.B` was set to `undefined` in that instance. Should the browser not freeze, retry from step 2.

For me, this happens at least once in ten tries, sometimes more often.

### What core version are you reporting this for?

10.288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
The team tried to reproduce this issue, in different systems, without success. We are closing this issue for non repro.
We might consider reopening it with a reproduction path not involving a module.
