### ISSUE TITLE
Updating an actor `prototypeToken` doesn't update properly if properties get deleted and added even when awaited.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8372]
### What happened?

Updating an actor prototypeToken in 10.287 doesn't update properly if properties get deleted and added even when awaited

Report from https://discord.com/channels/170995199584108546/956306859491471420/1029047201227362404

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create an Actor
- Update the `prototypeToken` with the following macro (replace the `id` with the `id` of the created actor)
```js
(async () => {
    const actorId = "u4okMdSGZwth6f9P";
    
 await game.actors.get(actorId).update({[`prototypeToken.flags.token-attacher`]:{test: 10}})    
 await game.actors.get(actorId).update({[`prototypeToken.flags.token-attacher-=test`]:null})    
 await game.actors.get(actorId).update({[`prototypeToken.flags.token-attacher`]:{testother: 12}})    
 await game.actors.get(actorId).update({[`prototypeToken.flags.token-attacher`]:{testThird: 5}})    
})();
```
- Drop the token from the actor onto a scene
- Check the flags of the controlled token with `canvas.tokens.controlled[0].document.flags['token-attacher']`
- Flags will show up as `{test: 10, testother: 12, testThird: 5}` but should be `{testother: 12, testThird: 5}`

### What core version are you reporting this for?

Version 10 Stable Build 287

### Relevant log output

```shell
-
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
The reporter has a syntax error in their example.

```diff
- 'prototypeToken.flags.token-attacher-=test'
+ 'prototypeToken.flags.token-attacher.-=test'
```
