### ISSUE TITLE
Token#getAdjustedPoint not present

### ISSUE THREAD

**Issue by the-real-orson** [foundryvtt/foundryvtt#8373]
### What happened?

I used Token#getSightOrigin() and was informed that this function is deprecated in favor of Token#getAdjustedPoint ,which as far as I can tell does not exist.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Select a token and type `_token.getAdjustedPoint();` in the console and press enter.

### What core version are you reporting this for?

10.287

### Relevant log output

```shell
commons.js:1703 Error: Token#getSightOrigin has been deprecated in favor of Token#getAdjustedPoint
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Token5e.getSightOrigin (foundry.js:47055:19)
    at <anonymous>:1:8
```
```
VM114850:1 Uncaught TypeError: _token.getAdjustedPoint is not a function
[No packages detected]
    at <anonymous>:1:8
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
The deprecation message needs updating, you should use `getMovementAdjustedPoint`.
