### ISSUE TITLE
Dragging an actor on the canvas could trigger unecessary token refresh operations.

### ISSUE THREAD

**Issue by DJ4ddi** [foundryvtt/foundryvtt#8382]
### What happened?

When dragging an actor onto the canvas, every existing token is refreshed 10 times, causing a huge overhead for bars, borders, effects, etc.

This is the call stack:
```
refreshHUD (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:45801)
_refresh (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:45786)
refresh (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:25113)
highlightObjects (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:23997)
deactivate (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:30330)
activate (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:30299)
_onDropActorData (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:37043)
await (Unknown Source:0)
_onDrop (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:24589)
callback (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:56371)
_handleDrop (c:\Program Files\Foundry Virtual Tabletop\resources\app\public\scripts\foundry.js:56422)
```

The key issue is that in the drop handler, every instance of `InteractionLayer` is deactivated, which results in another loop over all layers in `highlightObjects` which then refreshes all placeables within itself.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a new scene with any token.
2. Create a new actor with a prototype token.
3. Drag & drop the actor onto the scene.
4. Observe how the callstack mentioned above is called 10 times for the existing token from step 1.

### What core version are you reporting this for?

10.288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
> Something I'd like to note (and this is in no way meant as a jab toward the developers): This is the 3rd issue (plus a few Discord messages) regarding duplicate refresh/draw calls. I feel like at this point, a better solution would be to debounce and deduplicate the calls instead of fixing the occurence paths separately.

This is something I have planned/roadmapped - but was too ambitious to approach in V10. *Perhaps* addressable in V11.

**Comment by Feu-Secret** [comment]
@aaclayton Not repro on my side. I can see that calls to deactivate layers might be avoided, but in the worst case, there is just on refresh per token on the scene.

**Comment by Feu-Secret** [comment]
This issue has been reclassified.

**Comment by Feu-Secret** [comment]
This issue is moved to `V11 - Prototype 1` milestone. Risks for V10 compatibility are too high.

**Comment by dev7355608** [comment]
`InteractionLayer#deactivate` doesn't skip deactivation if the layer is already inactive unlike `InteractionLayer#activate`, which skips activation if already active. If it did, only the dropped token would be refreshed once instead of all tokens 8 (# of interaction layers - 1) times.
```diff
  /**
   * Deactivate the InteractionLayer, removing interactivity from its children.
   * @returns {InteractionLayer}    The layer instance, now inactive
   */
  deactivate() {
+   if (!this.#active) return this;
    canvas.highlightObjects(false);
```

**Comment by aaclayton** [comment]
Yes, we identified this issue with the deactivation layer and we have this changed merged in for the next v10 release.

**Comment by aaclayton** [comment]
EDIT: I have to take that back. I forgot the conversation I had with @Feu-Secret about this. We agreed that - while certainly we should avoid repeat unnecessary  deactivation workflows - there may likely be current modules that are reliant on the fact that other layers deactivate every time the active layer is switched. Some module authors may be relying on deactivate hooks or behaviors in this case. 

We will absolutely make this change, but it's going to come in V11 instead.

**Comment by Feu-Secret** [comment]
@aaclayton Long live to the `renderFlags`!
- See https://github.com/foundryvtt/foundryvtt/issues/9026
