### ISSUE TITLE
Selecting multiple tokens can have aberrant vision-mode rendering if one has darkvision

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8387]
### What happened?

If multiple tokens with vision enabled are selected, an unvarying monochrome is rendered within the vision range of any token with darkvision.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Two tokens, one with 60 feet of darkvision and another with vision enabled but no special modes and `null` vision range:

![Configs](https://user-images.githubusercontent.com/106829671/196007996-603b0179-4dfc-4784-b1a2-99c42c7015d1.png)

Token with darkvision selected:

![Token with darkvision](https://user-images.githubusercontent.com/106829671/196007973-4eefe2b1-618e-4d36-b72d-e9182497dbf0.png)

Token with no special vision selected:

![Token with no vision](https://user-images.githubusercontent.com/106829671/196008051-e1b821b1-217c-4e77-9283-8654db3b221e.png)

Both selected:

![Both](https://user-images.githubusercontent.com/106829671/196007987-b6f3db5b-5361-4e73-a7fd-92d580c333d5.png)

Notably, the issue only presents with lights using Adaptive Luminance coloration. With Legacy Coloration, for example, everything appears as expected:

![Natural Light](https://user-images.githubusercontent.com/106829671/196009327-00794046-c686-45c1-9bc4-ebe5bbc0b0b5.png)

### What core version are you reporting this for?

10.288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Hello @stwlam. This issue has been fixed here:
-https://github.com/foundryvtt/foundryvtt/issues/8434
