### ISSUE TITLE
Extremely large scenes and lights sometimes exhibit oddness with lights and walls

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#8394]
### What happened?

Originally sent in via email:

When setting a map to a large enough size, nonexistent walls that obstruct light and vision start to appear on large map sizes.

The sweet spot is somewhere between 21000x21000 and 22000x22000 for map size.
The light source starts hitting nonexistent walls above 92 feet of light.
If light vision angle is 180 degrees or less the nonexistent walls disappear.
Token vision angle is substantially less forgiving, and requires a more restricted sight radius to not see the invisible walls.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

**To reproduce:**
1. Create a scene, set the size to 25000x25000
2. Drop a token in the scene.
3. Set the token bright light distance to 300 and dim light distance to 300
4. Begin drawing walls to obstruct the light around the token. Eventually the lighting will break as it appears to hit nonexistent walls. Drawing walls on opposite sides of the light source appears to make the issue appear more quickly.
5. Drop a token on the map that has 360 division.
6. You may have to drag the token around and have it move for the nonexistent walls obstructing vision to show up.
7. Test server available:

### What core version are you reporting this for?

10.286

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
@aaclayton Found the culprit here. It is our `Math.roundFast` method, which behave strangely with values > 32 bits (so, signed 31 bits), and is related at Javascript number internal format (IEEE 754 64 bits double precision) I wonder if other errors we have with the generation of the polygons are not related to this limitation.

The workaround :

```js
export function roundFast(number) {
  if ( Math.abs(number) > 0x7FFFFFF ) return Math.round(number);
  return (number + (number > 0 ? 0.5 : -0.5)) << 0;
}
```
