### ISSUE TITLE
Drag/dropping items from temporary sheets fails

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/foundryvtt#8401]
### What happened?

As per title:

[temp_drag.webm](https://user-images.githubusercontent.com/25264887/196551330-97e27ea5-8576-4ecf-8926-48084f34e671.webm)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
(async () => {
	const actor1 = await Actor.create({name: "Repro", type: "character"}, {renderSheet: true})

	const actor2 = await Actor.create({
		name: "Repro (Temp)",
		type: "character",
		items: [
			{name: "Item", type: "weapon"},
		],
	}, {temporary: true})
	actor2.sheet.render(true) // `renderSheet: true` doesn't work for `temporary` items(?)

	// Drag-drop the "Item" item from actor2's sheet to actor1's sheet
})()
```

### What core version are you reporting this for?

Version 10 288

### Relevant log output

```shell
foundry.js:13687 Uncaught (in promise) Error: Failed to resolve Document from provided DragData. Either data or a UUID must be provided.
    at Item5e.fromDropData (foundry.js:13687:13)
    at async ActorSheet5eCharacter._onDropItem (foundry.js:61081:18)
fromDropData @ foundry.js:13687
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
In this case, the error message is informative. You need to either pass an existing UUID or the full item data when drag+dropping data. Your use case here is probably one that will not work properly under V10. Sorry.
