### ISSUE TITLE
Resetting token configuration preview breaks nested objects

### ISSUE THREAD

**Issue by DJ4ddi** [foundryvtt/foundryvtt#8407]
### What happened?

When making changes in the token configuration, the changes are correctly previewed. Upon saving the configuration, a reset is performed that should revert the token's local data to its original state. The way this is done briefly breaks any nested objects, e.g. flags, because `TokenConfig._previewChanges` calls `updateSource` with `recursive: false`, which means that the delta calculated in `TokenConfig._resetPreview` gets applied in a non-differential way for objects below the top level.

The token is then refreshed with the broken flags before being restored by the update operation. The token stays in a broken state if the user closes the configuration instead of saving it.

Side note: The issue occurs with all modules disabled, but is not relevant when the token flags aren't used by the system or any module.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a token in any scene.
2. Open the token configuration. Fire a change event for any input with a nested name. You can either simulate this behavior or install a module that modifies token flags, e.g. Bar Brawl.
3. Observe how the flag gets applied to the local token data as a preview.
4. Close the token configuration. Observe how the preview reset causes the flag diff to be restored (instead of restoring the original flags).

### What core version are you reporting this for?

10.288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I think this will be addressed by the fix for #8393
