### ISSUE TITLE
New actors created by dragging from a compendium do not take default token settings into account

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/foundryvtt#8410]
### What happened?

This was previously reported and erroneously closed in #6594.

(issues were deleted and some were in gitlab, so the best way to see what the previous bug reports included is to search in the server for '6594 in: github-notifications', e.g. [leading here](https://discord.com/channels/170995199584108546/527196252576808960/934967180259393577))

When dragging an actor from the compendium its default token configuration uses the existing values that were on that actor within the compendium, rather than being overridden with the Default Token Settings that can be configured in the settings.

This means that even if a GM tried to set a new default for all monsters (e.g. displaying names to owner), importing them will not apply that default (i.e. never displaying names), and the GM will have to manually fix the issues or resort to using a module.

This incorrect behavior happens when dragging an actor from the compendium - either onto the canvas or onto the Actors directory.  However, it does not happen when using the Import Entry context menu option on the actor.

NOTE:  this issue was [partially worked around](https://discord.com/channels/880968862240239708/936292011277942885/1033657723243470898) in the PF2E system, but does not account for all cases there.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Enter a world in any system
2. press Configure Settings
3. navigate to core settings
4. press Configure Default Token Settings
5. set Token Disposition: Friendly
6. Save Changes
7. Save Changes
8. open any pack that contains actors
9. drag an actor from that pack onto the canvas, thus creating a new Actor and a new Token that represents that actor
10. observe the token's (and the actor's) token configuration

Expected:  token and actor prototype should be Friendly
Actual:  the token is Hostile, and the Actor's prototype token is also Hostile

### What core version are you reporting this for?

Version 10 build 288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
It appears as if this issue has been resolved for the case of dragging actors directly from a compenidum pack to a scene, but has not been resolved for the case of dragging from the pack to the Actors sidebar. In the latter case, Default Token Config defaults are not respected (10.291).
