### ISSUE TITLE
Vision based Overhead tiles use radial occlusion on tokens with no vision

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#8411]
### What happened?

Users reported that foundry v10 roofs make it impossible for the GM to see anything under a roof while selecting an NPC token, as the new roofs reveal tokens and the background based on vision, which NPCs in many game systems (DnD 5e, pf2e, SWADE, etc.) don't have.

![image](https://user-images.githubusercontent.com/74384067/197386967-fbe18eeb-07d7-446b-aa92-fbc7e95cb942.png)

Giving all NPCs vision causes a great inconvenience to GM's, and has a big performance impact, which means it's by no means a preferred solution.

Anathema suggested "actors other than PC treat tiles as "full tile" in overhead mode.", which I think is reasonable.

Without a solution to this the premium content will have to remove all roofs in a patch, which I think would be a great shame as the new roofs, together with the FOW images make scenes in v10 really amazing to explore.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

set up a roof tile like this:

![image](https://user-images.githubusercontent.com/74384067/197387018-59cedb64-9cae-453a-97a7-d9f09ee77e37.png)

then move an NPC token under it. can be reproduced in swade, dnd5e, pf2e, and others

### What core version are you reporting this for?

Foundry v10 build 288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I have a candidate fix for this but it involves changing the signature for some public and protected methods so it will probably have to wait until v11 unless we come up with an alternative solution.

**Comment by stwlam** [comment]
> I have a candidate fix for this but it involves changing the signature for some public and protected methods so it will probably have to wait until v11 unless we come up with an alternative solution.

Can the new signature temporarily be handled via turning the parameter list into a single rest parameter and structurally determining which was passed to the method?

**Comment by Fyorl** [comment]
> Can the new signature temporarily be handled via turning the parameter list into a single rest parameter and structurally determining which was passed to the method?

In this case it involves changing the method's return value.

**Comment by aaclayton** [comment]
I was able to implement an improvement in this behavior without any breaking conseqeuences for V10 APIs, so this bug fix can go forward!
