### ISSUE TITLE
Bug with macro opening a specific page of a journal entry.

### ISSUE THREAD

**Issue by Lifthraser** [foundryvtt/foundryvtt#8412]
### What happened?

Creating a macro shortcut of a specific page of a V10 journal in my hotbar. When drag and droping the page to the hotbar, the macro is created, open the right journal page, but in edition mode, I suspect this is a bug.

The created macro:
Hotbar.toggleDocumentSheet("JournalEntry.aiqXDg64LZx8nq49.JournalEntryPage.tS7k9pHqyp6511eb")

No active module
Foundry 10 build 288
Tested with DND 5e system 2.0.3 and SWADE 2.0.6
![journal_page_maro](https://user-images.githubusercontent.com/79018988/197390131-d392eed4-8e5f-4390-a79d-783ba9913553.gif)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

create a journal entry
create a page
drag and drop that page to the hotbar
open the newly created macro
it edit the page

### What core version are you reporting this for?

version 10 build 288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is not a bug because the document sheet associated with Journal Pages is the one to edit that page. If you want a macro to open a journal entry to a certain page you need to link to the journal entry itself and render the sheet with a specific page requested as an option to the render method.
