### ISSUE TITLE
Unable to select multiple map notes with the note select tool

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8415]
Originally reported by Aedif#7268 https://discord.com/channels/170995199584108546/956306859491471420/1032693272772087860

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** n/a  
**Short Description of bug:** Not able to select multiple notes using 'The Select Notes' tool. The select tool added in v10 and documented in an article here (https://foundryvtt.com/article/map-notes/) does not work as intended.  
**Simple steps to reproduce the bug:** Place multiple notes on the scene, enable 'The Select Notes' tool, and attempt to drag a square or click on notes to select them.  
**Screenshots and/or console errors:**  
`canvas.getLayerByEmbeddedName("Note").options.controllableObjects === false`

**Comment by Fyorl** [comment]
I verified that in v9, the note select tool also does not allow for box selection or control of notes, just interaction with them. I will shift this to a documentation issue.

**Comment by Feu-Secret** [comment]
The related KB article has been updated : https://foundryvtt.com/article/map-notes/
