### ISSUE TITLE
Trying to edit the page of a journal stored in an editable compendium throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8417]
Originally reported by Farling#9579 https://discord.com/channels/170995199584108546/956306859491471420/1032732251676479519

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 11, Foundry app  
**Short Description of bug:** Trying to edit page of journal that is stored in editable compendium generates error in console  
**Simple steps to reproduce the bug:** Open a page from a journal stored in the compendium; then close the window, and see two errors  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/197567496-058a200c-794c-4781-830f-ea4be7d9f766.png)

**Comment by farling42** [comment]
This specifically occurs when the compendium is stored in a module, not just in the world.

**Comment by Fyorl** [comment]
Not able to reproduce this.

**Comment by farling42** [comment]
This is for a compendium module which was originally created in Foundry V9.

It seems that the pack from the module is being made to look like V10 format via the API, but the db remains in V9 format, i.e. it remains in the structure without pages:

```json
{
	"_id": "R9Kxh82L2DjiXWH9",
	"name": "Chapter 01: Introduction",
	"content": "<h1 style=\"text-align:center\">Welcome to Call of Cthulhu!</h1><p>-lots-cut-out-here-</p>",
	"img": "modules/coc-keeper-comp/images/call_of_cthulhu_7th_edition__rulebook_v1.6-Image-029.webp",
	"folder": null,
	"sort": 0,
	"permission": {
		"default": 0,
		"UFPOGWmai7W3D0dk": 3
	},
	"flags": {
		"core": {
			"sourceId": "JournalEntry.PSKAp2TVEX6W36zh"
		}
	}
```

**Comment by farling42** [comment]
After you're initial failure to reproduce this problem, I wrote a script to manually migrate each of the packs in the module, and I can now edit the packs.  Maybe this script, or some similar notes, need adding to https://foundryvtt.com/article/v10-journal-pages/ to ensure that other users don't get caught by the same problem.

```js
let modulename = "coc-keeper-comp";
const packs = game.packs.filter(pack => pack.metadata.packageName = modulename);
for (const pack of packs)
{
   const locked = pack.locked;
   if (locked) await pack.configure({locked: false});
   await pack.migrate();
   if (locked) await pack.configure({locked: true});
}
```

**Comment by Fyorl** [comment]
I was able to verify that having v9 JEs inside a module compendium does cause this, thank you for following up. I have added some additional wording to the journal migration guide that prompts module owners to migrate their journal compendia.

**Comment by farling42** [comment]
Shouldn't Foundry at least prevent the editing of pages in this situation?

Users could have made quite a few changes to a journal page, only for the error to occur on pressing the SAVE button.
