### ISSUE TITLE
GMs cannot open map notes for journal pages with limited permissions

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8420]
Originally reported by jeremyc#6034 https://discord.com/channels/170995199584108546/956306859491471420/1033819817024700607

**ALL MODULES DISABLED?** Yes  
**Short Description of bug:** When linking a map note to a Journal Page and the default ownership of the Journal is "None", if the page has ownership set to "Limited", the **GM** cannot double-click to open the Journal Page. Ownership works as expected when set to "None" or "Observer".  
**Simple steps to reproduce the bug:**  
* Create a journal, set the default ownership to "None" (default).
* Create a journal page, set the ownership to "Limited" for all players.
* Drag the page onto the map to create a map note.
* Note that double-clicking on the created map note **as the GM** does **not** open up the journal page.
* Change the journal page ownership to "None" or "Observer".
* Note that double-clicking on the created map note now does bring up the journal page properly.

**Console Errors:** None

**Comment by Mythano** [comment]
As further information, if you set the All Players to *Inherit* and set individual players to limited, this now allows the GM to access the map note.  Only adding if this information is needed to track it down.  Cheers.
