### ISSUE TITLE
Vision sources inside the scene rectangle can perceive tokens inside the padding region

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8431]
### What happened?

Detection modes that use the default LOS test are not affected by this issue, because the LOS polygon is restricted to the scene rectangle if its origin is inside it, but, for example, Sense All allows tokens to see other tokens in the padding.

Tokens that are not in the padding themselves shouldn't be able to perceive anything inside the padding at all.

```js
    const sceneRect = canvas.dimensions.sceneRect;
    const inBuffer = !sceneRect.contains(point.x, point.y);

    // Second test basic detection tests for vision sources
    for ( const visionSource of canvas.effects.visionSources.values() ) {
      if ( !visionSource.active || inBuffer && sceneRect.contains(visionSource.x, visionSource.y) ) continue;
      // ...
    }

    // Lastly test special detection modes for vision sources
    if ( !(object instanceof Token) ) return false;   // Special detection modes can only detect tokens
    for ( const visionSource of canvas.effects.visionSources.values() ) {
      if ( !visionSource.active || inBuffer && sceneRect.contains(visionSource.x, visionSource.y) ) continue;
      // ...
    }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Place two tokens; one in the padding, one in the scene rectangle. Give the token inside the scene rectangle Sense All.

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
Now in 10.290 tokens inside the padding cannot see anything that is inside the playable area. Is that intended?

**Comment by Feu-Secret** [comment]
> Now in 10.290 tokens inside the padding cannot see anything that is inside the playable area. Is that intended?

Yes, it is intended. Tokens in the padding are kind out of the playable area.
