### ISSUE TITLE
Steam Integration for Localized Prices

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#8439]
### User Experience

Hi.

The premium modules are very expensive for some countries which don't use dollar. 
Example:
Pathfinder Adventure Path: Abomination Vaults (Foundry VTT): $59.99 in brazilian currency: R$ 319,87
R$ 319,87 is something a very small number of people would pay.

I think the only solution for this is to use steam. The same adventure costs R$ 99,99 for Fantasy Grounds and is cheaper on sales. 

I know the integrate FVTT with steam has problems. But, make A LOT of more people be able to afford premium modules will worth.

A FGU solution is to let the user activate products bought in FGU store on steam and vice versa.
https://www.fantasygrounds.com/store/syncSteamAccount.xcp

**Comment by aaclayton** [comment]
We do not use Steam. Sorry.
