### ISSUE TITLE
Remove CTRL+WASD Pan keybindings

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#8440]
### What happened?

CTRL is a special modifier for all the `Move or Pan` controls, specifically for Panning, but CTRL+A is also the keybind for the `Select All Objects` control, so there's no way to Pan to the Left.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Press CTRL + W/S/D.
2. Press CTRL + A.

### What core version are you reporting this for?

V10.288

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by cswendrowski** [comment]
This has always been an awkward keybinding. CONTROL + WASD was never actually supported for canvas pan for this reason, but we are opting to remove the default WASD bindings entirely since we aren't a game and those keys are better used for other actions.
