### ISSUE TITLE
Updating both position and texture of a token in the same update causes the token to move out-of-sync with any interface drawings

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8445]
Originally reported by Freeze#2689 https://discord.com/channels/170995199584108546/956306859491471420/1035237584726671471

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, electron app  
**Short Description of bug:** When updating both position and texture of a token at once the token position isnt updated properly until x time passes or the canvas is clicked  
**Simple steps to reproduce the bug:** write an update for a token with both a change in position and texture.src  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/198588659-708e1c5c-f6e5-4643-b683-c746948b18a9.png)

**Comment by Fyorl** [comment]
I was not able to reproduce this when running the following macro:

```js
if ( !token ) return;
const {x, y} = token.document;
const {size} = canvas.dimensions;
token.document.update({
  'texture.src': foundry.documents.BaseActor.DEFAULT_ICON,
  x: x + size,
  y: y + size
});
```

Event Ctrl+Z to undo correctly reset the texture and position in a single step without delay.

**Comment by dev7355608** [comment]
The test token probably had the default icon already. The icon needs to change:
```js
_token.document.update({
    'texture.src': _token.document.texture.src !== 'icons/svg/mystery-man.svg'
        ? 'icons/svg/mystery-man.svg' : 'icons/svg/skull.svg',
    x: _token.document.x + canvas.dimensions.size,
    displayBars: 50,
    displayName: 50
});
```

**Comment by Fyorl** [comment]
> The test token probably had the default icon already.

It did not.


https://user-images.githubusercontent.com/207433/198682107-8ee59c4c-e2cf-4528-8be6-ad3a8f72b74a.mp4

**Comment by dev7355608** [comment]
Only the icon and border move but other elements do not:
![image](https://user-images.githubusercontent.com/31905376/198683947-c10e2268-7c09-4489-ae05-9e365ebf08a5.png)

**Comment by Fyorl** [comment]
OK, so the update happens correctly, the issue is with interface synchronisation.
