### ISSUE TITLE
Need to prevent editing of journal entries if the underlying db is still in V9 format

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#8448]
### What happened?

Foundry allows me to start editing a page of a journal, and it is only when I press the Save button that I get an error reporting that it wasn't possible to save the page.

This occurs when editing entries in a compendium stored in a module - these compendiums are not automatically updated to V10 format by Foundry.

See https://github.com/foundryvtt/foundryvtt/issues/8417 for the error report generated by Foundry V10.

Foundry should prevent editing if there is no chance that the Save button is actually going to save the edits.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Have a compendium module that was originally created in V9.
Create a world in V10 which has this module enabled.
Edit a page within one of the journals.
Press the Save button - see an error.

### What core version are you reporting this for?

Version 10.288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@dev7355608 could you take a look at this issue and #8448 to ensure that our new v12 server-side migration correctly gets a pre-v10 Journal into a working v12 state?
