### ISSUE TITLE
Convert dice box expand/contract to CSS transitions

### ISSUE THREAD

**Issue by gbursson** [foundryvtt/foundryvtt#8449]
### What happened?

Dice box result in chat cannot be made "open" permanently, as the CSS style affecting it is inlined:
![image](https://user-images.githubusercontent.com/1756600/198746010-9aad458a-9400-46ec-a32c-161626593209.png)

That setting should be moved to a class, as it was done before. 
Right now using Custom CSS module, I cannot modify the display due to CSS specificity rules.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

Using developer tools, navigate to element <div> with a class of "dice-tooltip". 
As inline CSS style is used, that cannot be modified using custom CSS

![image](https://user-images.githubusercontent.com/1756600/198746315-12fe4db3-cbc8-4844-a437-1323ef0e9fb8.png)

### What core version are you reporting this for?

V10 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I can't find evidence of this having changed in v10. It still uses jQuery's `slideUp` and `slideDown` which are applying these inline styles, but that has been the case since at least v6.

**Comment by Fyorl** [comment]
No update from the reporter so I'm removing the bug tag as I wasn't able to determine any regression in behaviour here. Re-framing this as a feature in a later version to use pure CSS transitions here rather than jQuery animations.
