### ISSUE TITLE
Make the "Show Players" "Show To: All Players" tick box to change Ownership Configuration on "All Players" section

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/foundryvtt#8450]
### User Experience

On Journals, either on the whole Journal or each page, there is the 
![image](https://user-images.githubusercontent.com/33260912/198336656-cbdd57cf-0493-4f66-9702-98a23a9b6ed9.png)
a button that pops up a configuration window
![image](https://user-images.githubusercontent.com/33260912/198336763-fde53ad2-b2c8-4b4f-86c9-2f4b31405622.png)
where you can change ownership depending on which tick is ticked.
However, the "All Players" tick box edits the ownership on all players instead of just the "All Players" section on the Ownership Configuration window
![image](https://user-images.githubusercontent.com/33260912/198337290-a2784c9a-ecce-4eca-9933-3a2932300c8a.png)
This is confusing because you can have "All Players: None" and each player might for example be an Observer, but then the Eye icon still looks like no one but the DM can see the journal page
![image](https://user-images.githubusercontent.com/33260912/198337707-467ac3b5-e7b0-4ba0-848a-f22e81e4b968.png)
Would be nice if the "All Players" tick box while showing the page to players would edit the "All Players" Ownership Configuration and not individual rights. (If specific players are selected, it will work exactly as now. Maybe some additional icons to discern who actually can see what would be nice.)

_Tested on a clean new world without modules._

**Comment by aaclayton** [comment]
Agree with this suggestion, if "All Players" checkbox is combined with a "Configure Ownership" directive we should apply that ownership level as the default one for the document. Good catch.
