### ISSUE TITLE
premium adventure uninstall button

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#8451]
### User Experience

with premium modules, they ask you to install and import all sorts of data for the adventure. which is great. but when you are expected to have unused data frozen in a compendium so that foundry runs smooth i can see it causing problems especially when you run something like pathfinder 2 and you are pulling from 6 books. by the time you are at your 6th installment you have 5 books being unused and taking up space whilst also being front loaded and not frozen into a compendium. this would cause games to run a bit slower or slower to load in. could there be something added to premium modules to remove what they added so that when you install a new book you only need the current data front loaded rather than all the other adventures/books loaded and all that data.

im mainly asking would it be possible to reverse module imports with the same automation as importing them for ease of use to the consumer

**Comment by aaclayton** [comment]
Thanks for your suggestion, but after discussion with the team we feel that this is not a feature we will add. Content can be deleted manually, and it is best practices for premium packages to import all their content within a single root-level folder which makes it easy to delete all that content for a certain document type.

**Comment by ThingsCouldGetDicey** [comment]
> Thanks for your suggestion, but after discussion with the team we feel that this is not a feature we will add. Content can be deleted manually, and it is best practices for premium packages to import all their content within a single root-level folder which makes it easy to delete all that content for a certain document type.

i understand my other suggestion is a big task to solve this and it comes from the idea of freezing tracks in audio. when you freeze a track in an audio production software like a daw. you can still use the information but whatever processing that has been done to it is frozen its no longer drawing from all the effects or whatever metadata is attatched to it. it can be played back but it cant be altered until its loaded back into the ram and unfrozen. 

my idea is that if we could async freeze stuff that isnt being used in compendiums and only use stuff on the canvas. it would drastically reduce the need for compendiums.  currently compendiums are frozen but if you could load as much as you wanted without having to drag in things from a compendium but have it frozen on the back end because it isnt being used then you wouldnt have a bottlneck in performance. im just using my imagination here but i would think the same logic that is used to process and freeze tracks in a daw could be applied to what is and what is not on the canvas. just a thought.
