### ISSUE TITLE
Support flags in the schemas used in Array/Set fields

### ISSUE THREAD

**Issue by ghost91-** [foundryvtt/foundryvtt#8458]
### User Experience

Foundry currently uses `ArrayFields` with nested schemas (`SchemaField`) to model arrays of nested data structures in documents. `SetField`s can be used in a similar way. This is currently used for `BaseActiveEffect.changes`, `BaseCard.faces`, and `BaseToken.detectionModes`.

Modules sometimes need to attach custom data to individual elements of these arrays. The solution for attach custom data to documents are flags. However, flags are just at the top level of documents, so currently, you would need to create some data structure in a flag that has information about which element in the array it corresponds to. This is complicated and prone to break, since you always need to make sure that the flag and the array stay in sync.

In order to solve this problem in a better way, it would be nice if the schemas of these array/set fields supported `flags` themselves, by including `flags: new fields.ObjectField()`. That way, modules could easily attach arbitrary to individual array elements.

This of course raises the question whether there should also be a form of `getFlag`, `setFlag`, and `unsetFlag` that can deal with these “nested” flags. While I think this is nice to have, it's not necessary for a first step. Just having the flags in the would already enable a bunch of use cases that are currently difficult/annoying. And properly getting these methods to work might be more difficult than it's worth.

There is also a precedent for having these nested `flags`: The schemas for manifest files (system.json, module.json, world.json) already support `flags` on their `SetField`s that contain schemas (`authors`, `media`, `languages`,  `packs`). This would basically just extend the concept to documents.

**Comment by aaclayton** [comment]
We cannot sustain a paradigm where every single object throughout our data modeling ecosystem contains the possibility of arbitrary flags. This functionality is and should be limited to primary documents and embedded documents.

**Comment by ghost91-** [comment]
That's very unfortunate. What is your recommended solution for cases like when a module needs to attach custom data to an `EffectChange`?

(It's also not like this would need to be done in many places, I was just able to find 3...)

**Comment by aaclayton** [comment]
> That's very unfortunate. What is your recommended solution for cases like when a module needs to attach custom data to an `EffectChange`?
> 
> (It's also not like this would need to be done in many places, I was just able to find 3...)

The best available solution for you is to store that additional data as a flag on the Active Effect, probably as an array where the indices of your flag array match to the indices of the changes array.
