### ISSUE TITLE
Certain measured template configurations can lead to unexpected highlighting of grid spaces

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8459]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1035571775280517192

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Electron/Any  
**Short Description of bug:** Measured templates give inconsistent or unexpected grid highlighting with some template setups.  
Simple steps to reproduce the bug: Aim cone template upwards and center origin in cell.  
Alternatively: Center in intersection and point one left and another right.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/199269488-7c8a6c66-8417-4391-92b0-143429e0bbe3.png)

![image](https://user-images.githubusercontent.com/207433/199269525-0205187e-8377-4b88-b18e-ce35fbca70c0.png)

**Comment by Fyorl** [comment]
This is caused by certain rounding considerations, so it has not been tagged as a bug, but it would be nice to have these behave a little more intuitively and consistently.

**Comment by dev7355608** [comment]
Points on the boundary aren't necessarily contained in the pixi shape even assuming infinite precision; it isn't just a purely rounding related issue. For example:
 ```js
p = new PIXI.Polygon([0, 0, 1, 0, 0, 1])
console.log(p.contains(0, 0)) // true
console.log(p.contains(0.5, 0)) // true
console.log(p.contains(0, 0.5)) // true
console.log(p.contains(1, 0)) // false
console.log(p.contains(0, 1)) // false

p = new PIXI.Polygon([0, 0, -1, 0, 0, -1])
console.log(p.contains(0, 0)) // false
console.log(p.contains(-0.5, 0)) // false
console.log(p.contains(0, -0.5)) // false
console.log(p.contains(-1, 0)) // false
console.log(p.contains(0, -1)) // false
```

The quick and simple solution would be to test multiple points in a small neighborhood:
```js
  // BaseGrid#_testShape
  _testShape(x, y, shape) {
    return shape.contains(x, y)
      || shape.contains(x, y - 0.5)
      || shape.contains(x, y + 0.5)
      || shape.contains(x - 0.5, y)
      || shape.contains(x + 0.5, y)
      || shape.contains(x - 0.5, y - 0.5)
      || shape.contains(x - 0.5, y + 0.5)
      || shape.contains(x + 0.5, y - 0.5)
      || shape.contains(x + 0.5, y + 0.5);
  }
```

**Comment by caewok** [comment]
I like @dev7355608's approach. I would not, however, call that many `contains` methods in a row. Instead, I would probably build a `containsAnyPoints` method that lets you test multiple points at once, and return early if any are true. This would avoid multiple cycles through the polygon edges and probably be worth it if you are testing a bunch of points like that. In the [`PIXI.Polygon.prototype.contains`](https://pixijs.download/dev/docs/packages_math_src_shapes_Polygon.ts.html) method, for example, I would build a comparable method where it tests all the provided points inside the `for` loop, exiting early when possible.

(You could create a polygon contains method using a robust orientation method, which would get you a consistent answer but it would almost certainly be slower. It may also still require enlarging the boundary slightly as the answer might be consistently "no" when you want "yes." )

**Comment by dev7355608** [comment]
A polygon-circle intersection test would be preferable to testing multiple points, I think. Testing multiple points is just a quick and easy fix that doesn't require to implement improved containment checks for all shape types. Not sure if testing 9 points is really a noticeable performance impact. I'd say it's more important that templates highlight the grid reliably than a slight performance hit.
```js
function intersectsCircle(polygon, x, y, radius) {
    if (polygon.contains(x, y)) {
        return true;
    }

    const points = polygon.points;
    const m = points.length;
    const rr = radius * radius;

    for (let i = 0, x1 = points[m - 2], y1 = points[m - 1]; i < m; i += 2) {
        const x2 = points[i];
        const y2 = points[i + 1];
        const dx = x - x1;
        const dy = y - y1;
        const nx = x2 - x1;
        const ny = y2 - y1;
        const t = Math.clamped((dx * nx + dy * ny) / (nx * nx + ny * ny), 0, 1);
        const x3 = t * nx - dx;
        const y3 = t * ny - dy;

        if (x3 * x3 + y3 * y3 < rr) {
            return true;
        }

        x1 = x2;
        y1 = y2;
    }

    return false;
}
```

The `contains` method of Rectangle has the same problem as Polygon; that's why the width and height is increased by 1 pixel in `_getRectShape` to counteract this problem. The padding could be removed with an improved `_testShape`.
