### ISSUE TITLE
Make Token.animate's mirroring animation faster

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#8477]
### User Experience

Mirroring = toggling a token's "Mirror Image" setting, either horizontally or vertically, which change that token's `texture.scaleX/Y`.
On `Token.animate`, when there's no `duration` set, it calculates the duration based on the x/y changes and/or rotation, otherwise it defaults to 1000ms, which is really slow for the mirroring.
I request to add logic to make the mirroring animation faster, between (1000 / 6) up to 500 (the maximum animation speed for rotation with movementSpeed 6).

For reference, this is the vanilla animation when updating `scaleX` (duration: 1000)
![Animação2](https://user-images.githubusercontent.com/5288872/200064011-34947c67-dd7e-415e-a721-447766bc9e16.gif)

This is how it would look like if the duration was (1000 / 3).
![Animação3](https://user-images.githubusercontent.com/5288872/200064768-99f81126-37ce-419d-9b78-847e974cabaa.gif)

The relevant code on `Token.animate`:
```js
   // Configure animation duration aligning movement and rotation speeds
    if ( !duration ) {
      const durations = [];
      const dx = a1.x - a0.x;
      const dy = a1.y - a0.y;
      if ( dx || dy ) durations.push((Math.hypot(dx, dy) * 1000) / (canvas.dimensions.size * movementSpeed));
      if ( dr ) durations.push((Math.abs(dr) * 1000) / (movementSpeed * 60));
      if ( durations.length ) duration = Math.max(...durations);
    }
```

My suggested change:
```js
   // Configure animation duration aligning movement and rotation speeds
    if ( !duration ) {
      const durations = [];
      const dx = a1.x - a0.x;
      const dy = a1.y - a0.y;
      if ( dx || dy ) durations.push((Math.hypot(dx, dy) * 1000) / (canvas.dimensions.size * movementSpeed));
      const dScaleX = Math.abs(a1.texture.scaleX) - Math.abs(a0.texture.scaleX);
      const dScaleY = Math.abs(a1.texture.scaleY) - Math.abs(a0.texture.scaleY);
      if ( dScaleX || dScaleY ) durations.push(1000 / 3);
      if ( dr ) durations.push((Math.abs(dr) * 1000) / (movementSpeed * 60));
      if ( durations.length ) duration = Math.max(...durations);
    }
```

**Comment by aaclayton** [comment]
I don't think its scalable for us to set a bespoke default animation duration for every token attribute. The fact that we have special cases for movement and rotation already feels ugly to me. I will think on this, but I think that perhaps the recommended approach would be for the caller of `Token#update` to specify a faster duration as part of the update if they are trying to achieve a certain visual effect.

**Comment by mclemente** [comment]
Not sure if related to this issue specifically, but V11 turned `CanvasAnimation._animateFrame` private and made it impossible to wrap it to skip specific animations as part of multiple movements (e.g. rotating token mid-movement), so the solution I had for my module on V10 is no longer possible.

Is there any chance you can revert that change?

**Comment by Feu-Secret** [comment]
We have improved the token animation framework for enhanced developer usability. Closing this issue.
See: https://github.com/foundryvtt/foundryvtt/issues/9787
