### ISSUE TITLE
"Compatibility Risk: verified for version 10" when module.json only specifies v9 compatibility

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#8478]
### What happened?

In the module listing, there is a red (or could be yellow?) "10" in the box for the module "Item Containers".  (span with classes "tag unknown".

In the module.json for "Item Containers" is contains:

```json
    "compatibility": {
      "minimum": 9,
      "verified": 9,
      "maximum": 9
    },
```

Thus the warning in the Module listing is clearly wrong. The displayed number in the module listing should be "9".

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Start foundry, ensure "Item Containers" module is installed.

Go to the "Add-On Modules" tab of the admin page.

Observe "10" displayed in the compatibility warning for "Item Containers".

### What core version are you reporting this for?

Version 10 build 288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
That module has a v10 release; isn't really clear what state your install is in.

**Comment by farling42** [comment]
It looks different this morning. No warning. But it definitely was an issue that I was seeing last night.
Maybe it is a side-effect of the known issue about the compatibility warning not updating after doing an "update all" on the module list.

**Comment by aaclayton** [comment]
I suspect this is a side-effect of compatibility tags not updating properly upon module update. Closing this one as duplicate.
