### ISSUE TITLE
Simplify interpolation logic for texture depth in the InverseOcclusionSamplerShader

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8490]
### What happened?

Radial and Vision occlusion doesn't work properly on roof tiles stacked on top of each other. Opacity of the occlusion changes depending on elevation of the second token in this configuration: 
![image](https://user-images.githubusercontent.com/31905376/200362239-d633127c-277e-4bdd-bae5-9b748954174d.png)

`InverseOcclusionSamplerShader` does some weird interpolation on depth values in the case of roof tiles. Fix:
```diff
-     float tex = roof ? 1.0 - smoothstep(0.19, depthElevation, occlusionElevation) 
-                      : 1.0 - step(depthElevation, occlusionElevation);
+     float tex = 1.0 - step(depthElevation, occlusionElevation);
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Two overhead roof tiles with radial occlusion mode.

Green tile: elevation = 20
Red tile: elevation = 0
Token 1: elevation = 0
Token 2: elevation = -30

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I believe our current stance that we reached concensus on is that we are not going to make an effort to improve the behavior of multiple roofs stacked on top of each other at this time. That work would be part of the technical redesign and suite of improvements that would come alongside us addressing Scene Levels.

@Feu-Secret do you agree with that concensus? Or is this an issue that we should try and prioritize improving in V10? Is the fix that @dev7355608 suggests in the issue one that we can or should apply in the absence of a more fully-featured solution?

**Comment by Feu-Secret** [comment]
@aaclayton Agree with you on that. We should postpone this issue until Scene Levels.
