### ISSUE TITLE
Rename manifest link in manifests to be clearer on its purpose

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8499]
### User Experience

The `manifest` field in manifests is endless source of confusion for new developers, commonly people seem to think it needs to point to current release's manifest.

It should instead be labeled something more clear about its purpose as the link to checking for update, or preferably link to latest version.

I don't have good suggestion for naming this, but `update` could work, even if it's not clear it wants a manifest (though mind, download is not clear it wants a .zip). Something better can probably be made up.

Aside: It's also very confusing to talk about the manifest your manifest in your manifest file points to with current wording (this is not a joke btw, this is a very real problem).

**Comment by aaclayton** [comment]
I realize this can be a source of confusion, but we should pursue other avenues to improve documentation and understanding of the field definition without changing the name - which our team believes is the best name for the field.
