### ISSUE TITLE
`DataModel#updateSource` doesn't return an empty object even though nothing changed

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8503]
### What happened?

I expect this to be true: `isEmpty(doc.updateSource(doc.toObject())) === true`.

![image](https://user-images.githubusercontent.com/31905376/200880835-fd3924ad-0c39-42ff-9e7d-e2ebb2454bf9.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
_token.document.updateSource(_token.document.toObject())
```

vs.

```js
diffObject(_token.document._source, _token.document.toObject())
```

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Closing as duplicate.
