### ISSUE TITLE
Darkvision rendering doesn't work properly when multiple tokens are selected

### ISSUE THREAD

**Issue by Zamrod** [foundryvtt/foundryvtt#8507]
### What happened?

Darkvision rendering doesn't work properly when multiple tokens are selected.
The turning of dim light into bright light does not function and if one token cannot see an area it is always rendered in greyscale even if in light.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Use this scene and select multiple tokens.
[fvtt-Scene-greyscale-test2.txt](https://github.com/foundryvtt/foundryvtt/files/9992121/fvtt-Scene-greyscale-test2.txt)

### What core version are you reporting this for?

Version 10.290

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@TheElderMindseeker commented:

### What happened?

When several player tokens share vision and at least one of them has darkvision, the shared vision in light becomes greyscale (as if in dark) even though it should be in color (as if in normal vision).

Although I like how certain characters with dark vision make everything go noir, I suppose it's a bug from technical point of view.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a world with Pathfinder 2e or DnD 5e system (probably would work with any system) without any add-on modules. Create a player (or a trusted player) in the User Management. Create two player-owned sheets (Player Character) and assign ownership to the created player. Assign Darkvision of at least 120 ft to one of the tokens but leave only Basic Vision to the other (either through Rules-Based Vision or manually in Token Settings/Vision).

Create an empty scene with non-grey color such as (HEX 7382f2) big enough to place 60 ft light (2000 px by 2000 px is good). Enable Token Vision and, optionally, Fog Exploration on this scene. Activate the scene. Place a light with 60 ft dim light and 30 ft bright light somewhere in the corner. Transition the scene to darkness using Light Controls.

Place both actor tokens in the dim light area (or just somewhere on the map). Log in as a player. The scene should look okay with colorized lit area and greyscale out-of-light area. Select and then de-select token with Basic Vision. All should remain okay. Select and de-select token with Darkvision. Now the lit area is greyscale though it should be colorized. Selecting Basic Vision token gets the vision right until de-selected. Note: in DnD 5e the scene colors are greyscale even without selecting/de-selecting tokens.

Here is how the light setup of the scene should look like:

![Foundry Vision Bug](https://user-images.githubusercontent.com/14041854/202847929-860f9b9f-d20e-4d38-98a0-877e40db6d24.png)

Here is the demonstration of the effect:

https://user-images.githubusercontent.com/14041854/202847866-f9ad9f29-a8e8-4aec-b72e-a2c26336f1e7.mp4

Video captured on V10 build 290 with Pathfinder 2e 4.4.0 on Linux machine;
Bug reproduced in Chrome, Firefox and Native App (Electron);
Bug reproduced using Pathfinder 2e 4.4.0 and DnD 5e 2.0.3;
Bug reproduced both on Linux and Windows. Mac unavailable.



### What core version are you reporting this for?

Version 10 build 290

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Yesat commented:

It was reported with #8061 and then closed. 
I have setup a quick scene with an "observer" player who doesn't control any token but can see everything the other token see. 
The map:
![image](https://user-images.githubusercontent.com/23231221/202905841-7656d81b-0cab-419a-b3e6-87b627e243b3.png)
The token without darkvision: 
![image](https://i.imgur.com/GRuTDMV.png)
The tokens with darkvision:
![image](https://i.imgur.com/VF7c0IP.png)
![image](https://i.imgur.com/Nq4nA0q.png)
The observer POV, with everything in grey scale and no module loaded.
![image](https://user-images.githubusercontent.com/23231221/202905982-48e60a98-ac2c-4a01-8029-4303d62e64e6.png)
