### ISSUE TITLE
When double-clicking on a placed map note to open its journal entry, that entry should be maximized if it was already rendered but in a minimized state.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#8514]
### User Experience

my current user experience is that when i have something minimised and i am using journal notes that are placed on the canvas. id love for my double click on the journal icon to expand and bring focus to the journal im double clicking on. the same goes for actor sheets and npc sheets once they are minimised.

currently what happens is the minimised journal changes to the current journal clicked but stays minimised rather than pulls focus and expands. then this results to me trying to find the minimised journal or npc/actor and when you are gming you may have quite alot open. so im finding myself spending alot of time trying to find where i put the thing im double clicking on and wondering why it isnt expanding. this improvement would help my workflow. 

many thanks.

**Comment by ThingsCouldGetDicey** [comment]
this also affects anything minimised. including compendium folders or any folders that have been popped out. or tabs being popped out.

**Comment by ThingsCouldGetDicey** [comment]
just to update to this i found a module that could do this but i think this behaviour really should be core. if you can absorb this into core i would really appreciate it. https://foundryvtt.com/packages/qol-maximize-reopened-sheets

**Comment by aaclayton** [comment]
This change was made in V12.
