### ISSUE TITLE
Creating a new World does not add an initial Version value to the World.JSON.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8515]
### What happened?

Creating a new World does not add Version to the World.JSON.

![image](https://user-images.githubusercontent.com/66535080/201615677-a8df81ab-3979-44d4-8d99-674dc08619b8.png)

https://discord.com/channels/170995199584108546/956306859491471420/1039358005805846558

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a new world in **Configuration and Setup**.
2. Check version.

### What core version are you reporting this for?

Version 10 Stable Build 290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
It's a bit unclear what this world version *should* be, we could choose something as a convention like `0` or `1`, or `1.0.0`, but it would be making an assumption either way. Perhaps it is better that world manifests are "unversioned" unless created by a package author that specifically wants to version-control them?

**Comment by mkahvi** [comment]
Leave it undefined but don't display version if it's undefined?

**Comment by aaclayton** [comment]
Yes, that is a sensible suggestion.
