### ISSUE TITLE
When using Hex Grid, Initial load of a map with a Background Image Scale different of 1 makes tokens appear with wrong scale.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8520]
### What happened?

 Initial load of a map with a different Background Image Scale has the token as a different size, I think it is using the default scale value. 
 
 Original Report: https://discord.com/channels/170995199584108546/956306859491471420/1041012239924219954

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Load a map with a hex grid using a different scale than the default of 1 and the tokens on that map have a scale of 1 until you go into the map options and hit save and it reloads the map with the correct scale.
First image is initial load of map, and second image is after I update the scale again.

![image](https://user-images.githubusercontent.com/66535080/201630569-bd7ee96f-d7ba-4965-a8d7-442f8707721b.png)
![image](https://user-images.githubusercontent.com/66535080/201630594-ecf3318d-f83c-458c-ad55-2fb2dd0c2641.png)

### What core version are you reporting this for?

Version 10 Stable Build 290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
I can't reproduce this issue. It is working fine in my environment. I need a second opinion.

**Comment by davelamorte** [comment]
Hello, it happens to me as well, only with hexagon, this is the settings of the maps:
![image](https://user-images.githubusercontent.com/46324776/201880565-6bab3f7a-0d5a-4fef-a7bf-fc4fa07ace3a.png)
![image](https://user-images.githubusercontent.com/46324776/201880614-2e5c32d0-53ab-4110-bd5e-257939849818.png)
![image](https://user-images.githubusercontent.com/46324776/201880640-0f22baee-3e63-4bab-a704-90c31f56a693.png)

**Comment by davelamorte** [comment]
Sorry, I forgot to specify, that behavior was before entering the settings and saving without doing any modification.
And this is after saving, all ok again. 
![image](https://user-images.githubusercontent.com/46324776/201881052-5ea6b13d-5e5e-4655-a011-5ff8e1e02fce.png)

If I switch to another map, and come back, it's broken again.
I'm using Foundry's server+client integrated, self-hosted.

**Comment by davelamorte** [comment]
OK, I found out a way to reproduce it.
GRID OPACITY has to be set at zero.
If it isn't set at 0, it works perfectly. Even 0.05 is enough to trigger the correct behavior. Only when it's set at 0 it doesn't work.

I hope this helps!

**Comment by Feu-Secret** [comment]
@davelamorte Useful information! Thanks.

**Comment by barrucadu** [comment]
Hey, in case you need any more information, I'm experiencing a very similar issue right now, and I believe it's because `_computeHexGridDimensions` is only called inside `draw`, which is only called if the grid is visible.

So I was able to work-around the issue by adding a macro which just runs:

```
canvas.grid.grid._computeHexGridDimensions(canvas.dimensions.size);
```
