### ISSUE TITLE
Searching a compendium entry with a research string containing an apostrophe is failing.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8522]
### What happened?

in compendium when searching Fortune’s Wheel there is no entries but searching for Fortune gives the exact entry "Fortune’s Wheel"

Original Post: https://discord.com/channels/170995199584108546/956306859491471420/1041332997967839332

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

in compendium when searching Fortune’s Wheel there is no entries but searching for Fortune gives the exact entry "Fortune’s Wheel"

Note from @Feu-Secret: Not able to reproduce it in my environment.

### What core version are you reporting this for?

Version 10 Stable Build 290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by silvative** [comment]
Also not able to repro 
![image](https://user-images.githubusercontent.com/66365038/202016500-6494930d-08ea-4cb4-9f7c-ba820e001cc8.png)
