### ISSUE TITLE
PlaceablesLayer._draw not restoring visibility of objects PIXI container

### ISSUE THREAD

**Issue by SethGallucci** [foundryvtt/foundryvtt#8528]
### What happened?

```js
// PlaceablesLayer._draw

async _draw(options) {

  // Clear quadtree
  if ( this.quadtree ) this.quadtree.clear();

  // Create objects container which can be sorted
  this.objects = this.addChild(new PIXI.Container());
  this.objects.sortableChildren = true;


  // -------------------------------------------------------------------------
  this.objects.visible = false; // <---- Visibility of container set to false.
  // -------------------------------------------------------------------------


  if ( this.constructor.layerOptions.elevationSorting ) {
    this.objects.sortChildren = this._sortObjectsByElevation.bind(this.objects);
  }

  // Create preview container which is always above objects
  this.preview = this.addChild(new PIXI.Container());

  // Create and draw objects
  const documents = this.getDocuments();
  const promises = documents.map(doc => {
    doc._destroyed = false;
    return doc.object?.draw();
  });

  // Wait for all objects to draw


  // ----------------------------------------------------------------------------------
  this.visible = true; // <---- Visibility of layer (instead of container) set to true.
  // ----------------------------------------------------------------------------------


  await Promise.all(promises);
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a new world.
2. Log into the world.
3. Create a new scene.
4. Add a `PlaceableObject` to the scene.
6. In the console, call the `draw` method of the layer onto which the `PlaceableObject` was added. (eg: `canvas.notes.draw();` if a Note was added).
7. Observe that all `PlaceableObject`s of that layer have disappeared. Note that if you chose to add a `Drawing`, you will still see the drawing (possibly another bug), but you won't be able to interact with it; templates behave similarly.
8. In the console, set the `visible` property of the `objects` container of the previously chosen layer to `true` (eg: `canvas.notes.objects.visible = true;`).
9. Observe that the `PlaceableObject`s reappear and have their interactability restored.

### What core version are you reporting this for?

Version 10 - Build 290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Yes, `objects` container `visibility` is by default `false`. The visibility is then updated with layer `activation` or `deactivation` (to avoid flickering problems I suppose). The consequence for this behavior for the API is that now we need a subsequent call to `activate` or `deactivate`, or a manual assignment to make it work properly.

@aaclayton Maybe we could add an option to force objects visibility to true?
