### ISSUE TITLE
Clear targets with Left Click Release doesn't broadcast to other users

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8530]
### What happened?

Because `User#updateTokenTargets` doesn't broadcast the targets, `TokenLayer#_onClickLeft` needs to:
```js
      // Clear targets if Left Click Release is set
      case "target":
        if ( game.settings.get("core", "leftClickRelease") ) {
          game.user.updateTokenTargets([]);
          game.user.broadcastActivity({targets: []});
        }
        break;
```

Assuming `User#updateTokenTargets` is working as intended, the documentation should mention that the targets are not broadcast, because the expectation might be that it does.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Enable *Left-Click to Release Objects*.
- Select Target tool.
- Target token.
- Clear targets by clicking the canvas.

For other users it still shows the token as targeted.

### What core version are you reporting this for?

Version 10 Stable 5 (build 290)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
`User#updateTokenTargets` is working as intended here. broadcasting the activity is a separate action (in the `User` class) that should be called if it is necessary (per example, in the event that is the subject of this issue => this is a bug).
