### ISSUE TITLE
Unsupported keys in package manifest files should generate a package warning that is surfaced to the developer.

### ISSUE THREAD

**Issue by gizmo2342** [foundryvtt/foundryvtt#8550]
### User Experience

This is a followup to https://discord.com/channels/170995199584108546/930898124782829638/1042035412992008243

Although the main issue happened to be a typo (`relationship` instead of `relationships`), a check for unknown keys would have saved me (and possibly others) a lot of time.

**Comment by aaclayton** [comment]
I think we should perhaps generalize this for all `DataModel` instances by adding an option to the constructor that would raise warnings if encountering keys in the input data which are not supported by the schema. We could then use that option in the case of loading package manifests and add any generated warning messages to the array forwarded to the client.

**Comment by gizmo2342** [comment]
I like that approach, even if it means that it is a v11 feature.

**Comment by mkahvi** [comment]
Like with a lot of developer oriented warnings, this kind of warning should not be shown to normal end users. It has no purpose for them and just increases warning noise for them about things they have zero need or ability to do anything about.

**Comment by aaclayton** [comment]
A good restriction to put in place in time for V12 to encourage developers to update to best practices with these manifest files.

**Comment by aaclayton** [comment]
Shifting to HIGH priority to do before V12 stable.
