### ISSUE TITLE
Protected packages will no longer attempt to soundgrade

### ISSUE THREAD

**Issue by gizmo2342** [foundryvtt/foundryvtt#8551]
### What happened?

When doing an update on a certain system/module or an "Update All" it sometimes happens that the system.json/module.json file is rewritten. In these cases the `protected: true` flag that is required for premium content is also removed.

I understand that this is necessary to avoid conflicts with the `signature.json` file, but to be honest: what is the `protected: true` flag good for if it's removed the moment it is in the way? How does this affect the protection of premium content?

I identified two cases in which a rewrite takes place:
- if sidegrade is done
- if foundry wants to correct something in the manifest

In the second case I was not able to clearly identify what must be "wrong" so that foundry does rewrite the manifest. But I can clearly say that it's not based on sidegrade. It also happens to newer versions that have not yet been registered with the module.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

see above

### What core version are you reporting this for?

Version 10 (build 290)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by gizmo2342** [comment]
Further remark to sidegrade: I personally dislike the fact that system.json/module.json get modified by Foundry. I would suggest that all these sidegrade information are stored in a seperate file (e.g. in the config folder) and only be applied in memory.

A modification of the system.json/module.json should only be done if explicitly invoked by a user (API call).

**Comment by aaclayton** [comment]
I think we need to get @cswendrowski to look carefully at this case.
