### ISSUE TITLE
Modules which were previously active should be automatically disabled if their dependencies are no longer satisfied.

### ISSUE THREAD

**Issue by gizmo2342** [foundryvtt/foundryvtt#8556]
### What happened?

This is related to #8555.

![grafik](https://user-images.githubusercontent.com/64664847/203950783-43509615-23e0-4bb0-b051-31677edf7567.png)

After uninstalling a dependent module (in this case CompendiumFolders) the tooltip claims that the activated module cannot be enabled instead of stating what dependency is missing.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Install a module including its dependencies.
2) Activate the module and its dependencies.
3) Return to setup and delete the dependency.
4) Launch the world again and check the Module Management.

### What core version are you reporting this for?

Version 10 (build 290)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
What is misleading here? The module cannot be enabled because there are missing dependencies.

**Comment by gizmo2342** [comment]
The module "is" already enabled (as it had been enabled before the removal of the dependency), so stating it cannot be enabled neglects this fact. Instead there should be a warning that a dependency is missing, ideally including which dependency is missing.

**Comment by aaclayton** [comment]
I see, so the module remains functionally enabled in this case?

**Comment by gizmo2342** [comment]
Yes. The module remains active, but might not be working properly. And there is no good hint, not on world launch, not in the Module Management dialog and not in the setup.

Ok, "misleading" might be the wrong word. Apologies, but I'm not a native speaker.

**Comment by aaclayton** [comment]
Scoping for V11 consideration.

**Comment by gizmo2342** [comment]
If you're going to disable such modules, please do not disable them silently!

**Comment by cswendrowski** [comment]
This should already be resolved in the latest V11 Testing 1 build, please let me know if that's not the case
