### ISSUE TITLE
`VisionSource#sourceType` is `"vision"` instead of `"sight"`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8562]
### What happened?

I assume `VisionSource#sourceType` should be `"sight"` instead of `"vision"`, because `PointSource#sourceType` is supposed to be one of `CONST.WALL_RESTRICTION_TYPES`, correct?

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 5 (build 290)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Yes, this seems to be a harmless (in core) error. We can probably change it in a V10 patch but we'll need to verify that there are no downstream consequences. Otherwise it might need to be a V11 fix.
