### ISSUE TITLE
Drawing text is visible on sections of the scene that are not otherwise visible to the selected token

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8565]
Originally reported by Centricus#1321 https://discord.com/channels/170995199584108546/956306859491471420/1046278813203566773

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Tested hosting via Linux (Node JS) and Windows, player views via Firefox  
**Short Description of bug:** Player can see text through walls  
**Simple steps to reproduce the bug:** Draw a wall. Draw text on one side of the wall. Place a token on the other side of the wall. The token can see the text through the wall.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/204285717-ce29026e-b890-410f-99e1-bb3492139f3a.png)

**Comment by aaclayton** [comment]
This is by design - at least with the current implementation. Drawing text is rendered in the interface layer and drawings are not culled based on visibility detection.
