### ISSUE TITLE
Add new 'documentTypes' field to package manifests that can be used to declare the document sub-types that the package provides

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8567]
```json
"documentTypes": {
  "Actor": ["sidekick", "villain"],
  "JournalEntryPage": ["quest", "dossier"]
}
```
This should be available to both `BaseModule` and `BaseSystem` models (*not* available to Worlds), but will only be functional for module packages in v11. Systems will continue to declare the sub-types they provide via their `template.json`.

`game.documentTypes` will then include sub-types provided by modules, namespaced by the module ID.

```js
{
  Actor: ["character", "npc", "vehicle", "villain-mod.villain"]
}
```

Part of #7521

**Comment by Fyorl** [comment]
Localisation keys should be in the format `TYPES.<document name>.<package ID>.<sub-type>`, .e.g. `TYPES.JournalEntryPage.quest-pages.quest`. See [this article](https://foundryvtt.com/article/module-sub-types/) for more information, in particular the header 'Localizing Sub-Types'. I'll add a link to the article to the main issue body.

**Comment by TheGiddyLimit** [comment]
Even better, thanks!
