### ISSUE TITLE
New JournalEntryPage type not applied

### ISSUE THREAD

**Issue by RobertBeilich** [foundryvtt/foundryvtt#8574]
### What happened?

I'm trying to add a new JournalEntryPage type.

I can see the new type in the drop down when clicking "Add Page", but when selecting it to create a new page, it defaults to the normal text sheet
If I force the type of the page via console it displays correctly, so the type is registered correctly, but is not applied when creating the page.

Debugging on client side, it shows that the socket response for the creation creates a page with type `text` while the request has type `custom`.

Am I missing something or is this really a bug?

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Minimal working example:
```js
class CustomPageSheet extends JournalPageSheet {
  get template() {
    return 'templates/journal/page-text-view.html'
  }
  activateListeners(html){
    super.activateListeners(html);
    html.append("<p>custom paragraph</p>");
  }
}

DocumentSheetConfig.registerSheet(JournalEntryPage, "custom-page", CustomPageSheet, {
  types: ["custom"],
  makeDefault: true,  
});

game.system.documentTypes.JournalEntryPage = game.system.documentTypes.JournalEntryPage.concat(['custom']).sort();
```

1. Put the above into a macro to test it out on the fly (from module perspective i've put the registration in the `init` hook, tested with `setup` and `ready` as well)
2. Checkpoint in `foundry.js` at line 12463 (in `_createEmbeddedDocuments` right after receiving the response)
3. Create a new journal entry
4. Add a new page to the journal entry with the newly shown `custom` type
5. at the breakpoint check the `response`
6. Created page is of type `text` instead of `custom`, but request reads `custom`

check if it would work if the type is correct to verify that the type exists and has logic behind it:
7. Change the type of the page manually to `custom`
8. Reopen the journal entry
9. The custom paragraph is displayed as expected

I've added my `response` object as the log output as reference

### What core version are you reporting this for?

Version 10 (build 290)

### Relevant log output

```shell
{
  "userId": "h0RSeqFe75LlgxaQ",
  "request": {
    "action": "create",
    "type": "JournalEntryPage",
    "parentType": "JournalEntry",
    "parentId": "OENwiwCvREr5wITu",
    "data": [
      {
        "sort": 300000,
        "name": "foobar",
        "type": "custom",
        "_id": "WeIxyDthB4VlFfqX",
        "title": {
          "show": true,
          "level": 1
        },
        "image": {},
        "text": {
          "format": 1
        },
        "video": {
          "controls": true,
          "volume": 0.5
        },
        "src": null,
        "system": {},
        "ownership": {
          "default": -1
        },
        "flags": {}
      }
    ],
    "options": {
      "temporary": false,
      "renderSheet": true,
      "render": true
    },
    "pack": null
  },
  "result": [
    {
      "sort": 300000,
      "name": "foobar",
      "type": "text",
      "_id": "WeIxyDthB4VlFfqX",
      "title": {
        "show": true,
        "level": 1
      },
      "image": {},
      "text": {
        "format": 1
      },
      "video": {
        "controls": true,
        "volume": 0.5
      },
      "src": null,
      "system": {},
      "ownership": {
        "default": -1
      },
      "flags": {}
    }
  ]
}
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
```js
game.system.documentTypes.JournalEntryPage = game.system.documentTypes.JournalEntryPage.concat(['custom']).sort();
```

This won't work to add your new type. New document sub-types must be added via the system's `template.json`, so that the server can be aware of them. More information can be found in the [Intro to System Development](https://foundryvtt.com/article/system-development/#data) KB article.

**Comment by RobertBeilich** [comment]
So this means that it's not intended for modules (not systems) to add new types?

btw, I actually was under the impression that the `registerSheet` part would register the sheet, the part you mentioned I though was only for the dropdowns :man_shrugging:

**Comment by aaclayton** [comment]
@RobertBeilich it is not *currently* supported for modules (not systems) to define custom document types. This is something that we are working on, however, as part of V11: https://github.com/foundryvtt/foundryvtt/issues/7521

**Comment by Fyorl** [comment]
> So this means that it's not intended for modules (not systems) to add new types?

Historically, document sub-types have been the domain of systems only, yes. But as Atro points out we have some ongoing work in v11 to relax that constraint.

> btw, I actually was under the impression that the `registerSheet` part would register the sheet, the part you mentioned I though was only for the dropdowns 🤷‍♂️

It does register the sheet, yes, your code looked correct for what you were trying to accomplish. The issue is that when the document creation request reaches the server to persist it, the server is not aware of the `custom` type, since it was not registered via the `template.json`, so it discards it. I would actually expect it to throw a validation error rather than falling back to a know good type, like `text`, so that bears investigating. But unfortunately, in v10, it's not possible for modules to add additional document types.

If you don't want to wait for v11, I would suggest co-opting an existing type (like `text`), and registering an alternative sheet for it that the user can select. You can store any additional data you need in `flags`.

**Comment by RobertBeilich** [comment]
> This is something that we are working on, however, as part of V11: #7521

That's great news :+1: 

> If you don't want to wait for v11, I would suggest co-opting an existing type (like text), and registering an alternative sheet for it that the user can select. You can store any additional data you need in flags.

I actually thought about "fixing" the type on `createJournalEntryPage`, but this obviously does not persist, so I would need to also add it to the flags and again fix all pages on `renderJournalSheet`. Does this sound reasonable? Or is this complete overkill and there is a simple solution to force the type to persist into the database?

<details>
<summary>Code snippet</summary>

```js
import moduleMetadata from "./config.js"

class CustomSheet extends JournalPageSheet {
  get template() {
    return `modules/${moduleMetadata.id}/templates/custom.html`;
  }
}

class AdditionalJournalTypes {
  get types() {
    return {
      custom: CustomSheet,
    }
  }

  get labels() {
    return {
      custom: `${moduleMetadata.id}.custom`,
    }
  }

  get currentType () {
    return this._currentType
  }

  _setCurrentType = (type = "") => {
    this._currentType = type
  }

  registerSheets = () => {
    for (let [type, label] of Object.entries(this.labels)) {
      DocumentSheetConfig.registerSheet(JournalEntryPage, moduleMetadata.id, this.types[type], {
        types: [type],
        makeDefault: true,
        label,
      })
    }

    game.system.documentTypes.JournalEntryPage = game.system.documentTypes.JournalEntryPage.concat(Object.keys(this.types)).sort()
    CONFIG.JournalEntryPage.typeLabels = mergeObject((CONFIG.JournalEntryPage.typeLabels || {}), this.labels)
  }

  currentTypeNeedsFix = (userId) => {
    return game.user.id === userId && Object.keys(this.types).includes(this.currentType)
  }
}


Hooks.once("init", async () => {
  game.AdditionalJournalTypes = new AdditionalJournalTypes()
  game.AdditionalJournalTypes.registerSheets()
});

Hooks.on("closeDialog", (_, element) => {
  game.AdditionalJournalTypes._setCurrentType()
  const select = element.find('select')[0]
  game.AdditionalJournalTypes._setCurrentType(select?.value)
})

Hooks.on('preCreateJournalEntryPage', (_, __, options, userId) => {
  if(!game.AdditionalJournalTypes.currentTypeNeedsFix(userId)) return;
  options.renderSheet = false // block render of wrongly created text journal page
})

Hooks.on("createJournalEntryPage", async (doc, _, userId) => {
  if(!game.AdditionalJournalTypes.currentTypeNeedsFix(userId)) return;
  const type = game.AdditionalJournalTypes.currentType
  await doc.setFlag(moduleMetadata.id, "type", type)
  doc.type = type
})

const fixPageType = (page) => {
  const type = page.getFlag(moduleMetadata.id, 'type')
  page.type = type || page.type
}

Hooks.on("renderJournalSheet", async (sheet, _, __) => {
  sheet.object.pages.forEach(fixPageType)
})
```
</details>

**Comment by Fyorl** [comment]
> Or is this complete overkill and there is a simple solution to force the type to persist into the database?

There is no way to force the type to be persisted, and nor should there be. As has been mentioned, what you are attempting is not supported by the core software. I would strongly recommend against attempting to work around it in the way you've proposed.
