### ISSUE TITLE
Highlight default map journal for map notes in journal entry dropdown-menu

### ISSUE THREAD

**Issue by Albinosheep** [foundryvtt/foundryvtt#8578]
### User Experience

You can connect a scene to an specific journal or journal page. You  can connect map notes to a specific journal entry.

If you use both, most of the time the map note will lead to a specific journal or page.

It would be easier, if the scene specific journal and page would be highlighted or suggested by default.

**Comment by aaclayton** [comment]
Took me a minute to understand what you mean by that, but I think I get it now. If a specfic entry or page is configured as the entry (or page) at the Scene level, that should be the default value when creating a new map note in the Scene. Right?

**Comment by Albinosheep** [comment]
Hi aaclayton,
thank you for your support! :-) I am sorry for my laborious explanation.
I think your proposal would be great! An other possibilty would be to set the configured entry on the top of the dropdown-menu, if you create a map note and want to connect it to a entry.
