### ISSUE TITLE
Hover state is temporarily lost when dragging a token within a scene

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8579]
### What happened?

If a user drags a token from one location in a scene to another, `TokenLayer#hover` is set to `null` despite the dropped token usually being the one that is in fact currently hovered. The hover state isn't then reestablished until a different token is hovered.

This isn't typically a problem in core since the only operation one could perform is targeting, but any other keybind that operates on hovered tokens will also fail.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Drag a token in a scene and drop it anywhere else.
2. Attempt to target the token via pressing T.

### What core version are you reporting this for?

10.290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think this issue may be resolved by changes we have already made in V11. Needs verification

**Comment by Feu-Secret** [comment]
@stwlam @aaclayton After some tests and verification, this issue could still happen. Sometimes, when initiating a drag from the edge of a hovered token, a `hoverOut` could be triggered before a drag operation could occur, this is a very edge case. To counter this edge case, we need to acquire the hovered state as long as the left button is not released.
