### ISSUE TITLE
Replace explored fog of war texture based approach by a polygon based approach. 

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8583]
Instead of using a texture for explored fow, use a polygon based approach
  - Shapes are processed in a worker thread with clipper.
  - Points are sent to the server for persistence
  - Pending elements rendering should be fast and performant during peaks of computation and shapes accumulation.
    - related to https://github.com/foundryvtt/foundryvtt/issues/8581

**Comment by aaclayton** [comment]
Closing as `wontfix` because we have devised significant performance improvements to the texture-based approach for managing FOW.
