### ISSUE TITLE
Center even number of token target pips and refresh pips when a token is resized.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8586]
### User Experience

An even number of pips is not centered at the moment:
![image](https://user-images.githubusercontent.com/31905376/205414376-13672944-6143-436f-acf7-c454a5b082f0.png)

It would be more aesthetically pleasing (to me) if the target pips were always centered:
![image](https://user-images.githubusercontent.com/31905376/205414483-37d89dab-b697-41d8-8fa4-5176e9db4a72.png)

```diff
    // For other users, draw offset pips
-   const hw = this.w / 2;
+   const hw = this.w / 2 + (others.length % 2 === 0 ? 8 : 0);
```

**Comment by aaclayton** [comment]
Yes, this is a good suggestion, I agree this would be better.

**Comment by dev7355608** [comment]
Bumping for V11 consideration.
