### ISSUE TITLE
Improve the verbosity of error messages related to invalid extension types for uploaded files.

### ISSUE THREAD

**Issue by plutoneld** [foundryvtt/foundryvtt#8587]
### User Experience

It could be helpful if the name of the disallowed file extension was shown in the error message, especially when batch processing files. This is probably mostly an issue for modules, such as the The Forge Asset Sync, where the user can't really tell which file upload is erroring out.

**Comment by aaclayton** [comment]
Improved the verbosity of this error message and added it to localization so it can be translated: 

![Image](https://github.com/foundryvtt/foundryvtt/assets/2468703/e6d16798-9252-4981-aad2-db198a639ab9)
