### ISSUE TITLE
Token HUD isn't updated when attribute is changed somewhere other than the HUD

### ISSUE THREAD

**Issue by ironmonk88** [foundryvtt/foundryvtt#8589]
### What happened?

If you have the Token HUD visible, and it's showing the HP in the input box, if you open up the Actor sheet and update the HP there, the Token HUD isn't updated with the new value.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open up a token's Actor sheet.
Open up the token's HUD.
Edit the HP value on the Actor sheet.
The HP change is not reflected in the Token HUD

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
This appears to have already been fixed by some other fixes we made to tokens in Testing 1.
