### ISSUE TITLE
Disabling a module should disable upstream packages that require it

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8594]
Originally reported by Phi#4271 https://discord.com/channels/170995199584108546/956306859491471420/1048093530142277652

**ALL MODULES DISABLED?** false, but bug relates to module management  
**OS, Hosting, Browser (if applicable):** Win11, Electron  
**Short Description of bug:** Disabling a module dependency does not disable or prompt you to disable the dependent module.
Simple steps to reproduce the bug: Start with a module and its dependency enabled. Then, disable the dependency. The dependent module will still be enabled, but will likely run into errors.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/205660708-4c4b12f0-1c1e-4d63-ac02-8b02b41aa837.png)
![image](https://user-images.githubusercontent.com/207433/205660729-4f9800e4-04b6-40b1-8f22-efdc5be60a2c.png)

**Comment by cswendrowski** [comment]
Removing bug tag since this was never a feature we had, but it's one we should add
