### ISSUE TITLE
Waking from sleep mode, electron client shows a grey screen

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8596]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1048578960121925783

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win11, Electron  
**Short Description of bug:** Waking from sleep mode, the Electron client shows only gray screen until F5 or restart of the electron app.  
**Simple steps to reproduce the bug:** Launch Electron client, launch a world and login into it, set your computer to sleep, and wake it up.

Possibly case of lost GPU context that is not re-acquired.

~~Aside: Did not test if this behaviour is better in browsers (they do resume smoothly, just don't know if Foundry does so in them).~~ The issue does not happen with running Foundry in browser.

**Comment by Fyorl** [comment]
I feel like this has been the case for a long time, or at least it used to be the case, and maybe has regressed.

**Comment by Feu-Secret** [comment]
Issue possibly fixed with v11. Need tests for confirmation.

**Comment by Feu-Secret** [comment]
Tests are confirming that this issue is fixed with v11. The context loss is correctly handled. Closing this issue as completed.
