### ISSUE TITLE
Bring settings menu to top if it's opened again

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8604]
### User Experience

Currently setting menu's (`game.settings.registerMenu()`) do not do anything if you click the button again while the menu is already open.

This leads to following problem: open the menu, select the core settings dialog hiding the settings menu underneath. Now if you click the button for opening the settings menu again, nothing happens, the menu remains hidden.

Instead, the already open settings menu should be brought to top when you click on the button for opening it.

**Comment by Fyorl** [comment]
I think this is already resolved in v11 by the change to make all Applications `focus: true` by default.
