### ISSUE TITLE
Feature Request: Pin max filepicker window height to window size (within reason)

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8612]
### User Experience

On Chrome, 1440p screen, 60px tall taskbar, the filepicker window, with enough subfolders and files in the list, puts the select file button and a few other bits of UI below a scroll that can be hard to activate, instead of one of the sublists': 
https://i.imgur.com/RYWiEeA.gif

Allowing this as a possibility is for sure better than nothing, and is required on small enough screens, but I don't think your defaults are set sanely if a perfectly reasonable (IMO) amount of files/folders produces this result on 1440p.

**Comment by aaclayton** [comment]
Interesting, I was almost certain we constrained the height of the app to have a maximum of the window height. We should revisit this.
