### ISSUE TITLE
When clicking in the hotbar to create a new macro, provide the initial form as a temporary document and only save it to the database if the user submits the form with valid data.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8613]
### User Experience

Currently if you click on an empty space on the macro bar, a create new macro dialog is opened. Even if that dialog is X-ed out of with no modifications to the contents, that useless macro is still created, polluting the macro directory and your bar. It seems the macro is created before the dialog runs even. I think adding a check on dialog close for 'if not modified, delete' would be a very nice QoL addition.

**Comment by aaclayton** [comment]
This remains a valuable and relatively easy QOL addition that we should be sure to do.
