### ISSUE TITLE
Text drawings cannot be edited directly in the scene.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8615]
### What happened?

In all core versions up to and including v9 (and _maybe_ into some of v10?), one could simply start typing while a text drawing was selected to edit its text. This does not work in 10.291; edits can only take place inside the configuration sheet for the drawing.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Make a drawing with a text label.
2. With it selected, try typing to change its text contents.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Hmm, interesting. A definite regression that I had not noticed.
