### ISSUE TITLE
Quadtree isn't updated when the texture of a tile is changed

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8616]
### What happened?

The quadtree isn't updated when the texture of a tile is changed.
```js
  /** @override */
  _onUpdate(data, options={}, userId) {
    const keys = Object.keys(foundry.utils.flattenObject(data));
    const changed = new Set(keys);

    // Re-draw the image
    if ( changed.has("texture.src") ) return this.draw();
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Place a tile at (0, 0) with the texture `A.png`.
```js
console.log(canvas.tiles.quadtree.getObjects(new PIXI.Rectangle(0, 0, 1, 1)).size) // 1
await canvas.tiles.placeables[0].document.update({ "texture.src": "B.png", x: 100, y: 100 })
console.log(canvas.tiles.quadtree.getObjects(new PIXI.Rectangle(0, 0, 1, 1)).size) // 1 (expected 0)
```

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I see the issue, because we `return this.draw()` the super-class `_onUpdate` behavior doesn't fire. We'll have to reconsider the right way to solve that. Thanks.

**Comment by Feu-Secret** [comment]
Confirming that this issue is fixed. @dev7355608, but for your test to work, the test after the update should happen just after the next frame is redrawn.
