### ISSUE TITLE
Clicking on an image with a link in the editor opens the page in Foundry with no way to get back

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#8617]
### What happened?

A ProseMirror editor with an image wrapped in an `a` tag will open the link in Foundry VTT replacing Foundry VTT.

[linked-image-bug.webm](https://user-images.githubusercontent.com/5018947/207076725-1fd2f85f-fb8e-4962-9858-fa585f92515f.webm)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open a Journal Entry Page with a Prose Mirror Editor
2. Add an image and link it like `<a href="https://google.com"><img src="some/path/to/art.webp"></a>`
3. Click on the image in the editor

### What core version are you reporting this for?

V10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl we should probably adjust the prose-mirror schema to automatically include `target="blank"` in HTML anchor elements?

**Comment by Fyorl** [comment]
> @Fyorl we should probably adjust the prose-mirror schema to automatically include `target="_blank"` in HTML anchor elements?

We do have `Game#_onClickHyperlink` which globally catches hyperlink clicks and gives them `target="_blank"`. It skips links within a ProseMirror instance though to fix an issue where they would still be activated if you click them while editing (when the intention was to edit the link in some way, not follow it). So we probably need to be a bit more specific with that logic.
