### ISSUE TITLE
Handlebars numberFormat documentation is incorrect

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8622]
### Where did you find it, or where does it belong for requests?

V10 API Documentation (https://foundryvtt.com/api/v10/)

### What page or file needs a look at?

https://foundryvtt.com/api/classes/client.HandlebarsHelpers.html#numberFormat

### What core version are you reporting this for?

Version 10

### What is wrong, in your opinion?

Originally reported by `@jalensailin#1177`

> In the Handlebars Helper page in the API, there is a function called numberFormat. The example, however, incorrectly shows {{formatNumber}}. 
> 
> Reference: https://foundryvtt.com/api/classes/client.HandlebarsHelpers.html#numberFormat
![image](https://user-images.githubusercontent.com/26660743/207174266-555b333b-9880-4c3d-a72b-e911dc990e47.png)

**Comment by esb** [comment]
This problem still exists in the V12 documentation (and code).

https://foundryvtt.com/api/classes/client.HandlebarsHelpers.html#numberFormat
