### ISSUE TITLE
While and after moving a placeable the hovered placeable is the preview object

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8624]
### What happened?

After moving `layer.hover` is still the preview object until un-hovered and re-hovered.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Script macro:
```js
console.log(canvas.activeLayer.hover.isPreview)
```
Execute while and after moving the placeable. 

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Confirming that this behavior is fixed in V11. Closing this issue as completed.
