### ISSUE TITLE
Passing both dimension and position changes to Application.setPosition results in an unexpected final position.

### ISSUE THREAD

**Issue by teroparvinen** [foundryvtt/foundryvtt#8627]
### What happened?

When calling `Application.setPosition` with both a positional and a dimensional value (e.g. left and width) and the dimensional value applied to the current position of the window would cause it to expand off the screen, the positional input value is ignored.

Example setup:

- Window width is 1500px
- Sheet width is 300px, left is (1500px-300px) / 2 = 600px, or centered on the screen

Example call inputs:

- Left is 100
- Width is 1300

What happens:

- The method determines that 600 (current left) + 1300 (desired width) is greater than the window width 1500
- The input value of 100 (which would cause the window at the requested size to be entirely contained inside the visible window) is adjusted to 1500 (width of screen) - 1300 (desired width) = 200
- The app is erroneously situated at the right edge of the screen instead of centered in the window, which was requested and valid

Calling the method two times, first with dimensions and then with position will result in the expected behaviour, but is unexpected.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Write a script including a setPosition call

### What core version are you reporting this for?

Version 10 build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Resolved by ApplicationV2
