### ISSUE TITLE
Custom `JournalEntryPage` template does not auto-populate new documents

### ISSUE THREAD

**Issue by ben** [foundryvtt/foundryvtt#8628]
### What happened?

I'm looking to add a custom journal page type to represent a mechanical concept in the Ironsworn system (a "progress" page). I've had some success, but one of the problems I've seen is that templated data doesn't seem to be populating into new documents.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Update the system `template.json` with this snippet:

```json
  "JournalEntryPage": {
    "types": ["progress"],
    "progress": {
      "rank": 1,
      "current": 0
    }
  }
```

2. Create a new page of that type.

3. Find that document in the console, and see that the `system` field is an empty object.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl do you know if this is still an issue that `template.json` provided initial data might not get used? This is a quite old issue so I'm wondering if we ended up fixing it or bypassing it?
