### ISSUE TITLE
Clarification of Node.js 18 support in Foundry 10.291

### ISSUE THREAD

**Issue by felddy** [foundryvtt/foundryvtt#8629]
### Where did you find it, or where does it belong for requests?

Knowledge Base (https://foundryvtt.com/kb/)

### What page or file needs a look at?

https://foundryvtt.com/article/installation/#dedicated

### What core version are you reporting this for?

Version 10 Patch 6 (build 291)

### What is wrong, in your opinion?

I am trying to determine if Node.js `18` is now supported by FoundryVTT.  The official documentation says `use Node.js version 14.x or newer`, which would suggest `18` is supported.  However, the **magnificent** support folk on Discord were steering users away from `18` back in July.  Since then the topic has gone mostly dark.

For more context, this is in regards to updating the Node.js version of the container that I support.  A user has opened an [issue regarding IPv6-only servers](https://github.com/felddy/foundryvtt-docker/issues/531).  Migrating from Node.js `16` to `18` should mitigate this issue.  

I expect that the FoundryVTT issues with `18` have been ironed out since July, but I am hesitant to make this change if `18` could still be considered verboten by the devs.

I would appreciate any guidance you could provide about the current state of Node.js support.

Thank you for your support.

https://github.com/foundryvtt/foundryvtt/blob/344d616dfaa49f2a9a63fa0ce02377f88e2068ac/articles/installation.html#L52-L54

https://discord.com/channels/170995199584108546/486930822465716249/992475869102755890
```text
🌈 Phoenix (he/him) — 07/01/2022 1:04 PM
Node 18 does cause issues
Verify that it's using node16 and not 18 if you tried both 
```

https://discord.com/channels/170995199584108546/486930822465716249/992475973767413790
```text
🌈 Phoenix (he/him) — 07/01/2022 1:05 PM
officially foundry only supports node14
```

https://discord.com/channels/170995199584108546/486930822465716249/992476852507652156
```text
🌈 Phoenix (he/him) — 07/01/2022 1:08 PM
Yeah. Node18 does something that breaks foundry. They likely changed a core method foundry depends upon to act slightly different.
16 should be fine
```

 https://discord.com/channels/170995199584108546/486930822465716249/1002950173590306926
```text
🌈threz_👖🧡 — 07/30/2022 10:45 AM
Also node 18 isn't yet supported, you want to stick with 16. There may be unexpected issues with 18.
```

https://discord.com/channels/170995199584108546/689889940590690323/1035732674364579860
```text
Aithan — 10/28/2022 9:51 PM
what version of node.js should I install? The instructions on foundry say 14, but the node.js homepage suggests 18 cause it has LTS now

unsoluble (he/him) — 10/28/2022 9:52 PM
Latest LTS is fine
```

See:
- https://github.com/felddy/foundryvtt-docker/issues/531
- https://nodejs.dev/en/about/releases/

**Comment by aaclayton** [comment]
Hey @felddy thanks for highlighting this uncertainty. @anathemamask can you take over this task to ensure our documentation is accurate with regards to the exact node version range that our current stable release supports?

**Comment by anathemamask** [comment]
This was updated months ago, I simply failed to close the issue.

Woops!
