### ISSUE TITLE
S3 bucket integration ignores `forcePathStyle` setting

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#8630]
Emailed bug report:

**Issue Description**
Parameter `"s3ForcePathStyle": true` doesn't work right. It works for file browsing. But images are still linked in `domain.server.com` style and leads to an 404.

### Reproduction Steps
Set the `"s3ForcePathStyle": true` and check the links generated to images.

### What core version are you reporting this for?
V10

**Comment by Fyorl** [comment]
An update on the resolution to this: The `s3ForcePathStyle` option has been renamed to `forcePathStyle` in (I assume) v3 of the AWS SDK.
