### ISSUE TITLE
Support resizing a polygon drawing by changing the width and height on the DrawingConfig sheet.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8639]
### What happened?

![resizing-polygon](https://user-images.githubusercontent.com/31905376/207454080-17a9c025-19d7-49e6-9d22-220ba10becf9.gif)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a polygon drawing and change the width/height in the config.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This wasn't ever really intended, probably the "bug" here is that those width and height fields are editable in the first place, although we can add some logic behind the scenes to transform the polygon the same way we do when using the drag handler.
