### ISSUE TITLE
A placeable which is resized should not be considered a preview.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8653]
### What happened?

While resizing `drawing.isPreview` is true. Resizing tiles doesn't have this behavior. In my understanding preview objects are temporary objects created by cloning the original.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

`console.log(canvas.drawings.placeables[0].isPreview)` while resizing.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Probably already fixed in v11 from other changes, but needs verification.
