### ISSUE TITLE
zIndex always 0 when accessed from "canvas.activeLayer.placeables"

### ISSUE THREAD

**Issue by SvenWerlen** [foundryvtt/foundryvtt#8656]
### What happened?

My module needs to access the zIndex of tiles on a the active scene.
It iterates `canvas.activeLayer.placeables` and then `zIndex` to retrieve the information.
I now seems to always return `0`

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Add tile on scene (zIndex is 100 by default)
2) Execute `canvas.activeLayer.placeables[0].zIndex` => returns `0`
3) Execute `canvas.activeLayer.placeables[0].data.z` (deprecated) => return `100`

### What core version are you reporting this for?

Version 10 Build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This isn't actually unexpected. We don't use `zIndex` (the `PIXI.DisplayObject` property) anymore for sorting the primary canvas layer. V10 uses a custom sorting method that considers object `elevation` and `sort` properties.

**Comment by SvenWerlen** [comment]
Oh! I didn't know it. I confirm that `canvas.activeLayer.placeables[0].document.sort` returns the data I was looking for.
Thanks for the information!
