### ISSUE TITLE
Support an optional `activeCategory` argument for the GameSettings UI which allows it to be rendered directly to the tab for a specific module's settings.

### ISSUE THREAD

**Issue by mouse0270** [foundryvtt/foundryvtt#8657]
### User Experience

With the update to the settings window that allows you to filter down to a module's specific settings quickly and easily, it would be nice to have a feature that allows you to render the settings window to a specific module setting. 

The use case for this is, it would allow developers to add a settings button to their modules which may make for a better UX then forcing the users to go to the sidebar > configure settings > filter to module.

An example of how this may look could be
```javascript
await game.settings.sheet.render(true, {activeCategory: 'module-id'});
```

**Comment by aaclayton** [comment]
Great suggestion and certainly something we should do.
