### ISSUE TITLE
New actors created by dragging from a compendium pack to the Actors sidebar do not take default token settings into account.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8660]
It appears as if the issue in #8410 has been resolved for the case of dragging actors directly from a compenidum pack to a scene, but has not been resolved for the case of dragging from the pack to the Actors sidebar. In the latter case, Default Token Config defaults are not respected (10.291).

_Originally posted by @unsoluble in https://github.com/foundryvtt/foundryvtt/issues/8410#issuecomment-1358677553_

**Comment by unsoluble** [comment]
While I'm thinking of it, want to add a note here: If/when this ticket is addressed, there will no longer be any means of storing pre-defined token configurations for actors in compendiums (as anything defined in there will be overridden by the core Defaults on any UI-driven import). This seems to me like a bit of a loss, yeah? Might be worth at least thinking about an affordance for disabling the Defaults when desired.

**Comment by cswendrowski** [comment]
@unsoluble added a workflow where holding "ALT" while dragging in a document skips applying the default token config

**Comment by unsoluble** [comment]
_Nice_

**Comment by stwlam** [comment]
> @unsoluble added a workflow where holding "ALT" while dragging in a document skips applying the default token config

Would that overlap with alt-dropping onto the canvas to hide the token?
