### ISSUE TITLE
`PoolTerm.fromRolls` constructs `Roll`s using display formulas

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8661]
### What happened?

`Roll#formula` is documented as "a standardized representation for the displayed formula," but `PoolTerm.fromRolls` uses it instead of the base `Roll#_formula` to construct a new `Roll`:
```js
  static fromRolls(rolls=[]) {
    // ...
    const pool = new this({
      terms: rolls.map(r => r.formula), // 😢
      modifiers: [],
      rolls: rolls,
      results: allEvaluated ? rolls.map(r => ({result: r.total, active: true})) : []
    });
    // ...
  }
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Call `PoolTerm.fromRolls()`.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by CarlosFdez** [comment]
For context, this means that if you use formula to do a pretty displayed formula, it breaks certain methods.

**Comment by aaclayton** [comment]
Am I correct in interpreting this issue that the suggested fix would be the following:
```js
terms: rolls.map(r => r._formula),
```
Or am I misunderstanding the issue?

**Comment by stwlam** [comment]
> Am I correct in interpreting that the suggested fix would be the following:
> 
> ```js
> terms: rolls.map(r => r._formula),
> ```
Yes, that's right, though maybe I'm misunderstanding the purpose of the `formula` getter. I had the notion that it's for textual display, but is it expected that what is returned is still to be a parsable formula?
