### ISSUE TITLE
Add support for hidden Ruler measurement that are visible only to the measuring user and GMs. Holding the ALT key while dragging to measure hides the Ruler.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#8675]
### User Experience

so what i propose is a two fold approach to measurement controls. the issue i have as a gm. is if i have hidden actors that i want to measure and guage abilities to players currently the only way to make those measurements and templates invisible is a permissions setting in the menu. but also sometimes i want players to visually see the measurement distances for certain things. what i suggest is a button for template/distance visibility on the templates menu on the top left. and a short cut for gms and players to toggle that setting on and off. it would enable being able to suprise players a bit more and it wont give away that im targeting players.

**Comment by aaclayton** [comment]
Comment from @ThiefMaster:

### User Experience

This is something Roll20 has and I'm a bit surprised it's not a thing in Foundry:

**As a player I'd like to measure distances without other players or my DM seeing it.**

While generally a good DM will not do this type of metagaming, I think unconsciously there's still a good chance that they may act upon a likely action plan of the next character that's up in combat. For example, I'm measuring whether ✨*big kaboom spell*✨ has enough range to hit *big evil dude*. But I don't want to give him the idea that maybe moving a little bit away will keep him out of reach or require me to spend movement first (this is worse in systems like pf2e where having to take a movement action means I may not be able to use the most powerful 3-action spell). So I'd prefer to do the measurement privately.

**Comment by aaclayton** [comment]
Deprioritizing from V12. Would be good to explore at the same time as other "drag-ruler" like improvements in a future update.
