### ISSUE TITLE
SidebarDirectory renderUpdateKeys testing should allow sub-keys

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8677]
### User Experience

Currently if you want to make SidebarDirectory re-render on more than Foundry data changing, you have to override _render and then jankily skip SidebarDirectory (and anything else you inherit after that) when calling super (to avoid incorrect re-render cancellation):
```js
return SidebarTab.prototype._render.call(this, force, context);
```
And this _render override to begin with exists solely because it can't handle the following renderUpdateKeys addition:
```js
  static get defaultOptions() {
    const options = super.defaultOptions;
    options.renderUpdateKeys.push("system.unidentifiedName");
    return options;
  }
```

It'd be nicer if the default implementations for SidebarDirectory used `getProperty(d, k) !== undefined` instead of `k in d` testing for changes, as it would allow easier extension of the functionality without needing to risk breaking things by excessive overrides.

To be explicit.   
Core implementation in _render:
```js
!data.some(d => { return this.options.renderUpdateKeys.some(k => k in d); }
```
And my fix for it:
```js
!data.some(d => this.options.renderUpdateKeys.some((k) => getProperty(d, k) !== undefined))
```
The latter would work with no _render override if Foundry did that instead.

**Comment by aaclayton** [comment]
An easy low hanging fruit change (even if it took a long time to do it).
