### ISSUE TITLE
Scene navigation bar should indicate if the current scene is pinned to the bar using "Toggle Navigation"

### ISSUE THREAD

**Issue by teroparvinen** [foundryvtt/foundryvtt#8679]
### User Experience

Currently, there is no way to tell if the current scene has been pinned to the scene list floating at the top of the screen. Switching scenes has a loading time and finding the scene again after navigating to another scene can be a burden.

Possible solutions might be:

- Show a pin icon for a pinned scene, similar to the bullseye icon for the currently active scene
- Change the state of the "Toggle Navigation" entry in the menu to reflect the current state

**Comment by aaclayton** [comment]
I'm not sure I totally understand the value here. Scene are only displayed in the navigation bar if they are pinned - OR if they are otherwise currently viewed. Every scene in the navbar is a pinned scene.

**Comment by unsoluble** [comment]
The one small data point that isn’t visible at a glance is whether or not the currently viewed scene will _remain_ in the nav after you leave it.

**Comment by aaclayton** [comment]
Closing in favor of #9792
