### ISSUE TITLE
For v11: Upgrade Electron to v22+ / Chromium 108+

### ISSUE THREAD

**Issue by typhonrt** [foundryvtt/foundryvtt#8684]
### User Experience

With the v11 release it would be great to upgrade to the latest Electron version as there are significant browser features available like `container queries` post `Chromium 106`. 

This issue is just to track this task. Certainly rename, modify any details as it makes sense.

**Comment by aaclayton** [comment]
Definitely on our V11 roadmap!

**Comment by aaclayton** [comment]
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/8497
