### ISSUE TITLE
Outer-element tooltip fails to appear after hovering tooltipped inner element 

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8685]
### What happened?

From the console:
```js
ChatMessage.create({
  content: `<span data-tooltip="Greeting">Hello, <span data-tooltip="What's your name?">user</span>.</span>`
})
```

- If one mouse-hovers the outer span and then the inner span, both tooltips appear as expected.
- If one then mouse-hovers the outer span, the tooltip fails to appear.

Compare with use of `title` attributes, which has both appearing in either case:
```js
ChatMessage.create({
  content: `<span title="Greeting">Hello, <span title="What's your name?">user</span>.</span>`
})
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create the above messages and then compare hover responses.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm going to tag this to V11 and @Fyorl since we are making some changes to tooltips particularly with regards to ways to support nested tooltips.
