### ISSUE TITLE
Preserve query params in login redirect

### ISSUE THREAD

**Issue by numinit** [foundryvtt/foundryvtt#8687]
### User Experience

When /game redirects to /join for login, URL query arguments should be preserved.

Expected: visiting `http://my.foundry:30000/game?param=value` without login redirects to `http://my.foundry:30000/join?param=value`

Actual behavior: visiting `http://my.foundry:30000/game?param=value` without login redirects to `http://my.foundry:30000/join`

This enables deep linking usecases such as https://github.com/numinit/foundry-permalinks without external help from nginx.

(Note that there is a related bug - the `<body>` element should have the class name `game` when there are query params present, but actually has the class name `game?param=value`).

**Comment by aaclayton** [comment]
Merging with #8512 as a duplicate issue.
