### ISSUE TITLE
Convert RollTableConfig application to ApplicationV2 

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8696]
* Use flexcol to allow vertical resizing
* Consider using a 2 tab layout

## Related Issues
- https://github.com/foundryvtt/foundryvtt/issues/11900
- https://github.com/foundryvtt/foundryvtt/issues/11901
- https://github.com/foundryvtt/foundryvtt/issues/11902
- https://github.com/foundryvtt/foundryvtt/issues/9990
- https://github.com/foundryvtt/foundryvtt/issues/10417
- https://github.com/foundryvtt/foundryvtt/issues/4051
- https://github.com/foundryvtt/foundryvtt/issues/4546
- https://github.com/foundryvtt/foundryvtt/issues/8362
- https://github.com/foundryvtt/foundryvtt/issues/4538
- https://github.com/foundryvtt/foundryvtt/issues/4169

**Comment by aaclayton** [comment]
Deprioritizing from V11.

**Comment by aaclayton** [comment]
This would be a good candidate for ApplicationV2 treatment since we feel like this app needs an overhaul.

**Comment by aaclayton** [comment]
Too late to do this in V12 without disruption. Shifting to V13.

**Comment by anathemamask** [comment]
Related issues worthy of consideration:
#10901 
#10603
#10536
#10417 
#10029
#9750
#9088
#8362
#5694
#4546
#4169
#4051
