### ISSUE TITLE
Add support for automatically resizing a Scene Image

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8698]
Related to https://github.com/foundryvtt/foundryvtt/issues/2735

# Feature Summary
When changing Scene image dimensions, placed documents are usually shifted out of alignment with the background image. We want to better support GM's who wall and light a scene, then realize it's 30000 x 30000 and want to scale it down. We also want to support GM's who start a dungeon and expand it overtime, allowing placed objects to be left in place if the new size is intentionally larger to support a bigger new image, rather than the same image scaled.

![](https://media.discordapp.net/attachments/824339459528982599/1060681118115962961/image.png)

## UX: Add a "Linked" functionality

At creation time, a Scene is set to the dimensions of the background image. By default, these dimensions are "Linked" - they have a fixed aspect ratio, and can be changed via the Resize button (relative %) or by editing either field. While linked, editing either Width or Height will automatically adjust the other to maintain aspect ratio. A minimum would be set to the minimum dimensions that support a 50px grid. Placed documents will be automatically shifted to match the new scale.

When clicked, the Link button will "Unlink" the dimensions, removing the "Resize" button and allowing manual input of individual dimensions, possibly in non-uniform ways and below the grid size minimum. Upon save of a `width` or `height` change, we would prompt the user on if they would like placed documents automatically shifted. Warnings would be displayed when the new scale is non-uniform, and placed objects will likely end up distorted.

**Comment by plutoneld** [comment]
Sounds like this (specifically number 2) would remedy the old #2599 issue

**Comment by mclemente** [comment]
Moving my feedback from discord to here, plus adding some more.

>At creation time, a Scene is set to the dimensions of the background image.

If I create an image-less scene, I can't change the default 4000x3000 without changing the grid size, no matter if the dimensions are linked or unlinked.

>By default, these dimensions are "Linked" - they have a fixed aspect ratio, and can be changed via the Resize button (relative %) or by editing either field.

Unlinked status isn't shown when reopening the configs, it shows the dimensions as Linked. If I unlink dimensions, save, then come back to the config, it is shown as linked, but clicking the icon will show the tooltip as if I just re-linked it. Resize button isn't present on release 11.292.

I am not sure if Linked should be the default here. Map sizes aren't perfect round numbers like 4000x3000, and trying to change then by default will throw errors, like changing the height's 3000 to 4000 on a brand new scene, or some random size, like 1324.

>While linked, editing either Width or Height will automatically adjust the other to maintain aspect ratio. A minimum would be set to the minimum dimensions that support a 50px grid.

This isn't working as intended. If I create a new scene and try to decrease the default 4000x3000 to 400x300, it changes the grid size to 50, throws the red notification error that the grid size can't be lower than 50 and doesn't change the dimensions, turning a 40x30-squares scene into a 80x60-squares scene.

There should be a choice to not change the grid size, and it probably should be on by default. There's simply no point in increasing the scene's dimensions if I'm keeping the same number of squares.

I can't make a simple 400x400 scene for testing my modules without being hassled by this.

---

There's also a bug where erasing a zero at a time twice from one dimension will end up erasing 3 zeros from the other. You can see this bug starting at 0:15 on the attached video.

https://user-images.githubusercontent.com/5288872/213796100-7d2d32a3-32f1-460e-a0b0-9cb629ea62d0.mp4
