### ISSUE TITLE
Keep scroll position in compendium directory

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8701]
### User Experience

Currently if you toggle compendium locks or the like, scroll position resets for the compendium directory. This makes managing compendiums unnecessarily hard.

Please make it remember scroll position between renders.

**Comment by aaclayton** [comment]
Strongly suspect this is no longer an issue, tagging @cswendrowski to verify.

**Comment by cswendrowski** [comment]
> Suspect this is no longer an issue, tagging @cswendrowski to verify.

Both the Compendium sidebar and the Compendium app retained scroll when toggling lock, so this seems to be no longer an issue
