### ISSUE TITLE
Handle recursive folder deletion using purely server-side orchestration that emits standard modifyDocument events to the client as necessary to have the client process downstream changes.

### ISSUE THREAD

**Issue by LegoFed3** [foundryvtt/foundryvtt#8710]
### What happened?

I had some actors stored in a subfolder of a folder; upon *removing* said subfolder, they were moved to the parent folder, as expected. However, on the next world load they were in the root folder instead of the parent.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a structure as follows:

![immagine](https://user-images.githubusercontent.com/2862947/211638751-65138277-340a-4460-a7dd-471a4dbf4e5d.png)

*Remove* folder `LVL2`, and actor `LVL3` will be moved (correctly) under `LVL1`. Then restart the world (or simply reload) and `LVL3` will be in the root instead of under `LVL1`.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Might be fixed by some of the foldering changes we have already made in V11. Needs reverification.
