### ISSUE TITLE
`TokenDocument#getActor` doesn't validate `actorData` properly

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8711]
### What happened?

```js
    // Get base actor data
    const cls = getDocumentClass("Actor");
    const actorData = baseActor.toObject();

    // Clean and validate the override data
    const overrides = cls.schema.clean(this.actorData, {partial: true});
    const error = cls.schema.validate(this.actorData, {partial: true});
    if ( !error ) foundry.utils.mergeObject(actorData, overrides);
```
I think the merge of `baseActor.toObject()` and `this.actorData` needs to be validated, or `type` needs to be added to `this.actorData`. Otherwise the system field isn't validated properly as `cls` is `null` if no `type` is given in `SystemDataField#_validateType`:
```js
    /** @inheritdoc */
    _validateType(data, options={}) {
      super._validateType(data);
      options.source = options.source || data;
      const cls = this.getModelForType(options.source.type);
      if ( !cls?._enableV10Validation ) return;
      const schema = cls?.schema;
      const {errors} = schema?.validate(data, options) ?? {};
      if ( !isEmpty(errors) ) {
        throw new ModelValidationError(errors);
      }
    }
```
Also there should be an error/warning message printed in the console if the override data isn't valid.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

dnd5e 2.1.0

1. Create fresh unlinked token.
2. `_token.document.update({ actorData: { system: { attributes: { hp: { temp: 'invalid', max: 123567890 } } } } })`
3. `_token.document.getActor()`:

```
Uncaught Error: Actor5e [IlyCeb1Rb4MxJvMl] Model Validation Errors
[Actor5e.system]: Model Validation Errors
[NPCData.attributes]: Model Validation Errors
[NPCData.attributes.hp]: Model Validation Errors
[NPCData.attributes.hp.temp]: must be an integer
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Actor5e.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseActor (commons.js:7158:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Actor (foundry.js:16292:1)
    at new Actor5e (actor.mjs:10:16)
    at TokenDocument5e.getActor (foundry.js:21987:19)
```

4. `_token.document.update({ actorData: { type: _token.actor.type } })`
5. `_token.document.getActor()`: no error
6. `_token.document.getActor().system.attributes.hp.max !== 123567890`
 

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Tagging this to V11 rather than something to try and fix in V10.

**Comment by Fyorl** [comment]
Leaving a note to come back to this after we have a solution to #6892 since it will potentially change how `actorData` works. Any fix for this right now would potentially have to be re-done in that case.
