### ISSUE TITLE
`TokenDocument#getActor` can throw an error even though the schema validation succeeds because of `_validateModel`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8712]
### What happened?

```js
    // Clean and validate the override data
    const overrides = cls.schema.clean(this.actorData, {partial: true});
    const error = cls.schema.validate(this.actorData, {partial: true});
    if ( !error ) foundry.utils.mergeObject(actorData, overrides);

    // Create a synthetic token Actor
    const actor = new cls(actorData, {parent: this});
    actor.reset();  // FIXME why is this necessary?
    return actor;
```

The schema validation may succeed but the creation of the actor might still throw a model validation error because of `_validateModel`.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

dnd5e 2.1.0

1. Create unlinked token.
2. `_token.actor.update({ "system.attributes.hp.min": 100, "system.attributes.hp.max": 5})`
3. `_token.document.getActor()`:
```
commons.js:5510 Uncaught Error: Model Validation Error:
HP minimum must be less than HP maximum
    at NPCData.validate (commons.js:5509:21)
    at new DataModel (commons.js:5269:26)
    at new SystemDataModel (abstract.mjs:18:16)
    at new Base (abstract.mjs:92:18)
    at new CommonTemplate (common.mjs:20:16)
    at new CreatureTemplate (creature.mjs:30:16)
    at new NPCData (npc.mjs:44:16)
    at SystemDataField.initialize (commons.js:4814:25)
    at Actor5e._initialize (commons.js:5408:29)
    at Actor5e._initialize (foundry.js:13087:11)
```
4. Reload: Scene is broken.
5. Attempt to fix:
```
for (const scene of game.scenes) {
    const updates = [];
    for (const token of scene.tokens) {
        const hp = token.actorData.system?.attributes?.hp;
        if (hp?.min > (hp?.max ?? 0)) {
            updates.push({
                _id: token.id,
                "actorData.system.attributes.hp.min": hp?.max ?? 0
            });
        }
    };
    await scene.updateEmbeddedDocuments("Token", updates);
};
```
This update doesn't go through; it throws an error because `TokenDocument#_preUpdateTokenActor` tries to access `TokenDocument#actor` which throws the error above.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Tagging this to V11 rather than something to try and fix in V10.
