### ISSUE TITLE
Regenerate Scene thumbnails when importing Adventures

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8722]
Originally reported by aMediocreDad#2483 https://discord.com/channels/170995199584108546/956306859491471420/1061700775023218728

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):**
**Short Description of bug:**
Building an Adventure in an Adventure Compendium that includes scenes from a given world the thumbnails of said scenes will not transfer to an unknown environment correctly.

This is because the path to the thumbnail is what stored with the scene data in the adventure. The thumbnail should instead either be encoded into the data, or thumbnails need to be generated where the scene image is hosted (ref. this: https://github.com/foundryvtt/foundryvtt/issues/8491). Alternately, thumbnails could be generated upon importing.  
**Simple steps to reproduce the bug:**
1. Set up a new world.
2. Create a scene with an image background.
3. Create an adventure compendium with an Adventure Document
4. Add scene to Adventure and build.
5. Confirm in the resulting `pack` that the path to the thumbnail is stored with the scene data.

**Comment by Fyorl** [comment]
Related: #9192

**Comment by cswendrowski** [comment]
Closing in favor of https://github.com/foundryvtt/foundryvtt/issues/9192
