### ISSUE TITLE
Enhance display of Setup relationship tags to show the reason and if a required package is missing

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8728]
![](https://media.discordapp.net/attachments/824339459528982599/1063542540504158329/image.png)

![](https://media.discordapp.net/attachments/824339459528982599/1063544627879227402/image.png)

**Comment by MrVauxs** [comment]
Will it be shown on the module screen in an active world as well? That's where most people look at and find out they have missing dependencies.

**Comment by MrVauxs** [comment]
Looks like it isn't
![image](https://user-images.githubusercontent.com/32039708/215538639-2f9a44b5-eecb-4f53-b6dc-b0f67c64e04c.png)

**Comment by cswendrowski** [comment]
> Looks like it isn't ![image](https://user-images.githubusercontent.com/32039708/215538639-2f9a44b5-eecb-4f53-b6dc-b0f67c64e04c.png)

It is: 
![image](https://user-images.githubusercontent.com/15639841/216646805-b4bb7b42-dfa3-49ba-b6bf-a0ff329e37a4.png)

**Comment by MrVauxs** [comment]
Ah I see, it requires expanding the module list. It may be worth saying "expand more information" or such in the hover pop-up as that way of looking at modules is rarely used as far as I know.

Also worth noting: Version incompatibility is shown like this:
![image](https://user-images.githubusercontent.com/32039708/216649821-3c72f9a4-f987-4575-baec-e4a9558c3114.png)
