### ISSUE TITLE
Feature Request: Perserve folder hierarchy in the "create new" dialog

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8736]
### User Experience

Currently the list of folders in the create document dialog gets flattened and then sorted?
![](https://i.imgur.com/KhI9cfE.png)
maybe sorted, because it seems inconsistent if you mix the same name at different depths:
![](https://i.imgur.com/IbvYxsi.png)
Whatever it's doing now, I think it would be desirable to have the drop down ordered like the folder structure, with indentation for subfolders, if possible.

**Comment by aaclayton** [comment]
Reasonable request.

**Comment by esheyw** [comment]
![](https://i.imgur.com/bAqRA1Q.png) I didn't see this in the patch notes, but it's been implemented! I could debate about whether the horizontal line is too wide in the base font, or if there should be a space after the line before the subheading, but that's just quibbles, functionally this is exactly what I wanted. Thanks!
