### ISSUE TITLE
Move Adventure import workflows to be public API methods of the Adventure document itself, allowing for programmatic import of adventure content outside of the context of an AdventureImporter application instance.

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#8750]
## Implementation
```js
await adventure.import(options); // perform the end-to-end import workflow, passing import options
const preparedData = await adventure.prepareImport(); // prepare data for import, but don't perform it
await adventure.importContent(preparedData); // import prepared data
```

## Compatibility
- Hooks remain the same
- Backwards compatibility for `AdventureImporter` class is preserved by continuing to use the legacy workflow for any subclasses which override the `_prepareImportData` or `_importContent` methods.
- Those methods are now deprecated, however, and this backwards compatibility will be removed in V13

## Original Request
You can currently do it with `adventure.sheet._updateObject({}, new FormData())`, but it would be nice to have a more ergonomic solution.

**Comment by aaclayton** [comment]
Yeah, we need to add a `Document` API for this instead of having it be a sheet method.
