### ISSUE TITLE
Keyboard-based hex movement moves in odd patterns

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8756]
### What happened?

Moving a token on a hex map by holding a key down on a keyboard causes it to shift position in random directions instead of moving in an expected way

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Set any map to a hex-based grid
Place some tokens
Select a token and hold the down or up arrow key
Observe that the token doesn't strictly move up or down, but drifts in slow, random patterns until the key is released
[output.webm](https://user-images.githubusercontent.com/26660743/213521931-4c3debe6-d58c-43a7-9519-2d04c8c51304.webm)

### What core version are you reporting this for?

11p1

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think I have resolved this as part of https://github.com/foundryvtt/foundryvtt/issues/9061. I was not able to reproduce the behavior in the video after the aforementioned fix.
