### ISSUE TITLE
`Dialog.wait`: Dialog data is clobbered instead of being considered immutable

### ISSUE THREAD

**Issue by typhonrt** [foundryvtt/foundryvtt#8758]
### What happened?

The new `Dialog.wait` static method is handy, but has a major bug / flaw that is subtle, but reasonable to fix. The main issue / bug is that `Dialog.wait` clobbers the passed in dialog data modifying the button and close callback functions of `data`. This prevents invoking `Dialog.wait` multiple times w/ the same dialog data which is really handy for a helper / utility function. Consider the following code running against `Dialog.wait` in `v10.291`:

```js
const data = {
   title: 'Yo',
   content: 'Foundry Test',
   buttons: {
      one: {
         label: 'Foo',
         callback: () => 'FOO',
      },
      two: {
         label: 'Bar',
         callback: () => 'BAR',
      }
   }
};

let result = await Dialog.wait(data);

console.log(`!! RESULT: `, result);

result = await Dialog.wait(data);

console.log(`!! RESULT2: `, result);
```

Please view the attached webm.  The first invocation returns the callback result `FOO`. The second invocation returns `one` the button ID. 

[fvtt-dialog-wait-bug.webm](https://user-images.githubusercontent.com/311473/213611042-5aa1c26d-782d-425e-9bb0-b5b33b48e698.webm)

Now the reason `one` is returned on the second invocation is the code in `Dialog.wait` that returns the button ID when any potential callback function. result is undefined or the callback doesn't exist. The side effect of clobbering the initial dialog data overriding the initial callbacks w/ the wrapped callback that doesn't have a return statement then returns `undefined` and the  button ID is returned. 

IMHO in addition to not clobbering the dialog data the aspect of returning the button ID when any result is undefined _and_ rejecting the Promise on close when there is no result should be turned off by default and turned on by new dialog data options. Perhaps `resolveId` and `rejectClose` to match the parameters of `confirm` & `prompt`.  IMHO _changing the behavior_ of the dialog data configuration by returning the button ID in `wait` can lead to inaccuracies. 

Another refactor that can occur in this process is to allow button and close callbacks to also be invoked asynchronously. This is easy to accomplish especially w/ wrapping the buttons. 

-------------------------------------

```js
   /**
    * Wrap the Dialog with an enclosing Promise which resolves or rejects when the client makes a choice.
    * @param {DialogData} [data]        Data passed to the Dialog constructor.
    * @param {boolean}    [data.resolveId=false] - When true and there are undefined results from any button
    *        callbacks the button ID is returned.
    * @param {boolean}    [data.rejectClose=false] - When true and there are undefined results reject Promise.
    * @param {DialogOptions} [options]  Options passed to the Dialog constructor.
    * @param {object} [renderOptions]   Options passed to the Dialog render call.
    * @returns {Promise<any>}           A Promise that resolves to the chosen result.
    */
   static async wait(data={}, options={}, renderOptions={}) {
      // Explicitly define `rejectClose` and `resolveId` if available in dialog data otherwise default to false.
      const rejectClose = typeof data?.rejectClose === 'boolean' ? data.rejectClose : false;
      const resolveId = typeof data?.resolveId === 'boolean' ? data.resolveId : false;

      return new Promise((resolve, reject) => {
         // Tracks if a valid result is determined from a button press or default button ID.
         let isResolved = false;

         // Stores the wrapped `data.buttons`.
         const wrappedButtons = {};

         if (typeof data.buttons === 'object') {
            // Wrap buttons with Promise resolution.
            for ( const [id, button] of Object.entries(data.buttons) ) {
               const cb = button.callback;
               wrappedButtons[id] = Object.assign({}, button);
               wrappedButtons[id].callback = async html => {
                  // Button is pressed and this function will resolve the Promise.
                  isResolved = true;

                  const result = await (cb instanceof Function ? cb(html) : undefined);

                  // Handle the case when default button IDs are desired and there are no callback results.
                  resolve(resolveId && result === undefined ? id : result);
               };
            }
         }


         // Wrap close with Promise resolution or rejection.
         const close = data.close;
         const resolveClose = async () => {
            if (!isResolved) {
               const result = await (close instanceof Function ? close() : undefined);
               if ( rejectClose && result === undefined ) reject(new Error("The Dialog was closed without a choice being made."));
               else resolve(result); 
            }
         };

         // Construct the dialog.
         const dialog = new this({ ...data, buttons: wrappedButtons, close: resolveClose }, options);
         dialog.render(true, renderOptions);
      });
   }
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

^

### What core version are you reporting this for?

v10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I've split out the two addenda in this issue into their own (#9253 and #9255) so that this one can be used to track the bug.
