### ISSUE TITLE
Change scene image preview bagroundSize to cover

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#8760]
### User Experience

A really small tweak that would make the images in the sidebar less blurry - i use larger images for thumbnails and they get very zoomed in with the current configuration. Screenshots for reference (top with the proposed change, bottom current implementation)

![image](https://user-images.githubusercontent.com/1346839/213695578-807e6a42-96ab-44ca-a8b9-9b7aec2c2a61.png)

This change makes no difference to how the generated thumbnails are displayed, but makes a world of a difference for custom thumbnails that might not be sized correctly

**Comment by aaclayton** [comment]
Related: https://github.com/foundryvtt/foundryvtt/issues/7954
