### ISSUE TITLE
`this.radius` is undefined in `PointSourcePolygon#createPolygonWithAttenuatedThreshold`

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8766]
Originally reported by EBER#7243 https://discord.com/channels/170995199584108546/1065764070680186930/1065786243872469073

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** ---  
**Short Description of bug:**  
In `PointSourcePolygon#createPolygonWithAttenuatedThreshold` it should probably be `(config.radius ?? canvas.dimensions.maxR)` instead of `this.radius` (which is undefined):

```js
    // Create attenuation shapes for all threshold walls
    const radius = (config.type === "sight" && canvas.scene.globalLight) ? canvas.scene.dimensions.maxR : this.radius;
    const attenuationShapes = PointSourcePolygon.#createThresholdShapes(origin, radius, config,
      losThresholdActiveClipper, thresholdWalls);
    if ( !attenuationShapes.length ) return losThresholdInactive;
```

**Comment by caewok** [comment]
This bug probably occurred when this code was moved from `PointSource`. Worth double-checking any other references to `config` or `this`.
