### ISSUE TITLE
`Note.prototype._onClickLeft` and `Note.prototype._onClickRight` seem to work only on the `NoteLayer`

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#8770]
### What happened?

From some tests I am doing it seems that there click events added recently on the notes:

`Note.prototype._onClickLeft`
`Note.prototype._onClickRight`

only work when I am in the `NoteLayer`, I don't know if this is intentional or not , but just in case I would like such events to be actionable directly from the `TokenLayer` as done for doors.

My goal is to be able to trigger a macro upon clicking on the note while I am in the `TokenLayer`.

Priority: Low

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Try this piece of code (first on the `NoteLayer` then in the `TokenLayer`):

```
Note.prototype._onClickLeft = (function () {
	const cached = Note.prototype._onClickLeft;
	return function () {
		const p = cached.apply(this, arguments);
		console.log("Hello!!!")
		return p;
	};
})();
```

### What core version are you reporting this for?

Version 10 (Build 10.283)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
@p4535992 The Notes are working as intended on the Token layer (only the `_onClickLeft2` is not blocked, all others are).
You can allow the usage of `_onClickLeft` and `_onClickRight` by overriding `_canControl` into the `Note` class.
```js
  /** @override */
  _canControl(user, event) {
    if ( this.isPreview ) return false;
    return this.document.canUserModify(user, "update");
  }
```
