### ISSUE TITLE
Rename `PIXI.Polygon#isClockwise` to `PIXI.Polygon#isPositive` to be more mathematically precise and abstract away from y-axis orientation.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8771]
### What happened?

`isClockwise` is mathematically counterclockwise. Not all polygons are rendered on the screen, so I don't think it makes sense to define it based on how they appear in a y-axis down coordinate system. So if these terms are used, they should match the mathematical definition/convention. If pixi.js ever adds `isClockwise` to `PIXI.Polygon`, it's not going to match your definition. So that's a risk if you decide to keep the current definition. It's probably better to avoid the term (counter)clockwise completely, because it depends on how you look at it. Instead use the terms positive and negative orientation: the polygon is positively oriented if and only if the signed area is positive. This makes a lot more sense in the context of Clipper (http://www.angusj.com/clipper2/Docs/Units/Clipper/Functions/IsPositive.htm).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
A counter-argument is that it's not Foundry VTT specifically that inverts the y-axis, but rather PIXI that makes this choice. This attribute `isClockwise` is defined specifically on `PIXI.Polygon`. If we were maintaining some sort of more generic or mathemtically pure Polygon concept, I think there would be a worthy discussion about what y-axis assumptions should be encoded.

I think `PIXI.Polygon#isClockwise` should match the behavior of `PIXI.Polygon#points` in terms of how those points are visually arrayed. 

Does my counter-argument alter your opinion?
