### ISSUE TITLE
Provide a live subgrid-snapping preview when placing wall endpoints

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8772]
### User Experience

Currently, when placing or moving wall endpoints, they only snap to the scene subgrid _after_ being placed. It would be a significant QoL improvement to have the nodes snap _as they're being dragged_, to clearly indicate exactly where the endpoint is going to "land" before you commit to the placement.

(And of course this live snapping would be temporarily disabled while holding Shift.)

**Comment by aaclayton** [comment]
I worry it might end up looking a bit glitchy/jerky because the subgrid is quite fine, but we could experiment with this and see if it feels like an improvement.

**Comment by plutoneld** [comment]
> I worry it might end up looking a bit glitchy/jerky because the subgrid is quite fine, but we could experiment with this and see if it feels like an improvement.

If this was the default behavior and the user perceive a jerkiness, they might be driven to bypass snapping using Shift. I'm guessing that might not be desirable when it comes to walling?

I guess it comes down to how fine the subgrid is. I'd love to have this feature, but I think snapping works fine as is for the most part and "hiding" this behind a modifier key is preferable.

**Comment by unsoluble** [comment]
I find the worries about "glitchiness" a bit curious, since this would be a one-to-one representation of what's actually happening with the node placement. Surely the current behaviour of nodes jumping to a different position than where you just clicked is the more glitchy alternative.

**Comment by unsoluble** [comment]
(This has been completed in v12 :) )
