### ISSUE TITLE
Support optional indexing for embedded documents within compendium packs, allowing a limited set of fields for embedded documents to be known to the client.

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8773]
# Context
System developers have requested the ability to have limited indexing of embedded documents within compendium packs. Example use cases for this include:
- What types of `JournalEntryPage` documents exist within a `JournalEntry` document?
- Does an Actor have any `Item`s of a certain type?

# Solution
- Embedded documents are not indexed by default, as they are not included in the `Document.metadata.compendiumIndexFields` array of their parent.
- Indexing of embedded documents can be requested by the client as in the following examples:

## Example 1 - Default embedded index fields
```js
await game.packs.get("dnd5e.rules").getIndex({fields: ["pages"]});
```
An example indexed record from this query looks like:
```
**{
    "name": "Chapter 7: Using Ability Scores",
    "folder": null,
    "sort": 0,
    "_id": "0AGfrwZRzSG0vNKb",
    "uuid": "Compendium.dnd5e.rules.JournalEntry.0AGfrwZRzSG0vNKb",
    "pages": [
        {
            "name": "Using Ability Scores",
            "type": "text",
            "_id": "LgFIjR9ASPVL0W8K",
            "sort": 0
        },
        {
            "name": "Ability Scores and Modifiers",
            "type": "text",
            "_id": "yuSwUFIjK31Mr3DI",
            "sort": 0
        },
        {
            "name": "Advantage and Disadvantage",
            "type": "text",
            "_id": "d3eBZOe9PUvZ7dKQ",
            "sort": 0
        },
        {
            "name": "Proficiency Bonus",
            "type": "text",
            "_id": "tthOsaZTr7AVKnsW",
            "sort": 0
        },
        {
            "name": "Ability Checks",
            "type": "text",
            "_id": "OcHhrKKzffcVi03Q",
            "sort": 0
        },
        {
            "name": "Using Each Ability",
            "type": "text",
            "_id": "xt6tSGvU9e0vtXw6",
            "sort": 0
        },
        {
            "name": "Saving Throws",
            "type": "text",
            "_id": "9M9VztnDl81tTxgz",
            "sort": 0
        }
    ]
}
```

## Example 2 - Custom Embedded Index
```js
await game.packs.get("dnd5e.rules").getIndex({fields: ["pages.type"]});
```
An example indexed record from this query looks like:
```
{
    "name": "Chapter 7: Using Ability Scores",
    "folder": null,
    "sort": 0,
    "_id": "0AGfrwZRzSG0vNKb",
    "uuid": "Compendium.dnd5e.rules.JournalEntry.0AGfrwZRzSG0vNKb",
    "pages": [
        {
            "type": "text",
            "_id": "LgFIjR9ASPVL0W8K",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "yuSwUFIjK31Mr3DI",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "d3eBZOe9PUvZ7dKQ",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "tthOsaZTr7AVKnsW",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "OcHhrKKzffcVi03Q",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "xt6tSGvU9e0vtXw6",
            "flags": {}
        },
        {
            "type": "text",
            "_id": "9M9VztnDl81tTxgz",
            "flags": {}
        }
    ]
}
```
(not a great example because none of these pages had a custom sheet class defined, but you get the idea).

# Original Request Below

In the pf2e system, when a player chooses a feature like their character's class, they are presented with options available from the Classes (item) compendium. Homebrewers are able to create their own class items, and it's possible to select one for a PC's class. The workflow for these is a little more cumbersome, however: the system doesn't know where these additional classes live, and it is potentially costly depending on the size and number of item compendiums to look through every index for class items.

One solution could be that the server annotates each actor and item compendium with the set of `subtypes` found in each collection. Given that, the system could limit its search for valid options by quickly pulling from collections known to have at least one class item. Journal Entries are a little different, with their embedded pages having subtypes. Perhaps those indexes could instead have a similar `pageSubtypes` set, either for the entire collection or each index entry.

**Comment by aaclayton** [comment]
Adding to V12 project board to discuss feasibility for V12 development prioritization.
