### ISSUE TITLE
Ensure that any filesystem errors that occur during package installation or update cause the process to fail with an informative error message passed back to the user.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8775]
### User Experience

It's fairly common failure from users to launch Foundry with lesser permissions than they used for installing it, leading to them lacking write permission access to various bits.

It would be thus helpful to test the permissions in a few places, including module and system folders and warn about that in the setup page if there's issues.

**Comment by aaclayton** [comment]
We do test for write permission to the user data folder before launching the software. I presume you encountered a specific case where the check we are already doing was inadequate to prevent a permissions problem that surfaced later. Could you share some further details?

**Comment by mkahvi** [comment]
It's fairly common complaint for PF1 at least where people come after updating saying their sheets are broken.

The solution pretty much always is to tell them to uninstall the system, manually make sure the system is gone from Foundry data/systems/ and then re-install.

This is obviously caused by them initially installing things with admin user, and then later updating things as normal user.

**Comment by mkahvi** [comment]
This actually reminds me of a strange quirk in Windows OS, that if you just simply delete files and create new identical files on top, the OS sometimes blocks the operation since the delete hasn't finished yet (the underlying delete command has finished, but the operation hasn't been carried out).

This was a problem with for example Chrome at a time few years back, and the solution was to first rename and move the files to something else random, and then delete, so it wouldn't block the new file.

**Comment by aaclayton** [comment]
Does your feedback imply that it is possible for a system update to fail because of filesystem permissions and that failure does not prevent the overall package update workflow with an error message returned to the user?

**Comment by mkahvi** [comment]
That is the observed effect, yes. Though I have no first person experience with the issue, only with providing support in solving it for others.

**Comment by Fyorl** [comment]
Hard to say for sure with this one, but we've implemented improvements so that the user should at least see an error message notification, and the error will be logged for further troubleshooting.
