### ISSUE TITLE
Update of PDF Library

### ISSUE THREAD

**Issue by STBaf** [foundryvtt/foundryvtt#8777]
### User Experience

Assuming that the PDF.js library from Mozilla, which is mandatory on the Internet, is used to display PDF in browsers, the question here is whether it is possible to update the version contained to one of the latest versions of the library with the upcoming Foundry version.

The reason for this is that the version used apparently still corresponds to a version that contains a bug that was carried along in PDF.js for a long time: The incorrect display of 90 degree rotated PDF texts, mainly (and probably only) in input fields.

The problem here is that for users using an appropriate module like PDF Pager (or earlier in v9 PDFoundry) to use an editable PDF as an actor sheet, this may render the actor sheets unusable for fields containing text rotated 90 degrees.

While the library itself was explicitly included in PDFoundry and was unfortunately never updated (and PDFoundry is no longer developed for v10), PDF Pager now uses the Foundry built-in library for displaying PDFs, so I was referred to the Core Foundry feature request here to deliver.

For reference past tries to get this work in Actor Sheets that base on a PDF ;-)
https://github.com/Djphoenix719/PDFoundry/issues/111 (contains example PDF etc.)
https://github.com/farling42/fvtt-pdf-pager/issues/49 (latest request for this for PDF Pager)

Thanks

Note: I clearly see it as nice to have, so only if something really, really fits in with the time :-)

**Comment by Fyorl** [comment]
It shouldn't be too much trouble to update the underlying library we use here.

**Comment by Fyorl** [comment]
We've updated our underlying PDF.js dependency to version 3.4.120
