### ISSUE TITLE
Fields on an ActorSheet which still reference "data" fields instead of "system" fields can incorrectly be modified when they have an active effect applied because the data schema migration occurs after the AE override check.

### ISSUE THREAD

**Issue by awilner** [foundryvtt/foundryvtt#8784]
### What happened?

I'm currently experimenting with Active Effects in the Shadowrun 6 system (https://foundryvtt.com/packages/shadowrun6-eden), which has not been migrated to v10 yet. I had added an active effect to an actor, with a change applied to one attribute. I noticed that every time I closed the actor's form, the change was saved on the attribute itself, causing the increase to become part of the actor's data - while still having the effect registered. And whenever I opened the actor's form again, the effect would be re-applied to the attribute, causing the increase to be applied multiple times.

For example, let's say my actor had STR 3, and I added an effect that added +5 to the attribute. At first, the actor would have STR 3 with an overriden value of 8. Upon closing the form, the 8 was being saved back in the world's actors.db, and next time I opened the actor's form, the system would apply the +5 effect to the recently saved value of 8, causing the attribute to now be effectively 13. Subsequently closing and opening the actor's form would increase the attribute every time.
 
I noticed there's a handful of methods dealing with migrating v9 modules, and the v9 "data" system-specific structure was migrated to "system". There are methods that address this in the objects themselves, forcing this compatibility. And if I created the effect using, as in my example, "data.attributes.str.base" as the attribute key for the change, I saw that there was a call to `BaseActiveEffect::migrateData()` (commons.js:7120) that changed it to "system.attributes.str.base".

But the problem is, for systems not yet migrated to v10, the forms themselves contain input fields with names starting with "data.*".  So when the form was closed, there was a call to `ActorSheet::_getSubmitData()` (foundry.js:61389) where overriden keys are filtered out from an update, but the updated fields still had the "data." prefix (because they were taken from the form), while the override had the "system." prefix. This caused the attribute affected by the effect to be identified as being updated with no relation to the effect override, and so the effect would be applied permanently to the attribute.

I currently have a workaround, but it's an ugly hack: I implemented an overload of _getSubmitData for my class derived from ActorSheet, which performs this key replacing and filtering out of overrides. But I propose that the fix be added to `ActorSheet::_getSubmitData()` with something along the lines of:
```
            // Change keys from "data.*" to "system.*"
            let newData = {};
            for (let key of Object.keys(data)) {
                let newKey = key.replace(/^data\./, "system.");
                newData[newKey] = data[key];
            }
            // Prevent submitting overridden values
            const overrides = foundry.utils.flattenObject(this.actor.overrides);
            for (let k of Object.keys(overrides)) {
                delete newData[k];
            }
            data = newData;
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Reproduction is not very straightforward, I'm afraid. You have to have an instance of FoundryVTT running v10, and a system not yet migrated to v10 (for example, Shadowrun 6). Create an actor, and manually add an effect that has an attribute-altering change, by editing actors.db. Open the actor's form, then close it. If you do it multiple times, you'll notice the change is applied that many times.

### What core version are you reporting this for?

Version 10, build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks for the report. I must say I'm not certain whether this is actually an issue with active effect application, or rather a problem with allowing active effects to override values on a character sheet which is then saved (with those overridden values persisted). This type of UX requires some special logic.

What is supposed to happen here is that when active effects are applied, we track an object of `overrides` on the `Actor` instance that keeps track of which fields in the data model have been overridden by a temporary AE. In the `ActorSheet` class, we reference that object of `overrides` (you can see this in `_getSubmitData`) to ensure that we do not allow updates to an overridden value. 

In your case, it sounds to me like either (1) the `actor.overrides` object is wrong or is incorrectly populated OR (2) the `ActorSheet` used in your system does not enforce this restriction of not updating overridden fields. Could you look into that and share further feedback?

**Comment by awilner** [comment]
Thank you for the prompt reply. In my example, the actor.overrides object is correctly populated with nested properties:
```
system: { 
    attributes: {
        str: {
            base: 5
        }
    }
}
```
but the call to `super._getSubmitData(updateData)` in `ActorSheet::_getSubmitData()` returns an object with properties whose names are retrieved from the form fields, and since the system is not migrated to v10, the input fields in the form have the "data" prefix instead of the "system" prefix. So for the attribute altered by the effect, the form contains:
```
data.attributes.str.base: 8
```
This update will not be filtered out by the override above, because there will be no match between `"system.attributes.str.base"` (that came from the `actor.overrides`, because the actor object had its `data` property migrated to `system`),  and `"data.attributes.str.base"` (that came from the input name in the form, because the form is still in v9).

So in my understanding, neither of the 2 cases in your last paragraph apply, and my issue stems from the fact that the v10 compatibility code automatically transforms data->system almost everywhere, but since form input field names are not transformed, this restriction of not updating overridden fields will not work correctly, even though the code is indeed called.

**Comment by aaclayton** [comment]
I see, thanks for the further investigation. We do apply migrations to the data submitted from the form, but these shims are applied *after* the checks for actor overrides are done so they are too late to apply here. I'll re-frame this issue to see if we can shift the location where those override checks occur.

**Comment by aaclayton** [comment]
I *suspect* this issue is now fixed with changes we have made in V11. Adding this to the Testing 2 milestone to verify.

**Comment by Durak-Git** [comment]
(I reproduced it in the 11.296)
