### ISSUE TITLE
createScrollingText incorrectly(?) references text originating from ObjectHUD container

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8798]
From `@Mana#4176

The text originates from a Point on the canvas, not whatever weird the documentation says.

Ref: https://foundryvtt.com/api/classes/client.InterfaceCanvasGroup.html#createScrollingText

**Comment by mkahvi** [comment]
I think this has been fixed (with v11?)? The current documentation indeed says point now instead of something misleading.

**Comment by aaclayton** [comment]
Fixed for next release (V12 Dev 2)
