### ISSUE TITLE
Inline Roll Tooltips for formulas with data path variables should display the data path rather than the evaluation

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/foundryvtt#8810]
### User Experience

Currently an Inline Roll that contains a data path variable displays the result of that data path in the tooltip, I believe they should display the variable as written in the formula. In this example it is not obvious that the `+2` is coming from an actor's attribute of `@prof` unless you edit the item

![image](https://user-images.githubusercontent.com/86370342/214449427-40935950-2854-45c0-9098-0eb2ad357f3e.png)

**Comment by plutoneld** [comment]
Throwing in a suggestion of having both. The current tooltip first, and the suggested tooltip in parentheses after.

**Comment by MaxPat931** [comment]
Perhaps this issue https://github.com/foundryvtt/foundryvtt/issues/9157 could also be considered related? At least in regards to coming up with a solution.
Maybe the on-hover tooltip remains as-is showing the evaluation, and the clicked dice-tooltip shows the datapath variable in this scenario and the math function/not-a-dice-term for the scenario shown in that issue?

**Comment by aaclayton** [comment]
@Fyorl is this something we could easily do as part of our V12 "dice improvements" overall theme?

**Comment by Fyorl** [comment]
Yes, I don't expect it to be much work.
