### ISSUE TITLE
Privacy: Impossible to use when tracking protection is on

### ISSUE THREAD

**Issue by Q-efx** [foundryvtt/foundryvtt#8815]
### What happened?

If you enable tracking protection, sometimes it doesn't load or, at least, fields get the wrong names.

Funny enough, external modules work fine (i.e. DND Muncher) Its only foundry, which depends heavily on tracking

![grafik](https://user-images.githubusercontent.com/42732/215031955-d62e23b9-1b5d-45c7-9fd9-02aeaadc7ae6.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Use Firefox or Brave and enable strong privacy protection

### What core version are you reporting this for?

Version 10, 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I've got no idea why this mode would cause anything in Foundry VTT to fail. We don't use any tracking cookies or analytics of any kind. It looks like - based on the lack of localization strings - that the fetch request to load the english localization file is failing or being blocked. Can you please hit F12 and open the Console and share any error messages which appear?

**Comment by aaclayton** [comment]
I think what @vizovitin describes is a caching issues which was specifically improved upon in V10. So the update from V9 -> V10 could suffer from some browser cache that was stuck. Further updates after that point would be unaffected. I think the original issue is conclusively non-repro so I'm going to close this issue as "already fixed".
