### ISSUE TITLE
Improve upon the logic used to determine whether FOW needs to be committed when rendering a Vision update

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8823]
There are a number of issues or edge cases which can result in the wrong decision being made here. We should also factor this out as a independent method so that modules which need to implement custom FOW handling can make their own decision about whether a FOW commit is required.

Given the new performance improvements with V11 fog, we could consider committing every time in order to avoid making any mistake, but there should be a way to improve performance with some logic about whether the polygon is the same as previously when we visited a certain explored location.

## Related Issues
- https://github.com/foundryvtt/foundryvtt/issues/6921
- https://github.com/foundryvtt/foundryvtt/issues/8818
- https://github.com/foundryvtt/foundryvtt/issues/8816
- https://github.com/foundryvtt/foundryvtt/issues/8817

**Comment by dev7355608** [comment]
One more case that should be considered: The fog is committed every time if the LOS polygon is limited (<360 degrees vision angle or some other boundary shape constraints). Most users probably don't play with <360 degrees angles but those who do have never benefitted from the explored position tracking.
