### ISSUE TITLE
Limit client settings to the world scope/introduce user scope

### ISSUE THREAD

**Issue by CDeenen** [foundryvtt/foundryvtt#8828]
### User Experience

Currently, client settings are transferred between worlds. This means that if someone plays in different worlds where they want or need different settings they have to reconfigure them each time. (Optionally) limiting the settings to a specific world and/or user would fix this.

Another thing that would solve this and would be nice to have in general would be a user scope for settings. These settings would be stored on the server and applied no matter what browser or computer someone uses. I believe this makes a lot of sense for a lot of cases where client settings are currently used.

**Comment by aaclayton** [comment]
This suggestion would be covered by:
1. https://github.com/foundryvtt/foundryvtt/issues/8227
2. https://github.com/foundryvtt/foundryvtt/issues/4804
