### ISSUE TITLE
Decouple `content-link` class from event listener

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#8830]
### User Experience

Currently, if i attempt to use the `content-link` class to mimic core content links on my custom content links, it comes not only with the styles but also with the global event listener, forcing me to copy paste the class with a different name. This will cause issue for any module or system that applies custom theming to content links.

**Comment by aaclayton** [comment]
I agree it probably makes sense to separate the CSS rules here to (1) a class that defines the visual style and (2) a class which is the target for interactivity. We should allow interactivity without the visual style, or vice versa.

**Comment by stwlam** [comment]
In many places there is a `data-` attribute for event listeners to select on. Perhaps that could be taken up as a standard, with classes only being used for styling.
