### ISSUE TITLE
`Tile.prototype._createTextureData` mangles the pixel data

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#8831]
### What happened?

The `pixels` property stored in `Tile.prototype._createTextureData` is supposed to be a representation of the tile alpha. But there are two possible errors that result in mangled pixel data. 

In `Tile.prototype._createTextureData`, the mapping portion is causing the problems:
```js
    // Map the alpha pixels
    for ( let i = 0; i < pixels.length; i += 4 ) {
      const n = i / 4;
      const a = map.pixels[n] = pixels[i + 3];
      if ( a > 0 ) {
        const x = n % map.aw;
        const y = Math.floor(n / map.aw);
        if ( (map.minX === undefined) || (x < map.minX) ) map.minX = x;
        else if ( (map.maxX === undefined) || (x + 1 > map.maxX) ) map.maxX = x + 1;
        if ( (map.minY === undefined) || (y < map.minY) ) map.minY = y;
        else if ( (map.maxY === undefined) || (y + 1 > map.maxY) ) map.maxY = y + 1;
      }
    }
```

First, `map.aw` may be non-integer. But the actual number of pixels generated are rounded to the nearest width. (I think the formula for the number of pixels is `Math.round(map.aw) * Math.round(map.ah)` but you should probably confirm it is not `Math.ceil(map.aw) * Math.ceil(map.ah)`. So in the mapping code, `map.aw` should be `Math.roundFast(map.aw)`.

Second,  `const a = map.pixels[n] = pixels[i + 3];` should be `const a = map.pixels[i] = pixels[i + 3];`.

The updated code looks like:
```js
    // Map the alpha pixels
   const w = Math.roundFast(map.aw);
    for ( let i = 0; i < pixels.length; i += 4 ) {
      const n = i / 4;
      const a = map.pixels[i] = pixels[i + 3];
      if ( a > 0 ) {
        const x = n % w;
        const y = Math.floor(n / w);
        if ( (map.minX === undefined) || (x < map.minX) ) map.minX = x;
        else if ( (map.maxX === undefined) || (x + 1 > map.maxX) ) map.maxX = x + 1;
        if ( (map.minY === undefined) || (y < map.minY) ) map.minY = y;
        else if ( (map.maxY === undefined) || (y + 1 > map.maxY) ) map.maxY = y + 1;
      }
    }
```

Related: https://github.com/foundryvtt/foundryvtt/issues/8827

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

A simple test is to compare the pixel data before and after the mapping step. The only change should be the red channel should now equal the alpha channel. But that is not what is happening.

I also recommend drawing the resulting pixels to canvas to visualize what is happening. Something like:

```js
pixels = tile._textureData.pixels
width = Math.round(tile._textureData.aw)
color = 0x0000FF
ln = pixels.length
for ( let i = 3; i < ln; i += 20*4) {
  const n = i / 4;
  const x = n % width;
  const y = Math.floor(n / width);
  const alpha = pixels[i] / 255;
  canvas.controls.debug
      .beginFill(color, alpha)
      .drawCircle(x, y, 1)
      .endFill();
}
```

### What core version are you reporting this for?

v10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by caewok** [comment]
I suspect the intention was to actually keep only the alpha pixels. To accomplish that, something like this would work:
```js
    // Map the alpha pixels
    const w = Math.roundFast(map.aw);
    const ln = pixels.length;
    const alphaPixels = new Uint8Array(ln / 4);
    for ( let i = 0; i < pixels.length; i += 4 ) {
      const n = i / 4;
      const a = alphaPixels[n] = pixels[i + 3];      
      if ( a > 0 ) {
        const x = n % w;
        const y = Math.floor(n / w);
        if ( (map.minX === undefined) || (x < map.minX) ) map.minX = x;
        else if ( (map.maxX === undefined) || (x + 1 > map.maxX) ) map.maxX = x + 1;
        if ( (map.minY === undefined) || (y < map.minY) ) map.minY = y;
        else if ( (map.maxY === undefined) || (y + 1 > map.maxY) ) map.maxY = y + 1;
      }
    }
    
    map.pixels = alphaPixels;
```

That would save  a lot of space by only storing the alpha pixels. Looks like it might run a bit faster, possibly because the compiler has an easier time filling the alphaPixel array in order, versus the pixel-swapping of the original.

**Comment by caewok** [comment]
Might also want to consider rounding `map.aw` and `map.ah`. `Tile.prototype.#getPixelAlpha` rounds the aw width property:

```js
    // Next test a specific pixel
    const px = (Math.floor(y) * Math.roundFast(Math.abs(this._textureData.aw))) + Math.floor(x);
```
Instead, why not just round it when setting it in the first place in Tile.prototype._createTextureData? (Also, I don't see how aw could be negative, but assuming it is, you could take the absolute value there as well.) So:

```js
    map.aw = Math.roundFast(Math.abs(width / 4));
    map.ah =  Math.roundFast(Math.abs(height / 4));
```

**Comment by caewok** [comment]
Sorry to keep piling on this one, but thought you should probably be aware that, currently, `Tile.prototype.#getPixelAlpha` is returning odd results even if I fix the above issue. Again, I think it was assumed that the cached pixels would be the alpha channel only, and this is throwing off the calculation. If you keep all 4 channels, then I think the `px` variable in `Tile.prototype.#getPixelAlpha` should be multiplied by 4. If you end up keeping only the alpha channel, then `Tile.prototype.#getPixelAlpha` should probably work without alteration.

**Comment by Feu-Secret** [comment]
Thanks for the heads-up. We will keep only the alpha. We have no reasons to keep other channels.
