### ISSUE TITLE
List Missing Dependencies

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/foundryvtt#8833]
### User Experience

It is a common issue with modules that have a large list of dependencies, ESPECIALLY if those dependencies have a versioning requirement, for users to not know why they can't enable (or disable #8556) the module.

The hover could easily fit in a list of missing dependencies, whether it is an entire module that is missing, or being on an invalid version of a module. This is very common when an user presses the "Update All" button, and only *some* of the modules get updated.

An example of such a module can be [PF2e Animations ](https://github.com/MrVauxs/pf2e-jb2a-macros/blob/f236015dd81f4d5521cc20d8639fb4b2b574fc99/module.json#L95-L146) and it's 4 (6) dependencies (4 core, +2 included from one of the core modules dependencies), as well as being made for a specific version of a system.

**Comment by cswendrowski** [comment]
Already added in V11 via https://github.com/foundryvtt/foundryvtt/issues/8728

**Comment by MrVauxs** [comment]
> Already added in V11 via #8728

Made some comments in there.
