### ISSUE TITLE
Provide a way to source embedded items from a Compendium UUID instead of embedded item data

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#8839]
### User Experience

I was thinking the server could resolve the UUID and merge the compendium item data before sending the actor to the client.

This would be extremely useful for systems where most items come from a bundled compendium pack and these items are rarely modified by the user.
It would make it easier to keep embedded items up to date with system changes without the need to migrate or replace them in every actor.
This would also benefit actor compendium packs which currently need to have their embedded items updated regulary.

**Comment by aaclayton** [comment]
Merging your suggestion with #4451
