### ISSUE TITLE
Improve complete circle test of point source shapes

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8849]
### What happened?

```js
    // We can skip soft edges if we have a complete circle
    if ( this._flags.renderSoftEdges ) {
      const isCircle = (this.shape.points.length === PIXI.Circle.approximateVertexDensity(this.data.radius) * 2);
      if ( isCircle && (this.data.angle === 360) ) this._flags.renderSoftEdges = false;
    }
```
This test isn't good enough. It fails in common cases. 10 units (200 px) radius light source centered in the square:
![image](https://user-images.githubusercontent.com/31905376/216699634-95d51720-f224-45e4-9ab0-ecee52616ed1.png)

I recommend to check the area of the shape too. `circleArea` is the area of the polygon approximation of the circle with the given density. Because of the new Weiler-Atherton algorithm the points aren't rounded when the intersection is computed and so the `signedArea` of the complete circle matches `circleArea` very closely. The numerical error scales with the radius, but it shouldn't exceed 1e-5 in practice, because the scene dimensions shouldn't be larger than 2^16.
```js
class RenderedPointSource extends PointSource {

    /* ... */

    /**
     * Is the shape of this point source a complete circle?
     * @returns {boolean}
     */
    get #isCompleteCircle() {
        const { shape, data: { radius, angle } } = this;
        if (angle < 360) return false;
        const density = PIXI.Circle.approximateVertexDensity(radius);
        if (shape.points.length !== density * 2) return false;
        const shapeArea = Math.abs(shape.signedArea());
        const circleArea = (0.5 * density * Math.sin(2 * Math.PI / density)) * (radius ** 2);
        return circleArea - shapeArea < 1e-5;
    }

    /* -------------------------------------------- */
    /*  Rendered Source Initialization              */
    /* -------------------------------------------- */

    /** @override */
    _configure(changes) {
        // Decide whether to render soft edges with a blur
        // We can skip soft edges if we have a complete circle
        this._flags.renderSoftEdges = canvas.performance.lightSoftEdges && !this.preview && !this.#isCompleteCircle;

        /* ... */
    }

    /* ... */

}
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Good suggestion! Using the shape signed area makes the algorithm more robust.
