### ISSUE TITLE
Increase default `priority` of `CanvasAnimation#animate`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8853]
### What happened?

The default `priority` should be at least `PIXI.UPDATE_PRIORITY.LOW + 1`, so that the ticker of the animation executed before the current frame is rendered and not after the frame is rendered (PIXI's render ticker has `LOW` priority).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks for the suggestion, makes sense.
