### ISSUE TITLE
Elevation/sort changes need to trigger a perception update

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8873]
### What happened?

In the following functions elavation/sort changes and `canva.primary.sortChildren()` is called, but no perception update (`canvas.perception.update({refreshTiles: true}, true)`) is scheduled to update depth elevation uniforms of tiles and light sources:
- `DrawingDocument#elevation`
- `TokenDocument#sort`
- `WeatherEffects#elevation`
- `InterfaceCanvasGroup#draw`

There's also another issue: the tile occlusion updates are not instant but debounced; so the tiles are rendered incorrectly with the old depth elevation for a couple of frames (the depth buffer is instantly rerendered with the new elevation mapping).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Thanks for the report. Concerning occlusion update, we need to apply it immediately if the new `occluded` state is `true`, and the previous `occluded` state is `false`, otherwise we debounce it.
