### ISSUE TITLE
Feature Request: Increased granularity of token names/bars visibility settings.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8876]
### User Experience

As it stands, given the current token properties, there's no way to have a token which both always shows the name to its owner, *and* any non-owners who hover. 

Or one which shows its resource bars when controlled *and* when hovered.

Or having separate settings per resource bar, maybe I want HP always but some version of Mana only when controlled?

Separating the setting from a list into a few independent toggles would dramatically increase user options here.

**Comment by aaclayton** [comment]
Module territory.
