### ISSUE TITLE
`fromUuidSync` always returns a compendium index entry even if the requested document is cached locally

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#8883]
### What happened?

It looks like the intetion was to retun a document from `_parseUuid` if one is available but the function only returns `{collection, documentId, embedded: parts}` so `doc` is always undefined.

```js
function fromUuidSync(uuid, relative) {
  let {collection, documentId, embedded, doc} = _parseUuid(uuid, relative);
  if ( (collection instanceof CompendiumCollection) && embedded.length ) {
    throw new Error(
      `fromUuidSync was invoked on UUID '${uuid}' which references an Embedded Document and cannot be retrieved `
      + "synchronously.");
  }

  if ( collection instanceof CompendiumCollection ) {
    doc = doc ?? collection.index.get(documentId);
    if ( doc ) doc.pack = collection.collection;
  } else {
    doc = doc ?? collection?.get(documentId);
    if ( embedded.length ) doc = _resolveEmbedded(doc, embedded);
  }
  return doc || null;
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

-

### What core version are you reporting this for?

Version 10 Stable (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks for the bug report, we should certainly return the full `Document` if it exists in the client-side compendium cache.

**Comment by In3luki** [comment]
I've noticed this also occurs in `fromUuid` which also tries to get a `Document` from `_parseUuid` but never checks if one is available before requesting the `Document` from the server again.
```js
async function fromUuid(uuid, relative) {
  let {collection, documentId, embedded, doc} = _parseUuid(uuid, relative);
  if ( collection instanceof CompendiumCollection ) doc = await collection.getDocument(documentId);
  else doc = doc ?? collection?.get(documentId);
  if ( embedded.length ) doc = _resolveEmbedded(doc, embedded);
  return doc || null;
}
```

**Comment by aaclayton** [comment]
> Any chance of this getting treatment before V11?

Probably not, but it's *possible* we might backport it into a v10 closing release.
