### ISSUE TITLE
Check Dependent Systems/Modules for Compatibility Before Updating

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/foundryvtt#8884]
### User Experience

It would be great to be able to check for compatibility with  installed systems and modules when updating core, systems or modules. Something like a pop-up warning  when a user clicks 'Update', which loops through and checks the compatibility requirements of systems/modules that have dependencies on the package being updated.

**Comment by unsoluble** [comment]
Related to #8732

**Comment by aaclayton** [comment]
Closing as duplicate
