### ISSUE TITLE
Update Compendium UUID's to handle mixed-documents

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8886]
With the introduction of Compendium Folders, the old format of `Compendium.world.test.g2VbvDXLyXQu4G9t` is no longer going to work, since a document might be either the primary document type, such as `Actor`, or a `Folder.

The new format is `Compendium.world.test.Folder.g2VbvDXLyXQu4G9t` and `Compendium.world.test.Actor.g2VbvDXLyXQu4G9t`

**Comment by mkahvi** [comment]
For backwards compatibility, unspecified type could be treated as non-folder reference, which would reduce the breaking nature of this change.

**Comment by farling42** [comment]
It is definitely a big breaking change for everybody who uses compendiums to store their rule sets.

Having a sensible way of handling existing UUID format is required.

Why is the specific item type required in the UUID? Are you going to allow a single compendium to store a mix of different types?

**Comment by cswendrowski** [comment]
Thanks all for the feedback - after discussion, we are removing the deprecation period on the current UUID format for compendium links. New links will generate with the new format, but we have no plans to remove support for the existing format.
