### ISSUE TITLE
Prosemirror - Allow double-clicking image to open an edit dialog to change path

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#8887]
TinyMCE previously supported double-clicking an existing image to change paths; since we have an insert image option it would be useful to reuse the same dialog for double-clicking to edit the image src path.

**Comment by aaclayton** [comment]
@Fyorl how easy would this be to improve upon? If the weight is low it would be good to try to get this in for V11 alongside some of our other ProseMirror UX improvements.

**Comment by Fyorl** [comment]
> @Fyorl how easy would this be to improve upon? If the weight is low it would be good to try to get this in for V11 alongside some of our other ProseMirror UX improvements.

I don't imagine it would be a lot of work
