### ISSUE TITLE
Feature Request: Automatically scroll settings header list to last selected

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#8892]
### User Experience

Incredibly minor UX ask: when opening the Configure Settings window, if a heading is selected, scroll the list down to that heading, like so:  ![](https://i.imgur.com/sody19U.png)
current behaviour: ![](https://i.imgur.com/0j6tBS7.gif)

**Comment by esheyw** [comment]
The absolute dream stretch goal would be to persist this through reloads, but that's probably a lot more work than scrolling to the currently selected heading on render? I hope.

**Comment by aaclayton** [comment]
Preserving the scroll state on re-render is what we should focus on. We try not to persist data like scroll positions across reloads and instead treat this as emphemeral session data.
