### ISSUE TITLE
The texture loader may load the texture again if the previous call to `loadTexture` of the same resource wasn't awaited

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8909]
### What happened?

The texture loader should cache the promise of the base texture not the texture itself and return the cached promise. At the moment, if the previous `loadTexture` isn't awaited and the loader is still in the process of loading, another base texture is loaded and created, because the cache is still empty. `ControlIcon`'s `draw` call isn't awaited in a bunch of places, and so at least in the case of notes that's a problem:
```js
new Set(canvas.notes.placeables.map(n => n.controlIcon.texture.baseTexture)).size === canvas.notes.placeables.length // true in the active scene after login/reload even if all notes have the same icon image
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Blank scene and reload (`icons/svg/book.svg` must not have been loaded yet). Execute
```js
p1 = loadTexture('icons/svg/book.svg');
p2 = loadTexture('icons/svg/book.svg');
t1 = await p1;
t2 = await p2;
console.assert(t1.baseTexture === t2.baseTexture); // fails
```

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We want to evaluate the new PIXI v7 asset loader which may allow us to phase out our custom implementation. Depending on the outcome of that investigation, we would either want to fix this issue in our own implementation or switch the way we are loading textures to begin with.

**Comment by Feu-Secret** [comment]
Resolved with the new `TextureLoader` based on `PIXI.Assets`.

**Comment by dev7355608** [comment]
Not working for video textures, which are not loaded by `PIXI.Assets`:
```js
p1 = loadTexture("test.webm")
p2 = loadTexture("test.webm")
t1 = await p1;
t2 = await p2;
console.assert(t1.baseTexture === t2.baseTexture)
```
![image](https://user-images.githubusercontent.com/31905376/229106936-51a12f7e-1b23-4d28-ae9c-8f991109a915.png)
