### ISSUE TITLE
Journal Entry Pages can get incorrectly rearranged during small drag operations under certain conditions.

### ISSUE THREAD

**Issue by yjeroen** [foundryvtt/foundryvtt#8915]
### What happened?

Journal subpage jumps to the top if clicked a millisecond too long when it gets in "drag" mode

I expect the subpage to not change in order.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

[journal-clickdrag-issue.webm](https://user-images.githubusercontent.com/1303988/220332769-15c592b4-1416-4624-98ea-4b32afe061e4.webm)

### What core version are you reporting this for?

Version 10 Build 219

### Relevant log output

```shell
No console log is triggered
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Strange one! I'll have to look into this, I haven't seen this happen personally. 

I think we should consider reducing the sensitivity for Journal Entry Pages to what constitutes a dragstart. Perhaps it's currently too sensitive. Also, dropping a page on itself should not cause it to be re-sorted in the order. We can investigate improvements in both these areas.

**Comment by Fyorl** [comment]
We're using the native HTML drag-and-drop API here, which doesn't really have a configurable 'sensitivity' outside of anything a given browser might provide. We could implement something, but it would be strange to only do it for journal page drag-and-drop and not all the other places in the UI where we use native HTML drag-and-drop.

Having the page jump to the top when dropped on itself definitely looks like a bug though.

**Comment by yjeroen** [comment]
Else maybe provide a lock or edit node so order and journal title are not editable by default?
