### ISSUE TITLE
Light sources are not disabled if the vision mode turns of light sources

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8919]
### What happened?

Light sources not disabled by the Tremorsense vision mode:

![image](https://user-images.githubusercontent.com/31905376/220409151-6d845869-6d57-4daa-9216-e59bc0530ead.png)

![image](https://user-images.githubusercontent.com/31905376/220409092-f0e76916-e5e2-4b7c-b4e0-217cac2482e1.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Token with Tremorsense. Place a light source outside of the vision range with another token inside of it. Control the token with Tremorsense. Observe that the token in the light source is detected.

### What core version are you reporting this for?

Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Fixed with `active/hasActiveLayer` overhaul.
