### ISSUE TITLE
Fix and improve the workflow for vision modes deactivation and activation handlers

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8930]
### What happened?

Only `#callActivationHandlers` calls `activate`/`deactivate` for vision sources that are added or removed. There's no activation or deactivation calls if a vision mode is changed. There's also the issue that custom vision sources added in a `initializeVisionSources` hook are never activated but are deactivated each time `initializeSources` is called, because the hook is called after `#callActivationHandlers`.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Change the vision mode of a token and observe `activate`/`deactivate` calls.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Yes, I see the problematic when a vision mode is changed. With our current framework, tracking `activated`/`deactivated` handlers are tricky. We need to rethink how these handlers are called.
