### ISSUE TITLE
`SchemaField#toObject` throws an error when the initial field value is `null`

### ISSUE THREAD

**Issue by In3luki** [foundryvtt/foundryvtt#8932]
### What happened?

![image](https://user-images.githubusercontent.com/41452412/221356176-61f04525-bb52-4766-8109-b2c9677cd121.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

Add a nullable `SchemaField` to some `DataModel`:
```js
{
    foo: new foundry.data.fields.SchemaField({
        bar: new foundry.data.fields.StringField(),
    }, { nullable: true, initial: null }),
}
```

Try to call `toObject(false)` on that `DataModel`:

![schema-to-object](https://user-images.githubusercontent.com/41452412/221356287-489e5788-ec34-4c71-a92f-c2cb44abbb23.png)

### What core version are you reporting this for?

Version 10 Stable (build 291)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Related to https://github.com/foundryvtt/foundryvtt/issues/8934, addressed both.
