### ISSUE TITLE
Renaming players in User Management throws a validation error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8945]
Originally reported by Vex#4122 https://discord.com/channels/170995199584108546/956306859491471420/1070796755618238505

**All Modules Disabled** Yes  
**Browser** Chrome  
**Short Description** When creating new users, the next user created after the GM is Player2. Then Player3. If you try to rename those to Player1 and Player2 respectively, foundry will not be able to do so, and reverts the names back to the original, throwing an error message
```
User names must be unique, the name Player2 is already taken
fetch @ foundry.js:59187
```

**Steps to repro**
Create 2 new users. Rename the first user. Rename the second user to the first user. Error happens

**Comment by aaclayton** [comment]
May no longer be an issue after bugfixes in last release, will verify.

**Comment by aaclayton** [comment]
This issue no longer occurs in V11.
