### ISSUE TITLE
Roll instance stores dice in evaluation order rather than left-to-right

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8948]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1073879271694684231

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Any  
**Short Description of bug:** Roll instance .dice getter gives unexpected results.  
**Simple steps to reproduce the bug:**
```js
const roll = await Roll.create("1d20+(1d4)").evaluate()
console.log(roll.dice[0].faces);
```

You'll see the output is 4 instead of 20 as one would expect for the first die roll.

If you do `/r 1d20+(1d4)` and open the breakdown, you'll similarly see the rolls out of order.

It would be preferable that the eliminated rolls were stored with the terms they were collapsed into to maintain order, instead of general list on the roll itself that is prepended to `.dice` return value.

**Comment by dmrickey** [comment]
This is a bigger problem if systems are relying on the first roll to determine extra features. For example a nat 1 / nat 20 for critical fail/fumble and adding that to some kind of result data. Something super contrived like `1d20 + (1d1)` will always result in a critical fail.

**Comment by mkahvi** [comment]
The PF1 solution is kind of ugly, but it works for that system. I'd prefer the solution proposed in the bug report was applied to core, but it's too deep to do in the system in nice manner.

**Comment by mkahvi** [comment]
This also affects core Foundry default roll display for basic rolls I believe. Since  if the d4 rolls 1, Foundry shows that roll as a failure, same for rolling 4 on it, and it'll show it as success, instead of being based on the d20.

**Comment by dmrickey** [comment]
Is this still in the running for v12?

**Comment by aaclayton** [comment]
Yes, I think this is likely to be addressed in V12 as part of https://github.com/foundryvtt/foundryvtt/issues/9773

**Comment by aaclayton** [comment]
@Fyorl does the AST from Peggy give us some flexibility in terms of what order we store contained Dice in the array?

**Comment by Fyorl** [comment]
I believe we can actually close this already. This works as requested in the original issue now in v12:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/ba8dc4a6-c26b-44d8-9c41-61cab5d3c9d2)

**Comment by aaclayton** [comment]
Great!
