### ISSUE TITLE
Token textures are distorted when moving them on the canvas

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8950]
Originally reported by MaxPat#7936 https://discord.com/channels/170995199584108546/956306859491471420/1074781251707343101

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win/Chrome  
**Short Description of bug:** Token Image is distorted on Drag  
**Simple steps to reproduce the bug:** Assign a width x height that are not the same number, eg. 1x2, drag token to canvas. Witness the token art is distorted to fill the specified area, but once placed adjusts to fit the smallest dimension  
**Screenshots:** Top: 1x1 on left, 1x2 being dragged on right, Bottom: 1x1 on left, 1x2 on right after placement

![image](https://user-images.githubusercontent.com/207433/221669746-6d953e1e-f024-450a-bc2c-71e5e399df80.png)

**Comment by aaclayton** [comment]
This is not an easily fixed problem and relates to some tech debt that we have regarding workflows where you drag content from the sidebar onto the canvas. There might be some simple thing we can do to "fix" the bug in the short term but a longer-term redesign of this interaction workflow is needed.

**Comment by Feu-Secret** [comment]
@aaclayton Confirming that this issue is no more relevant in v11. I'm closing it as completed.
