### ISSUE TITLE
Tooltip sticks on the ProseMirror save button

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8951]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1075312582405136444

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Any  
**Short Description of bug:** Tooltip sticks for ProseMirror save button.  
**Simple steps to reproduce the bug:**

1) Use ProseMirror editor
2) Hover over save button until tooltip appears
3) Save
4) Note how the tooltip for the button sticks around until you hover something else that gives a tooltip.

Likely occurs for other similar instances where the element is removed and never triggers mouseleave event.

**Comment by Fyorl** [comment]
Looks like a regression of #8030 if reproducible

**Comment by Fyorl** [comment]
Not able to reproduce this

**Comment by mkahvi** [comment]
> Not able to reproduce this

If possible backport whatever fix you have to v10 final, tho it's non-critical, just annoying.

**Comment by mkahvi** [comment]
Personally I can reproduce this only on Opera GX. In Electron it works fine currently, though I'm pretty sure I experienced the issue originally in Electron.

**Comment by Fyorl** [comment]
> If possible please backport whatever fix you have to v10 final, tho it's non-critical, just annoying.

This was already fixed in v10 (#8030). The fix relies on specific browser behaviour of firing a `pointerenter` on an element when elements in front of it are removed from the DOM, without the mouse moving. It's possible that Opera GX doesn't behave in that way, but since it's based on Blink, I wouldn't have thought so.

**Comment by mkahvi** [comment]
I have a friend who had the same issue and they confirmed they were using Opera GX also.

**Comment by unsoluble** [comment]
(Opera GX is an explicitly unsupported fork)

**Comment by silvative** [comment]
I was not able to reproduce this error on Firefox and it sounds like it is not present on Electron either
