### ISSUE TITLE
UI scrolls up and partially hides

### ISSUE THREAD

**Issue by nocturnaltortoise** [foundryvtt/foundryvtt#8984]
### What happened?

Mid game (Pathfinder 2e), the UI for the players (not GM) seems to scroll up as you can see in the screenshot. Seemed to happen when damage was being applied. I've included some errors in the console that happened at the same time, but not always so may be unrelated.

![2023-03-03_22-14-09](https://user-images.githubusercontent.com/4539495/222846992-a4895d07-06ac-4805-91ce-43fd54f41d1a.png)

![firefox_2023-03-03_21-58-24](https://user-images.githubusercontent.com/4539495/222847036-5e893d9f-2334-4577-97df-c08f42c77261.png)

![firefox_2023-03-03_22-00-49](https://user-images.githubusercontent.com/4539495/222847071-36144d43-fd2a-4c99-8601-f934b0d2f748.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open up forge-vtt in the web browser as a player in a Pathfinder 2e game, deal damage to a target.

### What core version are you reporting this for?

Version 10 (Build 291), Pathfinder 2nd Edition 4.8.3

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by esheyw** [comment]
You really shouldn't post bug reports without checking if they happen with no modules -- This is, we think, an interaction with PF2e Target Damage and at least one other thing we haven't pinned down yet. Please come help us troubleshoot in the appropriate thread on [the system community discord](https://discord.gg/pf2e)

**Comment by aaclayton** [comment]
Closing as a module-related issue.
