### ISSUE TITLE
Ensure that applying a status effect overlay can downgrade previous overlays to a classic status icon.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8985]
### What happened?

Current behavior:
![overlay_status](https://user-images.githubusercontent.com/31905376/222873182-a24e0381-e183-44e4-be93-b5c5b8178479.gif)

Expected behavior:
![overlay_status_expected](https://user-images.githubusercontent.com/31905376/222873185-da606ee3-7b6f-48a3-bd9f-8ab76b901675.gif)

All overlay effects except the final one should be drawn normally:
```diff
      // Draw actor effects first
      for ( let f of actorEffects ) {
        if ( !f.icon ) continue;
        const tint = Color.from(f.tint ?? null);
        if ( f.getFlag("core", "overlay") ) {
+         if ( overlay ) promises.push(this._drawEffect(overlay.src, overlay.tint));
          overlay = {src: f.icon, tint};
          continue;
        }
        promises.push(this._drawEffect(f.icon, tint));
      }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Assign two overlay status effects.

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
It is intended for the `overlay` status to be singleton - in that there can only ever be one. This looks like a UX bug that when a second overlay status is applied the first should be automatically un-applied OR potentially downgraded to a non-overlay status.

**Comment by Feu-Secret** [comment]
I like this idea of degrading the previous overlay to a non-overlay. Let's go for it!
