### ISSUE TITLE
Add a way to reveal the fog of war for all players

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8987]
### User Experience

The core solution that is usually recommended to reveal the fog for all players when someone asks about it is this macro:
```js
const dimensions = canvas.scene.dimensions
let [created_light] = await canvas.scene.createEmbeddedDocuments('AmbientLight', [{dim: dimensions.maxR, vision: true, walls: false, x: dimensions.width/2, y: dimensions.height/2}])
await new Promise(r => setTimeout(r, 100));
await created_light.update({hidden: true})
await created_light.delete()
```
There are obvious problems with this macro: requires all players to be viewing the scene and briefly gives visibility of the entire scene, which could spoil things.

It's possible to override the fog exploration with a macro like this, but there's no way to force a fog load for all users. You'd have to tell your players to reload when you reveal the fog in a session.
```js
async function revealFog(scene = canvas.scene) {
    await scene.update({ fogExploration: false });
    for (const user of game.users) {
        const explorationData = {
            scene: scene.id,
            user: user.id,
            explored: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII="
        };
        const fogExplorationCls = getDocumentClass("FogExploration");
        let exploration = await fogExplorationCls.get({ scene, user });
        if (exploration) await exploration.update(explorationData, { diff: false });
        else {
            exploration = new fogExplorationCls(explorationData);
            await fogExplorationCls.create(exploration.toJSON());
        }
    }
}
```

Another problem with both macros is that, if a new user is created after the fog was revealed, the scene is unexplored for them, and the macro has to be run again.

There a modules that have the feature to reveal the fog, but that's just one of many things they do, and you shouldn't need a module for this. But the macro solutions aren't good enough.

I imagine a *Reveal Fog of War* button next to the *Reset Fog of War* button would be a good place:
![image](https://user-images.githubusercontent.com/31905376/222903995-51bc6137-f42b-4124-8dbb-49a8b4bc0b54.png)

**Comment by Feu-Secret** [comment]
This functionnality is something that we want to bring to core. More information to come.

**Comment by dev7355608** [comment]
> This functionnality is something that we want to bring to core. More information to come.

I assume this would have been a part of #8582, correct?
