### ISSUE TITLE
`WeilerAthertonClipper` should not be authorized to mutate the points of the subject polygon by default

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8991]
### What happened?

I think it's fair to expect that the subject polygon is not mutated by the clipping algorithm. `WeilerAthertonClipper` reverses the orientation of the polygon if it isn't positive. `WeilerAthertonClipper` should create a copy of the polygon in case it isn't positively orientated. The orientation of the subject might be important to the caller and therefore should not be changed.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
p = new PIXI.Polygon(0, 0, 0, 100, 100, 0);
new PIXI.Circle(0, 0, 50).intersectPolygon(p, { weilerAtherton: false })
p.points // [0, 0, 0, 100, 100, 0]
```
```js
p = new PIXI.Polygon(0, 0, 0, 100, 100, 0);
new PIXI.Circle(0, 0, 50).intersectPolygon(p, { weilerAtherton: true })
p.points // [100, 0, 0, 100, 0, 0]
```

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
I think this is done like that for performance reasons. We should certainly document the fact that the `WeilerAthertonClipper` mutates the points.

**Comment by dev7355608** [comment]
If it isn't changed, this behavior needs to documented for the following functions too. All of these may reverse the orientation of the subject polygon unexpectedly. The user can't know that these functions use `WeilerAthertonClipper` unless it's documented or they inspect the source code.
- `PointSourcePolygon#applyConstraint`
- `PIXI.Circle#intersectPolygon`
- `PIXI.Polygon#intersectCircle`
- `PIXI.Polygon#intersectRectangle`
- `PIXI.Rectangle#intersectPolygon`
- and `PointSourcePolygonConfig#boundaryShapes` should also mention is behavior.

Core seems to pass only positively-orientated polygons and also never the same polygon twice (meaning the caching of the orientation seems to do actually nothing at the moment; this is the only place where `isPositive` is used, and it's only called once per polygon). I tested:
```js
  constructor(polygon, clipObject, clipType, clipOpts) {
    if ( polygon._isPositive !== undefined ) throw new Error();
    if ( !polygon.isPositive ) throw new Error();
```
Never throws an error. So there shouldn't be any performance concerns from core's perspective if it created a copy instead of mutating, because that would never happen.

**Comment by Feu-Secret** [comment]
It is fair. Indeed a copy would probably be more appropriate.

**Comment by caewok** [comment]
Yes, I agree it would be better to make a copy if reversing. Positively-oriented polys are the norm, from what I can tell, in Foundry, so performance issue is unlikely.
