### ISSUE TITLE
`PIXI.Polygon#reverseOrientation` documentation is misleading.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8992]
### What happened?

Documentation claims that the points are mutated in-place:
> Reverse the order of the polygon points in-place mutating the current polygon.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
poly = new PIXI.Polygon(0, 0, 0, 100, 100, 0);
p1 = poly.points;
poly.reverseOrientation();
p2 = poly.points;
console.assert(p1 === p2); // fails
```

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Is this a documentation bug and we want the transformation to return a new polygon? or do we want the mutation to occur in-place? I think it's probably a documentation bug and we are okay with the points being a new array?

**Comment by dev7355608** [comment]
Looking at the title of this issue, I assume just the documentation has been changed and the "in-place" part has been removed. But I recommend to reverse in-place: that's much more efficient. A new point array is almost a new polygon. I'd expect `reverseOrientation` to reverse in-place if the documentation doesn't mention anything in this regard. Assume you want a copy of the polygon in the the reversed orientation: you'd do `polygon.clone().reverseOrientation()` (#8991). This creates a clone the points and then creates another point array with reversed orientation from cloned array. It isn't efficient at all. I don't see any benefits from `reverseOrientation` creating a new array.
