### ISSUE TITLE
`AbstractBaseMaskFilter` creates array object each `apply` 

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8993]
### What happened?

```diff
  /** @override */
  apply(filterManager, input, output, clear, currentState) {
-   const screen = filterManager.renderer.screen ?? null;
-   if ( screen ) this.uniforms.screenDimensions = [screen.width, screen.height];
+   this.uniforms.screenDimensions = canvas.screenDimensions;
    filterManager.applyFilter(this, input, output, clear);
  }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Good catch. This case escaped our vigilance.
