### ISSUE TITLE
Don't let light sources above a roof illuminate the space below the roof

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8996]
### User Experience

Just like light sources under a roof don't illuminate the space above the roof, light sources above a roof shouldn't illuminate the space below the roof (the light is blocked by the roof in both directions). We can use the new weather mask channel to make this happen.

In this example the light source is above the roof. Once the token steps under the roof, the roof is hidden, but the space below the roof is filled with the light that should be blocked by the roof, which is still there.
![roof_before](https://user-images.githubusercontent.com/31905376/223125739-e0416fae-2a20-4a55-97b1-d0ae37eb3ff4.gif)

After the suggested changes the light doesn't illuminated the space under the roof as expected.
![roof_after](https://user-images.githubusercontent.com/31905376/223125746-243c405b-8d5d-4ca0-86e5-f2d2391b24f3.gif)

The changes are simple. Replace
```
step(depthColor.g, depthElevation)
```
by
```
step(depthColor.g, depthElevation) * (1.0 - step((255.5 / 255.0) - depthColor.b, depthElevation))
```
in the light shaders. One more change is required: the global light sources is special and should illuminate everything even below roofs (maybe it wouldn't have to behave that way, but changing this behavior would be breaking). So `GlobalLightSource` needs to override `_updateCommonUniforms` to set the `depthTexture` to the empty texture, which makes all depth checks pass (no additional uniform required).
```js
  /** @override */
  _updateCommonUniforms(shader) {
    super._updateCommonUniforms(shader);
    shader.uniforms.depthTexture = PIXI.Texture.EMPTY;
  }
```

**Comment by aaclayton** [comment]
Worth considering I think

**Comment by caewok** [comment]
Wouldn’t light config need to have an elevation setting so the GM could set the light elevation for non-global lights? Otherwise, how would you light the inside of buildings with roofs?

To be clear, I think this is generally a good idea. And I don’t have laptop access right now, so for all I know elevation config is already in v11.

**Comment by dev7355608** [comment]
There's no need for that. Almost nothing would change for non-Levels users, because in core all nonglobal lights are always at elevation 0 and therefore underneath roofs. The only exceptions are token lights, which have the same elevation as the token. Here's an example with ambient light (green, elevation 0) and a light-emitting token (red, elevation 20) on top of the roof:
![roof_example](https://user-images.githubusercontent.com/31905376/223468544-c8a0b82e-a7dc-495a-9a2b-1ec2032f0d72.gif)
