### ISSUE TITLE
Add support for a list of favorites in the filepicker to quickly access chosen folders

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#8998]
### User Experience

When using Foundry VTT it's common to need to access a number of folders frequently. This adds support for creating a list of "favorite" folders that you can quickly access. It works across multiple sources and prefixes the folder's label with an icon representing the folder's source.
![image](https://user-images.githubusercontent.com/5018947/223183031-9c8b1796-4d50-421b-b3fb-9b5e5f155b3d.png)

**Comment by mattexdee** [comment]
Finished as part of https://github.com/foundryvtt/foundry-vtt/pull/897

**Comment by EddieEldridge** [comment]
I've wanted this for so long. Amazing work!
