### ISSUE TITLE
Module management list tooltip does not adjust with scroll

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9003]
ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Windows 11 (22621.1105), Chrome (110.0.5481.178)
Short Description of bug: Module list tooltip appears 2 modules above the hovered module.
Simple steps to reproduce the bug: I just put the mouse over an icon on a module and the tooltip appears just below the icons in a module three rows above. This occurs only if the modules list is scrolled partially down (if the window is scrolled very near the top, then the placement is in the correct position).

From: https://discord.com/channels/170995199584108546/1065764070680186930/1081732433583542372

**Comment by Fyorl** [comment]
Closing as nonrepro
