### ISSUE TITLE
Introduce RenderFlags which improves and generalizes the way that Document data changes flow into PlaceableObject#_onUpdate workflows which improves efficiency and maintainbility of rendering operations.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9026]
# RenderFlags
The new `RenderFlags` class is introduced which manages a `Set` of boolean flags and applies those flags just-in-time as part of the render loop. RenderFlags are used for both `PlaceableObject` as well as by the canvas `PerceptionManager`.

The redesign and rationalization of the code has led to a number of API changes, most of which are non-breaking but some are. The changes to `PlaceableObject` and subclasses are documented below.

# API Changes
This work involves a number of API changes to standardize and rationalize the way that PlaceableObject subclasses work. In general, we have worked to avoid breaking any existing public or protected APIs. The following changes largely involve enforcing that methods that were previously marked as `@private` are now strictly treated as such. In some cases methods that were previously private are now more accessible as either public or protected.

If there are module or system developers who were previously relying on one of these methods being accessible despite being marked `@private`, we encourage you to reach out to us. We are willing to consider making some of these methods more accessible if there is a clear use case for doing so.

## AmbientLight
* `AmbientLight#_drawControlIcon` which was previously `@private` is now instance private.

## AmbientSound
* `AmbientSound#_createSound` which was previously `@private` is now instance private.
* `AmbientSound#_drawControlIcon` which was previously `@private` is now instance private.

## Drawing
* `Drawing#_drawTime` which was previously `@private` is now instance private.
* `Drawing#_fixedPoints` which was previously `@private` is now instance private.
* `Drawing#_removePoint` which was previously `@private` is now `@internal`
* `Drawing#_onDrawingTextKeydown` which was previously `@private` is now instance private.
* `Drawing#_rescaleDimensions` which was previously `@private` is now instance private.
* `Drawing.normalizeShape` which was previously `@private` is now public.

## Measured Template
* `MeasuredTemplate#_getCircleShape` which was previously `@private` is now static private.
* `MeasuredTemplate#_getConeShape` which was previously `@private` is now static private.
* `MeasuredTemplate#_getRectShape` which was previously `@private` is now static private.
* `MeasuredTemplate#_getRayShape` which was previously `@private` is now static private.
* `MeasuredTemplate#_borderThickness` which was previously `@private` is now `@protected`.

## Tile
* `Tile#_getAlphaBounds` which was previously `@private` and unused has been deleted.
* `Tile#_linkedSprites` which was previously `@private` and unused has been deleted.
* `Tile#_refreshBorder` which was previously `@private` is now instance private.
* `Tile#_refreshPerception` which was previously `@private` is now instance private.
* `Tile#_createTextureData` which was previously `@private` is now instance private renamed as `Tile##refreshTextureData`
* `Tile#_textureData` which was previously `@private` is now instance private.
* `Tile#_prevOccludedState` which previously was implied as public is now instance private.

## Token
* `Token#updatePosition` has been deprecated without replacement as its functionality is no longer required.
* `Token#renderHUD` has been deprecated in favor of `token.renderFlags.set()`
* `Token#_isVisionSource` which was previously `@private` is now `@protected`.
* `Token#_cleanData` which was previously `@private` is now instance private.
* `Token#_drawAttributeBars` which was previously `@private` is now instance private.
* `Token#_getBorderColor` which was previously `@private` is now instance private.
* `Token#_drawTooltip` which was previously `@private` is now instance private.
* `Token#_getTooltipText` which was previously `@private` is now instance private.
* `Token#_getTextStyle` which was previously implied as private is now `@protected`.
* `Token#_toggleOverlayEffect` which was previously `@private` is now instance private.
* `Token#_canViewMode` which was previously `@private` is now instance private.
* `Token#_drawNameplate` which was previously `@protected` is now instance private for consistency with other draw sub-methods.

## Walls
* `Wall#_removeIntersections` which was previously `@private` is now instance private
* `Wall#_onModifyWall` which was previously `@private` is now instance private
* `Wall#_drawDirection` which was previously `@private` is now instance private
* `Wall#_getWallHitPolygon` which was previously `@private` is now instance private
* `Wall#_getWallColor` which was previously `@private` is now instance private
* `WallsLayer#highlightControlledSegments` is now deprecated in favor of `wall.renderFlags.set({refreshHighlight: true})`

**Comment by theripper93** [comment]
So, i'm using both _drawNameplate and _drawBars currently in v10. I do this to get the PIXI object (since PIXI has no clone() method) and i render those to a texture. Wouldn't this change pervent any kind of interaction like this or am i missing something?

**Comment by aaclayton** [comment]
@theripper93 this approach will not work in V11. `#drawNameplate()` and `#drawAttributeBars` are private methods. You can, however, reference their created objects to perform your needed workflow using, for example:

```js
Hooks.on("refreshToken", (token, renderFlags) => {
  if ( renderFlags.refreshNameplate ) {
    const nameplate = new PreciseText(token.nameplate.text, token.nameplate.style);    
    const container = new PIXI.Container();
    container.addChild(nameplate);
    const base64 = canvas.app.renderer.extract.base64(container);
  }
});
```
