### ISSUE TITLE
Allow Package manifests to declare Packs organized by Folder

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9033]
These folders should be created if not already present, and the Packs should be organized into them.

**Comment by aaclayton** [comment]
This work was unable to be completed in time for V11. We can revisit in V12 if desired.

**Comment by stwlam** [comment]
If open for consideration, it would still be useful to have folder data defined in `BasePackage#packs` (or wherever the intended place in the schema was)--even if the full feature is not implemented until a later Foundry version--to allow for modules or systems to provide a temporary solution.

**Comment by aaclayton** [comment]
I'm not sure this is still open for consideration, but I think there is a strong desire for this feature to exist so if we can rationally justify still doing it we should.
