### ISSUE TITLE
Allow users to reorganize Compendium Packs into different Folders than their declaring Manifest specifies

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9034]

**Comment by Zanderaf** [comment]
Is this in essence what the 2nd part of the Compendium Folders module did? The compendiums into folders part? I know I asked about this maybe a week ago and if it is the case I"m happy its opened!

**Comment by aaclayton** [comment]
Closing as duplicate/redundant of #9032, #9035, and #9132
