### ISSUE TITLE
Improve the way how elevation is mapped with primary canvas objects

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9045]
### User Experience

Because of the limited precision of the depth mask, objects that are not rendered into the depth mask should be skipped in `sortChildren` to not expand the min/max elevation range needlessly. Any object in the primary canvas group with a large finite elevation can destroy the depth mask (for example, a token at elevation -10000) such that lights are rendered above roofs.
```diff
  /**
   * Override the default PIXI.Container behavior for how objects in this container are sorted.
   * @override
   */
  sortChildren() {
    this.#elevation.min = Infinity;
    this.#elevation.max = -Infinity;
    for ( let i=0; i<this.children.length; i++ ) {
      const child = this.children[i];
      child._lastSortedIndex = i;
+     if ( !child.renderOcclusion ) continue;
      const elevation = child.elevation || 0;
      if ( elevation === Infinity ) continue;
      if ( elevation < this.#elevation.min ) this.#elevation.min = elevation;
      if ( elevation > this.#elevation.max ) this.#elevation.max = elevation;
    }
    this.children.sort(PrimaryCanvasGroup._sortObjects);
    this.sortDirty = false;
  }
```

Another suggestion I have is that the depth mask loops over all children and calls `renderOcclusion` on those that define it, instead of only the tiles. This makes is easier for other objects to render into the depth mask.
```diff
  /**
   * Create the roofs container.
   * @returns {PIXI.Container}
   */
  #createRoofsContainer() {
    const c = new PIXI.Container();
    const render = renderer => {
-     for ( const tileMesh of canvas.primary.tiles ) {
-       tileMesh.renderOcclusion(renderer);
-     }
+     for ( const child of canvas.primary.children ) {
+       child.renderOcclusion?.(renderer);
+     }
    };
    c.render = render.bind(c);
    return c;
  }
```

And maybe `renderOcclusion` should be renamed to `renderDepth`. That should make more sense.

**Comment by aaclayton** [comment]
I think this makes sense, will defer to @Feu-Secret for prioritization.
