### ISSUE TITLE
Extend cached container render texture configuration and choose the best texture format for canvas masks

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9048]
### User Experience

Now that WebGL 2 is required, we have more options.

### Format
Only the green and blue channels of the Occlusion/Depth mask are used. If those channels are changed to red and green, the texture format could be `RG`. Only the red channel of the Vision mask is used: change the `type` to `RED`.

### Type

The type of Occlusion/Depth mask could be changed to `FLOAT` (or `HALF_FLOAT`) to increase the precision of the depth buffer. Rendering floating point textures isn't necessarily supported: that's why it's necessary to check whether the `EXT_color_buffer_float` extension is present.
```js
class CanvasDepthMask extends CachedContainer {
  constructor(...args) {
    super(...args);
    this.#createDepth();
    if ( canvas.app.renderer.context.extensions.colorBufferFloat ) {
      this.renderTexture.baseTexture.type = PIXI.TYPES.FLOAT;
      this.renderTexture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
      this.float = true;
    }
  }
```
Depending on whether it's supported we round in `mapElevationAlpha` or not.
```js
mapElevationAlpha(elevation) {
    // ...
    if ( canvas.masks.depth.float ) return x / 255; // without rounding
    else return Math.round(x) / 255; // with rounding
}
```
Integer textures aren't an option, because they skip blending according to the spec, and the current implementation requires `MAX` blending.
> OpenGL ES Version 3.0.6 (November 1, 2019) - Section 4.1.7 (Blending)
> > Blending applies only if the color buffer has a fixed-point format. If the color buffer has an integer format, proceed to the next operation.

### Scale Mode
The `scaleMode` of the Occlusion and Depth mask should be `NEAREST`. It doesn't make sense to allow `LINEAR` filtering, because they contain depth values. `NEAREST` should be a bit faster. Also `LINEAR` filtering on floating point texture isn't necessarily supported; it's only supported if the `OES_texture_float_linear` extension is present. We don't need `LINEAR` filtering on any of the canvas masks, even the Vision mask, because only the centers of the pixels are sampled.

**Comment by aaclayton** [comment]
Good suggestions for improving efficiency. We *may* want to split this issue into 2 parts:

1. The color channel changes and assigning `NEAREST` as the `scaleMode` are probably non-controversial
2. Changing the depth texture to support floating point precision sounds like a nice idea, but I imagine comes at some cost (as well as only partial compatibility). We may want to consider that separately.

I'll pass this over to @Feu-Secret for his thoughts.
