### ISSUE TITLE
Apply Default Token configuration to Actors imported from Compendiums

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9053]
As a GM with a Default Token configuration such as "Display Name", I would like that setting to supersede whatever settings an imported Compendium Actor's token has

**Comment by stwlam** [comment]
Related/duplicate? https://github.com/foundryvtt/foundryvtt/issues/8660

**Comment by cswendrowski** [comment]
Dupe of https://github.com/foundryvtt/foundryvtt/issues/8660
