### ISSUE TITLE
Ability to set language per world instead of client.

### ISSUE THREAD

**Issue by SalieriC** [foundryvtt/foundryvtt#9055]
### User Experience

I'm playing a lot of different worlds, settings and systems. Most in English but sometimes I play with kids or teens who are not as fluent in English. In these cases I need the interface in my native language so everyone is on the same page. I'd much appreciate if there were a way to save the language as a world setting instead of a client one.

**Comment by aaclayton** [comment]
You can set the default language in server application settings. This default server language will be used for all worlds and all clients unless the client has specifically chosen a different language.

**Comment by SalieriC** [comment]
I don't get how that will help me in my case. I'd like to have a different language preference for each world so I don't have to change it manually every time. The server application setting isn't going to help me with that.
I do realise that this is a somewhat niche problem to have though.
