### ISSUE TITLE
Support passing a pre-configured HTMLElement to Tooltip#activate instead of only text content.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9056]
### User Experience

This would allow giving the tooltips DOM that already has listeners and other relevant bits hooked, without having to do it in roundabout manner by using mutation listener for the tooltip and figuring out if there is anything to listen on it.

This makes it more viable for macros to use it, and modules and systems that like adding lots of locked tooltips don't need a monolithic mutation observer proxy nor million small ones.

Oversimplified example:
```js
const dom = document.createElement("div");
const someEl = document.createElement("a");
someEl.addEventListener("click", doStuff);
dom.append(someEl)

game.tooltip.activate(element, { dom });
```

This simplifies tooltip usage, maintains context with the listeners, removes need for complicated mutation observer, and so forth.

Obviously this doesn't help cases where you use `data-tooltip`, but those I doubt can be helped for this.

**Comment by aaclayton** [comment]
Pretty good suggestion I think. We'll workshop what teh API would be but I think it makes sense to be able to directly pass in an HTMLElement to be used as the tooltip content.
