### ISSUE TITLE
Improve the API design of toggling the Combat state for Tokens with new methods Token#toggleCombatant and Token.toggleCombatants which replace the prior Token#toggleCombat method.

### ISSUE THREAD

**Issue by dmrickey** [foundryvtt/foundryvtt#9068]
# Implemented Feature
## New Methods
- `TokenDocument.createCombatants(tokens, options)` is a convenient way to bulk create Combatants from TokenDocuments
- `TokenDocument.deleteCombatants(tokens, options)` is a convenient way to bulk delete Combatants from TokenDocuments
- `TokenDocument#toggleCombatant(active, options)` handles toggling the combat state of that specific TokenDocument.

## Deprecations
- The prior method `Token#toggleCombat` is deprecated and will be removed in v14.
- The method `TokensLayer#toggleCombat` is deprecated and will be removed in v14.

# Original Request

I have a reference to a specific token that I was wanting to add to combat. So I called `token.toggleCombat(game.combat)`. But it also added other tokens to combat.

Arrow is the reference I had. Other controlled tokens are added.
![image](https://user-images.githubusercontent.com/3664822/225702211-cf57f469-e42c-40cc-96fa-ed165cf8bbd8.png)

Originally I had this macro
```js
const combat = game.combat ?? await Combat.create({ scene: game.scenes.active.id });
await Promise.all(canvas.tokens.controlled
   .filter((token) => !token.inCombat)
   .map((token) => token.toggleCombat(combat)));
```

Highlighting those three tokens and running this macro gave me this combat
![image](https://user-images.githubusercontent.com/3664822/225703107-03305c4b-2f8e-4557-83f0-0b496bbe9d91.png)

I was expecting to have a single combat with only those three combatants. But when I call `toggleCombat` on an individual token, apparently it's using outside knowledge to add itself plus any other selected tokens to combat. So me calling that for each of those three tokens made it so each of those tokens were added three times. This is super unintuitive and I don't understand how it makes sense to call "token.toggleCombat` on a specific token to also perform that behavior on other tokens that I wasn't referencing.

I do see that the documentation for this method says this, but again--it doesn't make sense to perform this action on tokens I'm not referencing.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

I'm running pf1e, though it shouldn't be relevant as I don't believe it's overriding this core functionality at all.

Select multiple tokens and run this macro, each token is added to combat for each token selected (so 1 token selected is 1 combatant, 2 tokens is 4 combatants, 3 is 9, etc)

```js
const combat = game.combat ?? await Combat.create({ scene: game.scenes.active.id });
await Promise.all(canvas.tokens.controlled
   .filter((token) => !token.inCombat)
   .map((token) => token.toggleCombat(combat)));
```

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I agree that this API isn't great. We'll find some opportunity to improve it.

**Comment by aaclayton** [comment]
Comment from @esheyw

> The current behaviour is clearly stated in the documentation, but that is *not* what you'd assume that method called in that way would do. A method on a single token shouldn't be operating on more than that token, at least not without some indication in the name, IMO.
