### ISSUE TITLE
Preview state of token/ambient lights config can prevent updates from being persisted

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9070]
### What happened?

Updates while the config is open are diffed against the preview state, because the preview is applied to the source of the document. This can prevent the update from being persisted if the preview value is coincidentally the same value as in the update.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Place a light source.
2. Open light config.
3. Change *Light Color* to red (`#ff0000`).
4. `ui.activeWindow.object.update({ config: { color: "#ff0000" } })`
5. Close config without saving.

Excepted: The light color is red and stays red after reload.
Actual: No light color after reload.

If the update is performed with `{ diff: false }`, the change is persisted.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Related to #9067
