### ISSUE TITLE
`canvas.controls.debug.eventMode` should be `"none"`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9072]
### What happened?

Point source polygon visualization prevents interaction with the canvas.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
It's really annoying that the new PIXI behavior is that `eventMode = "auto"` by default in v7. I really feel that `eventMode` should be "none" by default and interactivity events should be opt-in. It is annoying to have to do code like:
```js
    /**
     * A container of cursor interaction elements.
     * Contains cursors, rulers, interaction rectangles, and pings
     * @type {PIXI.Container}
     */
    this.cursors = this.addChild(new PIXI.Container());
    this.cursors.eventMode = "none";

    /**
     * Ruler tools, one per connected user
     * @type {PIXI.Container}
     */
    this.rulers = this.addChild(new PIXI.Container());
    this.rulers.eventMode = "none";

    /**
     * A graphics instance used for drawing debugging visualization
     * @type {PIXI.Graphics}
     */
    this.debug = this.addChild(new PIXI.Graphics());
    this.debug.eventMode = "none";
```
It would be much better to assign `eventMode` to a non-none value when you activate event listeners. 

Maybe I will try and push this as a suggestion upstream to PIXI.
