### ISSUE TITLE
`DiceTerm`s should look for a service (set in `CONFIG`?) to asynchronously evaluate dice rolls

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9090]
### User Experience

In order to implement a module offering an asynchronous roll evaluation service, currently one must subclass or monkey-patch `DiceTerm`, `Die`, etc. and override or replace `DiceTerm#_evaluate`. A less-messy approach would be possible if the `DiceTerm` classes checked for an API-compliant object or function in `CONFIG` and utilized that, falling back to standard synchronous evaluation if no such service is found.

**Comment by Fyorl** [comment]
This can be accomplished in V12 P2 with the new unfulfilled rolls API. It requires registering a new `CONFIG.Dice.fulfillment.methods` with a `handler` that will be called to fulfil the Roll, and then setting the `CONFIG.Dice.fulfillment.defaultMethod` to this method.
