### ISSUE TITLE
updateSource strips data from object (locally)

### ISSUE THREAD

**Issue by RobertBeilich** [foundryvtt/foundryvtt#9098]
### What happened?

When `fromDropData` (foundry.js LL13724 -13755) is called with a document that does not have a `sourceId` it gets set by `document.updateSource`. In the process all data (e.g. flags) on the item that is not on the source is wiped (until page reload, as this change is only locally).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Reference https://github.com/foundryvtt/pf2e/issues/7089 for an example.

### What core version are you reporting this for?

Version 10 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
Hi, this can be closed: it's entirely a bug on our end.
