### ISSUE TITLE
Provide public methods to modify `MeasuredTemplate` shapes

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9101]
### User Experience

In v11 dev 1, the `MeasuredTemplate` shape methods are all private: `getCircleShape`, `getConeShape`, `getRectShape`, and `getRayShape`.  In addition, the `shape` property is set using a switch inside the private `refreshShape` method. This combination makes modifying shapes or adding new shapes extremely difficult for systems or modules. 

Personally, this obliterates my Walled Templates module. But I know other modules and systems vary template shapes. For example, creating a rounded rectangle shape. Or SWADE’s ice cream cone shape. 

I propose that you simply make these shape methods public, as a simple solution for now. One of the primary things the `MeasuredTemplate` should do is return shapes, so it seems an bit odd to make the shape functions private. 

If you are interested in a more thorough refactor, I suggest making each shape a subclass that inherits from `MeasuredTemplate`. Ultimately, this could make it easier for systems to define the templates they want to use for their game. (Also, it might be easier to cache the shape this way, instead of recalculating it in `refreshShape` regardless of whether the relevant properties have been changed.)

**Comment by aaclayton** [comment]
Thanks for bringing up your use case. This is one of the changes implemented during https://github.com/foundryvtt/foundryvtt/issues/9026 which converted PlaceableObject methods which were previously `@private` to be formally private. For modules like yours that have a need and use case for non-private access we can work on the right way to support that.

Does your module subclass `MeasuredTemplate`, or have you been relying on patching methods on the prototype?

**Comment by caewok** [comment]
My module currently uses libWrapper to patch the shape methods. That ensures good compatibility with systems and modules that expect to see the `MeasuredTemplate` class. 

In theory I might be able to subclass `MeasuredTemplate` instead, but if I remember correctly, JavaScript does not allow subclasses to call private methods of the parent class. I would run into the same problem with having to re-write (and keep up to date) all the private method code with the shape methods and the refresh method. 

I am open to either subclassing or patching, whichever makes more sense to ensure compatibility.

**Comment by caewok** [comment]
FYI, my module is primarily intended to have templates interact with (mainly, be blocked by) walls. It does this by running the sweep on the template origin and replacing the original shape a with a polygon that represents the collision of the template shape with walls.

**Comment by aaclayton** [comment]
@caewok I took a moment to look into this. Relaxing our private API here is a possible route forward, but I think there is a better path for your use case which is self-contained, modular, and avoids the need for prototype patching. The following abbreviated example is how I would hope you could accomplish this without needing to interfere with any core MeasuredTemplate prototype methods.

```js
function onMeasuredTemplateRefresh(object, flags) {
  if ( !flags.refreshShape ) return;
  const origin = {x: object.document.x, y: object.document.y};
  object.shape = ClockwiseSweepPolygon.create(origin, {boundaryShapes: [object.shape]});
  object._refreshTemplate();
}

Hooks.on("refreshMeasuredTemplate", onMeasuredTemplateRefresh);
```

What are your thoughts?

**Comment by aaclayton** [comment]
I am receptive to your arguments, although I do still want to have some strong boundaries between what is internal functionality vs what is exposed to external developers to modify or subclass.

I have added the `MeasuredTemplate#_computeShape` method which is `@protected` which centralizes this logic and can be extended by subclasses who can either use the super-class behavior and then further modify the shape or can override the shape generation process entirely to take full control.

I hope this will be a good solution to your problem. Please let me know!

**Comment by caewok** [comment]
Thanks, I think this should work for my use case!
