### ISSUE TITLE
`_applyRenderFlags` must not be called in `render`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9104]
### What happened?

Transforms and bounds have already been computed when `render` is called. Children must not be added or removed. Position/size/rotation cannot be changed. Another issue: `Token.mesh` for example has already been rendered at the time `Token.render()` is called and the render flags are applied to the mesh.

The render flags need to be applied before rendering. Something like the following.
```js
// PlaceableObject

  applyRenderFlags() {

    // Apply render flags
    if ( this.renderFlags.size && !this._destroyed ) {

      // Full re-draw
      if ( this.renderFlags.handle("redraw") ) {
        const wasVisible = this.visible;
        this.visible = false;
        this.draw().then(() => this.visible = wasVisible);
      }

      // Incremental refresh
      else {
        const flags = this.renderFlags.getFlags();
        this._applyRenderFlags();
        Hooks.callAll(`refresh${this.document.documentName}`, this, flags);
      }
    }
  }
```
```js
// PlaceablesLayer

  /** @override */
  async _draw(options) {
    /* ... */
    canvas.app.ticker.add(this.#applyRenderFlags, this);

    // Wait for all objects to draw
    this.visible = true;
    await Promise.all(promises);
    this.objects.visible = true;
  }

  /** @override */
  async _tearDown(options) {
    canvas.app.ticker.remove(this.#applyRenderFlags, this);

    /* ... */
  }

  #applyRenderFlags() {
    for (const placeable of this.objects.children) {
      placeable.applyRenderFlags();
    }
    for (const placeable of this.preview.children) {
      placeable.applyRenderFlags();
    }
  }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 Development 1 (build 294)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Could you help me understand why it is too late to do this here? If I look at the `render(renderer)` method of the `DisplayObject` class this method delegates out to `_renderAdvanced()` or `_renderWithCulling()` or plain `_render()`.

Does applying render flags as the first operation of `render()` before calling `super.render()` not make synchronous changes before bounds are computed or before children are iterated over? 

I suppose perhaps the issue lies in `ObjectRendererSystem#render()` which updates transforms after emitting `"prerender"` but before calling `displayObject.render(renderer)`? Is that a correct understanding of the problem?

Adding every placeable object to the app ticker does not feel like a good solution. We need to work towards a solution which gives us the ability to enact object-level prerendering workflows before transforms are computed. Any thoughts? Perhaps we could discuss in a Discord thread?

FYI @Feu-Secret - this is likely what is responsible for the flicker we've been observing.

**Comment by dev7355608** [comment]
> Does applying render flags as the first operation of render() before calling super.render() not make synchronous changes before bounds are computed or before children are iterated over?

Transforms of the this object and all children have already been computed. The bounds of this object and all children may have already been computed by a parent of this object.

> I suppose perhaps the issue lies in ObjectRendererSystem#render() which updates transforms after emitting "prerender" but before calling displayObject.render(renderer)? Is that a correct understanding of the problem?

Yes. Before the render pass, the world transforms of all visible objects in the scene graph are computed. After that you must not change the visibility (`visible`) of any object (because the world transform of invisible object have not been updated), change anything about the transform (because the world transform matrix of the child wouldn't be updated at this point and the bounds would change), add children (the world transform would be invalid and the bounds of the object would change), remove children (the bounds would change).

> Adding every placeable object to the app ticker does not feel like a good solution. We need to work towards a solution which gives us the ability to enact object-level prerendering workflows before transforms are computed. Any thoughts? Perhaps we could discuss in a Discord thread?

What are you concerns about the ticker? You have to iterate each placeable each tick unless its layer is invisible. We can continue this discussion on Discord.

**Comment by Feu-Secret** [comment]
@dev7355608 @aaclayton 
I confirm that applying any changes during the `render` workflow might lead to unexpected results. This is verified while investigating on the *drawings* bug. My advice would be to link this workflow to the `PIXI.ticker` or to a `pre-render` phase.

**Comment by aaclayton** [comment]
Thanks for nudging us in the right direction here @dev7355608 - I believe we have a better solution to this design for our next release, V11 Dev 2.
