### ISSUE TITLE
Clearing chat log does not remove "jump to bottom" button

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9115]
From `@Drental#7146`
ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Windows 11, local instance, Chrome Version 111.0.5563.110 (Offizieller Build) (64-Bit)
Short Description of bug: Jump to bottom button stays when deleting all messages while scrolled up. Gets resolved once the chat log hits the bottom again.
Simple steps to reproduce the bug: roll a few things or post a bunch of lorem ipsum, scroll up, use the trash icon to delete all chat messages.
Screenshots and/or console errors:
![image](https://user-images.githubusercontent.com/26660743/228015197-e9027961-b268-438c-8e37-484c9fe1d135.png)

**Comment by cswendrowski** [comment]
Jump button clears on flush in my testing
