### ISSUE TITLE
Attempting to install with a valid manifest appears to trigger system validation errors

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9119]
From `@benstraub#3706`

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): MacOS
Short Description of bug: Trying to install Ironsworn system gives errors
Simple steps to reproduce the bug: Fresh install, clean data directory, try to install the Ironsworn system from the directory
Screenshots and/or console errors: These seem to suggest that the type fields in the packs are undefined, but they're not (https://github.com/ben/foundry-ironsworn/blob/main/system/system.json#L74) 

```
FoundryVTT | 2023-03-24 06:26:35 | [warn] System validation errors:
  packs:
    14:
      type: may not be undefined
    13:
      type: may not be undefined
[...]
```

**Comment by aaclayton** [comment]
I was able to install the system from <https://raw.githubusercontent.com/ben/foundry-ironsworn/main/system/system.json> without any issues or errors. Closing as nonrepro.
