### ISSUE TITLE
Chat bubbles do not appear as expected

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9120]
From `@dnapolitano#0948`

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Windows 11, Personal Laptop, Electron app, v11 293, dnd5e 1.1.4
Short Description of bug: chat bubble does not appear to generate (no console errors)
Simple steps to reproduce the bug: select token on canvas. Enter 'ello' into chat. Chat bubble does not generate though scene does pan to speaker.
Screenshots and/or console errors:
(searched is:issue is:open label:bug chat   within the github reported bug links above and did not locate a report of this).

![image](https://user-images.githubusercontent.com/26660743/228017372-7fc518ce-8e2a-4672-8121-48c696ffe79f.png)
![chat](https://user-images.githubusercontent.com/26660743/228017473-309dae2c-6185-48fa-ae85-461d5284d7c3.gif)

**Comment by mclemente** [comment]
Stumbled upon this bug.

The bubble's message actually appears when setting a breakpoint on the say() method, but it disappears when the Promise is fulfilled.
![image](https://user-images.githubusercontent.com/5288872/231907688-6eb00045-7a80-4c42-bf3f-8a1419b7293a.png)
