### ISSUE TITLE
Canvas fails with error when updating texture for a tile

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9122]
From `@agaringer#6498`

New RenderFlags implementation breaks Canvas on texture updates to Tiles
Reproducible in V11d1, works fine in V11p2
```
t = canvas.tiles.placeables[0];
t.document.update({ texture: { src: "icons/creatures/invertebrates/bug-sixlegged-gray.webp" } }); // the texture must not have been loaded yet
t.refresh();
```
See https://discord.com/channels/170995199584108546/1065764029278212230/1089583377033732188

Updating a Tile Image via the UI throws the same error.

Probably related to https://github.com/foundryvtt/foundryvtt/issues/9104

**Comment by aaclayton** [comment]
This issue is resolved now that #9104 is changed.
