### ISSUE TITLE
Route Prefix is ignored for asset paths

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9125]
From `@Mana#4176`

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Win11, Node, Firefox
Short Description of bug: Route prefix is ignored for assets
Simple steps to reproduce the bug: Use route prefix.
Screenshots and/or console errors:
Lots of XHR errors like:
GET http://myhost/icons/svg/mystery-man.svg

This repeats for all condition icons on world launch.
```
Error: Invalid Asset icons/svg/mystery-man.svg
    loadTexture .../routePrefix/scripts/foundry.js:27526
    _draw .../routePrefix/scripts/foundry.js:53116
    draw .../routePrefix/scripts/foundry.js:26459
    promises .../routePrefix/scripts/foundry.js:33005
    map .../routePrefix/scripts/commons.js:4052
    _draw .../routePrefix/scripts/foundry.js:33003
    _draw .../routePrefix/scripts/foundry.js:39794
    draw .../routePrefix/scripts/foundry.js:32509
    draw .../routePrefix/scripts/foundry.js:27603
    draw .../routePrefix/scripts/foundry.js:45362
    draw .../routePrefix/scripts/foundry.js:24948
    view .../routePrefix/scripts/foundry.js:22176
    initializeCanvas .../routePrefix/scripts/foundry.js:8708
    setupGame .../routePrefix/scripts/foundry.js:8541
    _initializeGameView .../routePrefix/scripts/foundry.js:9754
    _initializeView .../routePrefix/scripts/foundry.js:9730
    initialize .../routePrefix/scripts/foundry.js:8470
```
![image](https://user-images.githubusercontent.com/26660743/228019455-d474c05b-8057-4a1d-ac46-99d74812a439.png)

**Comment by mkahvi** [comment]
This issue is also quite dramatic with new worlds:  
![new-world](https://user-images.githubusercontent.com/8120158/228597577-1aa5ed1b-a77f-45e5-9abc-3a028fc636ee.png)

![nue-load](https://user-images.githubusercontent.com/8120158/228598188-ce01ef7d-0015-4c0c-ad66-868fb8b59482.png)
