### ISSUE TITLE
Canvas fails to initialize and throws error

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9126]
From `@Mana#4176`

ALL MODULES DISABLED? true
OS, Hosting, Browser (if applicable): Win11, Node, Firefox
Short Description of bug: Canvas initialization fails
Simple steps to reproduce the bug: Load a world
Screenshots and/or console errors:
```
Failed drawing interface canvas group: object is null foundry.js:64586:78
    fetch .../routePrefix/scripts/foundry.js:64586
    notify .../routePrefix/scripts/foundry.js:64513
    error .../routePrefix/scripts/foundry.js:64549
    onError .../routePrefix/scripts/foundry.js:754
    draw .../routePrefix/scripts/foundry.js:24950
    view .../routePrefix/scripts/foundry.js:22176
    initializeCanvas .../routePrefix/scripts/foundry.js:8708
    setupGame .../routePrefix/scripts/foundry.js:8541
    _initializeGameView .../routePrefix/scripts/foundry.js:9754
    _initializeView .../routePrefix/scripts/foundry.js:9730
    initialize .../routePrefix/scripts/foundry.js:8470
```

Any followup attempts to swap scenes produces the following:
```
TypeError: Failed drawing interface canvas group: this.border is undefined. this.border is undefined
    _destroy foundry.js:53095
    destroy foundry.js:26439
    destroy index.js:126
    _tearDown foundry.js:32545
    _tearDown foundry.js:32545
    _tearDown foundry.js:33039
    _tearDown foundry.js:39803
    tearDown foundry.js:32533
    draw foundry.js:32508
    draw foundry.js:27603
    draw foundry.js:45362
    draw foundry.js:24948
    view foundry.js:22176
    _onClickScene foundry.js:74942
```

This error also occurs when attempting to create new scene and enter view it. Creating and activating new scene and refreshing avoids it, until old scene is swapped to.

**Comment by mkahvi** [comment]
Here's export of one such failing scene. Importing this scene fails.

[fvtt-Scene-hex-grid-test.json.txt](https://github.com/foundryvtt/foundryvtt/files/11102730/fvtt-Scene-hex-grid-test.json.txt)

This scene was fine in v10 where it was created.

**Comment by Feu-Secret** [comment]
Hello @mkahvi. What is the system used for this scene? It is called "radiant". Is this system published? Is this system updated for v11?
We need additional informations to unblock this issue.

**Comment by mkahvi** [comment]
The system isn't published and it's been updated for v11, though nothing about its codebase relates to scene or canvas drawing currently.

I can import that scene to dnd5e and have the exact same issue, so it's not system related thing.

**Comment by mkahvi** [comment]
Yes, that looks correct. It's very simple scene that worked in v10 and broke in v11.
