### ISSUE TITLE
Add canvas.dimensions.distancePixels as a precomputed ratio between grid size and grid distance

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9128]
We often need to multiply data in distance units (like "30 feet") times the ratio of grid size over distance units (`canvas.dimensions.size / canvas.dimensions.distance`) to convert that metric into pixels. We can improve ergonomics by offering `canvas.dimensions.distancePixels` which can be multiplied directly.

**Comment by theripper93** [comment]
I suggested something along these line at some point ,for your consideration https://github.com/foundryvtt/foundryvtt/issues/8430

**Comment by aaclayton** [comment]
I think this adequately covers that use case because you can either multiply or divide by `canvas.dimensions.distancePixels` depending on which direction of conversion you need to achieve.
