### ISSUE TITLE
Add compatibility support for perception manager obsolete flag: `forceUpdateFog`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9137]
### What happened?

Preferably the perception manager would print a deprecation warning instead of throwing an error if `forceUpdateFog` is passed.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
canvas.perception.update({ refreshLighting: true, refreshVision: true, forceUpdateFog: true })
```

### What core version are you reporting this for?

Version 11 Development 1 (build 294)

### Relevant log output

```shell
foundry.js:30259 Uncaught Error: "forceUpdateFog" is not defined as a supported RenderFlag option.
    at #set (foundry.js:30259:23)
    at RenderFlags.set (foundry.js:30242:16)
    at PerceptionManager.update (foundry.js:47734:16)
    at <anonymous>:1:19
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
With our v11 FOW changes I believe we do not need a "force" option here anymore, but certainly if this flag existed previously we should continue to support it with a deprecation warning. I'll toss this over to @Feu-Secret

**Comment by Feu-Secret** [comment]
The `forceUpdateFog` flag is not needed anymore because the fog is now always fully rendered. Nevertheless, we should continue to support it with a deprecation warning.
