### ISSUE TITLE
os.version saved in diagnostics.json is useles on Linux

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9139]
### What happened?

The os.version string saved in diagnostics.json is probably useless, in my case it contains the build date of the kernel. I think reading the distro name and version from  /etc/os-release could provide you with more useful data. 
```
{
  "timestamp": 1679624136248,
  "os": {
    "platform": "linux",
    "version": "#1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023",
    "node": "18.15.0"
  },
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Install Foundry v11 on Fedora
2. Check diagnostics.json

### What core version are you reporting this for?

v11d1

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Implemented a helper method to attempt to read info from `/etc/os-release` with a fallback of `os.release()` used instead of `os.version()` which seems to be more informative in general.
