### ISSUE TITLE
Add option to disable minimum screen resolution error message

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9144]
### User Experience

I use a tiling window manager and it happens often that I resize for a short time web browser window running Foundry to half of my screen size. Each time when this happens  foundry shows this error:
![image](https://user-images.githubusercontent.com/3605541/229001163-89b40c59-5d5d-4956-916c-2020084046cd.png)

I've seen this message dozens of times and I would like to permanently disable it.

**Comment by aaclayton** [comment]
I think perhaps a good idea would be to trigger this message on a debounce so that it doesn't get generated for momentary screen resizing but only is displayed if the final resolution remains at a point that is below supported miniums.
