### ISSUE TITLE
Disappearing modules in Setup page

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9145]
### What happened?

After launching a game world and returning to the setup page, modules disappear. They appear again after restarting Foundry.  The modules are not compatible with v11 and are not active in any world, I only installed them.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Before:
![image](https://user-images.githubusercontent.com/3605541/229003912-2a8b7af0-8a32-4020-9120-7ef4f830b774.png)
After launching empty dnd5e world and returning to setup: 
![image](https://user-images.githubusercontent.com/3605541/229004366-38aa3868-abec-4a7d-abe7-cbb22b8064ac.png)

### What core version are you reporting this for?

v11d1

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
There are almost certainly some error messages associated with this behavior, either client-side console errors or server-side Node.js errors. It would be helpful for our ability to resolve this issue to have access to those error messages.

**Comment by grz0** [comment]
The only error that I get is this in the web browser console:
![image](https://user-images.githubusercontent.com/3605541/229372232-59441470-052d-499e-ae67-07df68dcd500.png)
But I don't know if it is related to this issue, it looks more like an error while launching dnd5e world.

I reproduced the issue by doing the following:
1. Install v10
2. Install Warhammer System
3. Install Warhammer Core, Altdorf, Starter Set, RNHD modules 
4. Upgrade to v11d1
5. Install dnd5e system and create empty world
6. start this world then go back to setup
