### ISSUE TITLE
'Possible EventEmitter memory leak detected' warning while launching a game world

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9146]
### What happened?

I noticed this warning when I was launching empty dnd5e world: 
```
(node:123683) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(landed) listeners added to [LevelDatabase]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Start empty dnd5e world.
I use node v18.15.0

### What core version are you reporting this for?

v11d1

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We're aware of this warning, it's coming from a dependency package we use rather than our own code. We will hope to resolve it but it may likely require an upstream package update to resolve.
