### ISSUE TITLE
Make game.settings.get() error on nonexisting setting tell what that setting was

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9148]
### User Experience

Currently the errors for `game.settings.get("imaginary", "setting")` print a generic nondescriptive error that it doesn't exist.
```
foundry.js:2799 Uncaught Error: undefined. This is not a registered game setting
```

It should instead additionally display the attempted scope and key in the log for clarity, for example:
```
"imaginary.setting" is not a registered game setting.
```

This probably doesn't matter that much for system and module authors, but much more useful for people writing macros since the errors lines and such are much less helpful to finding where the problem is, especially if you rely on the in-built macro editor.

**Comment by aaclayton** [comment]
Easy win, should prioritize.

**Comment by aaclayton** [comment]
I think this is done, need to double check.

**Comment by mkahvi** [comment]
I believe this was done via the duplicate issue #10834 unless I misundertstood something there.

**Comment by aaclayton** [comment]
Closing as already completed.
