### ISSUE TITLE
`ClockwiseSweepPolygon` should probably exclude collinear walls at all times

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9149]
### What happened?

Currently, `ClockwiseSweepPolygon.prototype._testWallInclusion` excludes walls collinear to the origin point, unless the config type is "move" or the wall is directional:
```js
 if ( (type !== "move") && !side ) return false;
```

But the current sweep algorithm does not handle collinear walls very well. Here are two examples after commenting out the above line in v10:

<img width="664" alt="Screenshot 2023-04-01 at 1 02 42 PM" src="https://user-images.githubusercontent.com/1267134/229313255-aa4b69ff-63e4-42b1-bce1-efe0b94dd15d.png">

<img width="664" alt="Screenshot 2023-04-01 at 1 02 04 PM" src="https://user-images.githubusercontent.com/1267134/229313257-28f2acf9-5ddf-4abd-9bc3-62408730764e.png">

My recommendation is to omit the above line, and always exclude walls collinear to the origin. While it might be possible to hack the sweep to accommodate collinear walls, that raises the question of what output would be desirable: Do you really want to return polygon that has a single-pixel line representing a collinear wall cutting through the polygon? That tends to lead to poor shading behavior and problems with Clipper. So long as walls in Foundry VTT are considered one-dimensional, it is better to ignore them when collinear to one. Alternatively, walls should have a predefined thickness—more than 1 pixel—but that would be a substantial change from current practice. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

If you run clockwise sweep for a scene with walls collinear to the origin point and set `config.type = "move"`, you are likely to see an erroneous polygon returned. 

Anyone who uses sweep with a move type may encounter this bug. Using the "move" type is common when you want to model something physical moving through a scene, such as a token or an arrow fired from a bow. It can be used to inform cover calculations, for example. 

### What core version are you reporting this for?

v10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think this requires some more thought. I am anxious particularly about movement tests that we should be sure to treat intersection with a collinear wall as a collision which would result in that movement being prevented. You should not be allowed to move onto (and along) a collinear wall and we should rely on existing tiebreaking logic which shifts the movement origin to eliminate such cases. My mind has been focused on other issues for a while so I may not be thinking about some considerations which are relevant here.

**Comment by dev7355608** [comment]
Duplicate #9071.

![image](https://user-images.githubusercontent.com/31905376/229369726-4ddce918-1d5a-4330-829b-693693f6a03d.png)

It is possible to move into collinear walls like this in V11. I didn't test V10. Not sure if this exception for `move`-type polygon still does what it's supposed to do.

I see the bug tag was removed: this should be considered a bug. There are modules that use `move`-type polygons. Besides Alterative Token Visibility another modules that uses `move`-type polygons is the Splatter, which uses these polygons as a mask to prevent blood from splattering through walls.

**Comment by caewok** [comment]
I slightly misstated what should happen; instead of omitting the line entirely, the line should change to always reject collinear walls:
```js
if ( !side ) return false;
```
Technically, collision testing should not count walls collinear to the origin for two reasons. 
1. Walls are 1 dimensional and so you cannot collide with a collinear wall. As @dev7355608 stated, you can currently move into collinear walls, and you (sometimes) could in v10. 
2. Collinear walls cannot form part of the sweep polygon, and so they are not part of the bounds that is supposed to be tested for collisions. But see my next statement...

There is some ambiguity about what collision testing is supposed to be doing in `ClockwiseSweepPolygon`. According to the description in `PointSourcePolygon,` collision testing is supposed to be checking whether a ray collides with an edge of the constructed polygon. That is not, however, what is actually being tested. Instead, the test is pulling all the walls considered by the sweep using `identifyEdges` and testing those for collisions, which is useful but a very different calculation. There appears to be quite a bit of techdebt here, which may be the reason for the confusion.

My view is, first, you don't really need collision testing methods for the sweep polygon to test if a ray collides with an edge of the constructed polygon. We have methods for that, including `contains`, that can be used on any polygon and there is really nothing special about the sweep polygon to warrant an additional method.

Second, there is something special about the `_testWallInclusion` method: It is very useful for all sorts of collision testing. I would make that method static and public. Maybe allow customization for collinear walls, although I remain unconvinced of the need in most cases. Then I would provide a utility method, not tied to `ClockwiseSweepPolygon,` to do collision testing for a provided ray and some relevant parameters, like wall restriction type, that calls the static version of `_testWallInclusion`.

**Comment by dev7355608** [comment]
`PointSourcePolygon.testCollision` also ignores collinear walls now at all times, but that doesn't change anything, because the ray-edge collision test in `ClockwiseSweepPolygon._testCollision` wasn't (and isn't) able to detect collisions with collinear walls.

@caewok `_testWallInclusion` is now a protected method of `PointSourcePolygon` (but not static).
