### ISSUE TITLE
Keep Decline and Accept buttons in the same order in License and Usage statistics prompt

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9152]
### What happened?

The usage statistics prompt is shown just after accepting the license, and I almost clicked the Decline button by mistake because it has different button order than the previous prompt.

![image](https://user-images.githubusercontent.com/3605541/229371996-2737ba81-80aa-43b1-9969-6fabd7f018ba.png)
![image](https://user-images.githubusercontent.com/3605541/229372011-e031eba0-3030-46ec-a284-6797b541a92b.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Install v11d1

### What core version are you reporting this for?

v11d1

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Our standard UX across the app is when we present a yes/no dialog we show yes on the left and no on the right, so I'll change the order of the EULA to conform to that.
