### ISSUE TITLE
`actor` variable in script macros always refers to base, world actor rather than the selected token's synthetic actor

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9158]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1084545676307878049

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** any  
**Short Description of bug:** `actor` in script macros points to source actor even when a token is selected (instead of the synthetic actor as one would expect)  
**Simple steps to reproduce the bug:**  
1) Make following script macro:
```js
ui.notifications.info(actor.uuid);
```

2) Use this macro for bunch of unlinked tokens from same actor.

I at least would expect this to refer to the actor of the selected token, so if you happen to update or pull data from the actor, it to be relevant to the token. But it's obviously not.

This is also against the documentation of what actor is supposed to refer to.

**Comment by Fyorl** [comment]
I can definitely understand the expectation that `actor` would be the token actor if a token is selected when executing the macro, but changing this behaviour now has the potential to break a lot of pre-existing macros that might have been depending on it. I feel that most macros that expect to be interacting with a token can just use `token.actor` if they want to be sure.

**Comment by krbz999** [comment]
I have to say I don't think I've ever seen anyone write a hotbar macro that specifically uses the current logic to apply to the "prototype" actor despite selections. In fact most aren't aware of it, this might just fix more than it breaks.

**Comment by aaclayton** [comment]
I think I'm inclined to agree that - with our improvements to token actors - it would probably be best if `actor` in macro scope refers to the unlinked token actor rather than the base.
