### ISSUE TITLE
`SpriteMesh#calculateTrimmedVertices` references non-existent `args` variable

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9162]
Originally reported by Aedif#7268 https://discord.com/channels/170995199584108546/956306859491471420/1086799990212534332

**ALL MODULES DISABLED?** false  
**OS, Hosting, Browser (if applicable):**  
**Short Description of bug:** SpriteMesh's `calculateTrimmedVertices` method calls proto method referencing args that don't exist  
**Simple steps to reproduce the bug:**  
**Screenshots and/or console errors:**

```js
  /** @override */
  calculateTrimmedVertices() {
    return PIXI.Sprite.prototype.calculateTrimmedVertices.call(this, ...args);
  }
```

**Comment by Feu-Secret** [comment]
Already fixed in version 11.294 (was detected during dev1 development)
