### ISSUE TITLE
Correct an issue that can occur when passing a Document as the target to a ForeignDocumentField as expected. This corrects a bug, for example, when updating User#character with an Actor instance.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9166]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1090268831722766377

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Any  
**Short Description of bug:** Updating user.character with invalid value claims the value must be a BaseActor instance  
**Simple steps to reproduce the bug:**
```js
game.user.update({character: 5})
```

Will error with:
```
foundry.js:59188 The value provided to a ForeignDocumentField must be a BaseActor instance.
foundry.js:747 Error: undefined. The value provided to a ForeignDocumentField must be a BaseActor instance.
```

This is however false(?), as it's asking for actor ID, not for actor document.
```js
game.user.update({character: "blort"})
```

Will instead say:
```
foundry.js:747 Error: undefined. User [HWD3pBdjsmSFiaFZ] Model Validation Errors
[User.character]: must be a valid 16-character alphanumeric ID
```

And if you give it valid actor ID, it finally works.

Attempting to actually give it an actor like the initial error suggested will make it go completely insane.

**Comment by aaclayton** [comment]
Resolved indirectly by https://github.com/foundryvtt/foundryvtt/issues/9178
