### ISSUE TITLE
Creating a token for a player pans the player's view to (0,0)

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9169]
Originally reported by Skimble#8601 https://discord.com/channels/170995199584108546/1065764070680186930/1092143074911715348

**ALL MODULES DISABLED?** (true)  
**OS, Hosting, Browser (if applicable):** Windows self hosted  
**Short Description of bug:** When using creatembeddeddocuments on a scene to create a new token with this code:  
```js
let token = {
        name: itemActor.name,
        x:x,
        y:y,
        texture:{src:itemActor.img},
        width: 1,
        height: 1,
        vision: false,
        hidden: false,
        actorId: itemActor.id,
        actorLink: true,
        actorData: {}
      }

    let scene = game.scenes.get(canvas_scene._id);
    await scene.createEmbeddedDocuments("Token", [token]); //createEmbeddedDocuments takes an array of creation data.
```

The token initially appears at 0,0 before being moved to the correct location. As the players all own the token in this case, it forces their view to pan to (0,0) regardless of the token's actual coordinates. X and Y are not set to 0,0 when the token is created, so this appears to be a bug.

**Simple steps to reproduce the bug:** See code above  
**Screenshots and/or console errors:** No errorrs, but if zoomed to 0,0 on player's screen, I can see the token briefly appearing there before vanishing.

**Comment by aaclayton** [comment]
This issue manifested in a different format in V11 given our changes to canvas render flags, but it did surface an issue that has been fixed regarding PlaceableObject _onCreate workflows.
