### ISSUE TITLE
Consider changing the default value for Toggle Notes Display to true

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#9173]
### User Experience

When new users are created in most systems, the toggle notes display is set to false. Map Links are already hidden if a player doesn't have permission for a journal, so this only serves to hide map links for journal pages the player has access to view anyway. The GM is unable to enforce a default either, so if map links are intended to be used by players (such as for hexploration or city maps) they'll have to communicate to each player to turn their map notes toggle on with no way of verifying.

The PF2e system runs this bit of code during setup (which is why I never found out this was the case until recently), but I think this is a more reasonable default in general:
```ts
game.settings.settings.get("core.notesDisplayToggle").default = true;
```

If I'd go one step further, my bias is that the toggle notes display shouldn't even exist. Even in PF2e (which defaults to true), a player tinkering around turned it off many sessions ago and wasn't seeing any of my map links, and I didn't know until much later. But I'd settle for it defaulting to on.

**Comment by krbz999** [comment]
Several systems have adopted this standard beyond pf2e. It would be great to see it as the actual core standard.
