### ISSUE TITLE
chatMessage Hook is not included in hookEvents

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#9177]
### Where did you find it, or where does it belong for requests?

V10 API Documentation (https://foundryvtt.com/api/v10/)

### What page or file needs a look at?

https://foundryvtt.com/api/modules/hookEvents.html

### What core version are you reporting this for?

Version 10/11

### What is wrong, in your opinion?

Reported by Mana in #docs-feedback: https://discord.com/channels/170995199584108546/1088790838403924048/1088790838403924048

Ref: https://foundryvtt.com/api/modules/hookEvents.html

`chatMessage` hook has documentation in the code, but it's not present in the online documentation.

**Comment by aaclayton** [comment]
Related to #9313
