### ISSUE TITLE
After broken token image link, cannot update

### ISSUE THREAD

**Issue by ihdavids** [foundryvtt/foundryvtt#9179]
### What happened?

I was trying to organize my token images somewhat. I moved a few of them that were already setup as actors in my world.
Of course I got the usual broken link indicator. However, once I tried to update the token links things LOOKED like they were working. (IE the npc character sheet and actor icon in the actor tab were updated) but when I dragged that actor out onto the canvas I get the mystery man icon, without fail.

This is on a brand new install of foundry as of less than 10 days ago on the latest version.
If I delete the actor and create a new actor and set its icon apropriately then things work but for some reason the actor that had the broken link seems to be doomed to always become the mystery man when imported onto the canvas.
I have tested this again on other actors and it happens without fail.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

To Reproduce:

1. Add some images to a folder somewhere in your game.
2. Create an actor and set it's token image.
3. Close foundry and then MOVE the token image in your foundry folder
4. Restart foundry and notice the broken link in the actors tab.
5. Fix the actors icon to point to the new location.
6. Now drag the actor on the canvas, notice he is mystery man.
7. Restart foundry just to be sure. Notice the actor once dragged on the canvas is still mystery man.

### What core version are you reporting this for?

10 Build 291

### Relevant log output

```shell
None that I could see.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
(In the future, best to hash out general troubleshooting like this over on the Discord.) 

According to your steps there, you didn’t update the actor’s token image path to point to the new location. Setting the Character Art for an actor only simultaneously updates the Token Art *once*, when the token art hasn’t already been set. 

Also, any time you’re making behind-the-scenes file moves/renames, be sure to do a Control-F5 in-game to clear your cache.
