### ISSUE TITLE
Use a single `PIXI.Graphics` object for square grid, on the same model as hex grid.

### ISSUE THREAD

**Issue by asuffield** [foundryvtt/foundryvtt#9180]
### What happened?

I was rummaging in chrome performance tools to debug a different issue, and stumbled over this suspicious looking stack trace:

![image](https://user-images.githubusercontent.com/1300408/230772908-7cccc992-ad76-40a2-b8b9-1b7d1be83aa0.png)

This is taken from a 10 second performance profile, and we spent about half a second repeatedly running through this call stack.  It's all some pixi rendering chain, and it's expected for this to be here, but it appears substantially too expensive for what it's doing - I just have a simple map up with a few tokens on it, nothing is happening, and profiling other pixi renderings with comparable numbers of things on screen is about ten times faster. I'd be expecting this to complete in 50ms, not 500ms.

I can't be sure this is broken, but it looks suspicious, and some deeper spelunking might find a needlessly inefficient thing.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Any profile of an otherwise idle app appears to be dominated by this call chain, should be easy to spot.

### What core version are you reporting this for?

10 build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
That's the grid. I've seen this in performance profiles of empty scenes before, but now I realized why: each line of the square grid is an individual `PIXI.Graphics`. If the lines are drawn into a single `PIXI.Graphics`, the performance improves significantly.

**Comment by aaclayton** [comment]
This may be something we can revisit. Several years ago the state of PIXI.js was such that the maintainers advised using different Graphics instances for each line instead of adding a large number of vertices to the geometry of a single Graphics object because some aspect of batching made that preferable and there was a maximum limit on the complexity of the geometry that could become particularly binding in the case of hexagonal grids which require many lines. 

I suspect that several things have changed - not to mention the switch to using the SmoothGraphics framework which may have different constraints. 

@dev7355608 is there anything we should be aware of regarding the maximum number of vertices/lines that we would add to a SmoothGraphics geometry?

**Comment by asuffield** [comment]
How about using PIXI.TilingSprite?

**Comment by dev7355608** [comment]
> This may be something we can revisit. Several years ago the state of PIXI.js was such that the maintainers advised using different Graphics instances for each line instead of adding a large number of vertices to the geometry of a single Graphics object because some aspect of batching made that preferable and there was a maximum limit on the complexity of the geometry that could become particularly binding in the case of hexagonal grids which require many lines.
> 
> I suspect that several things have changed - not to mention the switch to using the SmoothGraphics framework which may have different constraints.
> 
> @dev7355608 is there anything we should be aware of regarding the maximum number of vertices/lines that we would add to a SmoothGraphics geometry?

SmoothGraphics doesn't have a batch renderer. So in most cases it should be worse to split something into multiple Graphics elements. Exceptions are probably when only some of the elements constantly change, which would unnecessarily force the entire geometry of all elements to be rebuilt. So in the case of the grid that is completely static and all lines have the same line style it is especially bad to split it into multiple Graphics.

Now that WebGL 1 support has been dropped we are no longer constrained by 16-bit index buffers. You'd likely run out of memory before you run exceed the 32-bit indices.
