### ISSUE TITLE
Issue with HTML datalist in Foundry native application

### ISSUE THREAD

**Issue by CelestianGC** [foundryvtt/foundryvtt#9187]
### What happened?

When the console is open in the Foundry native application, the datalist appears in the console section of the window instead of its intended location. The scroll bar is not present (whether console is open or not), making it difficult to navigate through the options.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open Foundry native application.
Use a html datalist.
Open the console.
Observe that the datalist appears in the console section of the window and does not have a scroll bar.
Expected behavior:
The datalist should appear as expected, with a scroll bar present, even when the console is open.

Here is a screenshot of the Foundry Native application view of the issue:
![01_C78cPPBALf](https://user-images.githubusercontent.com/3953802/231487176-2c5d56ff-13ed-4328-ab38-a88ac3f09933.jpg)

Here is the same view from Chrome web browser:
![02_nrn5IFdr4X](https://user-images.githubusercontent.com/3953802/231487351-774d0c19-cfaa-4948-beef-19c20e30ca28.jpg)

### What core version are you reporting this for?

Version 10 - Build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
The core software ActiveEffectConfig application does not use or provide a datalist here, only a plain text input field. Any datalist that you have available is provided by a module or game system rather than by the core software.

In general, when reporting bugs to this repo please be sure you are only ever doing so in an environment with all modules disabled and that you have attempted to verify that it's not a module or system-related issue first.

**Comment by CelestianGC** [comment]
My bug report was for a problem with the Foundry native application, not a ruleset or module. Using datalist anywhere in Foundry using html templates seem to cause this problem as best I could tell.

**Comment by CelestianGC** [comment]
> My bug report was for a problem with the Foundry native application, not a ruleset or module. Using datalist anywhere in Foundry using html templates seem to cause this problem as best I could tell.

My bug report was for a problem with the Foundry native application, not a ruleset or module. Using datalist anywhere in Foundry using html templates seem to cause this problem as best I could tell.

**Comment by aaclayton** [comment]
I see. In this case it's an electron rendering bug and not anything to do with Foundry VTT itself because datalist elements do render properly in chromium. We wouldn't be able to do anything about this either way.

**Comment by CelestianGC** [comment]
> I see. In this case it's an electron rendering bug and not anything to do with Foundry VTT itself because datalist elements do render properly in chromium. We wouldn't be able to do anything about this either way.

Understood, thanks for the clarification!
