### ISSUE TITLE
Toggling top-level sort mode in the compendium tab does not update the icon

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#9197]
AKA Clicking the Toggle Sort button in the Compendium Packs tab doesn't change its icon
AKA It isn't clear how the sorting works.

### Toggle Icon
The Toggle Sort icon is stuck at A-Z icon and and doesn't change into the other icon that shows when toggling the sorting option on the other sidebars.

#### Reproduction Steps
![Animação8](https://user-images.githubusercontent.com/5288872/232149156-3f341dc7-b8b4-416b-9401-6b7efb7ebad8.gif)

### Sorting
~~Also, I'm not sure if the sorting is working as intended, as it only sorts folders at the top level, while Compendiums outside the folders are completely unaffected.
This isn't the behavior for other sidebars, where content outside folders still gets sorted.~~
(moved to #9219)

### Deleting
~~Trying to Remove Folder or Deleta All throws an error. This doesn't happen on the other sidebars.~~
(tracked in #9215)

### Search
~~When searching for a compendium pack, it searches for the `compendium.name` data (which is an id) instead of the `compendium.label` data. So something like the Starter Heroes compendium doesn't show up when searching for "start" and only shows up when searching for "heroes".~~
(moved to #9220)

### What core version are you reporting this for?

11.295

**Comment by cswendrowski** [comment]
We ran out of time to add manual sorting for compendium packs in Dev 2, we probably should have disabled this button for that release. Closing in favor of #9219
