### ISSUE TITLE
Allow passing arguments to script macros through chat messages

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#9201]
# Implemented Feature

Implemented a way to pass parameters to a macro command via a chat slash command of the form:
```
/macro {macroName} [param1=value1] [param2=value2] ...
```
For example
```
/macro My Macro greeting=Hello
```

# Original Request

While the latest development build added arguments to macros, it still isn't possible to pass arguments in any way through chat.

It's possible to add this feature by changing the `ChatLog._processMacroCommand` method.
Here's an example of how to do it:

```diff
_processMacroCommand(command, match) {
    let macro;
    const macroName = match[2];
    if ( Number.isNumeric(macroName) ) {
      const macroID = game.user.hotbar[macroName];
      macro = game.macros.get(macroID);
    }
-    if ( !macro ) macro = game.macros.getName(macroName);
-    macro?.execute();
+    if (!macro) {
+        const macroArray = match[2].split(" ");
+        let macroName = "";
+        for (const namePart of macroArray) {
+            macroName += namePart;
+            macro = game.macros.getName(macroName);
+            if (macro) {
+                args = macroArray.slice(macroArray.indexOf(namePart) + 1);
+                break;
+            } else macroName += " ";
+        }
+   }
+    macro?.execute({...args]);
  }
```

This has the caveat that it is not possible to pass arguments with names that would collide with another macro's name, e.g. a `move` macro and a `move token` macro where you call call `/macro move token` with token as an argument.

**Comment by aaclayton** [comment]
Can you back up a step and talk me through why we need pass programmatic arguments into execution of chat macros which inherently cannot do anything with those variables? What is the motivation for this feature request?

**Comment by mclemente** [comment]
You got things mixed up, the suggestion is for script macros that are called through the chat (e.g. `/macro openDialog`), as the title states, not for chat macros.

With this change, script macros can get arguments when invoking them from the chat.

Simplest example possible
```js
// macro name: rollSkill
// type: script
let { 0: skillId, 1: advDis, 2: parts } = args;
if (!skillId) return;
if (Number.isNumeric(advDis) && !parts) parts = advDis;
const advantage = advDis === "adv"
const disadvantage = advDis === "dis"

await actor.rollSkill(skillId, {
  event,
  parts,
  advantage,
  disadvantage,
  fastForward: true,
});
```

Then you type `/macro rollSkill per -5` and it'll roll Perception with a -5 modifier, you won't need to know the character's ability as you'd do with `/roll 1d20 + [perception mod] - 5`. If you want to roll with advantage/disadvantage, just type adv/dis before the modifiers. It has its uses.

Also, I know typing "/macro" would make calling some macros way too long, but calling macros by just their name (e.g. `/rollSkill per -5`) is a feature the Advanced Macros module will still have since it is used by some users and I know that has its own issues, so it wouldn't be acceptable on Core.

**Comment by aaclayton** [comment]
Hmm... The implementation of passing args to script macros uses an arguments object of key/value pairs. It sounds like your suggestion assumes that arguments are passed as unnamed positional arguments which I don't think is desirable. We would need to implement some additional parsing for the `/macro` command to be able to interpret and identify keyword named arguments.

Maybe something like `/macro {macroName} key1=value1 key2=value2 ...`

**Comment by Fyorl** [comment]
Maybe we could pass the entire string into the macro under a well-known parameter like `chatArgs`, and the macro can do its own parsing? It would allow for a macro to accept some bespoke format that is the most ergonomic for users to input (whether that's positional arguments or something else).

**Comment by mclemente** [comment]
>The implementation of passing args to script macros uses an arguments object of key/value pairs. It sounds like your suggestion assumes that arguments are passed as unnamed positional arguments which I don't think is desirable. 

My suggestion was built upon how arguments were read by my module, since there was no simple way to declare names like an object and the way it executed macros was exactly like that. 
I see how that would limit macros called through chat to need an entirely different logic to handle chat arguments. Even the macro example I gave had that issue when defining what was adv/dis and what was a bonus. This design wouldn't be desirable in the long run.

I went for a "less typing" design because there's a moment where it's easier to just make a lot of macros instead of typing each key/value pair.
My aim was at simple `/macro {macroName} bonus` macros, such as a `/macro spendResource X` to avoid the need of having similar macros for each different value (e.g. X=5/10/15/etc).
But maybe a change to key/pair in a way that a `/macro spend resource=X` macro would cut down on a lot of macros that it could be interesting for most users.

---

So, what about this one instead?

```js
_processMacroCommand(command, match) {
	let macro;
	const matchArray = match[2].split(" ");
	let macroName = matchArray[0];
	if (Number.isNumeric(macroName)) {
		const macroID = game.user.hotbar[macroName];
		macro = game.macros.get(macroID);
	} else macro = game.macros.getName(macroName);
	const args = {};
	if (matchArray.length > 1) {
		const keyValueRegex = /(\w+)\s*=\s*(\w+)/; // key = value
		matchArray.splice(1).forEach((token) => {
			if (macroName && !macro) macroName += ` ${token}`;
			if (!macroName) macroName = token;
			if (!macro) macro = game.macros.getName(macroName);
			else {
				const match = token.match(keyValueRegex);
				if (match) {
					const { 1: key, 2: value } = match;
					args[key] = value;
				}
			}
		});
	}
	macro?.execute(args);
}
```

Example macro:
```js
//macro name: "spend" or "do something" to test spaces
const {name, hp, mana, resource} = args;
console.log(name, hp, mana, resource);
```

Example: `/macro spend resource=5`, `/macro do something resource=5`, `/macro {hotbar number} resource=5` and any variations.

**Comment by aaclayton** [comment]
Note to self: review comment in <https://github.com/foundryvtt/foundryvtt/issues/7184#issuecomment-1532964833> for possible API change to the way that additional parameters are destructured.

**Comment by mclemente** [comment]
Hey, thanks for implementing this, but is there any chance you can change it to allow single values as Boolean?

## Example
```js
// macro name: rollSkill
// type: script
if (!id) return;
await actor.rollSkill(id, {
  event,
  parts: typeof bonus !== "undefined" ? bonus : "",
  advantage: typeof adv !== "undefined",
  disadvantage: typeof dis !== "undefined",
  fastForward: true,
});
```

Then calling: `/macro roll id=per adv` would roll Perception with advantage without the need to type `adv=true`.

## Code
```js
_processMacroCommand(command, match) {

    // Parse the macro command with the form /macro {macroName} [param1=val1] [param2=val2] ...
    let [macroName, ...params] = match[2].split(" ");
    let expandName = true;
    const scope = {};

    // Get the target macro by number or by name
    let macro;
    if (Number.isNumeric(macroName)) {
        const macroID = game.user.hotbar[macroName];
        macro = game.macros.get(macroID);
    }
    if (!macro) macro = game.macros.getName(macroName);

    for ( const p of params ) {
      const kv = p.split("=");
      if ( kv.length === 2 ) {
        scope[kv[0]] = kv[1];
        expandName = false;
      }
      else if (macro) {
        scope[kv[0]] = true;
        expandName = false;
      }
      else if (expandName) {
        macroName += ` ${p}`; // Macro names may contain spaces
        macro = game.macros.getName(macroName);
      }
    }
    if (!macro) {
     macroName = macroName.trimEnd(); // Eliminate trailing spaces
     macro = game.macros.getName(macroName);
    }

    if ( !macro ) throw new Error(`Requested Macro "${macroName}" was not found as a named macro or hotbar position`);

    // Execute the Macro with provided scope
    return macro.execute(scope);
  }
```

---

I'm fine with this not being implemented if you see any issues with it and won't push this issue any further, I'm already happy with all the new things added.
