### ISSUE TITLE
Polygon drawings with text can be resized below the dimensions of the text via the drag handle

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9203]
### What happened?

This is a bug according to #8488. But polygon drawings cannot be resized via the config (#8639). So this bug must not be fixed before #8639 is.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 (build 295)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
We're going to change this behavior for drawings. The shape will not be constrained anymore by the text.
