### ISSUE TITLE
Foundry cannot find SSL certificates in Oracle Cloud Machine

### ISSUE THREAD

**Issue by gianini777** [foundryvtt/foundryvtt#9209]
### What happened?

Hello

I had an oracle server hosting the Foundry VTT , but I lost the SSH key to connect. Because of that, I loaded a new machine with the Boot of the old one so as not to lose my settings and modules that I used.

In this new machine, when trying to configure video and audio in the foundry, the following message appears: "You cannot use Audio/Video calls unless you Fouyndry VTT server is using SSL certificates. See the online documentation for instructions.".

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1. Open the world;
2. Open Configure Settings;
3. Open the Audio/Video Configuration;
4. Then, the following message appears: "You cannot use Audio/Video calls unless you Fouyndry VTT server is using SSL certificates. See the online documentation for instructions."

![image](https://user-images.githubusercontent.com/70986158/232329830-cdc8daf1-c0ce-4989-960e-c25dd3c0721f.png)

### What core version are you reporting this for?

Version 10 (Building 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
Please visit the #install-and-connection channel on the Foundry discord for help troubleshooting your SSL setup.

**Comment by aaclayton** [comment]
As @unsoluble mentions, this github backlog isn't the right place for this type of support issue. If discord isn't a good solution for you please send us a support email to support@foundryvtt.com.
