### ISSUE TITLE
Use passive DOM event listeners more

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9210]
### User Experience

Even just looking through foundry.js code for `addEventListener()` calls, there's quite a few that don't call `event.preventDefault()` (nor `.stopPropagation()`) nor do they have ever reason to, so setting `{ passive: true }` on those listeners would likely improve responsiviness even if these are not frequently called handlers.

This is a simple change and should not have possibility of breaking anything.

Passive defaults to false for most events except few specific ones, so setting this explicitly _is_ necessary.

Jquery is incapable of creating passive listeners, so converting some of those to regular DOM event listeners could see improvements.

Personally I'd recommend _especially_ passing it to any event listeners dealing with mouse movement (mouseover, mouseout, mousemove, etc.).

For people with decent hardware and browser that runs _only_ Foundry this probably will be unnoticeable change, but for anyone that doesn't cover this can be very noticeable improvement. Electron client especially suffers from non-passive listeners from my experience of developing game systems and modules, most noticeable with reactive elements (e.g. tooltips).

**Comment by aaclayton** [comment]
This is something we can do as a general guiding principle moving forward with Application V2, but since this issue is more of a "invest more into best practices" I'm going to close it. The suggestion is well taken and we will work to incorporate this more into our new and redesigned apps moving forward.
