### ISSUE TITLE
Manifest validation fails for worlds with empty lines in their descriptions

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9222]
Originally reported by The Comamba#7519 https://discord.com/channels/170995199584108546/1065764070680186930/1097191261556973620

**ALL MODULES DISABLED?** true (Worlds view)  
**OS, Hosting, Browser (if applicable):** Parrot OS (a Debian derivative), foundry executable  
**Short Description of bug:** Metadata validation fails for some worlds whose description contains an empty line.  
**Simple steps to reproduce the bug:** Create world called "Buggy World" and replace world.json with
```json
{
  "title": "Buggy World",
  "description": "<p> </p>",
  "version": "1.0.0",
  "system": "dnd5e",
  "coreVersion": "10.286",
  "nextSession": "1970-01-01T00:00:00.000Z",
  "resetKeys": false,
  "safeMode": false,
  "systemVersion": "2.0.3",
  "id": "buggy-world",
  "compatibility": {
    "minimum": "10",
    "verified": "10.286"
  }
}
```
**Screenshots and/or console errors:**  
Console:
```
setup.js:2935: [buggyworld] Metadata validation failed for world "buggyworld": Cannot read properties of undefined (reading '0')
```

setup.js:
```js
for ( const pkg of Object.values(packageWarnings) ) {
        for ( const error of pkg.error ) {
          counts.error++;
          console.error(`[${pkg.id}] ${error}`); //This line throws the error.
        }
        for ( const warning of pkg.warning ) {
          counts.warning++;
          console.warn(`[${pkg.id}] ${warning}`);
        }
      }
```

**Comment by Fyorl** [comment]
Not able to reproduce this in the latest v11.

**Comment by silvative** [comment]
Not able to reproduce in v11t3
