### ISSUE TITLE
Add the Roll#resetFormula method as a public API for re-compiling the _formula attribute of the Roll class.

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9228]
### User Experience

I have run into situations in which I want to modify an existing instantiation of the `Roll` class. Usually some sort of modification to one or more terms of the roll. Currently, as of v10, there is no way to reset `_formula` in an approved manner. (Obviously, I can reset `_formula` by passing it a new value directly, but that involves an assumption on my part as to what the correct value should be.) 

This also happens in the `Roll.prototype.alter` method, where the method just modifies `_formula` manually:
```js
// Update the altered formula and return the altered Roll
this._formula = this.constructor.getFormula(this.terms);
```

The current approach is particularly problematic because there is a getter for formula that does not depend on the `_formula` property. An oversight?

I recommend providing an API to reset the roll formula based on the underlying terms. Either provide a setter for `formula` or a "clear" method to wipe the previous formula, so it can be recalculated later from the terms. 

Thanks!

**Comment by aaclayton** [comment]
Am I misunderstanding, or would an "API to reset the roll formula" be simply a wrapper around
```js
this._formula = this.constructor.getFormula(this.terms);
```
That's still a reasonable request, I just wanted to make sure this isn't bigger than I'm realizing.

**Comment by caewok** [comment]
Yes, it could be that simple. So long as you don’t want someone setting `_formula` directly. Given that it is supposed to be calculated from the terms, seems like your proposal is a good approach.
