### ISSUE TITLE
Improvement to the `localize` Handlebar helper to work with `concat`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9240]
### User Experience

I would like to use localize with concat in an html template. A simple example would be:
```html
<p> {{localize (concat "DND5E." "Advantage")}}</p>
```
The use case here is to replace "Advantage" with a variable. For example, you might use an `#each` iterator to cycle through a set of variables, localizing each term.  

This is not currently possible, because `localize` throws "typeError: key.split is not a function or its return value is not iterable." Ultimately, the issue is that `localize` expects a string but `concat` wraps the string in an object.

The current workaround is to wrap the `concat` in a `lookup` to coerce it to a string:
```html
{{localize (lookup (concat "DND5E." "Advantage") 'string')}}
```

A better solution might be to improve the `localize` helper to accommodate this use case. For example, a simple fix might be to cast `value` to a string:
```js
static localize(value, options) {
    const data = options.hash;
    return foundry.utils.isEmpty(data) ? game.i18n.localize((string) value) : game.i18n.format((string) value, data);
  }
```

All credit to Patrick in Discord for identifying the workaround and potential solution. See this [Discord discussion](https://ptb.discord.com/channels/170995199584108546/811676497965613117/1098251956713177138).

**Comment by mkahvi** [comment]
Solution should be simple case of:
````js
static localize(value, options) {
  if (value instanceof Handlebars.SafeString) value = value.string;
  // continue as normal
```

**Comment by aaclayton** [comment]
Adding this to v11 testing 2 since it's a 1-liner improvement.
