### ISSUE TITLE
`HandlebarsHelpers.selectOption` does not work with an array

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9244]
### Where did you find it, or where does it belong for requests?

V10 API Documentation (https://foundryvtt.com/api/v10/)

### What page or file needs a look at?

https://foundryvtt.com/api/classes/client.HandlebarsHelpers.html#selectOptions

### What core version are you reporting this for?

Version 10.291

### What is wrong, in your opinion?

Documentation suggests you can pass an array as choices to the Handlebars `selectOptions` helper:

```js
let choices = [{a: "Choice A"}, {b: "Choice B"}];
```

In testing and per [this Discord discussion](https://ptb.discord.com/channels/732325252788387980/754127569246355477/1022248351963545671), passing an array of choices results in a blank (undefined) list of selections in the dropdown. Passing an object appears to work fine.

**Comment by aaclayton** [comment]
There are a number of supported formats for the input to `selectOptions`. What you are looking for in this case would be an input structure that looks like either:

## Option 1
```js
let choices = {
  a: "Choice A",
  b: "Choice B"
}
```
with an invocation of:
```
{{selectOptions choices}}
```
OR

## Option 2
```js
let choices = [
  {id: "a", label: "Choice A"},
  {id: "b", label: "Choice B"}
]
```
For the second format your invocataion needs to look like:
```
{{selectOptions choices nameAttr="id" labelAttr="label"}}
```

**Comment by caewok** [comment]
Yes, having seen your suggested fix, I agree this is a documentation problem with how `selectOption` handles array objects.
