### ISSUE TITLE
There seems to be a limit of 19 items in a compendium folder v11 dev2

### ISSUE THREAD

**Issue by tposney** [foundryvtt/foundryvtt#9249]
### What happened?

I was reorganising a compendium and moving items into folders in the compendium. When I reached 19  items in a folder I could no longer move any more items to the folder.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

create a compendium and a folder in the compendium, then move items into the folder after 19 items are added to the folder subsequent drag/drops do nothing

### What core version are you reporting this for?

v11 dev 2

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by cswendrowski** [comment]
> I don't believe our code imposes any such limit. Tagging @cswendrowski on this to sync up with you to investigate though.

I was able to add more than 19:
![image](https://user-images.githubusercontent.com/15639841/233433577-537336f8-f16c-4d47-9fa3-56dbaca800cb.png)
![image](https://user-images.githubusercontent.com/15639841/233433718-46dc65c8-21be-49a5-92b1-96e478151797.png)
