### ISSUE TITLE
Improve the user experience of Module creation and editing with auto-slugification of package ID and compendium pack name fields.

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#9257]
### User Experience

[v11]

When using the new Create Module feature, neither the `Package Identifier` field nor the `Name` field for packs are slugified up front. The `Package Identifier` is slugified behind the scenes on submission at least, but the `Name`s are not:

<img width="270" alt="CleanShot 2023-04-20 at 18 37 08@2x" src="https://user-images.githubusercontent.com/801582/233520237-d8d2e8a9-2713-4e5e-92b4-eea638822d0a.png">

Suggest using the same mechanism you're already using in the World creation dialog, to provide an auto-slugified version of whatever's typed in the human-readable Title/Label field (which can then be overwritten if the user desires).

To facilitate this, I think the `Package Title` field should come first above `Package Identifier`, and similarly the pack `Label` should come above the `Name`. (Aside: Hint text for what `Label` versus `Name` mean would help non-devs here.)

**Comment by aaclayton** [comment]
I have already added slugify behavior for pack names, but agree we should do this in real-time as the user is typing. Will take this on as part of continued refinement.
