### ISSUE TITLE
Feature Request: a 'Shutter' door type and/or per-door icons setting.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#9263]
### User Experience

In order to model a window with shutters/curtains properly, you have to overlay two walls: one that lets light through (either always or as one of the new v11 windows), and a regular, light-stopping door directly on top of it. This works, but looks sort of silly, since it's not a door, and even with the 'door' open, the 'window' still prevents pathing.

If there's some way of working a feature like this into the core workflow like 'if door, allow different light/sound/movement blocking values per state', that'd be great, but probably way too much work. The two overlaid walls works well enough, even if it's slightly annoying (some method for 'cycling the stack' of walls would be great though - currently you have to just shift one node of the 'upper' wall to get at the lower)

But if we can't get that, could we at least get settable icons per door segment? There's a module that handles this: [Designer Doors](https://github.com/Exitalterego/designerdoors) but I think this is a simple/broad enough use case it should be doable in core in some fashion.

**Comment by aaclayton** [comment]
Closing as duplicate and merging into #5025
