### ISSUE TITLE
When dragging a macro from one hotbar space to another occupied space, swap their positions instead of clearing the prior slot.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#9265]
### User Experience

It's frustrating every time I go to organize my macro hotbar to remember that dropping one macro on another just makes the original go poof, instead of swapping slots. I'm not sure if the drag info includes which hotbar slot is being dragged *from*, but this would be a nice QoL improvement.

**Comment by aaclayton** [comment]
A good QOL improvement related to https://github.com/foundryvtt/foundryvtt/issues/8613
