### ISSUE TITLE
The sizes of compendium and document directory windows can become stuck if viewport is resized

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9268]
Originally reported by corporat#1282 https://discord.com/channels/170995199584108546/1065764070680186930/1098658039256600706

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Firefox/MacOS latest  
**Short Description of bug:** The window size of compendiums and document directories can become "stuck" smaller when the viewport shrinks and then grows again  
**Simple steps to reproduce the bug:** 
1. Open a compendium
2. Make the viewport very small (such as by opening console)
3. Move it around so it changes size to fit the viewport, then close the compendium
4. Make the viewport original size
4. Reopen the same compendium

**Comment by aaclayton** [comment]
Deferring until stable maintenance ,if this is in fact still an issue.

**Comment by aaclayton** [comment]
Removing as non-repro
