### ISSUE TITLE
Allow holding the target key (T by default) while performing a drag selection operation to target all Tokens contained in the selection rectangle instead of controlling them.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#9275]
### User Experience

most systems and i think its standard foundry practice to use T for target. 

But what im suggesting that helps not having to switch to the target selection tool is to implement and standerdise holding T to be able to drag whilst holding T to add to targets. it would improve the player workflow and feel easier to use.

**Comment by ThingsCouldGetDicey** [comment]
> 
sorry if i wasnt clear but what im suggesting is that when you press T for target that targets single targets. but what id like to see is that when you hold T for target you can also drag the mouse to select multiple targets. 

this would save from having to switch between the target button and going back to token controls.

**Comment by unsoluble** [comment]
Just in case you're not aware, Dicey, you can hold Shift while pressing T to target multiples.

**Comment by ThingsCouldGetDicey** [comment]
i know but this would be faster and more intuitive. aswell as useful for aoes.

**Comment by wonkoderverstaendige** [comment]
In trying to express the same: I often wish I could target selected tokens. Shift-add to selection works, but it's slow and requires a lot of attention. I often just want to box-select a large group of tokens and target them all. Either as requested by holding T, or Pressing a key combination (Ctrl-shift or something) to target the set of currently controlled tokens.
