### ISSUE TITLE
Attempting to re-order actors at the top-level of a compendium throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9280]
## Steps to reproduce
1. Create a new world.
2. Import some actors into the world.
3. Create a new Actor compendium in the world.
4. Drag a handful of actors into the compendium.
5. Refresh the page to ensure the compendium's document cache is voided.
6. Re-open the compendium that was just created.
7. Toggle the sort order from alphabetical to manual.
8. Attempt to re-order any of the actors.
9. Observe an error is thrown.

```
caught (in promise) Error: You must provide an _id for every object in the update data Array.
    at #preUpdateDocumentArray (foundry.js:13390:32)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13203:22)
    at async Actor5e.updateDocuments (commons.js:7760:23)
    at async Actor5e.sortRelative (foundry.js:14018:29)
```

**Comment by cswendrowski** [comment]
Could not repro. Since the error is from DND5E, which I know extends the Compendium App, this is likely a system issue
