### ISSUE TITLE
Overhaul the behavior of negative sources to suppress light and sight within it and block vision.

### ISSUE THREAD

**Issue by notfelx** [foundryvtt/foundryvtt#9283]
Overhaul how darkness sources (i.e. negative sources into our framework) are handled. Currently, a darkness source still provides a light source for vision and is revealing token inside the darkness area. Negative light sources should suppress light and vision and also block vision (like a wall would do). You should not be able to see behind a negative source. Negative light sources should not reveal the fog of war.

This overhaul should come with these improvements:

- https://github.com/foundryvtt/foundryvtt/issues/10435
- https://github.com/foundryvtt/foundryvtt/issues/10436
- https://github.com/foundryvtt/foundryvtt/issues/10437
- https://github.com/foundryvtt/foundryvtt/issues/10438
- https://github.com/foundryvtt/foundryvtt/issues/10439
- https://github.com/foundryvtt/foundryvtt/issues/10570
- https://github.com/foundryvtt/foundryvtt/issues/10480
- https://github.com/foundryvtt/foundryvtt/issues/10584
- https://github.com/foundryvtt/foundryvtt/issues/10585
- https://github.com/foundryvtt/foundryvtt/issues/10600
- https://github.com/foundryvtt/foundryvtt/issues/10599
- https://github.com/foundryvtt/foundryvtt/issues/10601

**Comment by Feu-Secret** [comment]
This issue needs a careful thinking and has been postponed to v12.
