### ISSUE TITLE
KB Updates - Compendium Packs

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9289]
- [ ] Compendium Folders
- [ ] Compendium Sidebar Menu UI Improvements
- [ ] Detail how the search function works
- [ ] Detail the new sort functions

**Comment by anathemamask** [comment]
Held pending finalization of UX/UI.

**Comment by CodeMoWerser** [comment]
Cody indicated the UI/UX updates are baked at this point, so I'll tag in and start working on this.
