### ISSUE TITLE
KB Updates - Introduction to Module Development

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9297]
- [x]  Review Article accuracy from a programming standpoint
- [x]  Revise the code blocks and json manifest to include new fields
- [x] Detail Image support in manifest JSON files
- [x] Mention and link to the Module Defined Subtypes article

**Comment by mattexdee** [comment]
Changelog for *Intro to Module Development*:
- Updated JSON examples
- Added details about `packFolders` and how they work
- Added details about how `media` works
- Noted that the `path` field is now optional and no longer requires the `.db` ending
- Switched `@APIV10` to `@API`
- Added some clarity about `scripts` and `esmodules`
- Added a section on Module defined sub-types
- Some other minor editing
