### ISSUE TITLE
KB Updates - Introduction to System Development

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9298]
- [x]  Review Article accuracy from a programming standpoint
- [x]  Revise the code blocks and json manifest to include new fields
- [x] Detail System Thumbnail Image support in manifest JSON files
- [x] Provide discussion of (and links to) the System Data Model article

**Comment by mattexdee** [comment]
Updated the intro to system development article.

**System Development Changelog**
- Added `esmodule` files to demo file structure
- Changed `.db` files to be folders to match LevelDB structure
- Removed the `path` field from the `system.json` demo and other areas
- Updated `compatibility` field demo
- Updated `authors` breakdown
- Removed the `path` and `module` fields from the `packs` definition in `Optional Manifest Attributes`
- Added details on how to use the `background` field
- Various typos, minor grammar changes etc.
- Linked to article on data models in the section on the data templates

**Comment by aaclayton** [comment]
Thank you very much @mattexdee!
