### ISSUE TITLE
KB Updates - Game Worlds

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9302]
- [ ] Update or add screenshot for world launch UI

**Comment by silvative** [comment]
Resolved with https://github.com/foundryvtt/foundryvtt/commit/cad4d05227c9898cc44ccbd88527dc109aad4755

### Changelog:

- Updated all 8 images with screenshots taken with the V11 interface
   - I recall you had a specific way you liked to crop images, so I have attached a zip of the images I used in case you would like to do so:   [world.zip](https://github.com/foundryvtt/foundryvtt/files/11376450/world.zip)
- Updated terminology to match V11 names, including:
   - Login Screen -> Join Page
   - Safe Mode -> Safe Configuration
   - Access Key -> Password
- Added instructions and explanations for new features such as locking worlds, favorite worlds, default worlds, Join Page themes, world list views
- Modified all instructions to support the new V11 workflow for the Game Worlds tab, most notably by reflecting the new positions of buttons and the shifting of options to a context menu.
