### ISSUE TITLE
Status effect is not applied to an actorless token if the status effect ID doesn't match the key of the entry in `CONFIG.specialStatusEffects`

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9310]
### What happened?

For example, the PF1 system adds to some of the status effects the `pf1_` prefix: so `sse` is`undefined` in these cases and the status won't be applied.

Also nothing is passed as the `active` argument to `_onApplyStatusEffect`.

```diff
    // Handle special case for effect(s) toggled for actorless token
    const effectsLength = data.effects?.length;
    if ( (effectsLength >= 0) && (this.actor === null) && (typeof options.toggleEffect === "string")) {
-     const sse = CONFIG.specialStatusEffects[options.toggleEffect.toUpperCase()];
-     if ( sse ) this._onApplyStatusEffect(sse);
+     const statusId = options.toggleEffect;
+     if ( Object.values(CONFIG.specialStatusEffects).includes(statusId) ) {
+       this._onApplyStatusEffect(statusId, this.document.hasStatusEffect(statusId));
+     }
    }
```

And we don't need this here anymore because `_onApplyStatusEffect` takes care of it:
```diff
    // Perception updates
    if ( visionChange || lightChange ) this.updateSource({defer: true});
    canvas.perception.update({
-     initializeVision: visionChange || lightChange || (options.toggleEffect === CONFIG.specialStatusEffects.BLIND),
+     initializeVision: visionChange || lightChange,
      refreshVision: elevationChange,
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 (build 296)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We can try and fix this bug, but I think we should seriously consider dropping support for special status effects on actor-less tokens in the future and require that tokens have an underlying actor in order for this functionality to be supported.
