### ISSUE TITLE
Add a hook in `Token._onApplyStatusEffect` to allow downstream modules or systems to support additional special status conditions which require token handling

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9311]
### User Experience

A hook in `Token._onApplyStatusEffect` would be eliminate the need for modules that add special status effects to patch `_onApplyStatusEffect` or subclass `Token`.

**Comment by aaclayton** [comment]
Makes sense, this is a good use case for a Hook.
