### ISSUE TITLE
`VisionMode.vision.defaults.color` has no effect

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9312]
### What happened?

Not sure if it is supposed to work or not. The `VisionMode` schema doesn't say which properties are allowed in `defaults`. It doesn't work when switching the vision mode in the UI, but it does work if changed via `TokenDocument.updateVisionMode`. But there's also no filtering of `defaults` in `updateVisionMode` like in `TokenConfig._onChangeInput`, and so it sets `angle`, `range`, and `enabled` if they are in `defaults`, which I assume is not intended.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 11 (build 296)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Feu-Secret this probably needs help from you to decipher the intended functionality and whether this is a bug or a documentation issue (or both).

**Comment by Feu-Secret** [comment]
This issue needs investigation.

**Comment by aaclayton** [comment]
Delaying work on this issue until V12.
