### ISSUE TITLE
Update summary reports error timed out for systems that have a max version set

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9321]
https://discord.com/channels/170995199584108546/1065764070680186930/1101306006362935316

![](https://media.discordapp.net/attachments/1065764070680186930/1101306005867995176/Screenshot_2023-04-27_190813.png?width=961&height=523)

**Comment by aaclayton** [comment]
Do we have reason to think this is a bug? Timeouts do happen and (intentionally). @cswendrowski was there more context in Discord that led you to feel this was a bug report rather than simply a legitimate timeout?

**Comment by kbrighton** [comment]
I can say that this exact same thing is happening to me as well.

**Comment by grz0** [comment]
I reported the same issue in #9150

**Comment by silvative** [comment]
I seem to be able to reproduce this issue on V11t3. 
I believe that I had a similar issue on earlier versions which was fixed by updating my Node version, but I'm not sure?


![Image](https://github.com/foundryvtt/foundryvtt/assets/66365038/29dac4cf-3ef6-462f-9528-39ae8d51c129)
