### ISSUE TITLE
Recreating a deleted World throws error

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9323]
https://discord.com/channels/170995199584108546/1065764070680186930/1101883045981728809

Simple steps to reproduce the bug: create a world, login, logout, delete the world, recreate the world with the exact same name, starting of world fails with below error (works after f5 though).

![](https://media.discordapp.net/attachments/1065764070680186930/1101883045772021790/image.png?width=961&height=121)

**Comment by aaclayton** [comment]
This issue needs a bit of time for further investigation, so shifting out of this milestone into Stable Maintenance.

**Comment by aaclayton** [comment]
We can still investigate to see if this can be fixed during stable maintenance, although depending on why this occurs we might have to delay the fix to v12.
