### ISSUE TITLE
Export Documents to Compendium packs retaining folder structure - either single folder or recursive.

### ISSUE THREAD

**Issue by toastygm** [foundryvtt/foundryvtt#9335]
## Single Folder
When a world document folder is exported to a compendium, it always exports to the root of the compendium.  Now that it is possible to have subfolders in compendiums, it would be beneficial to specify where the documents should be exported to; either in the top level or a particular (already existing) folder within the target compendium.  This allows a compendium to be built up from multiple folders within a world.

When the "Export Content" dialog is displayed, an additional dropdown field ("Destination Folder") would appear listing all of the folders that exist within the destination compendium pack, defaulting to the "(root)" of the compendium.

## Recursive
This feature request envisions a new checkbox in the dialog that appears when a world folder is exported to a compendium.  The new checkbox would be "Recurse folders", and if checked would export not only the contents of the folder, but recurse through all subfolders and export those items as well.  It would create the corresponding folder structure in the compendium.

This would allow a user to create their desired folder structure in the world, then export the entire folder structure (and all documents) to the compendium at once.

If the "Recurse folders" checkbox is unchecked, the current behavior (only exporting the documents in the selected folder, not subfolders) would be retained.

**Comment by aaclayton** [comment]
Thanks for considering to make this and the recursive case 2 separate issues. I may split them back out in the future but for now I think I'll combine them because we should be able to evaluate them together.
