### ISSUE TITLE
Multiple Wall UI/UX Bugs

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt#9340]
### What happened?

- Walls no longer have their Wall Directional indicators. This occurs on existing walls with a direction, and new walls that have a direction set on them. The walls still function as expected, however.
- Proximity walls do not respect wall direction for vision or light. This might not be a bug, but intentional function, but I would expect directional proximity walls to provide proximity vision when approached on their open side.
- Selecting multiple walls and double clicking a node the mass-edit them fails without an error, places a single wall node where the user clicked, which blocks any nearby nodes from being selectable. Changing the tool layer or drawing a new wall fixes this.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Draw a wall, and set a direction on that wall. No directional indicators will appear.

- Draw a proximity wall, and give it a direction. The wall's function will not change.

- Select multiple wall segments, and double click a wall node to open the configuration panel.

### What core version are you reporting this for?

V11 T1 296

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks for catching these issues Roman, we should try and fix these ASAP for testing 2.

**Comment by Feu-Secret** [comment]
Related to:
- https://github.com/foundryvtt/foundryvtt/issues/9361
- https://github.com/foundryvtt/foundryvtt/issues/9362
- https://github.com/foundryvtt/foundryvtt/issues/9363
- https://github.com/foundryvtt/foundryvtt/issues/9364

**Comment by shemetz** [comment]
Small extra issue (commented in #9364):  double-right-clicking a wall line segment does nothing, instead of opening the configuration window.
