### ISSUE TITLE
Attempting to edit a text drawing causes it to disappear when Left-Click to Release Objects core option is enabled

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9356]
Originally reported by LorduFreeman#8747 https://discord.com/channels/170995199584108546/1065764070680186930/1104517415485849741

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, nodejs, Chrome, DnD5e 2.1.5, V11 296  
**Short Description of bug:** Text Drawings disappear if double-left-clicked (menu briefly opens, then disappears) or deselected by clicking outside of them after placing and staying in Draw Text tool.  
**Simple steps to reproduce the bug:** Create  Draw Text rectangle, double-left-click it.  
**Screenshots and/or console errors:**  No errors. Info-messages confirm the drawing gets deleted immediately.

**Comment by Feu-Secret** [comment]
Reproduced this issue with the core option **"Left-click to Release Objects"** enabled.
