### ISSUE TITLE
Proximity walls do not respect wall direction for vision or light

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#9363]
### What happened?

This might not be a bug, but intentional function, but I would expect directional proximity walls to provide proximity vision when approached on their open side.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Draw a proximity wall, and give it a direction. The wall's function will not change.

### What core version are you reporting this for?

V11 T1 296

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
@aaclayton Should we consider this issue as a feature and still plan it for v11?

**Comment by aaclayton** [comment]
@Feu-Secret proximity walls should work with wall direction, if that isn't happening properly it's a bug.

**Comment by aaclayton** [comment]
@Feu-Secret is this an incorrect report then? Or do I misunderstand what the issue is about?

**Comment by Feu-Secret** [comment]
The wall direction is working as expected with proximity walls.
 @CodeMoWerser I propose that you open a feature request with the desired features.
