### ISSUE TITLE
On the walls layer, allow walls selection and manipulation by their line segment.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#9364]
### User Experience

Allow interaction with the line segment of the walls to ease their general usage:
- Selection
- Movement
- Hovering and focus

**Comment by shemetz** [comment]
@Feu-Secret while the feature now allows selecting and dragging walls, it does not allow for **double-right-clicking** them to open their configuration dialog window.  This feels like a bug now;  my cursor can hover over both wall nodes and lines, and can select both, but double-right-clicking a wall line does nothing while double-right-clicking a wall node opens the wall configuration.

(double-left-clicking, an alternative for opening the dialog, works normally on both nodes and lines).

Please extend this feature to support double right-clicking line segments!
