### ISSUE TITLE
Featured News does not always appear on first launch of V11

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#9367]
### What happened?

Originally discussed in Discord here: https://discord.com/channels/1064556936458158221/1100832577184596070/1101216125943021598

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1. Shut down Foundry
2. Delete cached news
3. Launch directly into a world
4. Return to Setup

### What core version are you reporting this for?

Version 11.296

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Created this as issue https://github.com/foundryvtt/foundryvtt/issues/9366, but yours has a better description so I'll remove the other.

> Investigate timeout or race condition issue with loading news and featured content upon first connection.
