### ISSUE TITLE
Foundry is crashing on exit

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9373]
### What happened?

I get this error after update to node v20.1 on foundry v10 and v11:
```
FoundryVTT | 2023-05-12 01:16:20 | [error] The "code" argument must be of type number. Received type string ('SIGINT')
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('SIGINT')
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at exit (node:internal/process/per_thread:188:24)
    at Object.onceWrapper (node:events:626:26)
    at process.emit (node:events:523:35)

```

OS: Linux

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Update nodejs to v20.1 then try to close foundry app in terminal pressing Ctrl+C.

### What core version are you reporting this for?

v10 and v11

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Note we don't explicitly support node 20, but this is caused by node 20 being more strict about the arguments to `process.exit` so it's a very simple fix.
