### ISSUE TITLE
Unreliable behaviour of "Import from compendium" function

### ISSUE THREAD

**Issue by toastygm** [foundryvtt/foundryvtt#9383]
### What happened?

After importing several compendiums as World Items, the import stopped working.  There is no error and the UI notifications indicate the items have been imported, but the World Items sidebar does not show the folder or items.

Shutting down and restarting the world seems to reset this.  I have seen this behavior on both Pathfinder 2e and HarnMaster 3 game systems.

The problem occurs intermittently, but once it occurs no more imports from Compendiums will work.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Go to a Items Compendium, and export contents
2. Check whether Items Compendium imported to a new World Item Folder.

Intermittently, the folder will not get created nor items visible in the sidebar.  Once this occurs, all subsequent imports from compendium will fail to create a visible folder.

### What core version are you reporting this for?

Version 11 Testing 2

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by silvative** [comment]
I'm not sure if this is related to the issue described but I noticed what I think is unexpected behaviour when following the instructions outlined

https://github.com/foundryvtt/foundryvtt/assets/66365038/3c605d0e-da07-4bd8-852f-d2c99f854c39

**Comment by cswendrowski** [comment]
Triage shows those particular items are incorrectly packed with a `folder`, so end up being rehomed
