### ISSUE TITLE
When installing multiple packages, all progress bars disappear when one completes

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9393]
https://discord.com/channels/170995199584108546/1065764070680186930/1106596093711630346

If multiple packages are being downloaded and have progress bars visibile, once the first bar reaches 100%, the other bars are hidden, and new bars are not generated as the update continues silently in the background

**Simple steps to reproduce the bug:** have two or more modules that require update, at least one much smaller than at least one other, something like GM Vision and an audio/animation pack. hit update all on the modules tab.

**Comment by aaclayton** [comment]
This might be related to the bugfix that @dev7355608 implemented, would suggest passing this to Eber.
