### ISSUE TITLE
World "requires dependency" state does not list missing dependencies

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9397]
![image](https://github.com/foundryvtt/foundryvtt/assets/15639841/1381c8b0-4f4a-4a51-b55e-db66a9368178)

This makes it difficult to diagnose why I can't launch a world

**Comment by aaclayton** [comment]
@DJ4ddi we'll look at improving this for an upcoming patch. To help us debug, would you be willing to share either by uploading here or by sending me a DM on Discord:

1. The `world.json` file for a world that is unable to launch
2. The `{Foundry Data}/Logs/diagnostics.json` file that tracks which packages and versions you currently have installed

This would help a lot to ensure that we are identifying the correct problem.
