### ISSUE TITLE
Develop a custom HTMLElement for `<range-picker>` which can be used for sliders with linked numeric input fields.

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt#9402]
### User Experience

These range sliders are nifty but sometimes I just want to type in the value directly!

![image](https://github.com/foundryvtt/foundryvtt/assets/66365038/a60029d4-c916-47cf-a715-2fb7d6b7b4c6)

**Comment by aaclayton** [comment]
Oops, I duplicated this issue, but this is now done!
