### ISSUE TITLE
Limit Import data input element to JSON files

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt/foundryvtt#9405]
### User Experience

Currently the import data dialog opens an OS file selector that can select any file, when in reality only JSON files are valid selections.
```diff
- <input type="file" name="data"/>
+ <input type="file" name="data" accept=".json"/>
```
Making a change like the above will limit the OS file selector to show only JSON files, preventing the user from uploading an invalid file, and simplifying finding JSON files in large folders.

**Comment by aaclayton** [comment]
Nice suggestion and an easy addition for us to make. I'll squeeze it into V11.
