### ISSUE TITLE
Face down cards should not display their name

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt/foundryvtt#9407]
### User Experience

A card being face down should represent their value being secret. However, currently, a card's name is still displayed regardless of its facing status. If the card deck has the card's value as its name (like the preset Poker decks do), this can reveal what is meant to be secret information.

Ideally, face-down cards should not display their names at all, or only show to GMs or owners of the card stack.

![image](https://github.com/foundryvtt/foundryvtt/assets/77904738/80936682-3e3d-4018-8783-e04c61a9e6aa)
Player view on an owned Hand. I wonder what cards I have...

**Comment by aaclayton** [comment]
Definitely a bug, I wonder if it was a regression at some point. I really don't think it was always like this? Should be fixed.
