### ISSUE TITLE
Ensure that the audio file played as the interface notification when a whispered message is received can be configured by a module.

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9408]
### User Experience

It is easy to miss a whisper from GM because the default notification sound is quiet. This has happened multiple times to me and my players. 
Please add 2-3 more audio files, for example, air horn.
Also, it would be nice to be able to select custom audio.

**Comment by aaclayton** [comment]
We can make sure - at least - that the audio file used for this is able to be assigned in `CONFIG` so that modules can change it to something else, but I think we'll be sticking with something subtle in core.

**Comment by aaclayton** [comment]
This is already the case and can be configured as `CONFIG.sounds.notification`. Closing as wontfix.
