### ISSUE TITLE
Being scrolled down on the Setup page creates offset Tooltips

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9413]
https://discord.com/channels/170995199584108546/1065764070680186930/1108659850877087765

Setup page package description tooltip appears very far above the hovered tile IF the page has been scrolled any
Simple steps to reproduce the bug:
1) Scroll down some.
2) Hover a package to get their description tooltip

The misalignment seems to be equal to the scrolling. 
![](https://cdn.discordapp.com/attachments/1065764070680186930/1108660617046392903/tooltip-misalignment.png)

**Comment by aaclayton** [comment]
I don't reproduce this one. Might be browser specific or already fixed?
