### ISSUE TITLE
Expired effects have erroneous label for duration

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9414]
https://discord.com/channels/170995199584108546/1065764070680186930/1108687699877052467

Place 3 actors in the combat tracker. Create an effect with a duration of 1 round on the actor who is first in initiative. Start combat and progress the turns. The effect's `duration.label` starts cycling between "None", "2 turns", "1 turn" forever.
(this bug also exists in v10)

![](https://media.discordapp.net/attachments/1065764070680186930/1108687699654758512/image.png?width=211&height=281)

**Comment by aaclayton** [comment]
Resolved duration computation.
