### ISSUE TITLE
Clarify the wording when asking to enable optional dependencies.

### ISSUE THREAD

**Issue by FloRad** [foundryvtt/foundryvtt#9420]
### User Experience

Currently the wording when asking for optional/recommended module dependencies can easily be misinterpreted in such a way that makes the dependencies seem mandatory when they are entirely optional (such as content modules).

Usecase: As a content provider I would like to recommend enabling/downloading other content modules I provide that the user may own.

![](https://media.discordapp.net/attachments/811676497965613117/1108795273209204786/image.png?width=486&height=350)
![](https://media.discordapp.net/attachments/811676497965613117/1108795503518421032/image.png?width=716&height=451)

**Comment by aaclayton** [comment]
@mouse0270 thank you for the suggestions, but please open a new issue. This one is closed.

**Comment by mouse0270** [comment]
Will do @aaclayton this was the one linked to, so I simply responded to it. I can make a new issue later today
