### ISSUE TITLE
Right clicking on a Folder opens and then immediately closes the context menu

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9427]

**Comment by toastygm** [comment]
This fix may not be in fact totally fixed.

I believe the fix was the following in `DirectoryApplicationMixin`:
```diff
- contextMenuSelector: ".directory-item",
+ contextMenuSelector: ".directory-item.document",
```

If so, then it is important to know that this breaks the Compendium context menus.  Once this fix is made, the context menu for compendiums simply don't show up at all.

**Comment by cswendrowski** [comment]
> This fix may not be in fact totally fixed.
> 
> I believe the fix was the following in `DirectoryApplicationMixin`:
> 
> ```diff
> - contextMenuSelector: ".directory-item",
> + contextMenuSelector: ".directory-item.document",
> ```
> 
> If so, then it is important to know that this breaks the Compendium context menus. Once this fix is made, the context menu for compendiums simply don't show up at all.

You should also apply the following to the defaultOptions of `CompendiumDirectory`:

```diff
+ contextMenuSelector: ".directory-item.compendium",
```
