### ISSUE TITLE
Compendium Packs not placed inside specified pack folders

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#9437]
### What happened?

Updating modules for v11, I've defined pack folders with subfolders and specified which packs should go in which folders, but the packs are added to the root of the Compendium Directory instead of the respective folders.

Additionally, none of the subfolders are added. The above happens even if I remove the subfolders and set the packs to be placed in the root folder.

The packs are still currently nedb.

```json
	"packs": [
		{
			"name": "deck",
			"label": "Core Deck",
			"path": "./packs/deck.db",
			"type": "JournalEntry",
			"ownership": {
				"PLAYER": "OBSERVER",
				"ASSISTANT": "OWNER"
			}
		},
		{
			"name": "documents",
			"label": "Core Docs",
			"path": "./packs/documents.db",
			"type": "JournalEntry",
			"ownership": {
				"PLAYER": "OBSERVER",
				"ASSISTANT": "OWNER"
			}
		},
		{
			"name": "tables",
			"label": "Core Rollable Tables",
			"path": "./packs/rollable-tables.db",
			"type": "RollTable",
			"ownership": {
				"PLAYER": "LIMITED",
				"ASSISTANT": "OWNER"
			}
		}
	],
	"packFolders": [
		{
			"name": "Backstory Cards: Core Deck",
			"sorting": "m",
			"color": "#144c73",
			"packs": [],
			"folders": [
				{
					"name": "Instructions",
					"sorting": "a",
					"color": "#144c73",
					"packs": [
						"documents"
					]
				},
				{
					"name": "Decks",
					"sorting": "a",
					"color": "#144c73",
					"packs": [
						"deck"
					]
				},
				{
					"name": "Tables",
					"sorting": "a",
					"color": "#144c73",
					"packs": [
						"tables"
					]
				}
			]
		}
	],
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a module with a manifest the defines pack folders and subfolders containing nedb `.db` files (in case that's the cause).
2. Install and activate the module.
3. Check Compendia and Folders in Compendium Directory.

### What core version are you reporting this for?

Version 11 Testing 3 (298)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by cswendrowski** [comment]
Was just a case of the packs already having folders - for other devs referencing this issue, you can reset all current pack folders for testing via `game.settings.set("core", "compendiumConfiguration", undefined)`
