### ISSUE TITLE
Add a standardized sort field to the `ActiveEffect` document schema

### ISSUE THREAD

**Issue by NekroDarkmoon** [foundryvtt/foundryvtt#9451]
### User Experience

Most base documents visible on either another document or the sidebar have a sort field defined on their schema, this doesn't hold true for the ActiveEffect document. And while systems and modules can set a flag on the ActiveEffect document and support sorting active effects on sheets, this requires additional logic in the sort method to account for active effects.

It would be nice to have the sort field be present on the document and while it can be argued that activeEffects are a temporary document and a sort value may seem pointless for them, there are systems that have effects living on actors and items for an extended period of time. One example of this is passive effects granted by items in the dnd5e system that live on the actor for an extremely long period of time.

**Comment by aaclayton** [comment]
Yes!

**Comment by aaclayton** [comment]
We don't have a use case in core for this but it might be good to sneak this in before V12 stable just so the field exists that downstream systems or modules could use.

**Comment by aaclayton** [comment]
The field has been added to the model, using this field to change the UX of active effects will be either up to systems or up to us later in core as a follow-up enhancement. The data is there to be used now though.
