### ISSUE TITLE
Migrate `ActiveEffect.icon` to `ActiveEffect.img` for consistency with other Document types

### ISSUE THREAD

**Issue by NekroDarkmoon** [foundryvtt/foundryvtt#9452]
### User Experience

Considering that `ActiveEffect.label` was deprecated in favor of `ActiveEffect.name`, I think it would make sense to apply a similar change to `ActiveEffect.icon` and deprecate it in favor of `ActiveEffect.img`. I believe `ActiveEffect` is the only primary document type that uses `icon` while other documents refer to `img`; `icon` in most other scenarios is used to refer to FA icons.

**Comment by JPMeehan** [comment]
Bumping for v12 consideration per @aaclayton comment in v12-feedback

**Comment by JPMeehan** [comment]
Concrete example of a benefit of unification: This would simply embedded document creation because right now creating an embedded document on an actor requires checking the document class to know what the property for the image associated with the document should be.
