### ISSUE TITLE
In some circumstances, deleting a system fails to refresh the setup UI

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9463]
Originally reported by mclemente#5524 
 
https://discord.com/channels/170995199584108546/1065764070680186930/1110775476252848178 
 
https://discord.com/channels/170995199584108546/1065764029278212230/1110986368370348153

1. Create a world with a system you have installed (i used DSA5)
2. Launch world at least once (this may be optional)
3. From setup menu uninstall the game system the world has assigned
4. error:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/d9c250ae-8717-455a-a086-2dd0c31669e5)

**Comment by Dumbhuman** [comment]
For whatever it's worth, I encountered this bug uninstalling DnD5e and also Cyberpunk 2020.

I did not encounter it when uninstalling Simple Worldbuilding System and Warhammer Fantasy Roleplay 4th Edition.
