### ISSUE TITLE
TokenConfig does not retrieve derived attributes for non-DataModel systems

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9472]
We moved to the model in #8726 for systems that use DataModels but should preserve the existing functionality for systems that don't, since it doesn't require any special `toObject(false)` behaviour.

**Comment by aaclayton** [comment]
Yes, I believe it would have that side effect. The fix we would apply here should correct that issue, but @Fyorl can verify as part of what we merge in.
