### ISSUE TITLE
Add support to "track change" the upstream manifest URL of a package if the current URL returns a 404 response and the website repo has a viable alternative.

### ISSUE THREAD

**Issue by aMediocreDad** [foundryvtt/foundryvtt#9476]
### What happened?

According to the update flow a package's Repository listing is checked to see if there exists a newer version: https://foundryvtt.com/article/package-management/

> If the Package is listed in the Package Repository:
> 2.a Foundry checks to see if the manifest field has changed in the listing and points to a newer version compatible with the installed version of Foundry.

While the text here is somewhat ambiguous, I understand it as:

1. Foundry checks the Package Repository (Foundry Admin?) for the existence of package.
2. Foundry checks if there is AN entry in the package's data with a newer version number.
3. Foundry asks if the user wants to "switch tracks" if the URL in the Package Repository is different to the manifest URL in the local package. 
4. Foundry uses the new or old manifest URL depending on user's response to download the new manifest.

Assuming the above is somewhat correct, there is then a bug, where the manifest URL in the Package Repository is ignored if the local URL is broken and not pointing to a manifest anymore.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

An example of this can be reproduced by downloading v10.2.2 of Forbidden Lands (only Foundry V10 conpatible):

https://raw.githubusercontent.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/v10.2.2/manifests/v10/system.json

And then attempting to update the system. The manifest URL in the downloaded package points to nothing:
https://raw.githubusercontent.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/main/manifests/v10/system.json

Whereas there does exist both a current and a newer version compatible with the current Foundry install in the Package Repository: https://foundryvtt.com/packages/forbidden-lands (Note v11.0.0)

### What core version are you reporting this for?

This bug has been present since v0.8.2. Tested on 10.291 and 11.299 most recently

### Relevant log output

```shell
An error declaring the manifest url returning 404 is presented the user
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by cswendrowski** [comment]
Dev note: We should track swap on 404's, but not 500's or timeout errors

**Comment by aaclayton** [comment]
My impression is that this would be a new feature - to add support for automatic track changing if the current manifest URL results in a 404 response - rather than a bugfix. @cswendrowski would you agree with that? We should evaluate how much risk there would be to make this change in V11 stable. We can potentially do that, or defer as a new feature for v12.

**Comment by cswendrowski** [comment]
@aaclayton the goal of track swaps is to present the user with the information that a newer version is available somewhere else, and the option to execute the swap. If the URL resolved and was older, a track swap would be prompted. I view the url being down completely as an error case we didn't consider and should be pretty easy to patch up
