### ISSUE TITLE
Private GM Roll chatlog dropdown does not create Private messages

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9486]

**Comment by aaclayton** [comment]
What chat command are you entering? `/roll` will always be public roll regardless of the dropdown value just as `/gmroll` will always be a GM roll. Are you sure this isn't a misunderstanding?

**Comment by cswendrowski** [comment]
From our KB:
> The /roll command will always roll using the selected type of roll

The dropdown does work for `/roll d20`, but not for general messages, which may be intended, but I'm no longer sure how I'm supposed to create a private GM chat message - is the only option to remember the `/whisper gm <message>` format?

**Comment by Fyorl** [comment]
Closing this; the roll mode drop-down is specifically for rolls, it has no bearing on normal chat messages.
