### ISSUE TITLE
Harden the ping activity handler against cases where the ping coordinates are (somehow) incorrect

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9491]
Reported by <https://discord.com/channels/170995199584108546/1065764070680186930/1110996971910615040>

Sometimes when my players ping on the map I get the attached error. Simple steps to reproduce the bug: unfortunately don't know how to reproduce. unchain your players (but expect them to be bad at describing what they just did)

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/f8db4ac2-4184-44cd-960f-a6b4cac25deb)

**Comment by Feu-Secret** [comment]
Unable to reproduce it. However, it is not bad to harden our handler to handle this edge case.
