### ISSUE TITLE
It is no longer possible to rectangle-select multiple map notes

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9500]
Reported <https://discord.com/channels/170995199584108546/1065764070680186930/1111672610330267758>

OS, Hosting, Browser (if applicable): Windows, Local hosting, desktop app,  11.299
Short Description of bug: Box-select of map notes no longer functions correctly: map notes are not selected.
Simple steps to reproduce the bug:  Create some map notes, try to use the box-select tool to select them

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/5e1902af-bff3-4bff-9d88-1bd8bda74c19)

**Comment by Feu-Secret** [comment]
Map notes box select is not possible and was not possible in previous versions. Here the normal behavior:
- https://foundryvtt.com/article/map-notes/
