### ISSUE TITLE
Package authors tooltip does not correctly render authors which have a `url` defined.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9502]
Reported <https://discord.com/channels/170995199584108546/1065764070680186930/1111766905380941864>

OS, Hosting, Browser (if applicable): any
Short Description of bug: Authors tooltip in setup page shows empty spots for authors that have URL defined.
Simple steps to reproduce the bug:
```json
  "authors": [
    { "name": "Example", "url": "https://example.com" }
  ],
```

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/2b436cc1-d4e3-4843-a44f-80aa20da3d10)

**Comment by Feu-Secret** [comment]
Fixed by : https://github.com/foundryvtt/foundryvtt/issues/9492
