### ISSUE TITLE
RollTableResult documentId field is incorrectly nullified when the table is moved into a compendium pack

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9505]
Reported <https://discord.com/channels/170995199584108546/1065764070680186930/1112020211546206258>

**Dev Note:** I'm not sure about this report, feels like this could just as easily be a misunderstanding as a bug. Needs repro and investigation.

ALL MODULES DISABLED? true

OS, Hosting, Browser (if applicable):  Win10, self/Node, Chrome

Short Description of bug:  documentId stripped from recursive RollTable results when moved into a compendium

Simple steps to reproduce the bug:
Create simple sidebar Roll Table with a single result pointed at a Roll Table in a compendium
Note the value of table.results.contents[0].documentId matches the id of the referenced compendium Roll Table
Put that sidebar Roll Table into a compendium
Note the value of table.results.contents[0].documentId matches the id of the referenced compendium Roll Table in V10, but is null in V11

## Other report from different user
<https://discord.com/channels/170995199584108546/1065764070680186930/1112026099300446238>

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: macos, self/Node, chrome
**Short Description of bug**: Rolltable results referencing compendium items show broken content-link when rolling from table in a compendium, but not when rolling from table in world.
**Simple steps to reproduce the bug**:
- create item compendium and add an item to it.
- create rolltable in world with results that reference those compendium items (e.g., dragging in items from compendium to add results to table). (Currently you need at least 2 results because of offsetHeight bug with 1-result tables,.)
- update new rollTable.
- roll on new rolltable in world, see item result appear in chat, everything looks good.
```
<li class="table-result flexrow" data-result-id="2N9AMOt3FXyi6tWz">
            <img class="result-image" src="systems/cy-borg/assets/images/icons/armor/rough.png">
            <div class="result-text"><a class="content-link" draggable="true" data-pack="cy-borg.cyborg-items" data-uuid="Compendium.cy-borg.cyborg-items.Item.hTJcEEmbZ1ANvrrj" data-id="hTJcEEmbZ1ANvrrj"><i class="fas fa-suitcase"></i>Rough</a></div>
        </li>
```
- create rolltable compendium, adding this new rolltable from world.
- open rolltable from rolltable compendium and roll on it.
- see broken item result with null item id:
```
<li class="table-result flexrow" data-result-id="2N9AMOt3FXyi6tWz">
            <img class="result-image" src="systems/cy-borg/assets/images/icons/armor/rough.png">
            <div class="result-text"><a class="content-link broken" draggable="true" data-pack="cy-borg.cyborg-items" data-uuid="Compendium.cy-borg.cyborg-items.Item.null"><i class="fas fa-unlink"></i>Rough</a></div>
        </li>
```

**Comment by mcglincy** [comment]
I did some additional testing, trying to determine exactly what's going on. 

A RollTable containing item results (doesn't matter if item results are in world or compendium) seems to have TableResults with a correct documentId when the RollTable is in world, but if that RollTable is moved into a compendium, the TableResults have a null documentId (as seen by grabbing the RollTable via game.packs.get() followed by pack.getDocuments(), and looking at the RollTable document's EmbeddedCollection of TableResults).

I also unpacked both the world data/tables and the packs test compendium to poke around. Both unpacked _source json files seemed to have the correct tableresults, and the tableresult json files had correct, non-null documentIds. 

So somehow getDocuments() may be not be populating the RollTable's embeddedCollection TableResult.documentId field for some reason?
