### ISSUE TITLE
When updating multiple packages simultaneously progress bars are not being correctly cleared once progress for a certain package reaches 100%

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9513]
when updating multiple packages the progress bars are not being cleared when they reach 100% and instead sticking around which prevents the display of additional progress bars for updates still ongoing in the background.

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/b87dc4d9-4bb4-462a-b3ff-4ba01b39ccba)

**Comment by Fyorl** [comment]
Not able to reproduce this

**Comment by dev7355608** [comment]
Me neither.

**Comment by aaclayton** [comment]
Might have been a one-off or some kind of other issue. 

In case it helps, I believe I requested to update multiple specific modules individually, rather than as an "update all" operation. Might that have anything to do with the behavior? Otherwise we can close this as nonrepro.
