### ISSUE TITLE
Warnings about missing fonts despite them being loaded

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#9546]
### What happened?

These messages show up in the dev tools with every refresh. The fonts do load, the warnings just appear regardless.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/df44e366-1d54-4c4d-9d41-04bf262ea15f)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1) Open foundry.
2) See dev tools.

### What core version are you reporting this for?

11.300

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Reproduced in my environment (Windows 11, Chrome 114.0.5735.134 64 bits)


![Image](https://github.com/foundryvtt/foundryvtt/assets/66535080/7bbb8702-77e0-4b6b-9a59-7315893c0f09)

**Comment by krbz999** [comment]
Adding this year-old context before it gets lost: https://discord.com/channels/170995199584108546/729084554119348245/1111348105506472067

**Comment by krbz999** [comment]
I am no longer receiving either of these warnings in v12. Seemed to have resolved itself in a build just prior to Stable 1.

RIP Amir and Bruno.

**Comment by aaclayton** [comment]
Probably a Chromium bug that updating to a new Electron version fixed. Thanks for the confirmation!
