### ISSUE TITLE
`Roll.fromTerms` fails to parse a formula with parentheses

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9554]
Originally reported by Loner#3473 https://discord.com/channels/170995199584108546/1065764070680186930/1113211436433428480

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux/node  
**Short Description of bug:** Roll.fromTerms is incorrectly parsing a formula with parentheses  
**Simple steps to reproduce the bug:**
1. const roll = new Roll("(d4)"); // or "max(d4 - 2, 0)"
2. Roll.fromTerms([PoolTerm.fromRolls([roll])])

**Screenshots and/or console errors:**
![image](https://github.com/foundryvtt/foundryvtt/assets/207433/dd3d00d3-1862-4a19-947a-f36c891a8ac0)

**Comment by Fyorl** [comment]
I can only imagine this is related to the changes in #8661 as I don't think we made any other changes to rolls, but I may be misremembering.

**Comment by Fyorl** [comment]
I had assumed this was a v11 regression that was impacting existing systems, but this error is also thrown if you run the example code in v10 as well. In that case I'm de-prioritising this from high priority, and postponing it to v12 where we intend to do some deeper work on roll evaluation.

**Comment by stwlam** [comment]
Also related? https://github.com/foundryvtt/foundryvtt/issues/6048

**Comment by Fyorl** [comment]
> It is a regression in the case of the mta module. The module formulas works perfect on v10 but breaks in v11. This stops the module to be used in v11. Should we have wait till v12 then?

I ran this example in v10:
```js
Roll.fromTerms([PoolTerm.fromRolls([new Roll("(d4)")])]);
```
And received the same error as in this issue.

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/ace1e7b3-f9c9-4f9f-b889-5d3375ae41af)

So I'm not really understanding how it can be a regression? If the code also doesn't work in v10, it can't have regressed in v11.

**Comment by jabelardo** [comment]
I see, maybe it's another bug. But it's the same method and a similar situation. I am going to create an isolated test case to report it

**Comment by maqloner** [comment]
This probably need to be investigate further, same code in V10 and V11, no moduled enabled

In V10.291 - No exception
![signal-2023-06-07-121038_002](https://github.com/foundryvtt/foundryvtt/assets/682154/f4b907ea-7361-4488-8913-af67d16250c7)

In V11.300 - Exception
![signal-2023-06-07-121449_002](https://github.com/foundryvtt/foundryvtt/assets/682154/cd15f361-2f31-4e5c-b484-fefe3a8780a9)

**Comment by Fyorl** [comment]
I will take another look, using the `MathTerm` instead

**Comment by maqloner** [comment]
The good news is I was able to reproduce the bug in V10.291 (I have a hard time believing that I didn't hard refresh the Desktop App in all my tests)

But it mean the regression was introduce somewhere in the latest release of V10

I'm surprise nobody encounter this bug yet, since this is in the api integration documentation of Dice So Nice https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/Integration#v08-and-v9

**Comment by jabelardo** [comment]
So I finally got a test case for this, and in my case is works for v10 just fine and it's used in https://foundryvtt.com/packages/mta 

V10: working fine
![v10-no-error](https://github.com/foundryvtt/foundryvtt/assets/3663543/d6ede7b1-fd51-4fce-8c1a-af1ea0c3fb22)

V11: error
![v11error](https://github.com/foundryvtt/foundryvtt/assets/3663543/2f1d022d-7a12-42f2-a228-6da39b8a44fb)

**Comment by Fyorl** [comment]
OK, the key is that the rolls are evaluated. It doesn't seem to work in v10 or v11 if the rolls are unevaluated. This must have been directly caused by #8661 then, since `formula` for the evaluated rolls will not have any parentheses in them, while `_formula` will (since it's the original formula).

**Comment by jabelardo** [comment]
> OK, the key is that the rolls are evaluated. It doesn't seem to work in v10 or v11 if the rolls are unevaluated. This must have been directly caused by #8661 then, since `formula` for the evaluated rolls will not have any parentheses in them, while `_formula` will (since it's the original formula).

But in my example it works on v10 when .roll({async: false}) is used

**Comment by Fyorl** [comment]
> > OK, the key is that the rolls are evaluated. It doesn't seem to work in v10 or v11 if the rolls are unevaluated. This must have been directly caused by #8661 then, since `formula` for the evaluated rolls will not have any parentheses in them, while `_formula` will (since it's the original formula).
> 
> But in my example it works on v10 when .roll({async: false}) is used

Yes, calling `roll` evaluates the roll. That's the reason it works. Without evaluating the roll, it fails in v10 also.

**Comment by Fyorl** [comment]
We are going to revert the changes in #8661 for now, in order to fix this issue for the systems that it impacts in v11, and will aim to fix the underlying issue with parsing parenthetical terms inside dice pools in v12.
