### ISSUE TITLE
Under some circumstances, an error thrown in _onMouseMove can prevent further mouse clicks from being handled

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9558]
Originally reported by corporat#1282 https://discord.com/channels/170995199584108546/1065764070680186930/1114292939049410662

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Mac/Firefox  
**Short Description of bug:** [Rare] Foundry suddenly stops handling button clicks. Any time I move the mouse inside the Foundry window I get an error in console  
**Simple steps to reproduce the bug:** I'm not sure, very infrequent and it only seems to happen when I'm working with compendium packs a lot  
**Screenshots and/or console errors:**
```
Uncaught TypeError: can't access property "SHOW_CURSOR", this.permissions is undefined
    hasPermission commons.js:12632
    _onMouseMove foundry.js:36047
    _onMouseMove foundry.js:26828
    timeoutId commons.js:2065
    setTimeout handler*debounce/< commons.js:2064
    addListeners foundry.js:26813
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128
commons.js:12632:24
```

**Comment by anthonyronda** [comment]
I found one way to repro this! I maintain that this isn't the only way to trigger the above, but the symptoms afterward are exactly the same

1. Run the following code anywhere (may be typed into console)
```js
ChatMessage.create({
      speaker: game.user,
      content: `test`,
    })
```

Note the following:
* the speaker shows as Unknown User in the created chatcard, but if you refresh, it will show the correct user
* option `user: game.user` is handled fine
* options `user: game.user.id` and `speaker: game.user.id` are handled fine
* passing game.user in the speaker option of ChatMessage.create() worked fine in V10

**Comment by Fyorl** [comment]
> @Fyorl could the nonrepro tag could be removed? I have repro steps above.

The nonrepro tag is removed when we are able to reproduce the issue internally.

**Comment by anthonyronda** [comment]
Apologies, my apprehension about it getting lost in the shuffle came from the milestone getting changed

**Comment by Fyorl** [comment]
I tested in both v10 and v11 and got the same result: Passing `game.user` in as the `speaker` field in `ChatMessage.create` clears all fields in the existing `game.user` instance, including the `permissions` field, which is what causes the reported error.

**Comment by Fyorl** [comment]
Closing this as wontfix as passing a `User` instance as the `ChatMessage#speaker` is an incorrect use of the API.
