### ISSUE TITLE
Ensure that the Module Creator is not destructive of fields which it does not directly manage, like compendium pack ownership, banner image, etc...

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9559]
Originally reported by Garunts#5905 https://discord.com/channels/170995199584108546/1065764070680186930/1114762194425483334

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Foundry VTT application  
**Short Description of bug:** "Visible to GM Only" option in "Edit Module" interface is not saved  
**Simple steps to reproduce the bug:**

- Open the Setup screen
- Click on "Create Module"
- Add 2 compendium packs, set "Visible to GM Only" to true in only one of them
- Click "Create Module"
- Open the new module's module.json file, see both packs have the same "ownership" even though one is supposed to be GM only and the other one isn't
- In the setup screen, right click the new module and click on "Edit Module"
- Open the compendium tab, verify both packs have "Visible to GM Only" set to false
- Click 'EDIT MODULE' to confirm the edit (even though nothing has been changed)
- Return to the module.json to see the "ownership" field has disappeared from the packs entirely

**Screenshots and/or console errors:**  
Module being created, resulting module json and the same module json after "editing" the module

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/0679c1e1-667a-49ae-8771-9617d3b10982)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/394968fa-2772-466f-9c40-9d1df75b8130)

**Comment by aaclayton** [comment]
Comment from @Allalinor:

### What happened?

When clicking on Edit module in Foundry, then just clicking the Edit Module button in the window that pops up to close it. (Not even doing anything) It removed some lines from my packs in my module.json. (see attached images for a before and after)
![Before](https://github.com/foundryvtt/foundryvtt/assets/7441153/13e6d0a7-cb25-4666-9075-a70fe9cda133)
![After](https://github.com/foundryvtt/foundryvtt/assets/7441153/a723f40b-f57d-4e03-84ce-a87d9b647b99)


### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Make/Get a module.json with some packs.
2. Open up Foundry
3. Right-click on the module and click Edit Module
4. Close the window that opened by clicking Edit Module

### What core version are you reporting this for?

Version 11 Build 304

### Relevant log output

_No response_

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled
