### ISSUE TITLE
Add reliable means of updating multiple synthetic actors in a single transaction

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9566]
### User Experience

Currently the only way to leverage `ActorDelta` diffing is by updating a single synthetic `Actor`. Alternative approaches do not enjoy the these facilities. These include:
- Updating an `ActorDelta` directly
- Updating a `TokenDocument`'s `delta` field, either from a `TokenDocument` or via `Scene#updateDocuments`.

Incidentally, the deprecated `actorData` field slips into the latter and throws a warning that also discourages the approach entirely:
![image](https://github.com/foundryvtt/foundryvtt/assets/106829671/fa30b1bc-b81d-4180-acee-b2485b5aa674)

Especially for the sake of performing system migrations of actor data, it would be convenient to have some way to speedily and safely update multiple synthetic actors.

**Comment by Fyorl** [comment]
This seems like the same thing as #5241 just specifically for the `TokenDocument#delta` field, or am I misunderstanding?

**Comment by stwlam** [comment]
That appears to be narrowly discussing post-write callbacks (and the example seems to be expecting an actor name change via a token name change), but it looks to be getting at the same larger issue.

**Comment by Fyorl** [comment]
Yes, you're right, the actual contents of that issue does not really cover the full subject. We kind of use it as a catch-all for the general issue of 'child updates embedded in a parent update do not behave as if those children were updated directly'. It should probably be re-written
