### ISSUE TITLE
Refactor Document data model to store source information in _stats

### ISSUE THREAD

**Issue by anthonyronda** [foundryvtt/foundryvtt#9567]
### What happened?

There is not a surefire way to know if a document has been created from a compendium, from no source (such as with the Create button), or from duplication, because sometimes documents created through duplication are incorrectly tagged/untagged as though they were created from a compendium or as a default "blank" document. 

This is a problem because my users have asked me to mutate actors with my system's `character` subtype on creation, specifically to enable link actor data for that subtype by default. If we overload _onCreate without checking for the sourceId flag, we may be overriding someone who manually set their Link Actor Data setting back to disabled. Ok, no problem, check the core flag, that's what it's there for right?

But we have a corner case: when we duplicate an actor created without a "source" document (again, like with the Create button), the duplicate also appears to be created the same way, so we are *still* possibly overwriting their chosen setting for this.

Further, it just makes sense to me that duplicated documents have the original document as a source. It's plenty useful to know the uuid of the original.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

## Scenario 1

Prerequisite: Make an Actor compendium TestComp with TestActorA inside (names aren't particularly relevant).

### Expected behavior

In world TestWorld, I drag an actor named TestActorA from a compendium TestComp to the actor directory. TestWorld TestActorA's `sourceId` core flag begins with `Compendium.TestComp.`.

I duplicate Test**World** TestActorA (i.e. not from Test**Comp** this time). TestActorA (Copy)'s `sourceId` core flag matches the uuid of Test**World** TestActorA. It does **not** match the uuid of Test**Comp** TestActorA.

### Actual behavior

TestActor (Copy)'s `sourceId` also begins with `Compendium.TestComp.` That is, it matches the uuid of the compendium actor. The duplicate's sourceId core flag does not match the actor it was duplicated from.

### Expected behavior

In world TestWorld, I create a new actor TestActorB from the Create Actor button. TestActorB's sourceId core flag is not set (`getFlag("core", "sourceId") => undefined`).

I duplicate TestActorB. TestActorB (Copy)'s `sourceId` core flag is set to TestActorB's uuid.

### Actual behavior

TestActor (Copy)'s `sourceId` is also not set.

### What core version are you reporting this for?

11.300

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Reframing this to refactor our data model here to store explicit data in the model (probably under `_stats`), rather than relying on a flag. Some initial prototyping:
```js
_stats: {
  // ...
  compendiumSource: UUIDField,
  duplicateSource: UUIDField
}
```

**Comment by anthonyronda** [comment]
Was this in dev2 or testing1? It wasn't assigned to the testing milestone

**Comment by aaclayton** [comment]
Aah.. oops we missed getting a milestone applied here. This was included in Dev2.
