### ISSUE TITLE
Classic Fantasy theme has very low contrast fields, making them difficult to see if empty

### ISSUE THREAD

**Issue by thre-z** [foundryvtt/foundryvtt#9578]
### What happened?

Empty fields are very difficult to see when using the Classic Fantasy theme in the setup screen. It almost looks like the field is missing completely:

<img width="528" alt="image" src="https://github.com/foundryvtt/foundryvtt/assets/73196709/cd99e51c-dc9c-457b-83dd-5052d550e884">

A little more contrast here would make navigating these settings much more clear. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Set theme to Classic Foundry, look at empty fields. 

### What core version are you reporting this for?

v11 build 300

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Agree this needs improvement
