### ISSUE TITLE
Allow package update checks to identify a newer version compatible with the current software build even if that is not the latest available version.

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#9579]
### What happened?

I'm not exactly sure how to search for this issue, so sorry if it was already open somewhere else - also i'm not able to test if this issue still persists in V11, that said.

On V10, if you are on a module version X and a V10 version Y of the mod is availeble, it will not be updated if a version Z for V11 is also availeble

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Attempt to update a module that has a new version availeble for the currently installed FVTT build but also has a version for the next major FVTT build
- The module fails to install the update, instead it blocks the update as the availeble update is not for the current FVTT build.

### What core version are you reporting this for?

V10

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Reframed as a feature request since this isn't a bug.

**Comment by theripper93** [comment]
Same Issues (should be merged)
https://github.com/foundryvtt/foundryvtt/issues/8115
https://github.com/foundryvtt/foundryvtt/issues/7547

Also, in terms of implementation suggestions, currently FVTT checks the manifest indicated in the manifest.json, The worflow should FIRST check against foundry servers (eg, the versions and manifests provided by the module developer in the package management page) then, if that fails, check the manifest.

This would allow both non-listed and listed packages to work as best as they can.
