### ISSUE TITLE
Sort compendium document types in the compendium creation dialog so that they appear in alphabetical order (according to localized document names)

### ISSUE THREAD

**Issue by mxzf** [foundryvtt/foundryvtt#9588]
### User Experience

Currently, "Adventure" shows up at the end of the list of list of compendium types in the compendium creation dialog (both from the sidebar and in the module creation UI).  This is because `CONST.COMPENDIUM_DOCUMENT_TYPES` is created by taking the list of document types, excluding some, and concatenating on the "Adventure" type.  

Instead, I suggest that it be constructed using slicing or splicing or sorting or some method to get them properly ordered.  

It's not a particularly important thing, but it would be a nice bit of polish for the list to be properly alphabetized again.

**Comment by aaclayton** [comment]
Reframed as a sorting problem for the UI dialog.
