### ISSUE TITLE
Utilize `CONFIG.Canvas.rulerClass.canMeasure`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9595]
### User Experience

A `Ruler` subclass is configurable by a system or module, but the public static `canMeasure` getter cannot be overridden with the expectation that it will be utilized:

- `Token#_propagateLeftClick` and `Token#_onDragLeftStart` directly invoke the core class rather than `CONFIG.Canvas.rulerClass`:
```js
   /** @override */
  _propagateLeftClick(event) {
    return Ruler.canMeasure;
  }

...

  /** @override */
  _onDragLeftStart(event) {
    if ( Ruler.canMeasure ) return false;
    return super._onDragLeftStart(event);
  }
```

- `Canvas#_onDragLeftStart` duplicates the code of the getter:
```js
  _onDragLeftStart(event) {

    // Extract event data
    const layer = this.activeLayer;
    const isRuler = game.activeTool === "ruler";
    const isCtrlRuler = game.keyboard.isModifierActive(KeyboardManager.MODIFIER_KEYS.CONTROL)
      && (layer instanceof TokenLayer);

    // Begin ruler measurement
    if ( isRuler || isCtrlRuler ) return this.controls.ruler._onDragStart(event);
```

Assuming `Ruler.canMeasure` isn't intended to be internal-only, It would be dandy if an override of the getter could potentially be put into service.

**Comment by aaclayton** [comment]
Reasonable request, we can probably fit that change into our next V11 stable maintenance patch.
