### ISSUE TITLE
High CPU usage on server upon token move.

### ISSUE THREAD

**Issue by ssg3Davins** [foundryvtt/foundryvtt#9596]
### What happened?

Moving tokens on a scene is using too much cpu on the server. That causes the issue that on slower CPUs even when only 4 player are trying to move their tokens, the game just becomes unresponsive and choppy for a few second. The more complex the token actors are the worse they perform. Tested it in several environments, with different systems. Using the Native App as the server instead of Node performs a bit better. It is a longstanding issue for me and my players, even in v10.
Short video about the issue on a clean install (using WASD to move more tokens, since the players move fast after each other in succession as well, still happens fairly often with drag&drop, when the party moves from A to B):
https://youtu.be/yXkXT-dpN_0

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Install Foundry. Install a system, like dnd5e, so you can grab premade actors from compendium. Pull one into the scene, copy it a few times, then move them around with keys.

### What core version are you reporting this for?

Version 11 Build 301

### Relevant log output

No Relevant info in the logs

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
If we can fit room for priortiization on this it has the potential to make a meaningful difference in the perceived responsiveness of the app.

**Comment by aaclayton** [comment]
Completed earlier in the V12 cycle.
