### ISSUE TITLE
S3 Compares plain value to url encoded value when getting SignedUrl

### ISSUE THREAD

**Issue by FaeyUmbrea** [foundryvtt/foundryvtt#9624]
### What happened?

The S3 Implementation compares a URL Encoded value against a non url encoded value when trying to figure out the URl format from the signedURL. This causes the replace string to not contain a {key} placeholder if the first item in the bucket happens to have a URL-Encoded symbol in it.

The result is lots of malformed URLs.

### What ways of accessing Foundry can you encounter this issue in?

- [x] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

Connect an S3 button and make sure the first item in the bucket has a space in it. 

### What core version are you reporting this for?

Version 11 (Build 301)

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
This appears to have been fixed by some incidental changes where we no longer attempt to compare against the result of `getSignedUrl`.
