### ISSUE TITLE
Refactor `Notifications` and add a `progress` type notification, deprecate current `displayProgressBar` in favour of the new system

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#9637]
### User Experience

The current progress bar is a bit outdated, instead of revamping it, merge it with the current Notification system by implementing a new `progress` type notification.

**Implementation**

- Refactor single notifications to their own class
- Add new progress type notification, with it's own `progress` class, possibly a green color and a spinning font awesome icon
- When calling `Notifications#notify` return the new `Notification` class instance
- Move all core methods that use `displayProgressBar` to the new notification

**Progress Implementation**

- The new class should have a `Notification#updateProgress` method to update the progress of the notification
- When calling `Notifications#notify`, add a `closeOnComplete` option to automatically dismiss the notification once progress reaches or goes over 100
- The new progress notification should not count towards the maximum number of notification on screen
- The new progress notification should always be on top of the stack, this can be easly implemented via the `order` property
- The new progress notification should not be dismissable by the user
- To show the progress without drastic changes to the current html, consider using `element.style.background = linear-gradient(90deg, ${PROGRESS_COLOR} ${percent}%, rgb(0 0 0 / 63%) ${percent}%);`
- possibly, show the progress pecentage where the close button is currently located

**Example usage**

```js
const notification = ui.notifications.progress("My progress bar", {closeOnComplete: true})

myFunction.onProgress((percent) => {
    notification.updateProgress(percent);
})
```

Example of how this new notification would look:
![image](https://github.com/foundryvtt/foundryvtt/assets/1346839/940b6f49-4058-4d88-8e3d-d9ae35ac390a)

**Comment by aaclayton** [comment]
Best to tackle this when we refactor this component of the UI with ApplicationV2/ThemeV2.
