### ISSUE TITLE
V11 S3 Cache Chromium CORS

### ISSUE THREAD

**Issue by Havoclivekiller** [foundryvtt/foundryvtt#9644]
### What happened?

After upgrading to V11 (from V10) tokens and tiles on Scenes do not show their images from S3. Something with how cache is done now in V11.
1. Everything worked in V10. I didn't change any configurations, except by fixing aws.json template to the new one.
2. All other images and assets work from S3 - Actors have their portraits on sheets and sidebar, Items too, Music works. Also Scenes themselves have working backgorund image from S3 but not token and tiles.

CORS
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "POST",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```

 bucket policy 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::XXX/*"
        }
    ]
}
```

 aws.json 
```
{
    "buckets": ["XXX"],
    "region": "eu-XX-1",
    "endpoint": "https://XXX/",
    "credentials": {
      "accessKeyId": "XXX",
      "secretAccessKey": "XXX"
    }
}
```

options.json
```
{
  "dataPath": "/home/ubuntu/foundryuserdata",
  "compressStatic": true,
  "fullscreen": false,
  "hostname": "XXXX",
  "language": "en.core",
  "localHostname": null,
  "port": XXXX,
  "protocol": null,
  "proxyPort": 443,
  "proxySSL": true,
  "routePrefix": null,
  "updateChannel": "stable",
  "upnp": true,
  "upnpLeaseDuration": null,
  "awsConfig": "/home/ubuntu/foundryuserdata/Config/aws.json",
  "passwordSalt": null,
  "sslCert": null,
  "sslKey": null,
  "world": null,
  "serviceConfig": null,
  "compressSocket": true,
  "cssTheme": "foundry",
  "deleteNEDB": false,
  "hotReload": false,
  "telemetry": true
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I can reproduce the issue by creating a new Actor, give him a portrait (token) from S3 and put them onto the scene to show the error.
I can FIX the problem by using Disable Cache from Network browser sidebar. So this might point to some caching issue V11 does.
Tested in three different systems - Imperium Maledictum, World of Darkness 20th and Crucible. All have this issue for me (and my players).
I can grant access to my game/host to a Dev if they want to debug and see what is the problem.

I was able to reproduce this problem locally by installing Foundry V11 and V10. All works on V10 Foundry but the error shows up on V11, so its not a host issue, it must be a V11 issue. Tested it also with 299 and 302, so both versions of V11 have this problem.

![image](https://github.com/foundryvtt/foundryvtt/assets/21118924/72f6fbbe-d1ba-4e1c-9f70-27754973bfc1)
![image](https://github.com/foundryvtt/foundryvtt/assets/21118924/c817cad4-da33-4e0c-a7e6-39d596ce28c1)
In the screenshot above you can see that the image was get normally but once I put the actor on the scene, the image failed fetch.
![image](https://github.com/foundryvtt/foundryvtt/assets/21118924/f6d597d3-8312-4d1c-bc7b-9d299eb73409)

Here's with Disabled Cache
![image](https://github.com/foundryvtt/foundryvtt/assets/21118924/e4c15ad8-6ba5-405a-b68a-7eb7254ba1a3)
![image](https://github.com/foundryvtt/foundryvtt/assets/21118924/45d596de-57fe-4116-b6ef-b33708329fc2)

### What core version are you reporting this for?

Foundry v11.302

### Relevant log output

```shell
Foundry VTT | Created Token with id [SZynB3ReLLth2HNq] in parent Scene [dYxfGmlaQNeMDAH3]

Access to fetch at 'S3URL/chrisnpc.webp' from origin 'SITE' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
game:1 

Access to fetch at 'S3URL/chrisnpc.webp' from origin 'SITE' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
foundry.js:29170 

Error: The requested asset S3URL/chrisnpc.webp could not be loaded: [Loader.load] Failed to load S3URL/chrisnpc.webp.
TypeError: Failed to fetch
    at earcut.js:128:75
    at async Promise.all (index 0)
    at async Su.load (earcut.js:129:1)
    at async Ja._mapLoadToResolve (earcut.js:184:51)
    at async Ja.load (earcut.js:184:51)
    at async TextureLoader.loadTexture (foundry.js:28952:17)
    at async loadTexture (foundry.js:29161:13)
    at async Token._draw (foundry.js:54451:20)
    at async foundry.js:28096:7
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We used some very specific and intentional workarounds in our previous V10 asset loader that were removed when switching to use the PIXI loader in V11. We may need to look into restoring some of those functions.
