### ISSUE TITLE
Edit World doesn't always update

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9647]
Originally reported by farling https://discord.com/channels/170995199584108546/1065764070680186930/1119582133325938751

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable)**:  
Hosted on Ubuntu, Chrome browser on WIndows  
**Short Description of bug**:  
Edit World doesn't always update  
**Simple steps to reproduce the bug**: 
- Open the Edit World window.
- Enter some text into the world description
- Press "Update World"
- Nothing happens.
- Pressing it a second time sometimes doesn't do anything either.
- Eventually, a press of the Update World button might work and the window close

**Screenshots and/or console errors**:
- Nothing is reported in the console at all.

**Comment by farling42** [comment]
I've just had this on 11.306.

I was only setting the date and time.

Chrome browser connected to server on remote Oracle cloud.

**Comment by krbz999** [comment]
The `<label>` tag is unresponsive. Clicking the `<i>` tag or the `<button>` all work as expected

**Comment by farling42** [comment]
Yes, the label is unresponsive on Chrome too.  (Good find krb)
