### ISSUE TITLE
Open token character sheets are not closed when toggling linked state of tokens

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9651]
Originally reported by mrkwnzl https://discord.com/channels/170995199584108546/1065764070680186930/1120319416601690112

**ALL MODULES DISABLED?** true  
**Short Description of bug**: When linking a currently unlinked token, the character sheet isn’t closed and an error appears in the console when closing the character sheet manually, reading “Actor is not a valid embedded Document within the Token Document.” Functionally, everything seems to be working, though.  
**Simple steps to reproduce the bug**: 
1. Create a new world with the DnD5e system. 
2. Create a scene and a PC actor. 
3. Drag the PC actor onto the scene.
4. Open the character sheet and then the token configuration window.
5. Disable “Link Actor Data.”
6. Click “Update Token.” Note that both the token configuration window and the character sheet are closed.
7. Double click the token to open the character sheet and open the token configuration again.
8. Enable “Link Actor Data.”
9. Click “Update Token.” Note that both the token configuration window closes, but the character sheet stays open.
10. Close the character sheet. The error appears in the console.
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/1d60c155-d89f-44c9-ba0b-2eb2d28be152)

**Comment by mrkwnzl** [comment]
Something I missed initially. Re-linking the token seems to take full effect only after reloading the world. Certain aspects seem not to work completely, such as assigning status effects after unlinking and re-linking the token. A reload seems to fix these issues. So it’s not quite correct that everything seems to be working functionally. Sorry about that.

**Comment by Fyorl** [comment]
> Something I missed initially. Re-linking the token seems to take full effect only after reloading the world. Certain aspects seem not to work completely, such as assigning status effects after unlinking and re-linking the token. A reload seems to fix these issues. So it’s not quite correct that everything seems to be working functionally. Sorry about that.

Are you able to summarise the things that don't work into some minimal, reproducible steps so that we can verify that any fix here also fixes those issues? That would be very helpful.

**Comment by mrkwnzl** [comment]
Yes, should have done that directly. Sorry.

Steps 1–3 as above.

4. Set a status effect on the token (right-click and one of the pre-made ones. Doesn’t matter which one.)
5. Unlink the token from the actor data.
6. Try disabling the status effect. After the first click, nothing happens. Any further tries result in the error `undefined id [LECTmFOsbn9ceWVV] is not in the set of invalid ids`. Notice that the icon of the status effect stays on the token.

    <img width="642" alt="Screenshot 2023-06-19 at 15 05 24" src="https://github.com/foundryvtt/foundryvtt/assets/40534855/14061734-ab40-4fad-8875-c14c47490841">

7. Reload the world. The status is now gone and enabling and disabling status effects works as intended.
