### ISSUE TITLE
Scene textures are loaded consecutively instead of concurrently

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9652]
Originally reported kage6375: https://discord.com/channels/170995199584108546/1065764070680186930/1119462376174014494

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**:
    Foundry - v11.302
    Foundry Host - Linux Host (Debian Bullseye), Nodejs 18.16.0
    Browser OS - Windows 10 Pro.
    Browser: Chrome (Version 114.0.5735.134 (Official Build) (64-bit))

**Short Description of bug**:

Scenes load images load in a synchronous fashion, this becomes espically noticable when loading multiple svg/icon files as the latancy for each icon delays page load. This wouldn't be so much of an issue if these could be cached in browser cache.

**Simple steps to reproduce the bug**:

   Load any scene which requires multiple image assets.

**Screenshots and/or console errors**:

**Comment by rikmarais** [comment]
Hey there 👋 Thanks for tackling this one. I hadn't noticed that this issue had already been completed when I logged a duplicate.

Just checking, was the fix here load icons async in parallel?

**Comment by Aeristoka** [comment]
Testing this fix in v11.304, this is WORLDS better than any previous v11 version (most recently v11.302).

Thanks!
