### ISSUE TITLE
Autoplay Video does not work for Animated Tiles 

### ISSUE THREAD

**Issue by KrisHammerberg** [foundryvtt/foundryvtt#9654]
### What happened?

I have created a .webm tile with a simple looped animation. 

I set it to Autoplay Video, but when starting up the scene it doesn't play although the autoplay option is still set. If I then manually set it to play, the autoplay option is unselected. 

I have disabled all modules except The Forge, because I run Foundry via the Forge. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

The animated tile is below:
[MOSHED-2023-6-16-16-8-4.webm](https://github.com/foundryvtt/foundryvtt/assets/7592064/10e1dde7-4ca1-480e-8f12-48c4a7df327f)

Windows 11
Chrome v114.0.5735.134

### What core version are you reporting this for?

Version 10 Build 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
10.291
```
Uncaught (in promise) TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at VideoHelper.play (foundry.js:4382:23)
    at VideoHelper._onFirstGesture (foundry.js:4422:12)
```
11.302
```
TypeError: Failed drawing interface canvas group: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.. Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at Tile._draw (foundry.js:53262:27)
    at async foundry.js:28096:7
    at async Promise.all (index 2)
    at async TilesLayer._draw (foundry.js:34970:5)
    at async TilesLayer.draw (foundry.js:34456:5)
    at async InterfaceCanvasGroup.draw (foundry.js:29240:9)
    at async InterfaceCanvasGroup.draw (foundry.js:47646:5)
    at async Canvas.draw (foundry.js:26313:9)
    at async Scene.view (foundry.js:23455:7)
    at async Game.initializeCanvas (foundry.js:8833:20)
```

The `duration` of the video you provided is initially infinity even though the `readyState` of the video is 4. After a bit the duration becomes 3.833.

The video duration is N/A (ffprobe):
```
Input #0, matroska,webm:
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, unknown/bt709/bt709), 386x61, SAR 1:1 DAR 386:61, 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      alpha_mode      : 1
```

So something is wrong with this video file.
