### ISSUE TITLE
Add a new combatTurnChange hook event which is linked with the managed combat events workflow allowing modules to react to turn order changes.

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#9664]
### What happened?

When the combatStarted hooks is called, game.combat.started is false

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Register a hook on combat start and log game.combat.started

![image](https://github.com/foundryvtt/foundryvtt/assets/1346839/17030027-4d0a-4963-abc6-961bea31d5ff)

### What core version are you reporting this for?

V11 302

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
It's a poorly named hook, because it functions more as a `preCombatStart`. Either should be renamed or moved.

**Comment by aaclayton** [comment]
The prior combat hooks were awkward because they triggered only for the initiating client before any database operation occurred. I have implemented a new hook `combatTurnChange` which should be better behaved for most use cases when you want to respond to a combat turn event occurring.
