### ISSUE TITLE
Foundry crashes on launch with old-format aws.json

### ISSUE THREAD

**Issue by thre-z** [foundryvtt/foundryvtt#9668]
### What happened?

This appears to be a regression of #9322.

Foundry v11 build 302 crashes on launch with the same error message as the above issue, if the aws.json has not been updated to the new format as described in #8898. 

See troubleshooting here: https://discord.com/channels/170995199584108546/1111088928032837712/1121140412258713611

Also, comments on the #9322 issue also indicate users are experiencing the crash. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create old-format aws.json that is valid for Foundry v10
2. Update v10 to v11
3. Launch Foundry
4. Notice the failure to launch, with the `CredentialsProviderError: Could not load credentials from any providers` error

### What core version are you reporting this for?

v11 build 302

### Relevant log output

```shell
https://discord.com/channels/170995199584108546/1111088928032837712/1121140412258713611
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Additional repro info: `buckets` needs to be omitted from the `aws.json`.
