### ISSUE TITLE
Tooltips getting stuck and\or showing odd behaivour

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#9670]
### What happened?

This issue is meant to track what the possible cause of this issue is as i don't have exact repro steps:

Tooltips seem to be (pardon the term) "janky"

- Sometimes they get stuck
- Sometimes they don't trigger
- Sometimes the wrong tooltip triggers if there are nested elements with tooltips

But i haven't been able to reliably reproduce this, but it happens often enough to be noticable\annoying
Anyone has any more info to this so we can open a proper issue?

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

**Steps for getting stuck issue:**
See video: https://streamable.com/jawsv4

### What core version are you reporting this for?

V10 and V11

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by theripper93** [comment]
Other example https://streamable.com/syfeyj

**Comment by theripper93** [comment]
If this is of any help, this change seems to solve the issue, but i don't have enough knowledge to know if it has other repercussions

```js
    #startDeactivation() {
        if (this.#deactivationTimeout) return;
        // Clear any existing activation workflow
        this.clearPending();

        // Delay deactivation to confirm whether some new element is now pending
        window.clearTimeout(this.#deactivationTimeout);
        this.#deactivationTimeout = window.setTimeout(() => {
            if (!this.#pending) this.deactivate();
        }, this.constructor.TOOLTIP_ACTIVATION_MS);
    }
```

The change is adding `if (this.#deactivationTimeout) return;` to the top of the function

**Comment by aaclayton** [comment]
Thanks for the proposed change, we'll investigate it!
