### ISSUE TITLE
some delete items are failing

### ISSUE THREAD

**Issue by JFranklin3000** [foundryvtt/foundryvtt#9672]
### What happened?

![image](https://github.com/foundryvtt/foundryvtt/assets/71140111/5c86f47d-837e-4c54-9a0d-2c1008ecf8b9)
When deleting an item off of an actor's sheet the following error can appear. 

![image](https://github.com/foundryvtt/foundryvtt/assets/71140111/24a34320-6cb6-42f0-995d-3b127973590d)
Here is the item in the embedded Collection for the actor. 

![image](https://github.com/foundryvtt/foundryvtt/assets/71140111/8bee73b5-2138-476a-85cf-aee7ad6ec13d)

![image](https://github.com/foundryvtt/foundryvtt/assets/71140111/65ca5886-d744-4c29-aa3a-e4ee9094a067)
And the errors in the console. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Install system here: https://raw.githubusercontent.com/WookieeMatt/Essence20/main/system.json

create new actor of type powerRanger

Open the Across the Stars Compendium

in the Origins folder drag the Antagonistic origin on to the new actor. 

Under the Perks tab on the new actor delete the Always Training Perk

### What core version are you reporting this for?

Version 11 Stable (build 302)

### Relevant log output

```shell
foundry.js:67697 undefined id [3Pr9tq4aFBxtlw8K] is not in the set of invalid ids
fetch @ foundry.js:67697
notify @ foundry.js:67594
error @ foundry.js:67631
_handleError @ foundry.js:3387
(anonymous) @ foundry.js:3369
value @ socket.js:532
value @ socket.js:459
L.emit @ index.mjs:136
(anonymous) @ manager.js:207
Promise.then (async)
it @ websocket-constructor.browser.js:5
value @ manager.js:206
L.emit @ index.mjs:136
value @ index.js:131
value @ manager.js:193
L.emit @ index.mjs:136
value @ socket.js:324
L.emit @ index.mjs:136
value @ transport.js:97
value @ transport.js:89
ws.onmessage @ websocket.js:69
commons.js:8005 Uncaught (in promise) Error: undefined id [3Pr9tq4aFBxtlw8K] is not in the set of invalid ids
    at EmbeddedCollection.getInvalid (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/embedded-collection.mjs:272:27)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4864
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4844)
    at ServerDatabaseBackend.delete (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:182:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.handleEvent (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/sockets.mjs:1:517)
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
> I am getting this from deleting items that were created from an id stored on another item, but some do it and some don't and some don't. In fact I have an item with 4 associated ids and it only happens on one of them.

I don't think we'll be able to investigate this until we have clearer reproduction steps. The provided error messages are not really sufficient to identify the root cause unfortunately.

**Comment by JFranklin3000** [comment]
Update the testing steps to reproduce using our system. Hopefully that is alright. Thanks!

**Comment by phildominguez** [comment]
![image](https://github.com/foundryvtt/foundryvtt/assets/41161497/457bd374-2651-4f3b-a0ce-652b7f372da5)
The error seems to be coming from here, but when I set a breakpoint it never actually reaches it.

**Comment by LebombJames** [comment]
I've had reports of this occurring in Starfinder when toggling conditions via the sheet (not via the token hud, for some reason). I can only reproduce it when using Forge, but some users can reproduce it locally. 

I've also noticed it seems to semi-reliably occur after toggling the condition (n + 1) times, where n is the number of items on the actor. (I.e if the actor has 2 items, toggling a condition item will work fine 2 times, then fail when removing it the 3rd time).

The condition item that failed to be deleted disappears on reload.

**Comment by dev7355608** [comment]
@JFranklin3000: I cannot reproduce it with the provided steps.

**Comment by JFranklin3000** [comment]
> @JFranklin3000: I cannot reproduce it with the provided steps.

We can reproduce it on 5 different systems now. I have included a screen capture of the steps after creating a game world with no modules enabled just the system. 

https://github.com/foundryvtt/foundryvtt/assets/71140111/71a9d9c8-4f2c-4f3d-8448-411ffde4e583

**Comment by JFranklin3000** [comment]
Note on the video that is from my forge install where I can also reproduce it. That one does have modules activated. 

https://github.com/foundryvtt/foundryvtt/assets/71140111/96e51793-6d63-4ae5-b8a8-6ee8b6281d8d

**Comment by stwlam** [comment]
I'm able to reproduce in a fresh Abomination Vaults world running the following from the console immediately after adventure import (warning to passers-by: will destroy data):
```js
for (const actor of game.actors) {
    const ids = actor.items.map((i) => i.id);
    await actor.deleteEmbeddedDocuments("Item", ids);
}
synthetics = game.scenes.map((s) => s.tokens.contents).flat().flatMap((t) => t.actor ?? [])
for (const actor of synthetics) {
    const ids = actor.items.map((i) => i.id);
    await actor.deleteEmbeddedDocuments("Item", ids);
}
```

**Comment by FloRad** [comment]
As of build 305 the error message has become more clear (The ID points to an active effect in a synthetic actor))
![image](https://github.com/foundryvtt/foundryvtt/assets/5250409/82825100-cd60-4b76-80a7-4894376431f5)
