### ISSUE TITLE
[CANCELLED] Sorting of Actor items picks wrong drop target

### ISSUE THREAD

**Issue by admiralnlson** [foundryvtt/foundryvtt#9677]
### What happened?

Affects versions: 299 to 302 at least. Could very well be much older though. Last time I formally tested this was when the fixes for #7130, #7579 and #7580 were deployed (V10 Testing 2).

Dropping items onto an actor does not initialize the `sort` value (or initializes it to 0), resulting in no explicit ordering of items:
![image](https://github.com/foundryvtt/foundryvtt/assets/4472669/d823771b-fb16-4eff-8e3a-0f3ac1fd93b0)
This causes inconsistent UX while sorting them via drop-and-drop afterwards. Items don't move to the expected position in the list e.g :
![fvtt-sort-regression2](https://github.com/foundryvtt/foundryvtt/assets/4472669/b759b201-58be-4642-816e-7f8d38ffa2ba)
In the above, the expected order after the drag-and-drop would have been B - A - C - D.

One could think it's only a matter of ensuring the sort value is adequately intiated but there is a second issue:

Reordering items via drag-and-drop **can** allow to make the `sort` values unique (albeit with some effort):
![image](https://github.com/foundryvtt/foundryvtt/assets/4472669/d1ee5c71-f56a-4948-baff-1204206a0455)

But the values now being unique does not at all guarantee that the problem is gone.
Reorder the items again and you can relatively easily get into a situation where duplicate `sort` values appear again:
![image](https://github.com/foundryvtt/foundryvtt/assets/4472669/5f8cb6a0-f323-4bb3-bb09-c219608c0f41)

=> Dropping a fresh item onto an Actor *or* sorting them via dra-and-drop should not lead to duplicate `sort` values.

N.B. something which may help the investigation on the 2nd issue --> `sort` values used to be more granular in v9 / early v10 (e.g. `sort: 298438`), But now they seem to be always be generated as multiples of 10000. Maybe it was already the case that duplicate values could happen as a result of a `performIntegerSort`  in the past but, if yes, then the issue simply occurs much, much more often now that `sort` values seem to have been "locked" to multiples of 10000 always.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See desc above.

### What core version are you reporting this for?

302

### Relevant log output

```shell
See general desc
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
> Dropping items onto an actor does not initialize the `sort` value (or initializes it to 0), resulting in no explicit ordering of items:

I'm not sure about this one. I would have thought it's the responsibility of the sheet implementation that's consuming the drop event to set some appropriate `sort` value. The core `ActorSheet` implementation does not attempt to do anything special with newly-dropped items where `sort` is concerned, for example.

> Reordering items via drag-and-drop can allow to make the `sort` values unique (albeit with some effort):

and 

> Reorder the items again and you can relatively easily get into a situation where duplicate `sort` values appear again:

These definitely seem like bugs though. If all `sort` values are `0` then the next sort should reshuffle the entire collection to have unique `sort` values, it shouldn't require any special effort. Any subsequent sorts giving one of the items the same `sort` value as another (such as `0`) is definitely a bug.

**Comment by admiralnlson** [comment]
@Fyorl

I was able to pinpoint the origin for the behaviour I observe. It's not a change in core.

In the actor sheet's .hbs, I am iterating over
```
(context.)actor.items
```
and not
```
(context.)data.items
```
like I used to (or SimpleWorldBuilding does).

I originally did because `(context.)data.items` are plain JSON Objects and I wanted to access getters defined in my Items' datamodels from the .hbs file.

And this works beautifully btw.

Except sorting breaks...

I've been at it for a couple hours, trying to make it work (iterating over `(context).actor.items.contents` or sorted versions of it for instance). But I have now given up and resorted to using `context.data.items` again, calling every single datamodel getter from within getData(options)` itself instead.

Feel free to consider this issue as a request to allow the use datamodels getters from .hbs files with item sorting still working as expected.
Unless there's a way to make both work already which I've missed..

**Comment by admiralnlson** [comment]
@Fyorl 

I was able to pinpoint the issue I'm facing more precisely.

It's the fact that _onSortItem doesn't actually make use of the dradDrop.dropSelector.

It only uses:
```
const dropTarget = event.target.closest("[data-item-id]");
```

In my case, Foundry is picking up the correct item to drag but is dropping it on the wrong one.
And that it because I'm using special drag selectors :
```
      dragDrop: [{
        dragSelector: ".items-list .item .item-drag",
        dropSelector: ".items-list .item"
      }],
```
![image](https://github.com/foundryvtt/foundryvtt/assets/4472669/c9cbb197-5914-4127-9700-4f45b9dfad3d)
```
  {{#each abilities as |item id|}}
    <li class="item" data-item-id="{{item._id}}">
      <div class="item-drag" data-item-id="{{item._id}}" title="{{localize 'castle-falkenstein.item.sort'}}"><i class="fas fa-bars"></i></div>
      [...]
    </li>
  {{/each}}
```


This results in no siblings being identified by
```
// Identify sibling items based on adjacent HTML elements
```
in _onSortItem. And that's what causing the generation of duplicate sort values and wrong sorting, since the algorithm is simply not aware of the _actual_ siblings.


May I suggest to review _onSortItem so that, rather than looking for the 'closest' item, it looks for the closest which also matches the dradDrop.dropSelector?

**Comment by Fyorl** [comment]
Thanks for following up. I'm not sure exactly of the intended behaviour here wrt to the `dropSelector`. I believe it's only intended to mark the 'drop zone', i.e. an area where things can be dropped, rather than being related to sorting specifically. I agree that the logic used to determine siblings is quite narrow and relies on very specifically-structured markup to work. Overriding it is the correct solution if your sheet differs here, but there is room for improvement.
