### ISSUE TITLE
Tour Management 'Start Tour from Beginning' button actually continues in-progress tour from last position.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#9680]
### What happened?

![](https://i.imgur.com/jb3MS32.png) 
If, in this state, I push the hovered button, the tour does not start over and continues at step two. Since there's *also* a reset tour button, I have a feeling this is a documentation error in the tooltip, not a bug.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

with clean localstorage, launch a foundry world in v11. Click through to step two of the intro tour, then x out. 

### What core version are you reporting this for?

v11.302

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I think the behavior here is correct (resume from where you left off), but the label is incorrect.
