### ISSUE TITLE
Allow for setting a `pack`'s `banner` to `null` in module.json to blank it out

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#9681]
### What happened?

Setting `banner` to empty string seems to fall back on the default banners, despite the relevant code apparently being 
`return this.metadata.banner ?? CONFIG[this.metadata.type]?.compendiumBanner;` which looks to me like `""` should be respected? Unless I'm misunderstanding `??`.

Happens in pf2e and dnd5e, so I'm assuming not a system issue.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

create a module.json with something like: 
```
    "packs": [{
            "name": "pf2e_actors",
            "label": "Local PF2e Actors",
            "path": "packs/pf2e_actors",
            "type": "Actor",
            "system": "pf2e",
	    "banner": ""
        }]
```
Load world
Observe the default banners in place

### What core version are you reporting this for?

11.302

**Comment by aaclayton** [comment]
I would expect that field to be optional, but require a string if defined. I would expect a blank banner string to result in a validation failure. If we make that change though we need to be careful that we wouldn't be failing validation on data that we created somehow via the Module Configuration utility or otherwise.

**Comment by esheyw** [comment]
Well I see some value in being able to say 'no banner please' in module.json, which is what I was trying to achieve. Instead, I've just pointed it at a transparent webp. I made it 600x400 but I imagine it could be 1px and still work fine? So, a trivial workaround. Just unexpected that it was needed.
