### ISSUE TITLE
Provide options to configure ambience effects on the whole scene.

### ISSUE THREAD

**Issue by jacksands** [foundryvtt/foundryvtt#9683]
# Related Issues

### Planned for Prototype 1

- https://github.com/foundryvtt/foundryvtt/issues/9836
- https://github.com/foundryvtt/foundryvtt/issues/9988
- https://github.com/foundryvtt/foundryvtt/issues/10125

### Nice To Have

- #10129 (nice to have)

# Original Request

Hi! thanks for the amazing work!

Pls, can you take in consideration allowing the Global Illumination of a scene to use the same options as any other ligth?
On V10 the module Perfect Vision ( https://github.com/dev7355608/perfect-vision ) allow that, but it has been abandoned, and there is some nice effects that can be done that way, without the need to create a gigantic light source with no wall constraints...

I included one print screen with how they solve that, also they included a "Animated Resolution" slider that can also change the effect quit nicely!  In the example that vortex cannot have this appearance without tweaking resolution.

![image](https://github.com/foundryvtt/foundryvtt/assets/7229143/40ae75c0-b3fa-449e-864d-3446bbc38684)

**Comment by Feu-Secret** [comment]
EPIC completed. Moved issues planned for P2 outside because they are not directly linked to ambience lighting.
