### ISSUE TITLE
Pressing the Ctrl key after token drag has been initiated leaves a ghost token on the canvas

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9685]
Originally reported by ullantra https://discord.com/channels/170995199584108546/1065764070680186930/1122002801761992816

**ALL MODULES DISABLED?**: TRUE  
**OS, Hosting, Browser (if applicable)**: Foundry v11.302, Windows 10  
**Short Description of bug**:  The following bug is only partially resolved:  
https://discord.com/channels/170995199584108546/1065764070680186930/1081741287356641370  
https://github.com/foundryvtt/foundryvtt/issues/9002  
Issues with the Shift modifier are no longer present.  
Issues with Ctrl (Control) modifier still happening. Confirmed also by 
https://discord.com/channels/170995199584108546/1111088928032837712/1122000261251084320

**Simple steps to reproduce the bug**:
Start moving a token and then press the Ctrl key. Results in the token being dropped on their starting point and there is a ghost token stuck to the cursor. Right Clicking is the only way to clear the ghost token

**Screenshots and/or console errors**:

Hard to see in the screen grab but this is after the ghost is triggered. The token is still sitting on the canvas on the left. The mouse (with no buttons or keys pressed) is on the right where the ghost token has attached itself. The ghost token does not interact with the canvas at all. While the ghost token is stuck the mouse, the mouse cannot left-click to interact with any other canvas items.

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/e52e7aa5-8109-482d-84a7-fb919a2065c1)

---

**ALL MODULES DISABLED?**: TRUE
**OS, Hosting, Browser (if applicable): **Foundry v11.304, Windows 10
**Short Description of bug:**
Related to https://discord.com/channels/170995199584108546/1065764070680186930/1122002801761992816
Ghost tokens can still be made to present though Ctrl key interactions.

**Steps to reproduce:**
1) Start token move by holding down left click and dragging.
2) Hold Ctrl while still holding left click = Token ghost image get frozen to canvas and detached from cursor.
3) Releasing Ctrl results in the ghost image snapping back onto cursor
4) Hold Ctrl *and whilst doing so* release left click = original token dropped back onto canvas in starting location, while the ghost token is now stuck on cursor
5) The cursor can be used somewhat normally (see screen snip attached), and can be cleareed using right-click.

This is a core bug that is compounded by its interaction with a very popular module Drag Ruler:
https://github.com/manuelVo/foundryvtt-drag-ruler/issues/288

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/c7acd24d-ae6a-45fb-8bfb-ca32443dc41a)

**Comment by pedrogrullada** [comment]
This bug doesn't seem to be fixed. Still able to reproduce it on 305.

**Comment by aaclayton** [comment]
@dev7355608 perhaps you can double check whether this fix got applied or whether it regressed somehow?

**Comment by Cempres** [comment]
This issue is still happening in correlation with Drag ruler module

**Comment by aaclayton** [comment]
> This issue is still happening in correlation with Drag ruler module

This issue is closed because we have merged the code change which fixes it, but that fix has not yet been released. Please stay tuned!
