### ISSUE TITLE
Scene background / foreground images transfer between scenes

### ISSUE THREAD

**Issue by SuddenlyJace** [foundryvtt/foundryvtt#9686]
### What happened?

When switching between scenes, the old foreground and background images will render on the newly switched to scene.
![image2](https://github.com/foundryvtt/foundryvtt/assets/95511854/ae48c9c0-a7a4-42ed-ab56-7f94df67bc78)
![image3](https://github.com/foundryvtt/foundryvtt/assets/95511854/a018261f-6c64-4f2a-a241-582196538cf1)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

This does not happen on Windows, only Linux. This was reproduced with Firefox 114.0.2 on Fedora 38.

Switch between scenes and the ghost images of previous scenes will appear.

If you hack in a return() statement in foundry.js @ line 49690 before this block of code then the problem goes away.
```
// Get compressed base64 image from the fog texture
    let base64image;
    try {
      base64image = await this.#extractor.extract({
        texture: this.#explorationSprite.texture,
        compression: TextureExtractor.COMPRESSION_MODES.BASE64,
        type: "image/webp",
        quality: 0.8,
        debug: CONFIG.debug.fog.extractor
      });
    } catch(err) {
      // FIXME this is needed because for some reason .extract() may throw a boolean false instead of an Error
      throw new Error("Fog of War base64 extraction failed");
    }
```

### What core version are you reporting this for?

Version 11 Build 302

### Relevant log output

```shell
Error: Encountered an error while tearing down the previous scene: Fog of War base64 extraction failed
    #save https://foundry.example.com/scripts/foundry.js:49702
    _try https://foundry.example.com/scripts/commons.js:13652
    add https://foundry.example.com/scripts/commons.js:13624
    add https://foundry.example.com/scripts/commons.js:13622
    save https://foundry.example.com/scripts/foundry.js:49673
```

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm going to tag this as `nonrepro` because it's certainly not something I've seen happen so we need to identify a set of reproduction steps which can generate the problem.

**Comment by SuddenlyJace** [comment]
I'm able to reproduce on windows using Firefox on Windows as well by using the 'add script override' from Firefox 

Add foundry.js after line 49692 `throw new Error('ERROR!');` so that the code block looks like.
```
// Get compressed base64 image from the fog texture
    let base64image;
    try {
      throw new Error('ERROR!');
      base64image = await this.#extractor.extract({
        texture: this.#explorationSprite.texture,
        compression: TextureExtractor.COMPRESSION_MODES.BASE64,
        type: "image/webp",
        quality: 0.8,
        debug: CONFIG.debug.fog.extractor
      });
    } catch(err) {
      // FIXME this is needed because for some reason .extract() may throw a boolean false instead of an Error
      throw new Error("Fog of War base64 extraction failed");
    }
```

1. Create a new world
2. Add 2 scenes and set a background and foreground image for both
3. Lay down walls to obscure a portion of one of the scenes
4. Drop a actor on the scene
5. Select the actor on the scene with fog of war
6. Switch scenes and you get the ghosting

If the actor is not selected then everything renders fine.

**Comment by SuddenlyJace** [comment]
This is may be a Fedora 38 specific implementation of something that causes the failure, but the failure revealing the previous scene images isn't great.

I don't know if the error itself is worth attempting to fix. The failure condition may be worth attempting to fix. 

The error looks to occur when texture is an instance of PIXI.REnderTexture, baseTexture.format is PIXI.FORMATS.RED and baseTexture.type is PIXI.TYPES.UNSIGNED_BYTE. It happens in this block of code below from foundry.js.

```
let resolution;

    // If the texture is a RT, use its frame and resolution
    if ( (texture instanceof PIXI.RenderTexture) && (baseTexture.format === PIXI.FORMATS.RED)
      && (baseTexture.type === PIXI.TYPES.UNSIGNED_BYTE) ) {
      frame ??= texture.frame;
      resolution = baseTexture.resolution;
    }
    // Case when the texture is not a render texture
    // Generate a render texture and assign frame and resolution from it
    else {
      texture = this.#generatedRenderTexture = this.#renderer.generateTexture(new PIXI.Sprite(texture), {
        format: PIXI.FORMATS.RED,
        type: PIXI.TYPES.UNSIGNED_BYTE,
        resolution: baseTexture.resolution,
        multisample: PIXI.MSAA_QUALITY.NONE
      });
      frame ??= this.#generatedRenderTexture.frame;
      resolution = texture.baseTexture.resolution;
    }

    // Bind the texture
    this.#renderer.renderTexture.bind(texture);

    // Check read pixels capabilities
    if ( !this.readPixelsSupported ) {
      this.#generatedRenderTexture?.destroy(true);
      this.#generatedRenderTexture = undefined;
      throw new Error("Reading pixels as RED/UNSIGNED_BYTE is not supported");
    }
```

**Comment by cjneidhart** [comment]
Okay, this "fix" is absolutely ridiculous. Yes, it properly tears down foreground images now, but it disables fog of war saving? That's significantly worse, and I'd rather just revert to the .302 behavior. Yes, I can just use chromium but I think it's unreasonable to not support fog of war on every modern os+browser.
