### ISSUE TITLE
If a compendium is inside a folder, colour the folder generated during an import-all to match.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#9693]
### User Experience

Say I've got my module's compendia all inside a folder, and I'd like to import the entire Local Macros compendium. I'd like it if the folder created during import inherited the colour of the compendium's immediate parent folder, so in this case: 
![](https://i.imgur.com/CSEq7Jx.png)
the resultant Local Macros folder in the macro directory would be coloured that same red.

**Comment by aaclayton** [comment]
I think that UX makes sense and shouldn't be too hard to do, although it should probably only apply in the case that your target is a new folder and not an existing one.
