### ISSUE TITLE
Map Pin Labels drawing under New Map Pins

### ISSUE THREAD

**Issue by MrZeyami** [foundryvtt/foundryvtt#9712]
### What happened?

Since V11 I've noticed that my map pin labels are drawing under other map pins if the map pin is older than the pin that ithe label is drawing under.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1) Create a map pin note and give it a label.
2) Create a second map pin and place it where the first pin's label text draws.

Result:
The label is now blocked by the second map pin when the first map pin is selected.

### What core version are you reporting this for?

Version 11 304

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm not sure whether this is a regression from V10 because I don't *think* we had logic to ensure that labels were always above control icons, but in case that was the case we should investigate. We can at least ensure that a pin is sorted to the top of its container on hover.
