### ISSUE TITLE
A newly created Combat encounter with no Combatants triggers an error when attempting to dispatch turn events.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#9718]
### What happened?

When a `Combat` is created, `_manageTurnEvents` attemps to find the "previous" combatant, of which there are none.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Create a combat encounter. Empty or by using the token HUD, doesn't matter.
2. Behold the console.

### What core version are you reporting this for?

11.304

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'combatantId')
    at Combat._manageTurnEvents (foundry.js:21346:53)
    at Combat._onCreate (foundry.js:21184:10)
    at ClientDatabaseBackend.callback (foundry.js:13574:11)
    at foundry.js:13547:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13547:33)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Ghorin46** [comment]
Hello
I also get that error message in the log console of my browser (Chrome on Linux Fedora) with the same reproduction steps.
Do we know if this has any real impact on the game (apart of the error message in the console) ? In my own tests, I was able to manage a combat from end to end in the Combat Tracker (with "The One Rine 2e" system) and without any problem but maybe i'm missing something.

**Comment by aaclayton** [comment]
The error doesn't disrupt ability to use the combat, it just pertains to dispatching of combat events related to the creation of the combat. It's pretty harmless.

**Comment by aaclayton** [comment]
Needs to shift to v12 because we need a more rigorous and potentially *slightly* breaking solution to this problem.

**Comment by jacobsteffler** [comment]
@aaclayton Do you happen to know if this error message is a duplicate of this issue?

```
Uncaught (in promise) TypeError: this.previous is undefined
    at _manageTurnEvents foundry.js:21581
```

Foundry 11.315, DnD5e 3.0.1

**Comment by aaclayton** [comment]
> @aaclayton Do you happen to know if this error message is a duplicate of this issue?
> 
> ```
> Uncaught (in promise) TypeError: this.previous is undefined
>     at _manageTurnEvents foundry.js:21581
> ```
> 
> Foundry 11.315, DnD5e 3.0.1, reproduced in an empty world with no modules

Yeah, same issue!
