### ISSUE TITLE
A new wall segment chained off an existing node should always be snapped precisely to that node

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#9719]
### What happened?

When you Control/Command-chain a new segment off an existing one, the expectation is that when an existing node is shown to be "selected" by enlarging when you hover near it, the start of your new segment will be precisely snapped to that existing node. This behaved predictably in v10.

In 11.304, hover-enlarging the existing node isn't enough to cause this snap — you need to actually start your drag from very close to the center of the node. If you're away from the center (but still enlarging the node), your new segment will start from an unexpected location.

Hover-highlighting an existing node should force the start of a new Control/Command-dragged segment to be snapped to that node, no matter where you actually start the drag from within that region.

https://github.com/foundryvtt/foundryvtt/assets/801582/af98a30a-cb9f-41ac-96ea-17995cc259c9

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a wall segment.
2. Move your mouse near enough to one of the existing nodes to "highlight" or enlarge it, but not near the center of the node.
3. Control/Command-drag a new segment from there.

### What core version are you reporting this for?

11.304

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I agree that the hover size of the node should be the relevant hitbox for triggering a chaining operation.
