### ISSUE TITLE
Required dependencies of recommended packages are incorrectly inherited as required dependencies of the recommending package

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9725]
Originally reported by cafmel: https://discord.com/channels/170995199584108546/1065764070680186930/1124328394943901706

**ALL MODULES DISABLED?** not applicable
**OS, Hosting, Browser (if applicable)**: Win10
**Short Description of bug**: When enabling a module that has another module listed as "recommends" in the module.json, the first module will inherit the "requires" of the second module.
**Further context**: When I attempt to enable the Heretic's Guide module in the Module Management tab, a pop-up appears listing LibWrapper as a required dependency and Token Attacher + ScenePacker as optional dependencies.
LibWrapper is NOT listed as a .requires in the module.json for Heretics, but it IS listed as such in the .json for Token Attacher.
**Simple steps to reproduce the bug**: Not sure what the simplest way to recreate it is. I can send the modules in question if needed.

**Heretic's Guide json**:
```"relationships": {
      "recommends": [
          {
            "id": "token-attacher",
            "type": "module"
          },
          {
            "id": "scene-packer",
            "type": "module",
            "manifest": "https://github.com/League-of-Foundry-Developers/scene-packer/releases/latest/download/module.json"
          }
      ]
    }
```
**Token Attacher json**:
```"relationships": {
    "requires": [
      {
        "id": "lib-wrapper",
        "type": "module",
        "manifest": "https://github.com/ruipin/fvtt-lib-wrapper/releases/latest/download/module.json",
        "compatibility": {}
      }
    ]
  }```

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/8eb30a1f-bca6-4b1e-a031-b849a3dd450e)

**Comment by Fyorl** [comment]
Moving this to v12 as it required a significant refactor of the module management interface to resolve cleanly.
