### ISSUE TITLE
Add "preview sound" option to filepicker when the selected file is an audio file

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt#9747]
### User Experience

This would make it easier to select sounds for various functions by allowing you to "preview" them in the same way that our thumbnails do for images

**Comment by plutoneld** [comment]
Seems like a duplicate of #5808

**Comment by plutoneld** [comment]
#8861 too

**Comment by aaclayton** [comment]
Closing as duplicate of #5808
