### ISSUE TITLE
'Cannot read properties of undefined (reading 'format')' error notification thrown when updating modules

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9756]
Originally reported by jeansenvaars https://discord.com/channels/170995199584108546/1065764070680186930/1127204469273284688

**ALL MODULES DISABLED?**: N/A
**OS, Hosting, Browser (if applicable)**: Windows, electron
**Short Description of bug**: Sporadic errors when pulling module updates
**Simple steps to reproduce the bug:**
I am getting sporadic errors at least once every time I check for module updates. Works fine upon retry. Is there something that Foundry could do to improve the user experience here?

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/4213159b-e3da-4222-8edc-88e1b4dd1fad)

**Comment by nat212** [comment]
I am getting this error as well on a self hosted Linux server. It happens pretty much every time I try to update modules, which means I haven't been able to update pf2e to the latest version after updating foundry
