### ISSUE TITLE
Wrong application directory for Launching the Server Using NodeJS under MacOS

### ISSUE THREAD

**Issue by Schaltfehler** [foundryvtt/foundryvtt#9767]
### Where did you find it, or where does it belong for requests?

Knowledge Base (https://foundryvtt.com/kb/)

### What page or file needs a look at?

https://foundryvtt.com/article/installation/

### What core version are you reporting this for?

Version 10/11

### What is wrong, in your opinion?

At `Extracting and Launching the Server Using NodeJS`

```
# access the application directory
cd ~/Library/Application Support/FoundryVTT
```

This directory seems to be wrong, it should be 
`cd /Applications/Foundry\ Virtual\ Tabletop.app/Contents/`

**Comment by unsoluble** [comment]
The article assumes that you have downloaded the node app into `~/Library/Application Support/` (and yes, should be more clear about this, which has been raised in the docs channel on the discord).

But what you’ve used instead there is the path to the Electron bundle, which is not the same thing in context.

**Comment by Schaltfehler** [comment]
Thank you. I misunderstood, documentation is correct. This can be closed then :-)
