### ISSUE TITLE
ActiveEffects get applied twice on load

### ISSUE THREAD

**Issue by SirSamwell** [foundryvtt/foundryvtt#9768]
### What happened?

On loading foundry/refreshing the page, active effects seem to be applied to unlinked token actors twice, instead of only once. When updating the actor in any way, like changing the name in the actor sheet, the effect is only applied once after the change is complete. Reloading the page again, will result in it being applied twice again.

This problem only exists when using unlinked tokens. Linked tokens and 'base actors' (the ones in the actor directory) seem to behave correctly.

I tried this with my homemade system, using status effects and active effects from items. I also created a test system that basically only provides a status effect to apply to an actor, but the bug persisted. It was tested on a dedicated server running on ubuntu as well as the native app on windows (even on different computers).

It seems to me that this bug was introduced with v11, as I tried the same bare bones test system on v10 where it worked as expected.

The test-system I used:
[test-system.zip](https://github.com/foundryvtt/foundryvtt/files/12063929/test-system.zip)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create an unlinked actor token in any scene
2. Apply a status effect that changes an attribute to the token. Example:
![image](https://github.com/foundryvtt/foundryvtt/assets/60266988/8c9e84ba-99c9-410a-932a-656511641409)
3. After reloading the page (F5), the override from the status effect will be applied twice until the token actor is changed in any way (e.g. changing the name).
After reload:
![image](https://github.com/foundryvtt/foundryvtt/assets/60266988/3f1f029f-c344-4ab7-95d5-1edabd1cc665)
After renaming:
![image](https://github.com/foundryvtt/foundryvtt/assets/60266988/a5b4ecfd-54b5-492a-ba3e-8f2a1937823a)

### What core version are you reporting this for?

v11 build 305

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl have we seen any reports like this elsewhere? Could this be a system-specific issue of rendering the modified values on the actor sheet and then handling actor sheet submissions which commit those modified values to source?

**Comment by Fyorl** [comment]
> @Fyorl have we seen any reports like this elsewhere? Could this be a system-specific issue of rendering the modified values on the actor sheet and then handling actor sheet submissions which commit those modified values to source?

This is the first report I've seen; it could be as you say. Some investigation will determine for sure though.
