### ISSUE TITLE
Lights with negative luminosity - interaction with basic vision detection mode

### ISSUE THREAD

**Issue by tyrielv** [foundryvtt/foundryvtt#9770]
### User Experience

A light source with negative luminosity will make tokens hard to see / invisible to users, but still detected with sight.

![negative luminosity example](https://github.com/foundryvtt/foundryvtt/assets/6468183/dfeeef87-1d25-4a5f-a737-6346fffc3b19)
The scene darkness is 1.
(1) is a small light source with negative luminosity. It renders as darker than normal darkness.
(2) is an NPC that is incorrectly 'detected with sight' by the player token because of (1).
(3) is an NPC that is correctly 'detected with hearing but not sight' by the player token. (Out of range of (1))
(4) The player token, which does not have darkvision.
This example was created in PF2e system, but I've been informed that the issue goes back to core foundry.
This screenshot was taken in Foundry V10. V11 changes how the 'detected with hearing but not sight' tokens are rendered, but whether the tokens are detected with sight or not appears to be the same.

Ideally a negative luminosity light could override a positive luminosity light for detection like it does for light rendering.

If this behavior was available, it would make for better implementations of features like magical darkness interacting with darkvision.

**Comment by aaclayton** [comment]
Closing since this request is now redundant with the way we are handling improved darkness sources.
