### ISSUE TITLE
Absorb and incorporate the functionality of the unfulfilled-rolls module to provide a core solution to managed and delegated evaluation of dice rolls using external inputs.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9775]
The https://github.com/foundryvtt/unfulfilled-rolls module currently provides this functionality as a temporary stand-in for a permanent core solution. Known current use cases include:

1. GoDice (https://foundryvtt.com/packages/godice)
2. Pixels Dice (https://github.com/foundryvtt/pixels)
3. Manual Rolls (https://foundryvtt.com/packages/df-manual-rolls)

## Related Issues
- https://github.com/foundryvtt/foundryvtt/issues/9090

**Comment by stwlam** [comment]
https://github.com/foundryvtt/foundryvtt/issues/9090 _!!_

**Comment by FloRad** [comment]
Given that the module doesn't currently seem to support blind GM rolls (it still asks for inputs) are there plans to enable some sort of skip/fallback to foundry's rolling in the case a blind roll is called for? Pf2e requires this a lot for things like recalling knowledge or various perception rolls, but that's just one scenario I can think of from the top of my head.

**Comment by stwlam** [comment]
The convention for flesh-realm Pathfinder play is for the GM to make all secret checks: blind-rolling by players is a convenience made possible by Foundry. Were a group playing over Foundry to return to rolling physical dice, I would expect that they also return to the standard convention.

**Comment by FloRad** [comment]
That's fair, but but I'm not sure it's fair to treat a group where where not all people have bluetooth dice (they are quite expensive compared to the free.99 mersenne-twister) like a full table group.

**Comment by aaclayton** [comment]
Regardless of the PF2E-specific convention, I think the feature request still stands that a core implementation of configuring external roll providers should be able to have some extra setting or logic to support falling back to (or forcing) ditial rolls when the roll mode is a blind roll.

This is something that @Fyorl can track as a requirement for the solution we develop.

**Comment by FloRad** [comment]
Another option would be to still take the roll from the die/input/etc but shift it left/right by some amount (say somewhere between `1` and `faces/2`) to determine the actual result. This would allow people to still roll their physical dice without knowing the actual result. The UX of that could be too confusing though.
