### ISSUE TITLE
Control border does not appear under certain token Dimension cases, in hexagonal-grid scenes

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#9790]
### What happened?

In a scene set to any of the Hexagonal grid styles, any tokens with grid space Dimensions of 5 x 5 or higher do not show their control/selection border. Neither does the border show when the Dimensions of the token are non-square — like 1 x 2 or 5 x 3 — regardless of whether either/both is greater than `4`.

All three of these tokens are controlled/selected in this screenshot:
![CleanShot 2023-07-17 at 11 41 53@2x](https://github.com/foundryvtt/foundryvtt/assets/801582/98d6133c-3ccd-4c46-ae12-fe3357b971e4)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Scene set to any hex grid style.
2. Token with dimensions either non-square or greater than 4 x 4.
3. Control token.

### What core version are you reporting this for?

11.305

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Unfortunately the grid borders are not entirely dynamic, we have hard-coded polygon shapes for sizes 0.5, 1, 2, 3, and 4 but don't have a configuration set for size 5. Ideally this would be dynamic rather than hard-coded but that logic is a bit tricky.

**Comment by aaclayton** [comment]
@dev7355608 has this been resolved with V12P1 changes?

**Comment by dev7355608** [comment]
> @dev7355608 has this been resolved with V12P1 changes?

Correct. Wrong milestone. Resolved by #10144.
