### ISSUE TITLE
Convert SceneNavigation to use ApplicationV2

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9792]
## Desired Changes
- Too many scenes caused the top of the UI to be pushed off the screen. Have enough scenes for the scene navigation links to cover the screen all the way to the bottom and beyond. This will cause the UI to be pushed up and the top right toolbar to be unreachable.
- cene navigation bar should indicate if the current scene is pinned to the bar using "Toggle Navigation". Currently, there is no way to tell if the current scene has been pinned to the scene list floating at the top of the screen. Switching scenes has a loading time and finding the scene again after navigating to another scene can be a burden.

## Related Issues
- #4644
- #5508
- #10626

**Comment by Norc** [comment]
For prioritization purposes, this can happen in the wild. Here's an example that occurred today, in this case due to importing 400 CzePeku scenes at once:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/24ce0869-42a5-4721-99a7-1d8bd6c6bf38)

**Comment by Norc** [comment]
Per SpiceKing's testing in 11.315, the breakage shown in this screenshot only occurs after a reload. Before the reload, the UI is more functional still (if overcrowded):
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/638709c9-0dff-4ae7-97a8-f2c8c2c992c6)

**Comment by aaclayton** [comment]
Deprioritization for V12. Out of time.

**Comment by anathemamask** [comment]
Related issues worthy of consideration:
#10626 
#5508
#4644
