### ISSUE TITLE
Replace Yauzl to newer version to account for signature errors 

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/foundryvtt#9802]
### What happened?

FoundryVTT uses the `yauzl` 2.10.0 or above package which has been unmaintained for several years now, and includes buggy behavior that breaks module installation.
![image](https://github.com/foundryvtt/foundryvtt/assets/32039708/b628a685-9d33-438d-8e7f-4c262d4b4df9)

It seems this was encountered [back in 2020](https://discord.com/channels/170995199584108546/513918036919713802/695750148248305804) (Discord Link), but nothing was made of it.

The zips that are causing these errors are simple zip files generated using the `zip` command inside a GitHub Action. I believe its the size of the module that ultimately breaks it.

As the title suggests, [this issue](https://github.com/thejoshwolfe/yauzl/issues/69) now suggests to switch to a maintained `yauzl-promise` package.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

You can privately message me at @vauxs on Discord to get an URL to the content creators module that causes this issue. I am the creator of it.

### What core version are you reporting this for?

11.305

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Something we can consider in V12.
