### ISSUE TITLE
Can no longer override parts of measured templates.

### ISSUE THREAD

**Issue by dmrickey** [foundryvtt/foundryvtt#9808]
### What happened?

I wanted the title to be `stop using #private methods in extensible classes` but I felt the current one is more appropriate - but I'll still drop it here because it might be relevant elsewhere, just not relevant to my specific use case here.

I've got a mod for pf1 where I retrofitted a bunch of templates. Basically I replaced circles/cones with a lot more options. In addition to being placed and/or sized differently than the default templates, I also allow the user to customize the fill color alpha, change the scale/alpha of a fill texture, modify the border in various ways. One of the things that my mod "just does" is to replace the control icon with the used Item's icon. (at least this was the behavior pre v11).

Another example is that some spells in pathfinder "extend from the edge of the token" instead of the center of a token. So I replaced those with a new "circle" that was actually as RoundedRect. So when that was drawn it wasn't even a circle shape any more (essentially it was still a `circle` type but the shape was swapped to a RoundedRect based on the presence of a flag on the document).

There were things I didn't override. For example I didn't touch Rectangles or Lines at all. (rectangles aren't really used by pf1, and lines are already simple enough they don't need much more complexity added in to work within the rules). So extending this base class instead of writing my entire own MeasuredTemplate class made sense.

Now that pf1 has been updated for v11, I'm working on updating my mod. But there are now private methods for things that I previously overrode. Previously I had overridden `refresh` to ensure that "if this was supposed to be RoundedRect, then it sill would be with the extra distance added in based on the token". But now `#refreshShape` exists instead so instead of just overriding `refresh` I now have to override the other method that calls `#refreshShape` because that is still overridable.

Similarly, I was overriding `_drawControlIcon` so I could make sure I'm using the right icon. But that is now `#createControlIcon` so if I want to keep that behavior, then I just have to override `_draw` which is the only place using this private method.

It just seems arbitrary which methods are now private and which ones aren't
![image](https://github.com/foundryvtt/foundryvtt/assets/3664822/efc92ad0-d829-4a1f-a901-fe9bb911d13e)

But basically the existence of these private methods just makes it harder for modules to make their own templates. I know I can essentially copy this entire class and then register my own template, but previously I was able to subclass this, overwrite a few parts, and still register my own template (just with a lot less work on my part).

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

Try to override private methods in a new class.

### What core version are you reporting this for?

v11.305

### Relevant log output

```shell
n/a
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We made a change here https://github.com/foundryvtt/foundryvtt/issues/9101 to add `MeasuredTemplate#_computeShape` as a protected method that your class can override which should allow you to re-frame template data to return a different shape back. 

Our control icon logic is not intended to be specifically overridable since that provides a critical interaction interface that the core software expects to be matched. There are ways you can modify the control icon after it is initially created, however, to do things like change its appearance or add additional functionalities.

**Comment by dmrickey** [comment]
I'm not sure I follow the logic behind parts of the control method being locked down. I can replace the one `_draw` method calling `#createControlIcon` and simply not call it (or call my modification that I would have replaced `#createControlIcon` with). 

Alternatively, I can replace the entire template class via setting `CONFIG.MeasuredTemplate.objectClass` to something else. As long as the public contracts remain the same the internals don't matter as much. Previously I was extending `MeasuredTemplate` and updating the config reference with my extended class. 

I'm not sure locking down a few private methods actually achieves the overall goal you're aiming for.

That being said, part of the goal for swapping out the icon is to give placement feedback for the local preview. If the template is in a valid location, show the template icon. If it's an invalid location, then show "not allowed" icon. I don't see any way to accomplish this without overriding _draw and having my own `create control icon` logic.
