### ISSUE TITLE
Light priority to control interactions between positive and negative luminosity

### ISSUE THREAD

**Issue by elizeuangelo** [foundryvtt/foundryvtt#9810]
### User Experience

I believe there should be a priority configuration to determine how light sources are rendered on the canvas. This is specially useful for negative/positive luminosity interactions.

Several systems use arbitrary rules to determine wether a light source overcomes another, all of this could be handled by the system or DM with a simple priority configuration.

**Comment by Feu-Secret** [comment]
More accurate issue here : https://github.com/foundryvtt/foundryvtt/issues/10437
