### ISSUE TITLE
Customizable World Logo in Foundry VTT

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#9812]
### User Experience

As a content creator using Foundry VTT for YouTube videos, I would like to request the addition of an option in the administration interface to easily customize the world logo that appears in the top-left corner when a world is opened. Currently, I have to manually replace the logo in the Foundry VTT files after each update, which is time-consuming and requires repetitive tasks.

Having this option would not only save time for content creators but also allow for a more personalized and professional touch to their worlds. It would greatly enhance the user experience and streamline the process of customizing the Foundry VTT interface.

Screenshot
![image](https://github.com/foundryvtt/foundryvtt/assets/4999783/b59bc217-0143-4623-bb4d-3c96eac49677)

Thank you for considering this feature request, and I look forward to its implementation in future updates.

Best regards,

**Comment by aaclayton** [comment]
I'm sorry, but I don't think we will make this UI element customizable in this way. Modules and systems can change it programmatically, and you could maintain your own module or world script to automatically change it that would be resilient to software updates. This is our product branding though and we do want the default experience with Foundry Virtual Tabletop to have the product logo present.
