### ISSUE TITLE
package warning spam/garbage?

### ISSUE THREAD

**Issue by derekbarnett** [foundryvtt/foundryvtt#9815]
### What happened?

I upgraded my foundry instance to v11 306 and the ubuntu box (22.04) it lives on last evening. I now have 793 package warnings, the vast majority of which are "The module "foo" has a requires relationship on a non-module, which is not supported." Without sifting through them all with a fine toothed comb, I can say that the vast majority of these are for modules (and at least one system, laf) that I do not have installed. 

One of the modules that it is giving me a warning for is downtime-ethck. I may have easily missed something, but I don't even see that it requires anything when I searched through its github. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open the setup page, look at package warnings.

### What core version are you reporting this for?

version 11 build 306

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by derekbarnett** [comment]
Here are the relevant log entries.
[complaint.log](https://github.com/foundryvtt/foundryvtt/files/12129945/complaint.log)

**Comment by Fyorl** [comment]
Duplicate of #9811
