### ISSUE TITLE
Better accommodate the Light Animation Types that require a non-zero Light Color to display

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#9819]
### User Experience

When editing a new ambient light with the core default settings, half of the Light Animation Type presets appear to do nothing at all when assigned. This is because the default Light Color is `#000000`, which needs to be non-zero for those animations to display.

Suggest at minimum a `hint` be added to the Light Animation Type control, explaining this requirement. Or perhaps the default Light Color could be `#111111` or similar, which seems to be roughly the threshold at which those animations will all display. Or some other way of addressing the behaviour, which appears "broken" out of the gate.

These are the animations that require a non-zero Color:

- Chroma
- Energy Field
- Force Grid
- Hexa Dome
- Light Dome
- Mysterious Emanation
- Radial Rainbow
- Revolving Light
- Star Light
- Swirling Fog
- Swirling Rainbow
- Vortex

**Comment by thre-z** [comment]
Hoping there's still time in the v12 cycle for this one to be completed. A nice little user experience improvement.
