### ISSUE TITLE
Provide a public API for custom roll functions

### ISSUE THREAD

**Issue by teroparvinen** [foundryvtt/foundryvtt#9820]
### User Experience

At the moment, there is no API for extending the set of functions available to roll formulas. Rolls expose the methods of the javascript `Math` object, so it is possible to hack this like my module Logic Rolls does: https://github.com/teroparvinen/foundry-logic-rolls/blob/main/module/logic-rolls.js

It would be nice to have a set API for providing this functionality without resorting to extending `Math`.

Note: There is a separate issue #8692 requesting adding the functionality of Logic Rolls to core, this issue is about providing an interface for general use (that would be useful in that specific module as well).

**Comment by aaclayton** [comment]
*Hopefully* this is something we can address in V12 as part of our adoption of Peggy parsing which could allow for the set of known functions to be extended as part of the grammar definition.

**Comment by Fyorl** [comment]
Custom functions may now be registered in `CONFIG.Dice.functions`, and will be called if they appear in roll expressions, taking precedence over `Math` functions.
