### ISSUE TITLE
Allow roll formula functions to operate on non-numeric intermediate values

### ISSUE THREAD

**Issue by teroparvinen** [foundryvtt/foundryvtt#9821]
### User Experience

Sometimes roll formulas can be a huge help in applying/activating abilities and spell effects that have niche limitations that are central to the flavor of the ability. I will mention two examples and how my module Whistler's Item Rolls Extended handles them (the implementation is for dnd5e).

The cantrip Chill Touch specifies "If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn". This is modelled by applying an effect with the active effect key of `flags.wire.disadvantage.attack.all` with a value of `and(@originator.isDefender, eq(@attacker.details.type.value, "undead"))`, which will lead to the disadvantage being applied only if the attacker is undead and the defender is the actor who cast the spell that created the active effect.

The Faerie Fire spell states "Any attack roll against an affected creature or object has advantage if the attacker can see it". This is implemented by assuming that any actor who is not immune to being blinded can see. Regardless of the validity of that assumption, it is implemented using an active effect effect key `flags.wire.grants.advantage.attack.all` with a value of `not(includes(@attacker.traits.ci.value, "blinded"))`. This formula checks if the attacker condition immunity array includes the specified value.

In the examples, the `eq` function needs to operate on strings and the `includes` function needs to operate on an array and a string. WIRE patches some of the `Roll` class methods to strip the numericality checks and pull this off: https://github.com/teroparvinen/foundry-wire/blob/main/module/logic-rolls.js.

It would probably be best to do numeric validation for the final result value of the entire roll formula, but not the intermediate steps.

This implementation is very reliant on the internals of the `Roll` class and the proposed V12 roll changes could potentially invalidate the functionality entirely. So it would be nice to get something like this considered when implementing the new roll parsing functionality.

**Comment by teroparvinen** [comment]
Related to #9820

**Comment by aaclayton** [comment]
This may be something we can address as part of the v12 work on improving roll parsing and evaluation logic using Peggy.
