### ISSUE TITLE
Package warnings of a module that failed to install because of an invalid manifest remain until the server is restarted

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9825]
Originally reported by tuxagon: https://discord.com/channels/170995199584108546/1065764070680186930/1131499534502088704

**ALL MODULES DISABLED?** false
**OS, Hosting, Browser (if applicable)**: Linux, self-hosted
**Short Description of bug**: Modules that have a critical manifest error require a Foundry reload to clear. Primarily UX related and the workaround is to restart the instance.
**Simple steps to reproduce the bug**: Here is a Discord chat about a detailed reproduction from <#1111088928032837712> https://discord.com/channels/170995199584108546/1111088928032837712/1131483855430361141

I'll summarize the high-level here: 

1. Basically, choose a package that has an invalid manifest. I discovered it with `graham-plowmans-music-pack`.
2. Try installing it, which should result in a critical error saying the manifest isn't valid
3. Refresh and you should see the warnings, but there won't be a folder tied to that package
4. Log out and they'll still be there when you log back in.

**Workaround**: Restart Foundry to clear them out since there is no folder for it to recreate the warnings from.

---

Comment by unsoluble:

To add onto that a bit: It's not the critical error from the failed install that gets logged to `game.data.packageWarnings`, but any incidental *warnings* that would have accompanied that package (due to other issues with its manifest) had it been successfully installed. But it failed the install, so these warnings shouldn't be logged.

**Comment by aaclayton** [comment]
Potentially related to #9811
