### ISSUE TITLE
Scrolling Status Text animations should be suppressed when the triggering token is toggled hidden

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#9833]
### What happened?

Scrolling Status Text animations are visible to all players with line of sight to the token, even if the token has been toggled hidden with the Toggle Visibility State control. The text animations ought to be suppressed in that case.

This behaviour is present in both 10.303 and 11.306.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Be in a game system that supports Scrolling Status Text
2. Enable Scrolling Status Text
3. Put a token within a Player's vision polygon
4. Toggle Visibility State on the token, making it hidden from the Player
5. Change a value on the token that triggers a Scrolling Status Text animation
6. View from the Player's login that the text animation is visible

### What core version are you reporting this for?

11.306, 10.303

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
This is a dnd5e system issue. 
@unsoluble Would you create this issue on the system issue repo?
@Fyorl Tagging you for this one.

![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/674c0c9e-613d-475c-af93-7a0005ec1c6a)

**Comment by unsoluble** [comment]
Feel like this should be handled at the core level, no? But sure, will ticket over there.

**Comment by Feu-Secret** [comment]
> Feel like this should be handled at the core level, no? But sure, will ticket over there.

This is a system specific method with a call to our generic `createScrollingText` API. This is the responsability of the caller to trigger the API or not, which has absolutely no data informations about any placeables. 😃
