### ISSUE TITLE
Proposal: Provide a limited means to interact with token animated movement

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9853]
### User Experience

Related: 
#5533 
#9787 

In limited scenarios, one might want to interact with a token that is being moved via `token.animate()`. For some animations, you could do that by pulling the animation from `CanvasAnimation.animations`. But for animated token movement, this is a very problematic workflow because there is no delta provided for the movement properties so it is very difficult to determine the rate of change. It is also difficult to get access to the `ontick` function that is passed as a parameter to `CanvasAnimation.animate`.

## Why does this matter?

In some limited scenarios, stopping or adjusting tokens as they move is necessary. By movement, I mean mostly changes to position, rotation, and elevation. Scenarios include:
- Syncing token movement with something else. Moving tokens in formation, moving tokens with templates, etc.
- Adjusting other properties. For example, my Elevated Vision module adjusts elevation as a token moves across designated terrain that changes elevation.
- Pausing or stopping token movement. Yes, you can see the path the token is taking using `preUpdate` and `update` hooks. But if you want to pause a token at a specific spot along its movement, you really need to interact with the movement animation.
- Tracking a property that may result in a pause or stop to token movement. For example, counting difficult terrain or requiring a GM or user check after encountering X of something.

## Proposal
1. Provide a means for modules or systems to add (or add to) the `ontick` function.

`CanvasAnimation.animate` has an optional `ontick` parameter, which is called each animation frame. And `Token.prototype._onUpdate` calls the `preUpdate` sequence and, through that, the `preUpdate` hook. Also in  `Token.prototype._onUpdate`, it sets `animationConfig = (options.animation  ||= {});` before starting the animation. 

But currently, you cannot set `options.animation` in the `preUpdate` hook, because the `options` parameter does not get passed back to the `options` variable in `Token.prototype.animate`. (It appears to be stripped out in `#preUpdateDocumentArray`). (This may be a bug, because it sure looks like `Token.prototype._onUpdate` expects the options to sometimes include `animation.ontick` and expects it could be added by the call to `super._onUpdate(data, options, userId)`.

So one approach would be to pass through the `options` parameter from the `preUpdate` hook to `Token.prototype.animate`, which in turn could then define the animation with provided parameters accordingly. Another approach would be to set up a distinct hook or some other means to allow one to pass through an `ontick` function.

2. Provide a means to discern the delta of the change in the animation ticks.

Right now, it is easy to tell where the token is and its current properties along the animation, but extremely difficult to discern what movement was covered since the previous animation tick. This is particularly critical for syncing movement of objects or if you are tracking some value—like movement cost—that is important to timing a token pause. 

My tentative recommendation here would be to store the previous update data object from the prior animation step and provide it as an argument to `ontick`. This, of course, could be undefined for the first animation step. This would allow the `ontick` function to handle any delta calculations as needed.

**Comment by aaclayton** [comment]
I'm not really sure about this proposal, or necessarily the motivating use cases for it:

> Syncing` token movement with something else. Moving tokens in formation, moving tokens with templates, etc.

Perhaps better handled with a refresh hook watching a specific render flag.

> Adjusting other properties. For example, my Elevated Vision module adjusts elevation as a token moves across designated terrain that changes elevation.

Would this be a database update? (presumably not) or a local override? 

> Pausing or stopping token movement. Yes, you can see the path the token is taking using preUpdate and update hooks. But if you want to pause a token at a specific spot along its movement, you really need to interact with the movement animation. Tracking a property that may result in a pause or stop to token movement. For example, counting difficult terrain or requiring a GM or user check after encountering X of something.

Token animation could be canceled from the Token `refresh` hook.

I'm not fundamentally opposed to the idea of improving the animation API, but this proposal doesn't strike me as a very elegant way to go about it. More brainstorming is required.

**Comment by caewok** [comment]
In response to your question about adjusting elevation: I would expect all changes done during animation to be local, with any database updates happening either through the update hooks or at the end/break in the animation. 

To me, the `ontick` function looks like the intended method to adjust additional properties, etc. during an animation call. Yes, you could probably accomplish this in a refresh hook if you try hard enough, but refresh is called for all sorts of reasons, so you end up putting quite a bit of logic in the refresh hook to pull out when the token is being refreshed due to animation. So I don't love the refresh hook for this approach. 

Ultimately, I don't have a strong preference as to the how. What I care about is that you currently cannot see the previous data for a given animation step, making it difficult to discern deltas. And there is no clear way to execute some test within the token animation as seems to be envisioned by the `ontick` parameter. Totally agree that there is not one obvious path forward here.

**Comment by mclemente** [comment]
Just chiming in with https://github.com/foundryvtt/foundryvtt/issues/8477#issuecomment-1605290478 and another use case where this would be important:

My module (About Face) applies a rotation during movement based on the direction the token moved, so when `Token.prototype.animate` runs, it will add a duration of ~250-500 (assuming a 90-180 degrees rotation).

The thing is, movement is super fast compared to that. If I were to move a token 10 squares in a 100px grid size canvas, the animation duration would be 16 (horizontal/vertical) or 23 (diagonal). And that's assuming 10 squares which is a lot on most games, just moving a single square is a duration of 1.6.

So, moving a token goes from 1.6ms to 250ms (156 times slower) just because there's a rotation in-between. And that's assuming it's a rotation, mirroring would turn it into a 1000ms movement.

My best option is to either ignore the whole movement, where a token will just teleport to the next position, which is far from ideal.

My second option is to wrap `Token.prototype.animate` and check if there's both dx/dy movement with rotation and ignore the rotation.

So, I'd really enjoy if this proposal were implemented.

**Comment by Feu-Secret** [comment]
We have enhanced the token animation framework for improved developer usability. It now includes an animation context that addresses the concerns raised in this GitHub issue.
See: https://github.com/foundryvtt/foundryvtt/issues/9787
