### ISSUE TITLE
Consider permitting `hidden` attributes to be present in HTML elements

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9857]
### User Experience

Currently, the [`hidden` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) is stripped from any HTML element:

![image](https://github.com/foundryvtt/pf2e/assets/106829671/10c09b4f-178a-41d2-8637-7e2b5fdfa3d0)

I'm not aware of any security concerns with this attribute, and it has its innate semantic significance (as opposed to a `hidden` class) in its favor.

**Comment by aaclayton** [comment]
@Fyorl what are your thoughts on adding this to our allowed element attributes list? On one hand it is harmless (I think). On the other hand it seems strange to save HTML content to the database with `hidden` elements. This feels more like something that would be managed client-side by an application that operates on that HTML.
