### ISSUE TITLE
Trusted Player Compendium Permissions

### ISSUE THREAD

**Issue by webmaster94** [foundryvtt/foundryvtt#9860]
### What happened?

It appears that Trusted Players do not receive the default "Observer" permission that regular Players do. This appears to be in an issue in both Foundry V10 and V11. Can confirm this is an issue in V11 Build 306. I can confirm this does not appear to be an issue in Version 10 Build 291. I did have issues with past builds of V10 where players could not read content that was linked to a compendium either in journal entries or via the D&D advancement workflow. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

You can see that by default, a newly created compendium receives permissions as below: 

![image](https://github.com/foundryvtt/foundryvtt/assets/85364225/d9aa4f25-a121-430d-8183-6f0cdb6fffac)

### What core version are you reporting this for?

Version 11 Build 306

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I might be misunderstanding the issue, but this *sounds* like a bug that we should address? Tentatively scoping to V11 maintenance.

**Comment by Fyorl** [comment]
I don't think this is a bug, just confusing UI. Blank values in compendium ownership inherit from any role beneath them. So here the Trusted Player role inherits the Observer ownership from the Player role below it. When I tested it, I confirmed that behaviour is still working correctly.
