### ISSUE TITLE
Cannot add multiple actors to combat at once

### ISSUE THREAD

**Issue by sesopenko** [foundryvtt/foundryvtt#9865]
### What happened?

In Foundry v10 I could select multiple actors on the map at once, right click, and click Add to Combat and it would add them all at once.  In foundry v11 I can only add one of them.

This was experienced in Foundry v11.306 for Linux on Ubuntu 22.04, when using Firefox for Windows as the browser.

I had to roll-back my foundry server from backups to v10 due to other issues which weren't allowing us to play, so I don't have log entries and can't go through the process of reproducing this again for now.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Install Foundry V11.306
Use the Pathfinder 2nd edition module, updated to the latest version
Add multiple entities, ie: kobolds

Select all of them by dragging a box over all of the entities on the map
Right click one of the entities
Click Add to Combat in the lower right next to the entity's icon

Expected results:

Should add all selected entities to combat

Actual results:

Only one of them is added

### What core version are you reporting this for?

Version 11 Release Build 306

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
In case this was a pf2e system issue, I tried reproducing:

https://github.com/foundryvtt/foundryvtt/assets/106829671/64d89c34-f608-4db2-8599-d219d817f9a9

**Comment by Fyorl** [comment]
Closing as nonrepro
