### ISSUE TITLE
Intigrate the functions of Perfect visions

### ISSUE THREAD

**Issue by Zarhog** [foundryvtt/foundryvtt#9879]
### User Experience

perfect vision offers many needed functions to the canvas, and they seem reluctant to upate it due to changes to V12, it would be nice to see this become core as the features are unilatitly usfull in all systems, and there for agnostic.
https://github.com/dev7355608/perfect-vision

**Comment by aaclayton** [comment]
We agree! We hired @dev7355608, the author of Perfect Vision, who works directly with us now. Many of the features of this module will be evolving and changing as we merge them (piece by piece) into the core software.
