### ISSUE TITLE
Using ctrl-S in editor can open browser save dialog

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#9882]
### What happened?

Whilst editing in the journal editor, if an auto-save ever occurs then pressing CTRL-S will open the browser's save dialog.

The Ctrl-S should always be consumed by the editor.

Note that ctrl-S while editing a journal/item title also open the browser's dialog, rather than just saving the new journal/item name.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open an existing journal page for editing.
Make some changes - wait for the auto-save to occur (or click elsewhere in the same page to immediately trigger a save).
Then press Ctrl-S and see the chrome browser's save dialog open.

### What core version are you reporting this for?

11.306

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by farling42** [comment]
It looks like #7528 hasn't been merged into V11.

**Comment by farling42** [comment]
Pressing ctrl-S in the HTML editor always opens the browser's save dialog.

**Comment by aaclayton** [comment]
@Fyorl is this one an easy fix?

**Comment by Fyorl** [comment]
I think the issue is that the auto-save is causing a re-render and the actual editor body is losing focus. Probably not too difficult to fix using the same logic we use to retain focus on form inputs.

**Comment by farling42** [comment]
I found it also happened frequently if I pressed ctrl-S shortly after opening a journal page.
