### ISSUE TITLE
Opinionated UserConfig UX Improvements

### ISSUE THREAD

**Issue by mouse0270** [foundryvtt/foundryvtt#9892]
### User Experience

Hello, not really sure what the title should be, but I'd like to make some suggestions to the UserConfig menu to improve the UX in my personal opinion.

One of my first suggestions would be to display an icon, to indicate to the user if they have `ownership` or `observer` rights to the actor in question. 

The second suggestion would be to sort the actors by this, showing actors they own first, and then actors they can view.

Lastly, I think it would be nice that if the user has only one actor in which they have ownership over, the UI preselects that actor for them. **Edit** This option would have to let the user unselect the actor by clicking on the selected actor a second time. Basically, turning it into a toggle.

Here is an example of the UI that I quickly prototyped.
![image](https://github.com/foundryvtt/foundryvtt/assets/564874/ecdf5cc1-7bf0-467d-8965-657fcde1adeb)

**Comment by aaclayton** [comment]
Nice suggestions, I agree these are improvements.

**Comment by aaclayton** [comment]
I'll take this on once we are outside of the dev phase since the user config app has been updated to ApplicationV2.

**Comment by aaclayton** [comment]
The revised character select dropdown organizes choices in optgroups for "Owner" vs "Observer". Actors within each group are alphabetically sorted.

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/2403dc9b-3226-4c85-a687-eac2bebba313)

**Comment by mouse0270** [comment]
I really do enjoy the concept you have implemented, however, I appear to have a few issues. 

For example, in your image above the UI looks very good, however I am using `Foundry v12.318` and D&D `3.1.2` and my UI looks like this:

![image](https://github.com/foundryvtt/foundryvtt/assets/564874/419d4d73-0265-4039-b3ec-bfc6673b6ac0)

1. The Transparent background (unlike the one in your image) makes the text very hard to read in my opinion.
2. As a GM with no Ownership / Observer rights specifically set I am not seeing those groupings. (Not a real issue, just thought I would point that out). I would expect that GM would see users under something like Owner as I believe the GM owns all actors?
3. As a GM, I don't appear to have anyone to select no actor, as it appears I can do in your example above.

**Comment by aaclayton** [comment]
@mouse0270 the changes I mentioned in my previous comment have not released yet...
