### ISSUE TITLE
Batch fromUuid calls in enrichHTML to retrieve multiple documents from a compendium at once rather than one-at-a-time

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#9893]
### User Experience

When a journal entry contains a few links to entries in compendiums, the page takes a significant amount of time to display.

Looking at the code, the enrichHtml function is calling fromUuid which reads an entire record from the LevelDB, when all(?) the data to generate the link is available in the metdata in the compendium's index.

The request is to change the logic in the enrichHtml function to only use the compendium's metadata index when creating links, rather than using fromUuid.

The check for compendium should be quite simple since the start of the uuid will be the string "Compendium."

**Comment by mrkwnzl** [comment]
For context, here’s a discussion about that on the Discord server starting with this post: https://discord.com/channels/170995199584108546/1065764029278212230/1137105424580087848

**Comment by aaclayton** [comment]
I'll tentatively scope this as a v11 bug, but we might need to re-frame it as a v12 feature change depending on how significant the change would be.

**Comment by farling42** [comment]
In theory, it should only require reworking `static _createContentLink` to not call fromUuid(sync) for compendiums.

**Comment by Fyorl** [comment]
> Although I just realised that most of my links are to PAGES within a journal, rather than to a journal itself, and the pages aren't stored in the compendiums index :-(

Yes, this is the reason it works the way it does: We cannot resolve a link to an embedded document inside a compendium by using only the compendium index. There are some optimisations we can make here, but this behaviour is very much intentional and not a bug.

**Comment by aaclayton** [comment]
Good clarification. We could consider using `parseUuid` to identify whether the link is able to be constructed without loading the document. I would think that we could construct a link synchronously if it:

1. Is a document within the world.
2. Is a primary document of a compendium and therefore indexed.
3. If it is an embedded document of a compendium but the link is fully-formed (i.e. with a text label)

We could view `fromUuid` as a last resort method with a bit of additional work.

**Comment by Fyorl** [comment]
> We could view `fromUuid` as a last resort method with a bit of additional work.

I don't think `fromUuid` should be the last resort. We want a full Document instance if at all possible so that we can call `toAnchor` on it in order to generate the content link. `ClientDocument#toAnchor` should be the canonical way to generate a content link, and using the minimal compendium index data should be reserved as a legacy fallback only for when `enrichHTML` is called with `async: false`.

**Comment by stwlam** [comment]
Perhaps there could be a smart `fromUuids` helper that gets everything it can synchronously from world collections/compendium caches and then makes a single call to `CompendiumCollection#getDocuments` with all the cache misses.
