### ISSUE TITLE
Bug: Root SRD folder keeps being created after duplication or deletion.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/foundryvtt#9902]
I moved all the SRD stuff into a seperate folder along with module stuff because I dont really use it at all. With 2.3, the folder is created as a new root folder in my world, and when I move it- it gets remade upon world launch. I've tried a suggestion by:

In the system.json - Deleting line 166, removing the comma on line 165, and adding the space after folders like MaxPat asked, but it still ends up making a new one.

**Comment by GambetTV** [comment]
Strangely the bug doesn't seem to kick in on brand new worlds, only existing ones.

**Comment by hjk321** [comment]
> Strangely the bug doesn't seem to kick in on brand new worlds, only existing ones.

My brand new test world on a fresh install of foundry is experiencing the bug.
