### ISSUE TITLE
Tile Browser's Asset Grid Size value resets whenever Display Mode view is changed.

### ISSUE THREAD

**Issue by Dumbhuman** [foundryvtt/foundryvtt#9908]
### What happened?

On a scene with a Grid Size of 100px, I opened the Tile Brower and entered a value of 200 in the Asset Grid Size field.  Then I switched from the default Tiles View to List View and noticed that the value of 200 I entered previously had reset back to the default 100.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open the Tile Browser in any scene.
2. Change the default value in the Asset Grid Size field.
3. Click any one of the inactive view buttons for Display Mode.
4. Observe that the previously changed value in Asset Grid Size resets to the default value.

### What core version are you reporting this for?

Version 11 Stable, Build 307

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by GameMaker** [comment]
This still seems to be happening in V11 build 315?

**Comment by aaclayton** [comment]
> This still seems to be happening in V11 build 315?

I'm not able to reproduce the problem. Changing the `Asset Grid Size` and subsequently changing the `Display Mode` retains the new asset grid size. @GameMaker can you please provide more in-depth reproduction steps?

**Comment by GameMaker** [comment]
You bet - here's a video of it happening, plus screenshots of my active modules - sorry, most are from the Cze and Peku patreon. :)

I was able to repro it with all modules turned off except The Forge, which is required, obvs.

[DemoOfGridSizeBug.zip](https://github.com/foundryvtt/foundryvtt/files/14504270/DemoOfGridSizeBug.zip)
<img width="505" alt="2024-03-05 19_25_33-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/6f1e2b9e-81c7-40a8-a7f2-0ed98629c4d6">
<img width="507" alt="2024-03-05 19_25_27-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/b4d4d5ef-dc9e-4d84-aada-aaf2452a15d7">
<img width="501" alt="2024-03-05 19_25_17-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/caa31254-fe45-409f-8f37-9ca9ba679ef1">
<img width="505" alt="2024-03-05 19_25_09-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/bc017b5b-abca-421d-8c0a-1d22d9d89f6e">
<img width="504" alt="2024-03-05 19_25_03-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/4e35a781-9413-42df-a669-4613fd91370e">
<img width="501" alt="2024-03-05 19_24_55-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/6f81f4f7-3e5a-4ff1-a8ec-4e1038bbac0d">
<img width="511" alt="2024-03-05 19_24_46-Foundry Virtual Tabletop — Mozilla Firefox" src="https://github.com/foundryvtt/foundryvtt/assets/1099635/888145dd-73fd-471e-8334-dae203f31a26">

**Comment by aaclayton** [comment]
Thanks for the video. I am not able to reproduce it. The Forge does make some overrides to the way that the file picker and file browser works. My best hypothesis is that this is a Forge-specific issue. I suggest perhaps bringing this up on their support discord and inquiring about whether that may be the case. Feel free to link to this issue.

If you believe it not to be a Forge-specific issue, perhaps you could find a reproduction path in a self-hosted Foundry VTT environment?

**Comment by GameMaker** [comment]
Yup, good call. Reinstalled locally and confirmed it did not repro. I'll mention it to the Forge team. Thanks, sorry for the blip.
