### ISSUE TITLE
[BUG] When hover a note the mouse interaction state is 0 not 1

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/foundryvtt#9919]
### What happened?

Previously with v10 I had this check on checking a note when I hovered with the mouse pointer:

```javascript
Hooks.on("hoverNote", (note, hovered) => {
  // If the note is hovered by the mouse cursor (not via alt/option)
  if (hovered && note.mouseInteractionManager.state == 1) {
    // DO SOMETHING
  }
});
```

this check now fail because the `note.mouseInteractionManager.state == 0`, but if i check the states object i see for the HOVER state should be 1.

```
note.mouseInteractionManager.states = {
    "NONE": 0,
    "HOVER": 1,
    "CLICKED": 2,
    "DRAG": 3,
    "DROP": 4
}
```

it is a bug or a wanted thing ?

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Core Version: 11.307
System: dnd5e 2.3.0 (Atropos) 

1) Create a note on the canvas
2) Prepare a javascript with the hook `hoverNote`
3) Hover the note with the mouse pointer
4) Check in debug the value of  `note.mouseInteractionManager.state` it should be 1 not 0

### What core version are you reporting this for?

Version 11.307

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by p4535992** [comment]
Possibly connected to https://github.com/foundryvtt/foundryvtt/issues/9940 and https://github.com/foundryvtt/foundryvtt/issues/9935

**Comment by aaclayton** [comment]
@dev7355608 I'm not sure whether this remains an issue after the changes we made to mouse interaction and hover state management. Could you take a quick look and identify whether further changes are needed here?
