### ISSUE TITLE
Chat log stops loading earlier messages past a certain point

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9923]
Originally reported by wiseturtle99 https://discord.com/channels/170995199584108546/1065764070680186930/1140068797500379136

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Any
**Short Description of bug**: Chat log will stop loading messages after roughly 104 messages
**Simple steps to reproduce the bug**: Send Over 104 messages in the chat, shut down the server, and reopen it. Scroll up to find the first message sent, and it will stop after 104 messages
**Screenshots and/or console errors**: Video of trying to scroll to the top, and log of what is the first message in the chat log when downloaded

https://github.com/foundryvtt/foundryvtt/assets/207433/42e37758-bbe8-4408-bf40-4e9f71bdce97

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/3d96e764-f44a-4bf2-a58a-02a0787a8ec4)

**Comment by stwlam** [comment]
The current expression for getting the scroll `pct` is `(log.scrollTop + log.clientHeight) / log.scrollHeight`. A `pct` between 0 and 1 seems better obtainable with `log.scrollTop / (log.scrollHeight - log.clientHeight)`.
