### ISSUE TITLE
Greater than and less than characters not allowed in chat

### ISSUE THREAD

**Issue by cahudson94** [foundryvtt/foundryvtt#9926]
### What happened?

When attempting to user certain characters in the chat window they are refused with an error message of "Cannot read properties of undefined (reading '0')"

Expected behavior
The greater than and less than characters should be aloud in regular chat and I am not positive this issue is limited to those two, but that is as far as my testing has found so far.

Browser Info (please complete the following information):

    Browsers tested include both Chrome and Firefox
    Versions: Chrome - 115.0.5790.171, Firefox - 116.0.2
    The above message is reflected both in the UI and the dev tools

Additional context
This is new behavior since an update from Version 10 to 11.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [x] Safari
- [ ] Other

### Reproduction Steps

Go to 'Chat Messages'
Click on 'The chat input box'
Type a message including a character such as "<" or ">"
Submit message to see error

### What core version are you reporting this for?

Version 11 (build 307)

### Relevant log output

```shell
Cannot read properties of undefined (reading '0')
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I'm not able to reproduce this. Did you upgrade to v11 via the in-app update, or by downloading a fresh installer from the website?
