### ISSUE TITLE
Add event parameter to macro execution

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9927]
### User Experience

This is mostly for macro content links so the macro can have the click event for details.

I've now for years been using `event` in macros thinking it was one of the parameters, but it's not. As such I'd like the triggering click event to be passed to content link macros to make these continue to work as expected in the future, and perhaps pass event=null otherwise.

The use of `event` has been integral part of a lot of my macros for finding the chat message they're attached to for example.

**Comment by krbz999** [comment]
This simple addition would be a nice qol change.

```diff
_onClickDocumentLink(event) {
-  return this.execute();
+  return this.execute({event});
}
```
