### ISSUE TITLE
Initialize `Canvas#mousePosition` at construction to prevent rare edge cases when `mousePosition` is retrieved before the first canvas mouse move.

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9935]
### What happened?

I noticed this while running two clients simultaneously to troubleshoot some other issue. I'm not sure if more-common user activity is vulnerable.

```js
  #forceCheckHover() {
    if ( this.hover ) return;

    // Get mouse position and check the token bounds
    const mousePos = canvas.mousePosition;                       // undefined
    if ( !this.bounds.contains(mousePos.x, mousePos.y) ) return; // 💥

    // If inside the bounds, emulate an onHoverIn event and set manually the interaction manager
    this._onHoverIn(new PIXI.FederatedEvent("pointerover"), {hoverOutOthers: true});
    this.mouseInteractionManager.state = MouseInteractionManager.INTERACTION_STATES.HOVER;
  }
  ```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. View the same scene from a pair of clients (I had the Electron client and Chrome going), refraining from moving one's mouse over one of the clients.
2. Move a token in the other client.
3. An error will be thrown in the first.

### What core version are you reporting this for?

11.307

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')
    at #forceCheckHover (foundry.js:55997:41)
    at _TokenPF2e.animate (foundry.js:55438:44)
    at async _TokenPF2e.animate (object.ts:341:15)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by p4535992** [comment]
Possibly connected to https://github.com/foundryvtt/foundryvtt/issues/9919 and https://github.com/foundryvtt/foundryvtt/issues/9940
