### ISSUE TITLE
Server side `TypeError` updating scenes with token with an empty delta diff

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#9938]
### What happened?

We have a script to update the URL of assets within the world to make it easy to migrate from remote hosted assets to locally hosted assets. As part of this, we update the scene data with an updated version of that scene's data.

This can sometimes lead to unexpected behaviour when embedded fields are `null`, which leads to a `TypeError` being thrown from `data.mjs`.

![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/0420dc7e-51a6-48e5-90ab-a7f84a12e1be)
I've been able to reproduce this in `node` and in the Foundry Electron client.

The API docs implies that the `changes` field is optional, but maybe it isn't properly defaulting. Please do close this if it is a non-issue. Thanks for reading!

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Update a scene with tokens with `null` deltas.

### What core version are you reporting this for?

Version 11.307

### Relevant log output

```shell
{"level":"error","message":"Cannot convert undefined or null to object","stack":"TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at ActorDelta.updateSource (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:394:17)\n    at #updateField (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:476:39)\n    at #updateData (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:446:24)\n    at Token.updateSource (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:402:28)\n    at EmbeddedCollection._createOrUpdate (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/embedded-collection.mjs:255:28)\n    at EmbeddedCollection.update (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/embedded-collection.mjs:233:12)\n    at #updateField (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:470:31)\n    at #updateData (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:446:24)\n    at Scene.updateSource (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:402:28)","timestamp":"2023-08-19 12:05:18"}
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Note that the resolution here prevents an error being thrown but does not truncate the ActorDelta. There is some associated tech debt here: #10131
