### ISSUE TITLE
Check for existence of `PlaceableObject#mouseInteractionManager` in `PlaceableObject#interactionState`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9940]
### What happened?

In `PlaceableObject.prototype.interactionState`, it should probably check for whether `mouseInteractionManager` is null, as that is the default value of that property. I managed to trip this error when debugging one of my modules, so I am not sure if it would be triggered in default Foundry. But it is at least theoretically possible.

Currently:
```js
  get interactionState() {
    return this._original?.mouseInteractionManager?.state ?? this.mouseInteractionManager.state;
  }
```

Change to:
```js
  get interactionState() {
    return this._original?.mouseInteractionManager?.state ?? this.mouseInteractionManager?.state;
  }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Unknown. See above.

### What core version are you reporting this for?

v11.307

### Relevant log output

```shell
foundry.js:28145 Uncaught TypeError: Cannot read properties of null (reading 'state')
    at get interactionState [as interactionState] (foundry.js:28145:91)
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by p4535992** [comment]
Possibly connected to this: https://github.com/foundryvtt/foundryvtt/issues/9919
