### ISSUE TITLE
Cannot click on Document ID/UUID clipboard helper if name is too long

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9946]
Originally reported by bithir https://discord.com/channels/170995199584108546/1065764070680186930/1141814637764038807

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Linux, Google Chrome (but do not think it is applicable)
**Short Description of bug**: You can't click the icon for folder id if the folder name is too long.
**Simple steps to reproduce the bug**: Name a folder "This is a really long folder name", right click on the folder and try to click on the icon for the folder id.
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/de6b2716-f2c9-4eb1-ab87-8837fa8991be)

**Comment by Fyorl** [comment]
I suspect this would be an issue with any Document sheet, but the Folder config just happens to be quite narrow.

**Comment by Fyorl** [comment]
Moving this to App v2.

**Comment by aaclayton** [comment]
This is resolved by ApplicationV2 which always reserves sufficient space for this button.
