### ISSUE TITLE
`ClockwiseSweepPolygon` can be self-intersecting

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#9953]
The rounding of internal edge collision points in `ClockwiseSweep._getInternalEdgeCollision` can produce self-intersections, which can break the triangulation and Weiler-Atherton clipping.

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/969078fd-5683-44ec-9fc5-b7ad4db02a3a)

[fvtt-Scene-clockwisesweeppolygon-bug-ILliaF3KAqYFKdBh.zip](https://github.com/foundryvtt/foundryvtt/files/12430892/fvtt-Scene-clockwisesweeppolygon-bug-ILliaF3KAqYFKdBh.zip)

## Possibly Related Issue
```js
CONFIG.Canvas.polygonBackends.sight.create({x: 3516, y: 4277}, { type: "sight" }).visualize()
```

[fvtt-Scene-clockwisesweeppolygon-bug-AVISfGBXmLexULqs.zip](https://github.com/foundryvtt/foundryvtt/files/11870360/fvtt-Scene-clockwisesweeppolygon-bug-AVISfGBXmLexULqs.zip)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/d73d7540-80aa-425c-98ba-89b3a7a2ec7a)

**Comment by aaclayton** [comment]
Going to have to defer this to V13. We are running out of time before stable and this should ideally be done earlier in a cycle so we have ample time to test it.

**Comment by dev7355608** [comment]
Originally reported by zemoloch: https://discord.com/channels/170995199584108546/1184176415139184731/1255152698903494780

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**:  V12.237
**Short Description of bug**: Terrain walls cause seemingly random spots near the Terrain Walls to break. The vision of a token that enters this spot penetrates all walls for a brief moment, causing a flicker and revealing the entire map within the token vision range, even through walls. The problem does not occur when terrain walls are removed.
**Simple steps to reproduce the bug**: Place Terrain Walls surrounded by Basic Walls.
**Screenshots and/or console errors**:
Screenshot 1: Token vision ends at walls as expected.
Screenshot 2: The token moves to the left and the vision flickers through all walls. It reveals the entire Fog of War within vision range, even across walls and rooms, in a circle.
Screenshot 3: Walls.
Scene json includes token on the right of a problematic spot.

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/777c2eae-845c-44c2-bec0-e5f2f7105b9b)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/f9b2d7f2-7844-44c8-a074-0826cbc01f05)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/fd4ddd35-0221-484f-a76c-767f3f0041ce)

[fvtt-Scene-crypt-Rcsln2t4KKOw6tgh.json](https://github.com/user-attachments/files/15973041/fvtt-Scene-crypt-Rcsln2t4KKOw6tgh.json)

---

Additional comment by crovaxon: https://discord.com/channels/170995199584108546/1184176415139184731/1255161672331690059

Addendum to this bug report since I was interacting with Moloch and managed to confirm it.
I suggest setting a white background color on the scene config shared by Moloch to make the fog of war and vision of that token easy to see (and funnily enough will turn the white mystery man SVG invisible :P).

I created a vid demonstrating the flicker and I can identify one key terrain wall group that while it is there, will almost always trigger that flicker. But even removing the marked terrain walls will still very rarely produce a flicker if I keep spamming left and right fairly quickly on that token in the position that Moloch has in the screenshots, likely an interaction with other terrain walls.

Another discovery: this happens while the token has a _vision_ of 60 ft set. If you remove that vision and instead give it a light source of 60 ft, this flicker does not occur.

[2024-06-25_15-35-55.webm](https://github.com/foundryvtt/foundryvtt/assets/31905376/64ffd0aa-79bf-45e3-bb3f-af848e38c3c7)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/30e0edff-9ed2-4724-9a87-69bc4d494a5e)

**Comment by dev7355608** [comment]
Originally reported by mathi_91: https://discord.com/channels/170995199584108546/1184176415139184731/1267609199546728489

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: windows desktop app
**Short Description of bug**: Token gets unrestricted vision on certain scene spots, either as a token stands in it or moves between certain squares. Walls works as expected in most places.
**Simple steps to reproduce the bug**: Scene Json attached. Put token on the spots indicated in screenshots. 
**Screenshots and/or console errors**:attached

Other observation: similar issue on the mirrored side of the scene, example of transition between squares reproducing the issue.

![image](https://github.com/user-attachments/assets/89c12d08-72cd-42e8-9a2f-094e1423eca7)
![image](https://github.com/user-attachments/assets/0ded34de-ed67-4d0d-8ec8-fda5f3145fff)
![image](https://github.com/user-attachments/assets/1e9acd6d-a173-4128-b56a-6d04470a4292)
![image](https://github.com/user-attachments/assets/c4f3d1b4-8aaf-4175-b604-4f6a6040fdc3)

[Scene with vision issues.json](https://github.com/user-attachments/files/16498498/Scene.with.vision.issues.json)

**Comment by dev7355608** [comment]
Originally reported by zhell9201: https://discord.com/channels/170995199584108546/1184176415139184731/1274494455113711706

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: app, chrome
**Short Description of bug**: Unrelated wall gaps can mess with visibility of tokens.
**Simple steps to reproduce the bug**: Load attached scene. Select Steve <:steve:1159234632445874308>. See that the big token to the East of it cannot be seen. Go to walls layer, move the wall (see vid) such that the "pillar" to the West of Steve cannot be seen by them. Select Steve <:steve:1159234632445874308>again, and now they can see the guy to the right. In this case it seems to be caused by the tiniest of gap in the pillar's walling.

https://github.com/user-attachments/assets/a1df0cd3-23d8-4582-8db5-f387b10c9f55

[fvtt-Scene-pillar-hall-gWisouTOytuGnXCv (3).json](https://github.com/user-attachments/files/16664355/fvtt-Scene-pillar-hall-gWisouTOytuGnXCv.3.json)

**Comment by dev7355608** [comment]
Originally reported by archmorn: https://discord.com/channels/170995199584108546/1184176415139184731/1277821500451455006

ALL MODULES DISABLED? True
OS, Hosting, Browser (if applicable): Windows 11, Foundry Cliente V12 - 331
Short Description of bug: Certain spaces of the grid reveal map and ignore wall for token vision
Simple steps to reproduce the bug: i unfortunately don't know how to reproduce it, tried everything
Screenshots and/or console errors: No console errors appear in the console but i have a video of the error and the JSON data from the scene

https://cdn.discordapp.com/attachments/1184176415139184731/1277821499595685979/Gravacao_de_Tela_2024-08-26_221655.mp4?ex=66ce8f82&is=66cd3e02&hm=583dfcaa6887bfb26dfbb43fd4300f2f959b4990a113c653cb0388207d355ea3&

[fvtt-Scene-map-0.4_-auril's-discord-l-m-uGoP3XzahD5pIvFG.json](https://github.com/user-attachments/files/16761817/fvtt-Scene-map-0.4_-auril.s-discord-l-m-uGoP3XzahD5pIvFG.json)

**Comment by dev7355608** [comment]
Originally reported by drentalbot: https://discord.com/channels/170995199584108546/1184176415139184731/1279517523624067123

**ALL MODULES DISABLED?** Yes
**OS, Hosting, Browser (if applicable)**: Chrome
**Short Description of bug**: Token loses light and vision in a specific position of the map
**Simple steps to reproduce the bug**:
1. import the scene
2. select the <:mysteryman:803758011042496552> in the bottom left
3. move one square into any direction and back
**Screenshots and/or console errors**:

**Long Description of the Issue**

I have a haunted scene where a token is emitting a light, except when it is in one specific location... the best guess what is happening is that one of the vision lines is passing two corner nodes before hitting a third wall, and when I move the token to any other position the light and vision works normally.
I am testing with no modules and a fresh import of the scene into a newly created world. Does anyone have an idea what might be happening here?

note: closing a door between 154 and 162 or moving 155 resolves the issue, for whatever reason.


I should be able to see all these, but when I move the step back again they all vanish (and a little further playing around with toher tokens that have vision shows that the light is missing)

Steps to observe the issue:

The door controls, the enemy, and the Note will appear and/or disappear.
If other tokens with Vision are on the scene that do not have darkvision, they will stop being able to see with the <:mysteryman:803758011042496552> in the starting position
If the Light on the <:mysteryman:803758011042496552> is edited to have a color, the light will be drawn normally, but the scene will not be revealed by the drawn light

~~I was unable to reproduce this issue on a local copy of this scene until I used a direct export from The Forge of this scene. I do not know if and how this changes the scene other than the path of the assets. But The issue does now appear without the Forge module, or any other modules enabled.~~
Figured out the difference that breaks it: The dim light radius of the token needs to be exactly 60 to cause the issue

reproduced with Foundry 12.331 and PF2e 6.2.3 and PF2e 6.3.1

![image](https://github.com/user-attachments/assets/a6189645-40db-4388-b46c-9451b1586282)
![image](https://github.com/user-attachments/assets/936b47b9-8ed1-4e76-b148-387d95cfca22)
![image](https://github.com/user-attachments/assets/5496b96e-1106-427c-8689-1380f3289cae)

[fvtt-Scene-a.-ghost-levels-J7nBX8gZ46YJ9mKx.json](https://github.com/user-attachments/files/16837353/fvtt-Scene-a.-ghost-levels-J7nBX8gZ46YJ9mKx.json)

**Comment by dev7355608** [comment]
Originally reported by staunch: https://discord.com/channels/170995199584108546/1184176415139184731/1282609614877098139

I've been having an issue with fog of war that I think started happening after I upgraded to V12 recently (but it could also be related to this scene specifically as the players haven't been here before). Basically sometimes while a token is moving their vision occasionally gets one frame during the movement where it seems to ignore all the walls in the scene and reveals a big circle around the token which is their max range vision. I've tried with all modules disabled and it still happens. Anyone have any idea how I can diagnose this and stop it happening?

https://github.com/user-attachments/assets/d84c2aaa-5cd7-4d8d-98cd-71ffbdc2a3ff

**Comment by dev7355608** [comment]
Originally reported by haman6762: https://discord.com/channels/170995199584108546/1184176415139184731/1284578558756388999

- Yes.
- Windows 10 Home, local.
- When moving around the map with a token, some specific spots on the grid results in a circle of fog of war being cleared, in a range of the tokens vision value.
- To replicate the bug, load a map from DungeonDraft, exported as a Universal VTT file, and remove the grid. Then have Foundry load the walls and light from the file. Then ensure all walls on the map snap to grid.  Then have token vision and fog exploration on, and global illumination off. And set the token vision range to 30 and/or 60, and vision mode to basic. Then move around the map, especially close to walls.
- An example scenario where the token on the map only moved one step up by pressing W is linked, along with an export of the scene.

![image](https://github.com/user-attachments/assets/f1c58825-3b81-4b57-81fc-c0798b4dd6f5)
![image](https://github.com/user-attachments/assets/a55f5589-f9a4-447e-99f0-9ad22f603940)
![image](https://github.com/user-attachments/assets/b534c12b-8847-45fa-9b77-90d32579e85f)

[Token Vision Bug - Scene Export.json](https://github.com/user-attachments/files/17014166/Token.Vision.Bug.-.Scene.Export.json)

**Comment by Nikkie1110** [comment]
Same issue, so adding some more material to hopefully be of use when troubleshooting.  I mostly get token vision errors when moving next to doors and only on some tokens.

https://github.com/user-attachments/assets/999311b2-18d8-4f54-b00b-8e2b47f03ff2

Example scene, token, and video of vision clipping issues.  I hope it helps
[fvtt_example_vision_clipping_token.json](https://github.com/user-attachments/files/17271084/fvtt_example_vision_clipping_token.json)
[token_vision_clipping_walls_when_next_to_door.json](https://github.com/user-attachments/files/17271086/token_vision_clipping_walls_when_next_to_door.json)

**Comment by dev7355608** [comment]
Originally reported by raveniteh: https://discord.com/channels/170995199584108546/1184176415139184731/1312559404893081750

**ALL MODULES DISABLED**? (/true - tested both modules on and off)
**OS, Hosting, Browser (if applicable)**: Foundry V12.331
**Short Description of bug**: Walls flicker and disappear when moving a token - it happens only at certain places, i.e. the one in example, rest of test grid squares work fine
**Simple steps to reproduce the bug**: Place walls and move token (I used wall mod to be able to convert drawing to walls)
**Screenshots and/or console errors**: https://cdn.discordapp.com/attachments/1184176415139184731/1312559404494749757/Foundry_Virtual_Tabletop_2024-12-01_00-15-39.mp4?ex=674ee9f4&is=674d9874&hm=59a55ade0158cb7ecd7fa0f30b69fd384bb14308011fecfdb06f530c3ed937dc&
