### ISSUE TITLE
Background image displays as pure white to users with older Mac laptops in latest Chromium builds ("White Scene" issue)

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#9957]
### What happened?

Affected users see pure white for the texture of the background image in all scenes in the latest Chromium browsers unless there is a nearby ambient light source on the screen that has its color value explicitly changed. If you place a new ambient light and pick a different Light Color, the background image displays normally as long as the light is in the screen - even if it is behind a wall or in the padding. As soon as the light isn't in the canvas, however, the white texture returns.

This issue apparently has been happening in Firefox for some time, but Chromium displayed the background image normally until very recently (possibly 116.0.5845.96, 116.0.5845.98 for sure, and is still present in .110). In at least some of these cases, the same scene displays in Safari correctly. It is currently unknown whether it displays in Electron native app properly or not (I'm almost certain it will not).

Two users updated to the latest Intel drivers available did not resolve the issue (but the latest driver versions were last released in 2021).

**Example 1** (Maggy, from a customer support email)
Example 1 with white background bug visible:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/cc87f85e-c1f1-4ad3-98b3-10407d586efd)

Example 1 with light added:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/b3fef99e-602e-4e66-89cd-ca0323405c50)

Example 1zoomed in too far to see the light again:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/c39245f9-624d-4503-acdf-da8c2fe1db01)

Example 1 Troubleshooting info:

> Foundry Virtual Tabletop: Version 11 Stable, 11.307
> Game System: pf2e, 5.3.2
> Active Modules: 0
> Performance Mode: 0
> 
> OS: Unknown
> Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[116.0.0.0](http://116.0.0.0/) Safari/537.36
> GPU: ANGLE (Intel Inc., Intel(R) HD Graphics 6000, OpenGL 4.1)
> Max Texture Size: 16384
> 
> Scene: 3300 x 2340 | Grid Size: 100 | Padding Percentage: 0.25
> Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2
> 
> Actors: 2 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
> Playlists: 0 | Compendium Packs: 77 | Chat Messages: 2

**Example 2** (Discord user Haminjars): 
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/c098f4a4-13ab-4d2c-85d3-a45bb4b0beb7)
Troubleshooting info:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/4c09f6cc-f7c3-4d1d-9347-23a703c03cfc)

**Example 3** (discord user Rogue of Legend)
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/e097ff8b-3164-4418-8fea-efc74e2cc486)
Troubleshooting info:
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/4ced978d-a39d-4948-a868-333a69822925)

> Foundry Virtual Tabletop: Version 11 Stable, 11.307
> Game System: dnd5e, 2.3.0
> Active Modules: 34
> Performance Mode: 2
> Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
> GPU: ANGLE (Intel Inc., Intel HD Graphics 5000 OpenGL Engine, OpenGL 4.1)
> Max Texture Size: 16384
> Scene: 3759 x 5213 | Grid Size: 70 | Padding Percentage: 0.25
> Walls: 61 | Ambient Lights: 5 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 20
> Actors: 127 | Items: 3 | Journal Entries: 43 | Rollable Tables: 31 |
> Playlists: 0 | Compendium Packs: 46 | Chat Messages: 60

example 4 (discord user takShaka)
https://github.com/foundryvtt/foundryvtt/assets/64667579/97571f9d-215f-4f83-ab0b-8db615034917
Troubleshooting info:

> Foundry Virtual Tabletop: Version 11 Stable, 11.308
> Game System: dragonbane, 1.2.0
> Active Modules: 25
> Performance Mode: 2
> OS: Monterrey v 12.6.8
> Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
> GPU: ANGLE (Intel Inc., Intel Iris Pro OpenGL Engine, OpenGL 4.1)
> Max Texture Size: 16384
> Scene: 1700 x 1100 | Grid Size: 100 | Padding Percentage: 0
> Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 0
> Actors: 182 | Items: 514 | Journal Entries: 49 | Rollable Tables: 201 |
> Playlists: 2 | Compendium Packs: 12 | Chat Messages: 0

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Using an affected hardware configuration*, create a new scene
2.  Define a background image and place a token with vision

**Expected**: Background image displays
**Current**: Backround image is solid white 

If you then place a new light within the screen, and change its light color, the background image will then display normally.

### What core version are you reporting this for?

Version 11.307

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
Just collecting some additional information that has been gathered since the initial issue report:

- This chrome bug may be the driving force here, some of the images posted look quite familiar to what we are seeing: https://bugs.chromium.org/p/chromium/issues/detail?id=1433650&q=component%3AInternals%3EGPU%3EANGLE%20white&can=2&sort=-opened

- Changing the backend used by the browser may help. One way of doing this for Chrome is to paste the following into the Chrome URL bar `chrome://flags/#use-angle` then selecting a different option, such as OpenGL. Note that this solution is untested on our end because we do not have access to affected hardware.

**Comment by Simyonovich** [comment]
this is STILL a problem, having half my players not seeing my maps. adjusting one light source's color value even just a tiny bit wipes the white from the screen and restores the map. please tell me there's some movement on this, as I cannot keep fixing this every time we switch scenes

**Comment by neilbenson** [comment]
I'm in the same situation, running Big Sur on a 2015 MacBook Pro. Whether I'm running a service in Docker or joining friend's game I get the same issue - I can't see background images or token using Chrome and Firefox. If I use Safari I can see them, but that has other issues (for me at least).

However, I joined a friend's game this evening and I could see the background and tokens. I was puzzled as to why before I realised he was running Foundry v9. So it seems this wasn't a problem with v9, but it is with v10 and v11. I know a lot has changed between v9 and v10, but maybe this will help.

**Comment by unsoluble** [comment]
@Simyonovich Add a 1-foot-radius light emission with a non-black color to the token of the player in question. This should fix it in all scenes they have a token in.

**Comment by Norc** [comment]
@Simyonovich Sorry that this issue continues to be a problem for you and others. 

@neilbenson , this is an upstream issue that is an interaction between Chromium-based browsers (including the Electron App) and certain older Mac hardware, and is independent of the version of Foundry. The reason why it appears to be so is simply because newer versions of Foundry come with newer versions of Electron. Viewing a map using the desktop app in V11 is affected, but last I heard V10 is not.

We are sorry about the delay in fixing... in addition to being an upstream issue, part of the problem is that we cannot reproduce this on any hardware that we have access to. What we need to help solve this problem is a volunteer who is willing to let us remotely connect to their computer and troubleshoot an affected Foundry instance directly.

If either of you or anyone else following this issue is willing to go above and beyond and let us connect to your computer in ths way, we would be very greatly appreciative, and could also offer a spare Foundry key or possibly some other Foundry content as thanks for your time and help. If this sounds like something you oculd help us with, please send me a DM and I'll coordinate logistics with you.

Sorry again for the inconvenience here... this is 100% something that is very much on our radar that we would love to get taken care of.

**Comment by neilbenson** [comment]
@Norc thanks for the detailed response. Here are my observations with browsers, all affected browsers have this issue with v10 and v11.

Chrome and Firefox: no background images or tokens
Safari: images work as expected, but has other issues (e.g. volume controls don't work)
Foundry App: works as expected

While I can run my games with the Foundry App I prefer to run Foundry in a Docker container then access in a browser, but  then I encounter the above issue. When I play a game self-hosted by a friend or in The Forge, I can't see the images unless I use Safari (but then I have the other issues).

I'd be happy to give remote access to my MacBook, the issue is going to be finding a time when we can do that. I don't have a great deal of free time at the moment and I'm in the UK so currently in BST timezone.

**Comment by Norc** [comment]
> @Norc thanks for the detailed response. Here are my observations with browsers, all affected browsers have this issue with v10 and v11.
> 
> Chrome and Firefox: no background images or tokens Safari: images work as expected, but has other issues (e.g. volume controls don't work) Foundry App: works as expected
> 
> While I can run my games with the Foundry App I prefer to run Foundry in a Docker container then access in a browser, but then I encounter the above issue. When I play a game self-hosted by a friend or in The Forge, I can't see the images unless I use Safari (but then I have the other issues).
> 
> I'd be happy to give remote access to my MacBook, the issue is going to be finding a time when we can do that. I don't have a great deal of free time at the moment and I'm in the UK so currently in BST timezone.

Our developer is UTC+2 and is quite willing to be flexible to meet up to investigate this, so if you have a window that makes sense for that timezone just let me know. The best way to coordinate would be by messaging me on discord (`norc.`) or by emailing `dan@foundryvtt.com`. Thanks again!

**Comment by neilbenson** [comment]
> I've received an interesting report that a fully updated Firefox browser is no longer seeing this issue. Can anyone here verify this, and if so, can anyone pinpoint exactly what version of Firefox the fix occurs in? That would be a huge help to us also.
> 

I've just updated my Firefox to v118.0.2 and have the same issue.

**Comment by AndreCaseyScott** [comment]
I can confirm this bug. Early-2015 Macbook, macOS Monterey v12.7. Foundry v11 hosted on a cloud server. Everything has been updated recently to their latest versions (macOS, Browsers, Foundry).

I've been using the Macbook to prep for months now with no issue. It first happened on Chrome a couple months ago, but I started using Opera GX which worked find for my purposes. Just last week Opera GX updated and now suffers the White Screen issue too. Works fine on my Windows 11 PC. Firefox also affected. 

The workaround of placing a colored light in the scene works as well. At least I can prep on my Macbook again.

**Comment by AndreCaseyScott** [comment]
Strange. I just placed a light on a map and set the color intensity to 0. The color can even be pure white. Still makes the map visible. If I turn off the light, the screen goes white again. I thought it might be connected to the Global Illumination or Token Vision settings for the Scene, but still occurs even when I turn those off. 

![Screen Shot 2023-10-11 at 22 01 49](https://github.com/foundryvtt/foundryvtt/assets/3774345/9e24d5a0-7423-4990-900d-69f882f9f5f1)

**Comment by neilbenson** [comment]
I also found that the radius of the light matters, if I am zoomed out I can see the whole map, but if I zoom in on an area of the map outside of the light radius the background disappears, so I have to make the light radius big enough to cover the map (or I guess have multiple light sources).

**Comment by Norc** [comment]
Yes, both of these observations are correct. The important thing isn't that the light has a "color" so much as that the light's color attribute isn't the default value. It can be set to anything, even #FFFFFF, so long as it is actually defined in the ambient light object. Changing the color is the only thing that matters... it doesn't matter what yo uchange it to.  Setting the color intensity to 0 is a great idea though... that way you get the workaround with even less impact to the scene.

Also, yes, the light source has to be physically present in the map canvas. It can even be behind a wall so the player cannot see it, but the player will still gain the benefit of the map background rendering properly. This is why I usually recommend having each PC token emit a small amount of light... one of those will typically always be on the scene, especially if you are a player. Adding a single ambient light in the padding of the map with a color intensity of 0 and a radius that reaches the whole map is another approach you can try, thanks for the idea.

**Comment by Norc** [comment]
> I've been using the Macbook to prep for months now with no issue. It first happened on Chrome a couple months ago, but I started using Opera GX which worked find for my purposes. Just last week Opera GX updated and now suffers the White Screen issue too. Works fine on my Windows 11 PC. Firefox also affected.

@AndreCaseyScott Yep, this issue has been spreading to the latest browsers slowly. Firefox was first affected, many months ago, then Chromium-based about a month ago, and apparently now finally Opera GX. I didn't mention Opera GX because, like Safari, it is not officially supported by Foundry and even though it bypasses this issue, other issues crop up instead. it is worth noting that Safari is not affected by this issue and likely never will be, because it is also managed by Apple and (as I understand it), this is fundamentally an issue Apple itself created as it's moving to the metal Backend.

AndreCaseyScott, we are looking for volunteers who would be willing to let us remotely control their computer temporarily to investigate this issue on an affected machine... we cannot reproduce it in house, because we do not possess affected hardware. NealBenson here has kindly agreed to help, but it will be some time before they can connect without dev and more tests are better anyway. If this is something you'd be willing to go above and beyond and help us troubleshoot, please reach out to me on discord at `norc.` or send us an email at `support@foundryvtt.com.` If not... no worries at all!

Thanks again for your confirmation and findings.

**Comment by Feu-Secret** [comment]
The problem has been identified. This is a WebGL backend bug or a GPU driver bug. The GL commands are not flushed properly in certain very rare situations. 
- This is happening in the `CanvasIlluminationEffects`. 
  - More precisely, the triggering of this bug is happening with `this.background = this.addChild(new PIXI.LegacyGraphics());`.
  - The `PIXI.LegacyGraphics()` is not properly flushed in the command chain, which is provoking the white screen.
- We believe that the "White Stairs issue" occurring on certain hardware is related to this problem.

With @dev7355608, we are working to provide a workaround.
