### ISSUE TITLE
Actors directory drag preview shows previously dragged actor's image

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9964]
### What happened?

Actors directory drag preview shows previously dragged actor's preview.

[previous-preview.webm](https://github.com/foundryvtt/foundryvtt/assets/8120158/ba817c49-3757-4db4-a8ca-e6c983c7023c)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Start drag on actor from actors directory.

On world launch, the first drag shows no preview.

Any follow-up drag shows preview for the previously dragged actor.

### What core version are you reporting this for?

11.308

This has been a bug for a long time, I thought I reported this before, but couldn't find any older report.

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Merging this comment into #2789 which is the required investment in order to fix this.
