### ISSUE TITLE
Assign _id to any unidentified NEDB documents at the time of NEDB to LevelDB migration

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#9969]
### What happened?

I have a simple compendium module (attached in zip) with a single scene. 
The scene has embedded entities like walls and lights.

When I import this scene from compendium into a v10 world, it works great.
When I import this scene from compendium into a v11 world, I don't see any of the walls or lights.

In v10, the embedded walls, lights, and other entities that don't have an `_id`, will get an `_id` created for them at import time by Foundry.
But in levelDB when the NEDB embedded entities are moved to the LevelDB database for this compendium module, there is no new `_id` created if `_id` doesn't already exist.

This can lead to the LevelDB database having a bunch of wrong keys for the embedded entities (they'll all effectively have "sceneId." but no id for the entity itself) and which could make it inaccessible

Could `_id`s maybe be defaulted to a new random `_id` on the spot, which would retain the information and behave as v10 does when importing the scene?

---
v10 compendium module with nedb database
[scene-embedded-no-id.zip](https://github.com/foundryvtt/foundryvtt/files/12468230/scene-embedded-no-id.zip)

<details>
<summary>v11 `fvtt package unpack` of compendium's scene after v10->v11 migration`</summary>

```json

{
  "name": "Forest Alchemist 1F",
  "navigation": true,
  "navOrder": 0,
  "navName": "",
  "background": {
    "src": "modules/scene-embedded-no-id/assets/Forest%20Alchemist%201F.jpg",
    "scaleX": 1,
    "scaleY": 1,
    "offsetX": 0,
    "offsetY": 0,
    "rotation": 0,
    "tint": null
  },
  "foreground": null,
  "foregroundElevation": 20,
  "thumb": "worlds/v10-dnd/assets/scenes/s9SOkdR0ApwWMTNy-thumb.webp",
  "width": 2700,
  "height": 2250,
  "padding": 0,
  "initial": {
    "x": null,
    "y": null,
    "scale": null
  },
  "backgroundColor": "#999999",
  "grid": {
    "type": 1,
    "size": 150,
    "color": "#000000",
    "alpha": 0.2,
    "distance": 5,
    "units": "ft"
  },
  "tokenVision": true,
  "fogExploration": true,
  "fogReset": 1693333514968,
  "globalLight": true,
  "globalLightThreshold": null,
  "darkness": 0,
  "fogOverlay": null,
  "fogExploredColor": null,
  "fogUnexploredColor": null,
  "drawings": [],
  "tokens": [],
  "lights": [
    null,
    null,
    null,
    null,
    null
  ],
  "notes": [],
  "sounds": [],
  "templates": [],
  "tiles": [],
  "walls": [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  "playlist": null,
  "playlistSound": null,
  "journal": null,
  "journalEntryPage": null,
  "weather": "",
  "flags": {
    "core": {
      "sourceId": "Scene.s9SOkdR0ApwWMTNy"
    }
  },
  "_stats": {
    "systemId": "dnd5e",
    "systemVersion": "2.3.1",
    "coreVersion": "10.303",
    "createdTime": 1693333563152,
    "modifiedTime": 1693333648564,
    "lastModifiedBy": "5DHrTBQ8YKZxD9AF"
  },
  "active": true,
  "folder": null,
  "sort": 0,
  "ownership": {
    "default": 0,
    "5DHrTBQ8YKZxD9AF": 3
  },
  "_id": "8fvrhlo1tFWwAajm",
  "_key": "!scenes!8fvrhlo1tFWwAajm"
}

```

</details>

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Unzip attached `scene-embedded-no-id.zip`
- Place in `Data/modules`
- Enable that compendium module in a v10 world
- Import scene successfully, see walls, lights, etc.
- Enable that compendium module in a v11 world
- NEDB data is migrated to LevelDB
- Import scene, see no walls, lights, etc.

### What core version are you reporting this for?

Version 11.308

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
@Fyorl this would be a good change to include alongside the backups release.
