### ISSUE TITLE
Certain characters being present in a filename can cause Foundry to fail to unzip it, getting stuck at 99%

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#9978]
### What happened?

Original issue:

> There's a very odd issue where a set of modules can't be installed (they're not released yet so not a huge problem right now). They download fully and install to 99% then hang indefinitely. If you refresh there are missing folders/files in the unzipped module directory and we haven't generated the signature file yet. The zip also remains in the root modules folder.
>
> There's no errors in the console, or in the node server with debugging on, no issues that I can see in the module.json file, and I don't think any issues with the original files but they're looking into that. They've also tried rezipping the module.

It turned out that the issue was resolved by renaming a file (`Michaël-Ghelfi-The-Full-Music-Discography-11-Of-Fire-And-Steam`) to not include the umlaut over the e but this is something we should consider hardening in the core software.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Include a file with the umlaut e in a module and install it using the package manager. It should hang at 99% infinitely.

### What core version are you reporting this for?

11.308

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by kvndrsslr** [comment]
This is likely very tool specific.
I think you guys use AdmZip, we do too.
Here is the related issue, not sure what to make of it without any further testing:
https://github.com/cthackers/adm-zip/issues/255

**Comment by Fyorl** [comment]
This appears to have been fixed with our move to `unzipper`.
