### ISSUE TITLE
When certain data is present, migrating to both  the latest DND5E and PF2E system gives a "name is undefined" error, leaving world in an unlaunchable state 

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#9979]
### What happened?

This (rare) issue has been seen in both 5E and PF2E worlds so far. It has only started occurring in the past week with the release of 11.308 (and subsequent release of Game Systems that are designed to work with 11.308, which may be more relevant).

When this issue occurs, the world becomes unlaunchable, throwing the following in the console when attempted:

`World launch failed: Actor [exBnueQsZ8KrrDGP] validation errors: name: may not be undefined. See the console (F12) for more details.`

The solution has been to downgrade the game system to a state where the world can be launched, and then renaming or, more often, deleting the actor with the given ID. Typically (but not always?), the actor itself has a valid name, and  it is an effect or item on it perhaps that is throwing the issue. Alternately, it can be a synthetic copy of that actor that has the invalid name.

I'm not sure if one or more issues is actually at work here: 

1) what mechanism is causing these actors (or the effects / items on them) to get into an invalid state that gives the "name is undefined" error? (could well be modules (VERY maybe tokenizer?) and not a core issue)
2) Why is this type of data causing the world migration to fail so badly that the world is unlaunchable afterwards due to a single actor? Should / can this be handled more smoothly?
3) Why is this issue happening now, seemingly starting with 11.308 (and matching PF2E / 5E game system releases)? 
4) Does the world migration failure have anything to do with the massive number of warnings with the same message? Example: here https://discord.com/channels/170995199584108546/670336046164213761/1146104547031400548 (zip file is available).

I have two world zip files of this issue occurring so far, but I don't want to attach user data to a public ticket. I'm particularly interested in getting non-PF2E test data.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Have a world with certain underlying data (two test worlds available, unfortunately, I don't have a 5E test world yet)
2. Using 11.308 and a pre-11.308 release of that system (PF23 5.2.3, for instance), open the world.
  The system migrates as expected, but throws errors for the existing invalid data  
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/c0035dc2-dbb8-4534-903d-d1c4ba32d1b6)
3.  Upgrade to latest version of system (for example, PF23 5.4)
4. Attempt to open the world again
**Current results**:
The world fails to open out of the Setup screen:
, hanging at around 50% ish of loading Package Data
![image](https://github.com/foundryvtt/foundryvtt/assets/64667579/3b66e3c0-00dd-4f03-8be9-012c9d2a22f4)

Reverting to a pre-11.308 version of the game system allows the world to launch and be repaired.

### What core version are you reporting this for?

11.308

### Relevant log output

```shell
World launch failed: Actor [exBnueQsZ8KrrDGP] validation errors: name: may not be undefined. See the console (F12) for more details.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by zoble** [comment]
Getting this with a 5e campaign. Following in case a solution is found before I downgrade.

**Comment by Norc** [comment]
> Getting this with a 5e campaign. Following in case a solution is found before I downgrade.

Hi @zoble! Please backup your world instructions here (https://www.youtube.com/watch?v=OmbxMmqNNXU). The fix is currently pretty simple... after baclomg up, please just install 11.307 and your world should open normally (though you may see some odd errors in there still). If you email support@foundryvtt.com or go to the #troubleshooting channel in our excellent community discord (https://discord.gg/FoundryVTT), we'd be happy to help you through the full process including fixing the underlying data issue if you like. Feel free to ping me (Norc).

Additionally, if you could send us the `Data\worlds\<world with issue>\data` folder either via email or discord PM to me, we'd be much obliged. I currently don't have a test DND5E world and I would love to test our potential fix against your world to verify it.

Thanks, and sorry again you hit this snag.
