### ISSUE TITLE
Websocket Connection Failed -- works in Incognito

### ISSUE THREAD

**Issue by whenbearsreign** [foundryvtt/foundryvtt#9986]
### What happened?

Currently, my set-up is running FoundryVTT in a Docker container on an Ubuntu VM. When using Chrome (Version 116.0.5845.180), I am met with "websocket connection to XXXXX failed". It loads the splash page, but no login screen.

However, as title states, it works in Incognito and other web browsers (tested Safari and Firefox)

My connection is done through a Cloudflare Tunnel with HTTPS, certs applied with env variables in container for SSL.

```shell
---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry-vtt
    volumes:
      - ./Data:/data
      - ./ssl:/data/ssl
    environment:
      - FOUNDRY_PASSWORD=XXXXXXXXXX
      - FOUNDRY_USERNAME=XXXXXXXXXXXXXXX
      - FOUNDRY_ADMIN_KEY=XXXXXXXXXXXX      
      - FOUNDRY_SSL_KEY=/data/ssl/key.pem
      - FOUNDRY_SSL_CERT=/data/ssl/cert.pem
      - FOUNDRY_COMPRESS_WEBSOCKET=true
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
``` 

To test if it was the Docker image, I installed on a new Debian VM with .zip installation and PM2, and got the same result.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Redeployed with env variable "FOUNDRY_COMPRESS_ WEBSOCKET=true"
- Fresh install of Foundry on Debian machine, same Cloudflare Tunnel setup with new IP (no SSL certs)

### What core version are you reporting this for?

Version 11 (Build 308)

### Relevant log output

```shell
_______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:91630 Foundry VTT | Reestablishing existing session 296bf4017e5aae29e4ad3d60
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
s @ manager.js:39
Pt @ index.js:29
(anonymous) @ foundry.js:8443
connect @ foundry.js:8442
create @ foundry.js:8429
window.addEventListener.once @ foundry.js:91638
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
websocket.js:44 WebSocket connection to 'wss://XX.xxxxx.org/socket.io/?session=296bf4017e5aae29e4ad3d60&EIO=4&transport=websocket' failed: 
value @ websocket.js:44
value @ transport.js:45
value @ socket.js:164
a @ socket.js:105
value @ manager.js:108
(anonymous) @ manager.js:331
```

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
If you are able to reproduce this issue outside of a Docker-hosted environment we can assist you further, but there is no confirmed issue with incognito mode and Foundry VTT websocket connections on the range of hosting options we support (self-hosted, cloud hosted via nginx, etc...). We do not offer support for docker environments, so unless this issue is reproduced in an environment we do support there is not any assistance we will be able to provide.

**Comment by aaclayton** [comment]
Can you share some more details about your environment? Are you using a reverse proxy server like nginx/caddy/apache/etc? Is there any other software or hardware feature of your environment that could be a factor for limiting connectivity?

**Comment by whenbearsreign** [comment]
> Can you share some more details about your environment? Are you using a reverse proxy server like nginx/caddy/apache/etc? Is there any other software or hardware feature of your environment that could be a factor for limiting connectivity?

Sure thing. Environment is an Proxmox LXC virtual container running Debian 12. I am using Cloudflare Tunnels for DNS, no other reverse proxy set up. Other services I run using Cloudflare Tunnels seem to work without issue, and as stated in the original post, it seems to work only when I am in Incognito mode or in a different web browser.

**Comment by Matt-BW** [comment]
I have the same issue whilst trying to migrate one of my worlds in both debian and ubuntu environments.  All the the others seemed quite happy and migrated quickly. One though is just refusing.

I copied the folders to a mac hosted one and it migrates to 11.313 quickly. Hoping I can find a way to copy it back.

**Comment by Khitiara** [comment]
having the same issue exactly, no docker, running on windows, foundry 12.331, running behind nginx behind cloudflare
